### ISSUE TITLE
RFC: Do we need Installation page in docs?

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1004]
In the official documentation, we have an installation page: http://loopback.io/doc/en/lb4/Installation.html.  I'm not sure whether we need the section for `Adding LoopBack 4 to an existing project`, because we highly recommend users to scaffold a LB4 app using CLI.

I have 2 proposals:
### Option 1 ### 
- Remove the installation page completely
- the prerequisite of installing Node already exists in [Getting Started page](http://loopback.io/doc/en/lb4/Getting-started.html). 

### Option 2 ###
- Keep the installation page
- Remove `Adding LoopBack 4 to an existing project` section
- Move [Install LoopBack 4 CLI](http://loopback.io/doc/en/lb4/Getting-started.html#install-loopback-4-cli) instruction from Getting Started to Installation page

related to: https://github.com/strongloop/loopback-next/issues/988

**Comment by kjdelisle** [comment]
Option 1 :+1:

**Comment by virkt25** [comment]
+1 for Option 1

**Comment by jannyHou** [comment]
+1 for Option 1:
restrict all issues open against the template generated by our cli, we may not want to triage and debug for any random apps....

**Comment by raymondfeng** [comment]
+1 for Option 1. In http://loopback.io/doc/en/lb4/Getting-started.html, we probably should recommend to use a tool like `nvm` for Node.js installation.

**Comment by virkt25** [comment]
I don't think we need to recommend `nvm` because we require Node 8 anyways ... and if a user has a need to use multiple versions on their machine I'm sure they would've come across `nvm` or one of the other solutions. If we get questions about it, then it might be worth adding it to a FAQ / something but Getting Started should be as simple as possible.

**Comment by dhmlau** [comment]
@bajtos, thoughts?
