### ISSUE TITLE
Rework markdown documentation scripts

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#1019]
[Tentative]

blocks #729 

## Overview
The current loopback.io scripts for our documentation will pull in READMEs without issue, but they are limited in their ability to parse other Markdown documents at top-level or in subdirectories.

As a result, we are unable to pull in documentation from things like the `example-getting-started` repository in a way that mimics the current setup in GitHub for our own documentation

Examples of problems include:
- Links becoming broken after import and conversion to HTML (docs paths don't correspond to resulting Liquid templating paths)
- Every single document that needs to be parsed must be added to the scripts (this could quickly grow out of control with respect to tracking and management of sourced documentation)

To correct this, we should change the scripts so that we can:
- source a common target by convention from an existing repository (ex. `docs` folder)
- _generate_ the include files ([for reference, this is an include file](https://raw.githubusercontent.com/strongloop/loopback.io/gh-pages/pages/en/lb4/Creating-decorators.md))
- organize our include files in directories that mirror their source package structure to make maintenance and manual navigation easier

## Acceptance Criteria
-- todo --

cc @raymondfeng @bajtos  @dhmlau

**Comment by kjdelisle** [comment]
I think this should be MVP given that it will directly affect how we create our documentation. More importantly, I'm already feeling the effects of not having this sorted out, as it's making the organization of documentation a painful and messy affair, rather than something that can easily be handled in neat, self-contained pull requests.

I won't tag the issue until I've heard some feedback, though.
cc @strongloop/sq-lb-apex

**Comment by virkt25** [comment]
This work will definitely help now and with future doc work so +1 for it being done sooner rather than later.

**Comment by shimks** [comment]
Tracked by https://github.com/strongloop/loopback.io/pull/643, could you please confirm @b-admike ?

**Comment by virkt25** [comment]
Closing as done. This was addressed via https://github.com/strongloop/loopback.io/pull/643
