### ISSUE TITLE
Model Relations Preview

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1032]
Assumption: Maintain 1-to-1 relationship between model and datasource due to juggler constraint

## DP3 scope

- Show the programming model, gather feedback.
- must have: HasMany relation
- stretch goal: BelongsTo relation

## Out of DP3 scope
- Additional relation types (HasAndBelongsToMany, polymorphic & embedded relations, etc.)
- Composite keys
- CLI tooling

**Comment by dhmlau** [comment]
Extracting the to-do list from #995, I've created the following tasks:

- hasMany: doc + blog #1351
- Inclusion of related models (same as LB3) #1352
- Infer target repository when related models are backed by the same datasource, otherwise let user explicitly provide the target repository  #1353
- Use relational decorators' metadata to construct constrained target repository instance on relational properties #1354 
- Refactoring: Remove execute function out of Repository interface and into its own interface for arbitrary SQL commands. #1355
- Refactoring: Split Repository interface into different interfaces based on the persistence function type i.e. LookupRepository interface to have all the Retrieval methods, WriteRepository (I'm sure there is a better name), would have the create methods, MutationRepository might have the update and related methods (this might fall under the previous one), and DestroyRepository for deletes.  #1356 
- incorporating relations in existing examples or creating a new example #1358

**Out of scope for DP3**
- Scoping for single models: https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#scopes #1360
- CLI command lb4 relation or the likes to wire up related models (think of LB3) #1359

**Comment by bajtos** [comment]
In the past (https://github.com/strongloop/loopback-next/issues/995#issuecomment-389549293), I wrote:

> We need a vision of how to iteratively deliver small increments of functionality, where each increment is something that our users (LB4 app developers) can start using. In our call, we were discussing the first smallest step. IIRC, it was HasMany with a single operation find, covering both repository/persistence and REST API in a controller method. The next step as I remember it: add create method to repository/persistence layer and expose it in REST API as a new controller method. After that, I think we can go wider - one task can be adding all remaining HasMany methods, another task can be BelongsTo. Many of the tasks you listed make sense to do after those two initial tasks are done. Some of them should be probably done as part of those two initial tasks. For example, "remove execute" and "split Repository interface" - I think that should be done in the extent needed by those baby steps.

@dhmlau The task list above does not provide those small increments of functionality. I am proposing to add the following stories, where the first story should be already in progress by @b-admike:

 1. HasMany with a single operation find, covering both repository/persistence and REST API in a controller method. 
 2. Add create method to repository/persistence layer and expose it in REST API as a new controller method.
 3. Add all remaining HasMany methods.

 #1355 and  #1356 may partially overlap with those three new stories. It's ok to keep the around as 
a reminder to verify that the changes were indeed made as part of those three vertical increments outlined above.

**Comment by dhmlau** [comment]
closing as done.
