### ISSUE TITLE
Integration with REST / SOAP services (weakly typed)

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1036]
Per discussion with @raymondfeng @kjdelisle, 
Integration with REST / SOAP can be divided into:
    - weakly typed integration
    - strongly typed integration (**stretch goal for GA**)

## Overview
Common characteristics for REST and SOAP services
- no fixed set of operations. operations are derived from the service spec (swagger / wsdl / openapi). Not the typescript implementation of the operations/interfaces
- we don't have typescript definition for the interfaces/operations

## Spikes
- Weakly typed integration:  #1069 
- Strongly typed integration: #1070 

## Additional requirement
- service information might need contextual info, e.g. security token and tracing id, which pass to the downstream.  -- when you're calling one service to another.  If we have this ability, then we can have the distributive tracing - part of the Cloud Native microservice experience.
- We might want to give flexibility to the developers to intercept the service invocation so that it can help to mediate request and response.

## DP3 scope

- [x] Leverage existing LoopBack 3.x connectors (soap, rest, swagger, gRPC)
- [ ] Need to figure out testability+ document it (see #1311)

## Out of DP3 scope:
- auto-generated .d.ts definitions
- CLI tooling

**Comment by raymondfeng** [comment]
There are a few different styles to invoke a service. For REST, they are:

1. Use a generic http client library such as [request](https://github.com/request/request) or [axios](https://github.com/axios/axios)
2. Use the spec driven approach, such as [swagger-client](https://github.com/swagger-api/swagger-js) and `loopback-connector-swagger`
3. Use the template driven approach, such as `loopback-connector-rest`

4. Use the decorator approach, we can inspect the controller class with openapi decorations and use the metadata to adopt 2. It could be interesting to use the skeleton controller class with decorations as a way to describe REST contracts (TS interfaces don't allow decorations)
5. Use the code-generation approach, such as [openapi-client](https://github.com/jhthorsen/openapi-client)

1, 2, 3 are weakly-typed while 4, 5 are strongly-typed.

**Comment by bajtos** [comment]
Done as far as the DP3 release is concerned.
