### ISSUE TITLE
Extension: Logging

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1037]
Per discussion with @raymondfeng @kjdelisle 
- This is for general logging & debugging for application developers and LB runtime.
- Currently the error is not informative.  We need to ask people for reproduction sandbox instead of trying to figure out what's happening by reading the logs.
- This is along the line with serviceability, e.g. First Failure Data Capture (FFDC)
- Need spike on how to instrument our codebase to use third-party modules

**Comment by bajtos** [comment]
Possibly related: https://github.com/strongloop/loopback-next/pull/4117
