### ISSUE TITLE
Lifecycle (start/stop)

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1039]
Based on discussion with @raymondfeng @kjdelisle 
- need to have minimal lifecycle to ensure we have graceful startup and shutdown
  - e.g. database connection, other connectors that hold resources 
  - we need to have a way to stop the connection
  - currently app.start only does it for REST server

**Comment by bajtos** [comment]
@raymondfeng  now that your pull request #1928 has been landed, is there anything else we should work on as part of this epic?

**Comment by bajtos** [comment]
Closing as done by https://github.com/strongloop/loopback-next/pull/1928.
