### ISSUE TITLE
First version of the API documentation

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#104]
A way for us to reflect the changes in the source code to an online version. Doesn't need to be 100%, just something working.

- [ ] Discussion
- [ ] Whether we or throw it up or not

https://strongloop.github.io/loopback-next-apidocs/

**Comment by ritch** [comment]
how is this blocked?

**Comment by rashmihunt** [comment]
This item is not ready to be worked on yet because,
- Depends on @mpatsute work item which is the tool to create API doc from type scripts in strong-doc tooling
- We don't have all the information regarding most important APIs

**Comment by crandmck** [comment]
Closed in favor of https://github.com/strongloop-internal/scrum-asteroid/issues/230
