### ISSUE TITLE
Minimum functionalities required 

### ISSUE THREAD

**Issue by arash01** [strongloop/loopback-next#1048]
Just wanted to share a thought after using loopback-next for a while.

I know so far you've focused on developers who create extensions for lb4 but I would say you need to satisfy other developers who use loopback-next as API services as well. I think you'll find difficult to encourage developers to write extensions for your framework without having actual users on the platform.

This means you need to release minimum functionalities asap to catch up with other nodejs frameworks. Personally I am still waiting to see model relations and calling external (APIs) functionalities in your framework to continue using lb4 for my personal projects.

**Comment by bajtos** [comment]
Thank you @arash01 for the feedback.

> you need to satisfy other developers who use loopback-next as API services as well

We are fully aware of that! Our next big release is going to target API server/application developers, see https://github.com/strongloop/loopback-next/issues/696 

> model relations

This is on our roadmap (although beyond MVP/Walking Skeleton), see the following issues:
 - https://github.com/strongloop/loopback-next/issues/419
 - https://github.com/strongloop/loopback-next/issues/812
 - https://github.com/strongloop/loopback-next/issues/995

> calling external (APIs) functionalities

We know this is important to support in LoopBack Next, however this feature is quite far down our backlog right now. 

 - https://github.com/strongloop/loopback-next/issues/451
 - https://github.com/strongloop/loopback-next/issues/522

I am closing this issue as it's not really actionable.
