### ISSUE TITLE
loopback-next does not export a main script

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#105]
users will not be able to access the package because a main script is not exposed

Can't "require('loopback-next')" via JavaScript.

**Comment by superkhau** [comment]
This has been addressed, users can do this via `const Application = require('@loopback/core').Application` or `import {Application} from '@loopback/core'` now. See https://github.com/strongloop/loopback-next/wiki/Hello-world for more info. Closing.
