### ISSUE TITLE
Add shortcut tests for @param

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#1052]
Add shortcut tests for 
@param.query.*
@param.header.*
@param.path.*

Take shortcuts `@param.header.*` as an example, the current test cases can be found in https://github.com/strongloop/loopback-next/blob/master/packages/openapi-v3/test/unit/decorators/param/param-path.decorator.unit.ts

The missing ones are:

- @param.path.long
- float
- double
- byte
- binary
- date
- datetime
- password

And add the same missing tests for @param.query.* and @param.path.*

Acceptance Criteria:

- [ ] Add missing shortcut test case for @param.header.*
- [ ] Add missing shortcut test case for @param.query.*
- [ ] Add missing shortcut test case for @param.path.*

**Comment by shimks** [comment]
Tagging this with #753

**Comment by shimks** [comment]
Tagging this with #753

**Comment by shimks** [comment]
@jannyHou Could you update the issue with an appropriate acceptance criteria? Thanks

**Comment by jannyHou** [comment]
@shimks Updated :)

**Comment by jannyHou** [comment]
PR merged
