### ISSUE TITLE
Production deployment/logging/monitoring

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1054]
Cross posting from @bajtos ' comment:

> production deployment, monitoring and logging; ideally using IBM Cloud as the target platform for our demos and to help us prioritize different aspects of production readiness. This topic involves questions like:

> - How do I modify behavior of my LoopBack4 application in production, e.g. modify error responses to not leak any sensitive data?
> - How do I configure database connection strings, access credentials, port number to listen on, etc. for my LoopBack4 application?
> - How can I secure my application? (This overlaps with the existing epic of Authentication/authorization/security.)
> - How do I monitor behavior of my LoopBack application in production, what useful insights can I get on top of usual low-level Node.js metrics?
> - How can I upgrade my applications with zero downtime? Is there anything special needed to enable blue/green deployments?
> - Where can I find logs from my app? How can I produce my own log entries from my custom code (e.g. controller methods)?

In addition, we need to be able change to use different config json based on the NODE_ENV. https://loopback.io/doc/en/lb3/Preparing-for-deployment.html#configuration-for-deployment.  
  - Need to add support for `server/config.production.json`, `server/component-config.production.json` and `server/datasource.production.json`

**Comment by dhmlau** [comment]
see https://github.com/strongloop/loopback4-example-shopping/tree/master/kubernetes

**Comment by raymondfeng** [comment]
A blog is being developed - https://github.com/strongloop/strongloop.com/pull/227

**Comment by dhmlau** [comment]
Closing as done. The blog is scheduled to be published.
