### ISSUE TITLE
[API Explorer] POST requests against API fail

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#1055]
## Reproduction

- Run the `example-getting-started` application
- Go to http://loopback.io/api-explorer/?url=http://localhost:3000/swagger.json to browse your API.
- Using the POST command, attempt to create a new Todo instance
- **Expected to see 200 OK**, but received `TypeError: NetworkError when attempting to fetch resource`

cc @raymondfeng 

If no one else gets to this one, I'll do it once I've finished with the documentation for example-getting-started.

**Comment by shimks** [comment]
Is this caused by not setting CORS?

**Comment by kjdelisle** [comment]
@shimks @raymondfeng  Are we not allowing CORS from loopback.io by default?

**Comment by virkt25** [comment]
We do allows CORS from all domains using the `rest` package but CORS implementation is incorrect, in that we don't automatically answer the HTTP `OPTIONS` request for a `POST` request that a browser normally performs as a pre-flight check for CORS. 

Fix will be to get the Swagger Definition we have and automatically answer `OPTIONS` request so pre-flight requests don't fail.
