### ISSUE TITLE
Fix api doc http://apidocs.loopback.io/#LoopBack4

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#1060]
### Description

The api docs for LoopBack 4 packages are not working. 

http://apidocs.loopback.io/#LoopBack4

**Comment by shimks** [comment]
tracked by https://github.com/strongloop/loopback-next/issues/989, close if necessary

**Comment by jannyHou** [comment]
thanks @shimks ! Sorry I didn't realize there is well groomed one already, searched for a wrong key word(jsdoc)
