### ISSUE TITLE
`@loopback/testlab` does not export should-sinon

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1063]
In order to inquire about how stubs or spies, `should-sinon` need to be imported but `testlab` does not make this module available for users to use.

An example in our docs imports from `testlab` and uses one of the assertions from the module, so I think it should be made available to be imported under the same namespace as `expect`. See http://loopback.io/doc/en/lb4/Testing-your-application.html#unit-test-your-controllers

**Comment by virkt25** [comment]
It used to be exported but we had issues with it and hence it was removed. That documentation should be updated till we get around to fixing the issue. 

Issue: https://github.com/strongloop/loopback-next/issues/641
PR removing export: https://github.com/strongloop/loopback-next/pull/665

**Comment by shimks** [comment]
I didn't know there was already an issue to go with this problem. Thanks @virkt25! Closing since it is a duplicate to #641 and has a valid workaround.
