### ISSUE TITLE
Modify commit linter to reject fixup! and squash! commits

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1078]
Right now, our commit linter accepts commits starting with `fixup!` and `squash!` prefix. As a result, it's easy to miss the fact that git history requires cleanup, and land such commits directly on a protected branch (typically `master`).

I am proposing to change our commit linter to reject such commits.

Example:
 - https://github.com/strongloop/loopback-next/pull/1050/commits
 - https://travis-ci.org/strongloop/loopback-next/jobs/347713734

```
⧗   input: fixup! change ctx.getValueOrPromise to return ValueOrPromise
✔   found 0 problems, 0 warnings
⧗   input: feat(context): add type as a generic parameter to `ctx.get()` and friends
✔   found 0 problems, 0 warnings
```

**Comment by virkt25** [comment]
`commitlint` doesn't have support right now to disable the git messages. It's a feature. Though from looking at a issue in their repo, they would be open to someone adding a feature to allow an override for the wildcards used.

Automatic Ignores: https://github.com/marionebl/commitlint/blob/master/%40commitlint/is-ignored/src/index.js

Relatied Issue in Commitlint: https://github.com/marionebl/commitlint/issues/60
