### ISSUE TITLE
Discuss: Use turbo-http instead of native http module

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1083]
Quoting from https://github.com/mafintosh/turbo-http:

> WIP, this module is already really fast but there are some HTTP features missing and easy perf gains to be had.
> On my laptop I can serve simple hello world payloads at around 100k requests/seconds compared to 10k requests/second using node core.

Should we consider switching our REST layer to turbo-http when the library becomes more stable?

**Comment by raymondfeng** [comment]
If we agree on the approach proposed by https://github.com/strongloop/loopback-next/pull/1082, the http implementation can be pluggable for LoopBack 4.
