### ISSUE TITLE
[SPIKE] Add Code Climate Tool

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1087]
**Timeboxed 1-2 days**
# Description/Steps to reproduce

An interesting tool that I think we might benefit from in terms of better code quality. Checks for duplicate code, refactoring possibilities, etc. along with test coverage. 

https://codeclimate.com/product/

**Comment by dhmlau** [comment]
Let's do a spike and to get more information on how it can help us.

**Comment by raymondfeng** [comment]
-1. There is no free-tier: https://codeclimate.com/quality/pricing/

**Comment by sbacem** [comment]
Free for open source

**Comment by raymondfeng** [comment]
@sbacem Thank you for clarifying. I didn't notice the `fine print` (**Free for open source. Forever.**). It's surprising that the project does NOT highlight it.

**Comment by bajtos** [comment]
I don't know much about CodeClimate. What I would like as the outcome of this spike, is some sort of a demonstration showing us how we can benefit from CodeClimate in our day-to-day work. It would be even better to show a problem we already have in our code base that we are not aware of but which is highlighted by CodeClimate.

The second part of the spike should explore downsides of integrating CodeClimate. How much longer our `npm test` and CI builds are going to take? What other issues we may run into?

**Comment by virkt25** [comment]
My initial proposal was because I saw some demos of CodeClimate and they are capable of providing powerful analysis in code maintainability, refactoring possibilities, test coverage, etc. 

Just saw they are also testing (beta) features to identify bottlenecks in projects by showing how long a PR is in review, how long it takes to merge, etc. That said I'm not sure of the value the beta features might add. 

I'm not sure how a spike can take place on an integration such as CodeClimate. I think the best approach would be to add this to the repo (NOT A REQUIRED CHECK -- so no impact on waiting for it to finish) for a trial period of a month so everyone can explore the tool and then we can decide if it's worth keeping or not.

**Comment by jannyHou** [comment]
> I think the best approach would be to add this to the repo (NOT A REQUIRED CHECK -- so no impact on waiting for it to finish) for a trial period of a month so everyone can explore the tool and then we can decide if it's worth keeping or not.

+1 for giving it a try 👍

**Comment by dhmlau** [comment]
It sounds appealing if we could get more information on https://codeclimate.com/velocity/

**Comment by dhmlau** [comment]
seems like we're good with this spike.  Moving this to backlog.

**Comment by bajtos** [comment]
FWIW, CodeClimate offers code coverage too - see https://codeclimate.com/quality/. Once we decide to keep using CodeClimate, it may be better to switch off Coveralls.

**Comment by dhmlau** [comment]
I believe this is done.  
@virkt25 has shown me the code climate velocity (not the quality one).  Seems likes a good tool to know the bottlenecks and each team member's github activity categorization.

**Comment by bajtos** [comment]
> I believe this is done.
> @virkt25 has shown me the code climate velocity (not the quality one). Seems likes a good tool to know the bottlenecks and each team member's github activity categorization.

@dhmlau 

A spike is not done until there are follow-up stories with enough details that the team can estimate then. Unless we decide to not pursue Code Climate based on learnings from the spike?

**Comment by dhmlau** [comment]
That's true.  @virkt25 , could you please schedule a spike discussion meeting? Thanks.

**Comment by virkt25** [comment]
I'm not sure a meeting is warranted for this spike. I had added CodeClimate Quality to `loopback-next` but didn't get around to setting up the test coverage tool they offer since that requires a bit more effort than just the Quality tool. 

You can see the tool here: https://codeclimate.com/github/strongloop/loopback-next/builds

As for the spike results, from when it was working I made the following observations:
- Some of the refactor stuff was good but often missed details such as a single different parameter. Or two similar loops in two different packages which it would suggest to refactor.
- The tool is great but most of that analysis seemed to me like a `won't fix` as the tool isn't exactly optimized for monorepos.

Currently the tool isn't working because of how our `tslint` is configured vs. the version they are using or something. No settings for me to change / control that. 

![image](https://user-images.githubusercontent.com/3311536/45431617-0faa1100-b676-11e8-96ff-87fa1f1ca76d.png)

My proposal would be to not use this tool for code quality purposes since it doesn't play nice with monorepos. I am however still interested in a code coverage tool as the current one seems to fluctuate based on `.md` changes for some reason. -- But also not sure we can rely on code coverage as right now we can't even get `tslint` step to pass.

Given the above findings I'm not sure if it's worth having a spike meeting for this / what the next steps are for this. I can book one if the team is interested. cc: @dhmlau @bajtos @strongloop/sq-lb-apex

**Comment by bajtos** [comment]
> My proposal would be to not use this tool for code quality purposes since it doesn't play nice with monorepos. 

Sound like a reasonable conclusion to me.

We can come back to CodeClimate later in the future and check if they improved their support for monorepos yet.

**Comment by virkt25** [comment]
Closing this issue for now.
