### ISSUE TITLE
Example tests failing

### ISSUE THREAD

**Issue by zbarbuto** [strongloop/loopback-next#1088]
# Description/Steps to reproduce

Run the following commands:
`lb4 example getting-started`
`cd loopback4-example-getting-started`
`npm install`
`npm test`

All the endpoint tests fail with 404 errors.

This seems to be a result of the recent update to openapi-v3.

**Comment by zbarbuto** [comment]
It actually seems to be the result of a dependency not published as if you run the tests in the monorepo they work:

1. run lerna bootstrap and then cd into the example-getting-started folder
2. run `npm test` - all tests pass
3. clean the repo and copy the `example-getting-started` into an isolated folder
4. `npm install && npm test`
5. tests fail again

**Comment by jannyHou** [comment]
@zbarbuto I am trying `lb4 example getting-started`, will let you know soon

**Comment by zbarbuto** [comment]
I managed to get it working by running `npm pack` on all the dependencies in this repo from `master` and installing them from the `gzip` files one by one - so it's almost definitely just something that isn't published to npm yet, hence why the monorepo tests still work.

**Comment by jannyHou** [comment]
@zbarbuto I run `npm i -g @loopback/cli` and then `lb4 example-getting-started`, the generated app's `package.json` is still on v2, see `dependencies`: 

```
"@loopback/context": "^0.1.0",
    "@loopback/boot": "^0.1.0",
    "@loopback/core": "^0.1.0",
    "@loopback/rest": "^0.1.0",
    "@loopback/openapi-v2": "^0.1.0"
```

Could you post your dependencies' versions here? I want to see is it using `openapi-v2` or `openapi-v3`

**Comment by virkt25** [comment]
Good catch! `lb4 example` copies the code from `master` but the dependencies installed are from the last release. oas3/upgrade PR changed the project to OAS3 but we haven't released a new version hence the issue. The upgrade included changes to the `@loopback/rest` module. We'll do a release shortly to address this issue :)

**Comment by zbarbuto** [comment]
@jannyHou Slightly different command - I ran `lb4 example getting-started` not `lb4 example-getting-started`

@virkt25 Awesome, Thanks! I thought that might be the case.

**Comment by jannyHou** [comment]
@virkt25 Great catch, thank you!

**Comment by virkt25** [comment]
A new release was published. I've verified the tests now pass for `getting started` after cloning it using `lb4 example`. @zbarbuto you can close the issue once you've verified.

**Comment by zbarbuto** [comment]
Working for me now. Thanks, guys.
