### ISSUE TITLE
Todo example getting 404 error

### ISSUE THREAD

**Issue by vijeta-singh** [strongloop/loopback-next#1090]
Hi Everyone,

I am trying to learn loopback 4 so I have started with the to-do example.
https://github.com/strongloop/loopback-next/tree/master/packages/example-getting-started

I have removed all api call , i have just get and post.
Get is working fine but on post request I am getting 404 error.
OPTIONS http://localhost:3000/todo 404 (Not Found)
Failed to load http://localhost:3000/todo: Response for preflight has invalid HTTP status code 404.
```ts
import {get, post, param} from '@loopback/rest';
import {HttpErrors} from '@loopback/rest';
import {TodoSchema, Todo} from '../models';

import {inject} from '@loopback/core';
import {repository} from '@loopback/repository';
import {TodoRepository} from '../repositories/index';

export class TodoController {
    repository: TodoRepository;

    constructor() {
        this.repository = new TodoRepository();
    }

    @get('/hello')
    hello(): string {
      return 'Hello world!';
    }


    @get('/todo')
  async findTodos(): Promise<Todo[]> {
    return await this.repository.find();
  }

  @post('/todo')
  async createTodo(
    @param.body('todo', TodoSchema)
    todo: Todo,
  ) {
      console.log('inside post');
    // TODO(bajtos) This should be handled by the framework
    // See https://github.com/strongloop/loopback-next/issues/118
    if (!todo.title) {
      return Promise.reject(new HttpErrors.BadRequest('title is required'));
    }
    console.log('after if');
    return await this.repository.create(todo);
  }

  }
```

Please let me know how I can fix this issue.

Thanks

**Comment by virkt25** [comment]
Duplicate of https://github.com/strongloop/loopback-next/issues/1088

**Comment by shimks** [comment]
We've just upgraded our `rest` server to use `openapi-v3` package, which deprecates `@param.body` decorator. Please use `@requestBody()` instead and let us know if that worked out for you.

**Comment by virkt25** [comment]
related to https://github.com/strongloop/loopback-next/issues/1055

**Comment by vijeta-singh** [comment]
I tried this code 
@requestBody({type:'object',  
    acceptedTypes: ['application/json', 'application/xml'],shemaSpec: TodoSchema
  })

But now in api explorer I am not getting option to pass parameter.
Can you give me an example with Todo schema how I can use @requestBody.

Thanks again Shimks.

**Comment by shimks** [comment]
Try using `@requestBody()` without any arguments. What this should do is automatically generate a schema for `Todo` model as long as it's been decorated with `@model` and `@property`.

Let me know if that works out for you :)

**Comment by kjdelisle** [comment]
@vijeta-singh 
Your request body object used in the `@requestBody` decorator doesn't look like it complies with the OpenAPI v3 specification for [Request Body Objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#requestBodyObject).

I would definitely go with @shimks ' suggestion, though.

**Comment by virkt25** [comment]
> Response for preflight has invalid HTTP status code 404

This should now be fixed with the latest release of `@loopback/rest` which adds support for CORS. Can you please give this another try using the latest version of LoopBack 4. 

I'd also suggest starting with a fresh copy of `getting-started`, you can run `lb4 example` to create a new copy which is build using OpenAPI 3 Code (the changes mentioned by @shimks). 

Give that a try and let us know if you need further help.

**Comment by vijeta-singh** [comment]
I have downloaded the revised of getting-started example and requestBody is working.
Thanks everyone for detailed information.
