### ISSUE TITLE
How we can automigrate models in database in loopback-next

### ISSUE THREAD

**Issue by vijeta-singh** [strongloop/loopback-next#1098]
In loopback 4 how we can automigrate or autoupdate the database from model?

**Comment by kjdelisle** [comment]
We do not have automigration or autoupdate as a part of LoopBack 4 at this time.
We do intend to add it once the core starts to move away from an alpha state and approach production readiness.

The current legacy juggler bridge has been made to utilize the [loopback-datasource-juggler](https://github.com/strongloop/loopback-datasource-juggler) for performing CRUD operations against datasources, but it is a limited subset of the functionality provided by LoopBack v3's juggler.

See the [repository package](https://github.com/strongloop/loopback-next/tree/master/packages/repository) for current capabilities.

**Comment by debjeetdas** [comment]
Any updates on this?

**Comment by dougal83** [comment]
@debjeetdas Hi, are you looking for the following?

https://loopback.io/doc/en/lb4/Database-migrations.html
