### ISSUE TITLE
Modify docs to follow 80 chars per line rule

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1099]
Some of the docs on loopback.io are not line wrapped, which makes review difficult since it's hard to tell what change was made when github's diff isn't being all that helpful.

There should be an automatic linter (like prettier) that should do this for us.

**Comment by bajtos** [comment]
@shimks @virkt25 isn't this already done since we are formatting all Markdown files using `prettier` now?

**Comment by shimks** [comment]
Closing as done
