### ISSUE TITLE
Express vs. Koa?

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-next#11]
I don't have an opinion, but since Ritchie mentioned this some time ago, I thought I'd throw it in the mix.  
Shall we replace Express with Koa in LB4?  

Excuse my naiveté, but would it be possible to _add_ Koa, so that apps could use either Koa or Express style middleware?  Or is that impossible or impractical?

What are implications for:
- LB core, connectors, components, etc.
- Examples and docs
- Tools / workspace
- LB users (app developers)

**Comment by rmg** [comment]
Based on the current implementation using `http` directly, it appears the answer is **neither**. Close?

**Comment by ritch** [comment]
For now we are using Node.js http server directly. I think we can build a much better framework if we unshackle ourselves from Express and instead build our own lightweight extensible core.

**Comment by superkhau** [comment]
I agree with @rmg, we should close this until some actionable items on Koa/Express come up.
