### ISSUE TITLE
loopback-next - API explorer not working

### ISSUE THREAD

**Issue by vijeta-singh** [strongloop/loopback-next#1101]
Hi,

Today I have started with fresh installation of loopback-next and tried to implement simple hello world.
When I am accessing http://loopback.io/api-explorer/?url=http://localhost:3000/swagger.json 
getting "Failed to load spec".

API are working fine when I am accessing from postman or browser.
Do I need to install another component for this,I have installed this "loopback-component-explorer": "^5.3.0" but no luck.

Thanks

**Comment by virkt25** [comment]
Hi @vijeta-singh, with the recent move to OpenAPI 3, the URL has changed from `swagger.json` to `openapi.json`.

Try visiting http://loopback.io/api-explorer/?url=http://localhost:3000/openapi.json

You can also use the shortcut and visit localhost:3000/swagger-ui which will redirect you to the above link.

**Comment by vijeta-singh** [comment]
I can see api list here  http://loopback.io/api-explorer/?url=http://localhost:3000/openapi.json

But  localhost:3000/swagger-ui showing failed to load spec.

Thanks virkt25

**Comment by virkt25** [comment]
if `localhost:3000/swagger-ui` isn't working, try clearing your browser cache. You're welcome @vijeta-singh !

Let us know your feedback on the framework once you've used it some more :)
