### ISSUE TITLE
Introduce `@types/cors` as a dev dependency in `rest`

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1102]
When a new project generated from `lb4` compiles, it fails with the following message:
```shell
node_modules/@loopback/rest/dist/src/rest-server.d.ts(2,23): error TS2688: Cannot find type definition file for 'cors'.
node_modules/@loopback/rest/dist/src/rest-server.d.ts(8,23): error TS7016: Could not find a declaration file for module 'cors'. '/Users/kyusungshim/dev/testingSandbox/jfjfj/node_modules/cors/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/cors` if it exists or add a new declaration (.d.ts) file containing `declare module 'cors';`
```

We should `npm i --save-dev @types/cors` in `rest` to circumvent this issue. Although, I'm curious as to why this isn't a problem when `npm test` is run on our monorepo.

**Comment by raymondfeng** [comment]
I guess that we need to move `"@types/cors": "^2.8.3"` from `devDepedencies` to `dependencies`. Please note in monorepo, devDependencies are also visible.

**Comment by shimks** [comment]
Shall I make a PR to fix this?

**Comment by raymondfeng** [comment]
Yes, please.

**Comment by shimks** [comment]
Closing since it's fixed
