### ISSUE TITLE
Controller generator generates `@param.body`

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1108]
## Description / Steps to reproduce / Feature proposal
When generating the controller, the `create` function contains `@param.body` which is no longer valid for openapi-v3. 

### Steps to reproduce
1. run `lb4 example`
2. select `getting-started`
3. after the app being cloned, delete `controller\todo.controller.ts`
4. run `lb4 controller`
5. follow the prompt to select the Todo model and TodoRepository
6. Take a look at the newly generated `todo.controller.ts`

## Current Behavior
for the create function:
```
  @post('/todo')
  async create(@param.body('obj') obj: Todo)
```

## Expected Behavior
should be something like:
```
@post('/todo')
  async createTodo(@requestBody() todo: Todo) {
  ```
## Additional information
Suspect that the template is not correct:
https://github.com/strongloop/loopback-next/blob/71e5af10365b7fa6277cad8f6a216439610f19df/packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.template#L15

Seems like `@param.body` exists some other places in the template as well.

## Acceptance Criteria
Make sure the generated controller has no compile error.

**Comment by virkt25** [comment]
I believe this has been fixed with https://github.com/strongloop/loopback-next/pull/1109

**Comment by jannyHou** [comment]
yep @virkt25 Thanks, I am closing this issue.
