### ISSUE TITLE
Controller MegaThread

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#111]
Let's talk about `Controller`'s.

**Background**

 - [What is a Controller?](https://github.com/strongloop/loopback-next/wiki/Overview#what-is-a-controller)

**Comment by superkhau** [comment]
Closing in favour of the current proposal in the [wiki](https://github.com/strongloop/loopback-next/wiki/Controllers). Please create follow up issues for anything more specific that needs to be discussed.
