### ISSUE TITLE
Move documentation to monorepo

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#1114]
## Description / Steps to reproduce / Feature proposal
A follow up to #843:
>It would be great to have the documentation for loopback-next in the monorepo, so that we can keep documentation changes together with all other changes (runtime, CLI templates, API docs, etc.).
As part of the proposal, create the task

## Acceptance Criteria
- ~[ ] Create a script to trigger Travis build on `loopback.io` when there are changes made to `@loopback/docs` or `loopback-next`.~
- ~[ ] Create test coverage for the [script](https://github.com/strongloop/loopback.io/pull/643/) which pulls down doc changes from `loopback-next` into `loopback.io`. You can do so with JavaScript.~ **not needed at the moment as the script exits with non 0 status code if it fails to do a certain step.**
- ~[ ] Create a test on `loopback.io` which validates that `npm start` does not produce any errors. This would signify that `Jekyll` runs successfully.~ **Travis/GitHub pages is smart enough to not push changes to production if a build fails and a developer can get the same result and debug by running the scripts and Jekyll locally.**
    - After pulling in the readme's, @loopback/docs then run the `test`to make sure `loopback.io` still works

**Comment by shimks** [comment]
Most of the items in the criteria are done right?

**Comment by dhmlau** [comment]
>Most of the items in the criteria are done right?

nope.

@b-admike , I forgot to ask when we're grooming this.  Is there anything left that needs discussion or it's ready for estimate?

**Comment by b-admike** [comment]
@dhmlau I think it's ready for estimation, but it's good to bring it up for discussion to see if anyone has questions about the criteria.

**Comment by b-admike** [comment]
After having a discussion with Diana, I'm closing this as we have determined the acceptance criteria for this ticket are accounted for (I've updated the ticket). If anyone has a different opinion or other criteria to add, we can re-visit this ticket and discuss further.
