### ISSUE TITLE
loopback-next validation using class-validator not working

### ISSUE THREAD

**Issue by vijeta-singh** [strongloop/loopback-next#1116]
In loopback-next can I use class-validator https://github.com/typestack/class-validator#custom-validation-classes ?

I tried putting constraint on model file -
```ts
@property({
    type: 'string',
    required: true
  })
  @IsEmail()
  email: string;
```

in controller - 
```ts
validate(obj).then(errors => { // errors is an array of validation errors
    if (errors.length > 0) {
        console.log("validation failed. errors: ", errors);
    } else {
        console.log("validation succeed");
    }
});
```

It's not working always returning validation success message when input email is invalid.

thanks

**Comment by shimks** [comment]
Hello @vijeta-singh, could you please provide us your code in a reproduction sandbox? Thanks

**Comment by vijeta-singh** [comment]
I have found the solution.
First I am converting javascript object to class object using class-transformer.
Then calling validate function on new object.
Thanks.
