### ISSUE TITLE
(docs): Reserved binding keys page needs to be updated - missing binding keys / binding keys in wrong package

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1118]
## Description / Steps to reproduce / Feature proposal
[Reserved binding keys ](http://loopback.io/doc/en/lb4/Reserved-binding-keys.html)page is out of date.  It includes missing binding keys / binding keys in wrong package.

- package: core
  - the following binding keys do not exist in `core` but in `rest`, according to the keys.ts (https://github.com/strongloop/loopback-next/blob/action-composition/packages/rest/src/keys.ts)
    - `application.apiSpec`
    - `bindElement`
    - `getFromContext`
  - `components.${component.name}` found in `boot` and `repository`, but not `core`
  - `controllers.${controller.name}` found in `rest` (?)

- package:rest
  - Under `Rest Sequence Action Binding Keys`, should the CONSTANT values of the following names be prefixed with `SequenceActions`?  Looking from: https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/keys.ts
    - sequence.actions.findRoute
    - sequence.actions.invokeMethod
    - sequence.actions.logError
    - sequence.actions.parseParams
    - sequence.actions.reject    
    - sequence.actions.send

- package: openapi-spec
   - should be renamed to `openapi-v3`?
   - missing keys: https://github.com/strongloop/loopback-next/blob/master/packages/openapi-v3/src/keys.ts

- package: repository
   - Reserved prefixes > extra back-tick for `repositories.*``
   - cannot find the 3 binding keys in the code.  Did I look at the wrong place or it no longer exist?

- the following packages do not exist in this page, not sure if this is as expected:
  - boot
  - build
  - cli
  - metadata
  - openapi-v3-types
  - repository-json-schema

- the `page content` should be in alphabetical order.  Currently they are, except for `rest`. 

connect to #988

## Question
Do we want to remove the `Reserved Binding Keys` page or update?  
See discussion in #956

**Comment by shimks** [comment]
related to https://github.com/strongloop/loopback-next/issues/956

**Comment by jannyHou** [comment]
Agree with @shimks 's story regarding "generate docs by code", probably improve [`TSParser`](https://github.com/strongloop/strong-docs/blob/29cd00c35b48e0143aa84cdda433706e9c1a1e46/lib/tsParser.js#L65) to achieve it.
As for the temporary manually written page:

> package: openapi-spec should be renamed to openapi-v3?

`openapi-spec` is replaced by `openapi-v3-types` - it doesn't have binding keys
`openapi-v2` is replaced by `openapi-v3`  - [openapi-v3/keys](https://github.com/strongloop/loopback-next/blob/master/packages/openapi-v3/src/keys.ts)

**Comment by dhmlau** [comment]
Duplicate of https://github.com/strongloop/loopback-next/issues/956
