### ISSUE TITLE
How to modify the success & error api reponse.

### ISSUE THREAD

**Issue by vijeta-singh** [strongloop/loopback-next#1126]
For  api sucess & error api response I want different template then the default response.
How I can do that ? I want to have a global function so that I can access this in all controller.

**Comment by virkt25** [comment]
Hi @vijeta-singh, Have a look at this controller for an example of how we use `HttpErrors` from `@loopback/rest` to set success / error response codes. This gives you the most flexibility. 

https://github.com/strongloop/loopback-next/blob/master/packages/example-getting-started/docs/controller.md#srccontrollerstodocontrollerts-1

> I want to have a global function so that I can access this in all controller.

Can you please elaborate some more on this? I'm not sure I understand what you mean by a template?

**Comment by vijeta-singh** [comment]
I have see todo example

On success I want to return 
{
   "success": "true",
   "data":{json object}
}

On error I want to return 
{
    "error": {
                   "field name":"Validation Message"
                 }
}

On error I don't want to return status code.
