### ISSUE TITLE
[CLI] Generating `index.ts` in each models/repositories/controllers automatically

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1127]
## Description / Steps to reproduce / Feature proposal
In an LB4 app (e.g. in `example-getting-started` example), it seems like the general pattern is to have the export statements in the `index.ts` file in each folders (models/repositories/controllers), so that the classes in those folders can simply be imported by 
`import {SomeClass} from "../models";`

## Acceptance Criteria
I wonder if this is a good idea to:
- generate those index.ts automatically as part of `lb4 app` command
- for any artifacts created by CLI (currently we only have `lb4 controller`), add the export in index.ts
e.g. `export * from './someclass.repository';`

**Comment by virkt25** [comment]
Do we still want this with pattern with `@loopback/boot` in place which can just discover and bind the classes. 

That said someone might still want to import a class for type information

**Comment by shimks** [comment]
I'd say we still want this so that users can easily import them to unit/integration test. That being said, I'm not sure if this is something we NEED to have.

**Comment by dhmlau** [comment]
Currently if I want to reference some model in `models` folder in a controller, i think we still need to import it even with boot.  right? 
IMO, it's just nice-to-have, because when I was creating my own app, I had to create the index.ts for each folder.  It would be nice if the tooling can do it for me.  But we don't have the generator for models and repositories (which might have bigger need).

**Comment by virkt25** [comment]
If we are generating the artifacts, this part should be easy. +1 for it.

**Comment by raymondfeng** [comment]
The complexity comes into play when we add the 2nd controller. To maintain `controllers/index.ts`, the cli needs to know to how to add new entries to the existing `index.ts`.

**Comment by shimks** [comment]
That sounds easy enough for me; check the content of `index.ts` if it exists. If the import is already there, leave it alone. If it isn't, then add it.

**Comment by dhmlau** [comment]
i thought we are going to have a separate export statement for each class?  then if it exists, then we have to append from what's existing.  
```
export * from './test1.controller';
export * from './test2.controller';
```

**Comment by virkt25** [comment]
Well, when a new artifact is generated using `lb4` it should generate a `index.ts` in the artifact folder if not present and if present, it should append the new file as an import.

**Comment by dhmlau** [comment]
Discussed with @bajtos , what's in scope for `DP3` is to decide as a team on what to do with this.

**Comment by virkt25** [comment]
This isn't something too difficult to implement IMO and it should be implemented. Here's some modules we can leverage to accomplish this task:

- https://www.npmjs.com/package/make-index
- https://www.npmjs.com/package/ts-indexer
- https://www.npmjs.com/package/create-ts-index

**Comment by bajtos** [comment]
Assigned to @virkt25, looks like he is already working on something related in https://github.com/strongloop/loopback-next/pull/1363
