### ISSUE TITLE
loopback-next more information about error/status code.

### ISSUE THREAD

**Issue by vijeta-singh** [strongloop/loopback-next#1133]
On post api call if model validation fails it returns "Bad Request" or "unprocessable entity" with status code.
With status code I want more information  on error so that I can debug.
How I can get more detail on error?

**Comment by bajtos** [comment]
Hello @vijeta-singh, sorry for the long delay. What is the version of `@loopback/core` and `@loopback/rest` you are using? How can we reproduce the error on our side?

**Comment by bajtos** [comment]
Closing as a duplicate of #1434
