### ISSUE TITLE
move `Concepts` section out of `@loopback/repository`'s README and into the `docs` folder

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1137]
## Description / Steps to reproduce / Feature proposal

There are concepts detailed out in the README of `@loopback/repository` that are not present in the docs. To keep the README light-weight and to preserve good information, the `Concepts` section in the README should be migrated over to appropriate pages in docs.

- related to #1121 

## Acceptance Criteria
- [ ] remove concepts from README in `@loopback/repository`
  - [ ] append `### Repository` in `Repository.md` in the docs
  - [ ] append `### Model` in `Model.md`
  - [ ] append `### DataSource` and `### Connector` in `Repository.md` 
  - [ ] Delete `### Mixin`
  - [ ] Delete `### Type`

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by shimks** [comment]
Acceptance criteria updated.

**Comment by dhmlau** [comment]
Closed as done.
