### ISSUE TITLE
CRUD api call in the same controller with authentication apis.

### ISSUE THREAD

**Issue by vijeta-singh** [strongloop/loopback-next#1143]
I have users controller I want to have crud apis and authentication apis in the same controller.
But I am getting **Unhandled error in POST /user: 500 Error: The key authentication.currentUser was not bound to any value.**  on other get/post api call.

Also I could not find documentation about login and logout ,how I can use these feature of authentication?

**Comment by virkt25** [comment]
Hi @vijeta-singh are you using `@loopback/authentication`? Can you share either a sandbox to reproduce this issue or some code so it's easier to debug. 

That said, with LoopBack 4 we don't have a built in user model that provides `login` / `logout` **yet**. Authentication / Authorization is something we plan to add in the future. We'll be investigating this in this issue: https://github.com/strongloop/loopback-next/issues/1035

Feel free to post in that issue how you would like to see Authentication / Authorization to work :D

**Comment by virkt25** [comment]
Closing the issue due to inactivity. Comment / Ping me to have it re-opened.
