### ISSUE TITLE
[Docs] Re-work Extending LoopBack 4

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1149]
## Description / Steps to reproduce / Feature proposal

Extending LoopBack 4 section of Docs isn't very cohesive and seems to be all over the place. I am proposing this section be re-written to tell a story / guide the user through creating an extension for LoopBack 4. Ideally something a bit more advanced than `example-log-extension` and the story would explain the concepts of what different technological terms such as Decorators / Mixins / etc. are. 

## Current Behavior

The current Extending LoopBack 4 and the sections under it are all over the place in terms of content and not telling a cohesive story with multiple different examples. 

## Expected Behavior

Tell a more cohesive, concise story to extension development with a single example. 

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by shimks** [comment]
Just wondering, the proposal covers the rewrite/deletion of the subpages as well right?
Here's a couple of additional criterias that I think should be a part of this story:
- Get rid of `language-related-concepts.md` and `Mixin.md` and have their content included in the extension guide
- Rewrite of readme from `@loopback/metadata` to match with the content from the extension guide

If people feel these tasks should be separate from the issue, I'll create separate issues for them.

**Comment by virkt25** [comment]
Yep. I still need to flesh out the criteria in it's entirety but this is intended to cover the sub-pages under Extending LoopBack 4. As for the metadata page, I reviewed it and I don't think the readme should change, if anything, other readme's need to be as detailed in explaining the APIs and usage. 

That said, a new doc should be written for Extending LoopBack 4 covering decorators / usage in a more example / task driven manner instead of just plugging in the README file.
