### ISSUE TITLE
Services 

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#115]
Description:
   1.  A `Service` object will be configured to access a single datasource through a loopback connector, and will be mixed in with dao methods
   ```
   {
     Service: 'Fraud Alerts SOAP service'
     Datasource: {
        connector :  'SOAP'
        WSDL: 'http://fraudmanagement/alerts.wsdl'
        host: 'localhost'
        port: '8083'
     }
   }
```
  2. The `Service` will have features from LB 2/3.x like Service discovery/migration (as equal to model discovery)
```
AccountService.discoverModel('AccountDB');
```
  3. The `Service` will provide CRUD methods to access the datasource 
```
    const accountData = AccountService.find(filter);
    const fraudData = { id: accountData.accountNumber, type: 'Alerts'};
    fraudService.create(accountData.accountNo, fraudData);
```

Expected result
1. The service will provide a layer of abstraction for backend services.
2. A Repository can be tied to every service, to provide collections/parsing/mapping
3. We will continue to have some of the lb2/3.x features to discover and build easy back end models

We are seeing more and more of this pattern in loopback-next-example

https://github.com/strongloop/loopback-next-example/blob/fb0faf4e6f399295e97bc4dc72a82d515dd242ce/services/facade/repositories/accounts/index.ts#L19

**Comment by superkhau** [comment]
Closing in favour of current proposal in the [wiki](https://github.com/strongloop/loopback-next/wiki).
