### ISSUE TITLE
Update and revamp `should-as-function.d.ts`

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1152]
## Description / Steps to reproduce / Feature proposal

The type information of `should-js` may be outdated and needs to be updated to reflect the latest state of the module.
From @bajtos 
> Ideally, it should be possible to refactor the original upstream type definition file so that:
> - types common to both `require('should')` and `require('should/as-function')` live in a single file
> - people using `should` will receive typings including Object-prototype changes
> - people using `should/as-function` will receive typings starting from `should()` function only.

- related to https://github.com/strongloop/loopback-next/pull/1148

## Acceptance Criteria

- Copy paste `should.d.ts` from `should` module
  - get rid of type definition that enables object-prototype manipulation (see https://github.com/strongloop/loopback-next/blob/master/packages/testlab/should-as-function.d.ts#L21-L25)
  - add in type definition for `use`, `addChain`, `add` and `alias`
- Add additional criteria as needed

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
Let's leave the part "refactor the original upstream type definition" out of scope of this issue. Then the acceptance criteria look pretty clear to me. /cc @b-admike
