### ISSUE TITLE
test/ping.controller.test.ts(20,44): error TS2339: Property 'requestHandler' does not exist on type 'RestServer'.

### ISSUE THREAD

**Issue by ambrt** [strongloop/loopback-next#1166]
## Description / Steps to reproduce / Feature proposal
lb4 app
cd my-app
yarn install
npm start
## Current Behavior
```
> npm run build && node .


> lb42@1.0.0 build E:\ByDev\Ideo\lb42
> lb-tsc es2017

test/ping.controller.test.ts(20,44): error TS2339: Property 'requestHandler' does not exist on type 'RestServer'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! lb42@1.0.0 build: `lb-tsc es2017`
npm ERR! Exit status 2
```
## Expected Behavior
starting app

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
Thanks for reporting the issue. Please upgrade to `@loopback/cli@0.5.1`.
