### ISSUE TITLE
[APIDocs] Missing content from RepositoryMixin

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1171]
## Description / Steps to reproduce / Feature proposal
For the RepositoryMixin apidocs section (http://apidocs.loopback.io/@loopback%2frepository/#1798), besides the tsdocs for the class, the rest are missing. For example tsdocs for `repository` and `dataSource` functions are missing. 

## Current Behavior
Only the description for RepositoryMixin class shows up, but nothing for the functions.

## Expected Behavior
Should also show the tsdocs (including code examples) for the functions.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
The problem is the information is at the level inside the function body, what we can do is to put more information at the top level.

cc @raymondfeng @bajtos

**Comment by shimks** [comment]
The problem with the docs in `repository.mixin.ts` is that the order in which the docs introduce {summary, example, params} is wrong. Currently, the docs are written in this order: summary -> params -> example. It should be written in this order: summary -> example -> params. Just switching those should fix the problem (I think). Can someone with enough bandwidth try this?
