### ISSUE TITLE
config/datasources.json spelling mistake in Getting Started

### ISSUE THREAD

**Issue by Herdubreid** [strongloop/loopback-next#1185]
## Description / Steps to reproduce / Feature proposal
Follow the Getting Starting Tutorial
datasources.json:
{
  "name": "ds", <-- should be "db"
  "connector": "memory"
}

## Current Behavior
Errors on testing:
Unhandled error in GET /todo: 500 Error: The key datasources.db was not bound to any value.

## Expected Behavior
Works as downloaded example

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@shimks , was it something you were trying to fix in one of your PRs?

**Comment by shimks** [comment]
This has been fixed by https://github.com/strongloop/loopback-next/pull/966

**Comment by dhmlau** [comment]
I guess the docs was missed out.  
@Herdubreid , would you like to submit a pull request? 
I believe you're referring to this file: https://github.com/strongloop/loopback-next/blob/master/packages/example-getting-started/docs/datasource.md?

**Comment by dhmlau** [comment]
@Herdubreid , it's been fixed through #1195.  Thanks.
