### ISSUE TITLE
Controllers and beyond

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#12]
Controllers decoupled from the data models/ORM is a concept I have had in my mind for very long time and that I am personally interested in exploring.

We have already started some exploratory work in this direction, see 
https://github.com/strongloop-internal/scrum-loopback/issues/614#issuecomment-187124065 and the rest of the discussion.

Once we have a basic concept of a connector implemented, it will open up many further areas to investigate, for example:

 - Right now, defining custom types to describe input/output values of custom remote methods is a bit cumbersome. The format of these definition is LDL, which is our own non-standard language. I would like to allow users to describe their input/output values using JSONSchema and/or the subset of JSON Schema used by Swagger.

 - There are only very basic validation of input arguments that are not Models - we check for type (string/number/object) and whether the argument is required or not. I would like to see improved validations, using either JSON Schema or npm modules like [joi](https://www.npmjs.com/package/joi)

 - ORM independence. Let's face it, writing and maintaining a good ORM is a lot of work, and in all honesty, I think we are pretty much failing at that. I would like to make it easy for LoopBack users to switch to a different ORM/data-access library when their needs outgrow the basic ORM capabilities we provide in LoopBack.

For the scope of loopback-next, I think there will be more than enough work to implement Controllers as a first-class entity, meaning:
 - the runtime
 - support in loopback-boot 
 - support in loopback-workspace
 - a CLI tool to create new controller
 - a CLI tool to add a new remote method to a controller
 - (optionally, but preferably) support in APIC Editor

**Comment by superkhau** [comment]
Closing as this is already happening. Current proposal can be found at https://github.com/strongloop/loopback-next/wiki/Controllers.
