### ISSUE TITLE
loopback-next:  hide model property in response

### ISSUE THREAD

**Issue by vijeta-singh** [strongloop/loopback-next#1201]
Hi,

I want to hide some property in api response and I want handle this at model level.
How I can do that?

Thanks

**Comment by virkt25** [comment]
Hi @vijeta-singh, I'm not entirely sure what you mean by hiding some property in api response?

But if you wanted to filter a response to exclude some properties you can try the following. 
- Create a new `SEND` Sequence action and register that with your application ... this new action can filter the properties you would like to exclude. 

OR

- You can create an entirely new Sequence Action that you can add right before the SEND action and filters the response you are sending. 

For either task, this Doc shows how to implement a Sequence Action and customize the sequence. http://loopback.io/doc/en/lb4/Sequence.html

Let me know if this helps you accomplish what you were trying to accomplish / if I can help further.

**Comment by dhmlau** [comment]
In discussion with @raymondfeng , there are 2 things we can consider:
1) need infrastructure to support the declarative approach for defining models and allows the "hide" property
2) another possibility is to provide pluggability of actions (in the form of extensions) to allow application developers to plug in some transform for the response.

**Comment by shadyanwar** [comment]
@virkt25 @dhmlau It would be great if we could re-open this issue.

**Comment by agnes512** [comment]
The comment https://github.com/strongloop/loopback-next/issues/3453#issuecomment-568242123 might related to this issue.

**Comment by agnes512** [comment]
Please check [Hidden property](https://loopback.io/doc/en/lb4/Model.html#hidden-properties) section.
