### ISSUE TITLE
How to pass filter fields and where parameter for get api

### ISSUE THREAD

**Issue by vijeta-singh** [strongloop/loopback-next#1202]
In get api response I want selected property.
How I should pass fields filter and where parameter in get api call.

I am passing { "fields": {"id": true, "first_name": true, "last_name": true,"status":true} }.
Getting following error - 
Unhandled error in GET /user?filter=%7B%22fields%22%3A%20%7B%22id%22%3A%20true%7D%7D: 500 AssertionError [ERR_ASSERTION]: The query argument must be an object

**Comment by vijeta-singh** [comment]
Does loopback-next support api response filer by where option? I did not find any example regrading this in documentation.

**Comment by dhmlau** [comment]
@vijeta-singh , this is related to the type coercion.  In favor of https://github.com/strongloop/loopback-next/issues/750, I'd like to close this issue and continue the discussion over there.  Thanks.
