### ISSUE TITLE
TSDoc for overloaded functions are not showing up properly

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1204]
## Description / Steps to reproduce / Feature proposal

Currently, multiple docs on overloaded functions (such as `route` in `@loopback/rest, rest-server.ts`) 
are not rendered correctly; only the first one gets shown and the rest disappears. This is not the way docs for overloaded functions should be treated.

- see http://apidocs.loopback.io/@loopback%2frest/#700

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by shimks** [comment]
@raymondfeng Could you take a look at this issue and tell us whether it's a strongdoc problem or a typedoc problem?

**Comment by raymondfeng** [comment]
@shimks Please verify https://github.com/strongloop/strong-docs/pull/110. 

```sh
cd loopback-next/packages/rest
<your-dir>/strong-docs/bin/cli.js --preview --tsconfig tsconfig.build.json
open http://localhost:3000
```
