### ISSUE TITLE
Data Mapper in Repository

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#121]
# Description
A `DataMapper` would map data from one collection to another collection in the repository.

```
const summary = AccountSummary.map('summary-map', account, customer, transactions);

// summary-map.ts
@datamapper('summary-map')
export class SummaryMap {
  @map('accounts/id')
  accountNumber: string
  @map('customer/id')
  customerNumber: string
  @map('transactions', 'forEach', 'SubMap')
   transactions: array
}
@datamapper('sub-map')
export class SubMap {
  @group(['transactions/amount', 'transactions/fees'], function(a, b) {return a + b})
  amount: number
}
```

# Expected result
1. Constructs for object to object mapping.
2. Constructs for array to array mapping.
2. Constructs for reduce array

**Comment by deepakrkris** [comment]
yes, in this example having a simple class is enough. But there will be cases where the collections have completely different fields, and mapping will run to > 2000 lines. 

|                          Collection 1                                     |          Collection 2                                 |
| -------------------------------------------------| ------------------------------------ |
| Company[0].Dept[projectName ].Emp[ ].name     | Project[0].Person[].property1            |
| Company[0].Dept[projectName ].Emp[ ].section  | Project[0].Person[].property1000     |
| Company[0].Dept[projectName ].billcode             | Project[0].Person[].finance[].code    |
| Company[0].Client[].Support[].Person[].velocity  | Project[0].Person[].productivity        |

**Comment by deepakrkris** [comment]
yes, in this example having a simple class is enough. But there will be cases where the collections have completely different fields, and mapping will run to > 2000 lines. 

|                          Collection 1                                     |          Collection 2                                 |
| -------------------------------------------------| ------------------------------------ |
| Company[0].Dept[projectName ].Emp[ ].name     | Project[0].Person[].property1            |
| Company[0].Dept[projectName ].Emp[ ].section  | Project[0].Person[].property1000     |
| Company[0].Dept[projectName ].billcode             | Project[0].Person[].finance[].code    |
| Company[0].Client[].Support[].Person[].velocity  | Project[0].Person[].productivity        |

**Comment by deepakrkris** [comment]
some example of data mapper :  https://docs.mulesoft.com/mule-user-guide/v/3.8/dataweave-examples
`data transformation is an inevitable component of connectivity` https://blogs.mulesoft.com/dev/getting-started-with-dataweave-part-1/

**Comment by ritch** [comment]
Let's move this discussion to another forum and focus this issue list on core design.
