### ISSUE TITLE
[APIDocs] Types and interfaces in openapi-v3-types not showing up in apidocs

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1223]
## Description / Steps to reproduce / Feature proposal
In the [apidocs for openapi-v3-types](http://apidocs.loopback.io/@loopback%2fopenapi-v3-types/), 
there are only 2 entries show up:
- Function: isReferenceObject
- Function: isSchemaObject

None of the types and interfaces from https://github.com/strongloop/loopback-next/blob/master/packages/openapi-v3-types/src/openapi-v3-spec-types.ts shows up. 

## Current Behavior
only 2 functions show up

## Expected Behavior
at least the interfaces show up

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by shimks** [comment]
Figured out why: `docs.json`doesn't have an entry for openapi-v3-types.ts
I'll make a PR for this
