### ISSUE TITLE
[CLI] Generate DataSource

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1225]
## Description / Feature proposal
CLI command to generate datasource.  It generates either:
- datasource.ts, or;
- datasource.json with DataSource class that reads datasource.json

Sample for the first approach:
- https://github.com/strongloop/loopback-next/blob/master/packages/repository/examples/juggler-bridge/note-with-repo-class.ts#L22-L25

Sample for the latter approach: 
- datasource.json: https://github.com/strongloop/loopback-next/blob/master/packages/example-todo/config/datasources.json
- datasource.ts: https://github.com/strongloop/loopback-next/blob/master/packages/example-todo/src/datasources/db.datasource.ts

### User Experience
```
$lb datasource
? Enter the datasource name: testds
? Select the connector for testds: (selection of connectors) PostgreSQL (supported by StrongLoop)
? Connection String url to override other settings (eg: postgres://username:password@localhost/database): postgres://username:password@localhost/database
? host: localhost
? port: 5432
? user: username
? password: ****
? database: testdb
? Install loopback-connector-postgresql@^2.4 No
```
As a result, src/datasources/testds.datasource.ts will be generated.

### Outstanding questions
- What should we be generating?  just the datasource.ts? or similar to what we have in `example-todo`? 
- For the list of connectors for selection, do we want to have the same list as in LB3? 

---

## Acceptance Criteria
- [ ] Create `lb4 datasource` -- works like LB3 CLI with the following changes:
    - [ ] Each datasource config is stored in it's own `.json` file
    - [ ] An accompanying `.ts` file is created which injects the datasource config
- [ ] Tests as usual
- Not related but relevant: @loopback/boot will bind JSON config files to Context
    - Must provide a way to override from `env` ...

**Comment by dhmlau** [comment]
Things to consider: 
1) CLI to generate the datasource
2) bootstrap any LB3 datasources.json and model definition.

**Comment by bajtos** [comment]
> What should we be generating? just the datasource.ts? or similar to what we have in example-todo?

IMO, we should also register the newly created datasource with the application, see e.g. https://github.com/strongloop/loopback-next/blob/c92603157ca7f08cf3748ca6bbd1e68da87d821e/examples/todo/src/application.ts#L48-L56

Simplified version that's probably good enough for DP3:

```ts
import {db} from './db.datasource.ts';
// ...
app.dataSource(db);
```

Ideally, this registration should provided by `@loopback/boot`, but I think we are not there yet. I guess we should create a new story to allow `@loopback/boot` to discover and register datasources and implement that story first, before working on this one.

> For the list of connectors for selection, do we want to have the same list as in LB3?

Yes, let's start with the same list.

**Comment by jannyHou** [comment]
> Ideally, this registration should provided by @loopback/boot

@bajtos see https://github.com/strongloop/loopback-next/pull/1261, I think @virkt25 is already doing it :)

**Comment by dhmlau** [comment]
related to https://github.com/strongloop/loopback-next/issues/441

**Comment by dhmlau** [comment]
@virkt25 , if it's good for estimate, please move to the `needs estimate` column.  thanks.
