### ISSUE TITLE
[Docs] Update ways to contribute to LoopBack

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1228]
## Description / Steps to reproduce / Feature proposal

**This issue came about based on the March Retrospective**

Currently the [Contribution Guidelines](http://loopback.io/doc/en/contrib/index.html) indicate that a way to contribute to the project includes the following:
- Reporting issues
- Contribution to code
- Contribution to docs

We need to add a new section to tell users that another way they can contribute to LoopBack (Next and 3.0) is by helping us Triage issues! This section should include details on what triaging means -- ensuring a repro sandbox is available / works, answer doesn't exist in Docs, identifying the issue as a question, bug or feature request, etc.

To be consistent and depending on the amount of content that needs to go under this section it might make sense to add a new page to the Sidebar as all other approaches have a dedicated page. However I think that should only be done if there is enough content for guidelines on how to triage an issue.

**Comment by dhmlau** [comment]
Thinking out loud here... 
Ways to contribute: 
- triaging 
  - helping each other out.  There might be issues that look familiar
- provide feedback
  - there are pull requests marked `[RFC]` 
  - _Question_: do we want to have a `RFC` label?
  - open new issue for feature proposal
- open issue for bugs
- contribute code 
  - if you're starting out, try the ones with issues marked `good first issue`.
  - general guidelines for contributing code
  - contribute code in LB3
  - contribute code in LB4 (I think we're doing pretty good here)
- contribute docs
  - general guidelines for contributing docs
  - contribute docs in LB3
  - contribute docs in LB4
- becoming collaborator
  - we're looking for "valuable contribution"
  - how should people sign up?
     - we actively look for collaborators? 

**Inspired by:** 
- https://nodejs.org/en/get-involved/contribute/
- https://github.com/nodejs/getting-started/blob/master/README.md

Also, we have duplicate information in various places that might need to clean up:
- loopback.io (http://loopback.io/doc/en/contrib/index.html)
- CONTRIBUTING.md in each repos
- DEVELOPING.md in loopback-next

My suggestion is to have a single place of content.  If we need to have it in multiple places (for example we still want to keep CONTRIBUTING.md), we can make it to reference the main location.

[more to edit.. ]

**Comment by bajtos** [comment]
While we are making this changes, it would be great to upgrade our ISSUE TEMPLATE to support multiple kinds of issues. See what TypeScript has for an example:

https://github.com/Microsoft/TypeScript/issues/new/choose

<img width="724" alt="screen shot 2018-10-18 at 16 34 43" src="https://user-images.githubusercontent.com/1140553/47162163-be83e180-d2f3-11e8-8dfb-517648446065.png">

**Comment by dhmlau** [comment]
It seems to be a collection of the following issues:
- How to contribute documentation, https://github.com/strongloop/loopback-next/issues/1853
- "How to contribute doc" was covered in #1673

**Comment by dhmlau** [comment]
Seems like the changes for all the 3 sections are done.  Closing it as resolved. 

- Reporting issues
- Contribution to code
- Contribution to docs
