### ISSUE TITLE
[Docs] Local Site Scaffolding

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1232]
## Description / Steps to reproduce / Feature proposal

We have a `@loopback/docs` package which is great but it presents a challenge with being able to visualize the site for testing purposes. Common mistakes such as invalid YAML / nested folders / incorrect markdown rendering / etc can't be caught as there is no easy way for us to test our changes by starting up the site with the content from the `@loopback/docs` package. 

## Current Behavior

We have to update the docs -> Publish -> Wait for changes to be picked up by loopback.io -> Hope everything works (no invalid YAML / formatting issues / etc).

## Expected Behavior

I should be able to start a local jekyll server within the project with the minimal files needed from loopback.io to be able to view the docs locally and know of any build failures locally before creating a PR / merging.

Some possible solutions that come to mind
- Git Submodules to pull in loopback.io as the top level and bootstraping will link to the local copy of `@loopback/docs`. 
- Copy the minimal number of files needed to scaffold `/lb4/docs/` (don't need the rest of the site) and make sure the docs work fine by being able to view the changes. `@loopback/docs` will house these files. 

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
Probably fixed in https://github.com/strongloop/loopback-next/pull/1254 ?
