### ISSUE TITLE
ACID compliance, rollback, joins, associations, arbitrary SQL

### ISSUE THREAD

**Issue by Vandivier** [strongloop/loopback-next#1235]
## Description / Steps to reproduce / Feature proposal

Feature proposal!

## Current Behavior
Loopback doesn't have associations https://www.netiq.com/communities/cool-solutions/handling-move-events-and-associations-loopback-driver/

Loopback has trouble with or lacks acid compliance including rollback (unlike, say, Sequelize) https://stackoverflow.com/questions/34965732/how-to-implement-acid-transactions-in-loopback#38231272

## Expected Behavior
1. enforce associations for sql
2. Acid compliance for SQL
3. I want to be able to execute arbitrary SQL including flavor-specific queries like SELECT NOW() seamlessly within Loopback instead of having to use two DB management solutions in one app.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by hvlawren** [comment]
In our loopback 3 app, we had to execute some native sql to use some Postgres specific queries (e.g. https://www.postgresql.org/docs/9.6/functions-textsearch.html) for features in some cases (like the fuzzy text matching) and for performance in other (complex multi table joins with many rows per table). Having a more elegant way to do this would be nice.

**Comment by achrinza** [comment]
Related: #2331
