### ISSUE TITLE
Allow automatic repository inferrence from `@repository`

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1239]
## Description / Steps to reproduce / Feature proposal

`@repository()` should allow the automatic dependency injection from just the property/argument type it's decorating.

```ts
class MyController {
  constructor(
    @repository() myRepository: MyRepository
  } {}

  // ...
}
```

## Current Behavior

Repository pending for dependency injection needs to be manually specified, even if it's already been specified in the property/argument type:

```ts
class MyController {
  constructor(
    @repository(MyRepository) // Isn't this redundant?
    myRepository: MyRepository
  } {}

  // ...
}
```

## Expected Behavior

- allow use case for dependency injection using type inference capability of `@repository`
  - NOTE: this might only be possible with DI on properties atm since type inferrence can only be done on decorated properties and methods (parameters and return types). We currently do not support class level decoration, so the work may need to be deferred until the class level decoration implementation.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
The injection of `repository` should be explicit: `@repository` is required. I'm fine to make the arg optional if it can be inferred from the type.

**Comment by virkt25** [comment]
I think we need to be consistent with other injection decorators and this might be better as:

`@repository(MyRepository) myRepository` ... and myRepository will be assumed to have type `MyRepository` which is what I believe `@inject` does ... or was proposed in a PR.
