### ISSUE TITLE
MVP for LB4 web site

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1243]
### Timebox for 1 week

For the LB4 web site, we can do it in stages.  
The epic is captured in here: https://github.com/strongloop/loopback-next/issues/817

As the first step, the goal is to have a very basic LB4 web site up based on the design team's design (https://ibm.invisionapp.com/share/S4F1BCJTG#/screens/270115273 - available behind firewall), i.e. 
- standalone LB4 web site up and running
- landing page having different links to our existing LB4 content

The original task / epic has estimate of 20 pts. 
connected to: https://github.com/strongloop/loopback-next/issues/817

### Acceptance Criteria
- [x] Get the blueprint from design team
    - https://ibm.ent.box.com/s/tki7ffw4krc1l2lsbmy6avwmp7uhn1i5
- [x] Make a new repository (v4.loopback.io) which will contain a GitHub Pages-based Jekyll site
      - are we using Bootstrap?
 Create new site with the following layout:
- [x] Home - Landing Page (/)
- [x] In landing page, there are multiple links
   - [x] getting started  --> http://loopback.io/doc/en/lb4/Getting-started.html
   - [x] contribute --> https://github.com/strongloop/loopback-next/blob/master/docs/CONTRIBUTING.md
   - [x] docs  --> http://loopback.io/doc/en/lb4/
   - [x] link to LB blog --> https://strongloop.com/strongblog
- [x] Add the link somewhere in the loopback.io page

**Comment by dhmlau** [comment]
Needs discussion - what content do we want to show for `resources` and `contribute`.

**resources** points to:
- http://loopback.io/resources/ or 
- new content?

**contribute** points to:
- https://github.com/strongloop/loopback-next/blob/master/docs/CONTRIBUTING.md (preferred)
- https://loopback.io/doc/en/contrib/index.html

**Comment by virkt25** [comment]
`resources` page already has a design with modified content / links to resources.

---

`contribute` should point to the new `CONTRIBUTING` doc since the site will be for LB4. That said, this content is heavily geared to our development style for LB4! As such I think we should preserve some of the old content (under docs for v2/v3) perhaps?

**Comment by dhmlau** [comment]
> resources page already has a design with modified content / links to resources.

Is it a lot of effort to add it in?  I'm thinking to get the MVP web site up and running, then can add more content incrementally.  

>contribute should point to the new CONTRIBUTING doc since the site will be for LB4. That said, this content is heavily geared to our development style for LB4! As such I think we should preserve some of the old content (under docs for v2/v3) perhaps?

Since it's a LB4 web site and our intention is to keep LB2/LB3 and LB4 as separate sites.  I guess that's even better?

**Comment by dhmlau** [comment]
Based on feedback we have so far, I've updated the acceptance criteria.
I'm removing `resources`, because we don't need it as the minimal viable product.

@strongloop/lb-next-dev , PTAL.  Would like to get it estimated the coming Tue. Thanks!

**Comment by jannyHou** [comment]
@dhmlau have we decided which ui framework to use? BootStrap?

**Comment by virkt25** [comment]
BootStrap is fine IMO. We might not even need this if we start with the default template provided by the static site generator -- I would call this an implementation detail. Using a SPA framework such as `Angular / React` would be an overkill. 

A few other choices to consider / worth discussing however (and ideally this doesn't end up requiring a spike ... ) ... is what static site generator we should use. 

Currently we use: 
- Jekyll

I would like to propose a switch to a node static site generator and we use Travis to build it for us. Both options below have build their site using their own tool and you can see their code in the GitHub Repos. 
- [Hexo](https://hexo.io/)
- [VuePress (new but promising contender!)](https://vuepress.vuejs.org/)

**Comment by bajtos** [comment]
> contribute points to:
> - https://github.com/strongloop/loopback-next/blob/master/docs/CONTRIBUTING.md (preferred)
> - https://loopback.io/doc/en/contrib/index.html

If the LB4 site is going to have a different URL, then I think it makes more sense to point to LB4-specific contribution guide (i.e. loopback-next's CONTRIBUTING.md).

FWIW, we have a related story that's out of DP3 scope: https://github.com/strongloop/loopback-next/issues/950 _Update Contrib docs to match the new reality_.

**Comment by virkt25** [comment]
The site will be static, deployed to GitHub Pages. Travis will be needed to build the static site (convert `.md` -> `.html`). GitHub Pages does this for us for Jekyll sites but if we go with a `Node` static site builder such as VuePress / Hexo then we need Travis to run the build stage and deploy to GitHub Pages.

**Comment by virkt25** [comment]
Blueprint link posted.

**Comment by dhmlau** [comment]
PR: https://github.com/strongloop/v4.loopback.io/pull/1

**Comment by dhmlau** [comment]
done. See web site: v4.loopback.io
