### ISSUE TITLE
Can't create model with related model

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback-next#1269]
## Description / Steps to reproduce / Feature proposal

I would like to create model with related model/s . but can't

```
const feature = await this.featureRepository.findOne({
      where: {
        name: 'Book'
      }
})

const model = await this.repository.create({name: 'test', features: [feature]})

```

## Current Behavior

Getting following error: 

`Unhandled rejection TypeError: Class constructor Feature cannot be invoked without 'new'`

How can I create model with related model? I can't find any example for that

**Comment by jannyHou** [comment]
Hi @cajoy the relation implementation in loopback-next is still in progress, see our spike story in: https://github.com/strongloop/loopback-next/issues/995

**Comment by cajoy** [comment]
Thank you @jannyHou, that explains

**Comment by jannyHou** [comment]
@cajoy you are welcome! I am closing this issue and let's use #995 to track the progress & everyone's option. We can continue the discussion there. 
Feel free to reopen this one if you have other questions!
