### ISSUE TITLE
Make the factory HTTP framework function configurable

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#1290]
## Description / Steps to reproduce / Feature proposal
Make the factory HTTP framework function (`express()`) configurable and switchable with other Express-compatible frameworks

## Current Behavior
None

## Expected Behavior

https://github.com/strongloop/loopback-next/issues/1255#issuecomment-384966553

## Acceptance Criteria

LB4 should accept an options object to configure the underlying HTTP framework.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by shimks** [comment]
Rejecting as the acceptance criteria is not clear enough. What is the 'options object'?

**Comment by shimks** [comment]
Dropping from dp3 from our agreed consensus in our estimation meeting

**Comment by bajtos** [comment]
Removed from 4.0 GA scope, added to _[EPIC] REST layer improvements (post-GA) #1452_
