### ISSUE TITLE
Test lb4 CLI on Node 10

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1296]
## Description / Steps to reproduce / Feature proposal

From #1206 

> Node 9 CLI issues after global install

Related Note:
> Had Node installed via brew and lb4 install location wasn't part of the PATH.

---

User had reported error with CLI on Node version 9. Seeing as Node 10 is out and we made some changes with regards to enabling Node 10 I think the issue might've been resolved.

## Acceptance Criteria

- [x] Test `lb4 app` with the latest version to make sure it works as expected
    - If there is an error -- If a simple 5 minute fix create a PR else open a new issue with the error message.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@virkt25 , now that we know a simple app works in Node 10.  It seems to meet the acceptance criteria?

**Comment by virkt25** [comment]
Closing as done.
