### ISSUE TITLE
[CLI] Do not prompt for Application Class name

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1297]
## Description / Steps to reproduce / Feature proposal

From #1206 
> Why do I need to create a class?

Related Notes:
> Refers to the CLI prompting for Application Class Name. No description of what that Application class refers to.

---

We already prompt the user for a `Project name` and then prompt for an `Application class name`. 

## Acceptance Criteria

- [ ] Remove prompt for Class Name (Use the default we generate) -- this will prevent users from having to enter the it again / get confused about what the `Application class name` is.
    - Might be good to have a message stating the name of the class that we generated.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
I think the proposal is against our intention - we want to have reasonable defaults based on conventions for the code generation but we also want to allow users to confirm/customize.

If the concept of `Application` is not clear, we can add a link or make it more descriptive in the CLI.

**Comment by bajtos** [comment]
+1 for making the CLI prompts more descriptive, so that users understand why we are asking them about application class name.

**Comment by jannyHou** [comment]
I also tend to omit the customizing step of the app class name, don't feel people often have the need to rename it...we can either make the prompt message more descriptive, or remove it and add a short document says we allow the customization.

**Comment by shimks** [comment]
^^^ I'm for removing the prompt for the application class name as well. In my opinion, the users that _do_ want to customize their application class name should be able to set up a flag (`--applicationClassName=CustomNameApplication`).

**Comment by shimks** [comment]
Rejecting for estimation. More feedback wanted on what to do with the issue.

**Comment by dhmlau** [comment]
I'd like to propose to move this out of DP3.  IMHO, this is a minor issue compared to other UX issues we're having, e.g. CLI for models/datasource/relations.

**Comment by bajtos** [comment]
> I'd like to propose to move this out of DP3. IMHO, this is a minor issue compared to other UX issues we're having, e.g. CLI for models/datasource/relations.

+1, I have changed the labels accordingly.

**Comment by dhmlau** [comment]
related to #1340

**Comment by dhmlau** [comment]
@virkt25 , we now have the `--yes` option for the express mode. 
Is this ticket good to close?  thanks.

**Comment by virkt25** [comment]
Yep.
