### ISSUE TITLE
Add build passing badge

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#130]
Depends on Travis CI (#161) + AppVeyor (#162 and #164) being set up properly first.

- [x] Confirm the build is 100% passing on CI
- [x] Get correct badge from shields.io
- [x] Add to badge section in README

**Comment by bajtos** [comment]
I think we need to setup Travis CI and AppVeyor integration first?

**Comment by superkhau** [comment]
@bajtos Yup, just adding this to the backburner. ;)

**Comment by bajtos** [comment]
The build is passing on Travis (see #161), we are not passing on Windows yet (see #162 and #164).

**Comment by superkhau** [comment]
Added build passing badge for Travis.
