### ISSUE TITLE
[EPIC] Cloud Native Experience

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1304]
### Area 1: Scaffold LB4 application from Cloud UI (IBM Cloud App Service starter project)
- https://console.bluemix.net/developer/appservice/dashboard

### Area 2: As-is and to-be scenario
- (As-is scenario)Try to deploy LB4 app to IBM Cloud and see what the steps are and extra metadata it needs
   - blog post to go through the steps
   - LB4 documentation 
- (To-be scenario) Identify tooling that can help with the developer experience
   - e.g. generator integration with IBM Cloud
   - https://github.com/strongloop/loopback-next/issues/1476

### Area 3: Deploy LB4 as microservices and communicate with other microservices
- Consider a scenario of multiple microservices, 2 in LB4 and 1 in other lang, such as Java/Go/…
  - Starting with two LB4 microservices
   - make them talk to each other and package them into 2 docker containers and deploy into k8s 
   - then add the polyglot one

### Area 4: enable health/metrics/distributed tracing
- Try to enable health/metrics/distributed tracing with CNCF (including istio)
- https://istio.io/
- https://www.cncf.io/

### Area 5: Cloud service integration
- Cloud service integration, such as hosted DB, storage, AI, security, serverless, …

### Area 6: Align with IBM Microclimate workflow and tooling
- https://microclimate-dev2ops.github.io/

### IBM CloudNative 
- https://github.ibm.com/ibmcloud/CloudNative (https://pages.github.ibm.com/ibmcloud/CloudNative/)
cc @raymondfeng

**Comment by bajtos** [comment]
Since the 4.0 GA scope is only to run spikes, I opened a different epic to keep track of that research - see #1459. Let's keep the current epic as a post-GA item grouping tasks needed to make Cloud Native a 1st class experience.

**Comment by jannyHou** [comment]
- add discussion for micro climate
