### ISSUE TITLE
[CLI] [Spike] Come up with UX for application scaffolding through CLI

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1309]
## Description / Steps to reproduce / Feature proposal
We need to conduct a spike on the possible UX of an application CLI experience. It should encompass some ideas from:
- #1297: Application class name
- #1298: Enabling Mocha/LoopBack Build
Other areas that may need to be considered are:
- TSLint
- Prettier

## Acceptance Criteria
- come up with a couple of ways to deliver UX for both newbies and experienced devs alike
  - potentially look at how other CLI toolings offer this experience (like Angular)
- conduct a poll on strongloop/loopback-next to see how they feel about the options we've come up with

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
Some more background...

Based on our discussion today with @strongloop/lb-next-dev , I think there are 2 camps:
**Opinion#1**: The less questions we ask in the prompt is better. 
Reason: For new users, they may not know all the concepts behind LB4, so they might be lost (or it is not necessary) to ask them too many questions when we can make some of the decisions for them.

**Opinion#2**: Customization is important to our users.  There are defaults to help them making the decisions. If they don't know what to change, they can always fall back to the defaults. 
Reason: If we provide too much "magic", users would lose the ability to customize their application.  

In addition, there was discussion around adding CLI docs link in the command line help or even in the prompt, so that users can know where to get more information.

As a result, we'd like to get some user feedbacks after hashing out a few proposals.

**Comment by bajtos** [comment]
@strongloop/loopback-next we would like to hear your opinion about CLI tooling. What should we prefer more - simplicity or customizability?

**Opinion#1**: The less questions we ask in the prompt is better. 

Reason: For new users, they may not know all the concepts behind LB4, so they might be lost (or it is not necessary) to ask them too many questions when we can make some of the decisions for them.

**Opinion#2**: Customization is important to our users.  There are defaults to help them making the decisions. If they don't know what to change, they can always fall back to the defaults. 

Reason: If we provide too much "magic", users would lose the ability to customize their application.  

For example, when scaffolding a new application via `lb4 app`, or a new extension via `lb4 extension`, should we ask the user whether they want to use prettier, tslint, mocha tests, etc., or should we simply "force" on them everything that we consider as a best practice?

**Comment by doublemarked** [comment]
@bajtos just ask the user as the first question. Here's an example of how [Semantic UI](https://github.com/Semantic-Org/Semantic-UI) approaches its setup:
```
[15:31:03] Starting 'run setup'...
? Set-up Semantic UI (Use arrow keys)
❯ Automatic (Use default locations and all components) 
  Express (Set components and output folder) 
  Custom (Customize all src/dist values) 
```

If you pick Automatic, then you zip through the setup. If you pick Custom then it asks a lot of questions.

**Comment by m3hari** [comment]
I completely agree with @doublemarked just an additional thought inspired by the Vue Cli, plugin system is pretty awesome. 

We can always start with the basic default configuration and add functionality as the project grows using plugins.

Example: adding cypress e2e configuration and dependencies on alredy create project
```
$ npm install -D @vue/cli-plugin-e2e-cypress
$ vue invoke e2e-cypress

```

this will add the required dependencies, inject commands and add configurations.

IMO this plugin architecture is pretty great and will make lb CLI flexible.

**Comment by bajtos** [comment]
Thank you @doublemarked and @m3hari  for the feedback!

The idea of adding a prompt for express/custom setup crossed my mind too, it's great to hear other frameworks are already doing the same 👍  I think we have a winner here 🎉 

As for CLI plugins, this is sort of similar to what Yeoman does with generators too. It's a great feature to have, but I don't think we will have bandwidth to work on it any time soon - we have other big issues to tackle first. Maybe after 4.0 GA is released, we can take a look at this again?

**Comment by dhmlau** [comment]
Closing this spike as resolved because we're going to have the "basic vs customize mode" (terminology TBD) and the task is tracked under #1340
