### ISSUE TITLE
Add coverage badge

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#131]
- [ ] Confirm code coverage is 100% (or passing at least)
- [ ] Get badge from shields.io
- [ ] Update badge wiki page with correct badge link
- [ ] Add to badge section in README

**Comment by bajtos** [comment]
I am proposing a different approach:
1. Setup Coveralls integration, configure Travis CI jobs to report to Coveralls
2. Let Coveralls to add the badge to our README (they have UI for that)

**Comment by bajtos** [comment]
> Update badge wiki page with correct badge link

@superkhau I am not sure what do you mean by this, which wiki page would you like to change?

The rest of the TODO list should be taken care of by the linked pull requests shown above.

**Comment by superkhau** [comment]
https://github.com/strongloop/loopback-next/wiki/Badges

Was keeping a list of badges we use here (ie. might reuse in other repos), but might not be worth maintaining anymore.

**Comment by bajtos** [comment]
> Was keeping a list of badges we use here (ie. might reuse in other repos), but might not be worth maintaining anymore.

Yeah, let's delete that page. We can always find the up-to-date list of badges in README, right?
