### ISSUE TITLE
Make coercion and validation work off of @loopback/types

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1319]
## Description / Steps to reproduce / Feature proposal

For DP3, we'd like validation and coercion system implemented in the http-layer to use `@loopback/types`

## Acceptance Criteria
- [ ] Move `types` folder from `@loopback/repository` into its own package; Make sure this PR is refined and make sure it lands https://github.com/strongloop/loopback-next/pull/947
- [ ] Move over the converters used in http coercion into appropriate files in `@loopback/types` with extensibility in mind.
  - [ ] Come up with a decorator system (`@param` or a new one if necessary) to introduce metadata to appropriately infer type metadata (for example Date)

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
@shimks we already have another story covering validation at REST layer, see #750:

> ## Acceptance Criteria
>
> -  Coerce incoming query string, path and header inputs into strings, numbers, booleans, Dates
>    - Do not coerce timestamps (Unix timestamps in milliseconds)
> - Validate only that the output is correct for the chosen type
>
> ## Notes
>
> We should consider using either strong-remoting or AJV to perform the coercion

Assuming we implement #750 first, what would be the scope & acceptance criteria of this story #1319?

**Comment by shimks** [comment]
@bajtos I believe the acceptance criteria should remain unchanged considering the scope of this task is to move over the converters used in http coercion into a 'LoopBack' typing hub.
