### ISSUE TITLE
Interceptors

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#133]
- [ ] Must be able to inject request/response interceptors for a Controller
 ```
      @intercept('request',  function(request, next) {
         logMessage(request, next);
      });
      @intercept('response', './scripts/error-handler');
      @intercept('request', './scripts/user-context');
      @api(def) 
      class OrderCancellationController {
      .....
      }
``` 
- [ ] interceptors will be invoked in the order of declaration for the controller
- [ ] interceptor scripts must export a function with a specific signature
- [ ] An interceptor can modify the request/response, headers and body

**Comment by dhmlau** [comment]
need a way to register the decorators for interceptors

**Comment by bajtos** [comment]
I think this is conceptually similar to remoting hooks (beforeRemote, afterRemote, afterRemoteError) in LoopBack 3.x

**Comment by raymondfeng** [comment]
See https://docs.nestjs.com/interceptors

**Comment by dhmlau** [comment]
Closing as done. 
See https://loopback.io/doc/en/lb4/Interceptors.html
