### ISSUE TITLE
[Release] 🚀 Developer Preview 3 🚀

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1330]
This is a high-level issue keeping track of the upcoming release _LoopBack 4 Developer Preview 3_.

## Target Date

July 2018

## Scope

See the current list of stories we are considering as a candidate for DP3 release here:
https://github.com/strongloop/loopback-next/labels/DP3

**https://github.com/strongloop/loopback-next/issues/1038 Robust HTTP processing capabilities**

- [x] Must have: rework internals to use Express request/response types
- [x] Leverage CORS middleware instead of the current workaround (minimal refactoring)
- [x] HttpEndpointFactory - a new module to deal with HTTP(S) setup, a dependency of `@loopback/rest`
- Stretch goal: serving OpenAPI spec document should be implemented in a controller method

Out of DP3 scope:
- Local API Explorer (Swagger UI) should be implemented using Express middleware
- Expose Express to app developers, allow them to add custom middleware

**https://github.com/strongloop/loopback-next/issues/1036 Integration with REST / SOAP services**
- [x] Leverage existing LoopBack 3.x connectors (soap, rest, swagger, gRPC)
- [x] Need to figure out testability+ document it

Out of DP3 scope:
- auto-generated .d.ts definitions
- CLI tooling
  
**https://github.com/strongloop/loopback-next/issues/1032 Model relations PREVIEW**
- Show the programming model, gather feedback.
- [ ] must have: HasMany
- stretch goal: BelongsTo

Out of DP3 scope
- Additional relation types (HasAndBelongsToMany, polymorphic & embedded relations, etc.)
- CLI tooling
   
**https://github.com/strongloop/loopback-next/issues/755 Validation and Type conversion**
- [ ] deserialize HTTP parameters on OpenAPI spec
- [ ] minimal validation of input parameters at REST layer
- stretch goal: extensibility of coercion and validation

**Usability Improvements**

**Comment by dhmlau** [comment]
Closing as done!
