### ISSUE TITLE
HTTP endpoint factory

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1331]
Rework the way how an HTTP server is setup and configured for LoopBack applications (RestServer instances) following the approach outlined in https://github.com/strongloop/loopback-next/pull/1082.

**IMPORTANT**

The spike was based on an assumption that we will support different frameworks (Express, Koa, etc.). Based on the spike outcome, we decided to go forward with a single framework and use Express request/response types everywhere. __As a result, most of the spike code needs to be simplified by removing generic type arguments etc__.

https://github.com/strongloop/loopback-next/blob/2bddc47ccda56a50c52a8a92facd87e3a3f4944d/packages/http-server/src/common.ts#L12-L48

https://github.com/strongloop/loopback-next/blob/2bddc47ccda56a50c52a8a92facd87e3a3f4944d/packages/http-server/src/common.ts#L116-L212

## Acceptance criteria

- There should be a new module for creating HTTP and HTTPS servers.
- `@loopback/rest` should use this new module to start/stop the server
~- The module should support HTTP config only~

## Out of scope

The following features are out of scope, but please keep them in mind when designing the new module.

- HTTPS support - see https://github.com/strongloop/loopback-next/issues/430
- Configurable framework factory function - see https://github.com/strongloop/loopback-next/issues/1290

**Comment by dhmlau** [comment]
Closing this as PR #1369 has merged
