### ISSUE TITLE
Blog post: Leveraging Express for a more robust HTTP processing

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1337]
Write a blog post describing 
 - the changes made as part of the epic
   - https://github.com/strongloop/loopback-next/issues/1292
   - https://github.com/strongloop/loopback-next/pull/1326 (etc.)
   - Leverage CORS middleware instead of the current workaround (minimal refactoring)
   - #1331 HTTP endpoint factory 
 - our motivation behind these changes
 - what it means for LB4 app and extension developers, how to upgrade

**Comment by bajtos** [comment]
In progress.

**Comment by dhmlau** [comment]
Closing it as done.  https://strongloop.com/strongblog/loopback4-improves-inbound-http-processing
