### ISSUE TITLE
Creating Express mode for generating applications(must have) and other artifacts(optional) through CLI

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1340]
## Description / Steps to reproduce / Feature proposal
There should be a mode for creating apps through CLI where users can expect everything to be done for them without having to configure anything through the prompts.

## Acceptance Criteria
- [x] Add an `Automatic` / `Custom` mode for selecting the project settings.
    - [x] Appropriate Tests / Blog posts / etc. 
- [x] Figure out the optional prompts
  - how to pass answers to them.
- [x] Maybe introduce a flag to specify the express mode
- [x] App cli is a must have goal
  - other clis are stretch goals
- [x] A blog post
## Related PR
https://github.com/strongloop/loopback-next/pull/1384

## Discussion points
- How are we going to present this option to the users?
  - Through prompts?
  - Through flags/options?

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
Getting the feedback from https://github.com/strongloop/loopback-next/issues/1309 and team discussion, I think the general idea of each CLI command is to have `express` and `custom` mode, such that:
```
$ lb4 <<artifact>>
> express (<<prompt for minimal items>> )
   custom (<<customize everything>>)
```

**Proposal for `lb4 app` command**
- `custom` path would show what we're showing currently, asking:
    - project name
    - project description
    - project root directory
    - application class name
    - project build settings
-  `express` path asks only project name, and keeping defaults for the rest, such that:
    - project name: (user defined) 
    - project description: `loopback4 example` 
    - project root directory: (same as project name)
    - application class name: (project_name+Application)
    - project build settings: enable tslint, prettier, mocha, loopbackBuild

**Comment by bajtos** [comment]
I think the proposed express mode is too express. For example, I don't think there is any good default value for a project description to use in the express mode.

The whole discussion (see https://github.com/strongloop/loopback-next/issues/1309) was started because build settings are difficult to understand for new users. I think that's all we should hide behind express/custom mode.

I think the following prompts should remain unchanged:

```
$ lb4 app
? Project name: todo-app
? Project description: A simple todo app
? Project root directory: todo-app
? Application class name: TodoAppApplication
```

The custom/express prompt should be displayed after those initial questions were cleared and we are going to decide how to configure the build:

Currently:

```
? Select project build settings:  (Press <space> to select, <a> to toggle all, <i> to invert selection)
❯◉ Enable tslint
 ◉ Enable prettier
 ◉ Enable mocha
 ◉ Enable loopbackBuild
```

My proposal:

```
? What build steps would you like to enable: (Use arrow keys)
❯ All recommended (loopbackBuild, mocha, tslint, prettier) 
  Manually select features
```

**Comment by dhmlau** [comment]
Closing as done.  The blog post is ready, just waiting to be published.
