### ISSUE TITLE
Allow coercion and validation to be extensible

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1343]
## Acceptance Criteria
- _to be hashed out after the completion of #1319, #750 and #118_

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
A spike for 4.0 GA: https://github.com/strongloop/loopback-next/issues/1463

**Comment by shimks** [comment]
Closing in favor of #1463.
