### ISSUE TITLE
Using `lb-mocha` with VSCode's debug feature results in an error

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1348]
## Description / Steps to reproduce / Feature proposal

When using VSCode's debugging feature with LoopBack 4's testing script `lb-mocha`, it is not possible to use the `restart` button as doing so would result in timing out with an `ECONNREFUSED` error. I believe this is because the child processes (or the parent processes) aren't being correctly shut down when restarting.

There are two child processes involved when `lb-mocha` is invoked:
lb-mocha -> mocha (1st child process) -> _mocha (2nd child process)

Below is the settings I've tried to use with `lb-mocha` in `launch.json`

```json
    {
      "type": "node",
      "request": "launch",
      "name": "Run Mocha tests",
      "program": "${workspaceRoot}/node_modules/.bin/lb-mocha",
      "cwd": "${workspaceRoot}",
      "args": [
        "DIST/test/**/*.js",
        "-t",
        "0",
        "--inspect"
      ],
      "autoAttachChildProcesses": true
    }
```

Ideally, we'd like to directly call `_mocha` so that we wouldn't have to deal with child processes, but that brings up the question of how we are going to handle testing the correct build for the node version the user is on.

This was brought up in #1336

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
The PR #1509 has landed. Is this ticket good to close?

**Comment by raymondfeng** [comment]
@shimks Did you try to add `--exit` to args?

**Comment by shimks** [comment]
Just tried it out. I get `Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9229).` after I try to restart the debugging sesion

**Comment by kowsheek** [comment]
@shimks Hi there, have you been able to get this working since?
