### ISSUE TITLE
HasMany relation - Docs and Blog post

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1351]
## Description / Steps to reproduce / Feature proposal
As a follow up task for PR #1342, we need documentation and blog post for the hasMany relation. 

### Acceptance Criteria
- [x] documentation on hasMany relation
  - [x] Definition of a `hasMany` relationship between our data models
  - [x] How the relation is defined
  - [x] How the relation can be used in controller methods
- [x] blog post includes: 
   - design considerations/decisions from the spike #995
   - future work - e.g. hasMany is the first one we complete, next is BelongsTo

cc @b-admike 

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@b-admike , could you please modify the acceptance criteria as needed so that we can estimate tmr? thanks.

**Comment by b-admike** [comment]
@dhmlau done. I think what was there before makes sense, just added a couple more points.

**Comment by dhmlau** [comment]
Closing as done.
