### ISSUE TITLE
Use relational decorators' metadata

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1354]
## Description / Steps to reproduce / Feature proposal
Use relational decorators' metadata to construct constrained target repository instance on relational properties

### Acceptance Criteria
@b-admike , could you please add the acceptance criteria? 

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by b-admike** [comment]
@dhmlau I think this is covered by #1372 (which I've updated) with the following criteria:
>Infer relation metadata from the hasMany decorator to construct constrained target repository instance on relational property
It makes sense to do it as part of that story. Closing this.

**Comment by b-admike** [comment]
Talked with @dhmlau. We've agreed that this issue can be closed.
