### ISSUE TITLE
Relation refactoring: Split Repository interface into different interfaces

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1356]
## Description / Steps to reproduce / Feature proposal
See https://github.com/strongloop/loopback-next/pull/1194#discussion_r184261118 for background. This tasks aims to break up the `Repository` interface into different interfaces based on the persistence function type and refactor the repository interfaces which extend from it to use those interfaces via a Mixin.

### Acceptance Criteria
- [ ] Split `Repository` interface into different interfaces based on the persistence function type i.e. `LookupRepository` interface to have all the Retrieval methods, ~~`WriteRepository` (I'm sure there is a better name), would have the create methods~~, `MutationRepository` might have the update and related methods (this might fall under the previous one), ~~and `DestroyRepository` for deletes~~. A good list from @raymondfeng:

> 1. QueryRepository - read-based operations (find, findOne, count, ...)
> 2. MutationRepository - write-based operations (create, update, delete, ...)
> 3. CrudRepository (QueryRepository + MutationRepository)
> 4. EntityRepository (CrudRepository + findById, updateById, deleteById, ...)

- [ ] Explore the use of a Mixin for a smart way of sharing the implementation bits from the different repositories (for e.g. how can `HasManyEntityCrudRepository` inherit the needed CRUD methods from the interfaces mentioned above?).

- [ ] tests / docs

**Comment by jannyHou** [comment]
@strongloop/sq-lb-apex @hacksparrow @raymondfeng @bajtos Any updates on this story?

**Comment by b-admike** [comment]
@jannyHou Sorry, I need to work with @raymondfeng to update the acceptance criteria. I'll have it ready for our next estimation meeting.

**Comment by raymondfeng** [comment]
Here are some candidates I see:

1. QueryRepository - read-based operations (find, findOne, count, ...)
2. MutationRepository - write-based operations (create, update, delete, ...)
3. CrudRepository (QueryRepository + MutationRepository)
4. EntityRepository (CrudRepository + findById, updateById, deleteById, ...)
