### ISSUE TITLE
Incorporating relations in our examples

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1358]
## Description / Steps to reproduce / Feature proposal
Incorporating relations in our examples, either create new example or use existing ones (e.g. todo example).

### Acceptance Criteria
The example application should:
- [ ] Create another todo intermediate example(a new example package)
- [ ] demonstrate defining and configuring a `hasMany` relation, and calling related repository CRUD APIs from controller methods
- [ ] have the necessary unit and acceptance tests
- [ ] have proper naming convention for the controller method paths / API endpoints (a good read at https://medium.com/@factoryhr/how-to-build-a-good-api-relationships-and-endpoints-8b07aa37097c)
- [ ] Docs and tutorials that show users scaffold the new example package step by step.
Note:

- List/User hasMany Todos
  - owner decides which use case makes more sense
- Authentication is not in scope of this story.
- bonus: figure out a way that don't duplicate code from todo example.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
In discussion with @b-admike and @shimks, there are few options on how to add relations in our examples: 
**Option 1**: Use [todo](https://github.com/strongloop/loopback-next/tree/master/examples/todo) example
- General idea: todo list has todo's 
- Pros: effort will be smaller because we will be adding models instead of creating a new app
- Cons: it might be hard for our users to follow if one example serves too many purpose

**Option 2**: Recreate [CoffeeShop example ](https://loopback.io/doc/en/lb3/Introducing-the-Coffee-Shop-Reviews-app.html) from LB3
- General idea: create a trimmed down version of CoffeeShop that serves the purpose for showing `hasMany` relation.  When we have more relations added, this would be the example to add.
- Pros: this can be a dedicated example if we need to add more relations later.  Also, we can use this as a reference on what would be the differences vs LB3

**Comment by b-admike** [comment]
@dhmlau I've added some acceptance criteria, but I think we should discuss what type of app we would like to create before we estimate this task. Thoughts? We have a good starting point with the options you provided and I personally would like to go with Option 2, because I think creating a new app would not be daunting given the examples we already have in place.

**Comment by dhmlau** [comment]
closing as done.
