### ISSUE TITLE
Property 'body' does not exist on type 'ParsedResponse'

### ISSUE THREAD

**Issue by Vandivier** [strongloop/loopback-next#1362]
## Description / Steps to reproduce / Feature proposal

consider the following controller.ts:
```ts
    export class Get_access_tokenController {
      PUBLIC_TOKEN = this.request.body.public_token;
      constructor(@inject(RestBindings.Http.REQUEST) private request: ParsedRequest) {}

      // Map to `GET /get_access_token`
      @get('/get_access_token')
      ping(): object {
        return {
           PUBLIC_TOKEN,
        };
      }
    }
```
## Current Behavior

1 - My IDE (Brackets) throws on line 2: "Property 'body' does not exist on type 'ParsedResponse'"
2 - [Docs state](http://loopback.io/doc/en/lb4/Sequence.html) "Request - (TBD) missing API docs link"

## Expected Behavior

1 - Docs exist for ParsedResponse, showing what properties exist there
2 - I have some way to access the request body

May be related to [1038](https://github.com/strongloop/loopback-next/issues/1038), but I don't see a requirement about documentation over there.

**Comment by virkt25** [comment]
@Vandivier Thanks for trying out LB4 and the feedback above. Can you try the following:

1. Install the latest version of the CLI (`npm i -g @loopback/cli`) -- generate a new project and try the above. 

2. `PUBLIC_TOKEN` is a property and hence in `ping()` should be referred as `this.PUBLIC_TOKEN`

---

The reason to re-install the CLI and generate a new project is that we recently made the switch from a custom `ParsedRequest` type to just `Request` from `express`. We are in process of moving the `http` processing back to `express` minus the routing. Stay tuned for more changes. 
- `Request` type has a `.body` property :) 

As for docs, I agree we need to work on updating the docs to better reflect the changes. Would you be able to submit a PR for the docs? -- The team probably won't be able to update them till we're done with `DP3` -- but this likely won't affect how `req.body` works any further.

Let me know how it goes with the above.

**Comment by virkt25** [comment]
@Vandivier any updates?

**Comment by Vandivier** [comment]
ParsedResponse error is OBE but docs are outdated. Please use this issue to track doc updates:

1. As mentioned in my original comment, [Request and Response](https://loopback.io/doc/en/lb4/Sequence.html) docs are missing.
2. Now that we are using Express again, [Why Not Express](https://loopback.io/doc/en/lb4/Crafting-LoopBack-4.html#why-not-express) should be updated.

**Comment by virkt25** [comment]
New request docs are on their way! https://github.com/strongloop/loopback-next/pull/1519

---

I'll create an issue to track updating `Why Not Express` so it's easier to track :)

**Comment by Vandivier** [comment]
@virkt25 Thanks!!
