### ISSUE TITLE
Add tests for `hasMany` relation source code

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#1379]
## Description / Acceptance Criteria:
Add appropriate tests for the following files introduced in #1342.
 - [x] `constraint-utils.ts` https://github.com/strongloop/loopback-next/blob/066dfa3fc8a24f0e7ce7756673ba8d60af7fae62/packages/repository/src/repositories/constraint-utils.ts
- [x] `relation-factory.ts` https://github.com/strongloop/loopback-next/blob/066dfa3fc8a24f0e7ce7756673ba8d60af7fae62/packages/repository/src/repositories/relation.factory.ts
- [x] `relation-repository` https://github.com/strongloop/loopback-next/blob/066dfa3fc8a24f0e7ce7756673ba8d60af7fae62/packages/repository/src/repositories/relation.repository.ts

**Comment by dhmlau** [comment]
@b-admike , is this working in progress now? if not, is it intended for DP3?

**Comment by b-admike** [comment]
@dhmlau yeah I have started working on it with #1383 (I think it's good to have in DP3).

**Comment by b-admike** [comment]
Done in #1383.
