### ISSUE TITLE
Build Authentication package to use Passport Strategies

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#138]
Implementation of https://github.com/strongloop/loopback-next/tree/master/packages/authentication

- [x] Implement our version of passport.authenticate to authenticate incoming requests 
- [x] implement our version of passport.initialize

**Comment by ritch** [comment]
@deepakrkris - lets chat about this - you don't need `passport.initialize`

**Comment by raymondfeng** [comment]
Per passport docs and my experience:
> In a Connect or Express-based application, passport.initialize() middleware is required to initialize Passport. If your application uses persistent login sessions, passport.session() middleware must also be used.

**Comment by ritch** [comment]
@raymondfeng we are implementing the equiv. of `passport.initialize()` / `passport.authenticate()` and just using `strategy.authenticate()`...

Here's a somewhat complete set of stubs we need to implement:

```ts
import {inject} from "@loopback/loopback";
import {authenticate} from "@loopback/authenticate";

class MyCtrl {
  constructor(@inject('authentication.user') user) {
    this.user = user;
  }

  @authenticate
  whoAmi() {
    return this.user.username;
  }
}

// setup authentication
BasicAuthStrategy = require('passport-basic');

let app = new Application();
app.bind('authentication.strategy').to(BasicAuthStrategy);

app.bind('authentication.user').to((@inject('authentication.credentials')) => {
  
});



// impl
function authenticate() {
  
}

// routing (loopback core)
function invoke() {
  
}

// authentication bindings (@loopback/authentication)
app.bind('authentication.authenticated').to(() => {
  
});
```
