### ISSUE TITLE
LB4 website: Getting Started page

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1382]
## Description / Steps to reproduce / Feature proposal

Part of incremental effort to fully implement `v4.loopback.io`. See #817.

## Acceptance Criteria
- [ ] refactor `index.html` to extract out the header and footer
- [ ] create `Getting Started` page as according to the given spec

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
Issue moved to [strongloop/v4.loopback.io #22](https://github.com/strongloop/v4.loopback.io/issues/22) via [**ZenHub**](https://www.zenhub.com/)
