### ISSUE TITLE
[Spike]How to modify datasource configuration in integration/acceptance tests

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1396]
**Time-boxed to 1 week**

When I wrote the original Thinking in LoopBack content, which was later converted to best-practices guides [Implementing features](http://loopback.io/doc/en/lb4/Implementing-features.html) and [Testing your Application](http://loopback.io/doc/en/lb4/Testing-your-application.html), I was thinking that acceptance and integration tests should use the very same datasource configuration as the actual application, to ensure that tests are testing the same database setup as will be used during app runtime.

Based on our recent experience in #1385 and #1347, it's becoming clear that there are legitimate needs to slightly tweak datasource configuration in tests. For example:
 - When dealing with in-memory connector persisting data in a file, we may want to disable this persistence in tests by unsetting `file` property.
 - When running tests against a real database, we may want to use a different table name so that our tests are not touching the data used by the actual app.
 - When testing Service integration, we may want to configure caching proxy to speed up our test suite.

Let's address these needs!

## See also

- [Spike] Allow extensions to contribute custom convention for environment-specific operational configuration #1464

## Acceptance Criteria(Spike):

What we need to figure out:

 - How to define datasources and repositories in such way that integration/acceptance tests and test-data builders can tweak the configuration.
 - How to write test-data builders in such way that tests can provide a modified datasource configuration. For example, test-data builders can accept a datasource instance or a repository instance initialized by the actual test to use the correct datasource configuration.
 - How to tweak datasource config in acceptance and integration tests and use that tweaked configuration for test-data builders too.

Two candidate approach are:

- create api to generate the datasource dynamically
- provide env based settings, boot can pick up the config accordingly

 
Let's keep this issue focused on database-backed datasources only. Testing Services is out of scope, see #1311 for that.

## Acceptance criteria(suggested as implementation)

- Discuss Spike Results and get consensus on the approach
- Create a follow up task with the following to be implemented based on outcome of this: 
```
 - Update the content and code snippets in the following doc pages to show the new approach:
   - [ ] [Implementing features](http://loopback.io/doc/en/lb4/Implementing-features.html) 
   - [ ] [Testing your Application](http://loopback.io/doc/en/lb4/Testing-your-application.html)
 - Update `examples/todo` to use the new approach
 - Update templates used by CLI to follow the new approach, especially the datasource template and possibly repository template (if it's implemented by the time we start working on this story)
```

**Comment by jannyHou** [comment]
Comments from Raymond:
- We want to generate datasource from environment.

Let's discuss more about the detail of "new approach" then revisit this story.
Some possibility of the "new approach":
- create api to generate the datasource dynamically
- provide env based settings, boot can pick up the config accordingly

**Comment by bajtos** [comment]
> Let's discuss more about the detail of "new approach" then revisit this story.
> Some possibility of the "new approach":
> 
> - create api to generate the datasource dynamically
> - provide env based settings, boot can pick up the config accordingly

@jannyHou Should we create a spike story to figure out the direction we want to take? That way we can properly plan the work/time needed for this research.

**Comment by jannyHou** [comment]
@bajtos A spike sounds good to me.

I think the following description could be the acceptance criteria for that spike:

> What we need to figure out:
How to define datasources and repositories in such way that integration/acceptance tests and test-data builders can tweak the configuration.
How to write test-data builders in such way that tests can provide a modified datasource configuration. For example, test-data builders can accept a datasource instance or a repository instance initialized by the actual test to use the correct datasource configuration.
How to tweak datasource config in acceptance and integration tests and use that tweaked configuration for test-data builders too.
Let's keep this issue focused on database-backed datasources only. Testing Services is out of scope, see #1311 for that.

And two candidate approach are:

- create api to generate the datasource dynamically
- provide env based settings, boot can pick up the config accordingly

How about turn this story to a spike then create new one for implementation?

**Comment by bajtos** [comment]
>  How about turn this story to a spike then create new one for implementation?

Sounds good 👍

**Comment by BostjanPisler** [comment]
Easy fix is to export testdb config in testdb.datasource and then bind the config object to app's datasource.

`app.bind('datasources.config.db').to(config);`
