### ISSUE TITLE
TestSandbox random dir generation

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1398]
## Description / Steps to reproduce / Feature proposal

Current TestSandbox uses the same folder the user provides for tests. If a file put in the sandbox is `require`d, it gets cached by it. A workaround for clearing the cache was introduced in #1391 but as per the comments, https://github.com/strongloop/loopback-next/pull/1391#issuecomment-394579019, decaching has it's own challenges.

## Current Behavior
- Before PR #1391, files get cached -- can break tests. Issues with multiple tests running in parallel.
- After PR #1391, files are decached but not a robust implementation. Multiple tests in parallel still an issue.

## Expected Behavior
TestSandbox should create a random folder in the given path (can be considered a basepath). When the sandbox is reset, instead of decaching -- we delete the old random folder and create a new one for the user. Similar behaviour as used in `loopback-boot`, see comment https://github.com/strongloop/loopback-next/pull/1391#issuecomment-394733995

## Acceptance Criteria
- [ ] Given a path for a TestSandbox (like present) - the instance should create a random folder inside that for the test
- [ ] When the TestSandbox instance is reset, the randomly generated folder should be deleted. A new random folder should be generated -- prevent issues with caching and parallel tests.
- [ ] Provide convenience methods on TestSandbox instance such as `sandbox.resolve()`, `sandbox.existsFile()`, `sandbox.existsDir()`, etc. -- to make working with sandbox easier as we now have random folders being generated -- this should be an abstraction from the user of TestSandbox.
- [ ] Tests
- [ ] Docs (TestSandbox is currently lacking documentation). 

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by jannyHou** [comment]
@dhmlau could you label this issue properly? Thanks. It's estimated.

**Comment by dhmlau** [comment]
@jannyHou @virkt25 , what's the impact of not fixing it (or deferring it after DP3)?

**Comment by virkt25** [comment]
For now the issue has a temporary fix. This doesn't need to be a part of DP3 IMO.
