### ISSUE TITLE
@loopback/rest: HttpHandler integration test times out after 2 seconds randomly

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#1407]
## Description / Steps to reproduce / Feature proposal

Run `npm test` from `loopback-next`.

## Current Behavior

Sometimes (not always) the http handler integration test fails with timeout.

```
1) HttpHandler
       with a body request route
         returns 400 for malformed JSON body:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/rfeng/Projects/loopback4/loopback-next/packages/rest/dist8/test/integration/http-handler.integration.js)
```

## Expected Behavior

It should pass consistently.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by hacksparrow** [comment]
Tried many times, not seeing it. Anyone else want to give it a go?

**Comment by hacksparrow** [comment]
Got a timeout error but in a different location:

```
  1) HttpCachingProxy
       proxies HTTP requests:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/ibm/projects/loopback-next/packages/http-caching-proxy/dist8/test/integration/http-caching-proxy.integration.js)
```

**Comment by dhmlau** [comment]
Since it's marked as a bug, I'd like to tag it as DP3.   Putting into our backlog.

**Comment by hacksparrow** [comment]
@bajtos did https://github.com/strongloop/loopback-next/pull/1415 fix the intermittent this too?

**Comment by bajtos** [comment]
> did #1415 fix the intermittent this too?

It's possible, but I don't really know, TBH. I haven't seen any timeouts recently though.

**Comment by bajtos** [comment]
I encountered a timeout recently, the test was not able to resolve `example.com` hostname into an address. This is very surprising considering that we have two tests (HTTP and HTTPS) and only one of them failed.

**Comment by bajtos** [comment]
I am proposing to increase the timeout of HttpCachingProxy tests that are talking to internet from the current default 2 second to something like 10 or even 30 seconds in order to accommodate for slow connections.

Thoughts?

**Comment by virkt25** [comment]
+1 - I’m experiencing timeouts with example-todo tests using caching in #1437

**Comment by bajtos** [comment]
Let's see if https://github.com/strongloop/loopback-next/pull/1442 can improve the situation.

**Comment by dhmlau** [comment]
@bajtos , does the PR #1442 help?  Is this ticket good to close?

**Comment by raymondfeng** [comment]
IIRC, there are two types of timeout we're after:

1. The timeout in the Todo application. I confirm it's due to the external Geo service.
2. The timeout in `HttpCachingProxy`. I'm not sure what's the root cause.

**Comment by virkt25** [comment]
Closing this as I haven't seen any recent build failures due to a timeout associated to this locally or on CI. We can reopen / create new issue if it shows up again.
