### ISSUE TITLE
@inject support for ctor args

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#142]
_From @ritch on April 13, 2017 17:31_

See https://github.com/strongloop/loopback-next/blob/master/packages/loopback/lib/application.ts#L20

My basic impl idea:

 - [x] implementing `inject(binding)(arg)`
 - [x] setting metadata using `Reflect.setMetadata()`
 - [x] invoking `new ctor()` by `ctro.apply(ctor, injectedArgs`
 - [x] create `injectedArgs` array from `Reflect.getMetadata(ctor)`

_Copied from original issue: strongloop-internal/scrum-asteroid#94_

**Comment by bajtos** [comment]
Done.
