### ISSUE TITLE
[RFC] Documentation for Mixin related topic

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1425]
## Description / Steps to reproduce / Feature proposal
To continue the discussion from https://github.com/strongloop/loopback-next/pull/1423, I'd like to get inputs on what we are going to do with the Mixin related documentation: 

1. http://loopback.io/doc/en/lb4/Language-related-concepts.html
It was removed from the sidebar in PR #1157 , however, the page still exists.  Not sure if there is a need to keep it. 

2. http://loopback.io/doc/en/lb4/Mixin.html
It was removed from the sidebar from the same PR #1157.  According to @shimks , it was meant to incorporate the content from this page to the Extending LB documentation.  Should we remove it? (@virkt25 might know the best?)

3. There is documentation on mixin in the [extending application](http://loopback.io/doc/en/lb4/Creating-components.html#extending-application-with-mixins). Do we need it to cover for mixin with other LB artifacts?

**Comment by jannyHou** [comment]
@dhmlau I think 1 and 2 could be removed. 3 is enough to guide people how to extend the framework by mixins. 
I would say quickly go through 1 and 2, if there is anything useful/we want to keep, merge them into 3. Then delete 1 and 2.
