### ISSUE TITLE
[CLI] Refactor Integration Tests to avoid duplication in test code

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1427]
## Description / Steps to reproduce / Feature proposal

As we add more `artifact` generators (such as `controller` / `datasource` / `model`), a pattern is emerging where some of the tests are being repeated across such generators.

Example tests (`it` names):
- does not run without package.json
- does not run without the loopback keyword

Example files for above (line #'s may change -- look for above tests)
- https://github.com/strongloop/loopback-next/blob/master/packages/cli/test/integration/generators/controller.integration.js#L49-L69
- https://github.com/strongloop/loopback-next/blob/master/packages/cli/test/integration/generators/datasource.integration.js#L80-L100

We should find a way to refactor those tests (and any other identical tests) to a base test suite we run for all `artifact` generators similar to how we have `base tests`. For inspiration, see: https://github.com/strongloop/loopback-next/blob/master/packages/cli/test/integration/lib/base-generator.js

## Current Behavior

- Repeated tests.

## Expected Behavior

- DRY code, don't repeat tests

## Acceptance Criteria
- [ ] Identify other tests repeated across artifact generator integration tests (and other types of tests)
- [ ] Refactor such tests into a standalone base integration test file
- [ ] Replace the tests from the files to the base tests -- ensure coverage doesn't drop

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
I'd think this is out of scope for DP3. 

@raymondfeng @bajtos , feel free to modify the tags if you think otherwise.

**Comment by bajtos** [comment]
Yeah, let's move this to GA backlog.
