### ISSUE TITLE
Order Independent Binding Resolution

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#143]
[Proposal discussion](https://github.com/strongloop/loopback-next/issues/139)

As a ext dev, I should be able to get any value (eg. start time, end time, response status), regardless of WHEN these values are set.

```ts
function myExt(@inject('result.status') status) {
  if (status !== 200) {
    console.error(ctx);
  }
}

@bind('result.status')
function myOtherExt(@inject('error') err) {
  if (error) {
    return 500;
  } else {
    return 200;
  }
}
```

- [ ] Finalize design
- [ ] Acceptance tests
- [ ] Basic impl for hard use cases (eg. res.status, res.time)
- [ ] Update loopback-next-example
- [ ] Update Docs

**Comment by bajtos** [comment]
Closing as no longer relevant.
