### ISSUE TITLE
[Spike] Deploy LB4 applications to IBM Cloud

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1446]
**Timeboxed to 1 and a half week** based on the assumption that the person assigned to the task would be investigating different kinds of deployment systems.

Find out what's needed to deploy LB4 applications to IBM Cloud and write a short document describing the steps.

Take our existing [Todo application](https://github.com/strongloop/loopback-next/tree/master/examples/todo) as the project to deploy, but make the following changes:

- Use [Cloudant](https://console.bluemix.net/catalog/services/cloudant) (free Lite plan) to persist our Todo items. To do so, we need to temporarily modify `db` datasource to use `cloudant` connector and add this connector to project dependencies. 
- When deploying to IBM Cloud, the application must be configured to use a cloud-based Cloudant instance.
- When developing and testing locally, the app should use local docker-based [Cloudant Developer Edition](https://hub.docker.com/r/ibmcom/cloudant-developer/).
- There may be other settings we need to tweak when deploying to cloud, for example the port number where to listen.

Besides the deployment guide, this spike should also identify the biggest pain points - things we need to improve to make the deployment experience smoother.

## Acceptance criteria

- [x] A feature branch in loopback-next containing `examples/todo` changes needed to persist data in Cloudant. 
- [x] A "do not merge" pull request from the feature branch which has been reviewed and approved at least by @raymondfeng and @bajtos
- [ ] A deployment guide for IBM cloud added to our docs. If the current LB4 feature-set is not sufficient to support such deployments, then create a new [wiki](https://github.com/strongloop/loopback-next/wiki) page instead of an official doc article.
- [ ] A list of pain points - steps that are difficult to perform and should be simplified. The list can be posted as a comment here in this issue.

**Comment by jannyHou** [comment]
- possible choice: cloud foundry/ku8/docker
  - figure out which one to use

**Comment by jannyHou** [comment]
Let's revisit the issue after discussion meeting.

**Comment by jannyHou** [comment]
@raymondfeng Could you add more details and your expectations of the spike? Thanks!

**Comment by dhmlau** [comment]
According to the estimate/time mapping for spikes from @shimks , marking this as `13` points.

**Comment by virkt25** [comment]
@hacksparrow I know you went over the pain points in the spike meeting. Can you document them here for future reference (include issues you've already created) and we can close out this task then as a new issue #1604 has been created to track the documentation work.

**Comment by hacksparrow** [comment]
**PULL REQUEST**
https://github.com/strongloop/loopback-next/pull/1574

**FINDINGS**
1. It is relatively simple to deploy a LB4 app to IBM Cloud Cloud Foundry.
2. It is possible to switch to a provisioned database service on IBM Cloud, without having to hard-code credentials and other service details.
3. We may need a post-boot extension point for modifying datasource configuration.
_"Ideally, one should be able to write a VCAP/CloudFoundry extension for LB4 that will plug into an extension point which will allow the extension to modify datasource configuration."_ - Miroslav

**PAIN POINTS**
1. `lb model` should prompt repository selection/creation - https://github.com/strongloop/loopback-next/issues/1587
2. Need a `lb` command to generate repositories - https://github.com/strongloop/loopback-next/issues/1588

**SUBSEQUENT ACTIONS**
1. Spike "Deploy a basic LB4 application to IBM Cloud Kubernetes" - https://github.com/strongloop/loopback-next/issues/1606
2. Task "Generate IBM Cloud artifacts" - https://github.com/strongloop/loopback-next/issues/1614

**Comment by hacksparrow** [comment]
@dhmlau @virkt25 does that look good?

**Comment by virkt25** [comment]
LGTM. So is this Spike good to close out as there are follow up tasks for all other issues / pain points?

> Juggler cannot resolve connectors in our monorepo - https://github.com/strongloop/loopback-next/blob/master/examples/soap-calculator/src/datasources/calculator.datasource.ts#L13-L17

I don't think there is much we can do about this ... this won't impact a user as they won't be developing their application within our monorepo.

**Comment by bajtos** [comment]
The acceptance criteria contains the following items that are not checked as done yet:

- A deployment guide for IBM cloud added to our docs. If the current LB4 feature-set is not sufficient to support such deployments, then create a new wiki page instead of an official doc article.

-  A list of pain points - steps that are difficult to perform and should be simplified. The list can be posted as a comment here in this issue.

I think the list of pain points has been sufficiently described in https://github.com/strongloop/loopback-next/issues/1446#issuecomment-413566643.

However, it looks like we are missing a pull request or a follow-up issue to write the deployment guide. @hacksparrow is my assessment correct? What is the plan for making the deployment guide happen?

**Comment by hacksparrow** [comment]
@bajtos https://github.com/strongloop/loopback-next/issues/1604 is the follow-up is for the documentation.
