### ISSUE TITLE
Example of Authentication Package

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#145]
As a user of the example app, I should be able to follow the example so that I can enable authentication in my app.

[See this example for details.](https://github.com/strongloop/loopback-next/blob/master/packages/authentication/test/acceptance/authentication/feature.md)

- [x] Bind Authentication username/password to the app #151 @rashmi
- [x] End-to-end example of everything working together (includes work at #136 @deepakrkris and #150 @siddhipai @mpatsute)

**Comment by rashmihunt** [comment]
PR - https://github.com/strongloop/loopback-next/pull/249
