### ISSUE TITLE
Handle IPv6 localhost URLs in http-server package

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#1453]
## Description / Steps to reproduce / Feature proposal

`http-server` does not format IPv6 address properly in its `url` property.

Discussion: https://github.com/strongloop/loopback-next/pull/1369#discussion_r193506651

## Current Behavior

Eg: `https://:::51492`

## Expected Behavior

Eg: `https://[::]:51492`

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
I assume from the discussion in #1369, we agree to include it in DP3?

**Comment by hacksparrow** [comment]
Fixed via https://github.com/strongloop/loopback-next/pull/1454.
