### ISSUE TITLE
[Spike] Deploy LB4 applications to Amazon AWS

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1465]
Find out what's needed to deploy LB4 applications to Amazon AWS and write a short document describing the steps.

See #1446 for more details and acceptance criteria.

**Comment by dhmlau** [comment]
Moving out of GA scope, keeping deploying to IBM Cloud as the first priority in the same epic.

**Comment by dhmlau** [comment]
We'll be focusing on the vendor agnostic approach, i.e. deploy to k8s.  Removing from TOB.

**Comment by jdriesen** [comment]
Hi,
Any idea when we can deploy to AWS ?
Is this already defined on the Roadmap ?

Thanks in advance for your reply
Johnny Driesen
Belgium

**Comment by bajtos** [comment]
> OK ... time now to deploy my App 'in the cloud...'
> Using AWS since years, since it's still the most popular one... (sorry to say, I'm aware you've an IBM relation)

Even though we have our own cloud at IBM, we are happy to support LoopBack users running on any other cloud of their choice. https://www.ibm.com/blogs/think/2018/03/how-to-bolster-your-multi-cloud-strategy/

> Can I kindly ask when deploying to AWS will supported ?

I am afraid we have many other tasks that we consider more important as this one.

> Succeeded in uploading a project using Docker and AWS Elastic Beanstalk...

Yes, we already support Docker-based deployments. When you scaffold a new LB4 project using our `lb4` tool, you will get a default `Dockerfile` to get you started.

You can find more details about Docker-based deployments here: https://loopback.io/doc/en/lb4/deploying_to_ibm_cloud_kubernetes.html

**Comment by saidineshgarapati** [comment]
> Hi devs,
> 
> First of all, congratz with the development of LB4 !
> It generates nice and clean code.
> And it runs very smoothly, at least... in my Dev Environment.
> 
> OK ... time now to deploy my App 'in the cloud...'
> Using AWS since years, since it's still the most popular one... (sorry to say, I'm aware you've an IBM relation)
> 
> See https://www.gartner.com/reviews/market/public-cloud-iaas/compare/amazon-web-services-vs-ibm.
> Compare the number of reviews ...
> 
> Having in mind... "a TSC generates JS Code" ... it can't be that hard to deploy.
> So, I wasn't expecting problems at all...
> 
> After trying, searching and struggling for many hours (not to mention days...), I arrived at this site.
> 
> Pity to see that TOB label has been removed, especially because you've the best product on the market at this moment !
> 
> Can I kindly ask when deploying to AWS will supported ?
> (in other words... is this already defined on your Roadmap ?)
> 
> **Update**:
> After a couple of days trial and error ...
> Succeeded in uploading a project using Docker and AWS Elastic Beanstalk...
> 
> Thanks in advance for your reply
> 
> Kind regards,
> 
> Johnny Driesen
> Senior Dev.
> Belgium

Hi Johnny Driesen, I am glad you succeeded in uploading a project using Docker and AWS loopback on AWS. I am trying on achieving the same.  Can you please share the procedure you followed in uploading a project using Docker and AWS Elastic.

**Comment by lonewolfaka9** [comment]
+1

**Comment by lonewolfaka9** [comment]
> > Hi devs,
> > First of all, congratz with the development of LB4 !
> > It generates nice and clean code.
> > And it runs very smoothly, at least... in my Dev Environment.
> > OK ... time now to deploy my App 'in the cloud...'
> > Using AWS since years, since it's still the most popular one... (sorry to say, I'm aware you've an IBM relation)
> > See https://www.gartner.com/reviews/market/public-cloud-iaas/compare/amazon-web-services-vs-ibm.
> > Compare the number of reviews ...
> > Having in mind... "a TSC generates JS Code" ... it can't be that hard to deploy.
> > So, I wasn't expecting problems at all...
> > After trying, searching and struggling for many hours (not to mention days...), I arrived at this site.
> > Pity to see that TOB label has been removed, especially because you've the best product on the market at this moment !
> > Can I kindly ask when deploying to AWS will supported ?
> > (in other words... is this already defined on your Roadmap ?)
> > **Update**:
> > After a couple of days trial and error ...
> > Succeeded in uploading a project using Docker and AWS Elastic Beanstalk...
> > Thanks in advance for your reply
> > Kind regards,
> > Johnny Driesen
> > Senior Dev.
> > Belgium
> 
> Hi Johnny Driesen, I am glad you succeeded in uploading a project using Docker and AWS loopback on AWS. I am trying on achieving the same. Can you please share the procedure you followed in uploading a project using Docker and AWS Elastic.

@saidineshgarapati  I was able to deploy the demo project on  beanstalk after getting an error with the PORT number I replaced 
EXPOSE ${PORT} to EXPOSE 3000 and it worked.

I'm not trying to create a pipeline from bitbucket to do deployment in beanstalk I will surely update here if anybody needs help.
