### ISSUE TITLE
[API Explorer] Fields shown but ignored

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1470]
## Description / Steps to reproduce / Feature proposal

From #1206 

For `examples/todo`, in the API Explorer, clicking on the `Try it Out` shows `id` (with a default value of `0`) as an option for all requests but the field is ignored by some calls such as `POST` for creating a new `id`. Remove this field from the API explorer for calls that do not honour it. 

## Current Behavior

- `id` field is shown for all requests and ignored by some of the REST calls.

## Expected Behavior

- `id` field and others only show in API Explorer for REST calls that will honour the Call.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
This is tricky to address, it requires us to emit different OpenAPI schema for different REST endpoints - see https://github.com/strongloop/loopback-next/issues/1179.

**Comment by jannyHou** [comment]
Let's open a new issue to discuss the following points:

- Figure out how to describe the excluded properties as partial of the model.
- How to map the partial model to Openapi schema.

**Comment by dhmlau** [comment]
Discussed with @raymondfeng , both this task and the spike task that @jannyHou is going to create will be `postGA`.  @jannyHou , please mark the new ticket as `postGA`. thanks.

**Comment by bajtos** [comment]
> I followed the Todo tutorial and generated the CRUD controller with the cli. In the API Explorer,  when I try the GET `/todos` request and enter `{ "where": {"id": "1"} }` in the filter and click execute, it is ignored. It doesn't appear in the request URL and results are not filtered.

This is a limitation of API Explorer and the OpenAPI spec in general :(

Please refer to the discussion in https://github.com/strongloop/loopback-next/pull/1679 for more details, see also https://github.com/swagger-api/swagger-js/issues/1385

**Comment by nabdelgadir** [comment]
Now that https://github.com/strongloop/loopback-next/pull/3297 is landed, the `id` property is excluded when making a `POST` request and developers have the option to exclude other properties as they see fit. Closing this issue as done.
