### ISSUE TITLE
[REST] Consistent response format for PATCH/PUT

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1471]
## Description / Steps to reproduce / Feature proposal

From #1206 

A `PATCH` / `PUT` request returns `true` while other REST endpoints return a JSON output. Should these methods also return a JSON response to be consistent?

## Current Behavior

- Returns a `boolean` for PATCH / PUT

## Expected Behavior

- Return `JSON` ... something like `{success: true}` or `{result: <value-returned-by-juggler>}`
- Update existing code / templates / tests

cc: @strongloop/sq-lb-apex @raymondfeng @bajtos Thoughts? Is this the intended behaviour or a bug? If it's the intended behaviour, do we want to look into changing it for LB4?

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
+1 for returning a JSON like `{success: true}` or perhaps `{result: <value-returned-by-juggler>}`.

Please note that we cannot return full model data in most cases. It would require another database command to fetch the updated model instance, which would introduce race condition.

I am going to label this as a bug and assign to Core-GA backlog for consideration.

**Comment by jannyHou** [comment]
+1 for returning a JSON result. Agree with Miroslav's comment. And it also allows we to customize result details, e.g. Cloudant includes which data fails update and which one passes.

**Comment by bajtos** [comment]
In #1723, I reworked methods returning `boolean` to return `undefined` and report "model not found" via 404 Not Found error.

However, the following endpoints are still returning a naked number:

- `PATCH /my-models` (`repo.updateAll(data, where)`) returns a number of updated instances.
- `GET /my-models/count` (`repo.count(where)`) returns a number of instance found.

I think we should rework these two endpoints to wrap the number in an object:

```json
{
  "count": 123
}
```

For reference, here is the LoopBack 3.x behavior:
 - [count](https://loopback.io/doc/en/lb3/PersistedModel-REST-API.html#get-instance-count) returns an object with `count` property, e.g. `{count: 6}`.
 - [updateAll](http://apidocs.loopback.io/loopback/#persistedmodel-updateall) returns an object with `count` property too.
