### ISSUE TITLE
Demo scenario: Shopping Cart Component

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1481]
## Description / Steps to reproduce / Feature proposal
As part of the e-commerce store demo scenario in #1476, this task is to create the Shopping Cart component.  Shopping cart data will be stored in a distributed in-memory cache, e.g. Redis.

Questions:
- Are we going to use Redis?
  - Yes
- Is it going to be another LB app?  If so, then I believe it will be blocked by #1447  (KeyValue Repository task)
  - Controller within the same application that uses the KVRepository.

## Acceptance Criteria
- [x] Controller + KV Repository for Redis Database
- [x] Mockup / Dockerize a Redis Instance for use with this
- [x] Simple Model: Cart (id) containing multiple Products (ids + quantity)
- [x] A REST API controller either full CRUD or at least the APIs that make sense for this component

**Comment by bajtos** [comment]
Yes, this is blocked by #1447, I am relabelling this story as `p2`.

**Comment by bajtos** [comment]
In progress by @raymondfeng - see https://github.com/strongloop/loopback4-example-shopping/pull/4

**Comment by bajtos** [comment]
The acceptance criteria don't not describe any Controller (REST API), is that intentional?

IMO, a shopping cart component is not complete without a REST API to access the data.

**Comment by virkt25** [comment]
@raymondfeng Is this good to close?

**Comment by raymondfeng** [comment]
@virkt25 Please review https://github.com/strongloop/loopback4-example-shopping/pull/13 1st.

**Comment by raymondfeng** [comment]
One last piece: https://github.com/strongloop/loopback4-example-shopping/pull/14

**Comment by dhmlau** [comment]
Closing as resolved.
