### ISSUE TITLE
Demo scenario: Product Recommendation component

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1482]
## Description / Steps to reproduce / Feature proposal
As part of the e-commerce store demo scenario in #1476, this task is to create the Product Recommendation component.  Information will be fetched from a SOAP/REST service.

Questions:
- Do we want SOAP service instead of REST service? 
    - Use REST for now, SOAP can be a different branch / service at a later date. The main concept to show off is the Service Proxy integration / Usage.

## Acceptance Criteria
- [ ] Controller using service proxy to talk to Product Recommendation REST API
- [ ] Mockup of Product Recommendation Service (Express / LoopBack App / Serverless Function).

**Comment by shimks** [comment]
Not groomed. Pls groom

**Comment by b-admike** [comment]
I don't have a strong opinion on whether the operation(s) depend on SOAP service(s) or REST API, but if the other components are using REST, then we might want to use SOAP for diversity.

**Comment by raymondfeng** [comment]
Let's start with REST and add SOAP if necessary.
