### ISSUE TITLE
`lb4 model` Declarative Support

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1491]
## Description

In version 3.x, LB has declarative (JSON / YAML) and programatic support for creating / declaring models. This is an important feature for LB that should have parity in LB4. Some reasons why declarative support is important:
- Better Developer Experience, gives flexibility to choose declarative / programatic programming model
  - In LB4, Programatic involves a TS Class + Decorators for metadata
- We should promote separation of concerns between metadata and TS Classes.
  - Declarative gives ability to read / write metadata iteratively
- Declarative allows metadata to be manipulated by tooling (CLI, workspace, etc).

### Spike Results

Declarative support for models was explored in https://github.com/strongloop/loopback-next/compare/boot-spike?expand=1

### Proposal
- CLI creates a JSON file in `src/models/todo.model.json` to store metadata
- CLI creates a Base Class that the actual class can extend. Will have a note stating this class may be regenerated and shouldn't be edited. Declares properties w/ types for a strongly typed class. File: `src/models/_generated/todo.base.model.ts`
- CLI creates an actual Model Class as follows: `src/models/todo.model.ts` that extends the generated base class. Users can programatically extend this class if they want!
    - **NOTE:** There seems to be a bug with just setting just the `static definition` OR `@model` and the `swagger-ui` URL ... it seems to only show properties decorated with `@property` decorator for the Model in the explorer.
- `lb-build` regenerates the Base Class with each build. (Document this requirement -- or provide scripts in a `bin` folder or something to regenerate models as a `prebuild` step for users using regular `tsc` ... they will also need a script to copy over `json` files to the `dist` folder. _(I personally think we should just document the need for `lb-build` and tell users to use that.)_
- `lb-clean` cleans the the `_generated` folder. (Or a similar script).
- JSON to class generation logic + the logic in CLI should come from a shared source ... `@loopback/utils`? `@loopback/build`? etc. -- Ensures consistency with generation process.

#### Alternative
- An alternative proposed by @raymondfeng was to have weakly typed classes instead of strongly typed classes (Since connectors depends on metadata and not actual class properties). PROS: Doesn't require regeneration. CONS: Poor DX as lack of type information in Model Class. _(I personally prefer strongly typed classes)_ 

### Needs Discussion
- Are we ok with this proposal? What are some pitfalls? Alternatives?
- Code Generation: Do we only generate code once and let the developer maintain the JSON / Code OR do we provide solution to keeping generated code in sync with declarative options (like the proposl above)?

### Acceptance Criteria

_To be flushed out based on discussion_

**Comment by bajtos** [comment]
I'd like to propose a radically different approach: let's use AST (abstract syntax tree produced by the TypeScript parser) to programmatically access and modify model definitions. I believe that  ES6+ and TypeScript added enough structure in the form of classes, decorators and module imports to make this approach feasible. 

Sure, it will take more time to get there, especially the initial part where we need to find out how to work with AST. However, the benefits are tremendous. No need to keep `_generated` files around and jump between generated and user-written classes when navigating through the code, etc.

Thoughts?

**Comment by virkt25** [comment]
I had considered the idea before but didn't explore it further because of the amount of time it would've taken to learn about the compiler and working with the AST. That said ... if we are willing to put in the time I'd like to learn more about the AST as it would be an interesting new challenge to explore. Some questions:

- Is the plan to add the properties to the class using AST at compile time?
- How does that affect the developer experience for when the JSON changes?
- Do we support a watcher (the compiler has support for it)?

---

A good read: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API
