### ISSUE TITLE
Duplicate Purpose text in docs/site/todo-tutorial-scaffolding.md 

### ISSUE THREAD

**Issue by jimmymcpeter** [strongloop/loopback-next#1497]
## Description / Steps to reproduce / Feature proposal
Hi,

At the bottom of [docs/site/todo-tutorial-scaffolding.md](https://github.com/strongloop/loopback-next/blob/master/docs/site/todo-tutorial-scaffolding.md#structure) you have a Structure section with a files table.  It looks like the `Purpose` text in the table for `src/datasources/README.md` and `src/models/README.md` are both the same.  Likely a copy and paste error.

## Current Behavior

Both Purposes read:
> Provides information about the datasources directory, how to generate new datasources, and where to find more information.

## Expected Behavior

Update the `src/models/README.md` Purpose text

**Comment by jannyHou** [comment]
@jimmymcpeter Thank you! Good catch, fixing it now.

**Comment by jannyHou** [comment]
fixed in https://github.com/strongloop/loopback-next/pull/1498, closing it.
