### ISSUE TITLE
Refactor loopback-datasource-juggler into multiple modules

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#15]
There are many responsibilities in [loopback-datasource-juggler](https://github.com/strongloop/loopback-datasource-juggler) today. We need to decompose them into separate modules for different concerns. 

The following slides outline some of the main perspectives around juggler as potential candidates:

[LoopBack-Model-Composition.pptx](https://github.com/strongloop/loopback-next/files/727282/LoopBack-Model-Composition.pptx)

**Comment by superkhau** [comment]
We should close this as part of you landing https://github.com/strongloop/loopback-next/pull/392

**Comment by dhmlau** [comment]
@raymondfeng, is it good to close?
