### ISSUE TITLE
Add Snyk to loopback-next

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1516]
## Description / Steps to reproduce / Feature proposal

Currently we don't have Snyk support in this repo under the Strongloop account.

- [ ] Enable Snyk under Strongloop account for this repository
- [ ] Ensure Snyk-bot works with monorepo **OR** use `snyk` npm package to write a custom script using `lerna` to work with the monorepo (Inspiration: https://github.com/forcedotcom/salesforcedx-vscode/pull/467)

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
We now have Renovate bot to update the dependencies.
