### ISSUE TITLE
Error messages not being sent in the response

### ISSUE THREAD

**Issue by marioestradarosa** [strongloop/loopback-next#1528]
## Steps to reproduce
Currently if you point to GET  /model/anyvalidvalue  such as GET /fruits/200 where the fruit ID 200 does not exist 

## Current Behavior
You will get only the _http status_ **500,** no error message saying "no <model> found with id <anyvalidvalue>". Not even custom error messages are being exposed to the client application.

Relates to #1469

## Expected Behavior
Received the correct http err status but most important is that  the appropriate error message comes in the json object.

**More details and our work  around** 
Our simple solution as app developers to give demos so far was to include the following code in the _sequence.ts_ in our **LB4** test application.

**From** 
```javascript
 } catch (err) {
      this.reject(context, err);
}
```
**To** 
A temporarily solution for our demos. *Note:* We tried {expose:true} alone but still didn't work

```javascript
} catch (err) {
      err = Object.assign({errorMessage: err.message, expose: true}, err);
      this.reject(context, err);
}
```

With the latter, then LB4 is sending an appropriate message so far in our new property errorMessage. I understand this is just a work around,.

**Comment by virkt25** [comment]
Related to https://github.com/strongloop/loopback-next/issues/1469

**Comment by dhmlau** [comment]
@marioestradarosa, thanks for bringing it up.  I'd like to close this ticket in favor of #1469.  Please continue the discussion there.  Thanks.
