### ISSUE TITLE
[CLI] `lb4 model` strict prompt

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1530]
## Acceptance Criteria

- [ ] Add a prompt to explain / ask user if they would like the model to be `static` or not (default to current behaviour). Update template to include that when not the default.

**Comment by bajtos** [comment]
Cross-posting from our [Model](https://github.com/strongloop/loopback-next/blob/master/docs/site/Model.md) docs:

To create a model that allows both well-defined but also arbitrary extra properties, you need to disable strict mode in model settings and tell TypeScript to allow arbitrary additional properties to be set on model instances.

```ts
@model({settings: {strict: false}})
class MyFlexibleModel extends Entity {
  @property({id: true})
  id: number;

  // Define well-known properties here

  // Add an indexer property to allow additional data
  [prop: string]: any;
}
```

**Comment by nabdelgadir** [comment]
Closing as done https://github.com/strongloop/loopback-next/pull/2204.
