### ISSUE TITLE
HasMany Docs & Implementation Inconsistent

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1533]
## Description / Steps to reproduce / Feature proposal

- The second bullet in this section https://loopback.io/doc/en/lb4/HasMany-relation.html#configuring-a-hasmany-relation says:

> Declare a property with the factory function type **HasManyRepositoryFactory<targetModel, typeof sourceModel.prototype.id>** on the source repository class.

BUT in code, the implementation has `id` and `targetModel` flipped as follows for the `HasManyRepositoryFactory`:
```
HasManyRepositoryFactory<SourceID, Target extends Entity>
```
---

While the doc is an easy fix, my question is which form is correct? 

- `EntityCrudRepository<Target, TargetID>` -- Takes Target first.
```
DefaultHasManyEntityCrudRepository<
  TargetEntity extends Entity,
  TargetID,
  TargetRepository extends EntityCrudRepository<TargetEntity, TargetID>
> implements HasManyRepository<TargetEntity>
```
Above takes Target Model first.
- `class CrudRepositoryImpl<T extends Entity, ID>` - Takes Target first

---

## Acceptance Criteria
- [ ] Update implementation to be consistent with other implementations as outlined above i.e. it should take `Target` and then `SourceID` type.
- [ ] Update docs to be consistent with implementation
- [ ] Mark this as a **breaking change!!**

**Comment by shimks** [comment]
The reason we switched to `<SourceID, Target>` form was because we wanted to annotate from source model to target model.

That being said, it does seem counter intuitive for people that aren't familiar with relations. I think I'd be ok with the proposed solution.

**Comment by bajtos** [comment]
Initially, we have `<Target, SourceID>`. I proposed to switch the order, looks like the docs were not updated as part of that change.

I don't mind much whether we choose `<Target, SourceID>` or `<SourceID, Target>` as the order or template arguments.

However, we need to get the docs in sync with the actual implementation.

**Comment by b-admike** [comment]
> While the doc is an easy fix, my question is which form is correct?
> 
> EntityCrudRepository<Target, TargetID> -- Takes Target first.
> DefaultHasManyEntityCrudRepository<
>   TargetEntity extends Entity,
>   TargetID,
>   TargetRepository extends EntityCrudRepository<TargetEntity, TargetID>
> > implements HasManyRepository<TargetEntity>
> Above takes Target Model first.
> 
> class CrudRepositoryImpl<T extends Entity, ID> - Takes Target first

`DefaultHasManyEntityCrudRepository` is describing the type of the (constrained) target repository so it only depends on the target model and its ID. But yeah good catch on the doc fix, it should be updated!

**Comment by bajtos** [comment]
> I still think it should take model first and the idType but 🤷‍♂️

Yeah, I think it makes more sense to me too.

How about renaming `SourceID` to `FK` or `ForeignKey`? Then we would have a reasonable pair `(Target, ForeignKey)`.

**Comment by virkt25** [comment]
> How about renaming SourceID to FK or ForeignKey? Then we would have a reasonable pair (Target, ForeignKey).

+1. Just a comment / suggestion would be that technically it takes the `ForeignKeyType` not the `ForeignKey` ... since in all places I've seen us pass in `typeof Customer.prototype.id`.

**Comment by b-admike** [comment]
>I still think it should take model first and the idType but 🤷‍♂️

Sorry, I misunderstood the proposal. I'm okay to have it as `model` first and the source Id type after 👍 

> How about renaming SourceID to FK or ForeignKey? Then we would have a reasonable pair (Target, ForeignKey).
> 
> +1. Just a comment / suggestion would be that technically it takes the ForeignKeyType not the ForeignKey ... since in all places I've seen us pass in typeof Customer.prototype.id.

`(Target, ForeignKeyType)` sounds good.
