### ISSUE TITLE
[CLI] `lb4 app` not reflecting HTTPS features

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#1542]
## Description / Steps to reproduce / Feature proposal

The app generated by `lb4 app` doesn't seem to be using the latest `@loopback/http-server` and `@loopback/rest`, which should include the HTTPS features.

## Current Behavior
Dependencies `@loopback/http-server` and `@loopback/rest` are not updated to the latest although their package version seems to say so.

## Expected Behavior

Dependencies `@loopback/http-server` and `@loopback/rest` should have the latest code.

@virkt25 any ides what's going on?

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by virkt25** [comment]
What version of `@loopback/rest` are you seeing? I just installed the latest version of the CLI `npm i -g @loopback/cli` and then created an app `lb4 app version-test` and the `package.json` shows the latest dependencies listed. 

![image](https://user-images.githubusercontent.com/3311536/42826722-1a1ca480-89b3-11e8-98ee-8ddf6b67c284.png)

**Comment by dhmlau** [comment]
@hacksparrow , are you still seeing this issue? or you're not using the latest cli?

**Comment by hacksparrow** [comment]
Works now.
