### ISSUE TITLE
compile error in generated model ts file when using lb4 model

### ISSUE THREAD

**Issue by mgleland** [strongloop/loopback-next#1562]
## Description / Steps to reproduce / Feature proposal
lb4 model
name it, etc
add a property of type array, and type object, using the cli

## Current Behavior
generated code is:
...
  @property({
    type: 'array',
    arrayType: object,

  })
  fields?: object[];

with the error (at least in vscode): Cannot find name 'object'. Did you mean 'Object'?  (the object after arrayType: has the squiggly line)
 
## Expected Behavior
no error in generated code ;-)

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by marioestradarosa** [comment]
Because it is inside the @property decorator, the sintax should be 
    `arrayType: 'object',`  as opposed to `arrayType: object`

**Comment by shimks** [comment]
Fixing this as of now
