### ISSUE TITLE
Booting Services

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1576]
## Description / Steps to reproduce / Feature proposal

- From #1560, it can be seen that there is a need to boot a `service`.

## Acceptance Criteria

- [ ] `ServiceMixin` in `@loopback/service-proxy` that adds a `.service()` convenience method
- [ ] Implement a `service` booter leveraging the above Mixin
- [ ] CLI Template Updates (if applicable)
- [ ] Tests
- [ ] Docs + Blog

**Comment by marioestradarosa** [comment]
You mean in a similar way the controllers are being discovered and bind automatically?

**Comment by virkt25** [comment]
Yes, exactly how controllers are discovered and bound automatically. Just realized this is a duplicate issue of a much better groomed task. 

Closing as duplicate of https://github.com/strongloop/loopback-next/issues/1439
