### ISSUE TITLE
Feature Request - API for dynamic model creation

### ISSUE THREAD

**Issue by meepeek** [strongloop/loopback-next#1580]
## Description / Steps to reproduce / Feature proposal

I have checked in here https://loopback.io/doc/en/lb4/LoopBack-3.x.html and don't think what I am about to mention was existing in the plan so I would like to purpose.

I am using LB 3 and wish the model to be able to create programmatically (run time) by calling an API, instead of manually defining JSON.

## Current Behavior

Programmer will have to manually add JSON file, or generate by CLI, for each model. If an additional model is needed, we will have to restart the server.

## Expected Behavior

I wish the model can be created either adding JSON file or calling an API and the system will create a model and corresponding JSON file if needed.

Another idea is moving models definition to be defined in lowdb JSON, instead of plain JSON. This way programmer may create their own API to dynamically create models.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by mgleland** [comment]
yes, please - I depend on the ability to dynamically generate models.

**Comment by dhmlau** [comment]
I think this is related to https://github.com/strongloop/loopback-next/issues/1517.

**Comment by meepeek** [comment]
@dhmlau Thank you the information. However, the dynamic I meant was a bit different.

Actually, strongloop had implemented a GUI which has the feature similar to what I described, I think it's called Strongloop's Arc or Studio which you can mange a model from web UI.

As the current loopback backend that I experienced, I think it will need to restart the server once you have made changes on the model, which made model definition static. What I meant was an API to generate model and save and the load new model without restart server.

**Comment by mgleland** [comment]
also need the plain old createModel method that lets you create a model programmatically rather than from json files, etc.

**Comment by bajtos** [comment]
The pull request https://github.com/strongloop/loopback-next/pull/4235 shows how to define a model and expose it via a REST API at runtime. Feel free to join the discussion there or in follow-up stories we are going to create soon.
