### ISSUE TITLE
Browser prompts user for creds when Cloudant creds are incorrect

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#1592]
## Description / Steps to reproduce / Feature proposal
1. Set up a Cloudant datasource with wrong creds. 
2. Start app.
3. Load page.
4. Lo and behold!

In case of LB3, the app crashes in booting phase with an unhandled error. 

## Current Behavior
![image](https://user-images.githubusercontent.com/950112/43641448-54d3f538-9741-11e8-9e9b-a0b1ef7384a4.png)

I have tried with a MySQL datasource, it crashes the app when loading the page; there is no prompt.

## Expected Behavior
All datasources should verify connectivity during the booting phase. If the app is up and running, we should assume all connectors will be working successfully, unless their servers are down.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@hacksparrow , could you please add the acceptance criteria so that the team can estimate?  Thanks.

**Comment by dhmlau** [comment]
Do you think we should close this ticket and continue the discussion/work in https://github.com/strongloop/loopback-next/issues/1640?

**Comment by hacksparrow** [comment]
Ok, let's close this.
