### ISSUE TITLE
[CLI] automatically insert juggler-imports and RepositoryMixin

### ISSUE THREAD

**Issue by marioestradarosa** [strongloop/loopback-next#1594]
## Feature proposal
`# lb4 --enable-juggler`

Should add the juggler-imports and the RepositoryMixin reference automatically when creating the application.ts

This option will help tutorials.

## Current Behavior
We have to copy & paste the code on application.ts once we start using the repository feature

## Expected Behavior
The switch passed to lb4 CLI should add it automatically.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
Maybe `lb4 --enable-repository`?

**Comment by marioestradarosa** [comment]
That sounds better. However, does LB4 allow implementation of repositories without juggler?

**Comment by marioestradarosa** [comment]
@raymondfeng  , what if we use the options instead? . That way no new switch is introduced and app developers can enable/disable it at first-time generation.

```javascript
 this.buildOptions = [
      'tslint',
      'prettier',
      'mocha',
      'loopbackBuild',
      'vscode',
      'enable-repository',
    ];
```
