### ISSUE TITLE
Doc Generator Approach

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#16]
@hacksparrow lets discuss the details for generating the loopback-next docs based on typescript.

This is mainly the build process.

**Comment by dhmlau** [comment]
@ritch, are you referring to the API / TS doc?  If so, I believe it's already completed and good to close this ticket? 
cc @crandmck

**Comment by crandmck** [comment]
Yes, AFAIK this is re API docs, and it is done, except for deploying updates of apidocs.strongloop.com to production.

**Comment by kjdelisle** [comment]
Closing as out-of-date.
