### ISSUE TITLE
Test other Passport Strategies

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#160]
The initial implementation of https://github.com/strongloop/loopback-next/tree/master/packages/authentication

will only test basic auth... this story represents the testing/impl for other strategies (More generic impl).

**Comment by bajtos** [comment]
I think this is loosely related to #155

**Comment by arash01** [comment]
I confirm passport-http-bearer has been tested and it works fine 👍

**Comment by bajtos** [comment]
Thank you @arash01! I am closing this issue a done then.

**Comment by dhmlau** [comment]
Closing as it is no longer relevant.
