### ISSUE TITLE
Composite ID in model repository. 

### ISSUE THREAD

**Issue by hosiduy** [strongloop/loopback-next#1600]
## Feature proposal
Hi Loopback team, 
I working in a project which have composite ID in model. 
I look up in the loopback 4 document but can't find instruction about init repository with composite ID. 
Have lb4 framework supported this feature?

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by shimks** [comment]
We currently don't have support for composite ID, but it is on our list of things to do. We'll use this issue to keep a track of the feature.

**Comment by hosiduy** [comment]
Hi Loopback Team, 
do we have any update on this feature?

**Comment by globaltommy** [comment]
+1 - any updates?

**Comment by shimks** [comment]
@hosiduy, @globaltommy This feature's been covered by #1830.
@dhmlau, do you want to close this ticket in favor of the other one?

**Comment by dhmlau** [comment]
@shimks, that's a good idea!
Please continue the discussion in #1830.
