### ISSUE TITLE
Document how to deploy LB4  app to IBM Cloud via CloudFoundry

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#1604]
## Description / Steps to reproduce / Feature proposal

Add documentation for deploying LB4 app to IBM Cloud's Cloud Foundry.

Related to: https://github.com/strongloop/loopback-next/pull/1574
Information to document can be inferred from the PR for the Spike.

## Acceptance Criteria
- [ ] Document Cloud Foundry artifacts creation (manifest.yml, .cfignore)
- [ ] Document service provisioning and binding (links to IBM Cloud Docs)
- [ ] Document sample code for using the provisioned service in the app's datasource

**Comment by dhmlau** [comment]
@hacksparrow , as part of the grooming exercise, could you please provide more details on:
- where this information will be added in documentation
- what needs to be included, i.e. what are the things a user needs to do in order to deploy an LB app to IBM Cloud

After we have that, we can then move for estimation.  Thanks!

**Comment by dhmlau** [comment]
Cross posting comments from @raymondfeng https://github.com/strongloop/loopback-next/issues/1614#issuecomment-413567914:
> We need to find out how much IBM Cloud CLI can do against a LB4 project and try to reuse it as much as possible. Check out https://console.bluemix.net/docs/cli/reference/ibmcloud/download_cli.html#install_use
>
> Having some commands in the CLI to enable/configure cloud deployment/integration is good if necessary.

**Comment by bajtos** [comment]
> where this information will be added in documentation

IMO, we should create a new page called along the lines of a "Deployment guide".

> what needs to be included, i.e. what are the things a user needs to do in order to deploy an LB app to IBM Cloud

The spike pull request #1574 already contains a draft of a deployment guide, see https://github.com/strongloop/loopback-next/blob/3f55d2d819c0da5e18b7e06d41c78da4817d11a4/examples/todo/DEPLOYING.md. This guide does not describe the changes needed in the application implementation though, these changes are contained in the spike pull request.

**Comment by dhmlau** [comment]
Closing as resolved. PR #1668 has landed.
