### ISSUE TITLE
Blog about LB4 app deployment to IBM Cloud Cloud Foundry.

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#1605]
## Description / Steps to reproduce / Feature proposal

Write a blog describing the ability and steps to deploy a LB4 app to IBM Cloud's Cloud Foundry.

## Acceptance Criteria
- [x] Inform we've documented the deployment steps as of today.
- [x] Inform we'll continue to look into ways to enhance the user experience, e.g. auto-generate some of the artifacts, and look into Kubernetes deployment.

**Comment by dhmlau** [comment]
I think we can put the details/steps on how to deploy LB4 app to IBM Cloud in docs, which will be covered in #1604.  Messages to deliver in the blog can be:
- we've documented the deployment steps as of today
- we'll continue to look into ways to enhance the user experience, e.g. auto-gen some of the artifacts, and look into kubernetes deployment

Related to: #1459

**Comment by dhmlau** [comment]
FYI - please see the blog author guideline: https://github.com/strongloop/strongloop.com/blob/master/_posts/2001-05-04-information-for-blog-authors.md

**Comment by dhmlau** [comment]
Closing as done
