### ISSUE TITLE
Create parameter decorator shortcuts for the object type

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#1607]
## Description / Steps to reproduce / Feature proposal

Inspired by issue https://github.com/strongloop/loopback-next/issues/100. 

We should create decorator shortcuts for object parameters from:
  - query
  - header
  - path

The shortcut should be able to infer the schema from the type metadata.

For example:
```ts
import {Note} from '../models'
class MyController {
  @get('/test')
  async test(@param.query.object('note') note: Note) {
    // your code
  }: void
}
```

## Acceptance Criteria

- [ ] create shortcuts
  - [ ] @param.query.object

**NOTE:** Objects are rarely if ever passed in via a `path` parameter or `header` as such those decorators are not to be added as part of this task. If someone decides to pass them via those areas, they can do so using the full `@param` decorator.

**Comment by dhmlau** [comment]
@jannyHou , I'm thinking this is `post GA` since it's enhancement on the developer experience or convenience.  what do you think?

**Comment by virkt25** [comment]
This was discussed during estimation and agreed to be a `post-GA` task.

**Comment by bajtos** [comment]
Closing as implemented via https://github.com/strongloop/loopback-next/pull/1667
