### ISSUE TITLE
[CLI] Offer User Defined Models as a Base Class

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1610]
## Description / Steps to reproduce / Feature proposal

From #441 

For the `lb4 model` command currently we offer no Base Class selection. The infrastructure is there but we default the question to `Entity` base. 

Similar to LB3, we should detect user created Models in `/src/models` and offer those as an option in the CLI for users so they can build new models which extend existing Models. This is a common use case. 

## Current Behavior

- No base class options

## Expected Behavior

- Provide a base class selection option based on the Models present in the user app.

## Acceptance Criteria
- [ ] Scan `/models` for models and offer those as a `baseClass` option in the CLI (`Entity` should be the first options)
- [ ] Support express mode by defaulting to `Entity`
- [ ] Support `--config` by accepting it as JSON property `baseClass`
- [ ] Update docs

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
Closing as done via https://github.com/strongloop/loopback-next/pull/1746
