### ISSUE TITLE
Generate IBM Cloud artifacts

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#1614]
Add command / option in `lb4` (CLI) to generate IBM Cloud artifacts for various environments.

**Comment by virkt25** [comment]
@hacksparrow Can you provide a list of what these artifacts are and if any info is needed to generate these artifacts? 

Overall I'm actually not a fan of adding this into the CLI, this is something the user should be able to copy-paste once and forget especially given the fact that the CLI doesn't know the geo, account info, sizing / scaling rules / etc.

**Comment by raymondfeng** [comment]
We need to find out how much IBM Cloud CLI can do against a LB4 project and try to reuse it as much as possible. 

Having some commands in the CLI to enable/configure cloud deployment/integration is good if necessary.
