### ISSUE TITLE
[Docs] Relation decorators doc is not up-to-date

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1615]
## Description / Steps to reproduce / Feature proposal
In this section (https://loopback.io/doc/en/lb4/Decorators.html#relation-decorators), it says:
```This feature has not yet been released in alpha form. Documentation will be added here as this feature progresses.```
 even though we support `@hasMany` now.  Looks like the docs needs to be updated.

## Acceptance Criteria
- [ ] Review https://loopback.io/doc/en/lb4/Decorators.html#relation-decorators and update the docs to reflect the current status

**Comment by bschrammIBM** [comment]
There is a note on the Decorators page that says _Please note we will elaborate more about model and model definition in the
[Model](Model.md) page, and replace the link above with a LoopBack 4 link_ 
If this has been updated, then this note can be removed and the link can be updated to an LB4 page.

There is also the following note: ```ts
// Missing example here
// Will be provided in Model.md
// refer to [example code](https://github.com/strongloop/loopback-next-example/blob/master/services/account-without-juggler/repositories/account/models/Account.ts)
```
Can we update this with the example?

**Comment by dhmlau** [comment]
It's been updated with PR https://github.com/strongloop/loopback-next/pull/1686.  Thanks @bschrammIBM!
