### ISSUE TITLE
Improve testing documentation on emptying databases

### ISSUE THREAD

**Issue by lightheaded** [strongloop/loopback-next#1616]
## Description / Steps to reproduce / Feature proposal
I am following [the documentation][1] in attempt to empty the database before my acceptance test cases

In my `hello.controller.acceptance.ts` I have

    import { givenEmptyDatabase } from './helpers/database.helpers';
    ...
    before(givenEmptyDatabase);
    ...
    describe( ... ) { ... }

in `database.helpers.ts` I try to act according to the [LoopBack 4 documentation][1]

    import {HelloRepository} from '../../src/repositories';
    import {testdb} from '../fixtures/datasources/testdb.datasource';

    export async function givenEmptyDatabase() {
      await new HelloRepository(testdb).deleteAll();
    }

but it's never described what the `testdb.datasource.ts` should look like. I have tried to make it look similar to my regular `db.datasource.ts`, but I'm not sure what to export..

	import {inject} from '@loopback/core';
	import {juggler, AnyObject} from '@loopback/repository';
	const config = require('./db.datasource.json');

	export class DbDataSource extends juggler.DataSource {
	  static dataSourceName = 'db';

	  constructor(
	    @inject('datasources.config.db', {optional: true})
	    dsConfig: AnyObject = config
	  ) {
	    super(dsConfig);
	  }
	}

## Current Behavior
The example in [Clean the database before each test][1] does not reveal what `testdb.datasource.ts` looks like.

    import {testdb} from '../fixtures/datasources/testdb.datasource';

## Expected Behavior
The example in [Clean the database before each test][1] does includes a code snippet describing `testdb.datasource.ts`

  [1]: https://loopback.io/doc/en/lb4/Testing-your-application.html#clean-the-database-before-each-test

**Comment by dhmlau** [comment]
@virkt25 @shimks , could you please take a look if we need to further groom this task before estimation?  Thanks.

**Comment by lightheaded** [comment]
Got an answer from the [@loopback/repository][1]. testdb.datasource.ts should look like this:

	import { juggler } from '@loopback/repository';

	export const testdb: juggler.DataSource = new juggler.DataSource({
	  name: 'db',
	  connector: 'memory'
	});

  [1]: https://github.com/strongloop/loopback-next/tree/master/packages/repository

Added a pull request #1619 to mirror that in the documentation

**Comment by dhmlau** [comment]
PR #1619 is in progress.

**Comment by dhmlau** [comment]
@lightheaded , your PR #1619 has merged.  Thanks for your contribution.  Is this ticket good to close?  Thanks.

**Comment by lightheaded** [comment]
Yes, sure. Thanks!
