### ISSUE TITLE
Swagger-ui redirect fails when on IPv6 locally

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1623]
## Description / Steps to reproduce / Feature proposal

Create an app using `lb4 app`. Have your OS configured for IPv6 (default on Macs). Go to http://[::1]:3000/swagger-ui

Instead of loading the swagger-ui modules to explore the API's an error is generated saying `Failed to load API Definition`. 

![image](https://user-images.githubusercontent.com/3311536/44354155-08c51f80-a477-11e8-9750-53691e090154.png)

I suspect this has something to do with the RegEx used below. I played around with the RegEx used in regex101.com and I think the correct regex should be `/:[0-9]+(?!])/` to work with IPv6 addresses. 

I made the changes but can't verify locally but for some reason I can't verify the fix ... creating this issue to track it as I plan to go back to trying to debug my dev environment. I can't even get a `console.log` statement added to the function to print :/

https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/rest.server.ts#L358-L371

## Acceptance Criteria
- [ ] Able to redirect to `/swagger-ui` when on IPv6 without an error

**Comment by dhmlau** [comment]
@virkt25 , trying to understand the impact of not getting it fixed by GA, though i think we should. 
IIRC,  `http://[::1]:3000/swagger-ui` gives the error message in the original description.  Can we change the message to ask users opening another URL `http://localhost:3000/swagger-ui` instead?  or it won't work in all cases too?  Thanks.

**Comment by dhmlau** [comment]
PR https://github.com/strongloop/loopback-next/pull/1637

**Comment by dhmlau** [comment]
@raymondfeng , I just assigned it to you since PR #1637 is yours.

**Comment by raymondfeng** [comment]
Fixed by #1637
