### ISSUE TITLE
Rejecting unauthenticated requests

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#166]
- [ ] Implementation of `app.bind('authentication.authenticated')` (might overlap with what @deepakrkris is working on)
- [ ] Request needs to be rejected when it's not authenticated and authentication is required
  - `app.get('authentication.authenticated')` needs to be used in the router

**Comment by ritch** [comment]
`authentication.authenticated` is no longer required

and rejecting requests needs tests, the impl is just `throw` with a `err` that has a status code...
