### ISSUE TITLE
[CLI] `lb model` makes confusing prompts

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#1665]
## Description / Steps to reproduce / Feature proposal

There are two prompts which make no sense.

*Is ID field*?
*Required?*

![kapture 2018-09-03 at 12 29 32](https://user-images.githubusercontent.com/950112/44972041-6e380680-af75-11e8-813a-de9c749c6a0c.gif)

Is the intended prompt *Is ID field Required?*. We should fix is ASAP.

## Current Behavior

Confusing prompts.

## Expected Behavior

No confusing prompts.

**Comment by bajtos** [comment]
My understanding of these prompts - please note these prompts are related to a model _property_ being defined.

> Is ID field?

Is this property the identification of the model (a primary key)?

> Required?

Is this property required, i.e. must it always have a value set?

@strongloop/sq-lb-apex could you please confirm?

**Comment by virkt25** [comment]
> could you please confirm?

That was certainly the correct interpretation of those prompts.

**Comment by dhmlau** [comment]
PR #1666
