### ISSUE TITLE
Incorrect directory in tutorial documentation

### ISSUE THREAD

**Issue by payne-chris-r** [strongloop/loopback-next#1674]
There are many issues with your lb4 documentation/tutorial (especially the BONUS section of the to-do list). 
On the Examples and tutorials -> Todo Tutorial -> Bonus: Integrate with a geo-coding service, under **Implement a service provider**:

I'm prrrretty sure your paths are off. You say to create a new directory, and add two new files, but then the example paths are just in the src/ directory instead of the newly created src/services folder...

```diff
Implement a service provider
Create a new directory src/services and add the following two new files:

- src/geocoder.service.ts defining TypeScript interfaces for Geocoder service and implementing a service proxy provider.
+ src/services/geocoder.service.ts defining TypeScript interfaces for Geocoder service and implementing a service proxy provider.
- src/index.ts providing a conventient access to all services via a single import statement.
+ src/services/index.ts providing a conventient access to all services via a single import statement.

- src/geocoder.service.ts
+ src/services/geocoder.service.ts
```
```js
import {getService, juggler} from '@loopback/service-proxy';
import {inject, Provider} from '@loopback/core';
import {GeocoderDataSource} from '../datasources/geocoder.datasource';

export interface GeoPoint {
  ...
}
```
**This one's fine!**
src/services/index.ts
```js
export * from './geocoder.service';
```

**Comment by payne-chris-r** [comment]
FWIW, I got that from https://loopback.io/doc/en/lb4/todo-tutorial-geocoding-service.html
Looks like you also have documentation here, which is less wrong, but still wrong?
https://github.com/strongloop/loopback-next/blob/master/docs/site/todo-tutorial-geocoding-service.md

**Comment by payne-chris-r** [comment]
There are also just huge inconsistencies between those two pages... Not sure which one is more relevant.

**Comment by virkt25** [comment]
The link to the GitHub repository is the latest. loopback.io self-updates with the content but only when there is a new version of `@loopback/docs` released to ensure it's in sync with the features. 

I'll do a new release shortly and ensure the tutorial is up to date. Thanks for pointing this out :)
