### ISSUE TITLE
Couldn't get bonus to work

### ISSUE THREAD

**Issue by payne-chris-r** [strongloop/loopback-next#1676]
## Description / Steps to reproduce / Feature proposal
Even addressing (best I could) #1674 and #1675 I couldn't get the Bonus set up properly. 
I tried: https://loopback.io/doc/en/lb4/todo-tutorial-geocoding-service.html
and
https://github.com/strongloop/loopback-next/blob/master/docs/site/todo-tutorial-geocoding-service.md
and still getting:

```bash
src/services/geocoder.service.ts:28:5 - error TS2322: Type 'Promise<GenericService>' is not assignable to type 'GeocoderService'.
  Property 'geocode' is missing in type 'Promise<GenericService>'.

28     return getService(this.datasource);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Current Behavior
```
$ npm start

> loopback-test@1.0.0 prestart /Users/chrispayne/loopback-test/loopback-test
> npm run build


> loopback-test@1.0.0 build /Users/chrispayne/loopback-test/loopback-test
> lb-tsc

src/services/geocoder.service.ts:28:5 - error TS2322: Type 'Promise<GenericService>' is not assignable to type 'GeocoderService'.
  Property 'geocode' is missing in type 'Promise<GenericService>'.

28     return getService(this.datasource);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! loopback-test@1.0.0 build: `lb-tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the loopback-test@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chrispayne/.npm/_logs/2018-09-06T21_22_51_171Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! loopback-test@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the loopback-test@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chrispayne/.npm/_logs/2018-09-06T21_22_51_190Z-debug.log
```
## Expected Behavior
Something that at least ran?

**Comment by marioestradarosa** [comment]
hi @payne-chris-r , thank you for reporting it. You should wrap the returned value for value() method with a Promise as follows:

```ts
value(): Promise<GeocoderService> {
 return getService(this.datasource);
  }
```
Also make sure you are running the latest version of  Loopback 4, since we are in Beta, it is constantly updated.

**Comment by marioestradarosa** [comment]
BTW, if you run `lb4 example todo` it will create the todo tutorial app for you. I have just reviewed the code and it works, so you can use it along the tutorial also.

**Comment by payne-chris-r** [comment]
Awesome.
Documentation should say:
```diff
- value(): GeocoderService {
+  value(): Promise<GeocoderService> {
  return getService(this.datasource);
}
```

**Comment by geocine** [comment]
I ran into this , still the documentation is not updated. Is there a way we can do a pull request to update the documentation?

**Comment by raymondfeng** [comment]
@geocine I see `Promise<GeoService>` at https://loopback.io/doc/en/lb4/todo-tutorial-geocoding-service.html#implement-a-service-provider. What issue are you seeing?
