### ISSUE TITLE
[Spike] HasMany relation to same Entity

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#1682]
## Description / Steps to reproduce / Feature proposal

This is a spike story for https://github.com/strongloop/loopback-next/issues/1571. Based on the discussion in the original story, we need a quick spike to 

- Create a test case to mock the scenario - Entity creates a hasMany relation to itself.
- See if it fails. If yes:
  - Troubleshoot the reason, e.g. infinite dereference of circular dependencies or other reasons.
  - Discover the gap between the potential fix and the current code.

*Timebox it to 2 days*

**Comment by danysz** [comment]
When we will have a fix for it?

**Comment by nabdelgadir** [comment]
I modified the `Todo` model by adding the following two properties:

```ts
@hasMany(() => Todo, {keyTo: 'parentId'})
todos?: Todo[];

@belongsTo(() => Todo)
parentId?: number;
```

And the `Todo` repository as follows:

```ts
import {
  DefaultCrudRepository,
  juggler,
  HasManyRepositoryFactory,
  BelongsToAccessor,
} from '@loopback/repository';
import {Todo} from '../models';
import {inject, Getter} from '@loopback/core';

export class TodoRepository extends DefaultCrudRepository<
  Todo,
  typeof Todo.prototype.id
> {
  // EDITED HERE
  public readonly todos: HasManyRepositoryFactory<
    Todo,
    typeof Todo.prototype.id
  >;
  public readonly parentId: BelongsToAccessor<Todo, typeof Todo.prototype.id>;

  constructor(@inject('datasources.db') dataSource: juggler.DataSource) {
    super(Todo, dataSource);
    // EDITED HERE
    this.parentId = this._createBelongsToAccessorFor(
      'parentId',
      Getter.fromValue(this),
    );
    this.todos = this.createHasManyRepositoryFactoryFor(
      'todos',
      Getter.fromValue(this),
    );
  }
}
```
And added the following two endpoints to the controller:
```ts
@post('/todos/{id}/todo')
async createOrder(
  @param.path.number('id') todoId: typeof Todo.prototype.id,
  @requestBody() todoData: Todo,
): Promise<Todo> {
  return await this.todoRepo.todos(todoId).create(todoData);
}

@get('/todos/{id}/parentId')
async getPink(
  @param.path.number('id') todoId: typeof Todo.prototype.id,
): Promise<Todo> {
  return await this.todoRepo.parentId(todoId);
}
```

Then tried creating a parent `Todo` with only a `title` property [`POST /todos`]:
```json
{
  "id": 5,
  "title": "parent"
}
```

Then tried adding a child `Todo` via `POST /todos/{id}/todo`:
```json
{
  "id": 6,
  "title": "child",
  "parentId": 5
}
```

Then when I tried getting the parent `Todo` via `GET /todos/6/parentId`:
```json
{
  "id": 5,
  "title": "parent"
}
```

However, if I try `GET todos/5/`, it doesn't include the child `Todo` (I assume this will be available when partial updates are supported), but if I try `GET todos/6/` then I do get the `parentId`: 

[result from `GET /todos/`]
```json
{
  // ...
  {
    "id": 5,
    "title": "parent"
  },
  {
    "id": 6,
    "title": "child",
    "parentId": 5
  }
}
```

@b-admike thoughts? Did I miss anything?

**Comment by b-admike** [comment]
@nabdelgadir That looks good to me. Thank you for verifying! We can now capture this scenario in a test case in https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/__tests__/acceptance/has-many.relation.acceptance.ts.

**Comment by nabdelgadir** [comment]
Going to close this spike as the error couldn't be reproduced and leave adding a test as part of the original issue #1571.
