### ISSUE TITLE
Module has no exported member ServiceMixin

### ISSUE THREAD

**Issue by siosio34** [strongloop/loopback-next#1688]
## Description / Steps to reproduce / Feature proposal
Hi. i report npm run start error when make todo tutorial in loopback-next document.
this error message is
```
error TS2305 Module has no exported member ServiceMixin.
```

so i enter node_modules/@loopback/service-proxy then no named exported ServiceMixin.  
## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by marioestradarosa** [comment]
Hi @siosio34, 
The ServiceMixin has just been introduced in one of the recent releases. Do you have the latest @loopback/cli package in your environment?.  

I currently have @loopback/cli version: 0.22.0

**Comment by Sarh** [comment]
Hello, 
I am having this same error. I currently have @loopback/cli version: 0.22.0

**Comment by marioestradarosa** [comment]
I could reproduce it. Even if we have 0.22.0 , the lb4 app is not including the latest package from the npm repository. we´ll fix it. 

For now, can you install it manually in your project? , it should be @0.8.0 , which is the one that contains the ServiceMixin addition.

` npm install @loopback/service-proxy@latest --save`

**Comment by marioestradarosa** [comment]
**As an additional note:** If you run the following command to scaffold the example.

`lb4 example todo`

and then inside the `loopback4-example-todo` directory you try to run it `npm start`.  You will see that it complains with the following error:

`error TS2307: Cannot find module '@loopback/openapi-v3-types/node_modules/openapi3-ts/dist/model/OpenApi` 

I had to install manuall the openapi3-ts dependency inside the openapi-v3-types as follows:

`cd ./node_modules/@loopback/openapi-v3-types`
and then 
`npm install`

After that the scaffolded example will run properly. 
I will open an issue on this one now.

**Comment by raymondfeng** [comment]
@marioestradarosa See https://github.com/Microsoft/TypeScript/issues/26985 and https://github.com/strongloop/loopback-next/issues/1643.

**Comment by raymondfeng** [comment]
@marioestradarosa Pls review https://github.com/strongloop/loopback-next/pull/1689

**Comment by siosio34** [comment]
Ok. this issue is just temporary bug because of loopback cli and service-proxy version difference.  it will be fixed after latest published to npm. i'll wait ~

**Comment by raymondfeng** [comment]
Please try `@loopback/cli@0.22.1`.

**Comment by theclive** [comment]
Hi guys.  I didn't try `lb4 example todo` but I've just tried following the [getting started](https://loopback.io/doc/en/lb4/Getting-started.html) this morning and stumbled upon the error @marioestradarosa reproduced above when running `npm start`.   I checked which version of the cli I have (see below) and it's the version @raymondfeng suggested in the [latest comment](https://github.com/strongloop/loopback-next/issues/1688#issuecomment-419779139) - 0.22.1) but the error persists.  @marioestradarosa's [suggestion](https://github.com/strongloop/loopback-next/issues/1688#issuecomment-419688949) got me past the error (ty @marioestradarosa 🥇).

> clive:lb-4-test clive$ lb4 -v
> @loopback/cli version: 0.22.1
> 
> @loopback/* dependencies:
>   - @loopback/authentication: ^0.11.7
>   - @loopback/boot: ^0.13.0
>   - @loopback/build: ^0.7.2
>   - @loopback/context: ^0.12.6
>   - @loopback/core: ^0.11.6
>   - @loopback/metadata: ^0.9.6
>   - @loopback/openapi-spec-builder: ^0.8.6
>   - @loopback/openapi-v3-types: ^0.9.0
>   - @loopback/openapi-v3: ^0.13.0
>   - @loopback/repository-json-schema: ^0.10.7
>   - @loopback/repository: ^0.16.0
>   - @loopback/rest: ^0.20.0
>   - @loopback/testlab: ^0.12.0
>   - @loopback/docs: ^0.17.0
>   - @loopback/example-hello-world: ^0.9.7
>   - @loopback/example-log-extension: ^0.11.7
>   - @loopback/example-rpc-server: ^0.11.3
>   - @loopback/example-todo: ^0.17.0
>   - @loopback/example-soap-calculator: ^0.3.0
>   - @loopback/dist-util: ^0.3.6
>   - @loopback/service-proxy: ^0.8.0
>   - @loopback/http-caching-proxy: ^0.3.6
>   - @loopback/http-server: ^0.3.6
>   - @loopback/example-todo-list: ^0.3.4
> clive:lb-4-test clive$

Here is the error I receive in when running `npm start`:
```
clive:lb-4-test clive$ npm start

> lb4test@1.0.0 prestart /Users/clive/Developer/learning/loopback-fiddling/lb-4-test
> npm run build


> lb4test@1.0.0 build /Users/clive/Developer/learning/loopback-fiddling/lb-4-test
> lb-tsc

node_modules/@loopback/rest/dist8/src/keys.d.ts:54:39 - error TS2307: Cannot find module '@loopback/openapi-v3-types/node_modules/openapi3-ts/dist/model/OpenApi'.

54     const API_SPEC: BindingKey<import("@loopback/openapi-v3-types/node_modules/openapi3-ts/dist/model/OpenApi").OpenAPIObject>;
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! lb4test@1.0.0 build: `lb-tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the lb4test@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/clive/.npm/_logs/2018-09-10T08_27_05_801Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! lb4test@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the lb4test@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/clive/.npm/_logs/2018-09-10T08_27_05_821Z-debug.log
```

**Comment by marioestradarosa** [comment]
Hi @theclive , 
Thank you for your report 👍 .  However, the original issue has been solved as per @raymondfeng suggestion on installing the latest cli version.  I introduced a separate issue _(unwittingly)_  on the same thread which is the one you are experiencing now. This second issue will be solved when the #1689 lands.

**Comment by raymondfeng** [comment]
Please try the latest release.

**Comment by marioestradarosa** [comment]
@raymondfeng , I am closing this issue related to ServiceMixin which is now fixed. I opened a new issue for the problem with the open-api-v3-types dependency to accurately document it.
See https://github.com/strongloop/loopback-next/issues/1695
