### ISSUE TITLE
Intellij Idea errors on bootstrapped app

### ISSUE THREAD

**Issue by matejthetree** [strongloop/loopback-next#1692]
I am having errors from IntelliJ Idea ide

<img width="720" alt="screen shot 2018-09-10 at 13 13 38" src="https://user-images.githubusercontent.com/10059426/45294390-7b1ba380-b4fb-11e8-9354-9e52d177c750.png">

I took a screenshot of, because I cannot copy this error.
Do you happen to know the reason behind this, or should I post the bug on IntelliJ bug tracker?

Thank you

**Comment by virkt25** [comment]
Looks to be IntelliJ specific. I haven't had issues with Sublime 3 (with TS Intellisense plugin) / VS Code. Might be best to ask them for help with the issue.

Don't have a license for IntelliJ to be able to reproduce but if they say it's something on our end let us know and we'll look into it further.

**Comment by matejthetree** [comment]
2.81

**Comment by raymondfeng** [comment]
Please try 3.0.x.

**Comment by matejthetree** [comment]
Works with 3.0.x
I switched from bundled version to npm latest typescript
