### ISSUE TITLE
Cannot choose a base model class in `lb4 model`

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1698]
When creating a new model, it is desirable to choose the base class from which the new model should inherit.

Possible use cases:

- inherit from `Entity` - this is typical for models persisted in a CRUD database
- inherit from `Model` - this is typical for models persisted in a KeyValue storage like Redis, but also for models describing data schemas used by nested (embedded) properties of other models (e.g. an `Address` model).
- inherit from a model defined in the application - this can be useful to design object hierarchy of models, e.g. a `Customer` is a `User`, but also an `Administrator` is a `User`.

/cc @raymondfeng if there is already an existing issue keeping track of this work, then feel free to close this one as a duplicate.

## Acceptance criteria

 - [ ] MUST HAVE: `lb4 model` asks the user whether the new model class should inherit from `Entity` or `Model`.
 - [ ] MUST HAVE: `--base` option to specify the base model via CLI arguments
 - [ ] MUST HAVE: update `lb4 repository` (added by https://github.com/strongloop/loopback-next/pull/1659) to offer only models inheriting from a base model compatible with the selected datasource (CRUD requires Entity, KeyValue can work with both Entity and Model).
 - [ ] SHOULD HAVE: `lb4 model` should offer all application model classes in addition to built-in Model and Entity classes in the prompt.
- [ ] Extract the functions like listing available models to utils.

**Comment by marioestradarosa** [comment]
I would add to the acceptance the command line option for that property too. I am not talking about a config file, but something like `--base-model or --base` .

**Comment by bajtos** [comment]
+1 to add `--base` 👍

**Comment by marioestradarosa** [comment]
Ok, I think I can work with this 😄 .  
@bajtos , so choices are Entity or Model. CRUD  can only work with Entity.  KV can work with Entity and Model. Model refers to a Model class name such as CustomerModel or Model is a base class such as Entity?.

**Comment by raymondfeng** [comment]
@marioestradarosa In addition to the base classes, we should also add existing models to the list of choices (similar as you did for `lb4 repository`, but a list instead of checkbox). Thanks!

**Comment by marioestradarosa** [comment]
> but a list instead of checkbox
👍 this simplifies it.

So, the list should contain the literals Entity, Model + the list of available models in src/models correct?

**Comment by raymondfeng** [comment]
Yes.

**Comment by raymondfeng** [comment]
In LB3, we also allow the user to select `custom type ...` and write in a name. I'm not sure if we have to do so in LB4. Let's get the basics working 1st.
