### ISSUE TITLE
Missing one step for adding ServiceMixin in documentation

### ISSUE THREAD

**Issue by shazha** [strongloop/loopback-next#1701]
## Description / Steps to reproduce / Feature proposal
Create a new LB4 app and try to add a rest service as datasource by following the doc[ Integrate with a geo-coding service](https://loopback.io/doc/en/lb4/todo-tutorial-geocoding-service.html#services).
## Current Behavior
When trying to access the injected rest service, the following exception occurred:
`The key services.GeocoderService was not bound to any value.`
## Expected Behavior
The rest service can be injected properly.

## Fix
After applying the following changes to `application.ts` file, the error is gone. And this should be documented:  

From
```
export class StorageApplication extends BootMixin(
  RepositoryMixin(RestApplication),
```
to
```
import {ServiceMixin} from '@loopback/service-proxy';

export class StorageApplication extends BootMixin(
  ServiceMixin(RepositoryMixin(RestApplication)),
```

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by virkt25** [comment]
Great catch! Would you be interested in submitting a PR to fix this?

**Comment by shazha** [comment]
Sure, I'll submit a PR later.

**Comment by virkt25** [comment]
PR Landed. Thanks for the contribution @shazha! 💯 🎉
