### ISSUE TITLE
Unknown Command 'lb4'

### ISSUE THREAD

**Issue by mastermind42** [strongloop/loopback-next#1716]
After installing loopback 4 by doing: npm i -g @loopback/cli, I am unable to get lb4 command to work.

This is on mac 10.13.4

**Comment by dhmlau** [comment]
@mastermind42 , just want to make sure it's installed properly, could you please check by running `npm -g ls | grep @loopback`? 
My output is:
```
├─┬ @loopback/cli@0.22.10
│ ├─┬ @loopback/dist-util@0.3.7
```

**Comment by hacksparrow** [comment]
@mastermind42 try on a new shell/tab.

**Comment by virkt25** [comment]
If the above doesn't work can you please share with us the version of Node and npm being used.

**Comment by dhmlau** [comment]
@mastermind42 , are you still having this issue?

**Comment by raymondfeng** [comment]
@mastermind42 Please re-open the issue if it still exists.
