### ISSUE TITLE
relation expects foreignKey on the Object

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1719]
## Description / Steps to reproduce / Feature proposal

When I was working on user order history component for https://github.com/strongloop/loopback4-example-shopping I ran into an issue ...

`/users/{userId}/orders` expects the orders object to have a `userId` field (Since it's a required property of the `Order` model and is enforced by the controller coercion / validation). The issue is that passing in the `userId` on the Order object passes controller validation but causes the relation validation to throw an error saying the foreign key can't be changed -- despite the fact that the foreign key is exactly the same as the one in the URL and the one given to the repository. 

## Current Behavior

Throws error if foreign key on object saying you can't change it even if it's the same one.

## Expected Behavior

Be smart enough to not throw an error if the key given is the same as the one that's expected. 

---

My current solution is to delete the foreign key in the controller. The other alternatives I can think of is to mark the key as an optional property (do we want this?) ... or to mark the `requestBody` type as `Partial<Order>` but this will mean losing type validation of expected properties on the Order type.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
I think it's possible for TypeScript to exclude some properties explicitly using `Exclude`, for example:

```ts
type OrderWithoutUserId = Pick<Order, Exclude<keyof Order, 'userId'>>
```

**Comment by virkt25** [comment]
@raymondfeng That worked in terms of TS Validation BUT it breaks the explorer whereby `Try it out` only gives me a `{}` instead of the model that I could just edit.

**Comment by raymondfeng** [comment]
Yes, I commented in https://github.com/strongloop/loopback-next/issues/1722. We need to have a way to reflect such TS types in OpenAPI spec.

**Comment by bajtos** [comment]
The problem may be easy to fix - see the discussion in https://github.com/strongloop/loopback-next/issues/2658 and the following code:

https://github.com/strongloop/loopback-next/blob/a396274db3ecd0486b686f4e7f0703636e57e97b/packages/repository/src/repositories/constraint-utils.ts#L58-L59
