### ISSUE TITLE
Shared tslint and tsconfig

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#174]
In the spirit of `eslint-config-loopback`, we should move our tsc and tslint configuration to a shared package that can be used by other LoopBack.next projects, e.g. loopback-next-example.

cc @ritch @superkhau

**Comment by superkhau** [comment]
Any ideas for the name of the package? Does tslint provide conventions like http://eslint.org/docs/user-guide/configuring#using-a-shareable-configuration-package?

**Comment by bajtos** [comment]
**I am proposing `@loopback/tsling-config`**

tslint does provide conventions for sharing rules, see [sharable-configuration-rules](https://palantir.github.io/tslint/2016/03/31/sharable-configurations-rules.html). In the post, they are using `shared-tslint-rules` as the project name. Other people seem to use `tslint-config-{name}`, see e.g.

 - https://www.npmjs.com/package/tslint-config-olo
 - https://www.npmjs.com/package/tslint-config-ezhome
 - https://www.npmjs.com/package/tslint-config-standard

BTW we may want to consider using some eslint rules via https://github.com/buzinas/tslint-eslint-rules, but that's out of scope of this patch. OTOH, I personally think we should move to Prettier (see #165) and configure tslint only to check for programming errors only.

**Comment by superkhau** [comment]
Prettier looks nice, I like the philosophy. +1

I'm fine with @loopback/tsling-config.

Using some ESLint rules is fine, we can address those when they actually come up IMO.

**Comment by dhmlau** [comment]
relate to: https://github.com/strongloop/loopback-next/issues/165

**Comment by bajtos** [comment]
Closing as done by https://github.com/strongloop/loopback-next/pull/682
