### ISSUE TITLE
Enumerate model properties in Filter/Where schema

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1748]
The pull request #1679 is adding `getFilterJsonSchemaFor` API for obtaining a JSON/OpenAPI schema of a `filter` argument. The initial implementation is generic and does not describe the actual model properties in the schema. Let's fix that!

 - LB4 models are strict by default (extra properties are not allowed).
 - It's possible to create a LB4 model that allows additional properties, Filter schema needs to detect and support this case.
 - Besides model properties, `where` object can contain operators like `and`, `or`, `inq`. See their full list in our docs: [Where filter: Operators](https://loopback.io/doc/en/lb3/Where-filter.html#operators).
 - Besides `where` condition, model properties are used by `fields` property too.

**Comment by ghsamm** [comment]
Hello @bajtos, I'm working on this as my first open-source commit.

Here is how I made it work for fields:

```
fields: {
    type: 'object',
    properties: Object.assign(
        {},
        ...Object.keys(modelCtor.definition.properties).map(k => ({
            [k]: {type: 'boolean'},
        })),
    ),
    additionalProperties: true,
}
```

I can follow the same principle for other properties if you think I'm going in the right direction.

Here is my pull request: https://github.com/strongloop/loopback-next/pull/2241

I am very excited to start contributing to such a great project. Please tell me if there is something I can improve to get my PRs accepted.

**Comment by bajtos** [comment]
Closing as done via https://github.com/strongloop/loopback-next/pull/2241
