### ISSUE TITLE
Sugar decorators for Filter and Where parameters

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1749]
See https://github.com/strongloop/loopback-next/pull/1679#discussion_r219726035

Let's add few more `@param` flavors to simplify declaration of Filter and Where arguments.

```ts
@param.query.filter(Todo)
// alias for @param.query.object('filter', getFilterSchemaFor(Todo))

@param.query.filter('filterObj', Todo)
// alias for @param.query.object('filterObj', getFilterSchemaFor(Todo))

@param.query.where(Todo)
// alias for @param.query.object('where', getWhereSchemaFor(Todo))

@param.query.where('whereObj', Todo)
// alias for @param.query.object('whereObj', getWhereSchemaFor(Todo))
```

## Acceptance criteria
- [ ] Implement `@param.query.filter` and `@param.query.where` as outlined above. Test must be included, try to work test first. (Follow TestDrivenDevelopment - start by adding a failing test, and so on.)
- [ ] Update REST Controller template to use these new shortcuts
- [ ] Update all example controllers to use these new shortcuts
- [ ] Update code examples in the tutorial documentation pages to match the updated source code of controllers

**Comment by dougal83** [comment]
``@param.query.object('whereObj', getWhereSchemaFor(Todo))``

I have a concern with there being a query parameter being described externally as an object.  If we have the open api spec describing the query parameter as an object, it raises a question of how we serialise into a string and satisfy the type externally based on the spec?

**Comment by dhmlau** [comment]
@bajtos @dougal83, what's your suggestion on how to handle this issue? (part of the Q1 planning). Thanks.

**Comment by raymondfeng** [comment]
Implemented by https://github.com/strongloop/loopback-next/pull/4745
