### ISSUE TITLE
[SPIKE] [CI] Azure Pipelines

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1752]
## Description / Steps to reproduce / Feature proposal

See https://github.com/marketplace/azure-pipelines

Azure Pipelines offers 10 parallel builds for Open Source Projects and offers the capability of being the one-stop shop for testing on Linux, macOS, Windows (vs. the current setup of Travis + AppVeyor (so slow ... ugh)). 

The purpose of this spike is to investigate the feasibility of testing the feasibility of switching to Azure Pipelines. I would propose the plan be to add the integration but not make it a required check. This will allow these builds to run alongside the current setup and we can see if it's faster / slower / other issues etc. Let this run against the repo for 30-days and then have a spike results meeting to discuss with the team what they noticed with Azure vs. the current setup (speed, reliability, etc). Make a decision to proceed with keeping it or not. If keeping it / switching to it as the default -- make it a required check, remove Travis, AppVeyor. 

## Spike Criteria

- [ ] Add Azure Pipelines to this repository (must be done by the org owner)
- [ ] Configure it to run out Linting (on Linux) + Tests (on all 3 platforms + Node 8, 10)
- [ ] Ensure pipeline is hooked into GitHub PR Status API but is **not** a **required** check.
- [ ] Let it run for 30 days for monitoring while the team observes speed, reliability, etc. 
- [ ] Have a spike meeting to discuss team observations and to decide if this should be adopted in place of the current CI pipelines we have
- [ ] Document outcome (adopted / rejected) on this ticket as results of the spike for the community to know our reason for the switch

**IF ADOPTED**
- [ ] Make the check required on GitHub PRs
- [ ] Remove Travis + AppVeyor
- [ ] Blog

**IF REJECTED**
- [ ] Remove Azure Pipelines optional check from the repo

**Comment by kaylangan** [comment]
I'm a Program Manager for Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

**Comment by bajtos** [comment]
The TypeScript project seem to have a reasonably complex pipeline configuration including "nightly publish", it may be a good source of inspiration for our setup.

https://typescript.visualstudio.com/TypeScript/_build
