### ISSUE TITLE
Maybe some mistakes in comment?

### ISSUE THREAD

**Issue by dreamdevil00** [strongloop/loopback-next#1756]
## Description / Steps to reproduce / Feature proposal
In [datasource.booter.ts](https://github.com/strongloop/loopback-next/blob/7e1acfc1e72da89e22421c8e94aaac3ba9083e0d/packages/boot/src/booters/datasource.booter.ts#L49) , the comment seems copyed from repository.ts.
## Current Behavior
The comment is about repository, not datasource
## Expected Behavior
comment about datasource

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by virkt25** [comment]
Fixed. Thanks for pointing this out @dreamdevil00
