### ISSUE TITLE
Relational Controllers

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#1758]
## Description / Steps to reproduce / Feature proposal

Based on https://github.com/strongloop/loopback4-example-shopping/pull/12#discussion_r219978416

I am proposing we eventually add support to our existing relational controllers for manipulating individual related models. 

Ex:
```
/users/{userId}/orders/{orderId}
```

So this in its current form is not all that helpful as one would argue being able to directly manipulate the model using `/orders/{orderId}` as we don't have referential integrity (https://github.com/strongloop/loopback-next/issues/1718) yet ... but once we do, this can help ensure that only users with access to an order are the ones manipulating it. 

This could also just be solved using authorization and may not be needed. 

The purpose of this issue is to drive a discussion to figure out if this is needed or not.

**Comment by bajtos** [comment]
Cross-posting https://github.com/strongloop/loopback4-example-shopping/pull/12#issuecomment-424280027

>We should probably introduce singular controllers for these operations where the orderId is known. 
> 
>`/users/{userId}/orders/{orderId}` 

We have discussed this in the past, when implementing "hasMany" relation. Updating a single model via relation endpoint does not make much sense. Once you know the id of the target model (`orderId`), you can update the model directly via non-relation API (`PATCH /orders/{orderId}`).

The endpoint `/users/{userId}/orders/{orderId}` would make sense if we were using composite primary keys (e.g. an order is identified by `(userId, orderId)`, think of how GitHub repositories are identified), but our current implementation does not support composite keys AFAIK.

---

Personally, I think we have more pressing issues to deal with at the moment. I am proposing to put this story on hold for now.

@dhmlau @raymondfeng @strongloop/sq-lb-apex thoughts?
