### ISSUE TITLE
landing page has a mistake for the git clone link

### ISSUE THREAD

**Issue by stuzenz** [strongloop/loopback-next#1762]
## Description / Steps to reproduce / Feature proposal
Really simple - there seems to be a mistake on your landing page

http://v4.loopback.io/getting-started-oasgraph.html
git clone git@github.com:strongloop/oasgraph.git

going to the repository
git clone https://github.com/strongloop/oasgraph.git

**Comment by raymondfeng** [comment]
Both git urls should work.
