### ISSUE TITLE
@loopback/cli  update notification 

### ISSUE THREAD

**Issue by marioestradarosa** [strongloop/loopback-next#1768]
## Description / Steps to reproduce / Feature proposal
```sh
lb4 --version
@loopback/cli version: 0.24.0
``` 

and then 

```sh
npm install -g @loopback/cli
..
 - @loopback/http-caching-proxy: ^0.3.11
  - @loopback/http-server: ^0.4.2
  - @loopback/example-todo-list: ^0.6.1

```

finally.

```sh
 lb4 --version
@loopback/cli version: 0.26.0
   ╭──────────────────────────────────────────╮
   │                                          │
   │    Update available 0.24.0 → 0.26.0      │
   │   Run npm i -g @loopback/cli to update   │
   │                                          │
   ╰──────────────────────────────────────────╯
```

## Current Behavior

It is asking me to update, after the update was completed.

## Expected Behavior

Shouldn't display anything since I am upgrading. Probably the message should be displayed on any `lb4` command such as the first `lb4 --version` above. ?

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
The implementation is based on https://github.com/yeoman/update-notifier. It's by design not to prompt users the 1st time.

When `lb4 --version` is invoked, we forced the check by setting the interval to 0. 

Are you seeing the the box shows up right after `npm i -g @loopback/cli`?

**Comment by marioestradarosa** [comment]
> Are you seeing the the box shows up right after npm i -g @loopback/cli?


correct, that's the last message after running npm i -g

**Comment by marioestradarosa** [comment]
@raymondfeng,

I installed again `@loopback/cli version: 0.24.0`, then I ran the following commands:

`lb4 --version`   -- gave me 0.24.0 no upgrade notification
`npm i -g @loopback/cli` -- installed the latest 0.26.0 , no upgrade notification
`lb4 --version`  -- showed me the output below with upgrade notification

```sh
@loopback/cli version: 0.26.0

@loopback/* dependencies:
  - @loopback/authentication: ^0.11.16
  - @loopback/boot: ^0.14.2
  - @loopback/build: ^0.7.4
  - @loopback/context: ^0.12.12
  - @loopback/core: ^0.11.13
  - @loopback/metadata: ^0.9.11
  - @loopback/openapi-spec-builder: ^0.9.3
  - @loopback/openapi-v3-types: ^0.9.5
  - @loopback/openapi-v3: ^0.15.1
  - @loopback/repository-json-schema: ^0.11.1
  - @loopback/repository: ^0.18.1
  - @loopback/rest: ^0.25.1
  - @loopback/testlab: ^0.14.1
  - @loopback/docs: ^0.21.1
  - @loopback/example-hello-world: ^0.10.2
  - @loopback/example-log-extension: ^0.11.16
  - @loopback/example-rpc-server: ^0.11.10
  - @loopback/example-todo: ^0.20.1
  - @loopback/example-soap-calculator: ^0.4.2
  - @loopback/dist-util: ^0.3.7
  - @loopback/service-proxy: ^0.8.7
  - @loopback/http-caching-proxy: ^0.3.11
  - @loopback/http-server: ^0.4.2
  - @loopback/example-todo-list: ^0.6.1


   ╭──────────────────────────────────────────╮
   │                                          │
   │    Update available 0.24.0 → 0.26.0      │
   │   Run npm i -g @loopback/cli to update   │
   │                                          │
   ╰──────────────────────────────────────────╯
````

**Comment by marioestradarosa** [comment]
@raymondfeng , the notification only happens once, if I run `lb4 --version` again, it disappears. Probably it is something not too important to address at this moment.

**Comment by marioestradarosa** [comment]
On another note,

I made search on their repo and found that some do to solve this.

```ts
       if(notifier.update &&
           notifier.update.latest !== pkg.version) {
            // Notify using the built-in convenience method
            notifier.notify();
        }
```
