### ISSUE TITLE
[Docs] Add docs for exposing GraphQL APIs

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1775]
## Description / Steps to reproduce / Feature proposal
Currently user can do the following steps to create GraphQL APIs within a LoopBack app:

1. Run npm i --save express express-graphql oasgraph
2. Make sure the LB app has started. 
3. From the browser, go to http://localhost:3000/openapi.json, copy the openapi.json, and save it under the root of the LoopBack application, say `todo-openapi.json`
4. Run `./node_modules/.bin/oasgraph todo-openapi.json`
5. Test it by going to http://localhost:3001/graphql

## Acceptance Criteria
- [ ] Determine where to put the docs.  
   - Perhaps as one of the tutorials in https://loopback.io/doc/en/lb4/Examples-and-tutorials.html
- [ ] Create the docs page with the above steps 
   - Verify the steps first as things might've changed by the time of writing.

**Comment by marioestradarosa** [comment]
> create GraphQL APIs

For what I understood, please correct me, it can only expose GraphQL Schemas from the OpenAPI spec file, but not it won't create any API.  If this is correct ,then I think you should change the title, otherwise, ignore this message 😄

**Comment by marioestradarosa** [comment]
@dhmlau , Here is my summary for this weekend. I played with OASGraph as a library and wrote this small presentation. We need to check what to add/remove etc. I see a potential way to mount the /graphql using the internal express. So, the developer can configure the option if he/she wants a graphql server , something like `{ graphql : { available: true, mountPoint: '/graphql' } }`  passing this to the application, the internal express can be used to create it using oasgraph as the translator. 

At this moment, I just played with the two dependencies and could manage to make a working loopback 4 application with no problems. I think the only problem at this moment is the the Delete operation not being sent the correct format to **OASGraph**, I will open an issue on this, aside from that I could test the relationships on the todo-list querying them and works fine. 

Here is a small video presentation summarizing my findings this weekend. Note that the current oasgraph CLI is only used to test an openapi.json spec file, this won't work in production, probably the best way is to use the mechanism I placed on the video, this way, I didn't have to install the oasgraph CLI or run npm link etc.

https://www.youtube.com/watch?v=s2hScucNmaA

**Comment by dhmlau** [comment]
@marioestradarosa , yes, but I haven't given too much thought on where it should be. :)   Any suggestion? 
FYI - As part of the QuickLab/workshop for Node+JS Interactive (soon will be available in [IBM Developer web site](https://developer.ibm.com/)), we've adding that instruction on top of the todo tutorial.

**Comment by dhmlau** [comment]
sure. sounds good.
