### ISSUE TITLE
Add support for type-safe queries

### ISSUE THREAD

**Issue by gms1** [strongloop/loopback-next#1777]
## Feature proposal

Hallo loopback team,

please provide a mechanism for building type-safe queries (e.q Where/Filter objects), which would make refactoring much easier.

Building type-safe queries could be done by the use of the TypeScript 'keyof' operator (validity of the property names) in combination with the TypeScript indexed access operator 'T[K]' (validity of the property types) 

sample:
https://github.com/gms1/node-sqlite3-orm/blob/master/src/sqlite3orm/query/Where.ts

## Current Behavior

*  Where/Filter are not type-safe
*  refactoring of entity properties (names/types) is not supported 

## Expected Behavior

*  Where/Filter or similar objects should be type-safe
*  refactoring of entity properties (names/types) should be easy

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
Have you checked out https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/query.ts? Using keyOf is a good idea to improve the type safety. I’ll take a look.

Patches are welcome!

**Comment by gms1** [comment]
yes, I've already seen that; that should not be so hard to change.
I am just not sure if we can/should start this before GA, if the 'repository' package will be moved (into the new monorepo for the juggler packages), if this query-syntax can be changed, if necessary, if I can spend enough time,...
I'll start reading the contribution guide now :-)

btw since you are also involved in the community connector for sqlite3: Since this connector is not intended for the new monorepo and therefore not much progress can be expected in the near future, there is now another sqlite3-connector:
https://github.com/gms1/loopback-connector-sqlite3x

**Comment by raymondfeng** [comment]
@gms1 That looks great! I added a comment. Would like to open a PR to make the review easier?

**Comment by gms1** [comment]
yes I will, but first I would like to check these points:
1. Promise support would require the juggler to await the query values; if it does not already, I want to remove this feature from this PR (otherwise I have to write unit tests)
2. default type AnyObject for Where / Filter / WhereBuilder / FilterBuilder to avoid the breaking change (as you suggested)
3. typing complex queries to see if the compiler/IntelliSense works as expected
(apart from 1) the whole thing can only be tested manually)

So I will not be able to do this PR until the middle/end of the next week

**Comment by gms1** [comment]
I had unexpectedly spare time to follow up this PR today: #1782

and I am going to report additional issues:

1. examples in 'packages/repository/examples/juggler-bridge/\*.ts' are broken:
   AssertionError [ERR_ASSERTION]: Entity Note must have at least one id/pk
   property.

2. the 'eq' operator (defined in 'packages/repository/src/query.ts') is not
   supported by the current juggler so {title: {eq: 't1'}' does not work ( the
   shorthand form {title: 't1'} is ok ).

   Should this be reported as bug for loopback-next or as feature request for
   loopback-datasource-juggler? Because of consistency (to the 'neq' operator),
   I would like to vote for the feature request.

3. feature request: support for the 'like' operator

4. how about logical 'not'? based on the current juggler, at least 'nin' (NOT IN) and
   'nlike' (NOT LIKE) are missing

**Comment by dhmlau** [comment]
PR: https://github.com/strongloop/loopback-next/pull/1816

**Comment by dhmlau** [comment]
@gms1 , PR #1816 has merged.  Is this issue good to close? Thanks.

**Comment by gms1** [comment]
yes, many thanks!
