### ISSUE TITLE
CLI generates controller code that does not compile

### ISSUE THREAD

**Issue by john-boy** [strongloop/loopback-next#1778]
## Description / Steps to reproduce / Feature proposal
Use lb4 controller to generate a REST controller with CRUD functions.

## Current Behavior
The code generated for count and patch/updateAll results in a compiler error.
error TS2322: Type 'Count' is not assignable to type 'number'.

## Expected Behavior
The code expected result should match the actual repository result.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by virkt25** [comment]
Tried reproducing it and was unable to do so. If you updated to the latest version of the CLI, you will also have to update `@loopback/repository` in your application to ensure the new interfaces are available to your app. For reference, here are all the versions you should be on from the latest release. 

```
- @loopback/benchmark@0.2.16
 - @loopback/docs@0.22.0
 - @loopback/example-hello-world@0.10.3
 - @loopback/example-log-extension@0.11.17
 - @loopback/example-rpc-server@0.11.11
 - @loopback/example-soap-calculator@0.4.3
 - @loopback/example-todo-list@0.7.0
 - @loopback/example-todo@0.20.2
 - @loopback/authentication@0.11.17
 - @loopback/boot@0.14.3
 - @loopback/cli@0.27.0
 - @loopback/context@0.12.13
 - @loopback/core@0.11.14
 - @loopback/http-server@0.4.3
 - @loopback/metadata@0.9.12
 - @loopback/openapi-v3@0.15.2
 - @loopback/repository-json-schema@0.11.2
 - @loopback/repository@0.19.0
 - @loopback/rest@0.25.2
 - @loopback/service-proxy@0.8.8
```

If you're still running into issues please let us know the version of the packages you are using.

**Comment by dhmlau** [comment]
@john-boy , with the [above comment](https://github.com/strongloop/loopback-next/issues/1778#issuecomment-425649247) from @virkt25, this should probably resolve your problem. Therefore, I'd like to close this issue.  
Please feel free to ping here if your problem still exists.  Thanks for adopting LoopBack 4!
