### ISSUE TITLE
repository: the use of the 'eq' condition in a Where-object is silently failing

### ISSUE THREAD

**Issue by gms1** [strongloop/loopback-next#1788]
## Description / Steps to reproduce / Feature proposal

definitions from repository/src/query.ts or loopback-datasource-juggler/types/query.d.ts:
```TypeScript

/**
 * Matching condition
 */
export interface Condition {
  eq?: any;
  neq?: any;
  gt?: any;
  gte?: any;
  lt?: any;
  lte?: any;
  inq?: any[];
  between?: any[];
  exists?: boolean;
  and?: Where[];
  or?: Where[];
}

/**
 * Where object
 *
 * Examples:
 * `{afieldname: 'aName'}`
 * `{and: [{fieldone: 'one'}, {fieldtwo: 'two'}]}`
 * `{or: [{fieldone: 'one'}, {fieldtwo: 'two'}]}`
 */
export interface Where {
  and?: Where[]; // AND
  or?: Where[]; // OR
  [property: string]: Condition | any; // Other criteria
}
```
so this should be a valid Where-object:
```TypeScript
const where = {title: {eq: 'foo'}};
```
but this operator is not implemented by the juggler (please see the 'operators' object in 'loopback-datasource-juggler/lib/dao.js'), which seems to interpret this condition as a kind of shorthand form and is using the string literal "[object Object]" as parameter for this query

```Bash
gms@orion:~/tmp$ grep -Rw eq loopback-datasource-juggler/lib/
gms@orion:~/tmp$ grep -Rw neq loopback-datasource-juggler/lib/
node_modules/loopback-datasource-juggler/lib/dao.js:  neq: '!=',
node_modules/loopback-datasource-juggler/lib/dao.js: * - neq: !=
node_modules/loopback-datasource-juggler/lib/connectors/memory.js:        // a neq filter, and when the value is an empty array ([]).
node_modules/loopback-datasource-juggler/lib/connectors/memory.js:        if (matcher.neq !== undefined && value.length <= 0) {
node_modules/loopback-datasource-juggler/lib/connectors/memory.js:      if ('neq' in example) {
node_modules/loopback-datasource-juggler/lib/connectors/memory.js:        return compare(example.neq, value) !== 0;
```

## Current Behavior
using the 'eq' operator does not work
## Expected Behavior
either the 'eq' operator should be removed from the Condition interface or the juggler should implement the missing 'eq' operator

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
@gms1 Good catch. We might want to convert `x: {eq: 1}` to `{x: 1}`. I'm also fine to disable `eq` for now.

**Comment by raymondfeng** [comment]
A patch is welcome!

**Comment by dhmlau** [comment]
@gms1 , does the "type-safe queries" PR fix the problem?  Since #1782 is merged, is this ticket good to close?  Thanks.

**Comment by gms1** [comment]
I don't think so: while the 'WhereBuilder' is only using the shorthand form (e.g ```{x: 1}```), it is actually possible to manually write a 'Where' object using the wrong longhand form (e.g. ```{x: {eq: 1}}```), so as @raymondfeng already mentioned, we should consider disabling the 'eg' from 'Operators' and from 'PredicateComparison'
if nobody does that in front of me, I'll create this patch, but unfortunately it's not possible for me in the next days

**Comment by raymondfeng** [comment]
@gms1 I'm fixing it in juggler as part of https://github.com/strongloop/loopback-datasource-juggler/pull/1638. If we see `eq`, we drop the operator.

**Comment by dhmlau** [comment]
Fixed via https://github.com/strongloop/loopback-datasource-juggler/pull/1638. Closing this issue as resolved.
