### ISSUE TITLE
Pre-release prep/cleanup

### ISSUE THREAD

**Issue by rmg** [strongloop/loopback-next#179]
Should the top-level package be marked as `private` so that it can't be accidentally published?

* [x] check that all sub-packages are private if needed (eg. `example-codehub`)
* [x] remove placeholder packages (eg. `@loopback/remoting`, `@loopback/juggler`)
* [ ] ensure all packages have a (minimal) README following https://loopback.io/doc/en/contrib/README-guidelines.html
* [x] consider renaming `@loopback/loopback` back to `@loopback/core`, or if we want to keep `@loopback` scope, then use `@loopback/core` or similar.

For local testing purposes, you can use `ephemeral-npm` to test out the `npm publish` aspects with something like this (assuming `docker` native or Docker for Mac), other wise adjust `127.0.0.1` to match the exposed IP):
```
$ docker run -d -p 4873:4873 \
    -e NPM_USER=admin -e NPM_PASSWORD=admin -e NPM_SECRET=supersecret \
    strongloop/ephemeral-npm:verdaccio-alpine
$ npm config set //127.0.0.1:4873/:_authToken "vxtX8n4r7W3fjABQi6uJyQ=="
$ npm_config_registry=http://127.0.0.1:4873/ lerna publish --skip-git
```

/cc @bajtos @ritch

**Comment by bajtos** [comment]
Yes please 👍 ✖️ 💯

**Comment by bajtos** [comment]
Added one more task:
> ensure all packages have a (minimal) README following https://loopback.io/doc/en/contrib/README-guidelines.html

**Comment by bajtos** [comment]
Added two more items:

> - consider adding `"publishConfig": { "tag": "next" }` to `package.json` of all modules
> - consider renaming `@loopback/loopback` back to `loopback`, or if we want to keep `@loopback` scope, then use `@loopback/core` or similar.

**Comment by raymondfeng** [comment]
-1 to rename `@loopback/loopback` back to `loopback`.
+1 to use `@loopback/core`.

**Comment by jonathan-casarrubias** [comment]
100% agree with @raymondfeng not to `loopback` thumbs up to `@loopback/core`

**Comment by superkhau** [comment]
Everything in this list is done:

Follow up issues:

- Minimal READMEs at https://github.com/strongloop/loopback-next/issues/260
- `next` tags at https://github.com/strongloop/loopback-next/issues/261
