### ISSUE TITLE
lb4 finds no datasource despite having been used to generate one

### ISSUE THREAD

**Issue by koalabi** [strongloop/loopback-next#1791]
## Description / Steps to reproduce / Feature proposal
Although lb4 has been used to generate datasource and model, it finds no datasource at the moment of creating a repository.
The error message provides a link to a page describing how a datasource should be created to be discoverable but there is nothing there that my datasource (created by lb4) violates.

Versions:
* Node: 10.0.0
* Loopback-cli: 0.27
* OS: Ubuntu 16.04LTS

## Current Behavior
alain@aegnor:\~/devel/strongloop/lb-4-test-2$ ls -l src
total 28
-rw-rw-r-- 1 alain alain  836 sep 29 22:28 application.ts
drwxrwxr-x 2 alain alain 4096 sep 29 22:28 controllers
drwxrwxr-x 2 alain alain 4096 sep 29 22:33 datasources
-rw-rw-r-- 1 alain alain  416 sep 29 22:28 index.ts
drwxrwxr-x 2 alain alain 4096 sep 29 22:28 models
drwxrwxr-x 2 alain alain 4096 sep 29 22:28 repositories
-rw-rw-r-- 1 alain alain 1012 sep 29 22:28 sequence.ts
alain@aegnor:\~/devel/strongloop/lb-4-test-2$ ls -lR src
src:
total 28
-rw-rw-r-- 1 alain alain  836 sep 29 22:28 application.ts
drwxrwxr-x 2 alain alain 4096 sep 29 22:28 controllers
drwxrwxr-x 2 alain alain 4096 sep 29 22:33 datasources
-rw-rw-r-- 1 alain alain  416 sep 29 22:28 index.ts
drwxrwxr-x 2 alain alain 4096 sep 29 22:28 models
drwxrwxr-x 2 alain alain 4096 sep 29 22:28 repositories
-rw-rw-r-- 1 alain alain 1012 sep 29 22:28 sequence.ts

src/controllers:
total 16
-rw-rw-r-- 1 alain alain  748 sep 29 22:28 home-page.controller.ts
-rw-rw-r-- 1 alain alain   35 sep 29 22:28 index.ts
-rw-rw-r-- 1 alain alain 1188 sep 29 22:28 ping.controller.ts
-rw-rw-r-- 1 alain alain  337 sep 29 22:28 README.md

src/datasources:
total 16
-rw-rw-r-- 1 alain alain  42 sep 29 22:33 index.ts
-rw-rw-r-- 1 alain alain 182 sep 29 22:33 keywords-ds.datasource.json
-rw-rw-r-- 1 alain alain 403 sep 29 22:33 keywords-ds.datasource.ts
-rw-rw-r-- 1 alain alain  80 sep 29 22:28 README.md

src/models:
total 4
-rw-rw-r-- 1 alain alain 72 sep 29 22:28 README.md

src/repositories:
total 4
-rw-rw-r-- 1 alain alain 84 sep 29 22:28 README.md
alain@aegnor:\~/devel/strongloop/lb-4-test-2$ lb4 model
? Model class name: Keyword

Let's add a property to Keyword
Enter an empty property name when done

? Enter the property name: id
? Property type: number
? Is id the ID property? Yes
? Is it required?: Yes
? Default value [leave blank for none]: 

Let's add another property to Keyword
Enter an empty property name when done

? Enter the property name: label
? Property type: string
? Is it required?: Yes
? Default value [leave blank for none]: 

Let's add another property to Keyword
Enter an empty property name when done

? Enter the property name: description
? Property type: string
? Is it required?: Yes
? Default value [leave blank for none]: 

Let's add another property to Keyword
Enter an empty property name when done

? Enter the property name: comment
? Property type: string
? Is it required?: No
? Default value [leave blank for none]: 

Let's add another property to Keyword
Enter an empty property name when done

? Enter the property name: 
   create src/models/keyword.model.ts
   update src/models/index.ts

Model Keyword was created in src/models/

alain@aegnor:\~/devel/strongloop/lb-4-test-2$ lb4 repository
**Generation is aborted: Error: No datasources found at /media/elrond_2tb/devel/strongloop/lb-4-test-2/src/datasources.
        Please visit https://loopback.io/doc/en/lb4/DataSource-generator.html for information on how datasources are discovered**

alain@aegnor:\~/devel/strongloop/lb-4-test-2$ lb4 -v
@loopback/cli version: 0.27.0

@loopback/* dependencies:
  - @loopback/authentication: ^0.11.17
  - @loopback/boot: ^0.14.3
  - @loopback/build: ^0.7.4
  - @loopback/context: ^0.12.13
  - @loopback/core: ^0.11.14
  - @loopback/metadata: ^0.9.12
  - @loopback/openapi-spec-builder: ^0.9.3
  - @loopback/openapi-v3-types: ^0.9.5
  - @loopback/openapi-v3: ^0.15.2
  - @loopback/repository-json-schema: ^0.11.2
  - @loopback/repository: ^0.19.0
  - @loopback/rest: ^0.25.2
  - @loopback/testlab: ^0.14.1
  - @loopback/docs: ^0.22.0
  - @loopback/example-hello-world: ^0.10.3
  - @loopback/example-log-extension: ^0.11.17
  - @loopback/example-rpc-server: ^0.11.11
  - @loopback/example-todo: ^0.20.2
  - @loopback/example-soap-calculator: ^0.4.3
  - @loopback/dist-util: ^0.3.7
  - @loopback/service-proxy: ^0.8.8
  - @loopback/http-caching-proxy: ^0.3.11
  - @loopback/http-server: ^0.4.3
  - @loopback/example-todo-list: ^0.7.0

## Expected Behavior
The expected behavior is that lb4 finds a datasource it has generated itself ;-)

**Comment by marioestradarosa** [comment]
@koalabi , thank you for your time and effort to test this feature. The PR was landed, so the issue was closed automatically. The patch will be available in the next CLI publication to npm, hopefully it won't take that long.

**Comment by koalabi** [comment]
@marioestradarosa 
Thanks again for the support, Mario
As you asked (late but I couldn't act before), my .json and .ts files (without the credentials, of course)

keywords-ds.datasource.json:
{
  "name": "KeywordsDS",
  "connector": "mysql",
  "url": "",
  "host": "ds_bla002.local",
  "port": 23306,
  "user": "xxx",
  "password": "xxx",
  "database": "lb4test_2"
}

===============
keywords-ds.datasource.ts:
import { inject } from '@loopback/core';
import { juggler, AnyObject } from '@loopback/repository';
import config = require('./keywords-ds.datasource.json');

export class KeywordsDSDataSource extends juggler.DataSource {
  static dataSourceName = 'KeywordsDS';

  constructor(
    @inject('datasources.config.KeywordsDS', { optional: true })
    dsConfig: AnyObject = config,import { inject } from '@loopback/core';
import { juggler, AnyObject } from '@loopback/repository';
import config = require('./keywords-ds.datasource.json');

export class KeywordsDSDataSource extends juggler.DataSource {
  static dataSourceName = 'KeywordsDS';

  constructor(
    @inject('datasources.config.KeywordsDS', { optional: true })
    dsConfig: AnyObject = config,
  ) {
    super(dsConfig);
  }
}

  ) {
    super(dsConfig);
  }
}

Is there any modification I can do to the source code/filenames to go further in my exploration? (I have had a look at the source code (mainly diffs) but it is not obvious) If too complicated to explain, feel free to ignore and I will wait.

Kind regards,
Alain

**Comment by marioestradarosa** [comment]
> Is there any modification I can do to the source code/filenames to go further in my exploration?

Probably the best way so far would be to remove the data sources files along with the line inside index.ts and recreate it with any name such as Keworkds . Once the patch is published on npm you will be able to name it KeywordDS.  -- ps: also remove the repository generated and recreate it.

**Comment by koalabi** [comment]
Thanks for the info. I tried (recreated the datasource and then created the repository. It worked better (found the datasource) but I got an error while creating the repository.
It's reproduced below just for info (I need to see whether it's reproducible and to do the manipulation again):

alain@aegnor:~/devel/strongloop/lb-4-test-2/src$ lb4 repository

Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: /media/elrond_2tb/devel/strongloop/lb-4-test-2
? Please select the datasource KeywordsDatasource
? Select the model(s) you want to generate a repository Keyword
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: node.forEachChild is not a function
    at traverse (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/@phenomnomnominal/tsquery/dist/src/traverse.js:50:14)
    at Object.traverseChildren (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/@phenomnomnominal/tsquery/dist/src/traverse.js:29:5)
    at Object.match (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/@phenomnomnominal/tsquery/dist/src/match.js:11:16)
    at query (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/@phenomnomnominal/tsquery/dist/src/query.js:11:20)
    at Object.exports.getIdFromModel (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/lib/ast-helper.js:119:19)
    at RepositoryGenerator._getModelIdProperty (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/generators/repository/index.js:59:20)
    at RepositoryGenerator.promptModelId (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/generators/repository/index.js:381:35)
    at Object.<anonymous> (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/yeoman-generator/lib/index.js:424:27)
    at /home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

Kind regards,
Alain

**Comment by marioestradarosa** [comment]
> Just found a .yo-rc.json in a parent directory.
 
This happens if you are not in root directory of the project. You are executing it inside src/ subdirectory.

**Comment by marioestradarosa** [comment]
One thing to look at is the  TS dependency for the ATS system. Fixed here in this PR, which probably hasn't been published to NPM yet.   https://github.com/strongloop/loopback-next/pull/1790

**Comment by koalabi** [comment]
Thanks for the info. I tried (recreated the datasource and then created the repository. It worked better (found the datasource) but I got an error while creating the repository.
It's reproduced below just for info (I need to see whether it's reproducible and to do the manipulation again):

alain@aegnor:~/devel/strongloop/lb-4-test-2/src$ lb4 repository

Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: /media/elrond_2tb/devel/strongloop/lb-4-test-2
? Please select the datasource KeywordsDatasource
? Select the model(s) you want to generate a repository Keyword
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: node.forEachChild is not a function
    at traverse (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/@phenomnomnominal/tsquery/dist/src/traverse.js:50:14)
    at Object.traverseChildren (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/@phenomnomnominal/tsquery/dist/src/traverse.js:29:5)
    at Object.match (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/@phenomnomnominal/tsquery/dist/src/match.js:11:16)
    at query (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/@phenomnomnominal/tsquery/dist/src/query.js:11:20)
    at Object.exports.getIdFromModel (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/lib/ast-helper.js:119:19)
    at RepositoryGenerator._getModelIdProperty (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/generators/repository/index.js:59:20)
    at RepositoryGenerator.promptModelId (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/generators/repository/index.js:381:35)
    at Object.<anonymous> (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/yeoman-generator/lib/index.js:424:27)
    at /home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

Kind regards,
Alain

**Comment by koalabi** [comment]
@marioestradarosa 
Hi Mario,
I tried again this evening, in a new project created from scratch. I also made sure TypeScript was installed locally and on the PATH (see transcript). The problem persists:

alain@aegnor:\~/devel/strongloop/testlb-4-1$ export PATH=/media/elrond_2tb/devel/strongloop/testlb-4-1/node_modules/typescript/bin:$PATH
alain@aegnor:\~/devel/strongloop/testlb-4-1$ hash -r
alain@aegnor:\~/devel/strongloop/testlb-4-1$ tsc -v
Version 3.1.1
alain@aegnor:~/devel/strongloop/testlb-4-1$ lb4 repository? Please select the datasource KeywordsDatasource
? Select the model(s) you want to generate a repository Keyword
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: node.forEachChild is not a function
    at traverse (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/@phenomnomnominal/tsquery/dist/src/traverse.js:50:14)
    at Object.traverseChildren (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/@phenomnomnominal/tsquery/dist/src/traverse.js:29:5)
    at Object.match (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/@phenomnomnominal/tsquery/dist/src/match.js:11:16)
    at query (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/@phenomnomnominal/tsquery/dist/src/query.js:11:20)
    at Object.exports.getIdFromModel (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/lib/ast-helper.js:119:19)
    at RepositoryGenerator._getModelIdProperty (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/generators/repository/index.js:59:20)
    at RepositoryGenerator.promptModelId (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/generators/repository/index.js:381:35)
    at Object.<anonymous> (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/yeoman-generator/lib/index.js:424:27)
    at /home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/alain/.nvm/versions/node/v10.0.0/lib/node_modules/@loopback/cli/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

Based on some paths in the stack trace, it seems I indeed use NVM but I don't think I installed it explicitly (not sure, though - then it was quite a time ago).

This is just for info. I will proceed (possibly creating the repository manually) and will wait for a forthcoming npm (and possibly lb4) update.

Thanks for your prompt and efficient support.
Regards,
Alain

**Comment by koalabi** [comment]
@marioestradarosa,

Re: your kind request to try again "lb4 repository" with CLI v. 0.28. It's getting further and generates a repository but there is still a glitch (for which the TypeScript transpiler correctly suggests a fix): 

alain@aegnor:~/devel/strongloop/lb-4-test-2$ lb4 repository
The project has dependencies with incompatible versions required by the CLI:
- @loopback/context: ^0.12.13 (cli ^0.13.0)
- @loopback/repository: ^0.19.0 (cli ^0.20.0)
- @loopback/testlab: ^0.14.1 (cli ^0.15.0)
? Continue to run the command? Yes
? Please select the datasource KeywordsDatasource
? Select the model(s) you want to generate a repository Keyword
   create src/repositories/keyword.repository.ts
   update src/repositories/index.ts

Repository Keyword was created in src/repositories/

alain@aegnor:~/devel/strongloop/lb-4-test-2$ ls -l src/repositories/
total 8
-rw-rw-r-- 1 alain alain  38 oct  3 21:51 index.ts
-rw-rw-r-- 1 alain alain 429 oct  3 21:51 keyword.repository.ts
alain@aegnor:~/devel/strongloop/lb-4-test-2$ npm start

> lb4test2@1.0.0 prestart /media/elrond_2tb/devel/strongloop/lb-4-test-2
> npm run build


> lb4test2@1.0.0 build /media/elrond_2tb/devel/strongloop/lb-4-test-2
> lb-tsc

src/repositories/keyword.repository.ts:13:20 - error TS2552: Cannot find name 'datasource'. Did you mean 'dataSource'?

13     super(Keyword, datasource);
                      ~~~~~~~~~~

  src/repositories/keyword.repository.ts:11:5
    11     @inject('datasources.Keywords') dataSource: KeywordsDataSource,
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'dataSource' is declared here.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! lb4test2@1.0.0 build: `lb-tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the lb4test2@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alain/.npm/_logs/2018-10-03T19_53_00_239Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! lb4test2@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the lb4test2@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alain/.npm/_logs/2018-10-03T19_53_00_287Z-debug.log

Manually changing "datasource" into "dataSource" leads to a successful build and to some run. I don't see the model in the API Explorer but maybe I still have to generate a service (not checked in the documentation yet)

**Comment by koalabi** [comment]
@marioestradarosa 

(Maybe I should make this a new issue - For now, I won't)
When I try to generate a service, I still experience the same problem regarding "no datasources found". When generating a repository, it works (probably just another minor source adaptation overlooked?)

alain@aegnor:\~/devel/strongloop/testlb-4-1$ lb4 -v
@loopback/cli version: 0.28.0

@loopback/* dependencies:
  - @loopback/authentication: ^0.11.18
  - @loopback/boot: ^0.14.4
  - @loopback/build: ^0.7.5
  - @loopback/context: ^0.13.0
  - @loopback/core: ^0.11.15
  - @loopback/metadata: ^0.9.13
  - @loopback/openapi-spec-builder: ^0.9.4
  - @loopback/openapi-v3-types: ^0.9.6
  - @loopback/openapi-v3: ^0.15.3
  - @loopback/repository-json-schema: ^0.11.3
  - @loopback/repository: ^0.20.0
  - @loopback/rest: ^0.25.3
  - @loopback/testlab: ^0.15.0
  - @loopback/docs: ^0.22.1
  - @loopback/example-hello-world: ^0.10.4
  - @loopback/example-log-extension: ^0.11.18
  - @loopback/example-rpc-server: ^0.11.12
  - @loopback/example-todo: ^0.21.0
  - @loopback/example-soap-calculator: ^0.4.4
  - @loopback/dist-util: ^0.3.7
  - @loopback/service-proxy: ^0.8.9
  - @loopback/http-caching-proxy: ^0.3.12
  - @loopback/http-server: ^0.4.4
  - @loopback/example-todo-list: ^0.8.0
alain@aegnor:\~/devel/strongloop/testlb-4-1$ lb4 service
The project has dependencies with incompatible versions required by the CLI:
- @loopback/context: ^0.12.13 (cli ^0.13.0)
- @loopback/repository: ^0.19.0 (cli ^0.20.0)
- @loopback/testlab: ^0.14.1 (cli ^0.15.0)
? Continue to run the command? Yes
? Service name: keywords
Generation is aborted: Error: No datasources found at /media/elrond_2tb/devel/strongloop/testlb-4-1/src/datasources. Please visit https://loopback.io/doc/en/lb4/DataSource-generator.html for information on how datasources are discovered
alain@aegnor:\~/devel/strongloop/testlb-4-1$ 

NB: I still have a warning about some dependencies not OK for \@loopback/cli v. 0.28 (see lines just after "lb4 service"). Tried to resolve it with both rm'ing node_modules and doing a "npm update --save" but to no avail):

**Comment by koalabi** [comment]
Note: in this attempt, there is no hyphen in datasource names:

alain@aegnor:\~/devel/strongloop/testlb-4-1$ lb4 service
? Service name: keywords2
Generation is aborted: Error: No datasources found at /media/elrond_2tb/devel/strongloop/testlb-4-1/src/datasources. Please visit https://loopback.io/doc/en/lb4/DataSource-generator.html for information on how datasources are discovered
alain@aegnor:\~/devel/strongloop/testlb-4-1$ ls -l src/datasources/
total 16
-rw-rw-r-- 1 alain alain  39 oct  3 18:36 index.ts
-rw-rw-r-- 1 alain alain 178 oct  3 18:36 keywords.datasource.json
-rw-rw-r-- 1 alain alain 394 oct  3 18:36 keywords.datasource.ts
-rw-rw-r-- 1 alain alain  80 oct  3 18:17 README.md

**Comment by marioestradarosa** [comment]
> The project has dependencies with incompatible versions required by the CLI:

> @loopback/context: ^0.12.13 (cli ^0.13.0)
@loopback/repository: ^0.19.0 (cli ^0.20.0)

Each version of lb4 CLI comes with new versions in its dependencies. You ran lb4 inside a project generated with a previous version of it , possible < 0.28.0 , that's why you received this warning.  

In our case, as we are just testing, it is better to create a new app using the new lb4 cli version.  If we were in production, then it is just going to be a matter of upgrading the package.json and run `npm install` again.

**Comment by marioestradarosa** [comment]
> ? Service name: keywords2
> Generation is aborted: Error: No datasources found at /media/elrond_2tb/devel/strongloop/testlb-4-1/src/datasources. Please visit https://loopback.io/doc/en/lb4/DataSource-generator.html for information on how datasources are discovered

I don't think it is an error or glitch.  If you check the documentation on `lb4 service` you will see that it requires a datasource linked to either a SOAP or REST only. As you don't have any on your `src/datasources`  it can't find one and is complaining about it.

**Comment by marioestradarosa** [comment]
> I don't see the model in the API Explorer but maybe I still have to generate a service (not checked in the documentation yet)

Currently to generate an application that connects to a Database for CRUD operations you won't need a service. here is usually the steps as you did already:

- lb4 app
- lb4 datasource
- lb4 model 
- lb4 repository
- npm start

and then http://localhost:3000/your-end-points

**Comment by koalabi** [comment]
Note: in this attempt, there is no hyphen in datasource names:

alain@aegnor:\~/devel/strongloop/testlb-4-1$ lb4 service
? Service name: keywords2
Generation is aborted: Error: No datasources found at /media/elrond_2tb/devel/strongloop/testlb-4-1/src/datasources. Please visit https://loopback.io/doc/en/lb4/DataSource-generator.html for information on how datasources are discovered
alain@aegnor:\~/devel/strongloop/testlb-4-1$ ls -l src/datasources/
total 16
-rw-rw-r-- 1 alain alain  39 oct  3 18:36 index.ts
-rw-rw-r-- 1 alain alain 178 oct  3 18:36 keywords.datasource.json
-rw-rw-r-- 1 alain alain 394 oct  3 18:36 keywords.datasource.ts
-rw-rw-r-- 1 alain alain  80 oct  3 18:17 README.md

**Comment by koalabi** [comment]
@marioestradarosa 

A big thanks, Mario. Thank to your "lb4 for dummies" above, I have been able to successfully create an API for "keywords". (I confess: I hadn't read the doc about service and I thought - a bit hastily - that services were required, a bit as in Angular.

My next exploration step (as announced earlier) before tacking a more concrete project is to try GraphQL but I have the impression there are several GraphQL initiatives running, maybe not all lb4-compatible. Is there any reliable information available?

Thanks in advance.

**Comment by marioestradarosa** [comment]
@koalabi,

There is currently for **GraphQL** the amazing library OASGraph
 https://github.com/strongloop/oasgraph

I also created a small video here https://youtu.be/s2hScucNmaA

**Comment by koalabi** [comment]
@marioestradarosa 
(I'm digressing here)
Hi Mario, thanks for the link to your fine video. I have followed the detailed instructions but I get a runtime exception (probably at the OASGraph level): 
AssertionError: Schema object cannot have additionalProperty: patternProperties

Strange is that the additional property (patternProperties) does not come from the code you showed. Any idea? (Apparently no such open issue on the OASGraph side)

**Comment by marioestradarosa** [comment]
@koalabi , please open an issue so we can help others 😄 .

**Comment by koalabi** [comment]
@marioestradarosa 

No problem but do I do it here or in strongloop/oasgraph?

**Comment by marioestradarosa** [comment]
here is fine 👍

**Comment by marioestradarosa** [comment]
Ahhh, probably your code was out-of-date. The ping controller was not sending the correct OAS spec object, until the current version of the CLI tool 0.28.0.

**Comment by koalabi** [comment]
OK, I'll investigate this path and let you know. Thanks.

**Comment by koalabi** [comment]
@marioestradarosa 
Right on target! Fine, Mario : I generated a new app, compared to 2 ping.controllers and just backported the modification into my code and, bingo!, it is now working.
Thanks!

**Comment by nnbosko** [comment]
I'm having this issue after having created a REST API datasource. No matter what name I give the thing, the CLI program fails to detect it on attempting to create a repository.

**Comment by raymondfeng** [comment]
@nnbosko That's by design of LB4. Datasources backed by services such as REST and SOAP are now only available for `lb4 service` instead of `lb4 repository`.

**Comment by lavenpillay** [comment]
> @nnbosko That's by design of LB4. Datasources backed by services such as REST and SOAP are now only available for `lb4 service` instead of `lb4 repository`.

For anyone still having this issue, even after upgrading, this may be of use to you.
In my case I don't actually need the datasource, so by creating a dummy one with either REST or SOAP type, i was then able to successfully use `lb4 service`
