### ISSUE TITLE
Missing doc about form-data parameters in controller

### ISSUE THREAD

**Issue by JesusTheHun** [strongloop/loopback-next#1797]
In the documentation about route parameters ( https://loopback.io/doc/en/lb4/Routes.html#parameters ) it is mentioned "form Data". However, no where we can see a use of it. And right now, I'm unable to catch any submitted data from the form.

In my case, in the sequence, the call of `this.parseParams(request, route)` return an array of undefined values. So obviously I'm missing something, and document it would be great !

Exemple : 

```typescript
export class RegistrationController {

  // stuff 

  @post('/register', {
    responses: {
      '200': {
        description: 'Registration information page',
        content: {'text/html': {schema: {type: 'string'}}},
      },
    },
  })
  create(
    @param.query.string('email') email: string,
    @param.query.string('password') password: string,
  ): Promise<string> {
    // email & password are empty
  }
}
```

**Comment by JesusTheHun** [comment]
Hi @marioestradarosa , have you been able to perform some tests ?

**Comment by raymondfeng** [comment]
You probably should use `@requestBody` to decorate the body parameter and use `body.email` and `body.password`. Something like:

```ts
create(@requestBody({
    content: {
      'application/x-www-form-urlencoded': {
        schema: {
          type: 'object',
          properties: {
            email: {
              description: 'email',
              type: 'string',
            },
            password: {
              description: 'password',
              type: 'string',
            },
          },
        },
      },
    },
  })
  body: {
    email: string;
    password: string;
  }) {
    console.log(body.email);
    return 'good';
  }
```

**Comment by dhmlau** [comment]
Moving it to `In Progress` because of PR #1838.

**Comment by dhmlau** [comment]
Closing as done, because PR #1838 has landed.
