### ISSUE TITLE
Express/Koa compatibility

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#180]
# Description/Steps to reproduce

LoopBack.next is built with Node core `http`/`https` modules. To leverage the ecosystem around Express/Koa, we need to have a compatibility story to cover the following perspectives:

1. API level (req/res/app/...)
2. Middleware

# Expected result

# Additional information

See https://github.com/strongloop/loopback-next/issues/11

**Comment by bajtos** [comment]
@kjdelisle - PTAL - this is relevant to our discussion about Koa/Express/Micro/Fastify support we had yesterday. I think @virkt25 may be interested too.

**Comment by dhmlau** [comment]
Looks like this is covered by #1255  (spike) and the other tasks (#1290, #1291, #1292, #1293).  Good to close? 

cc @raymondfeng @hacksparrow

**Comment by dhmlau** [comment]
Closing in favor of #1255.
