### ISSUE TITLE
Update LTS status of old loopback packages

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1802]
Once LoopBack 4.0 GA is released (https://github.com/strongloop/loopback-next/issues/1744), we need to move LoopBack 3.x packages into Active LTS mode:

 - Keep the latest version line in `master`, but mark it as "Active LTS". There will be no "Current" release line going forward. No new feature will be accepted, only bug fixes are allowed.

- The current Active LTS moves to Maintenance LTS, the version in Maintance LTS drops out of LTS.

- Add a short paragraph to README, explain why there is no Current version line and point users to LoopBack v4. Publish a new version to npmjs.org.

Packages to update:
  - [x] strong-remoting - https://github.com/strongloop/strong-remoting/pull/456
  - [x] loopback - made it more clear that no new features are accepted - https://github.com/strongloop/loopback/pull/4029
  - [x] loopback-component-explorer - https://github.com/strongloop/loopback-component-explorer/pull/251
  - [x] loopback-swagger - https://github.com/strongloop/loopback-swagger/pull/133
  - [x] loopback-boot - https://github.com/strongloop/loopback-boot/pull/284
  - [x] loopback-cli - https://github.com/strongloop/loopback-cli/pull/78
  - [x] generator-loopback - https://github.com/strongloop/generator-loopback/pull/398
  - [x] loopback-workspace - https://github.com/strongloop/loopback-workspace/pull/537
  - [x] loopback-context - https://github.com/strongloop/loopback-context/pull/40
  - [x] loopback-phase - https://github.com/strongloop/loopback-phase/pull/28
  - [x] loopback-sdk-angular - https://github.com/strongloop/loopback-sdk-angular/pull/291
  - [x] loopback-sdk-angular-cli - https://github.com/strongloop/loopback-sdk-angular-cli/pull/79
  - [x] grunt-loopback-sdk-angular - https://github.com/strongloop/grunt-loopback-sdk-angular/pull/37
  - [x] gulp-loopback-sdk-angular - https://github.com/strongloop/gulp-loopback-sdk-angular/pull/21

**Comment by jannyHou** [comment]
Closing since all PRs merged.
