### ISSUE TITLE
Add home page for examples

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#1806]
## Description / Steps to reproduce / Feature proposal

From #1798, we have identified that having a landing page for our example applications just like the ones introduced in #1763 for default home page makes UX simpler for our users. 

## Current Behavior

Users will see a 404 not found when visiting the root `/` page of the example applications e.g. `http://localhost:3000/`.

## Expected Behavior

A home page, just like the one that comes with `lb4 app`, should be displayed by default when users visit the root page of the examples (todo, todo-list, etc.).

## Acceptance Criteria
- [ ] Add a home page controller and html file (under `/public` directory) to existing examples
    - ~~hello-world~~
    - ~~log-extension~~
    - ~~rpc-server~~
    - [ ] soap-calculator
    - [ ] todo-list
    - [ ] todo
- [ ] Add applicable acceptance, integration, unit tests, docs

**Comment by marioestradarosa** [comment]
IMO hello-world, log-extension and rpc-server should be removed from the list. I am almost ready with this PR and hello-world doesn not implement BootMixin for a start, secondly the / is already taken by the hello world message.

**Comment by b-admike** [comment]
@marioestradarosa Thank you for taking this on and crossing those examples off the list (I just listed them without investigating if these changes are applicable)!
