### ISSUE TITLE
openapi-spec: support the upcoming 3.0 flavour of OpenAPI Spec

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#182]
This is a follow-up issue for #177, it may be a duplicate of #753

**Comment by bajtos** [comment]
Quoting from https://www.openapis.org/blog/2017/05/25/the-open-api-initiative-is-sending-you-a-save-the-date-card:

> At its meeting on Friday, 19 May, the Technical Developer Community (TDC) agreed to target the below timeline for release:
> - 4 weeks from 22 May through 16 June: Resolve remaining pull requests
> - 2 weeks from 19 June through 30 June: Comment period
> - 2 weeks from 3 July through 14 July: Resolve remaining comments and issues
> - 1 week from 17 July through 21 July: TENTATIVE release window

**Comment by dhmlau** [comment]
Talked to @jannyHou , seems like this could be a duplicate of https://github.com/strongloop/loopback-next/issues/753, since we're gonna support openapi3.  
Closing as dup. 
@kjdelisle @raymondfeng , if you don't agree, please reopen.  Thanks.

**Comment by bajtos** [comment]
According to https://github.com/strongloop/loopback-next/issues/696, migration to OpenAPI Spec v3 is out of scope of the MVP release. Let's keep this issue open until we actually have v3 support implemented.

**Comment by dhmlau** [comment]
Closing as it's been resolved.
