### ISSUE TITLE
Support for Firebird connector

### ISSUE THREAD

**Issue by lorenszendre** [strongloop/loopback-next#1841]
_Originally posted by @ritch in https://github.com/strongloop/loopback-next/issues/512#issuecomment-323114540_

Please add official support for Firebird. The firebird connector hasn't been updated for 3 years. There are millions of Firebird databases in use today. That is enough to justify official support.

**Comment by dhmlau** [comment]
@lorenszendre , thanks for your feedback!  I just modified the title to be more descriptive. 
Just want to let you know that this connector is maintained by the LoopBack community.

**Comment by AcacioDasChagas** [comment]
Has someone used Loopback 4 with the Firebird database? I used this database with Loopback 3, but I can't find a connector for the current version.
