### ISSUE TITLE
Migrate wiki content to loopback.io

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#185]
- [x] Migrate contents at https://github.com/strongloop/loopback-next/wiki/ to loopback.io
- [x] Edit and reformat as necessary
- [x] Replace wiki content with links to loopback.io.

**Comment by superkhau** [comment]
Won't migrate wiki content until beta is out (after all current sections in wiki have been updated with enough content).

**Comment by dhmlau** [comment]
Since this is for the beta, I'm marking this as `LoopBackNext-beta`.

**Comment by bajtos** [comment]
We need to wait for more days until the work on chit-chat app by @kjdelisle is done. Then we should move the content ASAP.

**Comment by crandmck** [comment]
OK, but still next sprint?

**Comment by dhmlau** [comment]
@crandmck , is this work completed already?

**Comment by crandmck** [comment]
Yes, sorry I should have updated.  I guess we can skip the normal steps and go straight to "review"...?
