### ISSUE TITLE
Enable eslint for CLI package

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1851]
The package [packages/cli](https://github.com/strongloop/loopback-next/tree/master/packages/cli) is the only package written in JavaScript and because it's an exception in our TypeScript-based project, it's not covered by any linter. As a result, this part of our codebase may contain silly bugs that could have been caught by a linter.

I am proposing to start running `eslint` for `packages/cli`.

Alternatively, we can rewrite `@loopback/cli` into TypeScript, but that would be a larger task IMO.

## Acceptance criteria

- [ ] `npm run lint` executes `eslint` for `packages/cli`
- [ ] `npm run lint:fix` executes `eslint --fix`
- [ ] eslint is configured using [eslint-config-loopback](https://www.npmjs.com/package/eslint-config-loopback) with custom configuration to disable eslint rules clashing with our Prettier formatting.
- [ ] all linting errors are fixed - this should be a standalone commit in the pull request.

**Comment by raymondfeng** [comment]
1. +1 to use eslint as the short-term improvement.

2. Converting the package into TypeScript might not be too complicated as we have used ES6 classes for most of the code.

**Comment by bajtos** [comment]
>  eslint is configured using eslint-config-loopback with custom configuration to disable eslint rules clashing with our Prettier formatting.

We can use [eslint-plugin-prettier](https://www.npmjs.com/package/eslint-plugin-prettier) or [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier) to help with that.

**Comment by bajtos** [comment]
Let's wait until https://github.com/strongloop/loopback-next/issues/2608 is done.

**Comment by dhmlau** [comment]
Closing it as done.
