### ISSUE TITLE
How to report bugs and create reproducible example app

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1854]
Our current documentation on [Reporting issues](https://loopback.io/doc/en/contrib/Reporting-issues.html) is describing the process for LoopBack 3.x projects and telling people to fork [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) repo on GitHub. This advice does not work for loopback-next.

We should decide what kind of reproduction examples we would like to receive from our users and describe it in documentation.

We need to update the current [doc-contrib](https://loopback.io/doc/en/contrib/doc-contrib.html) content to make it clear which instructions are applying to LB 3.x and where to find instructions for LB 4.x. The [CONTRIBUTING](https://github.com/strongloop/loopback-next/blob/a2ab86d3a3c721f28159585ca4e87bd8504476c4/docs/CONTRIBUTING.md) guide in this monorepo needs to be updated too.

Related tasks:
- Update the contribution page for Loopback 3 #1673
- Update ways to contribute to LoopBack #1228

**Comment by b-admike** [comment]
Excluding the following point from estimation because it's covered in #1673:
>We need to update the current doc-contrib content to make it clear which instructions are applying to LB 3.x and where to find instructions for LB 4.x. The CONTRIBUTING guide in this monorepo needs to be updated too.

**Comment by bajtos** [comment]
Closing as done via strongloop/loopback.io#785
