### ISSUE TITLE
[CLI] Create app using --config options need all options to be in the config.json

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1855]
## Description / Steps to reproduce / Feature proposal
If I would like to create an LB4 app using `lb4 app` using `--config` option without any additional prompts in the command line, I need to have the following config.json:

```
{
    "name": "test-1015",
    "description": "testing",
    "outdir": "test-1015",
    "applicationName": "Test1015Application",
    "repositories": true,
    "services": true,
    "tslint": true,
    "prettier": true,
    "mocha": true,
    "loopbackBuild": true,
    "vscode": true,
    "private": false
}
```

## Current Behavior
For any attribute that exists in the prompts but not in the config file, the user is asked in the command line. 

## Expected Behavior
I should be able to provide only the compulsory attributes (e.g. project name). 
For example, the following (or even smaller subset) should be enough to create an app using `lb4 app --config config.json`

```
{
    "name": "test-1015",
    "description": "testing",
    "applicationName": "Test1013Application",
    "outdir": "test-1015",
    "repositories": true,
    "services": true,
}
```

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
Please use `--yes` to skip optional prompts.
