### ISSUE TITLE
TypeScript type of ISharedSchema.format is too strict.

### ISSUE THREAD

**Issue by UselessPickles** [strongloop/loopback-next#1858]
## Description / Steps to reproduce / Feature proposal

The type of ISharedSchema.format should be of type "FormatType | string" instead of simply "FormatType" to comply with the OpenAPI specification. Here is a relevant excerpt about the "format" property:

> However, the format property is an open string-valued property, and can have any value to support documentation needs. Formats such as "email", "uuid", etc., can be used even though they are not defined by this specification.

See the "Data Types" section here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

## Current Behavior

ISharedSchema.format does not allow arbitrary string values.

## Expected Behavior

ISharedSchema.format should allow arbitrary string values. Note that it is still useful to define the string literal union type of defined values because it allows IDEs to provide auto-completion/suggestions of defined values. Therefor a type of "FormatType | string" is more useful than simply "string".

**Comment by raymondfeng** [comment]
We use OpenAPI 3.0.x. Let's refer to https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types

**Comment by raymondfeng** [comment]
@UselessPickles Where did you find ISharedSchema? We use https://github.com/metadevpro/openapi3-ts/blob/master/src/model/OpenApi.ts#L271. The `format` is an optional string.

**Comment by UselessPickles** [comment]
Maybe I reported this to the wrong project? Is this the project that is published on npm as "openapi-spec-builder"

**Comment by UselessPickles** [comment]
I got here by following the repository:github link from npm: https://www.npmjs.com/package/@loopback/openapi-spec-builder

I have "openapi-spec-builder" version 3.0.0 installed.

```ts
import ISchema from "openapi-spec-builder/lib/v2/Strict/ISchema";
```

**Comment by raymondfeng** [comment]
Do you refer to https://github.com/strongloop/loopback-next/blob/master/packages/openapi-spec-builder/src/openapi-spec-builder.ts? The npm module is `@loopback/openapi-spec-builder`.

**Comment by raymondfeng** [comment]
No problem.
