### ISSUE TITLE
How to use regular expressions in route path and how to make parameters optional

### ISSUE THREAD

**Issue by hbakhtiyor** [strongloop/loopback-next#1866]
* how to use regular expression in route path?

for example like expressjs
```
app.get('/assets/:uuid([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})', function (req, res) {
}) 
```

* how to make route param is optional?

for example

`/assets/eed761cf-5418-53d3-9f67-c279f58ac875.png`
`/assets/eed761cf-5418-53d3-9f67-c279f58ac875`, `.format` is optional

```
import { get, param } from '@loopback/rest';

export class AssetController {
  @get('/assets/{uuid}.{format}')
  assets(@param.path.string('uuid') uuid: string,
             @param.path.string('format') format?: string): object {
      return {};
  }
}
```

**Comment by hbakhtiyor** [comment]
cc @raymondfeng

**Comment by hacksparrow** [comment]
@hbakhtiyor LB4 uses Express' [serve-static](https://www.npmjs.com/package/serve-static) middleware for serving static files, you can see how to see regular expression and other patterns for a path at http://expressjs.com/en/4x/api.html#path-examples.

**Comment by hbakhtiyor** [comment]
i can't use like this in lb4, which valid in expressjs

```
@get('/assets/{uuid}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})')
```

**Comment by hacksparrow** [comment]
At the moment, static files can be served from a single mount point only. We don't have a controller interface yet. Having said that, you LB4 provides an Express-like method (`app.static()`) for setting up statics assets, here is an example:

```
  const app = new Lb4appApplication(options);

  const publicDir = path.join(__dirname, 'public');

  await app.boot();
  await app.start();

  app.static(/\/abc|\/xyz/, publicDir); // <-- regex path

  const url = app.restServer.url;
  console.log(`Server is running at ${url}`);
  console.log(`Try ${url}/ping`);

  return app;
```

**Comment by hbakhtiyor** [comment]
i don't need exactly for static serve, not related to my questions

**Comment by hacksparrow** [comment]
LB4 does not support regex based paths.

@bajtos @raymondfeng @strongloop/sq-lb-apex how about supporting regex-based paths?

**Comment by marioestradarosa** [comment]
> how to use regular expression in route path?

Is this  is to evaluate a regular expression against the uuid path parameter ?  
something like this?

```ts
if  (/^[0-9a-fA-F]{24}$/.test(uuidParamter)) {
} else { //error, not evaluated }
```

**Comment by hbakhtiyor** [comment]
yeah, want to add this in `@get` decorator like express route

**Comment by raymondfeng** [comment]
@hbakhtiyor We intentionally disabled the regular expression/wildcard support in paths to be compatible with OpenAPI and swagger-ui. See some discussions at https://github.com/strongloop/loopback-next/pull/1765.

OpenAPI spec is very vague about path templating - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#path-templating. See more information at:

- https://github.com/OAI/OpenAPI-Specification/issues/892
- https://github.com/OAI/OpenAPI-Specification/issues/1459

We can reevaluate the issue once the spec has a clear direction.

**Comment by bajtos** [comment]
+1 to what @raymondfeng wrote above.

> ```ts
> app.get(
>    '/assets/:uuid([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})', 
>    function (req, res) {
>   }
> );
> ``` 

My recommendation: Move the regular expression from the path definition into an OpenAPI spec parameter constraint.

```ts
    this.route(
      'get',
      '/asserts/:uuid',
      {
        parameters: [
          {
            name: 'uuid',
            in: 'path',
            schema: {
              type: 'string',
              pattern:
                '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
            },
          },
        ],
        responses: {
          /*...*/
        },
      },
      function(uuid: string) {
        // serve the asset
      },
    );
```

Please note that LB4 does not validate non-body parameters (e.g. path parameters yet) - see https://github.com/strongloop/loopback-next/issues/1573. (Implementing these validation should be pretty easy, would you like to contribute it yourself? Let's discuss in #1573).

**Comment by bajtos** [comment]
> how to make route param is optional?
>
> ```ts
> export class AssetController {
>   @get('/assets/{uuid}.{format}')
>   assets(@param.path.string('uuid') uuid: string,
>              @param.path.string('format') format?: string): object {
>       return {};
>   }
> }
> ```

Please note that in OpenAPI, path parameters are always required and all other parameters are optional by default. See OpenAPI's section [Parameter Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#parameter-object).

Field Name | Type | Description
-- | -- | --
required | `boolean` | Determines whether this parameter is mandatory. If the parameter location is "path", this property is **REQUIRED** and its value MUST be `true`. Otherwise, the property MAY be included and its default value is `false`.

As a result, it is not possible to have an optional path parameter in LB4, you have to move such parameter e.g. to a query string.

---

Ideally, I would like LB4 to provide the following syntax for annotating parameters as required:

```ts
@param.query.string('format', {required: true}) format?: string
```

For now, you have to use `@param()` directly (but don't have to specify the type since LB4 can infer the type from TypeScript metadata):

```ts
@param(name: 'format', in: 'query', required: true}) format?: string
```

**Comment by bajtos** [comment]
@hbakhtiyor did we answer your questions?

@raymondfeng @hacksparrow @dhmlau  I think we should capture these Q&A in our docs. What do you think?

**Comment by hacksparrow** [comment]
Agreed. He won't be the first and the last to come up with this requirement.

**Comment by hbakhtiyor** [comment]
@bajtos, partially, yeah

currently going with the snippet, also can't put `.` in the lb4 route, throw an error

```ts
  @get('/assets/{params}')
  async assets(
    @param.path.string('params') params: string
  ): Promise<object> {
    const routeAssetsMatches = /^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:\.(jpeg|jpg|png))?$/i.exec(params);
    if (!routeAssetsMatches || !routeAssetsMatches[1]) {
      throw new HttpErrors.UnprocessableEntity('the format of route is invalid');
    }

    const uuid = routeAssetsMatches[1];
    const format = routeAssetsMatches[2] || 'jpeg';
  }

```

**Comment by hbakhtiyor** [comment]
> Could you please post a code snippet showing what are you trying to do?

@bajtos , e.g
```ts
  @get('/assets/{uuid}.{format}')
  async assets(
    @param.path.string('uuid') uuid: string,
    @param.path.string('format') format: string
  ): Promise<object> {
  }
```

**Comment by bajtos** [comment]
@hbakhtiyor Interesting! I tried your example path in Swagger Editor (http://editor.swagger.io) and it looks like your example is a valid OpenAPI spec path template.

The spec:

```yaml
/pet/{petId}.{format}:
    get:
      # ...
```

The request made by the editor (petId = 1, format = json):

```sh
curl -X GET "https://petstore.swagger.io/v2/pet/1.json" -H "accept: application/xml"
```


Please open a new GitHub issue to discuss how LoopBack can add support for this use case.

**Comment by raymondfeng** [comment]
I thought it was supported by design. Let me check.

**Comment by bajtos** [comment]
@hbakhtiyor  the issue with `/assets/{uuid}.{format}` should be fixed now. Could you please update your dependencies to latest version and let us know if the problem went away?

**Comment by raymondfeng** [comment]
> works well, but .{format} is still not making optional

Why do you expect `.{format}` to be optional? The pattern says it expects the `format` comes after a `.`.
