### ISSUE TITLE
Outdated announcement on LB4 home page

### ISSUE THREAD

**Issue by larsm11** [strongloop/loopback-next#1870]
The below announcement is still showing on the [LB4 home page](https://loopback.io/doc/en/lb4/index.html), I wonder if that isn't a mistake.

_**"Important: LoopBack 4 is the next step in the evolution of LoopBack. It is still in early development and is not yet released"**_

**Comment by dhmlau** [comment]
@larsm11 , thanks for bringing to our attention.  It's fixed in [this PR](https://github.com/strongloop/loopback-next/pull/1859) and we need to get it refreshed on loopback.io.

**Comment by dhmlau** [comment]
Closing as resolved. Thanks for reporting this issue.
