### ISSUE TITLE
New LoopBack introduction image/logo

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#189]
# Depends on

- [x] Confirm with OM to make sure it is ok to have a replacement logo @ritch
  - If not, we still want a fresh image using the old logo, update @sichao once more is fleshed out

---

- [ ] Check with @sichao/@ritch to see logo is done
  - ~05/15
- [ ] Figure out a place to store the logo (most likely `docs/img` in LBn repo)
- [ ] Update first section of README with logo
- [ ] Update Overview page of wiki with logo

Related Issues:
https://github.com/strongloop/loopback.io/issues/429
https://github.com/strongloop/loopback.io/issues/430
https://github.com/strongloop/loopback.io/issues/431
https://github.com/strongloop/loopback.io/issues/432

**Comment by dhmlau** [comment]
Confirmed with Savio that he's ok with the logo change.
@ritch @sichao, what should be the next step?

**Comment by dhmlau** [comment]
Marking as `Core-GA` for now.

**Comment by raymondfeng** [comment]
Try http://brandmark.io/

**Comment by bschrammIBM** [comment]
Please see the following issues opened by Rand:
https://github.com/strongloop/loopback.io/issues/429
https://github.com/strongloop/loopback.io/issues/431

**Comment by bajtos** [comment]
@dhmlau who is driving the effort for getting a new logo? I assigned the issue to you, feel free to re-assign.

**Comment by dhmlau** [comment]
sure @bajtos.

Recap of our current status:
- we've engaged the designer team (Cody and Sichao) for rebranding. 
- *logo*: there's a voting survey going on: https://strongloop.com/strongblog/new-loopBack-logo/
  - survey will probably close soon - need to confirm with Dave W
  - once that's done, the new logo can be used to incorporate into the new web site design
-  *web site*: 
   - @virkt25 was working with Cody on the content to be put in the new site.  and it's been reviewed by the team.  @bschrammIBM has also reviewed.
   - next step is to get the logo and palette finalized (from the vote), then Cody will give us the blueprint of the site.

**Comment by dhmlau** [comment]
Logo and web site design is ready.  Closing this issue in favor of https://github.com/strongloop/loopback-next/issues/817.
