### ISSUE TITLE
Spike: Use express constructs / enable express shimming for Authentication

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#191]
- [ ] Use of passport-strategy's with dependence on Express request, response constructs
    Confirm:
    - [ ] `request.session`
    - [ ] `response.json`
    - [ ] `response.send`
    - [ ] `response.type`
- [ ] Shim/inject express dependencies without using express request/response/middleware

**Comment by superkhau** [comment]
@deepakrkris I'm guessing this is already done as part of your work on the Auth package impl. Safe to close?

**Comment by bajtos** [comment]
This may be required for #230 and/or #160.

**Comment by bajtos** [comment]
We need to revisit the goal of this story, considering that we are going to use Express REquest/Response types internally soon.
