### ISSUE TITLE
BelongsTo property with find

### ISSUE THREAD

**Issue by kawasaki23Ven** [strongloop/loopback-next#1929]
Hi, I need a example to get the Model with Relation BelongsTo in controller.

The example in the documentation dont work with find

**Comment by raymondfeng** [comment]
The `find` operation does not apply to `belongsTo`. For example, an order belongs to a customer, from the order perspective, you only need to know the owner.

What's your use case of `find` for belongsTo?

**Comment by kawasaki23Ven** [comment]
> The `find` operation does not apply to `belongsTo`. For example, an order belongs to a customer, from the order perspective, you only need to know the owner.
> 
> What's your use case of `find` for belongsTo?

Hello, I've got two models, one Customer and an order, I need to respond with a Json that contains the order name and id of the order, but that includes the Customer's name and Id in a custom Json.

I need to know how exactly can I create that specific query if I've got both models related throught a "belongsTo" relation.

I'm using this property in the order model to connect them:
  @belongsTo(() => customer, {keyTo: 'id'})
  customer_id: number;
The response I'd llike to obtain is the following:

{name: "order1",
id: 2
customer: {
name: "Pablo",
id: 1
}
}

Thank you very much in advance.

**Comment by Dallsant** [comment]
+1

**Comment by elpollo12** [comment]
+1

**Comment by jannyHou** [comment]
Maybe try `OrderRepository.find({where: {id: 2}, include: ['customer']})`.

**Comment by kawasaki23Ven** [comment]
Hi, I get this error :
Argument of type '{ include: string[]; }' is not assignable to parameter of type 'Filter<Order>'.

**Comment by raymondfeng** [comment]
@jannyHou `include` has not been implemented in LB4.

**Comment by bajtos** [comment]
Thank you @kawasaki23Ven for describing this use case to us. As I see it, the requested feature is already covered by the following issue: Include related models in "GET /mymodels" results #1889.

I am closing this one as a duplicate.
