### ISSUE TITLE
Openapi omitting schema from responses

### ISSUE THREAD

**Issue by dougal83** [strongloop/loopback-next#1933]
# Description

openapi.json seems to be omitting schema from responses (
[openapi.bug.txt](https://github.com/strongloop/loopback-next/files/2522175/openapi.bug.txt)).  I noticed the issue running through tutorial: https://loopback.io/doc/en/lb4/exposing-graphql-apis.html.  Due to the missing schema Oasgraph give warnings such as:

{
      "type": "MissingResponseSchema",
      "message": "Operation 'GET /todos/{id}' has no (valid) response schema.",
      "mitigation": "Ignore operation"
    },

## Current Behavior

Example:
...
 "/todos/{id}": {
...
 "get": {
...
        "responses": {
          "200": {
            "description": "Todo model instance",
            "content": {
              "application/json": {}
            }
          }
        }
...

## Expected Behavior

Example:
...
 "/todos/{id}": {
...
 "get": {
...
        "responses": {
          "200": {
            "description": "Todo model instance",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todo"
                }
              }
            }
          }
        }
...

## Other info:
@loopback/cli 1.0.2
Node: v10.9.0
Win 10

"dependencies": {
    "@loopback/boot": "^1.0.2",
    "@loopback/context": "^1.0.0",
    "@loopback/core": "^1.0.0",
    "@loopback/openapi-v3": "^1.0.2",
    "@loopback/openapi-v3-types": "^1.0.0",
    "@loopback/repository": "^1.0.2",
    "@loopback/rest": "^1.1.0",
    "@loopback/service-proxy": "^1.0.0",
    "express": "^4.16.4",
    "express-graphql": "^0.6.12",
    "loopback-connector-rest": "^3.1.1",
    "oasgraph": "^0.10.1"
  },

## Semi related:
#https://github.com/strongloop/oasgraph/issues/57

**Comment by hacksparrow** [comment]
Thanks for reporting @dougal83. I am taking a look at it.
