### ISSUE TITLE
Connection fails: ConnectionError: Server requires encryption, set 'encrypt' config option to true.

### ISSUE THREAD

**Issue by mdovoh** [strongloop/loopback-next#1934]
Connection fails: ConnectionError: Server requires encryption, set 'encrypt' config option to true.
It will be retried for the next request.
Unhandled error in POST /users: 500 ConnectionError: Server requires encryption, set 'encrypt' config option to true.
    at Connection.tedious.once.err (C:\Users\micha\Desktop\PHP\restapi\node_modules\mssql\lib\tedious.js:237:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.processPreLoginResponse (C:\Users\micha\Desktop\PHP\restapi\node_modules\tedious\lib\connection.js:1098:16)

**Comment by mdovoh** [comment]
"options": { " encrypt":true} is set

**Comment by raymondfeng** [comment]
Is it for ms sql server?

**Comment by mdovoh** [comment]
Yes on Azure

**Comment by dhmlau** [comment]
Looking through similar issues, I found this: https://github.com/adonisjs/adonis-lucid/issues/271#issuecomment-354182660.
Having the settings below (in your DataSource) might work: 
```
options: {
        encrypt: Env.get('DB_ENCRYPT', true)   // use this for Azure database encryption
      }
```

**Comment by mdovoh** [comment]
my datasourse format is json so how do i add options: {
        encrypt: Env.get('DB_ENCRYPT', true)   // use this for Azure database encryption
      } to the json file?
```
{
  "name": "db",
  "connector": "mssql",
  "url": "mssql://name:pass@*************/db",
  "host": "*************************",
  "port": 8080,
  "user": "************",
  "password": "********",
  "database": "db",
   "options": {  
   "encrypt": "Env.get('DB_ENCRYPT', true)"    
 } 
}
```

**Comment by raymondfeng** [comment]
You have to set up `encrypt` in the corresponding TS file

**Comment by mdovoh** [comment]
This is my datasource json
`{
  "name": "smscore",
  "connector": "mssql",
  "url": "************",
  "host": "************",
  "port": 1433,
  "user": "***********",
  "password": "********",
  "database": "smscore",
   "options": {  
   "encrypt":  "true",    
 } 
}`


**This is my TS code**
`import {inject} from '@loopback/core';
import {juggler} from '@loopback/repository';
import * as config from './smscore.datasource.json';

export class SmscoreDataSource extends juggler.DataSource {
  static dataSourceName = 'smscore';

  constructor(
    @inject('datasources.config.smscore', {optional: true})
    dsConfig: object = config,
  ) {
    super(dsConfig);
  }
}
`

**Comment by raymondfeng** [comment]
What about the following config?
```json
{ "name": "smscore", "connector": "mssql", "url": "************", "host": "************", "port": 1433, "user": "***********", "password": "********", "database": "smscore",  "encrypt": "true"  }
```

**Comment by jonrcrowell** [comment]
This worked for me but the encrypt setting needs to be a boolean and not a string. (I removed the quotes around "true".)

{ "name": "smscore", 
"connector": "mssql", 
"url": "************", 
"host": "************", 
"port": 1433, 
"user": "***********", 
"password": "********", 
"database": "smscore",  
"encrypt": true  }
