### ISSUE TITLE
Unit test a controller with stub repository

### ISSUE THREAD

**Issue by israelglar** [strongloop/loopback-next#1935]
### Description / Steps to reproduce
I'm following the documentation here https://loopback.io/doc/en/lb4/Testing-your-application.html#unit-test-your-controllers

I have a ProfileController that needs the repository: ProfileRepository.

```ts
describe('Profile.controller (unit)', () => {
  let profileRepository: ProfileRepository;
  let findProfile: sinon.SinonStub;
  let findByIdProfile: sinon.SinonStub;

  beforeEach(givenStubbedRepository);

  describe('create', async () => {
    it('', async () => {
      const controller = new ProfileController(
        profileRepository,
      );
      givenNoProfiles();
    });
  });

  function givenStubbedRepository() {
    profileRepository = sinon.createStubInstance(ProfileRepository);
    findProfile = profileRepository.find as sinon.SinonStub;
    findByIdProfile = profileRepository.findById as sinon.SinonStub;
  }

  function givenNoProfiles() {
    findProfile.resolves([]);
    findByIdProfile.resolves({statusCode: 404});
  }
});
```
I can't instantiate `controller` because it's expecting a repository with type `ProfileRepository` but the stub type is `SinonStubbedInstance<ProfileRepository>`.

I'm doing the same thing that is on the documentation, but can't get it to work. Am I doing something wrong?

Thanks

**Comment by bajtos** [comment]
@israelglar Thank you for opening this issue. The problem you are describing is something I have run into myself too. I solved it by adding a new helper to our `testlab`, it's called `createStubInstance` and you can see it in action for example in [examples/todo/test/unit/controllers/todo.controller.unit.ts](https://github.com/strongloop/loopback-next/blob/4bf0c89ec65ee823bb4526561722276b74bef880/examples/todo/test/unit/controllers/todo.controller.unit.ts)

```ts
import {createStubInstance, expect, StubbedInstanceWithSinonAccessor} from '@loopback/testlab';
// ...

let profileRepository: StubbedInstanceWithSinonAccessor<ProfileRepository>;
// ...

function givenStubbedRepository() {
  profileRepository = createStubInstance(ProfileRepository);
  ({findProfile, findByIdProfile}) = profileRepository.stubs;
}
```

With the new helper, you don't even need `findProfile` and `findByIdProfile` variables, you can use `profileRepository.stubs.findProfile` directly with no explicit typecasts needed.

Would you mind fixing the code example in [Unit test your controllers](https://loopback.io/doc/en/lb4/Testing-your-application.html#unit-test-your-controllers
) yourself and contributing the fix as a pull request? Here is the file to change: [docs/site/Testing-your-application.md](https://github.com/strongloop/loopback-next/blob/master/docs/site/Testing-your-application.md) and our [CONTRIBUTING guide](https://github.com/strongloop/loopback-next/blob/master/docs/CONTRIBUTING.md) to get you started.
