### ISSUE TITLE
Add ability to turn off the REST API when using GraphQL

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#1945]
## Description / Steps to reproduce / Feature proposal
Since LB4 provides a GraphQL interface to the API using OASGraph, we should have the ability to turn off the REST API, if needed.

## Current Behavior

When using OASGraph, LB4 exposes both REST API and GraphQL API.

## Expected Behavior

When using OASGraph, one should be able to turn off the REST API.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by marioestradarosa** [comment]
> When using OASGraph, one should be able to turn off the REST API.

How this should work?.  The **OASGraph** is just a library that is used as input for `graphql-server` _(translating the OpenAPI schema into graphQL schema automatically)_ . It is the `graphql-server` that translates the **GraphQL** queries and contact the REST API to resolve the request, hence the server: url in the `index.js` .  So _turning off_ the REST API will prevent this resolution to work, or probably I am missing something.
