### ISSUE TITLE
New Logo is not good

### ISSUE THREAD

**Issue by abductedMind** [strongloop/loopback-next#1946]
## Description / Steps to reproduce / Feature proposal
Look at logo small.

## Current Behavior
Logo is hard to read / busy.

## Expected Behavior
A good logo for the future of Loopback. Go Loopback!

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by hacksparrow** [comment]
@abductedMind can you post a screenshot of what you are referring to and in which context?

**Comment by abductedMind** [comment]
<img width="322" alt="screen shot 2018-11-05 at 9 33 54 am copy" src="https://user-images.githubusercontent.com/3782314/48005049-7250e380-e0e0-11e8-9e4e-f0a57ebbce18.png">

The logo's teeny weeny little triangle on the center right is required to read the shapes but its disproportionately small compared to the rest of the logo. Even on the website itself, the upper left size the logo starts to become hard to read. This should bother any logo-designer in my humble opinion.
