### ISSUE TITLE
CLI for model discovery in LB4

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1949]
## Description / Steps to reproduce / Feature proposal
If I have a sql datatabase (say mysql), how can i create model based on the schema in the database? 

Related to: https://github.com/strongloop/loopback-next/issues/1921

## Updates
Per our team meeting, @raymondfeng is suggesting to implement `lb4 discover` instead of document the current way for model discovery because not all the generated model json from the `discoverSchemas` method can be represented correctly in LB4 model (it works for the simple cases, but may not be for other).

There will be 2 stages in `lb4 discover`:
1. Getting the model JSON from database
   - after creating the datasource, users can simply run this discover command to get the model json.
   - at the same time, model.json created in LB3 can be reused in this case
2. Using the model.json to generate model.ts

 @strongloop/loopback-maintainers, thoughts?

-------
## Acceptance Criteria
- [ ] Document the instruction in how to use`DataSource.discoverSchemas` to create model. 
   - Possibly create a page under `How tos` in documentation

### References
I've captured some steps in how to use model discovery and Mario added his comments in the following links:
https://github.com/strongloop/v4.loopback.io/issues/50#issuecomment-433191443
https://github.com/strongloop/v4.loopback.io/issues/50#issuecomment-433236523

**Comment by jannyHou** [comment]
Hmm I think this is a dup story of https://github.com/strongloop/loopback-next/issues/1921

And a community member is already implementing the cli in a forked repo.

**Comment by dhmlau** [comment]
@jannyHou , if it's a duplicate, I'm good to close this issue and continue the discussion over #1921.

**Comment by bajtos** [comment]
@jannyHou @dhmlau Since you closed this issue as a duplicate of #1921, could you please update labels on #1921 to include labels from this issue? 

As I see it, this issue was about improving our CLI, while #1921 was more about documenting how to use existing APIs.

**Comment by bajtos** [comment]
Do we also need to update our issue keeping track of feature parity with LB3? https://github.com/strongloop/loopback-next/issues/1949 Are there any other issues and Epics to update?

**Comment by dhmlau** [comment]
@bajtos, is this PR https://github.com/strongloop/loopback-next/pull/2245 fixes this issue?

**Comment by dhmlau** [comment]
Closing as done as PR https://github.com/strongloop/loopback-next/pull/2245 has landed.
