### ISSUE TITLE
Support local API Explorer

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1960]
## Description / Steps to reproduce / Feature proposal
See PR https://github.com/strongloop/loopback-next/pull/1957

### Acceptance Criteria
- [x] Make API Explorer as a component and can be run without internet connection.  
   - @hacksparrow has a PR https://github.com/strongloop/loopback-next/pull/1957
- [x] Documentation on how can users use it
- [x] Blog post

**Comment by bajtos** [comment]
The feature (including docs) has been landed. Now we need to write a blog post.

**Comment by bajtos** [comment]
The blog post is in review.

**Comment by bajtos** [comment]
Closing as done.
