### ISSUE TITLE
Auto execute a function inside a service provider once the app gets started

### ISSUE THREAD

**Issue by Dallsant** [strongloop/loopback-next#1963]
Good day, I want to know how to start a function in a service when the app gets started. Thanks in advance.

**Comment by kawasaki23Ven** [comment]
+1

**Comment by jannyHou** [comment]
Hi @Dallsant @kawasaki23Ven could you explain more about "start a function in a service"?
This might be related to the life cycle discussion in https://github.com/strongloop/loopback-next/issues/1845

**Comment by Dallsant** [comment]
> Hi @Dallsant @kawasaki23Ven could you explain more about "start a function in a service"?
> This might be related to the life cycle discussion in #1845

Hello, yes, that is what I had been looking for, thank you very much.

**Comment by jannyHou** [comment]
I am closing it since the answer if found. Feel free to reopen it if you have more questions.
