### ISSUE TITLE
Allow extensions to contribute static assets

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1967]
While working on self-hosted API Explorer as a standalone extension (see https://github.com/strongloop/loopback-next/pull/1957), we discovered a missing feature: how can extensions like API Explorer contribute static assets?

```ts
export class ExplorerComponent implements StaticComponent {
   staticAssets = [
     {
       path: '/explorer1',
       rootDir: './public', //path.resolve(__dirname, '../../../explorer'),
       options: {},
     },
   ];
 }
```

The tricky question to answer: what part of LB should process `staticAssets` provided by components? It cannot be done by `Application` and/or `mountComponent` in `@loopback/core`, because static assets are REST-specific and don't make sense in GraphQL applications (for an example). 

Consider also the following example we need to support:

```ts
const app = new Application();
app.component(RestComponent);
app.component(ExplorerComponent);
```

A more subtle problem to address (ideally as part of this work): how can an extension (e.g. ExplorerComponent) declare a dependency on another extension (e.g. RestComponent)? Consider the following example - ideally the app should throw an error because the API Explorer cannot be used on non-REST apps:

```ts
const app = new Application();
app.component(ExplorerComponent);
```

**Comment by raymondfeng** [comment]
IMO, this is a typical extension point/extension pattern:

1. The RestComponent declares an extension point to accept static assets (say: `static-assets-extension-point`)
2. The ExplorerComponent declares an extension to the `static-assets-extension-point`.

Please note the order of component loading should not matter. 

For the RestComponent, it needs to know all extensions contributed to the `static-assets-extension-point` and handle them accordingly. One of the challenges is how to deal with add/remove of such extensions after the RestComponent is loaded/started. Probably we need to introduce the observer pattern.

See my experiment at https://github.com/strongloop/loopback-next/pull/657. I think we should continue on that path.

**Comment by bajtos** [comment]
> The RestComponent declares an extension point to accept static assets (say: static-assets-extension-point)
> The ExplorerComponent declares an extension to the static-assets-extension-point.

Should we perhaps leverage Context bindings, similarly to how `app.controller()` leverages context bindings under the hood to keep a list of all controllers?

1. The Explorer component exports a binding with the key `static-assets.explorer`. (`app.static` would be changed to create bindings with a similar key under the hood too.) See how controllers are registered now: https://github.com/strongloop/loopback-next/blob/81c85d3659b7009f4437ab2795379ac2e38db19f/packages/core/src/application.ts#L42-L47

2. The REST server looks for all bindings with `static-assets.` prefix and register them with the routing table. See how controllers are iterated now: https://github.com/strongloop/loopback-next/blob/81c85d3659b7009f4437ab2795379ac2e38db19f/packages/rest/src/rest.server.ts#L276-L278

This would require us to allow components to contribute arbitrary bindings, as discussed in https://github.com/strongloop/loopback-next/pull/1924.

What I like about this approach is that it builds on existing patterns we are already using for other LB4 features, there is no need to implement new infrastructure for extension points.

A possible downside I see: this does not allow components to declare their dependencies (e.g. Explorer requires REST). OTOH, I think this second part can be addressed independently.
