### ISSUE TITLE
Tutorial on how to build a LB4 app using plain JavaScript

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1970]
## Description / Steps to reproduce / Feature proposal
The recommended way to build LoopBack 4 applications is to use TypeScript.  Given that there are a lot more JavaScript developers out there than the TypeScript counterpart, we should look into how to build a LB4 app using plain JavaScript. 
- is it possible?  If so, document it and create a tutorial
  - e.g. JavaScript does not have a notion of decorators.  How can someone achieve the same thing with JavaScript, if possible? 
- How much is it easier to use TypeScript than to use JavaScript?

cc @raymondfeng @bajtos 

## Acceptance Criteria
- [ ] Tutorial in docs (maybe under howto section) on how to create a LB4 app using JavaScript
- [ ] Blog post - cover some of the points in the spike finding.  Some suggestions:
   - what we can possibly do in the future to make this user experience better, if any
   - what are the pain points of using JS or what can't be done in JS, and guide users that the best way to do it is through TypeScript.

**Comment by bajtos** [comment]
@dhmlau is this story a part of or a duplicate of the epic _Plain JavaScript experience #560_?

**Comment by dhmlau** [comment]
@bajtos , sorry about the late reply.  I'm thinking this story is part of the _Plain JavaScript experience_ epic.  After the spike #1978 , we should create a tutorial (i.e. this story) to show users how to build LB4 using JS.

**Comment by bajtos** [comment]
> I'm thinking this story is part of the Plain JavaScript experience epic. After the spike #1978 , we should create a tutorial (i.e. this story) to show users how to build LB4 using JS.

Sounds good, thank you for clarification.
