### ISSUE TITLE
Mail connector undefined

### ISSUE THREAD

**Issue by DivCorleone** [strongloop/loopback-next#1971]
## Steps to reproduce

```
lb4 datasource 
? Datasource name: mail
? Select the connector for mail: Email (supported by StrongLoop)
? An array of transport configuration objects: [ { "type": "SMTP", "host": "smtp.gmail.com", "secure": true, "port": 465, "tls": { "rejectUnauthorized": false   },  "auth": { "user": "name@gmail.com",  "pass": "pass"  }  }  ]
```
index.ts: 

```javascript
export async function main(options: ApplicationConfig = {}) {
  const app = new MaillingApplication(options);
  await app.boot();
  await app.start();

  const url = app.restServer.url;
  console.log(`Server is running at ${url}`);
  console.log(`Try ${url}/ping`);

  let mailer = new MailDataSource;
  console.log('mailer.connector: ', mailer.connector); // undefined

  return app;
}
```

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@DivCorleone, I've transferred your issue to `loopback-next` which is the repo to open LB4 issues.

**Comment by dhmlau** [comment]
Closing as duplicate of https://github.com/strongloop/loopback-next/issues/1971.

**Comment by dhmlau** [comment]
Sorry to close your issue by accident.  Looks like this issue will be closed if I closed your original ticket.

**Comment by dhmlau** [comment]
@DivCorleone, may I know what you're trying to accomplish in the code snippet above?  
You might want to take a look at this documentation page: https://loopback.io/doc/en/lb3/Email-connector.html.  Thanks.

**Comment by DivCorleone** [comment]
I'm trying to send mails. I have seen your loopback v3 documentation, but unfortunately i didnt find a way to make it works in lb4 ? I tried reproducing every step in loopback v4 but for me some steps doesn't stick with lb4. Maybe i am not yet enough experienced with loopback to make it works. So here are the different approaches i tried:

By following the v3 doc:

 - Create a mail datasource using `lb4 datasource` (step 1 of the doc)

 - Create a model even if config-model.json is not appearing anymore in lb4, by using `lb4 model` and adding `@model({"datasource": "mail"})` to the model decorator to simulate what is made in the doc (step 2). But i think in lb4 that would be more a repository that would be needed than a model defining a shema ? But unfortunaly when ruining `lb4 repository` he doesnt find the mail datasource (others work).

 - Try implementing a similar function that the one presented, but unfortunately i had multiple problems: what is the similar app object in lb4 that is use in lb3, there is no more` let app = module.exports = loopback()` containing all the models ? My newly created mail model has no send method in his definition ? how it is supposed to use it without defining it in a strong typed language and without any heritage ? (step 3)

Having no answer to those questions i tried to do it my way by directly instantiating the MailDataSource, to make it connect, but his connector object is undefined. I tried with `lb4 datasource` like shown in my first message or like that:

``` javascript
let mailer = new juggler.DataSource('mail', {
    name: "mail",
    connector: "mail",
      "transports": [
    {
      "type": "smtp",
      "host": "smtp.gmail.com",
      "secure": true,
      "port": 465,
      "tls": {
        "rejectUnauthorized": false
      },
      "auth": {
        "user": "name@gmail.com",
        "pass": "pass"
      }
    }
  ]
   });

console.log('mailer.connector: ', mailer.connector); // undefined
```

As you can see i'm a bit lost, am i missing something? 

I have a wrapper around nodemailer that can do the work, i'm just looking for a more LB4 friendly way of doing it.

**Comment by dhmlau** [comment]
@DivCorleone, after discussing with @bajtos:
- Ideally we can use the email connector for this purpose.  However, the email connector is part of the LB3 core, so cannot be used as-is.
- What  you can do is:
    - Option#1: use nodemailer directly (which you have already done) and implement it as a service.  See https://github.com/strongloop/loopback-next/blob/master/examples/todo/src/services/geocoder.service.ts as an example. 
    - Option#2: use email connector built by the community instead of our supported email connector.  See https://www.npmjs.com/search?q=loopback%20connector%20email. 

To go forward, what we'll need to do:
- remove email connector option when running `lb4 datasource`
- possibly implement the email connector (extracted from LB3 core) as part of the juggler-next effort

Hope it helps and thanks for reporting this.  I'll create the tasks for the 2 to-dos.

**Comment by DivCorleone** [comment]
Thank you for the answers, that is good for me so i close the threat.

**Comment by ibmjm** [comment]
@DivCorleone are you able to share a working sample of how you were able to get LB4 to work with nodemailer?  I am unable to follow what you did from the brief description your mentioned above, unfortunately.

**Comment by DivCorleone** [comment]
Sorry but i never had a working example of nodemailer working inside of LB4. Idk if at this time LB4 mail connector has been implemented. The brief example was just to show that the mail connector was not present in LB4.

**Comment by ibmjm** [comment]
@DivCorleone Oh that's a shame, it sounded like this was closed because you'd reached a viable workaround :(

**Comment by DivCorleone** [comment]
Yes, the workaround is to use nodemailer directly. Or use a community connector, but i didnt try this.

**Comment by ibmjm** [comment]
> Yes, the workaround is to use nodemailer directly. Or use a community connector, but i didnt try this.

I was able to add a controller to my LB4 application that sends email, by adding  `let nodemailer = require("nodemailer");` at the top of my controller, and then in my controller class adding a method along these lines:

```  @get('/mail')
  async mail() : Promise<any> {
    let transporter = nodemailer.createTransport({
      sendmail: true,
      newline: 'unix',
      path: '/usr/sbin/sendmail'
    });
    return transporter.sendMail({
      from: 'sender@example.com',
      to: 'recipient@example.com',
      subject: 'Message',
      text: 'I hope this message gets delivered!'
    });
  }
``` 

Obviously the method would have to be fleshed out to be useful, but I hope this helps someone.

**Comment by gautamkriiest** [comment]
> > Yes, the workaround is to use nodemailer directly. Or use a community connector, but i didnt try this.
> 
> I was able to add a controller to my LB4 application that sends email, by adding `let nodemailer = require("nodemailer");` at the top of my controller, and then in my controller class adding a method along these lines:
> 
> ```
>   async mail() : Promise<any> {
>     let transporter = nodemailer.createTransport({
>       sendmail: true,
>       newline: 'unix',
>       path: '/usr/sbin/sendmail'
>     });
>     return transporter.sendMail({
>       from: 'sender@example.com',
>       to: 'recipient@example.com',
>       subject: 'Message',
>       text: 'I hope this message gets delivered!'
>     });
>   }
> ```
> 
> Obviously the method would have to be fleshed out to be useful, and it would be preferable to have a proper LB4 email connector, but I hope this helps someone.

do you have working model with LB4 which can trigger email?

**Comment by ibmjm** [comment]
> 
> do you have working model with LB4 which can trigger email?

Sorry, I don't understand why you mean by working model... the sample above was in the controller and could use any model needed.

**Comment by gautamkriiest** [comment]
> > do you have working model with LB4 which can trigger email?
> 
> Sorry, I don't understand why you mean by working model... the sample above was in the controller and could use any model needed.

please send me service part.
