### ISSUE TITLE
Docs: how to impose additional conditions on repo.find filter

### ISSUE THREAD

**Issue by jiwantmg** [strongloop/loopback-next#1973]
I am trying to find all records based on deleted_at flags null. I typed a query like.. 

```ts
let academic_levels: AcademicLevel[] = await this.academicLevelRepository.find(filter, {
        fields: { deleted_at: null},
        where: { deleted_at: null }
      }
```

but it seems it is not working. I also tried this query with fields and where individually without including at once. Please tell me where can I put a where condition that returns me a list of records with deleted_at= null;

I found a one solution. I can send a filter query in a url but I don't exactly don't want this features for deleted_at since it will be the common filter for all query.

## Current Behavior

```json
{
    "data": {
        "academic_levels": [
            {
                "code": "567c3909-da87-0b6b-ad2d-cb6f3427f681",
                "org_code": "483d8100-da0d-b020-ee52-7318cadc5ac7",
                "title": "PRIMARY LEVEL",
                "short_code": "PS",
                "level_number": 1,
                "duration_days": 100,
                "status": null,
                "created_by": "Jiwan",
                "created_at": "2018-11-04T12:11:33.524Z",
                "updated_at": "2018-11-04T12:11:33.524Z",
                "deleted_at": "2018-11-04T12:16:44.163Z"
            },
            {
                "code": "a66f45cc-bb3f-d3e0-5042-6bc6e00c24bd",
                "org_code": "483d8100-da0d-b020-ee52-7318cadc5ac7",
                "title": "PRE SCHOOL",
                "short_code": "PS",
                "level_number": 1,
                "duration_days": 100,
                "status": null,
                "created_by": "Jiwan",
                "created_at": "2018-11-04T12:10:56.253Z",
                "updated_at": "2018-11-04T12:10:56.253Z",
                "deleted_at": null
            }
        ]
    },
    "date": "Mon Nov 05 2018 02:58:37 GMT+0000 (UTC)",
    "url": "/academic-levels"
}
```

## Expected Behavior

```json
{
    "data": {
        "academic_levels": [
  
            {
                "code": "a66f45cc-bb3f-d3e0-5042-6bc6e00c24bd",
                "org_code": "483d8100-da0d-b020-ee52-7318cadc5ac7",
                "title": "PRE SCHOOL",
                "short_code": "PS",
                "level_number": 1,
                "duration_days": 100,
                "status": null,
                "created_by": "Jiwan",
                "created_at": "2018-11-04T12:10:56.253Z",
                "updated_at": "2018-11-04T12:10:56.253Z",
                "deleted_at": null
            }
        ]
    },
    "date": "Mon Nov 05 2018 02:58:37 GMT+0000 (UTC)",
    "url": "/academic-levels"
}
```

**Comment by b-admike** [comment]
@jiwantamang Thank you for providing details on the failure. I can try to recreate a model with your properties and try it out, but if you can create a simple app which can show the problem in a repo, it'd help me to debug it.

**Comment by b-admike** [comment]
@jiwantamang I've created a sample app with a similar but simpler model:
```ts
@model()
export class AcademicLevel extends Entity {
  @property({
    type: 'string',
    id: true,
  })
  code?: string;

  @property({
    type: 'string',
    required: true,
  })
  title: string;

  @property({
    type: 'string',
    default: 'PS',
  })
  short_code?: string;

  @property({
    type: 'date',
    default: null,
  })
  deleted_at?: string;

  constructor(data?: Partial<AcademicLevel>) {
    super(data);
  }
}
```

Adding a controller method which searches with filter `{where: {deleted_at: null}}` returns the expected results:
```ts
  async findWithNullDelete(): Promise<AcademicLevel[]> {
    const filter: Filter = {where: {deleted_at: null}};
    return await this.academicLevelRepository.find(filter);
  }
```

```
[
  {
    "code": "c",
    "title": "string",
    "short_code": "PS",
    "deleted_at": null
  }
]
```
as opposed to a call to `find()`:
```
[
  {
    "code": "a",
    "title": "string",
    "short_code": "PS",
    "deleted_at": "2018-11-07T18:51:37.010Z"
  },
  {
    "code": "b",
    "title": "string",
    "short_code": "PS",
    "deleted_at": "2018-11-07T18:52:18.000Z"
  },
  {
    "code": "btring",
    "title": "string",
    "short_code": "string",
    "deleted_at": "2018-11-07T18:51:37.010Z"
  },
  {
    "code": "c",
    "title": "string",
    "short_code": "PS",
    "deleted_at": null
  }
]
```
One thing I noticed from your code snippet was that you had `filter` as the first argument (which is coming from the query perhaps?) and you are passing your own filter object to the `find()` method as a second argument. In that case, LoopBack treats it as an [Options](https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/common-types.ts#L42-L44) object and ignores it (in the case of memory connector see https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/connectors/memory.js#L377-L381). Should we treat it differently @strongloop/sq-lb-apex @bajtos @raymondfeng?

**Comment by jiwantamang** [comment]
Thank you very much Biniam.
    I really appreciated with your concern about the issue but I was looking for a different solution like I wanted to use the feature of filter on find() where a user can send a custom filter query. At the mean time we must also able to put some extra param on filter like 'deleted_at:null'

I did some extra work and find a solution, please tell me if I am doing right or wrong.

https://github.com/jiwantamang/user-service

**Comment by marioestradarosa** [comment]
@jiwantamang ,  if you want to place a default where clause for the find controller method, do the following: 

```ts
    let imposedWhere = { deleted_at: null };
    if (isFilter(filter)) {
      filter.where = new WhereBuilder(filter.where).and(imposedWhere).build();
    } else {
      filter = new FilterBuilder().where(imposedWhere).build();
    }
  // after this line, we will find the return await this.  statement
```
You will have to import in the controller the following items:

```ts
WhereBuilder,
  FilterBuilder,
  isFilter,
} from '@loopback/repository';
```

**Comment by bajtos** [comment]
> In that case, LoopBack treats it as an Options object and ignores it (in the case of memory connector see https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/connectors/memory.js#L377-L381). Should we treat it differently

I think the current implementation is fine, at least as far as I am concerned.

See the example in the comment by @marioestradarosa for how to solve the use case required by the user.

I think it would be great to capture this recipe in our documentation. I am labelling this issue as "Docs" and "good first issue".

**Comment by b-admike** [comment]
Ah I misunderstood your question @jiwantamang. @marioestradarosa's example snippet should do the trick. I also agree on adding this to docs as @bajtos mentioned as many users would be looking to customize/constrain incoming filter objects.

**Comment by lakshmansai1980** [comment]
is there a way to include nested property in fileds under Filter in loopback 4.

**Comment by agnes512** [comment]
@lakshmansai1980  Yes, please check the nested relation part in the [Query multiple relartions](https://loopback.io/doc/en/lb4/HasMany-relation.html#query-multiple-relations) section.

**Comment by agnes512** [comment]
Filter builder is added in http://127.0.0.1:4001/doc/en/lb4/Querying-data.html#build-filters-with-filterbuilder
Where builder is added in http://127.0.0.1:4001/doc/en/lb4/Where-filter.html
