### ISSUE TITLE
Why is there a `package-lock=false` instruction

### ISSUE THREAD

**Issue by David-Mulder** [strongloop/loopback-next#1983]
## Description / Steps to reproduce / Feature proposal
For continious integration it's crucial that a package-lock.json is generated, but for some reason a default loopback project will contain a `.npmrc` file with a `package-lock=false` instruction.

## Current Behavior
No `package-lock.json` is generated

## Expected Behavior
A `package-lock.json` file is generated

**Comment by raymondfeng** [comment]
For generated applications, a `package-lock.json` can be desired as you said. Are you willing to contribute a patch?

**Comment by jannyHou** [comment]
we could make it an option when generate the app: let the user decide generating `package-lock.json` or not.

**Comment by David-Mulder** [comment]
First of all it would be useful to find out why somebody explicitly put it in there? That's not something that happens by mistake~

Couldn't find the new CLI code quickly, but changing that will be trivial, just didn't want to put in a PR if there is some reason for not generating a `package-lock.json` file ever in an application. Only place afaik where it sometimes can make sense is in public library code and even there it often is useful to know the last successfully used versions to prevent a variety of problems.

**Comment by derdeka** [comment]
@dhmlau @David-Mulder This isses seems to be resolved, as the project uses package-lock.json now.

**Comment by dhmlau** [comment]
You're right. Thanks. Closing as resolved.
