### ISSUE TITLE
.find() and .delete() issues on a DefaultHasManyRepository with MongoDB connector

### ISSUE THREAD

**Issue by loredanacirstea** [strongloop/loopback-next#1987]
## Description / Steps to reproduce / Feature proposal

Using `loopback-connector-mongodb` and a `hasMany` relationship between two Mongo collections (`PipeContainer` and `PipeFunction`).

Inside my `PipeContainerController`, I can successfully do `await this.pipeContainerRepository.functions(containerid).create(pipeFunctionDataObject);` and it correctly creates the new `PipeFunction` record. 

However, the following do not work:
```
await this.pipeContainerRepository.functions(containerid).find();
await this.pipeContainerRepository.functions(containerid).delete();
```

## Current Behavior

```
await this.pipeContainerRepository.functions(containerid).find();
```
returns `[]` even though there are records to be returned.
I also tried `find({where: {_id: "some_valid_id"}})` and again, it returned `[]`.

```
await this.pipeContainerRepository.functions(containerid).delete();
```
Does not remove any if the `PipeFunctions` linked to `PipeContainer` through `containerid`

I assume the problem is with `where`. 

## Expected Behavior

`.find();` on a `DefaultHasManyRepository` should have returned a non empty array.
`.delete();` should have removed all the `PipeFunction` records with the given `containerid`.

**Comment by loredanacirstea** [comment]
My `containerid`field is a `string`. I am using MongoDB, so in fact it is an `ObjectId(<string>)`).
I assume the above issue is related to the fact that when querying:
-  `where = {containerid: "5bdf94e84388069b10351f23"}` returns `[]`
- `where = {containerid: {like: "5bdf94e84388069b10351f23"}}` returns all the pipefunctions with `containerid == "5bdf94e84388069b10351f23"`

`console.log(this.pipeContainerRepository.functions("5bdf94e84388069b10351f23"))`  gives:
```
DefaultHasManyRepository {
  getTargetRepository: [Function: getter],
  constraint: { containerid: '5bdf94e84388069b10351f23' } }
```
Note the constraint.

**Comment by jormar** [comment]
I have the same problem here. I tried `where = {containerid: {like: "5bdf94e84388069b10351f23"}}` and it works... but, it doesn't seem like right.

**Comment by b-admike** [comment]
Hi @loredanacirstea @jormar, sorry for the late reply and thank you for the detailed reproduction steps. I was able to see the issue and I think for this to work, we would need to set the `strictObjectIDCoercion` flag (see https://github.com/strongloop/loopback-connector-mongodb#strictobjectidcoercion-flag) on the model that is being queried, in this case, `PipeFunction`, so that the id is not coerced into ObjectID. To do this, you'd need to add it to the `settings` of the model by supplying the metadata in the `model` decorator for the target model as follows:

```ts
@model({
  settings: {
    strictObjectIDCoercion: true,
  },
})
```

**Comment by b-admike** [comment]
Closing this as resolved, but feel free to re-open @loredanacirstea @jormar.
