### ISSUE TITLE
Docs: fix file-name captions for source code snippets

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1994]
In many places of LB4 documentation, we use the following style for source code file examples:

<pre><code>
#### src/models/todo-list.model.ts

```ts
 import {hasMany} from '@loopback/repository';
 import {Todo} from './todo.model';
// etc.
```
</code></pre>

This is inconsistent with the style we use in LB3 documentation and possibly other places, see https://loopback.io/doc/en/contrib/code_samples.html

<pre><code>
{% include code-caption.html content="/common/models/user.json" %}

```javascript
...
// Some code
...
```
</code></pre>

I am proposing to fix all documentation files in loopback-next to use code-caption style.

**Comment by dhmlau** [comment]
Looks like this task is in progress.
