### ISSUE TITLE
Running unit tests inside docker

### ISSUE THREAD

**Issue by ido567** [strongloop/loopback-next#1995]
I have a fresh installation of Loopback V4 which I try to run inside a docker.
To access the `ping` endpoint, I had to set the `HOST` ENV variable to `0.0.0.0`.
My problem is that after the change, I get an error when I run `npm run test`, the log:
```
> myapp@1.0.0 pretest /src
> npm run clean && npm run build


> myapp@1.0.0 clean /src
> lb-clean dist


> myapp@1.0.0 build /src
> lb-tsc es2017 --outDir dist


> myapp@1.0.0 test /src
> lb-mocha --allow-console-logs "dist/test"



  !!

  0 passing (109ms)
  2 failing

  1) HomePageController
       exposes a default home page:
     Error: connect EADDRNOTAVAIL ::1:33967 - Local (:::0)
      at Object._errnoException (util.js:1022:11)
      at _exceptionWithHostPort (util.js:1044:20)
      at internalConnect (net.js:976:16)
      at defaultTriggerAsyncIdScope (internal/async_hooks.js:283:19)
      at net.js:1074:9
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) PingController
       invokes GET /ping:
     Error: connect EADDRNOTAVAIL ::1:46317 - Local (:::0)
      at Object._errnoException (util.js:1022:11)
      at _exceptionWithHostPort (util.js:1044:20)
      at internalConnect (net.js:976:16)
      at defaultTriggerAsyncIdScope (internal/async_hooks.js:283:19)
      at net.js:1074:9
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)

```

I found few posts about Loopback & docker, but they were all about V3.
Any idea of how to fix it? Or any related materials for docker & V4?

**Comment by dhmlau** [comment]
@ido567 , let me try it out later tonight.  A few things to note:
- HomePageController no longer being generated if you're using the latest @loopback/cli. 
- Regarding the error about :::0, it might be because it's expecting a IPv6 address? There's some change in the generated index.js file to specify the host, see https://github.com/strongloop/loopback-next/blob/master/examples/todo/index.js#L15.

**Comment by dhmlau** [comment]
@ido567, I created the `Dockerfile` below and ran into the same issue:
```
From node:8-slim
EXPOSE 3000
```
It looks like it is related to IPv6 issue.  I tried to look up solutions related to this but failed to resolve the problem.  Will continue to look into it some more tomorrow.

Having said that, in `test/test-helper.ts`, we can force to use IPv4 address to avoid this problem.

From:
```
export async function setupApplication(): Promise<AppWithClient> {
  const app = new Test_1Application({
    rest: config,
  });
...
```
to: 
```
export async function setupApplication(): Promise<AppWithClient> {
  const config = givenHttpServerConfig();
  config.host = '127.0.0.1';
  const app = new Test_1Application({
    // rest: givenHttpServerConfig(),
    rest: config,
  });
```

Hope it helps for now.

**Comment by mathiasarens** [comment]
This solved the issue for me.

**Comment by dcuenot** [comment]
On my side, it doesn't solve the issue.
Do you have any idea?

Please find below my error messages:

```
1) HomePage
       exposes a default home page:
     Error: connect EADDRNOTAVAIL ::1:33857 - Local (:::0)
      at internalConnect (net.js:875:16)
      at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
      at defaultTriggerAsyncIdScope (net.js:965:9)
      at process._tickCallback (internal/process/next_tick.js:61:11)

  2) HomePage
       exposes self-hosted explorer:
     Error: connect EADDRNOTAVAIL ::1:33857 - Local (:::0)
      at internalConnect (net.js:875:16)
      at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
      at defaultTriggerAsyncIdScope (net.js:965:9)
      at process._tickCallback (internal/process/next_tick.js:61:11)

  3) PingController
       invokes GET /ping:
     Error: connect EADDRNOTAVAIL ::1:33509 - Local (:::0)
      at internalConnect (net.js:875:16)
      at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
      at defaultTriggerAsyncIdScope (net.js:965:9)
      at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by jeckel** [comment]
@dcuenot In some cases, the port returned by the `givenHttpServerConfig` is 0.

I've fixed this on my side by modifying the `test-helper.ts` like this :

```js
export async function setupApplication(): Promise<AppWithClient> {
  const config = givenHttpServerConfig();
  if (config.port == 0) {
    config.port = parseInt(process.env.PORT || '3000');
  }
  if (typeof config.host == 'undefined') {
    config.host = process.env.HOST || 'localhost';
  }
  const app = new NoviApplication({
    rest: config
  });
```

**Comment by raymondfeng** [comment]
@jeckel We intentionally use port `0` so that the OS assigns an available port for the rest server. The port should have no impact on `ipv6` or `ipv4`.

**Comment by raymondfeng** [comment]
BTW, can you try to enable ipv6 for your docker daemon? See https://docs.docker.com/v17.09/engine/userguide/networking/default_network/ipv6/.

**Comment by jeckel** [comment]
@raymondfeng I have the exact same result as reported by @dcuenot 

I'll try to activate IPv6 on my machine and let you know. But I won't be able to enable it on the CircleCI daemon (which I use for CI)

What about the possibility to force PORT and HOST with env variables when needed ?

**Comment by raymondfeng** [comment]
Please review https://github.com/strongloop/loopback-next/pull/2433

**Comment by jeckel** [comment]
@raymondfeng Thx a lot for this fix :)
