### ISSUE TITLE
Advanced Auth Features

### ISSUE THREAD

**Issue by nabdelgadir** [strongloop/loopback-next#2000]
## Description 
Step 5 from https://github.com/strongloop/loopback-next/issues/1035#issuecomment-429774436.

Armed with a small application having authentication and authorization constraints in place, let's look at extensibility and what extension points we may need to define to support those use cases.

Few example scenarios to drive our focus:

- Allow customers to register and login using their Google account.
- Implement multi-tenancy - group users and admins into realms. Users (customers and admins) from one realm cannot see data from other realms. A superuser can see data from all realms.
- Simplify management of scopes by introducing Roles (a user belongs to a single role, a role grants many scopes).
- Implement an OAuth provider for 3rd party client apps. Let the customer decide which scopes they are willing to grant to each app (an access token used by an app).
- Add support for 2-factor authentication based on TOTP (Time-based One-time Password), using a mobile phone app like [Authy](https://authy.com/) or [Google Authenticator](https://en.wikipedia.org/wiki/Google_Authenticator) as the second factor.

Ideally, there should be a documentation and/or a blog-post and/or a reference implementation to make it easier for LB4 users to implement similar functionality in their project.

Previous step: https://github.com/strongloop/loopback-next/issues/1999

**Comment by David-Mulder** [comment]
Just noting: A user might be able to "only read data (role: 'reader') from realm A", but also "can be an admin (role: 'admin') in realm B". So I would expect:

 - Realms can be nested (e.g. company -> department -> team)
 - A user can have one role for each realm he has access to

In combination with the nested behavior this would allow a user to have read access to all data from company A & C, but also have write privileges to department IV of company A.
