### ISSUE TITLE
[OpenAPI] Filter properties different from number, not used in the call

### ISSUE THREAD

**Issue by apocaliss92** [strongloop/loopback-next#2003]
## Description / Steps to reproduce / Feature proposal
1. Open OpenAPI
2. Select an endpoint allowing filter param
3. Set di filter to something like this: 
      {
        "where": {"a": 1},
        "fields": {"a": true},
        "offset": 10,
        "limit": 10,
        "skip": 10,
        "order": [
             "a"
        ]
      }
4. Execute the call
## Current Behavior
The effective call made is the following:
curl -X GET "http://127.0.0.1:3000/users?filter[offset]=10&filter[limit]=10&filter[skip]=10" -H "accept: application/json"
ignoring the filter parameters "not-number"
## Expected Behavior
curl -X GET "http://127.0.0.1:3000/users?filter[offset]=10&filter[limit]=10&filter[skip]=10&filter[where][a]=1&filter[fields][a]=true&filter[order]=a" -H "accept: application/json"

**Comment by jannyHou** [comment]
@apocaliss92 I think it's the same issue as https://github.com/strongloop/loopback-next/issues/3770, we will support complex object filter in the explorer.

I am closing this issue as a duplicate and let's use #3770 to track the progress. Feel free to reopen it if you have other questions.
