### ISSUE TITLE
loadash low severity issue on npm audit

### ISSUE THREAD

**Issue by mightytyphoon** [strongloop/loopback-next#2004]
## Issue Description
npm audit return a low severity issue.

## Current Behavior
on npm audit
```
Low             Prototype Pollution

  Package         lodash

  Patched in      >=4.17.5

  Dependency of   @loopback/build [dev]

  Path            @loopback/build > strong-docs > dox > jsdoctypeparser >
                  lodash

  More info       https://nodesecurity.io/advisories/577
```

## Expected Behavior  
no issue.

**Comment by dhmlau** [comment]
It's related to this ongoing PR: https://github.com/strongloop/loopback-next/pull/1903

**Comment by vinutha93bnvs** [comment]
is there any update on when this issue will be fixed ?
Looking for production Go with some PI data. 
This is a blocker for me.

**Comment by mightytyphoon** [comment]
@vinutha93bnvs it's actually not a real problem, as you can see it comes from  @loopback/build > strong-docs > dox > jsdoctypeparser > lodash

Basically it's an error from the docs, you can remove strong-docs or ignore the error. I agree it would be better (psychologically) to not see any error on npm audit but it's actually not something that could stop you from going into production.

**Comment by raymondfeng** [comment]
@vinutha93bnvs Please note `strong-docs` is dev dependency and it's not required by the runtime. If you use `npm i --production`, it will not be installed.
