### ISSUE TITLE
React SDK

### ISSUE THREAD

**Issue by KyDenZ** [strongloop/loopback-next#2006]
Hi,

I saw that you are currently working on the React SDK. Do you know approximatively when will you release that feature ? 

Thank you very much.

**Comment by dhmlau** [comment]
@KyDenZ, currently we are not working on any of the client SDKs.  You might get this from this extension wish list GitHub issue: https://github.com/strongloop/loopback-next/issues/512, where such SDK could be an extension?

**Comment by jdegger** [comment]
Are the old client SDKs compatible with loopback 4?

**Comment by jdegger** [comment]
@dhmlau Are the old client SDKs compatible with loopback 4?

**Comment by KyDenZ** [comment]
@dhmlau, I think that a SDK like it was done for loopback 3 and Angular 2 would be good instead of an extension.

Or, the possibility of converting TypeScript models to a file compatible with OpenApi. I know that the opposite is possible to convert an openApi file to models loopback, but the opposite does not seem to me.

@jdegger, old sdk do not work with loopback 4.

You can use [openApi](https://github.com/OpenAPITools/openapi-generator) to generate your front and back models.

**Comment by dhmlau** [comment]
I believe @KyDenZ has answered the question.  Closing this as resolved. Thanks.
