### ISSUE TITLE
Defining virtual fields in models (linked to a mysql datasource)

### ISSUE THREAD

**Issue by overburn** [strongloop/loopback-next#2013]
Hi,

Having trouble handling a hasMany relation. So, I have Product -> Has Many -> Properties

I've defined the productId property on the Properties model; Defined the hasMany decorator on the 'properties' field of the Product model.

Updated the Product repository to handle assignment via a HasManyRepositoryFactory.
Only issue now is that the automigration creates a "properties" TEXT field on the Product table. (MySQL).

Any idea how I could define it as purely virtual?

Thanks!

**Comment by b-admike** [comment]
Hi @overburn, this should be fixed by #2167 in the latest release (https://github.com/strongloop/loopback-next/releases/tag/%40loopback%2Frepository%401.1.3). Feel free to re-open if you still see this issue.
