### ISSUE TITLE
Add Component page under Key Concepts

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2020]
## Description / Steps to reproduce / Feature proposal
In https://loopback.io/doc/en/lb4/Crafting-LoopBack-4.html#rebuilding-loopback-experience-on-top-of-the-new-core, the link for `Component` is broken. 

Talked to @raymondfeng , we should have a page for `Component` under concepts.  

Related to https://github.com/strongloop/loopback-next/issues/1908

## Acceptance Criteria
- [ ] Create a `Component` page under `Key concepts`. Describe the functionality and interface of a `Component` class on it.
- [ ] Refactor the `Using components` page by moving relevant content to `Component` page.
- [ ] Link the `Component` page from `Concepts` page.

**Comment by bajtos** [comment]
As a short-term solution to fix the broken link, I am proposing to point readers to https://loopback.io/doc/en/lb4/Extending-LoopBack-4.html for now as part of this story, and create a new story to write `Component` page under `Concepts`.

**Comment by dhmlau** [comment]
Created PR https://github.com/strongloop/loopback-next/pull/2361 to fix the broken link, and updated the Acceptance Criteria.

**Comment by dhmlau** [comment]
@raymondfeng , what content do you have in mind for that `Component` page?  given that we have https://loopback.io/doc/en/lb4/Using-components.html.  Thanks.

**Comment by dhmlau** [comment]
Fixed the broken link through PR https://github.com/strongloop/loopback-next/pull/2361.  Moving this out of `TOB`.

**Comment by dhmlau** [comment]
I forgot that we need to estimate this task first. 
@hacksparrow, could you please edit the acceptance criteria? Thanks!

**Comment by emonddr** [comment]
@dhmlau 
> In https://loopback.io/doc/en/lb4/Crafting-LoopBack-4.html#rebuilding-loopback-experience-on-top-of-the-new-core, the link for Component is broken. 

I don't see the word `Component` on the url you mentioned. Do you mean it is missing somewhere on the left side bar?

**Comment by dhmlau** [comment]
Sorry.. I think I was referring to the section above. Should be here: https://loopback.io/doc/en/lb4/Crafting-LoopBack-4.html#deep-dive-into-loopback-4-extensibility. But I fixed the broken link to point to the `using-component.md`.

**Comment by dhmlau** [comment]
Closing as resolved because PR https://github.com/strongloop/loopback-next/pull/2702 has merged.
