### ISSUE TITLE
Custom visual style of REST API Explorer

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2023]
_This is a follow-up for https://github.com/strongloop/loopback-next/pull/2014 which introduced a new extension providing a self-hosted API Explorer._

As a user building a LoopBack application with a self-hosted API Explorer, I would like to change the visual style (colors, etc.) of the Explorer UI.

Implementation wise, this may require the following features:
- Allow the app developer to provide a different `index.html.ejs` template
- Allow the app developer to provide custom CSS/JS/other static assets as an alternative to default assets provided by swagger-ui.

We should review how [loopback-component-explorer](https://github.com/strongloop/loopback-component-explorer) is approaching this problem and use it as an inspiration.

Reference files:

- For LB3, you can replace the [loopback.Styles.css](https://github.com/strongloop/loopback-component-explorer/blob/master/public/index.html#L10) to customize the look, see file https://github.com/strongloop/loopback-component-explorer/blob/master/public/index.html
- The corresponding LB4 file: https://github.com/strongloop/loopback-next/blob/master/packages/rest-explorer/templates/index.html.ejs

Acceptance Criteria:

- [ ] Try modifying the theme by overriding the style files like [`swagger-ui.css`](https://github.com/strongloop/loopback-next/blob/master/packages/rest-explorer/templates/index.html.ejs#L8)
- [ ] Document how to do it.

**Comment by aabou** [comment]
Hello @bajtos,
I'd like to customize the title of my app.
So, i tried to change it in my public/index.html. the change has been applied on my home page and not on my /explorer page!.
The title is-it a custom param (expl one change to all page)? and, have you any proposition to change it in the explorer please?
Thanks in advance.
;-)

**Comment by bajtos** [comment]
@aabou thank you for the comment. At the moment, our API explore does not support customization - that's why this issue is still open!

My recommendation is to create your own fork of `@loopback/rest-explorer` and make any changes there. Just remember to change the package name to something else before you publish it to an npm registry.

The source code can be found here: https://github.com/strongloop/loopback-next/tree/master/packages/rest-explorer It's just few files integrating swagger-ui with LoopBack 4.

**Comment by dougal83** [comment]
https://github.com/ostranme/swagger-ui-themes - Feeling blue looks nice if going for a default lookback feel.

**Comment by jannyHou** [comment]
Merged PR #5200 The guide is updated in https://github.com/strongloop/loopback-next/tree/master/packages/rest-explorer#customizing-swagger-ui-theme, will show up in the documentation https://loopback.io/doc/en/lb4/Self-hosted-rest-api-explorer.html after a new release 🎉 

Thanks for everyone's suggestion and review again 👏 closing it.
