### ISSUE TITLE
Exposing GraphQL APIs tutorial doesn't work

### ISSUE THREAD

**Issue by rubys** [strongloop/loopback-next#2029]
## Description / Steps to reproduce / Feature proposal

Follow the steps in [Exposing GraphQL APIs](https://loopback.io/doc/en/lb4/exposing-graphql-apis.html)

## Current Behavior

```
$ npm i --save oasgraph express express-graphql
npm WARN express-graphql@0.7.1 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN oasgraph@0.11.2 requires a peer of graphql@^0.9.6 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-type-json@0.2.1 requires a peer of graphql@>=0.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN blog@1.0.0 No license field.

+ express-graphql@0.7.1
+ express@4.16.4
+ oasgraph@0.11.2
added 32 packages from 28 contributors, removed 6 packages, updated 3 packages and audited 3563 packages in 5.37s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
$ npx oasgraph http://localhost:3000/openapi.json
npx: installed 156 in 5.754s
command not found: oasgraph
```

## Expected Behavior

Server launched and listening for input on port 3001.

**Comment by raymondfeng** [comment]
@rubys I think you need to install `oasgraph-cli` now as the CLI has been refactored into its own module.
```
npm i --save oasgraph-cli express express-graphql
```

**Comment by raymondfeng** [comment]
@dhmlau Please fix the docs.

**Comment by dhmlau** [comment]
The PR (https://github.com/strongloop/loopback-next/pull/2008) that fixes this issue has merged last night.  Let me get it released.

**Comment by rubys** [comment]
Thanks!  Closing as a dupe of https://github.com/strongloop/loopback-next/pull/2008

**Comment by rubys** [comment]
The good news is that the oasgraph server launches. The bad news is that I can't get any of the queries to work.

input:

```graphql
query {
  article(id:1) {
    title
  }
}
```

output:

```json
{
  "errors": [
    {
      "message": "Invalid URI \"/articles/1\"",
      "locations": [
        {
          "line": 31,
          "column": 3
        }
      ],
      "path": [
        "article"
      ]
    }
  ],
  "data": {
    "article": null
  }
}
```

**Comment by rubys** [comment]
I'm also getting a number of warnings:

```json
{
  "warnings": [
    {
      "type": "MissingResponseSchema",
      "message": "Operation 'PATCH /articles/{id}' has no (valid) response schema.",
      "mitigation": "Ignore operation"
    },
    {
      "type": "MissingResponseSchema",
      "message": "Operation 'DELETE /articles/{id}' has no (valid) response schema.",
      "mitigation": "Ignore operation"
    },
    {
      "type": "MissingResponseSchema",
      "message": "Operation 'PATCH /comments/{id}' has no (valid) response schema.",
      "mitigation": "Ignore operation"
    },
    {
      "type": "MissingResponseSchema",
      "message": "Operation 'DELETE /comments/{id}' has no (valid) response schema.",
      "mitigation": "Ignore operation"
    },
    {
      "type": "InvalidSchemaType",
      "message": "Request / response schema has no (valid) type: {\"type\":\"object\"}",
      "mitigation": "Fall back to type 'GraphQL String'"
    },
    {
      "type": "InvalidSchemaType",
      "message": "Request / response schema has no (valid) type: {\"type\":\"object\"}",
      "mitigation": "Fall back to type 'GraphQL String'"
    },
    {
      "type": "InvalidSchemaType",
      "message": "Request / response schema has no (valid) type: {\"type\":\"object\"}",
      "mitigation": "Fall back to type 'GraphQL String'"
    },
    {
      "type": "InvalidSchemaType",
      "message": "Request / response schema has no (valid) type: {\"type\":\"object\"}",
      "mitigation": "Fall back to type 'GraphQL String'"
    },
    {
      "type": "InvalidSchemaType",
      "message": "Request / response schema has no (valid) type: {\"type\":\"object\"}",
      "mitigation": "Fall back to type 'GraphQL String'"
    },
    {
      "type": "InvalidSchemaType",
      "message": "Request / response schema has no (valid) type: {\"type\":\"object\"}",
      "mitigation": "Fall back to type 'GraphQL String'"
    },
    {
      "type": "InvalidSchemaType",
      "message": "Request / response schema has no (valid) type: {\"type\":\"object\"}",
      "mitigation": "Fall back to type 'GraphQL String'"
    },
    {
      "type": "InvalidSchemaType",
      "message": "Request / response schema has no (valid) type: {\"type\":\"object\"}",
      "mitigation": "Fall back to type 'GraphQL String'"
    }
  ],
  "numOps": 16,
  "numOpsQuery": 8,
  "numOpsMutation": 8,
  "numQueriesCreated": 8,
  "numMutationsCreated": 4
}
```

**Comment by dougal83** [comment]
> The good news is that the oasgraph server launches. The bad news is that I can't get any of the queries to work.
> 
> input:
> 
> ```graphql
> query {
>   article(id:1) {
>     title
>   }
> }
> ```
> 
> output:
> 
> ```json
> {
>   "errors": [
>     {
>       "message": "Invalid URI \"/articles/1\"",
>       "locations": [
>         {
>           "line": 31,
>           "column": 3
>         }
>       ],
>       "path": [
>         "article"
>       ]
>     }
>   ],
>   "data": {
>     "article": null
>   }
> }
> ```

Open http://localhost:3000/openapi.json.  Do you have servers url set like the following?  I had issue from 'lb4 example todo-list' that server url was '/' but rebuilding the example from scratch returned the openapi spec set correctly.


```json
"servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
```
Alternatively you can save the openapi spec alter the url and launch graphql with altered openapi spec file directly.

**Comment by raymondfeng** [comment]
See https://loopback.io/doc/en/lb4/Server.html#customize-how-openapi-spec-is-served. Adding the following config should work.
```
setServersFromRequest: true,
```

**Comment by raymondfeng** [comment]
@rubys Which version of `@loopback/cli` do you use?

The latest version should generate `index.js` as follows:
```js
const application = require('./dist');
  
module.exports = application;

if (require.main === module) {
  // Run the application
  const config = {
    rest: {
      port: +process.env.PORT || 3000,
      host: process.env.HOST || 'localhost',
      openApiSpec: {
        // useful when used with OASGraph to locate your application
        setServersFromRequest: true,
      },
    },
  };
  application.main(config).catch(err => {
    console.error('Cannot start the application.', err);
    process.exit(1);
  });
}
```

With `setServersFromRequest: true`, the openapi.json should have `servers` friendly to oasgraph.

**Comment by rubys** [comment]
> @rubys Which version of `@loopback/cli` do you use?

That was it.  I was using loopback-cli 1.0.1.  Upgrading to 1.1.1 fixes this.

Closing the issue again.

Thanks!

**Comment by dhmlau** [comment]
Looks like the todo-list example does not take in the `config` as parameter.  https://github.com/strongloop/loopback-next/blob/master/examples/todo-list/index.js#L22

It should be:
```
application.main(config).catch(err => {
    console.error('Cannot start the application.', err);
    process.exit(1);
  });
```

Let me verify and submit a PR.

**Comment by dougal83** [comment]
@johntom 

> ./node_modules/.bin/oasgraph : The term './node_modules/.bin/oasgraph' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a

Assuming the example is sound, worked for me a while ago.  Oasgraph relies on npx to run, perhaps that is not configured correctly?  Open up powershell and run 'npx' if that is not recognized then you need to set up your environment.  Possibly you do not have an environment path variable to npm?

e.g.: C:\Users\<username>\AppData\Roaming\npm

Also recommend that you use the following to manage npm on windows(if you don't already!):
https://github.com/felixrieseberg/npm-windows-upgrade

Additional info:
https://www.npmjs.com/package/npx

**Comment by bajtos** [comment]
@johntom thank you for the feedback. Would you like to contribute the necessary documentation improvements yourself? See https://loopback.io/doc/en/contrib/doc-contrib.html to get started.

**Comment by chadmg** [comment]
@bajtos @johntom What is the reason for todos being changed to todos**2**?? Is this a bug? It doesn't make sense to me as to why the 2 needs to be appended to the route name.

**Comment by dudipsh** [comment]
@chadmg  I have the same issue, did you figure it out ?

**Comment by dougal83** [comment]
> @chadmg I have the same issue, did you figure it out ?

@dudipsh I've just followed the tutorial and the result is as expected (ie. todos).  I'd suggest ensuring that you are fully up to date.  Works with following:

- openapi-to-graphql-cli version: 1.6.2
- @loopback/cli version: 1.25.1

If it helps, a working example here: https://github.com/dougal83/loopback4-example-graphql
