### ISSUE TITLE
Boot scripts

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2034]
A boot script is a short piece of code that users want to run during application setup (boot), e.g. to apply additional configuration in a programatic way, add more routes, etc.

In LB3, a boot script is a JS file in `server/boot` directory, loopback-boot automatically discovers and runs these scripts as part of boot.

For LB4, we should come up with a solution that will enable app developers to define custom code bits to be executed during boot, possibly also during start & stop. It is not necessary to use the LB3 approach, we should approach this challenge with a fresh mind and pick a design that leverages the power of LB4.

## Acceptance criteria

TBD

**Comment by bajtos** [comment]
@lucaslopez I like your proposal, but at the same time I feel it's orthogonal to the concept of boot scripts (a convention on where to place source code bits + a booter to discover and execute those bits).

Could you please open a new issue where we can focus on discussing your proposal?

In LoopBack 3, the application object is also an event-emitter providing events like `app.on('modelDefined')` and we were using such events internally too. I think it makes a lot of sense to introduce a similar concept in LB4 too.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/pull/1928

**Comment by lucaslopez** [comment]
> See #1928

Is this considered to cover the loopback application to be an event emitter or should I still open a new issue?

**Comment by lucaslopez** [comment]
> @lucaslopez I like your proposal, but at the same time I feel it's orthogonal to the concept of boot scripts (a convention on where to place source code bits + a booter to discover and execute those bits).
> 
> Could you please open a new issue where we can focus on discussing your proposal?
> 
> In LoopBack 3, the application object is also an event-emitter providing events like `app.on('modelDefined')` and we were using such events internally too. I think it makes a lot of sense to introduce a similar concept in LB4 too.

Thanks for the info! I was not aware LB3 is emitting events as well. Is this documented somewhere or it is just meant for internal use?

**Comment by raymondfeng** [comment]
Please check out https://github.com/strongloop/loopback-next/issues/1928

**Comment by acrodrig** [comment]
I am running into this issue right no with LB4. I want to make sure certain objects exist in the DB right after starting the application. Since all of the application configuration happens in a `constructor` I cannot use `async` methods and I am at a loss as to how best to check if the DB has the needed entities and if not insert them.

Can you help with a workaround with the current state of affairs for LB4?

**Comment by raymondfeng** [comment]
Please follow up with https://github.com/strongloop/loopback-next/pull/2094 and #1928.

**Comment by acrodrig** [comment]
@raymondfeng Thanks for your quick answer. I am just using the DB update as an "example" of something you want to happen right after the application starts. It could also be connecting to a server via a socket, validating a bucket exists on S3, or anything really. So #2094 is not really applicable to my question.

And I did read through #1928 bore. I love the approach and would use it if it were available. Unfortunately it is not yet available.

So my question is, as I am sitting here _today_ trying to use LB4 to get a project done, what is the best approach to get an asynchronous task done after the application/server starts?

**Comment by raymondfeng** [comment]
Hopefully #1928 will be landed soon. Before that, you might have to override `app.start()` method or add more logic to `index.js` to trigger your scripts after `start`.

**Comment by acrodrig** [comment]
Thanks! Somehow I was not aware of `index.js`, so that works well.

**Comment by bajtos** [comment]
> Thanks! Somehow I was not aware of index.js, so that works well.
> By default, VS Code is hiding the file for me and I was running under the assumption that TS would be used in all circumstances. If index.js is a file that requires editing occasionally, perhaps editors should be configured to to show certain .js files default?

Please put your custom logic to `src/index.ts` instead - add more steps to the `main` function.

**Comment by bajtos** [comment]
I am closing this story as done via #1928. Please open a new issue if there are any other changes/improvements needed to support your use cases.
