### ISSUE TITLE
Register Express middleware per route, controller class or controller method

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2035]
As a user migrating from Express, or simply wishing to leverage an existing Express middleware in my application, I would like to enable this middleware for certain routes, controller methods or entire controller classes.

Consider the following definition in an Express app:

```js
app.get('/api/users', 
  requireAuthenticated(),
  requireScope('read:users:all'), 
  withCacheControl({maxAge: '2 hours', private: true}),
  function getUsers(req, res, next) {
    // the route
  });
```

The code snippets below illustrate different ways of applying the middleware. Please note they are just examples, not a final proposal.

**Per route**

A possible LB4 solution (not very ergonomic, a better solution is needed):

```ts
app.route(new ExpressRoute(
  'get',
  '/api/users',
  {
    parameters: [
      {name: 'filter', in: 'query', schema: {/*...*/}}
    ],
    responses: { /*...*/ }
  },
  [
    requireAuthenticated(),
    requireScope('read:users:all'), 
    withCacheControl({maxAge: '2 hours', private: true}),
  ],
  function findUsers(filter: Filter) {
    return userRepo.find(filter);
  }
));
```

**Per controller method**

```ts
class UserController {
  @get('/api/users')
  @use(
    requireAuthenticated(),
    requireScope('read:users:all'), 
    withCacheControl({maxAge: '2 hours', private: true}),
  )
  find(
    @param.query.object('filter', {/*schema*/})
    filter: Filter
  ) {
    return userRepo.find(filter)
  )
}
```

**Per controller class**

This allows developers to apply the same set of middleware for multiple routes.

```ts
@use(requireAuthenticated())
class UserController {
  @get('/api/users')
  @use(requireScope('read:users:all'))
  find() {
    // ...
  )

  @del('/api/users')
  @use(requireScope('write:users:all'))
  delete() {
    // ...
  )
}
```

## Acceptance criteria

TBD

## Out of scope

- application-wide middleware, e.g. `app.use(passport.initialize())` - see #1293 and #1982
- error-handling middleware, e.g. `app.use((err, req, res, next) => {/*...*/})` - see #1293
- middleware serving content, e.g. `serve-static` - developers should use `app.static()` API.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/pull/1671, which can be possibly used as the plumbing.

**Comment by sanadHaj** [comment]
@bajtos  @raymondfeng  @dhmlau 
why do you need to use this proposal ? please elaborate . 
 just an idea , perhaps we can make it look like lb3 . 
an middleware dir that holding all the middlewares classes (like controller) each  class should have PreHandling and PostHandling method (preHandling before invoke controller , posthandling after invoke the controller). with keeping in minds the order of the middleware. 
maybe the issue in this approach is how to boot classes at restServer  @loopback/rest

using this approach we can make the whole thing separated and more clean .

**Comment by raymondfeng** [comment]
@sanadHaj Yes, I have something similar to allow middleware registration using `extension point/extension` via `Context`. See https://github.com/strongloop/loopback-next/pull/2249 as an example.

Are you willing to submit a patch?

**Comment by sanadHaj** [comment]
@raymondfeng 
yep , but first off all let me know how you intend to combine extension and phases to handle middleware 
 keep in minds before and after controller handle the request ? 
secondly may we need to refactor restServer loopback/rest instead of mount requesthandler directly to exprees
 (
https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/rest.server.ts#L224
). 
just to call the phases and the phases will forward the request to requestHandler.

let me know if i am right,
the developer will implement the extension and under the hod the phases will inject the 
extension inside the middileWarePhaseList . and from there call the 
phases and continue the job .

**Comment by sanadHaj** [comment]
@bajtos 
how you plan to provide the requestContext ?  
```ts
@use( requireAuthenticated())
```

**Comment by bajtos** [comment]
@sanadHaj 

> how you plan to provide the requestContext ?

As I wrote before, this GH issue is about using regular Express middleware, e.g. [helmet](https://www.npmjs.com/package/helmet), [cors](https://www.npmjs.com/package/cors) or even [passport](https://www.npmjs.com/package/passport). AFAIK, there is no concept of `requestContext` in Express, I don't see why we should be exposing `requestContext` to Express middleware.

Based on your older comment:

> an middleware dir that holding all the middlewares classes (like controller) each class should have PreHandling and PostHandling method (preHandling before invoke controller , posthandling after invoke the controller). with keeping in minds the order of the middleware.

I think you are looking for "method interceptors" that have been recently introduced by https://github.com/strongloop/loopback-next/pull/2687, see also https://github.com/strongloop/loopback-next/pull/2907, https://loopback.io/doc/en/lb4/Interceptors.html and https://loopback.io/doc/en/lb4/Interceptor-generator.html.

**Comment by codejamninja** [comment]
You can register middleware on a controller using the lb4-middleware component.

```
  @middleware((_req: Request, _res: Response, next: NextFunction) => {
    logger.info('local middleware');
    return next();
  })
  ping(): object {
    return {
      greeting: 'Hello from LoopBack'
    };
  }
```

**Comment by victor-enogwe** [comment]
In case someone else comes here, see the comment [here](https://github.com/strongloop/loopback-next/issues/3947#issuecomment-613898378)

**Comment by dhmlau** [comment]
See PR #5118

**Comment by raymondfeng** [comment]
See https://loopback.io/doc/en/lb4/Express-middleware.html#use-express-middleware-as-interceptors-for-controllers
