### ISSUE TITLE
Auto generated id in cloudant is not a number - todo example not working with cloudant

### ISSUE THREAD

**Issue by cloudwheels** [strongloop/loopback-next#2040]
## Description / Steps to reproduce / Feature proposal

- Deploy todo example connected to cloudant database using connector
- Add some todos
- get todos as a list
- get todos by id

## Current Behavior

inserted autogenerated ids are returned as a the numeric part of the document id if it starts with one, so that:
database records with ids:
```
id"3e8428d6ba9feb6819cfb30756d3d310"
{
 "_id": "3e8428d6ba9feb6819cfb30756d3d310",
 "_rev": "3-9c0030f442f6ac47aab94ceb359179c8"
}
id"70f03fa5007cbbc02690a1c65b3f3e78"
{
 "_id": "70f03fa5007cbbc02690a1c65b3f3e78",
 "_rev": "1-8ec76b46879aa8c3147debb9ab4dedf3"
}
id"75b55970bb16205e4c377da12d97bcf7"
{
 "_id": "75b55970bb16205e4c377da12d97bcf7",
 "_rev": "1-e3f8eca5e6afbac64b52ccc1aee1ec1d"
}
id"b54ad55e77d3c0c5cda2805731cfede0"
{
 "_id": "b54ad55e77d3c0c5cda2805731cfede0",
 "_rev": "1-f03a33fff19afa3f3464ff9a6b05d43d"
}
id"e096ae6ef623c7925d2d76716013bbdc"
{
 "_id": "e096ae6ef623c7925d2d76716013bbdc",
 "_rev": "1-62a17081d83c506b0763fc9d28c5df95"
}
```

are returned as below by the api's GET todos:

```
[
    {
        "id": 3,
        "title": "get better at this"
    },
    {
        "id": 70,
        "title": "try again"
    },
    {
        "id": 75,
        "title": "add"
    },
    {
        "id": null,
        "title": "get milk"
    },
    {
        "id": null,
        "title": "test post",
        "desc": "testing post",
        "isComplete": false
    }
]
```

GET todos/{id} doesn't work (404 not found)

## Expected Behavior
GET todos/{id} returns a todo with id={id} 

Id need to be handled by loopback as a string to return the cloudant doc id.

**Comment by cloudwheels** [comment]
Keeping you busy on a Friday @dhmlau - so sorry ;)
GET todos/{CLOUDANT_ACTUAL_DOC_ID} doesn't work (invalid data type of course as expecting a number)
Not quite a simple as changing the type of id in the todo model I don't think but I have limited understanding of how id types work at this stage: just looking for something that works if you can help!!!

**Comment by cloudwheels** [comment]
Worryingly I'm not sure how this could ever have worked....

**Comment by dhmlau** [comment]
@cloudwheels, no worries :)
If you're using the `todo` example as-is, you'd need to specify the id for `POST`. i.e. something like:
```
{
  "id": 1,
  "title": "task1",
  "desc": "aa",
  "isComplete": false
}
```
I just verified and it seems to be working fine for me.  The document id in cloudant is the id you specify in the json.
<img width="677" alt="screen shot 2018-11-16 at 4 05 42 pm" src="https://user-images.githubusercontent.com/25489897/48647256-7373f180-e9b9-11e8-97a4-3eb323920a6f.png">

Having said that, I did try your scenario where id is not specified in POST, and got a similar result.  It is strange that some id are null and some aren't.

@raymondfeng @b-admike, any idea?

**Comment by cloudwheels** [comment]
I am assuming the app https://mylb4app.eu-gb.mybluemix.net/openapi.json is your deployment @dhmlau ? I can post to this without specifying id and get a numeric id back but I think it suffers the same problem as I cannot get by id and some ids are long ints some short etc? Is this app persisting to cloudant?

**Comment by cloudwheels** [comment]
If I POST to your instance with an id (=1) I get an error, id can't be set:
```
{
  "error": {
    "statusCode": 422,
    "name": "ValidationError",
    "message": "The `Todo` instance is not valid. Details: `id` can't be set (value: \"1\").",
    "details": {
      "context": "Todo",
      "codes": {
        "id": [
          "absence"
        ]
      },
      "messages": {
        "id": [
          "can't be set"
        ]
      }
    }
  }
}
```

**Comment by cloudwheels** [comment]
I was just about to write:
I would also really like to know why your explorer page works and I just get a 'possible CORS error'. Hope to fix this when the locally hosted explorer package is released but still want to know!

So I visit my instance's explorer link which has been giving the CORS error ( https://explorer.loopback.io/?url=https://lb4.eu-gb.mybluemix.net/openapi.json ) and it's suddenly just working! Did somebody somewhere just do something?
Gotta love the bleeding edge :) :) :)

**Comment by dhmlau** [comment]
@cloudwheels , my apologies again for the roadblocks you're hitting! 
I was trying out different things on my app on IBM Cloud, so it may not be behaving as expected.  It's now at a working state: https://todo-diana.mybluemix.net. 

After discussing with @b-admike, we have a few conclusions:
- `id` is expected when creating a todo.  And it's working as expected. 
- According to https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#id-properties: 
> If an ID property has generated set to true, the connector decides what type to use for the auto-generated key. For example for SQL Server, it defaults to number.

   So in the case of Cloudant, id is a string.  To get this example working for Cloudant, we can simply make the id type to be `string`, which you've tried before. 
- However, IMHO, the id type should be database agnostic.  We've explored to use `any` type, but it seems like OpenAPI doesn't support this type (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types). I'd like to bring it forward to the LB maintainers and see what's the best approach for this.  Seems like we have a similar issue in mongodb connector as well (https://github.com/strongloop/loopback-connector-mongodb/issues/165). 
- For incrementing the id or specific attribute when creating the document in Cloudant, someone had done that in my previous project.  It's through the design document.  I can see if I can still find it, if you're interested. :) 

Hope it helps! 

@strongloop/loopback-maintainers, any insights?  
_Sorry if I've mixed up how the id related attributes in model works._

**Comment by dhmlau** [comment]
FYI - my updated todo example can be found here: https://github.com/dhmlau/loopback4-example-todo

**Comment by cloudwheels** [comment]
@dhmlau roads are pretty boring without the odd blockage, provided they an be shifted. The red lines node was throwing at me are less confusing after sleep and altering the id in the model to string type, updating the controller methods to accept string type and modifying todo controller unit tests is a couple of minutes and all works fine with cloudant, including posting without an id and getting that back as a new cloudant doc id which successfully retrieves the item by id.

I think this is as it should be and saying id is a required field is fine in a unit testing sense for the application but should really fail UAT as in the real world we are effectively using this as CRUD interface for which inserting a record and retrieving a unique id back on success is a key requirement.

Also reading the openapi.json the id field seems only to be 'Required' when making a post to /todos/{id} not when posting to /todos although that maybe my misunderstanding of the openapi schema.

For a more OOTB solution perhaps we can look into how the connector exposes how it handles id fields and pass / inject the relevant  type to the model and tests as a variable, or a more hacky option of some conditional logic around typeof id.

I will put up a repo at some point but working live instance at time of writing is as before, currently unauthenticated so feel free to post: https://lb4.eu-gb.mybluemix.net/openapi.json

Breakfast first though :)

**Comment by cloudwheels** [comment]
In summary this works as expected with the id property on the todo model set as string and test updates.
ie.
- post /todos with no 'id' > get back a generated string uuid of the cloudant document (its internal _id field) 
- post with a string 'id' > cloudant sets that as the document id
- post the same string id > cloudant possible duplicate error
- post with a numeric id > type error, expects string

So I can 'force' the id field ion the database by default.
There is some reference to this in the [cloudant connector docs here](https://github.com/strongloop/loopback-connector-cloudant#force-id) which suggests best practice is to not force the id and rely on the generated document id as the object's key, as I had intended.

This obviously has implications:
- if I then wanted to use a sql connector which auto generated numeric ids it might be complicated, so perhaps true database agnosticity is not acheivable
- re-mapping existing related records to these ids
However, this is really just forcing my hand in aligning with a noSql persistence model (unique id per record/object instance across the whole repository) vs Sql's  tablePerModelPrototype.uniqueIdForInstancesAcrossThisTableOnly structure, which I think / hope is probably the right thing to do architecturally.

With the possible exception of my comment above:

> For a more OOTB solution perhaps we can look into how the connector exposes how it handles id fields and pass / inject the relevant type to the model and tests as a variable, or a more hacky option of some conditional logic around typeof id

This Issue is 'solved' but I think the todo example (deploy to IBM Cloud) and docs need updating as the cloudant connection does not currently work correctly in the example without the modifications above @dhmlau

**Comment by bajtos** [comment]
> > For a more OOTB solution perhaps we can look into how the connector exposes how it handles id fields and pass / inject the relevant type to the model and tests as a variable, or a more hacky option of some conditional logic around typeof id
>
> This Issue is 'solved' but I think the todo example (deploy to IBM Cloud) and docs (including best practice for non-sql vs. sql?) need updating as the cloudant connection does not IMHO currently work correctly in the example without the modifications above.

Makes sense to me :+1:

@cloudwheels Would you like to contribute this improvement yourself?
