### ISSUE TITLE
The key rest.apiSpec was not bound to any value.

### ISSUE THREAD

**Issue by basitsattar** [strongloop/loopback-next#2045]
Hi
Is it possible to make a multiple server application in current version of loopback? I have a usecase where I need to run a Rest Server with a websocket server. How can I do this? 

I am implementing another server and extending from Application class instead of rest class, but it says i need to provide ApiSpec? Would I do it with getControllerSpec()? and how to combine all controllers then? 

This is my application.ts code

```
import { BootMixin } from '@loopback/boot';
import { ApplicationConfig, Application } from '@loopback/core';
import { RepositoryMixin } from '@loopback/repository';
import { RestApplication, RestComponent, RestServer } from '@loopback/rest';
import { ServiceMixin } from '@loopback/service-proxy';
import { MySequence } from './sequence';
import * as path from 'path';
import { AuthenticationBindings, AuthenticationComponent } from '@loopback/authentication';
import { AuthStrategyProvider } from './providers/authStrategy';
export class ChatviserApplication extends BootMixin(
  ServiceMixin(RepositoryMixin(Application)),
) {
  constructor(options: ApplicationConfig = {}) {

    options = Object.assign(
      {},
      {
        components: [AuthenticationComponent, RestComponent],
        rest: {
          sequence: MySequence,
          apiSpec: {
            test: "test"
          }
        }
      },
      options
    );

    super(options);
    this.server(RestServer, "RestServer");

    // // Set up default home page
    // this.static('/', path.join(__dirname, '../../public'));

    this.projectRoot = __dirname;
    // Customize @loopback/boot Booter Conventions here
    this.bootOptions = {
      controllers: {
        // Customize ControllerBooter Conventions here
        dirs: ['controllers'],
        extensions: ['.controller.js'],
        nested: true,
      },
    };
  }

  async start() {
    const server = await this.getServer(RestServer);
    server
      .bind(AuthenticationBindings.STRATEGY)
      .toProvider(AuthStrategyProvider);
    await super.start();
  }
}
```

Help would be appreciated.

**Comment by bajtos** [comment]
> Is it possible to make a multiple server application in current version of loopback? 

It should be possible to have multiple servers in a single application. However, supporting multiple servers is tricky and we haven't looked into ways how to make this easy to achieve. You are likely to discover things that are difficult to achieve while building such an application.

> I have a usecase where I need to run a Rest Server with a websocket server.  How can I do this?

@raymondfeng has recently created an example app showing how to build a WebSocket server, see https://github.com/raymondfeng/loopback4-example-websocket

> I am implementing another server and extending from Application class instead of rest class, but it says i need to provide ApiSpec? Would I do it with getControllerSpec()? and how to combine all controllers then?

You need to add `RestComponent` to your application if you are not using `RestApplication`.

```
// ...
import {RestComponent} from '@loopback/rest';

export class ChatviserApplication extends BootMixin(
  ServiceMixin(RepositoryMixin(Application)),
) {
  constructor(options: ApplicationConfig = {}) {
    // ...
  
    this.component(RestComponent);
  }
}
```

Please note that we are no longer supporting `options.components` that you are using in your code snippet.
