### ISSUE TITLE
Forget todos and align all examples to building a store

### ISSUE THREAD

**Issue by cloudwheels** [strongloop/loopback-next#2049]
## Description / Steps to reproduce / Feature proposal
Current starter examples are based around the concept of todos and their relationships in todoLists.  No doubt chosen for the relative simplicity of the concept.

From my understanding of the roadmap and current activity, the aim is to primarily demonstrate the product's production-ready capabilities through a reference implementation of an e-commerce store api backend [shopping sample](https://github.com/strongloop/loopback4-example-shopping)?

IMHO it would make more sense to start the examples with say Products and Product Variations (Orders, OrderProducts etc) to align to this and progress through one project until I've build my store, Angular Heroes style. 

Then when I move on to the next step I'm authorising adding Products to an Order etc., not adding "buying milk" to my OAuth2 authenticated cloud-distributed todo list of my chosen colour. The.Real.World. LargeRedTShirt-SmallBlueTShirt. :)
.
This can be achieved quickly just by renaming Todo Product Variation and TodoList Product or whatever: 
I also think is actually is a genuine one-to-many relationship for exploring related models, whereas I would probably implement todos and lists as many-to-many from the start to cover use cases of sharing items between lists.

Thanks for listening.

**Comment by bajtos** [comment]
@cloudwheels thank you for the proposal. IIRC, we created `todo-list` because it was the simplest way how to get a working example for a has-many relation.

I like your proposal to use a somewhat more realistic scenario.

The tricky part is how to keep the example simple, so that people reading the code can quickly discover the relevant parts & understand what's just a boilerplate, and to keep the maintenance costs low.

So perhaps we should rename `examples/todo-list` to `examples/has-many`, to make it clear that this particular example is demonstrating has-many relation, and rework the domain model to show "Order has many OrderItem instances" relation.

@strongloop/loopback-maintainers thoughts?

@cloudwheels once we reach an agreement on the direction, would you like to contribute these changes yourself please?

**Comment by cloudwheels** [comment]
Previous comment reworked to try to get to grips with how docs & samples fit together and can be reworked now, and what the bigger picture might be longer term.

**Comment by cloudwheels** [comment]
Is the plan to lerna import the shopping example repo into loopback-next/examples? 

Also, semantics I know,  but "Shopping" or "Store"?, "Example" or "Tutorial"?

Actually this whole issue is really semantics: as with avoiding too much boilerplate cluttering an explanation of the concepts, does effectively telling the user, even though they almost certainly understand,  "So far in other examples, we've been calling these 'Todos', but now we're calling them 'Orders'- don't worry were talking about the same concept of child relations",  not just add an unnecessary thinking step vs just consistently calling them Orders across all examples?

It's also pretty low hanging fruit to make that change now vs 2 years of example building & tutorials later! 

I also understand talk is cheap: I personally am more than happy to work through regenerating the sample apps with different entity names (which but nature should be a smooth & rapid process!) and work on updating docs and links for my own education / contribution :)

The possible need to revise folder structure for tutorials / examples / how tos / concepts is closely linked to #1908.

**Comment by cloudwheels** [comment]
@virkt25 Yes, "Stepped tutorial" is the phrase I was looking for.
Each tutorial step being essentially as set of how-tos (which only exist as part of the tutorial referenced as linked headings/anchors), and a summary of the Key Concepts involved, under their own section as currently but using the language of a store in their supporting code snippets. (links not implemented and of course just rough idea of sample steps but should show the idea).

----------------------
#Step 1
Let's get started building our store by installing loopback and creating a controller   

**We'll learn how to:**
- [install the loopback cli an scaffold an app](#installing-loopback-cli)
- [create a model](#creating-a-model) for store customers add a simple controller to view and manage their data using our store api 
- serve a static home page for our store from the loopback app
The example should help you to understand about using these [key concepts](https://loopback.io/doc/en/lb4/Concepts.html) in your own application:
- [Application](https://loopback.io/doc/en/lb4/Application.html)
- [etc]

##Installing Loopback CLI
Do this and that

##Creating a loopback [Application](https://loopback.io/doc/en/lb4/Application.html)

##Creating a [Model](https://loopback.io/doc/en/lb4/Model.html)

##Creating a controller

##Serving static pages

----------------------

#Step 2
Let's move on with or store to do this that and the other....
**In the [previous step](#step1)** of our tutorial we:
**learnt how to:**
-  [install the loopback cli an scaffold an app](#installing-loopback-cli)
- [etc]
and learned about these [key concepts](https://loopback.io/doc/en/lb4/Concepts.html) in loopback:
 [Application](https://loopback.io/doc/en/lb4/Application.html), [etc]

**In this step** we'll create models for the products in our store and a shopping cart, then set up basic authentication so customers can sign in and manage their own orders.
 We're going to learn **how to...** Add a one to many relationship .etc.,
 so we understand the **concepts of...** [Repository] etc

##Adding One-to-many relations: Create a product list and user order list

##Adding Basic Authentication to the store with [@loopback/authentication]

etc.
