### ISSUE TITLE
Async tracing support to Juggler layer

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#207]
Add async tracing support/`ctx` propogation to the juggler layer so that `await repo.find()` also has reference to `ctx`.

## BLOCKED BY

 - https://github.com/strongloop/loopback-next/issues/537
 - https://github.com/strongloop/loopback-next/issues/209

**Comment by bajtos** [comment]
I think we should allow users to specify how to build `options` argument used by `DefaultCrudRepository` when invoking juggler's `PersistedModel` methods.

For example:

```ts
class DefaultCrudRepository {
  async findById(id: any) {
    return this.PersistedModel.findById(id, await this.getOptions());
  }
}

class ProductRepository extends DefaultCrudRepository {
  getOptions() {
    return { accessToken: await ctx.get(Authentication.CURRENT_ACCESS_TOKEN); }
  }
}
```
