### ISSUE TITLE
Deploy to IBM Cloud: make cloud deployment default & other changes

### ISSUE THREAD

**Issue by cloudwheels** [strongloop/loopback-next#2072]
## Description / Steps to reproduce / Feature proposal
I will put in a PR for this rather than waffling here if the thinking makes sense, but
*Assumes node (?version) & npm installed*
Needs (do you have?) + setup links 
*No link/explanation of installing lb4 CLI*
Pre-requirements should link to CLI install instructions as well as external tools 
*Point out this can all be done on Free Tier services*
PaaS offerings vary in needing credit cards, limits of service etc so point out this is nice and straightforward
*Make cloud deployment default option*
- The quickest way to get this sample deployed is to use a connection string to the same remote cloudant instance for both the local and deployed app (explanation of where to find credentials in the cloudant console needed) 
- Setting up docker if it's not already in your devenv can be problematic and takes the reader away from the example.
- With (my preferred) use case of anywhere with wifi-chomebook/browser-google cloud shell I can run this pure cloud / no local with that set up in a couple of minutes, running cloudant in docker on another port is possible but connecting to it not/problematic for security reasons (more time away from the example working out why...ooh look I'm getting back the google login page, what was I doing again...)
- Even with Docker ready to go, pulling the image also blocks the flow of the tutorial
- You do not "HAVE TO connect the database to an app on Cloud Foundry", it's better practice and can be explained why but we're running a sample and only related to IBM cloud not lb4, so optional once we've already got it up and running in the cloud.
- Ditto using a separate dev database locally: we can assume no mission critical data is being overwritten!

## Current Behavior
& 
## Expected Behavior
As described above.

**Comment by dhmlau** [comment]
@cloudwheels , thanks for your comment.  Actually after discussing with you on the [previous GitHub issue](https://github.com/strongloop/loopback-next/issues/2033), it's clear to me that there should be a progression on the instruction (first with simple LB4 app without using any provisioned services, then with provisioned services on IBM Cloud).  I was re-organizing my thoughts in this blog, trying to incorporate your comments before making changes to the docs: https://medium.com/@MobileDiana/deploy-your-first-loopback4-application-to-ibm-cloud-2e671ac06b6c. But please submit a PR! :)

**Comment by cloudwheels** [comment]
@dhmlau - the blog is great to show how quickly thing can be done!
As per the two issue references above I have created my own "reorganizing of thoughts place"
Within the context of that and [this MO](https://github.com/loopstore/loopstore-tutorial-v4/issues/8), as per my comment in [this](https://github.com/loopstore/loopstore-tutorial-v4/issues/9):
> Started on #9 on this google doc: (See #8 )
> https://docs.google.com/document/d/1y_HThLEerWrP6uSfiVvgAI08rKoXuMmHl2LHZL5R4R4
> 
> Please comment here to request edit permissions.
> 
> The online codelabs PREVIEW generated version which REQUIRES GOOGLE SIGN IN and is probably best viewed in chrome is here:
> https://codelabs-preview.appspot.com/?file_id=1y_HThLEerWrP6uSfiVvgAI08rKoXuMmHl2LHZL5R4R4#2
> 
> The formatting is not necessarily as per final output, which is configured by the claat tool when the output is built against it.

It's almost the opposite, a bit of a plod through the IBM set up in the browser! Still WIP but FYI

**Comment by cloudwheels** [comment]
@dhmlau 
There is a test build of the above (incomplete/not final formatted) content as a codelab hosted on the demo repo's GH Pages here:
[https://loopstore.github.io/loopstore-tutorial-v4/index.html](https://loopstore.github.io/loopstore-tutorial-v4/index.html)

**Comment by dhmlau** [comment]
@cloudwheels, thanks for sharing!

**Comment by dhmlau** [comment]
See PR https://github.com/strongloop/loopback-next/pull/3254.

**Comment by dhmlau** [comment]
PR #3254 has landed. Closing it as done.
