### ISSUE TITLE
[Spike] Reference a Model/type and add additional constraints

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2082]
**Timebox to 5 days**

## Description / Steps to reproduce / Feature proposal
Originated from: https://github.com/strongloop/loopback-next/issues/1722

During the discussion with @raymondfeng @bajtos, there were different discussion over the support for partial update, we think a spike is needed.  

## Acceptance Criteria
- [x] Read through the discussion and proposals listed in the related issues 
- [x] Build a prototype showing how it can be done
- [ ] Share the spike outcome
   - [x] Put the summary in this issue
   - [x] Host a spike meeting
   - [ ] Blog post proposing what to do and involve the community
   
## Related issues
- #1722
- #1179 
- #1470 
- #1719 
- #1894

**Comment by jannyHou** [comment]
Some notes during the estimation meeting:

Let's do the spike from a more general level, think of the big picture of customizing a model's shape, a few of points to be considered:

- how to customize the shape of model
- satisfy different requirements of property
- apply constraints
- apply validations
- given a model and properties defined in it, we may have particular expectation at the rest layer, data persistency layer, etc….come up with a general solution to satisfy different requirements.

**Comment by bajtos** [comment]
> - apply constraints
> - apply validations

Please read through the discussion in https://github.com/strongloop/loopback-next/issues/1624, it has many insights relevant for this area.

Personally, I'd prefer to narrow down the scope of this spike and stay focused on the two use cases , otherwise it may take ages to complete:
 - PATCH - all properties are optional,
 - CREATE - id and possibly _rev must not be present

**Comment by bajtos** [comment]
the proposal: https://github.com/strongloop/loopback-next/pull/2646

**Comment by bajtos** [comment]
>   Blog post proposing what to do and involve the community

As discussed with @dhmlau, we will provide a summary in the March milestone blog post.

Closing the spike as done 🎉
