### ISSUE TITLE
context: Unique tracing id per context instance

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#209]
# Description/Steps to reproduce

See the discussion in #188

> @raymondfeng 
> Each instance of Context should have a unique id for tracing purposes.
> @bajtos
> How do you propose to generate that unique id? Should we just increase a number, or should we use uuid?
> @raymondfeng 
> I think uuid is good enough. We should also check out http://opentracing.io/documentation/.

**Comment by kesavkolla** [comment]
support for opentracion would be really great.  In that case the context should be propagated to all layers like services and repositories.  That way we can co-relate all the requests together.

**Comment by dhmlau** [comment]
Closing it as it's been resolved.
