### ISSUE TITLE
[Docs] Review and modify content in Controllers page 

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2099]
## Description / Steps to reproduce / Feature proposal
Originated from the docs cleanup epic: https://github.com/strongloop/loopback-next/issues/1908

Under Key Concepts > [Controller page](https://loopback.io/doc/en/lb4/Controllers.html#review-questions), there is a section of "Review Questions" which seem to be notes reminding what to add / modify in the future.  We should clean it up. 

### Review questions

- Simplest possible example of a Controller
  - app.controller()
  - a few methods
  - no usage of @api

- How to create a basic Controller (beyond the hello world)
  - Using DI (@inject)
  - Using decorators (eg. @authenticate)
  - Defining routes via sugar annoations (@get, @post)
  - Errors
  - Using async / await and Promises

## Acceptance Criteria
- [x] Review the [review questions section](https://loopback.io/doc/en/lb4/Controllers.html#review-questions) of the Controllers page
- [x] for items that are applicable, add / remove / update content accordingly.

**Comment by jannyHou** [comment]
Document the flow of creating a controller from running `lb4 controller`, incrementally add pieces of the rest apis
- run `lb4 controller` to create the controller class
- create business function
- decorate it with rest decorators
- inject services
- boot script will automatically load the controller
  - For `app.controller()`, if you want to customize the controller registration, it would be the api you can call.

Start with the simplest use case(create a controller by cli), then introduce customization approaches when the scenario turns to be more complicated.

**Comment by jannyHou** [comment]
Stretch goal: 
- We could visualize the controller concept (an example would be the nestjs doc) in a diagram.

**Comment by dhmlau** [comment]
Adding the `Review questions` from https://loopback.io/doc/en/lb4/Controllers.html#review-questions:
- Simplest possible example of a Controller
  - app.controller()
  - a few methods
  - no usage of @api

- How to create a basic Controller (beyond the hello world)
  - Using DI (@inject)
  - Using decorators (eg. @authenticate)
  - Defining routes via sugar annoations (@get, @post)
  - Errors
  - Using async / await and Promises

**Comment by nabdelgadir** [comment]
Review questions were removed as part of https://github.com/strongloop/loopback-next/pull/2376
