### ISSUE TITLE
[Docs] "Testing your application" page contains beta release information

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2101]
## Description / Steps to reproduce / Feature proposal
Originated from the docs cleanup spike: https://github.com/strongloop/loopback-next/issues/1908

The ["Testing your application" page](https://loopback.io/doc/en/lb4/Testing-your-application.html) seems to be outdated.  
- ["Create a stub service" section](https://loopback.io/doc/en/lb4/Testing-your-application.html#create-a-stub-service)
   - a WIP note
   - "The initial beta release does not include Services as a first-class feature." <-- we are no longer in beta release. This should be updated. 
- ["Perform an auto-generated smoke test of your REST API" section ](https://loopback.io/doc/en/lb4/Testing-your-application.html#perform-an-auto-generated-smoke-test-of-your-rest-api)
  - it says "It will be revisited after our MVP release".  

@bajtos, I don't have enough knowledge in this area to have a more complete acceptance criteria.  It seems like this page needs to be reviewed more thoroughly, rather than just catching the obvious. Thanks.

**Comment by bajtos** [comment]
> "Create a stub service" section

IMO, we should add content to this section, using "Create a stub Repository" for inspiration and  https://github.com/strongloop/loopback-next/pull/1347/commits/7ceb2c4edebcbcee5501a69c42c61f8ff2e2d675 for an example code.

> "Perform an auto-generated smoke test of your REST API" section
> it says "It will be revisited after our MVP release".

Let's modify the warning. Design-first approach is out of scope of 2018Q1, I think we need to use a warning that will work for longer term.

Very loosely related: https://github.com/strongloop/loopback-next/issues/644 _A better tool for automated API smoke tests_

**Comment by jannyHou** [comment]
Thanks @dhmlau and @bajtos according to the discussion the acceptance criteria would be:

Acceptance criteria:

- [ ] Add content to "Create a stub Repository"
  - using "Create a stub Repository" for inspiration and [7ceb2c4](https://github.com/strongloop/loopback-next/commit/7ceb2c4edebcbcee5501a69c42c61f8ff2e2d675) for an example code.
- [ ] Add warning to ""Perform an auto-generated smoke test of your REST API" section"
  - Let's modify the warning. Design-first approach is out of scope of 2018Q1, I think we need to use a warning that will work for longer term.

**Comment by bajtos** [comment]
> Add content to "Create a stub Repository"
> using "Create a stub Repository" for inspiration and 7ceb2c4 for an example code.

See also https://github.com/strongloop/loopback-next/issues/2185
