### ISSUE TITLE
 Endpoints continue to work even after deleting controller files

### ISSUE THREAD

**Issue by uptickr** [strongloop/loopback-next#2105]
## Description / Steps to reproduce / Feature proposal

Endpoints continue to work even after deleting the corresponding .controller.ts file

Create a controller as described in the Getting Started section. Then delete the .controller.ts file.

## Current Behavior

Endpoint works even after removing files.

## Expected Behavior

Should return 404 - Not Found

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
You should run `npm run clean && npm run build` to remove js files from `dist`

**Comment by uptickr** [comment]
Thanks. I got it. I was using npm start. Changing the start script to npm clean && node . fixes it for development.
