### ISSUE TITLE
build watch while in development with nodemon

### ISSUE THREAD

**Issue by ringodotnl** [strongloop/loopback-next#2107]
## Description / Steps to reproduce / Feature proposal
Trying to get a watch mode with lb4 while developing with:
"start:dev": "concurrently \"npm run build:watch\" \"nodemon .\"",

## Current Behavior
After cmd: npm run start:dev
Updated ts code is not active

## Expected Behavior
Updated ts code should be active

**Comment by bajtos** [comment]
Closing as a duplicate of #2242.
