### ISSUE TITLE
Use AST instead of ejs templates for generators

### ISSUE THREAD

**Issue by codejamninja** [strongloop/loopback-next#2113]
I think it would be better to generate code from an abstract syntax tree rather than using templates.

In the past, I have found the `@babel/generator` to be a solid choice for generating code from AST, however, that would not work for typescript. Perhaps, the `getTextOfNode()` method in the typescript compiler utilities would do the job. 

https://github.com/Microsoft/TypeScript/blob/aa3734c14834afb454c49bc956489980d990a765/src/compiler/utilities.ts#L503

This is definitely a much more flexible approach because it conforms to the user's style of choice. It also allows for dynamically modifying existing files without the huge risk of destroying code.

**Comment by codejamninja** [comment]
I build a project that should make it easy to reason with AST for code generation.

https://github.com/codejamninja/react-ast

**Comment by deepakrkris** [comment]
looks like this issue was covered, mostly with https://github.com/strongloop/loopback-next/pull/2426 , closing now, please open a new issue for additional topics.
