### ISSUE TITLE
Relation repositories don't have direct access to foreign key value

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#2114]
_Originally posted by @bajtos in https://github.com/strongloop/loopback-next/pull/2005/files#r237517294

`HasOneRepository` and `HasManyRepository` don't have direct access to the foreign key value to throw meaningful errors (e.g. `EntityNotFoundError`) with it. Currently `get()` and `find()` for these repositories could benefit from having access to it, but there are other methods as well.

**Comment by dhmlau** [comment]
@b-admike, is this still needed?  If yes, could you please add the acceptance criteria? Thanks.

**Comment by bajtos** [comment]
Here is the issue: when a relation method is trying to access a related model instance and no instance with the foreign key was found, we want to throw a helpful `EntityNotFoundError`. The constructor of `EntityNotFoundError` requires entity id as an argument, the code in relation repositories does not have the id at hand, only a constraint like `{[foreignKey]: value}`. It would be great to find a better solution. For example, we can extend `EntityNotFoundError` to accept either id (as now) or a constraint (a `where` filter) too.
