### ISSUE TITLE
Question: Loopback4 and API Connect

### ISSUE THREAD

**Issue by mbhassan** [strongloop/loopback-next#2116]
## Description / Steps to reproduce / Feature proposal
Are we going to be having APIConnect in LP4?

## Current Behavior
Working well in LP3.

## Expected Behavior
Not sure if it will be in LP4.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@mbhassan , not sure if I understand your question correctly.  Do you mean the `apic loopback` commands we had in LB3? https://loopback.io/doc/en/lb3/Command-line-tools.html.  Do you mind sharing what your use case?

For the other way round, we do have plans to have LB4 added to APIC (2019.x, not v5) CLI.

**Comment by dhmlau** [comment]
@mbhassan, if you're starting off fresh, I'd suggest you consider LB4.  APIs generated by LB4 can be consumed in APIC as well.  One caveat that I can see is there is a gap in the model relation (https://github.com/strongloop/loopback-next/issues/1450).  We're collecting feedback from the community to see which relations are more popular to bring it back and any interested contributors as well. 

cc @raymondfeng @jjtang1

**Comment by dhmlau** [comment]
@mbhassan, with the [above comment](https://github.com/strongloop/loopback-next/issues/2116#issuecomment-445377372), is this issue good to close?  Thanks.

**Comment by mbhassan** [comment]
yep :) ! Thanks for the advice!
