### ISSUE TITLE
belongsToMany relation to model of the same type fails

### ISSUE THREAD

**Issue by hvlawren** [strongloop/loopback-next#2118]
From discussion on #1571

## Description
I have a model called Category with a parentId field that points to the parent Category

Category Model:
```
export class Category extends Entity {
  @property({
    type: 'number',
    id: true,
    generated: true
  })
  id?: number;

  @belongsTo(() => Category)
  parentId: number;

  @belongsTo(() => Domain)
  containerId: number;

  @property({
    type: 'boolean',
    default: false,
  })
  internal?: boolean;

  @property({
    type: 'string',
    required: true,
  })
  title: string;

  @property({
    type: 'string',
  })
  description?: string;

  @property({
    type: 'string',
  })
  state?: string;

  constructor(data?: Partial<Category>) {
    super(data);
  }
}
```

I created a /categories/{id}/parent endpoint per the docs

When I call that endpoint I get this error:

```
Unhandled error in GET /categories/2/parent: 500 Error: Circular dependency detected: controllers.CategoryParentController --> @CategoryParentController.constructor[0] --> repositories.CategoryRepository --> @CategoryRepository.constructor[2] --> repositories.CategoryRepository
```

Category Parent Controller:

```
export class CategoryParentController {
  constructor(@repository(CategoryRepository) protected categoryRepository: CategoryRepository) { }
  @get('/categories/{id}/parent')
  async getCustomer(
    @param.path.number('id') id: number,
  ): Promise<Category> {
    return await this.categoryRepository.parent(id);
  }
}
```

Category Repository

```
export class CategoryRepository extends DefaultCrudRepository<
  Category,
  typeof Category.prototype.id
> {
  public readonly container: BelongsToAccessor<Domain, number>;
  public readonly parent: BelongsToAccessor<Category, number>;
  constructor(
    @inject('datasources.db') dataSource: DbDataSource,
    @repository.getter(DomainRepository)
    protected domainRepositoryGetter: Getter<DomainRepository>,
    @repository.getter(CategoryRepository)
    protected categoryRepositoryGetter: Getter<CategoryRepository>
  ) {
    super(Category, dataSource);
    this.container = this._createBelongsToAccessorFor('container', domainRepositoryGetter);
    this.parent = this._createBelongsToAccessorFor('parent', categoryRepositoryGetter);
  }
}
```

Note that the container part works as expected, only parent is broken.

**Comment by hvlawren** [comment]
That fixed it!

I'd say those two places probably make the most sense.

I've got a lot on my plate right now, so I'd suggest someone else add the docs.

**Comment by bajtos** [comment]
> That fixed it!

Great! 🎉 

> I'd say those two places probably make the most sense.
>
> I've got a lot on my plate right now, so I'd suggest someone else add the docs.

We all have a lot on our plates, don't we? 😉 

It would be great if you could find some time later to contribute back, but I will understand if you don't.

Let's keep this issue open, I think it's a good opportunity for new contributors.

**Comment by vvdwivedi** [comment]
Well, I am sniffing around for good first issues. Will take this up.

**Comment by haotangio** [comment]
Hello.
I make a PR to update document for this issue: https://github.com/strongloop/loopback-next/pull/2196
Please help me check it.

**Comment by mmeilby** [comment]
I just realized that if the above CategoryRepository has a hasMany relation to DocumentRepository and DocumentRepository has a belongsTo relation to CategoryRepository then you get a circular dependency error.
What should be done in this case as the Getter.fromValue(this) isnt really usefull here?

**Comment by SebastianDaehnrich** [comment]
@mmeilby: do you found a solution for the case

**Comment by mmeilby** [comment]
> @mmeilby: do you found a solution for the case

Well, yes, however the problem seems not to exist anymore. At least for the version I am using now.

The solution in May was to add this line before the repository class definition:
`@bind({scope: BindingScope.SINGLETON})
export class SomeRepository extends DefaultTransactionalRepository ...`
