### ISSUE TITLE
Calling other APIs (docs) is missing datasource binding example

### ISSUE THREAD

**Issue by loredanacirstea** [strongloop/loopback-next#2121]
## Description / Steps to reproduce / Feature proposal

I was trying to follow the steps from https://github.com/strongloop/loopback-next/blob/1016a09f707ad54eb08de0d33d8a1ce7ecca1f59/docs/site/Calling-other-APIs-and-Web-Services.md up until https://github.com/strongloop/loopback-next/blob/1016a09f707ad54eb08de0d33d8a1ce7ecca1f59/docs/site/Calling-other-APIs-and-Web-Services.md#get-an-instance-of-your-controller.

My example fas failing with `The key datasources.myApiDatasource was not bound to any value.`

I then found an example in your tests: https://github.com/strongloop/loopback-next/blob/8499862ed7bbb615d8bcdf2c2590fcdfaa624e8f/packages/service-proxy/test/unit/decorators/service-proxy.decorator.unit.ts#L38 that shows where you need to bind the datasource. This should be added to the docs.

**Comment by dhmlau** [comment]
@loredanacirstea, thanks for reporting this.  Are you interested in submitting a PR?  Thanks.

**Comment by dhmlau** [comment]
@loredanacirstea, we've improved our docs on the `Calling other APIs and web services` page https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html.  If you see other issue, please feel free to open a new GitHub issue. Thanks.
