### ISSUE TITLE
Update "Calling other APIs and web services" doc

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#2128]
## Description / Steps to reproduce / Feature proposal

The current "[Calling other APIs and web services](https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html)" doc is outdated. It has to be updated to use the latest conventions (CLI and code) to allow users to make requests to third-party backends.
 
## Acceptance Criteria

- [ ] Describe the steps for setting up an interface for making calls to third-party services
- [ ] Demonstrate how to re-expose a third-party REST service as a REST service in LB4
- [ ] Demonstrate how to expose a non-REST third-party service as a REST service in LB4

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
#2128 and #1766 are about the same docs page.  @nabdelgadir , could you please take a look and see if there are duplicate requirements and whether we can close one and continue the discussion on one of them?  Thanks.

**Comment by dhmlau** [comment]
I believe my PR https://github.com/strongloop/loopback-next/pull/2588 has covered that. Closing as done. Thanks.
