### ISSUE TITLE
Debugger not working correctly 80% of the time, even when there is no process on port. 

### ISSUE THREAD

**Issue by Kelvijn** [strongloop/loopback-next#2138]
```js
{
  "version": "0.2.0",
  "configurations": [{
    "type": "node",
    "request": "launch",
    "name": "Launch via NPM",
    "runtimeExecutable": "npm",
    "runtimeArgs": [
      "run-script",
      "debug"
    ],
    "port": 9229
  }]
}
```

Debugger worked fine before, reinstalled vscode and extensions. Restarted pc. Can't find a solution.
Just like any other day for the past couple of weeks I was developing a Loopback 4 app. Sometimes i would get this error but restarting my pc always worked. 
How to reproduce: Debug -> start debugging 

**OS**
windows 10 home

**VSCODE VERSION**
C:\Users\Calvin Swinnen>code --version
1.29.1
bc24f98b5f70467bc689abf41cc5550ca637088e
x64

**INSTALLED EXTENSIONS**
C:\Users\Calvin Swinnen>code --list-extensions
dracula-theme.theme-dracula
Equinusocio.vsc-material-theme
HookyQR.beautify
Mikael.Angular-BeastCode
robertohuertasm.vscode-icons
zhuangtongfa.Material-theme

**package.json scripts**
    "prestart": "npm run build",
    "start": "node .",
    "predebug": "npm run build",
    "debug": "node --nolazy --inspect-brk=9229 ."

**Comment by raymondfeng** [comment]
Can you elaborate the issue? What error messages do you see?

**Comment by Kelvijn** [comment]
![image](https://user-images.githubusercontent.com/24386111/49757648-3dc2df80-fcbd-11e8-8dd6-d1d731813920.png)

` "prestart": "npm run build",
    "start": "node .",
    "predebug": "npm run build",
    "debug": "node --nolazy --inspect-brk=9229 ."`

**Comment by yshing** [comment]
@Kelvijn You doesn't seems to have your VScode `launch.json` properly configured.
`runtimeExecutable` should not be `npm` and you don't need to configure that.
Just need to provide file to he JS entry point as `program`
e.g.
```
{
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceFolder}/app.js",
}
```
https://code.visualstudio.com/docs/editor/debugging#_launch-configurations.

Another reason might be the `predebug` script got run before `debug` script. And it's taking more than 10s to run. Hence, try remove the line `"predebug": "npm run build",` from package.json ?

**Comment by Kelvijn** [comment]
https://stackoverflow.com/questions/53740604/loopback-4-debugger-nodemon-solution

found a solution
