### ISSUE TITLE
How to pass null value to number field

### ISSUE THREAD

**Issue by anandrajputSF** [strongloop/loopback-next#2141]
## Description / Steps to reproduce / Feature proposal
How To pass null value to number field through Loopback4.
## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
Hi @anandrajputSF, what have you tried so far and what was the result?

Please create a small application showing what you are trying to do (see our [bug reporting instructions](https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs)) and also tell us what HTTP request you are making to when passing a `null` value.
