### ISSUE TITLE
lb4 specifying table name

### ISSUE THREAD

**Issue by rexliu0715** [strongloop/loopback-next#2145]
my existing database table name "foo_bar". I generate a model "fooBar". 

500 error: relation "schema.foobar" does not exist

where I can define the tablename? I does see reference on doc in lb4. please help. thanks

**Comment by bajtos** [comment]
See also https://github.com/strongloop/loopback-next/issues/2134.

**Comment by bajtos** [comment]
Closing as a duplicate of #2134.
