### ISSUE TITLE
[CLI] Use a custom Repository base class

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2149]
Application developers invoking `lb4 repository` should be able to specify a custom Repository class to inherit from. This repository can be defined in a 3rd-party extension or inside the application project.

At minimum, the CLI should accept custom class name (+ import path?):
 - via an interactive prompt
 - via CLI options
 - via JSON config

Even better, there should be a mechanism allowing extensions (npm packages) and applications to define custom Repository implementations in such way that `lb4 repository` can pick them and create a list of available repositories for the CLI user to pick from.

See also https://github.com/strongloop/loopback-next/issues/2095#issuecomment-446182948

**Comment by gczobel-f5** [comment]
@bajtos Hi, I started to work on this issue and I'm preparing a PR.
I have a question that raised looking on the tests.
Looks that there is an assumption that providing --datasource parameter, is enough to infer the Base repository. So a KV db used DefaultKeyValueRepository.

What will be the expected result when the DS type does not match with the base repository provided as an argument? Remember that at this moment we are looking only to filenames and not the file contents.

**Comment by dhmlau** [comment]
@gczobel-f5 , saw your PR https://github.com/strongloop/loopback-next/pulls, so I'm assigning this task to you.  Thanks.

**Comment by dhmlau** [comment]
PR https://github.com/strongloop/loopback-next/pull/2235
