### ISSUE TITLE
Polymorphism of entities

### ISSUE THREAD

**Issue by JakubMifek** [strongloop/loopback-next#2151]
Hi,
I came across an issue. I need two models (B, C) that extend a parent model (A). I'd like to create instances of Bs and Cs and store them as As in my database for queries later on.

## Steps to reproduce
jakub@Marvin:~/Projects$ lb4 bug
? Project description: bug
? Project root directory: bug
? Application class name: BugApplication
? Select features to enable in the project Enable tslint, Enable prettier, Enable mocha, Enable loopbackBuild, Enable vscode, Enable repositories, Enable services
   create .npmrc
   create .prettierignore
   create .prettierrc
   create DEVELOPING.md
   create README.md
   create index.ts
   create package.json
   create tsconfig.json
   create tslint.build.json
   create tslint.json
   create .vscode/settings.json
   create .vscode/tasks.json
   create test/mocha.opts
   create .gitignore
   create index.js
   create public/index.html
   create src/application.ts
   create src/index.ts
   create src/sequence.ts
   create test/README.md
   create src/controllers/README.md
   create src/controllers/index.ts
   create src/controllers/ping.controller.ts
   create src/datasources/README.md
   create src/models/README.md
   create src/repositories/README.md
   create test/acceptance/home-page.acceptance.ts
   create test/acceptance/ping.controller.acceptance.ts
   create test/acceptance/test-helper.ts
npm WARN deprecated text-encoding@0.6.4: no longer maintained
npm WARN bug@1.0.0 No license field.

added 527 packages from 1366 contributors and audited 3224 packages in 29.977s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

Application bug was created in bug.

Next steps:

$ cd bug
$ npm start

jakub@Marvin:~/Projects$ cd bug
jakub@Marvin:~/Projects/bug$ lb4 model
? Model class name: A
? Please select the model base class Entity
Let's add a property to A
Enter an empty property name when done

? Enter the property name: id
? Property type: number
? Is id the ID property? Yes
? Is it required?: Yes
? Default value [leave blank for none]: 

Let's add another property to A
Enter an empty property name when done

? Enter the property name: a
? Property type: string
? Is a the ID property? No
? Is it required?: Yes
? Default value [leave blank for none]: 

Let's add another property to A
Enter an empty property name when done

? Enter the property name: 
   create src/models/a.model.ts
   update src/models/index.ts

Model A was created in src/models/

jakub@Marvin:~/Projects/bug$ vim src/models/a.model.ts 

> Here I made sure that A is not strict

jakub@Marvin:~/Projects/bug$ lb4 model
? Model class name: B
? Please select the model base class A
Let's add a property to B
Enter an empty property name when done

? Enter the property name: b
? Property type: string
? Is b the ID property? No
? Is it required?: Yes
? Default value [leave blank for none]: 

Let's add another property to B
Enter an empty property name when done

? Enter the property name: 
   create src/models/b.model.ts
   update src/models/index.ts

Model B was created in src/models/

jakub@Marvin:~/Projects/bug$ lb4 model
? Model class name: C
? Please select the model base class A
Let's add a property to C
Enter an empty property name when done

? Enter the property name: c
? Property type: string
? Is c the ID property? No
? Is it required?: Yes
? Default value [leave blank for none]: 

Let's add another property to C
Enter an empty property name when done

? Enter the property name: 
   create src/models/c.model.ts
   update src/models/index.ts

Model C was created in src/models/

jakub@Marvin:~/Projects/bug$ lb4 datasource
? Datasource name: db
? Select the connector for db: In-memory db (supported by StrongLoop)
? window.localStorage key to use for persistence (browser only): 
? Full path to file for persistence (server only): 
   create src/datasources/db.datasource.json
   create src/datasources/db.datasource.ts
npm WARN bug@1.0.0 No license field.

\+ memory@0.0.3
added 1 package from 1 contributor and audited 3225 packages in 6.598s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
   update src/datasources/index.ts

Datasource db was created in src/datasources/

jakub@Marvin:~/Projects/bug$ lb4 repository
? Please select the datasource DbDatasource
? Select the model(s) you want to generate a repository A
   create src/repositories/a.repository.ts
   update src/repositories/index.ts

Repository A was created in src/repositories/

jakub@Marvin:~/Projects/bug$ lb4 controller
? Controller class name: B
? What kind of controller would you like to generate? REST Controller with CRUD functions
? What is the name of the model to use with this CRUD repository? B
? What is the name of your CRUD repository? ARepository
? What is the type of your ID? number
? What is the base HTTP path name of the CRUD operations? /bs
   create src/controllers/b.controller.ts
   update src/controllers/index.ts

Controller B was created in src/controllers/
jakub@Marvin:~/Projects/bug$ vim src/controllers/b.controller.ts

> Here I remove all GET methods and change POST method to:
```
  @post('/bs', {
    responses: {
      '200': {
        description: 'B model instance',
        content: {'application/json': {schema: {'x-ts-type': B}}},
      },
    },
  })
  async create(@requestBody() b: B): Promise<B> {
    return await this.aRepository.create(b) as B;
  }
```

jakub@Marvin:~/Projects/bug$ lb4 controller
? Controller class name: A
? What kind of controller would you like to generate? REST Controller with CRUD functions
? What is the name of the model to use with this CRUD repository? A
? What is the name of your CRUD repository? ARepository
? What is the type of your ID? number
? What is the base HTTP path name of the CRUD operations? /as
   create src/controllers/a.controller.ts
   update src/controllers/index.ts

Controller A was created in src/controllers/

> From this controller I remove the post method (A is abstract).

## Current Behavior vs. Expected Behavior
When start the application using `npm start` and open API explorer, POST methods for B and C expect A model instead of B and C respectively.

![image](https://user-images.githubusercontent.com/8631346/49958560-7bb54300-ff0b-11e8-87c0-9a5ef091fe70.png)

The interesting part is that this issue appears only ***after A controller addition*** but doesn't disappear after A controller removal.

I managed to get around this issue with ***removal*** (rename didn't help) of all models and recreation with A named ZA. Which leads me to conclusion that there is an issue in model search which goes in lexicographical order and takes first model that fits. And for some reason renaming does not do the trick. Swapping lines in index.ts didn't help.

Any ideas?

Thanks.

**Comment by bajtos** [comment]
Hi @JakubMifek, thank you for reporting the problem. Could you please create a small application reproducing the issue, so that we don't have to follow your long steps-to-reproduce ourselves? See https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs.
