### ISSUE TITLE
More than one app can listen on the same port

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#2155]
## Description / Steps to reproduce / Feature proposal

This may be a behavior from the underlying `net` Node.js module, but leads to unexpected behaviors. Three different apps can be run on the same host listening on the same port, if they use the `host` values `localhost`, `127.0.0.1`, and `::1`. I haven't tried but, `0.0.0.0` might make it possible to run a  fourth app, as well.

## Current Behavior

App starts successfully if the `host`:`port` combo is unique.

## Expected Behavior

Check if something is already listening on the same port on "localhost" and refuse to start if it is.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by gms1** [comment]
It should be quite possible that different apps (or the same app) are listening on different network interfaces (e.g 127.0.0.1, 127.0.0.2 and ::1) using the same tcp port. 
Binding to '0.0.0.0' (aka 'any') should of course conflict with all other ipv4 addesses like '127.0.0.1', but not with any ipv6 addresses like '::0'.
hm, 'localhost' depends on the configuration ... In any case the operating system is responsible for preventing different processes to be bound to the same socket address ( as long as the socket option 'SO_REUSEPORT' is not in use, which is likely the case for the 'http' node module ). What address are you seeing, if you try to ping 'localhost'?

**Comment by hacksparrow** [comment]
`ping` resolves "localhost" as `127.0.0.1`.

**Comment by bajtos** [comment]
I think this issue does not really belong to LoopBack, the behavior is coming from Node.js core. I am going to close this issue, feel free to continue the discussion in the issue tracker of Node.js.
