### ISSUE TITLE
`@loopback/testlab` is not working due to usage of `sinon` which is having a dependency problem itself

### ISSUE THREAD

**Issue by haotcdgroup** [strongloop/loopback-next#2158]
## Description / Steps to reproduce / Feature proposal
Related issues:
#1812 
https://github.com/sinonjs/nise/issues/66

Currently testlab is using "sinon": "^6.3.4"
Seem like we can upgrade to "sinon": "^7.2.2" to fix the issue (while still having `deprecated text-encoding@0.6.4: no longer maintained` warning)

## Current Behavior
Every package using "@loopback/testlab": "^1.0.2" or previous versions cannot get testing work due to https://github.com/sinonjs/nise/issues/66 issue

## Expected Behavior
Testing using `@loopback/testlab` should work

- Do a quick search to avoid duplicate issues: 
#1812
https://github.com/sinonjs/nise/issues/66

**Comment by dhmlau** [comment]
@nabdelgadir, could you please take a look? Thanks.
