### ISSUE TITLE
Loopback CLI depends on "loopback" keyword being present in package.json

### ISSUE THREAD

**Issue by dericgw** [strongloop/loopback-next#2163]
I removed the `keywords` section of my `package.json` and the next time I ran `lb4 model`, I received this error: 

```
Generation is aborted: Error: No `loopback` keyword found in /Users/dcain/Code/meal-api/package.json. The command must be run in a LoopBack project.
```

I add "loopback" as a keyword in my `package.json` and the problem goes away. I see [here](https://github.com/strongloop/loopback-next/blob/0a42541143636208832207669c0a2c36b7c9c1de/packages/cli/lib/base-generator.js#L326) that this is to make sure that we are in a loopback project.

I mean, this is an approach that possibly works, but it does feel kinda weird to have to keep the "loopback" keyword in my package.json. Instead, why don't we check the `dependencies` for a loopback package? Right below the code in the link above, the dependencies are parsed so it would be easy to look there. Or, what happens if we just skip that check? Is it really needed?

**Comment by raymondfeng** [comment]
@dericgw It's a protective check to make sure the command is running inside a valid LoopBack 4 project. I'm open to use other metadata such as dependencies in `package.json`. Are you willing to contribute a patch?

**Comment by dericgw** [comment]
I don't mind doing that. Do you think `@loopback/core` is the best package to depend upon? Or, should the CLI just look and see if any `@loopback` packages are available?

**Comment by shubhamp-sf** [comment]
@dericcain In case of extensions created with `lb4 extension` this still throws error, as in case of extensions `@loopback/core` is in `devDependencies` not `dependencies`.

![image](https://user-images.githubusercontent.com/110156023/192948440-c3050f4e-ccee-444b-9cc2-267b8204f7df.png)

**Comment by benjaminrae** [comment]
> @dericcain In case of extensions created with `lb4 extension` this still throws error, as in case of extensions `@loopback/core` is in `devDependencies` not `dependencies`.
> 
> ![image](https://user-images.githubusercontent.com/110156023/192948440-c3050f4e-ccee-444b-9cc2-267b8204f7df.png)

Is this the intented behaviour?

**Comment by benjaminrae** [comment]
@shubhamp-sf or peerDeps, `@loopback/core` is also included in peerDeps when you create an extension with `lb4 extension`

**Comment by benjaminrae** [comment]
@shubhamp-sf created #9476
