### ISSUE TITLE
Loopback 4, querying with SQLQuery with postgres connector

### ISSUE THREAD

**Issue by vishalvisd** [strongloop/loopback-next#2165]
# Description/Steps to reproduce

This is how I have defined my repository following very generic example given at loopback documentation:-
```

import {DefaultCrudRepository, juggler} from '@loopback/repository';
import {AModel} from '../models';
import {TimeseriesDataSource} from '../datasources';
import {inject} from '@loopback/core';

export class AModelRepository extends DefaultCrudRepository<
  AModel,
  typeof AModel.prototype.id
> {
  constructor(
    @inject('datasources.timeseries') dataSource: TimeseriesDataSource,
  ) {
    super(AModel, dataSource);
  }
}
```
I was hoping that if d`o AModelRepository.execute(sql, null, cb) i`t would work. But its giving error - `Error: Not implemented`

Any help is highly appreciated.

**Comment by shendkardevesh** [comment]
You can use and this worked for me.

this.dataSource.execute("select * from tbl_player", [])

**Comment by gregra81** [comment]
@bajtos This is great. When do you think it will be available in the lb4 official release?

**Comment by samarpanB** [comment]
I created a base repository class extending the DefaulCrudRepository and added an implementation for execute function which actually uses the datasource execute function to perform the task. Then, we used this new class as base repository class. This was a workaround until execute is implemented at repository level.
Here is the implementation

```
export abstract class AppDefaultCrudRepository<
  T extends Entity,
  ID
> extends DefaultCrudRepository<T, ID> {
  constructor(
    entityClass: typeof Entity & {
      prototype: T;
    },
    dataSource: MyDataSource,
  ) {
    super(entityClass, dataSource);
  }
  execute(
    command: Command,
    parameters: NamedParameters | PositionalParameters,
    options?: Options,
  ): Promise<AnyObject> {
    // Commented below statement until it is implemented 
    // return super.execute(command, parameters, options);
    return this.dataSource.execute(command, parameters, options);
  }
}
```

@bajtos do you think it is worthwhile to add this to DefaulCrudRepository as a workaround until it is implemented ? That ways, developers can use it with no breaking change in future.

**Comment by bajtos** [comment]
@samarpanB
> do you think it is worthwhile to add this to DefaulCrudRepository 

Yes please!

@gregra81 
> When do you think it will be available in the lb4 official release?

We are intentionally leaving this issue open because it's a great opportunity for new contributors. You are welcome to contribute the changes yourself, we are happy to help you along the way.

**Comment by samarpanB** [comment]
Okay @bajtos. I’ll generate a PR for this soon. Thanks.

**Comment by dhmlau** [comment]
@samarpanB, I'm assigning this task to you since you have the PR #2681.  Thanks.

**Comment by samarpanB** [comment]
No worries. Waiting for PR merge :). @bajtos
