### ISSUE TITLE
[Docs] Reorganize top level menu in docs

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2168]
Related to https://github.com/strongloop/loopback-next/issues/2087

Had a discussion with @bschrammIBM, her recommendation is to consolidate some of the top level menu in LB4 docs,  so that it's clearer to our users meaning: 

```
- Overview
- Examples & Tutorials
- Key concepts
- How-to
- Command-line interface
- Best Practices
- Extending LoopBack
- For LoopBack 3.x users
- Reference
```

More detailed recommendation for each section:

- [ ] Overview 
  - a new section which refers to https://loopback.io/doc/en/lb4/index.html page
  - it might be good to have a specific menu item for this "overview". 
  - we might be able to include some of the content in "Crafting in LB" for what's new in LB4 and rationale behind a new rewritten core. 

- [x] Examples & Tutorials
  - Remain unchanged
  - Make the distinction between examples and tutorials.  Discussed in https://github.com/strongloop/loopback-next/issues/2087.

- [x] Key concepts
   - Suggest to move [Reserved Binding keys](https://loopback.io/doc/en/lb4/Reserved-binding-keys.html) under [Dependency Injection](https://loopback.io/doc/en/lb4/Dependency-injection.html) 

- [ ] How-to
   - could rename to "usage guide" / remain unchanged / rename to something else.  Discussed in https://github.com/strongloop/loopback-next/issues/2087
   - Does [Calling other APIs](https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html) fall under this section? 

- [x] Command-line interface
   - no change

- [ ] Best Practices
    - Would it be better to group "Defining your testing strategy" and "Testing your application" under "Testing"? i.e. 
   ``` 
      Best Practices
          Defining the API
          Testing
               Defining your testing strategy
               Testing your application

   ```

- [ ] Extending LoopBack
  - Would "Booting an application" and "Using Components" fit under this section?

- [x] For current LoopBack users 
   - should rename it to "For LoopBack 3.x users" because current users should include 4.x users too.

- [ ] Reference
   - Can remove "glossory" because it's not a complete list and the Key Concepts section serves similar purpose

- [ ] "FAQ" and "Crafting LoopBack" - can consider to remove it
    - the content in FAQ does not look like what we normally see as FAQ.  Some content is outdated as well.
    - "Crafting LoopBack" - does not fit as part of the documentation.

**Comment by bschrammIBM** [comment]
Another reorganization suggestion is to move the Security Advisories onto the main menu on the https://loopback.io/doc/ home page. Right now the link is under LB3 only and it applies to othe releases (including LB4) https://loopback.io/doc/en/lb3/Security-advisories.html

**Comment by dhmlau** [comment]
Agree, since the security advisories are not specific to a particular version of LB.

**Comment by bajtos** [comment]
> Would it be better to group "Defining your testing strategy" and "Testing your application" under "Testing"?

👎 

In my experience, deeply nested trees are difficult to navigate. At the moment, "Best Practices" contains only three entries, that looks very reasonable to me, I don't see any need to move two of those two entries into a new sub-category. 

> Extending LoopBack
>
> Would "Booting an application" and "Using Components" fit under this section?

Not IMO. The section "Extending LoopBack" is for extension authors, i.e. people writing 3rd party modules to be used with LB4.

The pages "Booting an application" and "Using Components" are for application developers, i.e. people building REST API servers using LB4 and 3rd-party components.

**Comment by dhmlau** [comment]
The proposal in this PR https://github.com/strongloop/loopback-next/pull/3164 supersedes the proposed change here. Closing as duplicate.
