### ISSUE TITLE
Examples tsconfig filename resolution issue /w VSCode

### ISSUE THREAD

**Issue by dougal83** [strongloop/loopback-next#2175]
## Description / Steps to reproduce

1. Install any example via cli, e.g ''lb4 example todo-list''
2. Open folder in editor, e.g. VSCode
3. Trigger linter, e.g Open src/controllers/todo.controller.ts

(n.b. VSCode is only client tested)

## Current Behavior

Warns for example below (which is set via tsconfig.build.json):
[ts] Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

## Expected Behavior

The tsconfig rules to be applied correctly.  Renaming 'tsconfig.build.json' to 'tsconfig.json' resolves the config correctly in VSCode.

**Comment by dhmlau** [comment]
@nabdelgadir, could you please take a look? Thanks.
