### ISSUE TITLE
Update dependencies in loopback4-example-shopping automatically or periodically

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#2207]
## Description / Steps to reproduce / Feature proposal

When adding the JWT authentication strategy in `loopback4-example-shopping`, the dependencies in it are not updated for long time and the corresponding code update may take time(doing it now).

Since this is the standalone example application we actively maintain and adding features in, it's important to update its `@loopback/*` modules every time we do a new release.

I am thinking of setting up a github bot that automatically creates a new PR in `loopback4-example-shopping` as part of the release procedure in here. The PR contains only the dependency upgrading code, and we manually update the app if necessary.

## Current Behavior

The dependencies in loopback4-example-shopping is out of date

## Expected Behavior

We could use a bot that creates a dependency upgrade PR when a new version of `@loopback` is released.

**Comment by bajtos** [comment]
> Since this is the standalone example application we actively maintain and adding features in, it's important to update its @loopback/* modules every time we do a new release.

**Comment by dhmlau** [comment]
Related to https://github.com/strongloop/loopback-next/issues/2229

**Comment by dhmlau** [comment]
We've added greenkeeper via https://github.com/strongloop/loopback-next/issues/2229.  Is this issue good to close? Thanks.

**Comment by jannyHou** [comment]
Sorry for replying late 😞 Yeah it's good to close. And thanks for @bajtos 's suggestion!
