### ISSUE TITLE
mongodb aggregate ib4

### ISSUE THREAD

**Issue by johntom** [strongloop/loopback-next#2217]
## Description / Steps to reproduce / Feature proposal
In a recent issue https://github.com/strongloop/loopback-next/issues/2021, it was requested that a new issue be opened and since I did not see a new issue decided to create a new one. Plase let me know if this was unnecessary.
## Current Behavior
must execute api twice before getting aggregate results
## Expected Behavior
get data on first try

**Comment by johntom** [comment]
Found solution in https://github.com/strongloop/loopback-next/issues/2021
In my test, I clear out a collection and then rebuild with a loop through the aggregated data. Very Cool!
@get('/gymsaggregate', {
    responses: {
      '200': {
        description: 'Array of Gym model instances',
        content: {
          'application/json': {
            schema: { type: 'array', items: { 'x-ts-type': Gym } },
          },
        },
      },
    },
  })
  async finds(
    @param.query.object('filter', getFilterSchemaFor(Gym)) filter?: Filter,
  ): Promise<Gym[]> {
    if (!this.gymRepository.dataSource.connected) { await this.gymRepository.dataSource.connect(); }
    const gymCollection = (this.gymRepository.dataSource.connector as any).collection("Gym")
    let gc = await gymCollection
      .aggregate([
        {
          "$sort": {
            "Tenant": 1.0
          }
        },
        {
          $group: {
            "_id": {
              "tenant": "$Tenant",

              "month": {
                "$month": "$MessageLocalDateTime"
              },
              "year": {
                "$year": "$MessageLocalDateTime"
              },
              "CYM": "$CYM"

            },
          }
        },
        // { $skip: ((1 - 1) * 1) },
        // { $limit: 2 }
      ]).get();
    console.log('===================================')
    let obj = {}
    let objarray = []
    let ct = 0
    await this.gymaggregateRepository.deleteAll();
    for (const item of gc) {
      obj = { tenant: item._id.tenant, month: item._id.month, year: item._id.year, CYM: item._id.CYM };
      await this.gymaggregateRepository.create(obj);
    }
    return gc
  }

**Comment by sureshkodur** [comment]
Hi I found, 500 TypeError: Cannot read property 'settings' of undefined
at MongoDB.collectionName, while using the above query. I'm using
"loopback-connector-mongodb": "^4.1.0",
below is the code.

async create(
    @requestBody() loanClosingStatus: LoanClosingStatus[],
  ): Promise<any> {
    let repayments = await this.loanClosingStatusRepository.createAll(
      loanClosingStatus,
    );
    console.log('repayments', repayments);
    console.log(this.loanClosingStatusRepository.dataSource.connected); // false
    if (!this.loanClosingStatusRepository.dataSource.connected) {
      console.log('in if condition... initialization not complete');
      await this.loanClosingStatusRepository.dataSource.connect();
    }
    console.log(this.loanClosingStatusRepository.dataSource.connected); //true
    const _loanMappingCollection = (this.loanClosingStatusRepository.dataSource
      .connector as any).collection('LoanRequestMappings');  // it returns 500 error.

    console.log(_loanMappingCollection);
    const _loanRequestCollection = (this.loanClosingStatusRepository.dataSource
      .connector as any).collection('LoanRequests');
    let requestIDs = await _loanRequestCollection.find(
      {customerID: 'adasdasdasd'},
      {input_requestID: 1},
    );

    console.log('requestIDs:', requestIDs);

    let lmData = await _loanMappingCollection.aggregate([
      {
        $lookup: {
          from: 'LoanRequests',
          localField: 'RequestID',
          foreignField: 'input_requestID',
          as: 'AvailableLoanRequests',
        },
      },
      {$unwind: '$AvailableLoanRequests'},
      {
        $match: {
          $or: [
            {RequestID: '152216107695585237'},
            {RequestID: '152216076180212068'},
          ],
        },
      },
      {
        $lookup: {
          from: 'LoanClosingStatus',
          localField: 'LoanID',
          foreignField: 'LoanID',
          as: 'LoanRepayment',
        },
      },
      {$unwind: '$LoanRepayment'},
      {$project: {_id: 0}},
      {$out: 'tempData'},
    ]);

    console.log('lmData:', lmData);

    let paymentData = await this.getPayments(JSON.stringify(repayments));
    console.log('paymentData:', paymentData);
    return paymentData;
  }
code```

Error:
Unhandled error in POST /closingStatus: 500 TypeError: Cannot read property 'settings' of undefined
    at MongoDB.collectionName (/Volumes/Projects/WORKSPACE/suresh-koduri/loopback/excelrate-v2/node_modules/loopback-connector-mongodb/lib/mongodb.js:343:18)
    at LoanClosingStatusController.create (/Volumes/Projects/WORKSPACE/suresh-koduri/loopback/excelrate-v2/dist/controllers/loan-closing-status.controller.js:47:24)
    at value_promise_1.transformValueOrPromise.args (/Volumes/Projects/WORKSPACE/suresh-koduri/loopback/excelrate-v2/node_modules/@loopback/context/dist/resolver.js:208:41)
    at Object.transformValueOrPromise (/Volumes/Projects/WORKSPACE/suresh-koduri/loopback/excelrate-v2/node_modules/@loopback/context/dist/value-promise.js:227:16)
    at Object.invokeMethod (/Volumes/Projects/WORKSPACE/suresh-koduri/loopback/excelrate-v2/node_modules/@loopback/context/dist/resolver.js:203:28)
    at ControllerRoute.invokeHandler (/Volumes/Projects/WORKSPACE/suresh-koduri/loopback/excelrate-v2/node_modules/@loopback/rest/dist/router/controller-route.js:78:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Can any one help.
