### ISSUE TITLE
Compare speed between findById and findOne using primary key

### ISSUE THREAD

**Issue by hosiduy** [strongloop/loopback-next#2219]
## Description 
Hi Loopback team, 

For now, if I use function `findById` from `Entity` class, it will return error for not found case intead of returning null data. (I use mysql connector). So I need to use function `findOne` and using where statement with Id  `where: {id : idValue}` 

I wonder if the speed between 2 methods above for mysql database is the same. 
Do two queries above excuting the same query on database?

**Comment by bajtos** [comment]
@hosiduy 

> I wonder if the speed between 2 methods above for mysql database is the same.

Have you considered writing a small benchmark to verify the actual speed in your particular environment? You can take a look at our [benchmark](https://github.com/strongloop/loopback-next/tree/master/benchmark) package for inspiration, we use [autocannon](https://www.npmjs.com/package/autocannon) for measuring HTTP throughput. If you are concerned about the database side only, then you can call Repository APIs directly from JS/TS code and use e.g. [bench](https://www.npmjs.com/package/bench) to setup the benchmark.

> Do two queries above excuting the same query on database?

I believe so, but don't take my words and verify it yourself! Just run your application (or your test) with debug logs enabled. The connector will print the exact SQL queries it is sending.

On Unix (Linux, MacOS, etc.):

```
DEBUG=loopback:connector* node .
```

On Windows:

```
SET DEBUG=loopback:connector*
node .
```

**Comment by hosiduy** [comment]
Thanks for your support, I will try both.
