### ISSUE TITLE
Facilitate communication between multiple (polyglot) microservices

### ISSUE THREAD

**Issue by kesavkolla** [strongloop/loopback-next#222]
when developing microservices it's better to have complete disconnect from even code/repo structure. Let's say we've three microservices they should be able to develop independently on their own repo and be able to deploy on their own container. The communication between two different services should be pure API.  grpc has done some neat constructs around this. Can we get support for service-to-service high performant rpc style communication?  Currently the only communication supported is REST, which IMO is not efficient.

**Comment by raymondfeng** [comment]
Check this out - https://github.com/strongloop/loopback-example-polyglot. We already have a grpc connector for LoopBack.

**Comment by dhmlau** [comment]
relate to: https://github.com/strongloop/loopback-next/issues/521

**Comment by bajtos** [comment]
I am closing this issue because we are not going to have time to work on this in the next 6-9 months. However, we are happy to accept a pull request contributing this feature.
