### ISSUE TITLE
images for "Preparing the API for consumption" how-to not appearing in generated HTML or online

### ISSUE THREAD

**Issue by emonddr** [strongloop/loopback-next#2221]
## Current Behavior
The images in HTML file 

https://loopback.io/doc/en/lb4/Preparing-the-API-for-consumption.html 

are not visible.

The MD file 

/loopback-next/docs/site/Preparing-the-API-for-consumption.shelved.md 

makes use of 3 PNG files

![image](https://user-images.githubusercontent.com/6864736/50791273-5c51d180-128f-11e9-8073-e66a36d53df8.png)

![image](https://user-images.githubusercontent.com/6864736/50791288-6b388400-128f-11e9-8d96-eab7442da09d.png)

![image](https://user-images.githubusercontent.com/6864736/50791325-7b506380-128f-11e9-9d5a-a881b6065b45.png)

and they are present in

/loopback-next/docs/site/imgs
/loopback-next/sandbox/loopback.io/pages/en/lb4/imgs

There must be something wrong with the url of the images.

## Expected Behavior
I would expect the "document build" to have flagged an error for an invalid image url for the .MD file or generated .HTML file

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by emonddr** [comment]
using the MD image notation

![image](https://user-images.githubusercontent.com/6864736/50792893-7e9a1e00-1294-11e9-9b0d-dc11ad3025e4.png)
 
![image](https://user-images.githubusercontent.com/6864736/50792912-8d80d080-1294-11e9-9db4-cc1e5f4443db.png)
 
![image](https://user-images.githubusercontent.com/6864736/50792932-9a9dbf80-1294-11e9-98e6-980a91aca4bf.png)
 
with correct image url works.

![image](https://user-images.githubusercontent.com/6864736/50793130-39c2b700-1295-11e9-868c-e08b94b1e5c5.png)

**Comment by emonddr** [comment]
using

![image](https://user-images.githubusercontent.com/6864736/50793786-4811d280-1297-11e9-96b9-827d84b1d1e0.png)

doesn't work since it produces an invalid image url in the generated html 

![image](https://user-images.githubusercontent.com/6864736/50793848-7db6bb80-1297-11e9-859f-4523e01be93c.png)

**Comment by hacksparrow** [comment]
Thanks @emonddr, fixed in https://github.com/strongloop/loopback-next/pull/2226. Going forward we should be using Markdown image tags for all LB4 docs.
