### ISSUE TITLE
Setup greenkeeper to detect & update outdated dependencies

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2229]
GreenKeeper is a service that monitors outdated dependencies and can send a pull request to update them. It's a great tool for ensuring that we are always using the latest version of our dependencies.

In the past, it did not support monorepos and thus we could not use in for loopback-next. Fortunately, things have changed and GreenKeeper does support monorepos today.

Docs: https://greenkeeper.io/docs.html#monorepo

I am proposing to enable GreenKeeper for loopback-next.

See also the discussion in https://github.com/strongloop/loopback-next/issues/2207

**Comment by dhmlau** [comment]
@bajtos , since the requirement is originated from the example app, I'm thinking to set up GreenKeeper in this task as well.  

## Acceptance Criteria
Follow instruction in https://greenkeeper.io/docs.html#monorepo, set up GreenKeeper for:
- [ ] loopback-next
- [ ] loopback4-example-shopping

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/pull/2325

**Comment by raymondfeng** [comment]
And #2323

**Comment by dhmlau** [comment]
@raymondfeng , since we have greenkeeper now, would this task be considered as resolved?

**Comment by raymondfeng** [comment]
Done.
