### ISSUE TITLE
hasOne relation DELETE, PATCH and PUT CRUD operations are missing

### ISSUE THREAD

**Issue by RaphaelDrai** [strongloop/loopback-next#2233]
## Description / Steps to reproduce / Feature proposal
Add support hasOne CRUD Operations DELETE and PATCH

## Initial reference:
https://github.com/strongloop/loopback-next/pull/2147#issuecomment-453047863

## Acceptance Criteria
- It requires a feature enhancement to support DELETE and PATCH CRUD operations in hasOne relation.
- create interface for CRUD methods for DELETE and PATCH hasOne relation
- create test cases
- update docs
- create a follow up issue to demonstrate using multiple relations in a new/existing example

**Comment by b-admike** [comment]
Thank you for taking this up @RaphaelDrai! Sorry I had started on it a while back and didn't get to finish. Feel free to use https://github.com/strongloop/loopback-next/commit/b403947c2488e9f5111bf6d51dbca9f82505017f as inspiration/starting point.

**Comment by RaphaelDrai** [comment]
Hello @b-admike,
it is my pleasure to contribute, no problem.
Thanks you so much for the information for the starting point reference.

**Comment by RaphaelDrai** [comment]
Hello @b-admike,
I am starting to implement the DELETE first then I will continue with the PATCH and PUT operations.
I will change the title to add the PUT operation too.

**Comment by RaphaelDrai** [comment]
Hi @bajtos , @raymondfeng ,
I have added the new feature DELETE operation in hasOne relation and sent a pool request to merge it to the master.
Please do not close the issue #2233, I still need to provide the PATCH and PUT operations in the same issue.
Thanks a lot
Raphael
