### ISSUE TITLE
Spike: Application service layer with @service decorator (like Java Spring)

### ISSUE THREAD

**Issue by haotangio** [strongloop/loopback-next#2239]
As far as I understand, currently if we develop application with LB 4, most of the application logic will be handled by `controllers` (belongs to presentation layer) which are injected `repositories` (belongs to data access layer). This may make controller very "fat" (fat controller), and this is where we mix the application logic together with transport stuff (routing, HTTP response status, ...), which is somehow not so cool for complex use cases.

Moreover, some controllers may share the same application logic, or you even don't need a controller to fulfill a use case (e.g: seeding initial data on system startup). This is where a service object which encapsulates application logic would be helpful. It then could be used in many scenarios depending on external triggers (not only REST/SOAP/GraphQL controllers, but also cron-job handlers, application message-queue event-listeners, ...) via DI.

IMHO, Loopback 4 are kind of similar (or inspired?) by not only MVC, but also DDD (Domain-Driven Design). The usage of controller, repository, entity, factory, context, ... are also familiar to Java Spring. How if we have a similar `@service` decorator as well? Just my personal thought :)

**Comment by bajtos** [comment]
I think this is similar to the problem we encountered in https://github.com/strongloop/loopback4-example-shopping/pull/26, where the implementation of `login` method does not belong to repository nor controller, and we needed a new place (a service? a utility?) to provide implementation shared by multiple callers (controllers, tests, etc.).

**Comment by jannyHou** [comment]
+1 for Miroslav's comment above, we currently implemented it as a utility. I am not very expert on the difference between service and utility, so correct me if I am wrong: my point is if it's only for app/api developer's internal use, utility is good, if we give client access to it, then implement it as a service.

**Comment by luisfavila** [comment]
What about the cron-job/queue use case? Is there any way in the current implementation to invoke a controller from the application itself / have it initialized on boot as a singleton?

**Comment by raymondfeng** [comment]
I think we now have enough capabilities to support the `service` idea:

1. Each TypeScript class (not only controllers) can be decorated with `@bind` and `@inject` to be managed by IoC and DI.

2. We have improved `lb4 service` to generate local services - see https://loopback.io/doc/en/lb4/Service-generator.html

3. We support life cycle observers to allow use cases such as startup scripts or cron jobs - https://loopback.io/doc/en/lb4/Life-cycle.html

Please let us know what's missing to support your scenarios.

**Comment by haotangio** [comment]
Hello @raymondfeng. Thank you very much for your update.

I'm starting to use LB4 for several projects ahead and just checked in the current version of LB4.
And yeah, I think the current IoC and DI support is great enough to build production products.

The only lacking features to be perfect-to-use (in my feeling as framework users/developers) is about has-many-through relation, and built-in authorization with ACL. But it should be in a different issue ticket :)

**Comment by dhmlau** [comment]
@haotangio, thanks for your support for LoopBack 4! 

For hasMany Through, there's an ongoing PR to add the support: https://github.com/strongloop/loopback-next/pull/2359. 
For built-in authorization, please take a look at our docs: https://loopback.io/doc/en/lb4/Loopback-component-authorization.html.  

I'd like to close this issue as resolved.  Please feel free to continue the hasMany Through discussion in the above PR or open a new GitHub issues for other areas.  Thanks!!
