### ISSUE TITLE
Postgres not autogenerating id

### ISSUE THREAD

**Issue by codejamninja** [strongloop/loopback-next#2240]
## Description / Steps to reproduce / Feature proposal

When I try and create a record in postgres, it fails to generate an id. Postgres requires that the id not be null (which even if it didn't, I still want it not to be null)

## Current Behavior

I get the following error
```sh
null value in column "id" violates not-null constraint
```

## Expected Behavior

The id should be autogenerated and created in the database

**Comment by dougal83** [comment]
Have you set generated to true for db to seed ids:

```ts
  @property({
    id: true,
    generated: true,
    description: 'The unique identifier for a product',
  })
  id: number;
```

Same as lb3: https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html

**Comment by codejamninja** [comment]
Ah, thanks

**Comment by dhmlau** [comment]
@codejamninja , is this issue good to close then?  Thanks.
