### ISSUE TITLE
Automatically refresh upon changes (build & watch with nodemon)

### ISSUE THREAD

**Issue by yakirbu** [strongloop/loopback-next#2242]
Hi,

If I would like loopback to automatically refresh after changes, how can I do that?
running 'nodemon start' doesn't seem to work, it runs the server, but doesn't restart upon changes.

(.P.S, is there a substitute to 'lb property', for loopback 4, to add a new property to a model?)

Thanks.

**Comment by jannyHou** [comment]
@dougal83 Thank you for providing the example repository combines LoopBack 4 and Angular. 
cc @dhmlau shall we create a page in our document to promote community example repositories like this ^ ?

**Comment by gregra81** [comment]
@yakirbu Use this https://www.npmjs.com/package/tsc-watch
And add this line to your `scripts` in package.json:
`"start:watch": "tsc-watch -b --onSuccess \"node .\"",`

**Comment by dhmlau** [comment]
Related to: https://github.com/strongloop/loopback-next/issues/2107

**Comment by psaunders** [comment]
I have gotten quite a long way down the nodemon + ts-node route.

If you go down this route you will run into a few thing, first you have to create a point of entry file for ts-node because index.ts is some sort of bundling file.

```ts
import * as application from './src';

module.exports = application;

const config = {
  rest: {
    port: +process.env.PORT || 3000,
    host: process.env.HOST || 'localhost',
    openApiSpec: {
      setServersFromRequest: true,
    },
  },
};

application.main(config).catch(err => {
  console.error('Cannot start the application.', err);
  process.exit(1);
});
```

Then your nodemon configuration to package.json
```json
  "nodemonConfig": {
    "watch": [
      "src"
    ],
    "ext": "ts",
    "exec": "ts-node nodemon.ts"
  },
```

Then you have to add the typescript controller files into your `application.ts`

```
    this.bootOptions = {
      controllers: {
        // Customize ControllerBooter Conventions here
        dirs: ['controllers'],
        extensions: ['.controller.js', '.controller.ts'],
        nested: true,
      },
    };
```

I now am getting a:  `The key repositories.XYZRepository was not bound to any value` and am getting the feeling that this is not worth it and just switched over to this:

```
  "nodemonConfig": {
    "watch": [
      "src"
    ],
    "ext": "ts",
    "exec": "npm start"
  },
```

Which is a bit slow but fine for now.

**Comment by bschrammIBM** [comment]
> This experimental setup might do it:
> https://github.com/mightytyphoon/lb4-ng-quickstart
@dougal83 Thank you for providing the example repository combines LoopBack 4 and Angular.
We would like to publish this example on our loopback.io doc site, in a new section entitled **Community Contributions**. Are you ok with having this example published? Please let me know!

**Comment by bachdinhnhan** [comment]
> @yakirbu Use this https://www.npmjs.com/package/tsc-watch
> And add this line to your `scripts` in package.json:
> `"start:watch": "tsc-watch -b --onSuccess \"node .\"",`

@gregra81 
I started with your idea and the result is unexpected when it compiles entire project into the current directory instead of /dist folder. Eventually, it overrides the index.js file and makes the project unable to start with "npm run start". 

So after digging into **tsc-watch** and **tsc** itself, it ends up with a better version.
`"start:watch": "tsc-watch --target es2017 --outDir ./dist --onSuccess \"node .\"",`

**Comment by bachdinhnhan** [comment]
@dhmlau @yakirbu 
Try add this line to your scripts in package.json:
`"start:watch": "tsc-watch --target es2017 --outDir ./dist --onSuccess \"node .\"",`

**Comment by tsm91** [comment]
for the record: if u want to debug ur app and have proper sourcemap support. Use: `"start:watch": "tsc-watch --target es2017 --outDir ./dist --onSuccess \"node --inspect .\""` with [chrome canary](https://www.google.com/chrome/canary/) and [NiM](https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj?hl=en)

**Comment by tonifirnandes** [comment]
> for the record: if u want to debug ur app and have proper sourcemap support. Use: `"start:watch": "tsc-watch --target es2017 --outDir ./dist --onSuccess \"node --inspect .\""` with [chrome canary](https://www.google.com/chrome/canary/) and [NiM](https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj?hl=en)

Thanks, it works, but hopefully there is still another simple way, so our source code not fully of *.js.map file.

**Comment by pavelgronsky** [comment]
So, who can explain or who can show example about how I can used nodemon with Loopback 4. How I can changed files and take autorestart my loopback server?

**Comment by anjorinjnr** [comment]
Add
```
  "nodemonConfig": {
    "verbose": true,
    "watch": [
      "src/"
    ],
    "ignore": [
      "dist/*"
    ],
    "ext": "ts",
    "exec": "npm start"
  }
```
to your package.json

Then simply run nodemon (assuming you've already installed it)

**Comment by pavelgronsky** [comment]
@anjorinjnr What start file I need to run in nodemon command?
 **nodemon  index.ts**  - this is correct command?

**Comment by pavelgronsky** [comment]
Ok, work for me this option:
I added script to package.json

 "scripts": {
    "dev": "nodemon server.js"
  }

and added this to package.json:

"nodemonConfig": {
    "verbose": true,
    "watch": [
      "src/"
    ],
    "ignore": [
      "dist/*"
    ],
    "ext": "ts",
    "exec": "npm start"
  }

And run application by this command:
npm run dev

**Comment by frbuceta** [comment]
> Ok, work for me this option:
> I added script to package.json
> 
> **"scripts": { "dev": "nodemon server.js" }**
> 
> and added this to package.json:
> 
> **"nodemonConfig": { "verbose": true, "watch": [ "src/" ], "ignore": [ "dist/*" ], "ext": "ts", "exec": "npm start" }**
> 
> And run application by this command:
> **npm run dev**

It works for me too. Thanks

**Comment by tsm91** [comment]
> > for the record: if u want to debug ur app and have proper sourcemap support. Use: `"start:watch": "tsc-watch --target es2017 --outDir ./dist --onSuccess \"node --inspect .\""` with [chrome canary](https://www.google.com/chrome/canary/) and [NiM](https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj?hl=en)
> 
> Thanks, it works, but hopefully there is still another simple way, so our source code not fully of *.js.map file.

@tonifirnandes there is, modify tsconfig.json compilerOptions to inline sourcemaps. This also works for normal chrome, no need canary
```json
{
  "$schema": "http://json.schemastore.org/tsconfig",
  "extends": "@loopback/build/config/tsconfig.common.json",
  "compilerOptions": {
    "rootDir": "src",
    "sourceMap": false,
    "inlineSourceMap": true,
    "inlineSources": true
  },
  "include": ["src"]
}
```

**Comment by tsm91** [comment]
> > for the record: if u want to debug ur app and have proper sourcemap support. Use: `"start:watch": "tsc-watch --target es2017 --outDir ./dist --onSuccess \"node --inspect .\""` with [chrome canary](https://www.google.com/chrome/canary/) and [NiM](https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj?hl=en)
> 
> Thanks, it works, but hopefully there is still another simple way, so our source code not fully of *.js.map file.

this solution works with `nodemon` + `lb-tsc --watch`. also modified `tsconfig.json` to generate inline sourcemaps which is also supported by normal chrome. no need to install canary chrome

modify package.json:
```json
"scripts": {
  "build:watch": "lb-tsc es2017 --outDir dist --watch",
  "start:dev": "nodemon --watch ./dist --inspect ./index.js"
}
```

modify tsconfig.json:
```json
{
  "$schema": "http://json.schemastore.org/tsconfig",
  "extends": "@loopback/build/config/tsconfig.common.json",
  "compilerOptions": {
    "rootDir": "src",
    "sourceMap": false,
    "inlineSourceMap": true,
    "inlineSources": true
  },
  "include": ["src"]
}
```

cc @tonifirnandes

**Comment by hgouillard** [comment]
In package.json, i add for development run : 
`"start:dev": "export NODE_ENV=development && (npm run build:watch & nodemon --watch ./dist --inspect ./index.js)"`

**Comment by pavelgronsky** [comment]
> npm run dev
Ok, friends. 
I was able to understand how run nodemon by launch.json in VSCODE and how run nodemon by npm run dev command. Everything works fine, but how I can run nodemon together with debugged by npm command ?

**Comment by rodmcnew** [comment]
I think it would be best for adoption if loopback came with something that handled this out of the box. Installing the framework thinking you can start coding right away, then having to deal with this problem isn't a great experience.

- A new loopback app comes with 23 package.json scripts and none of them do this.
- Meanwhile create-react-app comes with 4 scripts and one does do this.
