### ISSUE TITLE
Any support ACL support

### ISSUE THREAD

**Issue by mdhanju** [strongloop/loopback-next#2254]
## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by jannyHou** [comment]
Hi @mdhanju thanks for being interested in the ACL feature. The authorization story is tracked in epic https://github.com/strongloop/loopback-next/issues/1035, feel free to join the discussion.

**Comment by osmanmesutozcan** [comment]
@jannyHou I will also be tracking the issue, thanks for the hard work there!

@mdhanju I also had an ACL requirement. Ended up writing a very small extension. You can check it [here](https://github.com/xanthous-tech/loopback-4-accesscontrol)

**Comment by DatGuyJonathan** [comment]
Thanks for the link @jannyHou . Would you be able to share a timeline for the ACL feature?

**Comment by dhmlau** [comment]
@DatGuyJonathan, for Q2, we're planning to enable mounting Express middleware for authorization. https://github.com/strongloop/loopback-next/issues/2697. 

Having said that, there are some examples from the community to create extensions for authorization. See https://github.com/xanthous-tech/loopback-4-accesscontrol from the above comment and possibly another example from https://github.com/strongloop/loopback-next/issues/538#issuecomment-479783245.

**Comment by raymondfeng** [comment]
We’re starting to add method interceptors, which can be used to add authorization capabilities on top of. Check out https://github.com/strongloop/loopback-next/pull/2687.

**Comment by dhmlau** [comment]
Closing as done. 
Please see https://loopback.io/doc/en/lb4/Loopback-component-authorization.html and https://github.com/strongloop/loopback-next/tree/master/examples/access-control-migration for reference. Thanks.
