### ISSUE TITLE
Loopback 4 IISNode Deployment Error "Buffer() is deprecated"

### ISSUE THREAD

**Issue by malis90** [strongloop/loopback-next#2258]
## Environment
`
@loopback/cli version: 1.5.0,
Node: v10.15.0
`
## IISNode Configurations
`
<configuration>
  <system.webServer>

    

    <handlers>
      <add name="iisnode" path="index.js" verb="*" modules="iisnode" />
    </handlers>

    <iisnode      
      node_env="%node_env%"
      nodeProcessCountPerApplication="1"
      maxConcurrentRequestsPerProcess="1024"
      maxNamedPipeConnectionRetry="100"
      namedPipeConnectionRetryDelay="250"      
      maxNamedPipeConnectionPoolSize="512"
      maxNamedPipePooledConnectionAge="30000"
      asyncCompletionThreadCount="0"
      initialRequestBufferSize="4096"
      maxRequestBufferSize="65536"
      watchedFiles="*.js;iisnode.yml"
      uncFileChangesPollingInterval="5000"      
      gracefulShutdownTimeout="60000"
      loggingEnabled="true"
      logDirectory="iisnode"
      debuggingEnabled="false"
      debugHeaderEnabled="false"
      debuggerPortRange="5058-6058"
      debuggerPathSegment="debug"
      maxLogFileSizeInKB="128"
      maxTotalLogFileSizeInKB="1024"
      maxLogFiles="20"
      devErrorsEnabled="true"
      flushResponse="false"      
      enableXFF="false"
      promoteServerVars=""
      configOverrides="iisnode.yml"
     />
    <rewrite>
      <rules>
        <rule name="dakia">
          <match url="/*" />
          <action type="Rewrite" url="index.js" />
        </rule>
      </rules>
    </rewrite>

  </system.webServer>
</configuration>
`
## Steps To Reproduce
Just deploy Loopback 4 application using IIS Node you will get the same error. Even deploying "loopback4-example-todo-list" give same error.
One thing to do to run application in IISnode you need to comment out given condition in index.js
`if (require.main === module) {
}`

## Descriptive Error
iisnode encountered an error when processing the request.
`
HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1001
HTTP reason: Internal Server Error
`
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:
`
(node:11892) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
`

Does anyone has solution for that?

**Comment by dhmlau** [comment]
@malis90 , I don't have experience with deploying to IIS.  Does it run with `/ping` endpoint? 
When deploying to IBM Cloud, I had to make some modification to `src/index.ts` according to this docs page: https://loopback.io/doc/en/lb4/Deploying-to-IBM-Cloud.html#updating-application.  Just a suggestion.

**Comment by dhmlau** [comment]
Thanks for the info, @malis90.  
Just in case you're not aware, there's a doc page on deploying with `pm2`: https://loopback.io/doc/en/lb4/deploying-with-pm2-and-nginx.html.

Do you think this issue is good to close? Thanks.
