### ISSUE TITLE
How to debug with break points in Visual Studio Code

### ISSUE THREAD

**Issue by michaelhaydendeveloper** [strongloop/loopback-next#2260]
Im not seeing how to fashion my launch.json file in Visual Studio Code to allow adding break points into my Loopback 4 code.
Does someone have an example of launch.json that enables this capability?

**Comment by dhmlau** [comment]
@michaelhaydendeveloper , here is the launch.json I used today to debug `packages/cli`.  
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Run Mocha tests",
      "program": "${workspaceRoot}/packages/build/node_modules/.bin/_mocha",
      "cwd": "${workspaceRoot}/packages/cli", <---- MY CHANGE HERE
      "args": [
        "--opts",
        "${workspaceRoot}/packages/cli/test/mocha.opts",
        "test/**/*.js", <----- MY CHANGE HERE
        "-t",
        "0"
      ]
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to Process",
      "port": 5858
    }
  ]
}
```

courtesy to @b-admike  :)

**Comment by dhmlau** [comment]
@michaelhaydendeveloper , did the above snippet help?  
Also, please review the discussion in this issue as well: https://github.com/strongloop/loopback4-example-shopping/issues/28.

**Comment by dhmlau** [comment]
@michaelhaydendeveloper , we believe we've answered your question.  So I'm closing this issue.  If you still have questions regarding the VS Code configuration, feel free to ping me to reopen or open a new ticket.  Thanks.

**Comment by smman89** [comment]
@michaelhaydendeveloper , it works for me

{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "LB4_Debug",
      "program": "${workspaceFolder}\\dist\\index.js",
      "cwd": "${workspaceRoot}",
      "args": [
        "--recursive",
        "--require",
        "source-map-support/register",
        "--allow-console-logs",
        "dist/test/**/*.js"
      ]
    }
  ]
}
