### ISSUE TITLE
Model relation: hasManyThrough

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2264]
Open a separate issue to track `hasManyThrough` per request from @RaphaelDrai in 
https://github.com/strongloop/loopback-next/issues/2043#issuecomment-448912973

> Hello @bajtos,
It is important for us to have in LB4 the hasAndBelongsToMany (the direct many-to-many relation) that we are using in our LB3 application. We are actually in a transition process to move our LB3 application to LB4 and hasAndBelongsToMany is considered as an high priority.
May I suggest to have a new and separated case for the hasManyThrough in order to avoid confusion with this current case?

**Comment by RaphaelDrai** [comment]
Hi @dhmlau ,
Thanks you for creating this separate issue.
I am adding the design proposal of the SW implementation for review and comment.
[Design_HasAndBelongsToMany_Contrib.docx](https://github.com/strongloop/loopback-next/files/2776434/Design_HasAndBelongsToMany_Contrib.docx)

**Comment by codejamninja** [comment]
As suggested by @bajtos, I'm going to start working on the hasManyThrough before finishing the implementation of hasAndBelongsToMany.

#2308

**Comment by codejamninja** [comment]
I attempted to reimplement hasManyThrough using the hasMany relation with a `through` property. After implementing it, I now think it might not be the best approach. Below are some of the issues I ran into.

The hasManyThrough has to make a database query before creating a constraint. This forces the `createHasManyRepositoryFactory` to return an asynchronous function, which breaks the existing API.

https://github.com/codejamninja/loopback-next/blob/codejamninja/has-many-through-using-has-many/packages/repository/src/relations/has-many/has-many-repository.factory.ts#L66-L79 

To keep backwards compatibility, I tried to make the `createHasManyRepositoryFactory` only return a promise if `through` is set. This allows the return type to be the following. I should mention that the following return type does give some errors currently.

```ts
HasManyRepository<Target> | Promise<HasManyRepository<Target>>
```
https://github.com/codejamninja/loopback-next/blob/codejamninja/has-many-through-using-has-many/packages/repository/src/relations/has-many/has-many-repository.factory.ts#L24

**Comment by codejamninja** [comment]
Another issue I ran into is the generics. hasManyThrough needs access to the through repository. This requires passing the repository type using generics, very similar to the way the target repository type gets passed through the generic.

https://github.com/codejamninja/loopback-next/blob/codejamninja/has-many-through-using-has-many/packages/repository/src/relations/has-many/has-many-repository.factory.ts#L45-L46

The challenge with this is that many times, hasMany is not using a through model and repository, so the through generic needs to be optional. This requires setting default generic values, and in my opinion is not ideal.

https://github.com/codejamninja/loopback-next/blob/codejamninja/has-many-through-using-has-many/packages/repository/src/relations/has-many/has-many-repository.factory.ts#L45-L46

Because the through generics are optional, this means they must be listed last. I would prefer the `ForeignKeyType` to be listed last.

This is why I think hasManyThrough should be defined in a separate relation altogether.

**Comment by codejamninja** [comment]
I would like to mention that using the hasManyThrough relation will be a little odd no matter how it is implemented because the constraint depends on asynchronous database queries. Using it will look something like the following.

Notice the two awaits

```ts
const patients = await (async this.physicianRepository.patients(physicianId)).find();
```

**Comment by codejamninja** [comment]
It would be great if ya'll could give me feedback on this.

**Comment by codejamninja** [comment]
I was just thinking, maybe the constraint for hasManyThrough could be built in the hasManyThrough repository (for example in the actual `find` method). This would most definitely require the hasManyTrhough to be implemented as a separate relation.

**Comment by codejamninja** [comment]
Ok, so I actually was able to get `hasMany` to work in a fully backwards compatible way with a `through` property being passed into it. Basically, instead of getting the constraint in the factory function, I pass an asynchronous constraint getter into the repository.

https://github.com/codejamninja/loopback-next/blob/codejamninja/has-many-through-using-has-many/packages/repository/src/relations/has-many/has-many-repository.factory.ts#L55-L74
https://github.com/codejamninja/loopback-next/blob/codejamninja/has-many-through-using-has-many/packages/repository/src/relations/has-many/has-many.repository.ts#L92

Because I can do it with an asynchronous getConstraint function, I think I will be able to stick with implementing this in the `hasMany` repository.  Currently, all the unit tests are passing in the following pull request.

https://github.com/strongloop/loopback-next/pull/2359

**Comment by codejamninja** [comment]
This also fixes the double await issue.

**Comment by codejamninja** [comment]
I have a very basic example of `hasManyThrough` working.
https://github.com/codejamninja/medical-practice-api

You will need to use the code from the following remote and branch to get this to work.
https://github.com/codejamninja/loopback-next/tree/codejamninja/has-many-through-using-has-many

```sh
cd loopback-next/packages/repository
yarn build
yarn link
```

```sh
cd medical-practice-api
yarn link @loopback/repository
yarn start
```

```ts
    this.physicians = this.createHasManyRepositoryFactoryFor(
      'physicians',
      getPhysicianRepository,
      getAppointmentRepository
    );
```
https://github.com/codejamninja/medical-practice-api/blob/master/src/repositories/patient.repository.ts#L32-L36

```ts
  @hasMany(() => Physician, { through: () => Appointment })
  physicians: Physician[];
```
https://github.com/codejamninja/medical-practice-api/blob/master/src/models/patient.model.ts#L18-L19

**Comment by codejamninja** [comment]
While I do believe the hasMany through relation should be built as part of the hasMany relation to maintain consistent behaviour with loopback 3, the repository and factory logic gets really messy and complex.

IMO, the messiest part is dealing with the through repository factory. The factory function needs a generic type referencing the through entity. However, when not using a hasManyThrough relation, the generic type for the through entity should not be passed through. Origionally I solved this delima by simply not passing the through entity generic and instead directly referenced entity. This is certianly not ideal as it limits the type checking when using through with the hasMany factory.

I decided that the best compromise is to still have hasMany contain the hasManyThrough realtion, but separated the relation repository factories. So, in summary if you want to use hasManyThrough, you just add the `through` property in your `hasMany` decorator in your model. But, to create the repository factory, you will use `createHasManyThroughRepositoryFactory`. Regular hasMany relations will still use the `createHasManyRepositoryFactory` function.

https://github.com/codejamninja/loopback-next/blob/codejamninja/has-many-through-using-has-many/packages/repository/src/relations/has-many/has-many-through-repository.factory.ts#L50
https://github.com/codejamninja/loopback-next/blob/codejamninja/has-many-through-using-has-many/packages/repository/src/repositories/legacy-juggler-bridge.ts#L278-L279
https://github.com/codejamninja/loopback-next/blob/codejamninja/has-many-through-using-has-many/packages/repository/src/repositories/legacy-juggler-bridge.ts#L284

https://loopback.io/doc/en/lb3/HasManyThrough-relations.html#defining-a-hasmanythrough-relation

**Comment by codejamninja** [comment]
If my previous comments are too technical, here are two simple examples of a `hasMany` relationship. One without a through model, and one with a through model.

## hasMany w/o through
This works exactly how hasMany has worked in the past with loopback 4

_models/patient.model.ts_
```ts
import { Entity, model, property, hasMany } from '@loopback/repository';
import { Patient } from '../models';

@model()
export class Physician extends Entity {
  @property({
    type: 'string',
    id: true
  })
  id?: string;

  @hasMany(() => Patient)
  patients: Patient[];
}
```

_repositories/patient.repository.ts_
```ts
import {
  DefaultCrudRepository,
  HasManyRepositoryFactory,
  repository
} from '@loopback/repository';
import { inject, Getter } from '@loopback/core';
import { MemoryDataSource } from '../datasources';
import { Patient, Physician } from '../models';
import { PhysicianRepository } from '../repositories';

export class PatientRepository extends DefaultCrudRepository<
  Patient,
  typeof Patient.prototype.id
> {
  public readonly physicians: HasManyRepositoryFactory<
    Physician,
    typeof Patient.prototype.id
  >;

  constructor(
    @inject('datasources.memory')
    dataSource: MemoryDataSource,
    @repository.getter('PhysicianRepository')
    getPhysicianRepository: Getter<PhysicianRepository>
  ) {
    super(Patient, dataSource);
    this.physicians = this.createHasManyRepositoryFactoryFor(
      'physicians',
      getPhysicianRepository
    );
  }
}
```

## hasMany w/o through
Notice the factory function is different

_models/patient.model.ts_
```ts
import { Entity, model, property, hasMany } from '@loopback/repository';
import { Appointment, Patient } from '../models';

@model()
export class Physician extends Entity {
  @property({
    type: 'string',
    id: true
  })
  id?: string;

  @hasMany(() => Patient, { through: () => Appointment })
  patients: Patient[];
}
```

_repositories/patient.repository.ts_
```ts
import {
  DefaultCrudRepository,
  HasManyRepositoryFactory,
  repository
} from '@loopback/repository';
import { inject, Getter } from '@loopback/core';
import { MemoryDataSource } from '../datasources';
import { Patient, Physician } from '../models';
import { AppointmentRepository, PhysicianRepository } from '../repositories';

export class PatientRepository extends DefaultCrudRepository<
  Patient,
  typeof Patient.prototype.id
> {
  public readonly physicians: HasManyRepositoryFactory<
    Physician,
    typeof Patient.prototype.id
  >;

  constructor(
    @inject('datasources.memory')
    dataSource: MemoryDataSource,
    @repository.getter('AppointmentRepository')
    getAppointmentRepository: Getter<AppointmentRepository>,
    @repository.getter('PhysicianRepository')
    getPhysicianRepository: Getter<PhysicianRepository>
  ) {
    super(Patient, dataSource);
    this.physicians = this.createHasManyThroughRepositoryFactoryFor(
      'physicians',
      getPhysicianRepository,
      getAppointmentRepository
    );
  }
}
```

**Comment by codejamninja** [comment]
I thought I might upload the following file to help clarify the code and variable names in the hasManyThrough implementation

![hasone](https://user-images.githubusercontent.com/6234038/52611266-45803b00-2e4a-11e9-9217-0eb7e83bf60c.png)

**Comment by dhmlau** [comment]
@codejamninja, thanks for taking up this story.  Is it ok if I assign this issue to you? I've already marked it as `community contribution`.  Thanks.

**Comment by codejamninja** [comment]
@dhmlau absolutely, thanks!

**Comment by codejamninja** [comment]
Anyone wanting to get early access to the hasManyThrough relation (or anyone wanting to test it), you can install it the following way.

```sh
npm install --save @loopback/repository@git+https://git@github.com/codejamninja/loopback-next.git#npm/has-many-through
```

or add the following to your package.json file

```json
{
  "dependencies": {
    "@loopback/repository": "git+https://git@github.com/codejamninja/loopback-next.git#npm/has-many-through"
  }
}
```

**Comment by privateOmega** [comment]
@codejamninja Any updates on this feature?

**Comment by codejamninja** [comment]
I will have updates before the end of the month. I'm a bit crunched with work at the moment.

**Comment by codejamninja** [comment]
My pull request for this at #2359 is ready.

For those interested in trying it out, you can install it the following way.

```sh
npm install --save @loopback/repository@git+https://git@github.com/codejamninja/loopback-next.git#npm/codejamninja/has-many-through-using-has-many@1.11.0-rc.1
```

or add the following to your package.json file

```json
{
  "dependencies": {
    "@loopback/repository": "git+https://git@github.com/codejamninja/loopback-next.git#npm/codejamninja/has-many-through-using-has-many@1.11.0-rc.1"
  }
}
```

**Comment by foxinni** [comment]
Hi, Tried to run the medical example but ran into this issue:

`src/controllers/appointment.controller.ts:51:52 - error TS2345: Argument of type 'typeof Appointment' is not assignable to parameter of type 'typeof Model'.`

![image](https://user-images.githubusercontent.com/124101/67092099-af599d00-f1ae-11e9-8a88-f98892943b81.png)

**Comment by foxinni** [comment]
Nevermind. Run `npm install --save @loopback/repository@git+https://git@github.com/codejamninja/loopback-next.git#npm/codejamninja/has-many-through-using-has-many@1.11.0-rc.1` and got it working.

**Comment by KalleV** [comment]
Hi. Any new developments on this feature? The project I'm working on uses several joining tables and this feature would significantly reduce the boilerplate and custom workarounds.

**Comment by jacksonhyde** [comment]
What's the status of this feature branch?

**Comment by hacksparrow** [comment]
We are currently working on landing it via smaller PRs. A few of them have already landed - https://github.com/strongloop/loopback-next/pulls?q=is%3Apr+is%3Aclosed+hasManyThrough.

**Comment by dhmlau** [comment]
Thanks for the interest in the `hasManyThrough` relation type. The core implementation is done. What's remaining are [adding docs](https://github.com/strongloop/loopback-next/issues/5835) and [cli](https://github.com/strongloop/loopback-next/issues/5836). 

cc @agnes512

**Comment by Mohammedalasaad** [comment]
Hi @dhmlau , Do you mean its on latest version now? can we use it like.. 
  @hasMany(() => Patient, { through: () => Appointment })

I have latest version  "@loopback/core": "^2.9.1", and I tried but still showing error on through.
Property 'model' is missing in type '() => typeof MemberMemberships' but required in type '{ model: TypeResolver<Entity, typeof Entity>; keyFrom?: string | undefined; keyTo?: string | undefined; }'.ts(2741)

**Comment by agnes512** [comment]
@Mohammedalasaad  The code are released in `"@loopback/repository": "^2.9.0"`. Notice that it is still an experimental feature, and we are fixing a bug in https://github.com/strongloop/loopback-next/pull/5858.

**Comment by savan-thakkar** [comment]
@agnes512 Just updated the application dependencies and now the latest version is "@loopback/core": "^2.9.2" but still not able to create hasManyThrogh relation like @hasMany(() => Patient, { through: () => Appointment })
So still its under development or is there any other way to achive it ? 
Thanks in advance

**Comment by agnes512** [comment]
@savan-thakkar Hi, could you check if you have the dependency `"@loopback/repository": "^2.10.0"` ( the bug is fixed). Notice it is under **repository**, not **core**.

**Comment by savan-thakkar** [comment]
@agnes512 Thanks for quick reply and yes its there "@loopback/repository": "^2.10.0"

**Comment by agnes512** [comment]
@savan-thakkar these are the dependencies:
```
 "devDependencies": {
    "@loopback/build": "^1.7.1",
    "@loopback/repository": "^2.9.0",
    "@types/debug": "^4.1.5",
    "@types/lodash": "^4.14.157",
    "@types/node": "^10.17.27", 
    "lodash": "^4.17.19"
  },
  "dependencies": {
    "@loopback/core": "^2.9.1",
    "@loopback/testlab": "^3.2.0",
    "@types/debug": "^4.1.5",
    "debug": "^4.1.1",
    "tslib": "^2.0.0"
  },
```

**Comment by savan-thakkar** [comment]
@agnes512  Thanks for the update I'll verify it at my side. Thanks

**Comment by agnes512** [comment]
Closing as done. Feel free to leave comment or open issues if you have questions or find anything wrong. Thanks.

**Comment by agnes512** [comment]
@savan-thakkar any luck?

**Comment by savan-thakkar** [comment]
@agnes512  Yes its fixed by defining the relation like @hasMany(() => TargetModel, {through: {model: () => ThroughModel}}).
And also thanks for the latest cli update as well.

But apart from this I have one more doubt/issue related to saving additional fields of pivot table. 
For example if pivot table has more fields other than source and target ids then how we can store those fields in same create api ?

**Comment by agnes512** [comment]
I guess you're asking how to create though model instances with additional info e.g
```
Appointment{doctorId: 1, patientId: 1, description: 'additional info'}
```
The [`create` and `link`](https://loopback.io/doc/en/lb4/HasManyThrough-relation.html#available-crud-apis) methods of hasManyThrough repository are able to specify the throughData by `options.throughData`.

**Comment by savan-thakkar** [comment]
@agnes512  Yes exactly, I am asking for the same. Thank you for your help and quick reply. Thanks again

**Comment by agnes512** [comment]
@savan-thakkar Yes, you should be able to do it if the API takes `throughData`. For example:
```ts
await userRepo
        .users(existedUserId)
        .create(
          {name: 'target model - user'},
          {throughData: {description: 'a through model - UserLink'}},
        );
```

**Comment by savan-thakkar** [comment]
@agnes512 Thank you for the exaplaination and help. It works :100: Thanks again
