### ISSUE TITLE
[Discussion] Upgrading minor versions for generated apps

### ISSUE THREAD

**Issue by TimothyRHuertas** [strongloop/loopback-next#2265]
## Description / Steps to reproduce / Feature proposal
The package.json produced by @loopback/cli 1.5.1 includes newer dependencies than the one generated by 1.4.0. Is there a recommended way to update existing projects generated with 1.4 to be contain updated dependencies (package.json) using the 1.5.1 cli?  

## Current Behavior
I can't find a migration/upgrade guide.

## Expected Behavior
There is a guide.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
Hi @TimothyRHuertas, we are scaffolding the applications using `^` operator to specify dependency versions, therefore no migration should be needed. Just run `npm update` in your project, it will update all your dependencies to the latest compatible version.

Can you suggest us how to improve our docs to make this information easier to discover?

**Comment by bajtos** [comment]
Closing as resolved by https://github.com/strongloop/loopback-next/pull/4080, which added `lb4 update` command to check/update project dependencies
