### ISSUE TITLE
loopback4 rest api 

### ISSUE THREAD

**Issue by MeenalYengul** [strongloop/loopback-next#2266]
## Current Behavior

It is showing error at build script. When I hit npm install no issue but when i hit npm run build it is showing build script error. I am frustrated now. I am new bie to this loopback. 

-------------------ERROR----------------------------------

`test/unit/vendors.controller.unit.ts:2:84 - error TS2307: Cannot find module '@loopback/testlab'.

2 import { createStubInstance, expect, sinon, StubbedInstanceWithSinonAccessor} from '@loopback/testlab';
                                                                                     ~~~~~~~~~~~~~~~~~~~


test/unit/vendors.controller.unit.ts:3:32 - error TS2307: Cannot find module '../../src/controllers'.

3 import {VendorController} from '../../src/controllers';
                                 ~~~~~~~~~~~~~~~~~~~~~~~

test/unit/vendors.controller.unit.ts:5:33 - error TS2307: Cannot find module '../../src/repositories'.

5 import {VendorsRepository} from '../../src/repositories';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pots-api@0.18.1219 build: `lb-tsc es2017 --outDir dist`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the pots-api@0.18.1219 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MeenalYengul\AppData\Roaming\npm-cache\_logs\2019-01-17T17_09_21_126Z-debug.log
`
-----------------------------------------------------------------------




## Expected Behavior

It should run and connect to the database. Fetch the values from database.

**Comment by raymondfeng** [comment]
If you can share your example project with a git repo, we can take a look. Please make sure the latest version of `@loopback/cli` is installed.
