### ISSUE TITLE
How to encrypt password in loopback 4?

### ISSUE THREAD

**Issue by bijarniya** [strongloop/loopback-next#2267]
```javascript
import { Member } from '../models';
import { MemberRepository} from '../repositories';
import {inject, Context} from '@loopback/context';

export class MemberController {
constructor(
 @repository(MemberRepository) private memberRepository: MemberRepository,
@inject('utilities.PasswordHasher') private passwordHasher: PasswordHasher,
 ) { }


 }
```

**Getting this error.**
**Which module can i use for this?.**
src/controllers/member.controller.ts:27:65 - error TS2304: Cannot find name 'PasswordHasher'.

`@inject('utilities.PasswordHasher') private passwordHasher: PasswordHasher`
                                                                   ~~~~~~~~~~~~~~

src/controllers/member.controller.ts:27:65 - error TS4063: Parameter 'passwordHasher' of constructor from exported class has or is using private name 'PasswordHasher'.

 `@inject('utilities.PasswordHasher') private passwordHasher: PasswordHasher,`
                                                                   ~~~~~~~~~~~~~~

**Comment by bkstorm** [comment]
I think it's just an example, you must implement PasswordHasher by yourself.
To encrypt password, you can check this loopback 4 shopping cart example, they use bcryptjs module: https://github.com/strongloop/loopback4-example-shopping/blob/master/src/controllers/user.controller.ts

**Comment by bajtos** [comment]
@bijarniya I have reformatted your comment. When posting code snippets, use triple back tick followed by a language name for syntax highlighting. See https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by sbacem** [comment]
@bijarniya  I think is better to set encrypt password in model when update the value of password, 
@bajtos I think loopback 4 needs listeners like in [TypeOrm ](https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md)

**Comment by psaunders** [comment]
Here is a small password service we use
```ts
import SecurePass, { VerificationResult } from 'argon2-pass';
import { Account } from '../models';

export class PasswordService {
  constructor(private securePass: SecurePass = new SecurePass()) {}

  async passwordIsForAccount(plainPassword: string, account: Account): Promise<boolean> {
    if (!account.password) {
      return false;
    }

    const result: VerificationResult = await this.securePass.verifyHash(
      Buffer.from(plainPassword),
      Buffer.from(account.password, 'base64'),
    );

    if (SecurePass.isValid(result)) {
      return true;
    }

    return false;
  }

  async getStringHashForPassword(plainPassword: string): Promise<string> {
    return this.securePass.hashPassword(await Buffer.from(plainPassword)).then(value => {
      return value.toString('base64');
    });
  }
}
```

**Comment by dhmlau** [comment]
Discussion with @raymondfeng @jannyHou @emonddr,
there might be something already existed in example-shopping.  @emonddr to look up the sample code.

**Comment by jannyHou** [comment]
@bijarniya I believe you were trying the authentication system in shopping example, now it's refactored to use `@loopback/authentication@2.x`, you can find:

- the password hasher class in [this service](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/services/hash.password.bcryptjs.ts#L34)
- how user service uses it in [file](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/services/user-service.ts#L31-L38)
- how the password encryption works in the user controller in [file](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/controllers/user.controller.ts#L53)

You can follow the tutorial [Authentication-Tutorial](https://loopback.io/doc/en/lb4/Authentication-Tutorial.html) to learn how the JWT authentication works in that example.

I am closing the issue as the answer is provided, feel free to reopen it if you still have questions :)

**Comment by BIMMITHA-GB** [comment]
Is there any possible way to encrypt password using MD5 encryption in loopback? And how it is implement in our loopback4 program.

**Comment by Lipinalipi** [comment]
md5 encryption is possible or not in loopback4?

**Comment by achrinza** [comment]
@BIMMITHA-GB @Lipinalipi LoopBack 4 does not have any special requirements for password hashing. Hence, you can use whichever hashing library to has the password before storing it in the database. This can be done either in the Service (recommended), Controller or Repository level. `@loopback/authentication-jwt` uses bcrypt, a strong, purpose-built hashing algorithm.

**Comment by dougal83** [comment]
> Is there any possible way to encrypt password using MD5 encryption in loopback? And how it is implement in our loopback4 program.

Can I just say... **don't encrypt a password with MD5**.  MD5 should be for creating file signatures, etc that require a fast hash.  Password encryption should be computationally expensive to make them resistant to brute force attacks.

+1 to the fellow above using 'argon2' implementation. 👍
