### ISSUE TITLE
README.MD doc bug for CLI

### ISSUE THREAD

**Issue by jgwinner** [strongloop/loopback-next#2269]
## Description / Steps to reproduce / Feature proposal
The readme.md page at:https://github.com/strongloop/loopback-next/tree/master/packages/cli
lists only these CLI options:

> Available commands:
> ```
>   lb4 app
>   lb4 extension
>   lb4 controller
>   lb4 example
> ```

## Current Behavior

The current code lists these options:
```
  lb4 app
  lb4 extension
  lb4 controller
  lb4 datasource
  lb4 model
  lb4 repository
  lb4 service
  lb4 example
  lb4 openapi


```

## Expected Behavior
There are a lot of issues, both open and closed; I figured I'd make a short note for a tiny doc sprint as I run into specific issues as I learn and implement LB4.

The main docs do list each option and what they do, so this isn't a show stopper, just caused me a minor grumble.

**Comment by nabdelgadir** [comment]
Thanks for bringing this to our attention! I opened a PR to update the README: https://github.com/strongloop/loopback-next/pull/2270.
