### ISSUE TITLE
How to set response manually for a specific operation from a controller?

### ISSUE THREAD

**Issue by lapellaniz** [strongloop/loopback-next#2279]
## Description / Steps to reproduce / Feature proposal
I have a requirement where I need to accept a query (using the Filter object) as a POST vs a GET. It's a long-running query. I plan to return a 202 accepted header from the POST along with a Content-Location and retryafter header. 

I was able to create a custom send provider but that applies to all requests regardless of the endpoint in my API so it seems to high level. In the provider I do have access to the response so I can update the header accordingly.

I noticed I can inject the Response object into my controller but I suspect that will make unit testing rather difficult.

## Current Behavior
By default the POST returns a 201 Created

## Expected Behavior
Is there a way to define at the endpoint level what HTTP status code or headers I want to send back with the response? I suspect I will run into something similar if I need to add custom validation and I want to return a specific status code.

**Comment by raymondfeng** [comment]
The controller method can return the http response object if it wants to have full control. For example:
```ts
async myOp(..., 
@inject(RestBindings.Http.RESPONSE) response: Response) {
// write to response
return response;
}
```

**Comment by lapellaniz** [comment]
This will work. I was injecting it at the constructor level but I really only need this functionality at the method level.
