### ISSUE TITLE
Step-by-step instructions to submit a PR

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2280]
## Description / Steps to reproduce / Feature proposal
There is information on how to submit a PR for LB4 / `loopback-next` repo.  As @raymondfeng pointed out, it might be useful to have step-by-step instructions to make a PR, similar to https://www.nearform.com/blog/getting-into-open-source-for-the-first-time/.

From @raymondfeng:
```
Here are some key things to cover:
1. folk `loopback-next` repo
2. git clone the folked repo
3. make changes locally
4. Run `npm it` to make sure everything is working
5. commit changes
6. push commits to the folked repo
7. create a PR
8. Sign CLA
9. go through PR review process
10. make more changes and push back to the folked repo
11. Rebase against latest master@upstream
12. Squash commits to create clean history for the PR
```

## Acceptance Criteria
- [ ] Create a new page that contains the instructions
    - Some existing info for reference: https://github.com/strongloop-internal/loopback-knowledge-base/blob/master/rebasing-community-prs.md
- [ ] Add a pointer at the LB4 contribution page: https://loopback.io/doc/en/contrib/code-contrib-lb4.html
- [ ] Verify that the steps are accurate by either having a new member contribute a PR and go through the outlined steps or us simulating a new user going through the contribution process.

cc @raymondfeng @emonddr

**Comment by emonddr** [comment]
@raymondfeng and I had a meeting to discuss the purpose, content and layout of this document.

 1) There should be a set of instructions for  github `experts` to follow that mainly focuses on things specific to the loopback.

Some things to mention : 

- signing the CLA
- how to amend commit messages
- fixing formatting issues and running : npm run test 
- making sure the CI jobs complete successfully
- the review process : handling multiple commits, rebasing, squashing
- that the PR template Checklist is the `pre-condition` for PR approval
- that the successful run of the CI jobs is the `post-condition` for PR approval

2) There should also be a set of instructions for github beginners to follow that takes them through the github steps, and the things specific to loopback.
