### ISSUE TITLE
LoopBack4 Cache Strategies

### ISSUE THREAD

**Issue by lapellaniz** [strongloop/loopback-next#2295]
The cache documentation I have found is for loopback3 and below using Model.beforeRemote and Model.afterRemote along with the config.json files for the server and model. Is there any guidance or new approach for caching using the new version of loopback?

**Comment by lapellaniz** [comment]
I know this isn't an issue. I am trying to build a cache extension similar to the example log-extension. I have a component, provider, and mixing all wired up. The idea is similar to the log extension that I will decorate methods in my controller and specify cache requirements.

Though similar experience with the log-extension, nothing happens. I can see the component is added along with the decorators but the provider never is instantiated. This happens to my custom cache extension and the log extension. The LogActionProvider constructor is never called and I assume b.c of that, the value function is never called.

I expect that when I make a call to an endpoint that is decorated with the log or (my custom cache decorator), the provider will also run (i.e. either a console.log entry will show up, or data will be returned from cache vs actually entering the controller method).

Am I misunderstanding how these components/providers work?

I have been able to override the "Send" sequence action, so I was considering maybe overriding the "InvokeMethod" sequence action and add caching there but I feel that following the same example as the log extension should work.

**Comment by lapellaniz** [comment]
After enough digging, I figured out I need to inject my custom cache sequence action into my sequence. I can then use it. I ran into an issue where in order for me to retrieve the cache metadata from the decorator used, I need to make a call to getController and getMethod. This is the same pattern as the example log extension. That raises an error if the request is not for a controller. For example if the request is for a static file or even the OpenAPI file. I found I can make a call to `RequestContext.isBound('controller.current')`. This allows me to do a conditional call but feels wrong as I had to search in the framework and understand what "controller.current" is.

Is there a cleaner way to pull controller level decorators from a sequence and have the code not throw an exception when the request isn't for a controller?

I ran into a similar issue with the log extension and plan to log a separate bug for that one.

**Comment by b-admike** [comment]
Hi @lapellaniz Awesome stuff for your custom cache extension work. In terms of having an error with your controller methods, I suggest having a look at https://github.com/strongloop/loopback-next/pull/2218/files to see how to mark your injected getter functions as optional. Can you please link your extension work to this issue so that the LoopBack team is aware and can help?

**Comment by dhmlau** [comment]
@lapellaniz , not sure if you have found a solution already. I'd like to point you to the [greeter application](https://github.com/strongloop/loopback-next/tree/master/examples/greeting-app) that uses [interceptor](https://loopback.io/doc/en/lb4/Interceptors.html) for caching.  Hope it helps.

**Comment by b-admike** [comment]
@lapellaniz Closing this for now (see our comments above for solutions), but feel free to re-open if you still have the same issue(s).
