### ISSUE TITLE
Branding / Site Redux Idea

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#23]
![rebranding-loopback](https://cloud.githubusercontent.com/assets/462228/22477686/d66d9934-e79b-11e6-8956-03bac6da5118.png)

Not committed to doing this quite yet... but here for posterity.

**Comment by superkhau** [comment]
Connect to https://github.com/strongloop/loopback-next/issues/189

**Comment by crandmck** [comment]
Might want to loop in Sumitha as well, since they are planning on using the green color scheme for the new GitHub/Jekyll-based strongloop.com site.  See https://strongloop.github.io/strongloop.com/ (this is the "staging site" very much under development until the domain name is switched over).

**Comment by dhmlau** [comment]
relate to https://github.com/strongloop/loopback-next/issues/189

**Comment by dhmlau** [comment]
@virkt25 pointed out the [IBM Compose site](https://compose.com/) as a good reference.  It's modern and make the things we want to display/promote more prominent.

**Comment by dhmlau** [comment]
@virkt25 , as discussed, could you please take the first stab at what content we should put on the landing page?  Given the timeline we have, we might need to do it in parallel when the design team is working on the design.

**Comment by dhmlau** [comment]
Closing it in favor of #817
