### ISSUE TITLE
OAuth2 Strategy support for the authentication package

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#230]

**Comment by dhmlau** [comment]
Relate to: https://github.com/strongloop/loopback-next/issues/307

**Comment by liudonghua123** [comment]
+1

**Comment by dhmlau** [comment]
Discussion with @raymondfeng @jannyHou @emonddr:
- there are 2 parts in the flow: 1/ get the access token (usually through some UI), 2/ use the access token for API calls. we'll focus on the 2nd part first. 
- we can create an example endpoint for OAuth2 to try it out in the example-shopping repo.

**Comment by jotamora** [comment]
> * focus on the 2nd part first.
> * we can create an example endpoint for OAuth2 to try it out in the example-shopping repo.

@dhmlau has been any advance on it? Thanks.

**Comment by dhmlau** [comment]
@jotamora, sorry about the very late reply! 
PR https://github.com/strongloop/loopback-next/pull/4919 has just landed. @deepakrkris, does it mean we have full for OAuth2 strategy now? Thanks.

**Comment by deepakrkris** [comment]
@dhmlau yes this issue can be closed now.
