### ISSUE TITLE
Is there any video course on loopback 4?

### ISSUE THREAD

**Issue by ankur1163** [strongloop/loopback-next#2305]
I looked everywhere but couldnt find any video course. Is there any available?

**Comment by psaunders** [comment]
This is the 101: https://www.youtube.com/watch?v=POtuWwqDB_E

**Comment by dhmlau** [comment]
@ankur1163, to get started, you can refer to the following links:
https://loopback.io/doc/en/lb4/Getting-started.html
https://loopback.io/doc/en/lb4/todo-tutorial.html

There might be some video resources created by the community, like what @psaunders posted above. 
Is there something in particular you're looking for? 

@psaunders, thanks for sharing the link. :)

**Comment by dhmlau** [comment]
@ankur1163 , i think we've answered your question, and would like to close this issue.  Thanks.

**Comment by HaiderMalik12** [comment]
Hey guys, 
I recently published the Loopback 4 course on Udemy. I am giving you the 92% discount code link. 
[Loopback 4: The Complete Developer's Guide - $9.99](https://www.udemy.com/course/loopback-4-the-complete-developers-guide/?couponCode=LBYTB12)

**Comment by Sampath-Lokuge** [comment]
@HaiderMalik12 Your discount code is not working? Have you updated the course recently?

**Comment by HaiderMalik12** [comment]
https://www.udemy.com/course/loopback-4-the-complete-developers-guide/?referralCode=3542EE74B4D1A2069E69

**Comment by Sampath-Lokuge** [comment]
@HaiderMalik12  Still it shows `$21.99`?

**Comment by HaiderMalik12** [comment]
> @HaiderMalik12 Still it shows `$21.99`?

https://www.udemy.com/course/loopback-4-the-complete-developers-guide/?couponCode=CDBCBE6A8CA0E4103697

**Comment by Sampath-Lokuge** [comment]
Thanks. I'll purchase it @HaiderMalik12

**Comment by souravahmed1** [comment]
> https://www.youtube.com/watch?v=POtuWwqDB_E

3rd class course.
