### ISSUE TITLE
Creating adapter for the plugged in passport strategies

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#2311]
## Description / Steps to reproduce / Feature proposal

We should allow users to plugin custom passport strategies like `passport-jwt`. I tried replacing our own implementation of `jwt` strategy with the community one `passport-jwt` in PR https://github.com/strongloop/loopback4-example-shopping/commit/3cbb0a8b8d41a6db5c5a9ecafa78b3aef6b1aad3 to verify it works with our current `@loopback/authentication` module, the missing part is make the strategy registration flexible.

## Acceptance Criteria

- [x] Allow developers to register their own passport strategy
- [ ] ~A reference for the implementation would be how we register a custom body parser in the application, see [this test case](https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/__tests__/acceptance/request-parsing/request-parsing.acceptance.ts#L47-L64)~ we have the extension point now 🎉 
- [x] Please note that this extension point only open for [`passport`](https://github.com/jaredhanson/passport) based strategies, which means when create the binding key/resolve the strategy name, make sure it's for `passport` particularly.
- [x] The story owner could explorer different approaches other than the way we register custom body parser.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
As I commented in https://github.com/strongloop/loopback-next/issues/2312#issuecomment-469598086, I think our support for Passport strategies should be built on top of a LoopBack-specific extension point described by #2312.

That means we need to implement #2312 before working on this story.

**Comment by bajtos** [comment]
I think this story depends on #2466: Add abstraction for authentication strategy.

**Comment by emonddr** [comment]
Some of this work seems to be occurring in the PR for https://github.com/strongloop/loopback-next/issues/2467.

**Comment by jannyHou** [comment]
> Some of this work seems to be occurring in the PR for #2467.

+1.

If we agree on the rewrite of adapter in the draft PR https://github.com/strongloop/loopback-next/pull/2688, then this story can be closed along with #2467 after the formal version of #2688 get merged

**Comment by jannyHou** [comment]
The new adapter is published as @loopback/authentication-passport@0.1.0, an experimental package 🎉 https://www.npmjs.com/package/@loopback/authentication-passport

We've tried 2 approaches:
- wrapping a passport strategy module like `passport-http`
- wrapping the express middleware `passport`

It turns out the 1st approach is more consistent with non-passport based strategies and we have need more effort to fully support wrapping an express middleware.

Closing it now.
