### ISSUE TITLE
Extension point for registering the authentication strategies

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#2312]
## Description / Steps to reproduce / Feature proposal

Follow the [extension pattern example](links_to_be_add_after_pr_merged) to create extension point for registering multiple authentication strategies.

Background of the story:
Now we implement a new provider in a hardcoded way to perform the authenticate action of the custom jwt strategy created by ourselves, see [custom authentication provider](https://github.com/strongloop/loopback4-example-shopping/blob/master/src/providers/custom.authentication.provider.ts).
This should be an extensible point that people can plugin the actions for both passport and non passport-based strategies.

## Acceptance Criteria

- [x] Create an extension point for authentication strategies
  - [x] Decorate a strategy provider class `AuthenticationStrategyProvider` with `@extensionPoint`
  - [x] The strategy provider class constructor should have a strategy getter decorated with `@extensions` 
   - [x] update the authentication action provider `AuthenticateActionProvider` to use `AuthenticationStrategy` interface and the new strategy provider class
  - [x] Document how to implement & register an auth strategy. Can be light documentation since we already have some documentation discussing extension points and extensions.
- [x] Use "jwt" and "basic" strategies for tests. Not shipping production ready strategies.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
IMO, we should design the extension point for auth strategies in the following way:
- The extension point is LoopBack specific, the strategy interface is defined to match the needs of LoopBack and custom LoopBack strategies. 
- To support Passport-based strategies, we should provide an adapter that will accept a Passport strategy and convert it into LB strategy (that will be part of https://github.com/strongloop/loopback-next/issues/2311 though).

**Comment by bajtos** [comment]
I think this story depends on #2466: Add abstraction for authentication strategy.

**Comment by jannyHou** [comment]
> To support Passport-based strategies, we should provide an adapter that will accept a Passport strategy and convert it into LB strategy

Sounds good to me. There is already an adapter in `@loopback/authenticate` we can borrow.

**Comment by dhmlau** [comment]
@emonddr , with your PR #2763 merged, does it mean this task is done? Thanks.
