### ISSUE TITLE
Design: Import/export bindings from a component

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#232]
Using bindings from a component in an app.

 - [ ] Acceptance test / example how to export bindings and import them into an `Application`

**Comment by raymondfeng** [comment]
See https://github.com/inversify/InversifyJS/blob/master/wiki/container_modules.md

**Comment by superkhau** [comment]
Initial impl on master: https://github.com/strongloop/loopback-next/blob/master/packages/core/src/application.ts#L18-L34
