### ISSUE TITLE
@hasmany parameter not showing in explorer in new version

### ISSUE THREAD

**Issue by techaks** [strongloop/loopback-next#2324]
https://github.com/strongloop/loopback4-example-shopping
check 

check 

> user.model.ts

there is parameter   
```
@hasMany(() => Order)
  orders: Order[];
```

in previous i was able to see in explorer screen but now AFTER UPDATE  IN new version i am not able to see it what is solution to show this

**Comment by techaks** [comment]
@dhmlau  please help

**Comment by dhmlau** [comment]
@techaks, let me make sure if I understand the problem you're having. 
After starting the app for `loopback4-example-shopping`, go to API Explorer (http://localhost:3000/explorer). I go to `POST /users` under `UserController` and was able to see `orders` attribute in the sample data:

<img width="253" alt="screen shot 2019-02-01 at 3 06 13 pm" src="https://user-images.githubusercontent.com/25489897/52146931-2fe16900-2633-11e9-97ee-aacbfb4c3588.png">

Is it what you're expecting but didn't see?

**Comment by techaks** [comment]
Yes

**Comment by dhmlau** [comment]
It seems to be working for me.  I ran `npm ls --depth=0` and below is the LB4 related modules and their versions: 
```
├── @loopback/authentication@1.0.9
├── @loopback/boot@1.0.9
├── @loopback/build@1.2.0
├── @loopback/context@1.4.1
├── @loopback/core@1.1.4
├── @loopback/openapi-v3@1.1.6
├── @loopback/repository@1.1.2
├── @loopback/rest@1.5.2
├── @loopback/service-proxy@1.0.6
├── @loopback/testlab@1.0.4
├── @loopback/tslint-config@2.0.0
```

**Comment by techaks** [comment]
I have solved something has been changed in new version.

├── @loopback/authentication@1.0.11
├── @loopback/boot@1.0.11
├── @loopback/build@1.2.1
├── @loopback/context@1.5.0
├── @loopback/core@1.1.5
├── @loopback/openapi-v3@1.2.0
├── @loopback/repository@1.1.4
├── @loopback/rest@1.5.4
├── @loopback/service-proxy@1.0.7
├── @loopback/testlab@1.0.5
├── @loopback/tslint-config@2.0.0

**Comment by dhmlau** [comment]
Do you mean it doesn't work in the module versions you stated [above](https://github.com/strongloop/loopback-next/issues/2324#issuecomment-459944957)?

**Comment by techaks** [comment]
Yes
