### ISSUE TITLE
Support `json` configuration in model property definition

### ISSUE THREAD

**Issue by angelwithaneye** [strongloop/loopback-next#2336]
## Description / Steps to reproduce / Feature proposal
All model properties are returned, regardless of the json option.

```ts
@property({ json: { out: false } })
email: string;
```

## Current Behavior

All model properties are returned, regardless of the json option.

## Expected Behavior

Properties with decorator property() **with** a spec like:

```ts
@property({ json: { out: false } })
email: string;
```

Should not be returned in the response.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
Hi @angelwithaneye, thank you for reporting the issue. I am afraid LB4 does not support JSON mapping in model properties yet.

cc @raymondfeng

**Comment by angelwithaneye** [comment]
Thanks for reviewing this.  It would be a really nice feature as right now I need to create DTOs for some models which is duplicate work.  This would be a really nice to have.

**Comment by jannyHou** [comment]
Could be related to https://github.com/strongloop/loopback-next/issues/2082
