### ISSUE TITLE
url generation force '0.0.0.0' to be '127.0.0.1'

### ISSUE THREAD

**Issue by noway56** [strongloop/loopback-next#2346]
## Current Behavior
@loopback/dist/src/http-server.js, in class HttpServer, function get url(), the host '0.0.0.0' is forced to be '127.0.0.1'
## Expected Behavior
Be able to use the url http://0.0.0.0:xxx

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dougal83** [comment]
0.0.0.0 is a special address.  Follow protocol and use 127.0.0.1 for loopback.

> 0.0.0.0 is a non-routable meta-address used to designate an invalid, unknown, or non-applicable target (a ‘no particular address’ place holder).

**Comment by emonddr** [comment]
Hello @dougal83 , I would like to help you with your question.

Can you please list the steps to reproduce the particular problem you are experiencing?

Thank you

:)

**Comment by raymondfeng** [comment]
@noway56 `0.0.0.0` is used as a binding ip address for all network interfaces. It's not suitable for urls, which are used by clients to access the http endpoint. Please note `http://0.0.0.0:xxx` does not even work on Windows.

**Comment by jeanmarcprevost** [comment]
Hello, i am confronted with this issue too. My hosting need "0.0.0.0" or "localhost", but not with : "127.0.0.1". The v3 run correctly but the v4 doesn't. Is there a way to run with localhost or "0.0.0.0" ?

**Comment by dougal83** [comment]
> Hello, i am confronted with this issue too. My hosting need "0.0.0.0" or "localhost", but not with : "127.0.0.1". The v3 run correctly but the v4 doesn't. Is there a way to run with localhost or "0.0.0.0" ?

Like[here](https://github.com/strongloop/loopback-next/blob/de8f626480e98854e831a11a0ef9d2f4d0492328/examples/hello-world/index.js#L15) in index.js?  Do you have an example that does not accept it?  What is your hosting environment?

**Comment by jeanmarcprevost** [comment]
```
export async function main(options: ApplicationConfig = {}) {
  options.rest = {
    host: "localhost",
    port: C.PORT
  };

  const app = new MyApplication(options);
  await app.boot();
  await app
    .bind(RestBindings.ERROR_WRITER_OPTIONS)
    .to({ debug: C.DEBUG === "true" });
  await app.start();
```
But in my console, when i run the application, i get : 
```
Server is running at http://127.0.0.1:4400
Try http://127.0.0.1:4400/ping
```
[it works as a charm in local]
My hosting is scalingo.com, it seems like heroku.

**Comment by noway56** [comment]
> Hello @dougal83 , I would like to help you with your question.
> 
> Can you please list the steps to reproduce the particular problem you are experiencing?
> 
> Thank you
> 
> :)



> @noway56 `0.0.0.0` is used as a binding ip address for all network interfaces. It's not suitable for urls, which are used by clients to access the http endpoint. Please note `http://0.0.0.0:xxx` does not even work on Windows.

Thanks for the explanation, my point should have focused on the "customizable IP" for the service, instead of hardly attached to a fixed ip address.

**Comment by noway56** [comment]
> @noway56 `0.0.0.0` is used as a binding ip address for all network interfaces. It's not suitable for urls, which are used by clients to access the http endpoint. Please note `http://0.0.0.0:xxx` does not even work on Windows.

Thanks for the explanation, my point should have focused on the "customizable IP" for the service, instead of being attached to a fixed ip address.

**Comment by emonddr** [comment]
Please see PR `feat(cli): add `--docker` option to generate docker files` https://github.com/strongloop/loopback-next/pull/2437 .

Now, when creating an lb4 application, there is a default option to create a docker file.
![image](https://user-images.githubusercontent.com/6864736/55803195-e1739f00-5aa7-11e9-8ee5-c53742009ae2.png)

The host and port information in index.js is now as follows:
```
const application = require('./dist');

module.exports = application;

if (require.main === module) {
  // Run the application
  const config = {
    rest: {
      port: +(process.env.PORT || 3000),
      host: process.env.HOST,
      openApiSpec: {
        // useful when used with OASGraph to locate your application
        setServersFromRequest: true,
      },
    },
  };
  application.main(config).catch(err => {
    console.error('Cannot start the application.', err);
    process.exit(1);
  });
}
```
and the Dockerfile is set up as:

```
# Check out https://hub.docker.com/_/node to select a new base image
FROM node:10-slim

# Set to a non-root built-in user `node`
USER node

# Create app directory (with user `node`)
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY --chown=node package*.json ./

RUN npm install

# Bundle app source code
COPY --chown=node . .

RUN npm run build

# Bind to all network interfaces so that it can be mapped to the host OS
ENV HOST=0.0.0.0 PORT=3000

EXPOSE ${PORT}
CMD [ "node", "." ]

```

**Comment by dhmlau** [comment]
Closing this issue as resolved.
