### ISSUE TITLE
getting custom defined Field in Model Property definition 

### ISSUE THREAD

**Issue by ghtech** [strongloop/loopback-next#2354]
## Description / Steps to reproduce / Feature proposal
Any way to define custom fields in @property({})   definition in LB4 model 
## Current Behavior
ie:

```ts
export class Device extends Entity {
  @property({
    type: 'string',
    id: true,
  })
  id?: string;  
  @property({
    type: 'string',
    description: 'Site Name Desc',
    minLength: 3,
    maxLength: 20,
    UFieldID: 2000,
  })
  siteName?: string;
  @property({
    type: 'string',
    UFieldID: 2001,
  })
  locationCode?: string;
  // .......
```

when I call `getJsonSchema` it only shows 

```ts
{ title: 'Device',
  properties:
   { id: { type: 'string' },
     siteName:
      { type: 'string',
        description: 'The unique identifier for a product' },
```

and excluded  `minLength`, `maxLength` and `UFieldID` from JSON Object.

## Expected Behavior
Because of this field validation does not work plus I want to use custom UFieldID  to save data according to field ID to different table to maintain change history at the time of Device record Update.

is there any way to get custom fields
Thanks
-Farhan

**Comment by bajtos** [comment]
@ghtech Thank you for sharing your use case with us!

We don't support all JSON-Schema validations yet. Please join the discussion in #1624 where we are keeping track of that feature.

I am closing this issue as a duplicate.
