### ISSUE TITLE
Bash completion script for lb4 CLI

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2358]
Quoting from https://iridakos.com/tutorials/2018/03/01/bash-programmable-completion-tutorial.html

> ### What is bash completion?
> Bash completion is a functionality through which bash helps users type their commands faster and easier. It accomplishes that by presenting possible options when users press the tab key while typing a command.
>
>```
> $ git<tab><tab>
> git                 git-receive-pack    git-upload-archive  
> gitk                git-shell           git-upload-pack     
> $ git-s<tab>
> $ git-shell
>```
>
> ### How it works
> The completion script is code that uses the builtin bash command complete to define which completion suggestions can be displayed for a given executable. The nature of the completion options vary from simple static to highly sophisticated.
>
> ### Why bother
> It is good to provide such a functionality to users:
> 
> - to save them from typing text when it can be auto-completed
> - to help them know what are the available continuations to their commands
> - to prevent errors and improve their experience by hiding or showing options based on what they have already typed

I am proposing to implement bash completion for our `lb4` CLI. Let's start simple with a static completion offering list of CLI commands. We can add more advanced completion later in subsequent iterations.

```
$ lb4<tab><tab>
app          datasource   service
extension    model        example
controller   repository   openapi
```

A proposal for installation instructions:

```
source <(lb4 --completion-bash)
```

See https://iridakos.com/tutorials/2018/03/01/bash-programmable-completion-tutorial.html for a tutorial on how to build bash completion and `npx --shell-auto-fallback bash` for inspiration on how to implement it in JavaScript/Node.js.

**Comment by raymondfeng** [comment]
Check out https://github.com/mklabs/tabtab

**Comment by peanutenthusiast** [comment]
I'm interested in submitting a PR for this!

**Comment by dhmlau** [comment]
@peanutenthusiast, please feel free!  Let me label it as `community contribution` then.

**Comment by noctifer20** [comment]
I've created basic completion with [tabtab](https://github.com/mklabs/tabtab)
And for installation, you have to run something like `lb4 install-completion`.
Is it suitable for cli ?

<img width="734" alt="Screen Shot 2019-08-23 at 7 42 09 PM" src="https://user-images.githubusercontent.com/18212378/63605398-e9f3ee80-c5de-11e9-8640-f8e270eaea64.png">

**Comment by noctifer20** [comment]
cc @bajtos

**Comment by bajtos** [comment]
> I've created basic completion with tabtab

Awesome!

> And for installation, you have to run something like lb4 install-completion.
> Is it suitable for cli ?

If you are referring to the process described in https://github.com/mklabs/tabtab#1-install-completion, then yes!

@noctifer20 could you please open a pull request so that we can discuss the specific details of your implementation? I find it difficult to discuss `lb4 install-completion` based on a high-level description only.

**Comment by bajtos** [comment]
Closing as done via #5296. Thank you @spirAde for contributing the feature! ❤️
