### ISSUE TITLE
Feature, Getting loopback can be pack by webpack

### ISSUE THREAD

**Issue by lygstate** [strongloop/loopback-next#2366]
## Description / Steps to reproduce / Feature proposal
loopback4 are already rewritten with TypeScript, that's should be wonderful
if loopback4 can be use webpack to pack into a single file:)

## Current Behavior
There is no way to do that, there is a concept of projectDir.
If we need webpack, we need have a way to deal with it.

## Expected Behavior
Webpack all dependencies of loopback4.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by baswag** [comment]
Would really love to have such a feature, especially when managing multiple Loopback Applications and other packages in a monorepo. @bajtos @raymondfeng

**Comment by bykeat** [comment]
I am user of webpack for deployment to MongoDB Stitch Hosting & Firebase with React framework for the front-end. I hope to see webpack able to support for LB4 as I'm currently started to learn TypeScript to migrate LB3 to LB4.

**Comment by achrinza** [comment]
Thanks for the suggestion! It's definitely a useful feature, and others have suggested something similar: #257. Webpack isn't really my forte, so I can't really help much in this area.

But if you want to contribute to LoopBack 4, feel free to look at [Contributing to LoopBack 4](https://loopback.io/doc/en/lb4/code-contrib-lb4.html) for info on how to do so. We welcome as all community contributions, big or small!

**Comment by dhmlau** [comment]
With PR #6356 landed, can this issue be closed? Thanks.
