### ISSUE TITLE
testlab: add helpers for testing HTTP servers

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#237]
- [x] Move code from `packages/loopback/test/support` to `packages/testlab`

- [x] Drop `Client` class in favour of [supertest](https://www.npmjs.com/package/supertest)

- [ ] Add helper APIs for setting up server + supertest:

  - [ ] Given a LoopBack app,  start it on an ephemeral port (`listen(0)`), wait until it's listening and then return a `supertest` instance pointing to this server. (This is useful for testing LoopBack apps.)
  - [x] Given a low-level `http.Server` instance, start it on an ephemeral port (`listen(0)`), wait until it's listening and then return a `supertest` instance pointing to this server. (This is useful e.g. for testing SwaggerRouter in isolation.)

  These two helpers should share most of the implementation code.

Background info from #135:
> - Rework tests to use supertest instead of request. Request's interface is already showing limitations, it's time to move to something better while the amount of needed changes is low.
> - Consider adding supertest to testlab, this makes sense when we also add helpers for setting up HTTP server for a loopback app/router and returning a supertest instance connected to that server.

cc @ritch @superkhau

**Comment by superkhau** [comment]
+1 and p1ing this as it will help with so many tests.

**Comment by ritch** [comment]
+1 for removing `request` blockers so we can user helpers... but we should have our own wrapper that is the equiv of supertest for lbn apps.

**Comment by ritch** [comment]
I would change the approach to this:

> Add helper APIs for setting up server + supertest:

instead we should do

> Add helper APIs for setting up server + superagent:

**Comment by bajtos** [comment]
> I would change the approach to this:
>> Add helper APIs for setting up server + supertest:

> instead we should do
>> Add helper APIs for setting up server + superagent:

@ritch let's discuss. Why do you perfer superagent over supertest?

What I like about supertest is the addition of `.expect()` API, which makes it easier to write assertions in the tests.

Compare supertest-based code

```js
return supertest(app).get('/foo')
  .expect(200)
  .expect('Content-Type', /json/);
  .expect({ok: true});
```

with superagent based code

```js
const result = await supertest(app).get('/foo');
expect(result).to.have.property('statusCode', 200);
expect(result.headers).to.have.property('content-type').match(/json/);
expect(result.body).to.deepEqual({ok: true});
```

**Comment by superkhau** [comment]
Do they both take Express `app`s? That makes it interesting because our `app` may not work OOB?

**Comment by bajtos** [comment]
> Do they both take Express apps? That makes it interesting because our app may not work OOB?

That's a good point. AFAICT, superagent does not provide any helpers for starting the server app, that's another addition provided by supertest.

And yes, supertest cannot start a LoopBack.next app, we need to provide our own helper for that. Fortunately, supertest accepts a base URL of an already running app, thus there is a way forward.

```ts
// a mockup
export async function request(app: Application): Supertest {
  await app.start();
  const info = await app.info();
  const url = info.url;
  return supertest(url);
}
```

**Comment by bajtos** [comment]
> Given a LoopBack app, start it on an ephemeral port (`listen(0)`), wait until it's listening and then return a `supertest` instance pointing to this server. (This is useful for testing LoopBack apps.)

Unfortunately, the `Application` class does not expose any API for starting a server, one has to create a `Server` and attach the app manually. Because of that, it's difficult to write a test helper for making requests to a generic LB.next app. 

Since the primary goal of this task was to get rid of `core/test/support`, I am leaving the task of adding a helper for creating a client for an app for later.
