### ISSUE TITLE
Register Express middleware per application

### ISSUE THREAD

**Issue by sanadHaj** [strongloop/loopback-next#2396]
As a user migrating from Express, or simply wishing to leverage an existing Express middleware in lb4 application, I would like to enable this middleware to be executed before/after lb4 route. 

Consider the following definition in an Express app:
```ts
// before route 
app.use(function (req, res, next) {
  console.log('Time:', Date.now())
  next()
})

app.get('/api/info', 
  function getInfo(req, res, next) {
    // the route
  });

// after route 
app.use(function (req, res, next) {
  console.log('Time:', Date.now())
  next()
})
``` 
loopback 4 currently not support before/after route/requestHandler  middleware.

I use the following short term workaround to support after route middleware 

```ts
export async function setupMiddleware(restApp: Application): Promise<void> {
    const expressApp = restApp.restServer.requestHandler;
    (<express.Application>expressApp).use(async (req,res,next)=>{
        // ...
        next();
    });
}

```

**Comment by sanadHaj** [comment]
just an idea : 
middleware directory that holding all  middlewares classes each class should have PreRoute and postRoute method (PreRoute before invoke controller , postRoute after invoke the controller).
 with keeping in minds the order of the middleware.

```ts
class MyMiddleWare{
 readonly order =  1;
  preRoute(req,res,next){
    next();
  }
  postRoute(req,res,next){
    next(); 
  }
}
```

**Comment by sanadHaj** [comment]
@bajtos  following our discussion  #2035

lets discuss high level first ,
 i think loopback should support this feature

**Comment by bajtos** [comment]
Thank you @sanadHaj for the comments. We already have a different GH issue opened to keep track of this feature - see #1293, let's close this one as a duplicate. Feel free to re-post your comments above to #1293.

Please note that as a temporary workaround, you can mount the LB4 app on a new Express instance and then register the app-wide middleware on that Express instance. See https://github.com/strongloop/loopback-next/issues/1982 and https://loopback.io/doc/en/lb4/express-with-lb4-rest-tutorial.html.

**Comment by bajtos** [comment]
> I would like to enable this middleware to be executed before/after lb4 route.

#1293 is for executing middleware before LB4 routing kicks in.

We want to allow developes to register routing middleware handling additional non-LB4 routes too, see https://github.com/strongloop/loopback-next/issues/2389 (already in progress).
