### ISSUE TITLE
Allow multiple models with same name

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#24]
- [ ] - Models should be classified with namespaces, preferrably in the java style package names.
- [ ] - Packaging (folder) paths like /common/models or loopback/models can be name spaces
- [ ] - this will allow having models with same names to be configured

**Comment by superkhau** [comment]
@raymondfeng Does your proposal at https://github.com/strongloop/loopback-next/pull/392 already consider this? (ie. is this safe to close?).

**Comment by bajtos** [comment]
>  Does your proposal at #392 already consider this (is issue this safe to close)?

Not really. The current DefaultCrudRepository is building a backing `PersistedModel` that's sharing the same model name with the TS-based `Entity` class.

**Comment by dhmlau** [comment]
Discussion with @bajtos @raymondfeng: 
- allow same model definition to be used to connect to different database
- model has to be uniquely accessible.  Introduce qualified name (namespace).
- it could be current limitation of juggler
- a spike might be needed.
