### ISSUE TITLE
Publish working versions of all alpha packages

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#240]
Connect to #159

- [x] Mark codehub as private #242 
- [x] @loopback/testlab #241 
- [x] @loopback/core

## Acceptance criteria

```js
const Application = require('@loopback/loopback').Application;
const app = new Application();
```

Should work in https://github.com/strongloop/loopback-next-quick-start.
- PR at https://github.com/strongloop/loopback-next-quick-start/pull/2

**Comment by jonathan-casarrubias** [comment]
Just a quick comment, why using @loopback/loopback as package, I would rather say @loopback/core is best, is more self explanatory and less redundant.

````js
const Application = require('@loopback/core').Application;
const Authentication = require('@loopback/authentication');
const app = new Application();
````

**Comment by superkhau** [comment]
@jonathan-casarrubias @loopback/core renaming is happening and part of #179

**Comment by superkhau** [comment]
>Also I would rather prefer to see import examples rather than require examples

I also agree, but these are minimal acceptance criteria to ensure backwards compat with JS since we're advocating both (ie. if it works with require, it'll work with TS import). I'll pass the suggestion along, TY. ;)

**Comment by superkhau** [comment]
@jonathan-casarrubias I published it all, should work the way you're expecting. Can you help me review the [installation wiki](https://github.com/strongloop/loopback-next/wiki/Installation) and provide some feedback? ;)

**Comment by jonathan-casarrubias** [comment]
@superkhau cool... Sure I'll check it right now and see how it works, I'll come up with any feedback I might have...

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Well first thing I can see is that you published the latests version under `@loopback/core` which is awesome, but the wiki is still referring to `@loopback/loopback`

**Comment by superkhau** [comment]
@jonathan-casarrubias Haha, sorry I'm updating it as we speak. ;) Would you like to help edit? I think we'll need to unpublish @loopback/loopback

**Comment by jonathan-casarrubias** [comment]
Sure @superkhau, if you give me access I can send a pull request for any conflict I find like this one

**Comment by superkhau** [comment]
@jonathan-casarrubias Can you try sending a pull? I added loopback.next contributor perms.

**Comment by superkhau** [comment]
Closing this issue as done.
