### ISSUE TITLE
SQL query map fields

### ISSUE THREAD

**Issue by sayavo** [strongloop/loopback-next#2405]
Hi,

I'm actually doing a SQL query to join the different relation between my models inside my repository and I'm querying on a PostgreSql database like this:

`  public findByPortfolioOrganization(filter: Filter, options: Options): Promise<FundAccess[]> {
    let self = this;
    let sqlStmt = "SELECT FundAccess.*, Fund.* AS Fund, Organization.* AS Organization FROM " + 'FundAccess JOIN Fund on (FundAccess.portfolio_identifying_data = Fund._1_Portfolio_identifying_data) JOIN Organization on (Fund.organizationId = Organization.id) where Organization.id = 2';

    return new Promise<FundAccess[]>(async function(resolve, reject) {
      await self.db.connector!.execute!(sqlStmt, function(err: any, results: FundAccess[]) {
        if (err !== null) return reject(err);
        resolve(results);
      });
    });
  }`

So it's working and I have this results:
`[ { id: 2,
    userid: 7,
    portfolio_identifying_data: 'FR222222222',
    format: 'TPT V4',
    frequency: '17',
    max_delivery_buz_days: 1,
    servicer: 2,
    status: 'PENDING',
    comment: 'OKAY',
    _1_portfolio_identifying_data: 'FR222222222',
    _3_portfolio_name: 'FONDS ACTIONS 2',
    _4_portfolio_currency_: 'EUR',
    organizationid: 2,
    name: 'TestOrga',
    updateat: '2019-02-15T15:25:36.067Z',
    createdat: '2019-02-15T15:25:36.067Z' } ]`

But I would like the result to be something like this:
`[ { id: 2,
    userid: 7,
    portfolio_identifying_data: 'FR222222222',
    format: 'TPT V4',
    frequency: '17',
    max_delivery_buz_days: 1,
    servicer: 2,
    status: 'PENDING',
    comment: 'OKAY',
    Fund: { _1_portfolio_identifying_data: 'FR222222222',
      _3_portfolio_name: 'FONDS ACTIONS 2',
      _4_portfolio_currency_: 'EUR',
      organizationid: 2,
    }
    Organization: { name: 'TestOrga',
    updateat: '2019-02-15T15:25:36.067Z',
    createdat: '2019-02-15T15:25:36.067Z' }
   } ]`
Following the name of the models to be separated by model name inside my object returned. Is it possible to get this results with the sql command ?
I could separated the object by hands but it's not the solution I expect. I would like to do the query with less operation possible.

Thanks for the reply.

## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by agnes512** [comment]
@sayavo Hi, IIUC, you'd like to get a `Fund` instance with related `Organization` with `organizationid =2` =>
```
[
  {  id = 7,
     // other attributes
    organizationId = 2,
    Organization: {
      id = 2,
      // other attributes
    }
  }
]
```

You can set a relation for these 2 models. For example, a `Fund` belongs to an `Organization`. And named this relation `organization`. You can find the details of setting up relations on our site [Relations](https://loopback.io/doc/en/lb4/Relations.html) and how to query data in repository level in the [Querying related models](https://loopback.io/doc/en/lb4/BelongsTo-relation.html#querying-related-models) section. 

For you case, once you setup the relation and enable the `inclusionResolver` (you can find the explanation in the links above), you will be able to query data with `fundRepository` class:
```
fundRepository.findById(2, {include: [{relation: 'organization'}]});
```

Let me know if it helps, thanks.

**Comment by sayavo** [comment]
Hi @agnes512,

thanks for the reply I manage to find a solution.
