### ISSUE TITLE
How to pass options to a class using @inject

### ISSUE THREAD

**Issue by adesege** [strongloop/loopback-next#2407]
## Description / Steps to reproduce / Feature proposal
I have a class which I've bind to the context.
## Current Behavior
When I pass an options object to the second argument of @inject, I get `Cannot resolve injected arguments for Http.[0]: The arguments[0] is not decorated for dependency injection, but a value is not supplied` in the console.

For example
```js
@inject(HTTP_BINDING_KEY, {
      baseUrl: '/external',
    })
protected http: Http

// application.ts
this.bind(HTTP_BINDING_KEY).toClass(Http);
```
## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
From the error, your Http class constructor's first argument is not decorated for injection. Can you share your `Http` class code here?

**Comment by adesege** [comment]
Thanks for the response, @raymondfeng. Here's the class. I'm trying to create a wrapper for Axios module

```js
import axios, { AxiosInstance, AxiosRequestConfig } from "axios";

export const HTTP_BINDING_KEY = "http";

export class Http {
  protected http: AxiosInstance;
  constructor(options: AxiosRequestConfig) {
    this.http = axios.create({ ...options });
  }

  async get(path: string) {
    return await this.http.get(path);
  }

  // tslint:disable-next-line:no-any
  async post(path: string, payload?: any) {
    return await this.http.post(path, payload);
  }
}
```

**Comment by raymondfeng** [comment]
If you want to inject `options: AxiosRequestConfig`, you can bind options to a different key such as `http.config`. 
```ts
constructor(@inject('http.config') options: AxiosRequestConfig) {
    this.http = axios.create({ ...options });
  }
```

BTW, we're working on a simpler solution at https://github.com/strongloop/loopback-next/pull/2259.

**Comment by adesege** [comment]
Thanks but I don't think that is elegant. First, I need to bind and inject the Http class before injecting the `http.config` options. I'm looking for a solution that can enable me to do that with just one `@inject`.

Also, can you point me to how to create a decorator that passes a value to a variable like `@param.string() userId: String`. Checked the different packages on loopback-next but couldn't find a solution.

**Comment by adesege** [comment]
Also, can you explain what the second parameter of `@inject` does? I suppose the value is passed to the constructor of the injected class?

**Comment by adesege** [comment]
> If you want to inject `options: AxiosRequestConfig`, you can bind options to a different key such as `http.config`.
> 
> ```ts
> constructor(@inject('http.config') options: AxiosRequestConfig) {
>     this.http = axios.create({ ...options });
>   }
> ```
> 
> BTW, we're working on a simpler solution at #2259.

I am currently getting this error message `The key http.config was not bound to any value.`

**Comment by raymondfeng** [comment]
The 2nd arg of `@inject` can be seen at https://github.com/strongloop/loopback-next/blob/master/packages/context/src/inject.ts#L41. It provides options for inject to behave, such as `optional` or a custom `resolve` function. Please note the custom `resolve` function can access the metadata, see an example at: https://github.com/strongloop/loopback-next/blob/master/packages/context/src/__tests__/acceptance/class-level-bindings.acceptance.ts#L275-L283.

**Comment by raymondfeng** [comment]
Use the following:
```ts
constructor(@inject('http.config', {optional: true}) options: AxiosRequestConfig) {
    this.http = axios.create({ ...options });
  }
```

**Comment by adesege** [comment]
Thanks. I will add tests to the list of places to check to get clarification.

> Also, can you point me to how to create a decorator that passes a value to a variable like `@param.string() userId: String`. Checked the different packages on loopback-next but couldn't find a solution.

cc: @raymondfeng

**Comment by adesege** [comment]
The `options` parameter is returning `undefined`. I saw the test case you shared but in my case, the options parameter is dynamic depending on which controller will be using.

**Comment by raymondfeng** [comment]
> The `options` parameter is returning `undefined`

That's expected for optional injection if the key is not found in the context.

Your use case seems to be different. I would suggest that you inject a factory class and use the options to create an instance in your controller.

**Comment by adesege** [comment]
Can you give me a sample use case please? That could point me in the right direction

**Comment by raymondfeng** [comment]
Something like:
```ts
@inject('http.factory') 
protected factory: HttpFactory;

...

const http = factory.create({baseUrl: '/external'});
```

**Comment by dhmlau** [comment]
@adesege, we believe we've resolved your question. I'd like to close this issue now. If you're still encountering this issue, please open a new issue. Thanks!
