### ISSUE TITLE
Automatically Disable Serving OpenAPI Spec When Explorer Is Disabled?

### ISSUE THREAD

**Issue by shadyanwar** [strongloop/loopback-next#2410]
## Description / Steps to reproduce / Feature proposal
When the explorer is disabled as per the [docs](https://loopback.io/doc/en/lb4/Server.html), the endpoint `/openapi.json` still serves OpenAPI Spec. I think this defeats the purpose of disabling the explorer.

Meanwhile, how to disable serving the OpenAPI Spec? The docs don't say.

**Comment by jannyHou** [comment]
Interesting, IMO enabling "explorer" and enabling "endpoint that returns the openapi.json file" are separate features. 

For example, other component like `oasgraph` can still consume the openapi specification exposed by that endpoint.

Is there any particular reason to disable `/openapi.json`?
To be more general, we can allow users disable arbitrary endpoints by having a black list.

**Comment by shadyanwar** [comment]
@jannyHou 

> For example, other component like `oasgraph` can still consume the openapi specification exposed by that endpoint.

Good to know.

> Is there any particular reason to disable `/openapi.json`?

Yes, security. It is publicly accessible. If there is a way to bind it with authentication, I will follow it. If not, I will want it disabled.

> To be more general, we can allow users disable arbitrary endpoints by having a black list.

That would be nice. I was surprised this gets generated. Are there any 'arbitrary endpoints' that I didn't ask for that get made?

**Comment by jannyHou** [comment]
@shadyanwar I see, the endpoint `/openapi.json` is served differently than controller endpoints. I think we can make [this line](https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/rest.server.ts#L229) configurable. 

For example: don't serve openapi specification when [`endpointMapping`](https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/rest.server.ts#L899) implies it's hidden.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/pull/2470

**Comment by bajtos** [comment]
Closing as done.
