### ISSUE TITLE
Status 413 : Payload Too large

### ISSUE THREAD

**Issue by mightytyphoon** [strongloop/loopback-next#2415]
## Description
Error on big files, there should be an option to put file size higher on post requests.

## Current Behavior
After post request :

`HttpErrorResponse {headers: HttpHeaders, status: 413, statusText: "Payload Too Large", url: "http://localhost:3000/api/videos",  …}`

Hi, 
I searched (and I am still searching) about this, but I can't find where to change file size in lb4. 

In lb3 there was the 'maxFileSize'. I think I will implement a streaming or something later on production but for now I just need to post big files since I can already read videos from the server, I just want to upload them.

Thanks.

**Comment by jannyHou** [comment]
@mightytyphoon Try provide the `maxFileSize` option in the request body parser option:

```ts

app.bind(RestBindings.REQUEST_BODY_PARSER_OPTIONS).to({limit: a_number_large_enough})
```

See related [source code implementation](https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/body-parsers/body-parser.json.ts#L25)

Let me know if that works.

**Comment by mightytyphoon** [comment]
@jannyHou wow, thanks, worked first try with : 
  `app.bind(RestBindings.REQUEST_BODY_PARSER_OPTIONS).to({limit: '50mb'})`
in index.ts

```
import {Application} from './application';
import {ApplicationConfig} from '@loopback/core';
import * as path from 'path';
import { RestBindings } from '@loopback/rest'; // import added (obviously)
export {Application};


const PORT = process.env.SERVER_PORT || 3000;


export async function main(options: ApplicationConfig = {rest: {port: PORT}}) {
  const app = new Application(options);
  await app.boot();
  await app.start();
  app.bind(RestBindings.REQUEST_BODY_PARSER_OPTIONS).to({limit: '50mb'}) // line added
  app.static('/', path.join(__dirname, '../../public'));
  app.static('/api/videos' , path.join(__dirname , '../../disk/videos'));

  console.log(__dirname);

  const url = app.restServer.url;
  console.log(`Server is running at ${url}`);
  console.log(`Try ${url}/ping`);

  return app;
}
}
```

Have a great day.

**Comment by raymondfeng** [comment]
See https://loopback.io/doc/en/lb4/Extending-request-body-parsing.html

**Comment by raymondfeng** [comment]
Maybe we should make it possible to configure via `RestServerConfig` declaratively.

**Comment by mightytyphoon** [comment]
@raymondfeng well, it was really my bad on this one, the solution was in the documentation but I was looking for something like loopback 3, with a json declaration. Anyway I guess it's also a good idea to have the possibility of declaring it via RestServerConfig.

Thanks.

**Comment by izidizi** [comment]
Doesn't work for me. Could it be due to my app is created as RPC-server?
https://github.com/strongloop/loopback-next/tree/master/examples/rpc-server

**Comment by emonddr** [comment]
@izidizi , the rpc server example is not for production, it is a dummy server just for illustration purposes and is an express server.

I guess if you wanted to set the file limit on this dummy server example (rpc server), you could do this:

```
...
import * as bodyParser from 'body-parser';

export class RPCServer extends Context implements Server {
  private _listening = false;
  _server: http.Server;
  expressServer: express.Application;

  constructor(
    @inject(CoreBindings.APPLICATION_INSTANCE) public app?: Application,
    @inject('rpcServer.config') public config?: RPCServerConfig,
  ) {
    super(app);
    this.config = config ?? {};
    this.expressServer = express();
    this.expressServer.use(bodyParser.json({limit: '5mb'}));
    rpcRouter(this);
  }
```

to set a limit, since the server used here is a plain express server.

**Comment by izidizi** [comment]
i see, thanks!

**Comment by faris-mobile89** [comment]
Does not work for me. I'm using LB4

app.bind(RestBindings.REQUEST_BODY_PARSER_OPTIONS).to({limit: '50mb'})


@raymondfeng the document does not tell me where to add the files. and also the modules are missing, can't be imported such as "BodyParserMiddleware".

https://loopback.io/doc/en/lb4/Extending-request-body-parsing.html

**Comment by emonddr** [comment]
@faris-mobile89 , please provide a minimal application in a github repo that demonstrates the issue you are having. Then we can investigate. thx.
