### ISSUE TITLE
Mongo unique document field

### ISSUE THREAD

**Issue by rabota-alexey** [strongloop/loopback-next#2418]
In my model I check that **username** field should be unique:
```@model()
export class User extends Entity {
  @property({
    id: true,
    index: true,
    generated: true,
  })
  id: string;

  @property({
    type: 'string',
    required: true,
    index: {unique: true},
  })
  username: string;
}
```

But when the User collection is created, the only **Id** index is created, without **username** index.

If I add unique index manually in database via 
`db.User.createIndex( { "username": 1 }, { unique: true } )`
then the database answers  
> Unhandled error in POST /users: 500 MongoError: E11000 duplicate key error index

How do I handle answers from Mongo in case of exception? Because client side receives

> 
    "error": {
        "statusCode": 500,
        "message": "Internal Server Error"
    }

**Comment by rabota-alexey** [comment]
2 days no response
```
begin
goto NestJs
end

**Comment by mikeevstropov** [comment]
Same problem
