### ISSUE TITLE
How to configure qs

### ISSUE THREAD

**Issue by ludohenin** [strongloop/loopback-next#2420]
I understand that LB is using `qs` under the hood to parse query string. Is there a way, through binding or other mean, to configure qs as it only parses object for a depth of 5. The rest is kept stingified (see https://github.com/ljharb/qs#parsing-objects) ?

**Comment by raymondfeng** [comment]
I think we need to make this line configurable via RestServerOptions - https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/rest.server.ts#L206

**Comment by raymondfeng** [comment]
@ludohenin Are you willing to contribute a patch?

**Comment by ludohenin** [comment]
@raymondfeng yes I can try to propose you something.
