### ISSUE TITLE
[SPIKE] Extract strings from @loopback/cli package

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2428]
## Description / Steps to reproduce / Feature proposal
Extract strings from `@loopback/cli` package.  Since it is written in JavaScript, we can continue to use `strong-globalize` to extract the string. 

## Acceptance Criteria
- [x] Run `slt-globalize` command to extract the string
- [x] Do some sniff tests to make sure it's working on another language.

## Reference
_It works for LB3, not sure if it works the same for LB4_
To test it:
- you can set the `LANG` variable to one of the locales: https://docs.oracle.com/cd/E23824_01/html/E26033/glset.html
e.g. `export LANG=zh_CN.UTF-8`
- restart
- run the cli and the specified language should show up

**Comment by emonddr** [comment]
strongglobalize doesn't understand TypeScript.
So we will focus on CLI for now.

**Comment by emonddr** [comment]
Utilize strongglobalize exactly as it was used in LB3, and see how it goes. For now.

**Comment by dhmlau** [comment]
Closing as done.
