### ISSUE TITLE
Add a option to disable calling to this.component(RestComponent);

### ISSUE THREAD

**Issue by lygstate** [strongloop/loopback-next#2439]
https://github.com/strongloop/loopback-next/blob/c77ac3899c73939f38c26274c5dc2b6b55bfed85/packages/rest/src/rest.application.ts#L67

So we can reuse RestApplication  with custom RestComponent and RestServer

**Comment by raymondfeng** [comment]
@lygstate Can you explain why you need to customize RestComponent? We can make things more flexible if your use case is common to our users.

**Comment by lygstate** [comment]
for example， i want to use the underlying express to host angular site that have angular route support along with specify the basepath， currently， its have three issue， no way to specify the static site without basepath， second， no way call express.all API， finally, have no way to use serve -index with express

**Comment by raymondfeng** [comment]
@lygstate We're improving express integration in a few perspectives:

- https://github.com/strongloop/loopback-next/pull/2306
- https://github.com/strongloop/loopback-next/pull/2423
- https://github.com/strongloop/loopback-next/pull/2434
- https://github.com/strongloop/loopback-next/pull/2387 (merged)
