### ISSUE TITLE
Create self-hosted SOAP service for test

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2444]
## Description / Steps to reproduce / Feature proposal
For SOAP service related tests, we rely on external soap services.  Those services might become unavailable for a short period of time or permanently.  We should create our own SOAP service running it in a container for our CI.  This work can be reused in our tests for `strong-soap` and other repos. 

### Acceptance Criteria
- [x] Create SOAP service that can be run in a docker container
- [ ] Use this container for CI in `loopback-next` repo, including updating tests.

Stretch goal:
- [ ] Use this container for CI in `strong-soap` repo.

**Comment by dhmlau** [comment]
From @raymondfeng 
https://www.ibm.com/support/knowledgecenter/en/SSAW57_8.5.5/com.ibm.websphere.samples.doc/ae/sample_jax_ws.html

**Comment by dhmlau** [comment]
@raymondfeng has created the soap service (source code: https://github.com/raymondfeng/calculator-webservice).  So i've checked off the first checkbox.  The next step is to hook it up with CI.

**Comment by raymondfeng** [comment]
@rmg Do we have hosting resources to run the soap web service in IBM cloud? I was able to deploy to my IBM account and it's a trial.
