### ISSUE TITLE
Autorebuild

### ISSUE THREAD

**Issue by guitarhero1** [strongloop/loopback-next#2462]
Please, how can I launch app, that will be rebuilt after changes in code? I'm not able to figure out...

**Comment by shadyanwar** [comment]
Some ideas were discussed in https://github.com/strongloop/loopback-next/issues/2242. The issue is still open though.

**Comment by guitarhero1** [comment]
up

**Comment by dhmlau** [comment]
To get everything in one place, let's continue the discussion in #2242. 
Closing this issue in favor of #2242.
