### ISSUE TITLE
Todo-List-Todo Controller example missing

### ISSUE THREAD

**Issue by wmlutz** [strongloop/loopback-next#2465]
I believe the last code snippet here: [https://loopback.io/doc/en/lb4/todo-list-tutorial-controller.html](https://loopback.io/doc/en/lb4/todo-list-tutorial-controller.html) has the wrong file example. It has Todo-List Controller and not Todo-List-Todo Controller.

**Comment by nabdelgadir** [comment]
The completed `TodoListTodo` controller file is linked underneath the completed `TodoList` controller, but I understand how that can be confusing. Do you want to submit a PR to improve our docs? See https://loopback.io/doc/en/contrib/doc-contrib.html.
