### ISSUE TITLE
Refactor the authentication action to be a common one.

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#2467]
## Description

Refactor the authentication action to be a common one that could perform `authenticate` for both non-passport based strategies and passport based strategies.

### Acceptance criteria 

- [ ] Refactor [`action`](https://github.com/strongloop/loopback-next/blob/master/packages/authentication/src/providers/authentication.provider.ts#L44) so that it could perform any strategy's authenticate method, not only passport based ones.
  - The returned strategy should be described using the `AuthenticationStrategy` interface created in #2466

**Comment by bajtos** [comment]
Isn't this a necessary part of #2466: Add abstraction for authentication strategy? I mean what is a new abstraction good for, when it's not used by the authentication action?

**Comment by jannyHou** [comment]
I was trying to split the abstraction story into separate ones, honestly without working on the code I couldn't say for sure does the auth action have to be refactored together with the auth strategy interface 😞

**Comment by emonddr** [comment]
May involve the work needed in #2311

**Comment by dhmlau** [comment]
@emonddr @jannyHou, now that PR https://github.com/strongloop/loopback-next/pull/2688 has landed, is this task done?
