### ISSUE TITLE
Spike: Create a custom Sequence in JSLB4

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#2475]
Follow up task for https://github.com/strongloop/loopback-next/issues/1978.

**Acceptance criteria**

a. Should be created as a class
b. Demonstrate usage with [JSLB4 Application class](https://github.com/strongloop/loopback4-example-javascript/blob/class-factory/server/application.js)

**Comment by bajtos** [comment]
Renamed the story to "Spike: Create a **custom** Sequence in JSLB4". 

I think it's important to change the default request processing in the new Sequence class, otherwise there is no point in having a custom sequence IMO. To keep this simple, I am proposing to add a minimal request logging.

```ts
class MySequence {
  // ...

  async handle(context: RequestContext) {
    try {
      const {request, response} = context;
      const route = this.findRoute(request);
      const args = await this.parseParams(request, route);
      const result = await this.invoke(route, args);
      this.send(response, result);
    } catch (error) {
      this.reject(context, error);
    }

    // Example log:
    //   GET /products 200 OK
    console.log(
      request.method,
      request.url,
      response.statusCode,
     response.statusMessage,
    );
  }
```

**Comment by hacksparrow** [comment]
Closing as per the decision taken in https://github.com/strongloop/loopback-next/issues/2567.
