### ISSUE TITLE
Spike: Create Model in JSLB4

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#2476]
Follow up task for https://github.com/strongloop/loopback-next/issues/1978.

**Acceptance criteria**

a. Should be created as a class
b. Should be automatically loaded in the LB4 app
c. Should be able to describe model properties
d. Should show up on Explorer and should be successfully interactive

**Comment by bajtos** [comment]
> Should be automatically loaded in the LB4 app

Please note that models are not loaded by LB4 apps. They mostly provide type information and data schema, and as such are loaded via `require()`.

> Should show up on Explorer and should be successfully interactive

The interactions are provided by Repositories, the REST API is provided by Controllers. Model is just a data schema.

The part I find important here: The code building OpenAPI spec from Model classes should recognize models created from JavaScript and correctly process their LDL definitions.
