### ISSUE TITLE
Spike: Create Repository in JSLB4

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#2477]
Follow up task for of https://github.com/strongloop/loopback-next/issues/1978.

**Acceptance criteria**

a. Should be created as a class
b. Should be automatically loaded in the LB4 app
c. Should have access to a specified Model
d. Should expose CRUD methods to interact with the Model
e. Should allow custom methods to be added, with access to:
  i. The LB4 request object
  ii. A Model

**Comment by bajtos** [comment]
One more thing to consider, I am not sure if it belongs here or to DI-related story #2473: we need a way how to customize the datasource configuration used by the repository.

In TypeScript, this is achieved via dependency injection:
- DataSource config is loaded from `datasources/{name}.json` and bound in Context
- For each DataSource, we have a custom class that receives its config via DI, defaulting to loading the config directly from the JSON file.
- Each repository class receives the DataSource instance to use via DI, defaulting to creating a new instance of the DataSource class created above.

The solution above is an implementation detail, we can use different approach in JavaScript. Here are the stories that are important for app developers:

- As an app developer, when running my app in test/staging/production environment, I want to customize my datasource configuration based on values supplied via ENV variables (see https://12factor.net).
- As an app developer, I want the option to use custom datasource configuration (connection string) when running my automated test suite via `npm test` on developer machines.
