### ISSUE TITLE
Request a loopback connector to interact api described by OpenAPI 3

### ISSUE THREAD

**Issue by yuzhebj** [strongloop/loopback-next#2493]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)
A connector to enable loopback app (loopback 3 or loopback 4) to interact with API described by **OpenAPI 3** is necessary, since  **loopback4** is using OpenAPI 3 as the API spec. Or is there any other project working on this issue?

### Expected result
API described by OpenAPI 3 can be treated as data source by using a connector.

### Additional information (Node.js version, LoopBack version, etc)
node.js: v 10
loopback: v3 or v4

**Comment by dhmlau** [comment]
Transferring to `loopback-next` repo since it's related to LB4. 
@yuzhebj , we have `lb4 openapi` command that generates LB4 artifacts from OpenAPI spec.  https://loopback.io/doc/en/lb4/OpenAPI-generator.html.  Is it what you're looking for? 

cc @raymondfeng

**Comment by yuzhebj** [comment]
@dhmlau Thanks for your reply first. But the `lb4 openapi` command is not what I am looking for. 
In loopback3, the `loopback-connector-swagger` can help to interact with API described by **Swagger 2** from other micro-service project. And now we have a new loopback4 project, and the API spec is described by **OpenAPI 3**. 
So, is there any tool similar with the `loopback-connector-swagger` and can support to interact with API descrined by **OpenAPI 3**? Since the swagger connector is really convenient. Otherwise, I have to use the Rest Connector to invoke the API defined in the new loopback4 project, and I have to have a long config file.

**Comment by dhmlau** [comment]
@yuzhebj, thanks for your clarification.  Discussed it with @raymondfeng, it's a feature to upgrade this connector to support OpenAPI 3.0.

**Comment by raymondfeng** [comment]
@yuzhebj I started to implement OAS 3.0 support in:

https://github.com/strongloop/loopback-connector-swagger/pull/52

Please note it's still WIP. There are changes from `swagger-client` that breaks the caching support that I have to figure out how to fix.

**Comment by yuzhebj** [comment]
@dhmlau @raymondfeng thanks so much and looking forward to the new release :)

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-connector-openapi
