### ISSUE TITLE
Response status code for delete can not be 204

### ISSUE THREAD

**Issue by thinkingpanda** [strongloop/loopback-next#2494]
## Current Behavior
for right now,loopback return 200 for delete success operation。and the property for status is readonly。
## Expected Behavior
return 204 is optional or status code can be overwrite

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@thinkingpanda, wanna make sure I understand where the issue is.  Currently, if I create the controller using the "REST Controller with CRUD functions", the delete endpoint is returning `204` as the status code, and we can change that by modifying the controller.  Or did I miss something? Thanks.

```
@del('/testmodels/{id}', {
    responses: {
      '204': {
        description: 'Testmodel DELETE success',
      },
    },
  })
  async deleteById(@param.path.string('id') id: string): Promise<void> {
    await this.testmodelRepository.deleteById(id);
  }
```

**Comment by thinkingpanda** [comment]
> @thinkingpanda, wanna make sure I understand where the issue is. Currently, if I create the controller using the "REST Controller with CRUD functions", the delete endpoint is returning `204` as the status code, and we can change that by modifying the controller. Or did I miss something? Thanks.
> 
> ```
> @del('/testmodels/{id}', {
>     responses: {
>       '204': {
>         description: 'Testmodel DELETE success',
>       },
>     },
>   })
>   async deleteById(@param.path.string('id') id: string): Promise<void> {
>     await this.testmodelRepository.deleteById(id);
>   }
> ```

I have tried servral times ,and find this:
It seems in core code if response without any content,response code will be changed from 200 to 204.so if you want a 204 ,you should return undefined in your code,and i find that response code in responses object have no effect. So if you wrote 201 in your responses object ,but only 200 would get.

only two response code you will get if you dont want to throw a httpError.
with a empty return ,you will get 204,in all the other scenes，you will get 200.
Is it true？
