### ISSUE TITLE
Spike: Port the `examples/todo` app to JavaScript

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#2501]
Port the [examples/todo](https://github.com/strongloop/loopback-next/tree/master/examples/todo) app to JSLB4 API. CRUD only, no Geocoder service integration.

**Acceptance criteria**

- [ ] Should replicate the original behavior, without the Geocoder service integration.
- [ ] Use routes to implement REST endpoints, not Controllers. See https://github.com/strongloop/loopback-next/issues/2474

**Comment by dhmlau** [comment]
Before working on this task, these 2 spikes (in order) #2474 and #2557 should be done first.
