### ISSUE TITLE
Unable to connect to SSL Enabled DB2 instance from Loopback

### ISSUE THREAD

**Issue by amrithrajvijayan** [strongloop/loopback-next#2504]
## Description
 I have a loopback application connecting to a DB2 instance which is working as expected. But I am unable to connect to a SSL enabled DB2 instance.  setting the parameter 'ssl' to true doesn't seem to have any impact

## Expected Behavior
Should be able to connect to DB2 (SSL Enabled) using Loopback

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@amrithrajvijayan, I haven't tried it myself, however, I recalled a user managed to get it to work by setting the `dsn` property, this value is provided by IBM Cloud DB2 credential property `ssldsn`.  

Reference: https://github.com/strongloop/loopback-connector-db2/blob/master/README.md#configuration

**Comment by amrithrajvijayan** [comment]
Finally, I have made this work. I used the property dsn as below,

          dsn: 'DATABASE=<database>;HOSTNAME=<hostname>;PORT=<port>;PROTOCOL=TCPIP;UID=<uid>;PWD=<pwd>;Security=SSL;SSLServerCertificate=<location>/Db2Cert.arm;'
