### ISSUE TITLE
Spike: replace strong-docs with api-extractor 

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2507]
Can we replace our home-grown apidocs solution based on [strong-docs](https://www.npmjs.com/package/strong-docs) with https://api-extractor.com?

API Extractor offers additional benefits beyond API docs generation, e.g. support for Alpha/Beta graduation and ability to remove internal classes/members from the generated `.d.ts` files.

## Acceptance criteria

- [x] Use [api-extractor](https://www.npmjs.com/package/@microsoft/api-extractor) to parse TypeScript sources and produce JSON files describing the API 
- [x] Convert `*.api.json` files into format we can consume by http://apidocs.loopback.io. We should research different alternatives, for example using [api-documenter](https://www.npmjs.com/package/@microsoft/api-documenter) to build Markdown files or writing our own converter that can produce HTML files.
- [ ] Propose the new apidocs pipeline: what steps to run at publish time, what artifacts to bundle in the npm packages, what steps will be run by our apidocs site.
- [x] List of user stories/tasks needed to switch loopback-next from strong-docs to api-extractor.

Related PRs: https://github.com/strongloop/loopback-next/pull/2834 and https://github.com/strongloop/loopback-next/pull/3055

**Comment by hacksparrow** [comment]
Good suggestion. We should go for it.

**Comment by jannyHou** [comment]
I like it's API review features like catching the API contracts change and checking the type export. Let's try it +1.

In case we want to try an alternative: I found a similar API generator tool [typedoc](https://www.npmjs.com/package/typedoc), given a rough comparison typedoc has plugins for setting up pipelines and rendering markdown API documents.

**Comment by dhmlau** [comment]
assign it to @raymondfeng , since he has a PR https://github.com/strongloop/loopback-next/pull/2834 for this.

**Comment by dhmlau** [comment]
Talked to @raymondfeng, we can close this as done.
