### ISSUE TITLE
Mysql transaction CRUD and Hook

### ISSUE THREAD

**Issue by lacuong2009** [strongloop/loopback-next#2509]
## Description / Steps to reproduce / Feature proposal
Hi. Anyone help me resolve issues about the transaction when I try CRUD with many objects to Mysql database. I look into document loopback 4 does not mention about database transaction.
## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by truongkhanhduy95** [comment]
Link to issue [#1599](https://github.com/strongloop/loopback-next/issues/1599)

**Comment by dhmlau** [comment]
@truongkhanhduy95 , thanks for the reference. 
Cross posting [my comment ](https://github.com/strongloop/loopback-next/issues/1599#issuecomment-468964994):

> Talked to @bajtos @raymondfeng, what we should do regarding transaction support:
> - shorter term: explain to users how to open a transaction and pass the transaction token/handles around in options.
> - longer term: have a spike on a more elegant solution.

I'd like to continue the discussion on transaction support in #1599, and close this issue as duplicate. Thanks.
