### ISSUE TITLE
Docs: Add "Working with Data" section 

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#2527]
We have enough feature to create the section and content as in the LB3 docs - https://loopback.io/doc/en/lb3/Working-with-data.html.

## Acceptance Criteria
Add the `Working with data` in LB4 docs, as a similar content and structure as https://loopback.io/doc/en/lb3/Working-with-data.html. Make sure the content is correct and relevant to LoopBack 4

- [ ] Working with data
   - [ ] Creating, updating and deleting data
   - [ ] Querying data (higher priority)
- [ ] Look at [Repositories](https://loopback.io/doc/en/lb4/Repositories.html) for LB4 and add what's missing from the Working with Data pages from LB3
  - [ ] this content will go underneath this section of the page.

### Out of scope 
The following section is out of scope for this task:
- `Advanced topics: data`

**Comment by dhmlau** [comment]
@hacksparrow , could you please review the acceptance criteria below?  I intentionally didn't put the advanced topic here, perhaps we can do it incrementally.  There's one about socket.io but not sure if it falls under the advanced topic.  https://github.com/raymondfeng/loopback4-example-websocket

## Acceptance Criteria
Add the `Working with data` in LB4 docs, as a similar content and structure as https://loopback.io/doc/en/lb3/Working-with-data.html.
- [ ] Working with data
   - [ ] Creating, updating and deleting data
   - [ ] Querying data

**Comment by bajtos** [comment]
> I intentionally didn't put the advanced topic here, perhaps we can do it incrementally.

+1 to leave advanced topics out of the initial version.

**Comment by emonddr** [comment]
This LB3 section https://loopback.io/doc/en/lb3/Working-with-data.html needs to be rewritten for LB4  to discuss the CRUD methods of a repository (instead of a model), and its relationship with controller endpoints.
