### ISSUE TITLE
'lb4 -v' suggests upgrade even though it is unnecessary

### ISSUE THREAD

**Issue by emonddr** [strongloop/loopback-next#2531]
## Description / Steps to reproduce / Feature proposal

"lb4 -v" suggests I upgrade from old version to latest version even though I have latest version

For example : 

```sh
dominiques-mbp:my_lab_4_loopback dremond$ lb4 -v
@loopback/cli version: 1.8.1

@loopback/* dependencies:
  - @loopback/authentication: ^1.0.14
  - @loopback/boot: ^1.0.14
  - @loopback/build: ^1.3.1
  - @loopback/context: ^1.6.0
  - @loopback/core: ^1.1.7
  - @loopback/metadata: ^1.0.7
  - @loopback/openapi-spec-builder: ^1.0.7
  - @loopback/openapi-v3-types: ^1.0.7
  - @loopback/openapi-v3: ^1.2.3
  - @loopback/repository-json-schema: ^1.3.3
  - @loopback/repository: ^1.1.7
  - @loopback/rest: ^1.7.0
  - @loopback/testlab: ^1.0.7
  - @loopback/docs: ^1.9.1
  - @loopback/example-hello-world: ^1.1.5
  - @loopback/example-log-extension: ^1.1.5
  - @loopback/example-rpc-server: ^1.1.4
  - @loopback/example-todo: ^1.5.0
  - @loopback/example-soap-calculator: ^1.4.0
  - @loopback/service-proxy: ^1.0.9
  - @loopback/http-caching-proxy: ^1.0.8
  - @loopback/http-server: ^1.1.7
  - @loopback/example-todo-list: ^1.5.0
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^1.1.10
  - @loopback/tslint-config: ^2.0.1
  - @loopback/example-express-composition: ^1.2.0


   ╭──────────────────────────────────────────╮
   │                                          │
   │     Update available 1.2.2 → 1.8.1       │
   │   Run npm i -g @loopback/cli to update   │
   │                                          │
   ╰──────────────────────────────────────────╯
```

Uncertain where '1.2.2' is coming from.

```sh 
dominiques-mbp:my_lab_4_loopback dremond$ npm ls -g @loopback/cli
/Users/dremond/.nvm/versions/node/v10.15.2/lib
└── @loopback/cli@1.8.1
```

## Current Behavior
Suggests I upgrade versions even though it is not necessary

## Expected Behavior
It should not suggest I upgrade the version if it is currently installed.

**Comment by raymondfeng** [comment]
We use https://github.com/yeoman/update-notifier and it defers notification to next time when `lb4` is launched after an update is detected. In your case, it's probably that you already run `npm install -g @loopback/cli` in between.

**Comment by dhmlau** [comment]
Hm. it seems to be working fine for me.  
```
$ lb4 -v
@loopback/cli version: 1.8.0
...
   ╭──────────────────────────────────────────╮
   │                                          │
   │     Update available 1.8.0 → 1.8.1       │
   │   Run npm i -g @loopback/cli to update   │
   │                                          │
   ╰──────────────────────────────────────────╯

```

After I update, 
```
lb4 -v
@loopback/cli version: 1.8.1
...
```
The `update available` box is gone.

**Comment by raymondfeng** [comment]
I believe that @emonddr ran into an edge case in a similar sequence as follows:

1. Start with `@loopback/cli` v1.7.0 installed
2. `@loopback/cli` v1.8.1 is then released
3. Uses `lb4 ...`, which triggers the update check and finds a newer version, but notification is deferred to next run of `lb4 ...`
4. Run `npm i -g @loopback/cli` to upgrade
5. Run `lb4 ...`, which displays the notification from step 3, which is obsolete now.

**Comment by dhmlau** [comment]
@emonddr, do you still encounter this issue? Now that we have published a new release yesterday, things seem to be working fine for me to notify about the update.

**Comment by emonddr** [comment]
I no longer see this issue. :)
