### ISSUE TITLE
Integrate Loopback 4 with IBM AppID service

### ISSUE THREAD

**Issue by dcarlon** [strongloop/loopback-next#2540]
## Description / Steps to reproduce / Feature proposal
Integrate Loopback 4 with IBM AppID service (https://github.com/ibm-cloud-security/appid-serversdk-nodejs).

The only available security in loopback 4 is using a user and password strategy. To be able to release an application to production, security is necessary.

## Current Behavior
N/A

## Expected Behavior
N/A

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by jannyHou** [comment]
You can wrap the AppID strategy with [@loopback/authentication-passport]https://www.npmjs.com/package/@loopback/authentication-passport and register the wrapped one as a LoopBack strategy.

The usage of that module is documented in https://www.npmjs.com/package/@loopback/authentication-passport

(A new version will be released soon)

**Comment by jannyHou** [comment]
I am closing it as the answer is provided. Feel free to reopen it if you still have questions.
