### ISSUE TITLE
postgresql connector not initialized

### ISSUE THREAD

**Issue by mightytyphoon** [strongloop/loopback-next#2544]
## Description / Steps to reproduce / Feature proposal
Hi !

I'm struggling with this, when I push the project on my server, the postgresql connector is not working.
To reproduce this, create a lb4 server, then a database/repo and try to launch the project with postgresql connector and a local or server side with pgsql database.

## Current Behavior

```
2019-03-06T19:23:19.069647329Z app[web.1]: Error: The connector has not been initialized.
2019-03-06T19:23:19.069666278Z app[web.1]:     at AppDataSource.freeze (/app/node_modules/loopback-datasource-juggler/lib/datasource.js:1982:11)
2019-03-06T19:23:19.069671616Z app[web.1]:     at AppDataSource.DataSource.automigrate (/app/node_modules/loopback-datasource-juggler/lib/datasource.js:1007:8)
2019-03-06T19:23:19.069703345Z app[web.1]:     at Application.migrateSchema (/app/node_modules/@loopback/repository/dist/mixins/repository.mixin.js:186:40)
2019-03-06T19:23:19.069708037Z app[web.1]:     at processTicksAndRejections (internal/process/next_tick.js:81:5)
```
This happens when I use `npm run migrate` it also happens if I use `datasource.once('initialized')` and also with a setTimeout. Also I verified that `datasource.initialized == true` and same for `datasource.connected`. I have still the error. Same with `app.migrateSchema()`.

## Expected Behavior
automigrate, autoupdate and migrate database should run without error about the not initialized connector.

Thanks.

**Comment by dhmlau** [comment]
@mightytyphoon, I just tried to create a LB4 app, set the datasource to be the PSQL running in docker, and run `npm run migrate`.  It was running fine.  What do you mean by "push the project on my server"?  I'm running everything locally.

Just in case, I'm running the latest version of the LB4 modules.
```
$ lb4 -v
@loopback/cli version: 1.8.1

@loopback/* dependencies:
  - @loopback/authentication: ^1.0.14
  - @loopback/boot: ^1.0.14
  - @loopback/build: ^1.3.1
  - @loopback/context: ^1.6.0
  - @loopback/core: ^1.1.7
  - @loopback/metadata: ^1.0.7
  - @loopback/openapi-spec-builder: ^1.0.7
  - @loopback/openapi-v3-types: ^1.0.7
  - @loopback/openapi-v3: ^1.2.3
  - @loopback/repository-json-schema: ^1.3.3
  - @loopback/repository: ^1.1.7
  - @loopback/rest: ^1.7.0
  - @loopback/testlab: ^1.0.7
  - @loopback/docs: ^1.9.1
  - @loopback/example-hello-world: ^1.1.5
  - @loopback/example-log-extension: ^1.1.5
  - @loopback/example-rpc-server: ^1.1.4
  - @loopback/example-todo: ^1.5.0
  - @loopback/example-soap-calculator: ^1.4.0
  - @loopback/service-proxy: ^1.0.9
  - @loopback/http-caching-proxy: ^1.0.8
  - @loopback/http-server: ^1.1.7
  - @loopback/example-todo-list: ^1.5.0
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^1.1.10
  - @loopback/tslint-config: ^2.0.1
  - @loopback/example-express-composition: ^1.2.0
```

**Comment by mightytyphoon** [comment]
Hi @dhmlau thanks for the answer.

I managed to make it work, there were several errors on my side, because I misunderstood some mechanics  on loopback 4.

About the 'connector not initialized' error, because of my 2 environments (prod/dev) I made different bindings in application.ts. Something like : `if(process.env.environment == 'PRODUCTION')`  => create the datasource with the production config settings, add postgresql connector and bind it to the application. But the binding wasn't working using : `this.bind('datasources.db').to(dataSource)` also it didn't work with `this.datasource(dataSource)` or `this.dataSource(dataSource , 'dbName' )`. Anything I tried in application to bind the dataSource depending on env variable wasn't working on production side.

This is related to #2438 

So I just deleted all dataSource config I made from application.ts and I ended putting them directly into the datasources/dataSourceName.ts like this :

```
// src/datasources/db.datasource.ts

import {inject} from '@loopback/core';
import {juggler} from '@loopback/repository';
import * as devConfig from './app.datasource.json'; // import dev json
import * as prodConfig from './app.ds.production.json'; // import prod json

export class DataSourceSettings{
  name: string
  connector: string
  url?: string
  file?: string
};

let config: DataSourceSettings;

if( process.env.NODE_ENV === 'PRODUCTION') {
  console.log(' --- Database in Prod Mode --- ')
  config = prodConfig;
  config.url = process.env.DATABASE_URL; // can add properties dynamically.
  console.log(config);
} else {
  console.log(' --- Database in Dev Mode --- ')
  config = devConfig;
  console.log(config);
}

export class AppDataSource extends juggler.DataSource {
  static dataSourceName = 'db';

  constructor(
    @inject('ds.config.db', {optional: true}) dsConfig: object = config,
  ) {
    // console.log(dsConfig);
    super(dsConfig);
  }
}
```

And this is working. So, as you can see, I imported several configs from  several json files. It's also possible to put all the settings in the datasource.ts file and getting rid of the json files. I made a class DataSourceSettings to have type security. And with this config I can use `npm run migrate` or `npm run migrate -- --rebuild` for example on production env.

The other problem was because I didn't put `generated: true` in the property decorator for ids so postgresql gave me an error like 'id can't be null' as there was no SERIAL type automatically generated :

```
import {Entity, model, property} from '@loopback/repository';

@model()
export class ExampleModel extends Entity {

  @property({type: 'number' , id: true ,  generated: true }) id: number;

   // other properties...

  constructor(data?: Partial<ExampleModel>) {
    super(data);
  }
}
```

So all is working so far, thank you very much for the fast answer.

Regards.

**Comment by dhmlau** [comment]
No problem @mightytyphoon.  I'd like to close this issue, and let's continue the discussion of the environment configuration in #2438. Thanks.
