### ISSUE TITLE
How to get client hostname and ip address

### ISSUE THREAD

**Issue by MrJim-06** [strongloop/loopback-next#2545]
I want to record the request's IP address and hostname. How to do it?

**Comment by raymondfeng** [comment]
In your controller, you can inject `RestBindings.Http.REQUEST`.

**Comment by vikramkh** [comment]
When I try to use: this.request in my code it throws an error: 
'this' implicitly has type 'any' because it does not have a type annotation.

**Comment by raymondfeng** [comment]
@vikramkh Can you show the code?

**Comment by vikramkh** [comment]
I changed it now but originally it was in a callback function which I think it was why it wasn’t working. I had a question as to how to get the IP address from request though if you don’t mind helping. Where is it located in the request object?

**Comment by raymondfeng** [comment]
See https://expressjs.com/en/api.html#req. We use Express Request.

**Comment by shadyanwar** [comment]
@raymondfeng What if I want to get the request headers (to get the IP address for example) in index.ts (inside the block "`export async function main`"). In my use case, I will use `await app.static `to redirect the user to a specific path based on their request headers.

**Comment by raymondfeng** [comment]
@shadyanwar In your case, maybe it's better off to have a facade controller that receives injection of `request` and delegates to other controllers (which can be injected to the facade one as dependencies too).

**Comment by ChannaJayanath** [comment]
export class MyController {
  constructor(@inject(RestBindings.Http.REQUEST) private request: Request) {
  }
} 
I add this
but 
this.request.ip always return 127.0.0.1
what is the issue

**Comment by raymondfeng** [comment]
See http://expressjs.com/en/api.html#req.ip

**Comment by ChannaJayanath** [comment]
this.request.ip  return 127.0.0.1
this.request.ips return nothing

can you help me. I used nginx reverse proxy in my server. Is that the issue?

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/request-context.ts#L75. Some of the http headers should help.

Please note that your can inject `RestBindings.Http.CONTEXT` for the request context.

**Comment by raymondfeng** [comment]
And check out https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/
