### ISSUE TITLE
question, how to getting controller support for gzip?

### ISSUE THREAD

**Issue by lygstate** [strongloop/loopback-next#2555]

**Comment by raymondfeng** [comment]
Good question. I think we need to add `compress` middleware to the express application behind `RestServer`. We are working on the extension point to allow additional express middleware to be mounted. Before that, you might have to follow https://loopback.io/doc/en/lb4/express-with-lb4-rest-tutorial.html.

**Comment by dhmlau** [comment]
Closing this issue as answered.
