### ISSUE TITLE
how to page and count all results from the repository?

### ISSUE THREAD

**Issue by salomaosnff** [strongloop/loopback-next#2566]
I created a new repository by extending Default CrudRepository, however I need the find () function (or other function) to return the paged result and the count of all found elements.

**Comment by marioestradarosa** [comment]
@salomaosnff ,

The repository implements the methods `count`  that returns the number of model instances (number of rows) that satisfies a condition : 
ie:
```ts
  const numberRecords = myRepository.count( { where: { city: 'xxx' }});
```
likewise method `find` can be used to query for the records. I haven't seen a method that returns the number of rows + the rows.

I advise you use the generated tools such as `lb4 repository` and `lb4 controller` that would generate and exposed this functionality.  In my experience the generated code would be sufficient to create a CRUD screen from angular, react etc.

**Comment by raymondfeng** [comment]
You can call `find` with a filter object that has `limit` and `offset` for pagination, such as:

```ts
const records = await myRepo.find({offset: 5, limit: 10});
```
