### ISSUE TITLE
"Create your app scaffolding" docs table misform

### ISSUE THREAD

**Issue by pSnehanshu** [strongloop/loopback-next#2599]
## Description / Steps to reproduce / Feature proposal
Visit https://loopback.io/doc/en/lb4/todo-tutorial-scaffolding.html and scroll to the bottom.

## Current Behavior
The table appears misformed
![loopback io](https://user-images.githubusercontent.com/9392350/54470861-97afd580-47d5-11e9-9c07-472270e8ec7f.png)

## Expected Behavior
It should look like this
![loopback github](https://user-images.githubusercontent.com/9392350/54470864-9ed6e380-47d5-11e9-9f20-44b9044d3f59.png)

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@pSnehanshu, thanks for reporting this.  I believe we've fixed it in PR https://github.com/strongloop/loopback-next/pull/2581 but haven't released it yet.  We'll make sure the latest changes got released soon so that the docs will be updated accordingly.  

cc @nabdelgadir

**Comment by dhmlau** [comment]
@pSnehanshu, I'd like to close this issue as resolved.  The docs will be refreshed with the fix on the next release.  Thanks.
