### ISSUE TITLE
Blog post about the JS spike findings and next steps

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#2605]
Create a blogpost based on the discussion in https://github.com/strongloop/loopback-next/issues/1978 and https://github.com/strongloop/loopback-next/issues/2567.

## Acceptance Criteria
Write a blog about the JS spike findings, including: 
- [ ] what was done as part of the spike and the assessment
- [ ] what is the next step and what type of scenario(s) we're going to support for the JavaScript experience out of the many user scenarios that one can use LoopBack

**Comment by dhmlau** [comment]
@hacksparrow, I've added the acceptance criteria.  Could you please take a look and edit accordingly?  Thanks!

**Comment by hacksparrow** [comment]
Looks good.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/strongloop.com/pull/186

**Comment by jannyHou** [comment]
Closing since the blog get approved, thanks @hacksparrow !
