### ISSUE TITLE
Switch from tslint to eslint

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2608]
TypeScript announced their intent to improve ESLint to allow ESLInt to be used as a linter for TypeScript codebase. Since the announcement, significant progress has been made on porting tslint rules to eslint.

As part of this story, we should investigate options to migrate our project infrastructure from tslint to eslint.

Work in progress:
- feat(build): add eslint scripts and default configs #2572
- [RFC] feat: introduce eslint with typescript-eslint to replace tslint #2492

**Comment by dhmlau** [comment]
@raymondfeng @bajtos, is this done https://github.com/strongloop/loopback-next/pull/2492?
