### ISSUE TITLE
Add next tag to publishConfig for alpha packages

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#261]
Follow up for #179 

Consider adding `"publishConfig": { "tag": "next" }` to `package.json` of all published modules.

- [ ] @loopback/core
- [ ] @loopback/context
- [ ] @loopback/openapi-spec
- [ ] @loopback/openapi-spec-builder
- [ ] @loopback/testlab

**Comment by bajtos** [comment]
The `next` tag would be important only if we were publishing the main package as `loopback`. Now that everything is scoped and the main package is `@loopback/core`, I think it's actually better to use the default `latest` tag.

As far as I am concerned, this issue should be closed as invalid/rejected.

cc @superkhau

**Comment by superkhau** [comment]
@bajtos :+1: Makes sense since we don't publish the main package at all. +1 for latest. Closing as rejected.
