### ISSUE TITLE
Database not being created

### ISSUE THREAD

**Issue by acrodrig** [strongloop/loopback-next#2612]
I am using the code below in a script to create a MySQL DB, to no avail. There are no errors, and I have tried both with `existingSchema` being "drop" and "alter". Also, with and without a `models` options.

```js
import { App } from "../src/application";

export async function migrate() {
    const app = new App();
    await app.boot();
    await app.migrateSchema({ existingSchema: "drop" });
    
    // Connectors usually keep a pool of opened connections,
    // this keeps the process running even after all work is done.
    // We need to exit explicitly
    process.exit(0);
}

migrate().catch(err => {
    console.error("Cannot migrate database schema", err);
    process.exit(1);
});
```

**Comment by dhmlau** [comment]
@acrodrig , are you following this docs page: https://loopback.io/doc/en/lb4/Database-migrations.html?

Another way to do it is to run `npm run migrate`.

**Comment by acrodrig** [comment]
Yes, I am following those docs. I could not make it work. I am closing this as I moved on from LB4. I found it lacking with respect to LB3. Thanks.
