### ISSUE TITLE
Circular dependency when trying to check for referential integrity

### ISSUE THREAD

**Issue by DatGuyJonathan** [strongloop/loopback-next#2615]
In the todo-list example, it looks like there is no check for a valid todo-list when creating a todo. I tried adding a check in todo.repository.ts:

```diff
diff --git a/examples/todo-list/src/repositories/todo.repository.ts b/examples/todo-list/src/repositories/todo.repository.ts
index 26e3c9c..e4a8d19 100644
--- a/examples/todo-list/src/repositories/todo.repository.ts
+++ b/examples/todo-list/src/repositories/todo.repository.ts
@@ -3,20 +3,22 @@
 // This file is licensed under the MIT License.
 // License text available at https://opensource.org/licenses/MIT
 
 import {
   BelongsToAccessor,
   DefaultCrudRepository,
   juggler,
   repository,
+  DataObject,
+  Options,
 } from '@loopback/repository';
 
 export class TodoRepository extends DefaultCrudRepository<
   Todo,
   typeof Todo.prototype.id
   {
   public readonly todoList: BelongsToAccessor<
     TodoList,
     typeof Todo.prototype.id
@@ -34,4 +36,12 @@ export class TodoRepository extends DefaultCrudRepository<
       todoListRepositoryGetter,
     );
   }
+
+  public async create(entity: DataObject<Todo>, options?: Options): Promise<Todo> {
+    const todoListRepo = await this.todoListRepositoryGetter();
+    if (! await todoListRepo.exists(entity.todoListId)) {
+      throw new Error('Unknown value: Todo.todoListId');
+    }
+    return await super.create(entity, options);
+  }
 }
```

This results in this error:
```
Unhandled error in POST /todo-lists/1/todos: 500 Error: Circular dependency detected: controllers.TodoListTodoController --> @TodoListTodoController.constructor[0] --> repositories.TodoListRepository --> @TodoListRepository.constructor[1] --> repositories.TodoRepository --> @TodoRepository.constructor[1] --> repositories.TodoListRepository
```

**Is there an example of how we can check for referential integrity?**

**Comment by dhmlau** [comment]
@nabdelgadir , could you please take a look? Thanks.

**Comment by DatGuyJonathan** [comment]
@nabdelgadir @dhmlau  @bajtos , do you some insight on why the getter complains about circular dependency?

I tried passing in the `TodoListRepository` in `Options` and the circular dependency error goes away. So I'm basically providing my own caching, but it's a poor workaround.

Usually with dependency injection, there is a scope attached to it. I was expecting the getter to behave like that and just get a cached copy from somewhere. But I think it's creating a new instance.

**Comment by nabdelgadir** [comment]
I tried looking at a way to do it at the repository level but couldn't figure it out. I think @b-admike would have more knowledge about this. However, there's an open issue regarding this https://github.com/strongloop/loopback-next/issues/1718, so it's something that we're planning on working on.

**Comment by dhmlau** [comment]
@DatGuyJonathan, I just run your code snippet on top of the todolist example, and seems to be running fine.  If I create a todo with todolist id that does not exist, it throws an error. 
Here is what I've done:
1. run `lb4 app todo-list`
2.  modify `src/repositories/todo.repository.ts` to be the same as your snippet in the original description.

Could you please try again and see if this problem still exists?  It's been a month since we've last tried, and there might be things that already fixed/changed. Thanks.

**Comment by jannyHou** [comment]
might be the same as https://github.com/strongloop/loopback-next/issues/2568

**Comment by bajtos** [comment]
> In the todo-list example, it looks like there is no check for a valid todo-list when creating a todo.

We are aware of this problem, see e.g. https://github.com/strongloop/loopback-next/issues/1718

> I tried adding a check in todo.repository.ts:

I am afraid your check is not reliable and makes it possible to create a Todo instance belonging to TodoList instance that no longer exists:

1. Request1 arrives to create a new Todo instance
2. Request2 arrives to delete the related TodoList instance
3. The code handling Request1 executes your new check, TodoList instance is found ✅ 
4. The code handling Request2 executes the database command and deletes the TodoList instance
5. The code handling Request2 executes `create` command and creates a Todo instance pointing to a TodoList that does not exist any more

We need the database to enforce referential integrity, that's the only reliable solution we are aware of. Further resources: https://github.com/strongloop/loopback-next/issues/2332 and https://github.com/strongloop/loopback-next/issues/2127.

**Comment by dhmlau** [comment]
According to the [above comment](https://github.com/strongloop/loopback-next/issues/2615#issuecomment-487897572), I'd like to move over the discussion to #1718 and close this issue as duplicate. Thanks!
