### ISSUE TITLE
Repository generator does not update index.ts

### ISSUE THREAD

**Issue by JesusTheHun** [strongloop/loopback-next#2618]
To reproduce : 
Create at least two models using the generator.
Execute the `lb4 repository` command. Select `all`using the hotkey `a`.

The repository are successfully generated, but the `index.ts` is not updated and therefore does not exports the repositories.

**Comment by dhmlau** [comment]
Transferring this issue to `loopback-next` repo.

**Comment by nabdelgadir** [comment]
I also just tried to do what you described with models `Model1` and `Model2`: 

```
$ lb4 repository
? Please select the datasource DsDatasource
? Select the model(s) you want to generate a repository (Press <space> to select, <a> to toggle all, <i> to invert selection)Model_1, Model_2
? Please select the repository base class DefaultCrudRepository (Legacy juggler bridge)
   create src/repositories/model-1.repository.ts
   create src/repositories/model-2.repository.ts
   update src/repositories/index.ts
   update src/repositories/index.ts

Repositories Model_1Repository,Model_2Repository was created in src/repositories/
```
And `index.ts` was updated successfully:

<img width="352" alt="Screen Shot 2019-03-20 at 10 30 21 AM" src="https://user-images.githubusercontent.com/42985749/54692306-2d5fa380-4afb-11e9-839c-8b1109447968.png">

Did you see this part:
```
update src/repositories/index.ts
update src/repositories/index.ts
```

**Comment by JesusTheHun** [comment]
I was using version 1.6.0.
I tried with 1.8.2, works fine. 
My bad, sorry.
