### ISSUE TITLE
Independent versioning of packages

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#262]
I am proposing to switch our monorepo into independent mode, where each package is versioned independently on each other. For example, I'd like `@testlab/loopback` to use versions `0.1.0` instead of `4.0.0-alpha.1`.

@raymondfeng @ritch @superkhau Thoughts?

**Comment by superkhau** [comment]
I'm +1 for independent mode -- I manually published for now anyways so we're not publishing via lerna yet (have an issue to confirm that it works at https://github.com/strongloop/loopback-next/issues/250).

**Comment by superkhau** [comment]
@bajtos I'm going to turn on independent mode for now, but leave the version number incrementing as 4.0.0-alpha.X until further discussion. I'll add a note for next LBn sync up.

**Comment by superkhau** [comment]
Done via https://github.com/strongloop/loopback-next/pull/278
