### ISSUE TITLE
Support nullable properties in OpenAPI & JSON validation

### ISSUE THREAD

**Issue by gordancso** [strongloop/loopback-next#2626]
## Description / Steps to reproduce / Feature proposal
When trying to perform POST request, some of the attributes are `null`.
**order.model.ts**
```
@property({
  type: 'object',
  default: null,
  nullable: true
})
specialRequests?: object;
```
**request body**
```
{
  "orderTime": "2019-01-01T00:00:00.000Z",
  "specialRequests": null
}
```
currently using mysql db with LB4

## Current Behavior
However, POST with such request body will always return validation error.

**Error: Unprocessable Entity
Response body**

```
{
  "error": {
    "statusCode": 422,
    "name": "UnprocessableEntityError",
    "message": "The request body is invalid. See error object `details` property for more info.",
    "code": "VALIDATION_FAILED",
    "details": [
      {
        "path": ".specialRequests",
        "code": "type",
        "message": "should be object",
        "info": {
          "type": "object"
        }
      }
    ]
  }
}
```

## Expected Behavior
Expected to successfully create a row in DB with captioned request body, same behavior as in LB3.

**Comment by bajtos** [comment]
Thank you @gordancso for reporting the problem. I did a quick search on the internet and found the following related information
- https://groups.google.com/forum/#!topic/jsonschema/mD6GDca4zN8
- https://stackoverflow.com/a/23737104/69868

https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#data-types
> `null` is not supported as a type (see [nullable](https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#schemaNullable) for an alternative solution)

As I understand the problem, we need to modify our code emitting OpenAPI Schema from LoopBack Model definitions to correctly handle nullable types.

1. When processing a property definition with `nullable: true` and emitting JSON Schema, we need to change the type from `'object'` to `['object', null]`. We may need a different solution to support object values with a schema (e.g. nullable model instances), possibly using `oneOf` rule. 

    Here is the place to change: https://github.com/strongloop/loopback-next/blob/e61565770b674fc8957e9e317632de71dcd39de5/packages/repository-json-schema/src/build-schema.ts#L88-L96

2. When converting JSON Schema to OpenAPI Schema, we need to remove `null` types and replace them with `nullable` flag.

   Here is the place to change: https://github.com/strongloop/loopback-next/blob/e61565770b674fc8957e9e317632de71dcd39de5/packages/openapi-v3/src/json-to-schema.ts#L27-L42

3. When converting OpenAPI Schema back to JSON Schema that we pass to AJV to perform validation, we need to convert from `nullable` back to `null` type.
  
    Here is the place to change: https://github.com/strongloop/loopback-next/blob/e61565770b674fc8957e9e317632de71dcd39de5/packages/rest/src/validation/request-body.validator.ts#L62-L68

    We are using a 3rd-party module to perform the conversion, we may need to implement these improvements there: https://www.npmjs.com/package/openapi-schema-to-json-schema. Possibly related: https://github.com/mikunn/openapi-schema-to-json-schema/issues/31

**Comment by bajtos** [comment]
See also https://github.com/epoberezkin/ajv/issues/486, https://github.com/epoberezkin/ajv-keywords/issues/32 and especially https://github.com/epoberezkin/ajv/commit/f2010f40f2046d5c2a9232d9e40601f1300a678d.

It looks like AJV should support custom keyword `nullable` now, so maybe it's enough to change the way how we are configuring AJV instances and enable `nullable` keyword in the options? 

AJV docs: https://github.com/epoberezkin/ajv#options

Here is the place where we are building AJV options:

https://github.com/strongloop/loopback-next/blob/e61565770b674fc8957e9e317632de71dcd39de5/packages/rest/src/validation/request-body.validator.ts#L144-L152

@gordancso would you like to take a closer look and perhaps contribute the necessary changes yourself?

**Comment by gordancso** [comment]
sure, @bajtos please let me know how i can contribute to this issue.

**Comment by rodmcnew** [comment]
We are also experiencing this issue.

**Comment by shijithkm** [comment]
We are also stuck with this issue during the development, it will be great if you could be fix this and release soon

**Comment by raymondfeng** [comment]
Please try the following definition:

```ts
@model()
  class Product {
   
    @property({required: false, jsonSchema: {nullable: true}})
    description?: string | null;

  
    constructor(data: Partial<Product>) {
      Object.assign(this, data);
    }
  }
```

**Comment by mikeevstropov** [comment]
```
@property({
  type: 'array',
  itemType: 'string',
  default: null,
  jsonSchema: {nullable: true},
})
cityIds: string[];
```
PATCH body
```
{cityIds: null}
```
will fail with
```
{
  "error": {
    "statusCode": 422,
    "name": "UnprocessableEntityError",
    "message": "The request body is invalid. See error object `details` property for more info.",
    "code": "VALIDATION_FAILED",
    "details": [
      {
        "path": ".cityIds",
        "code": "type",
        "message": "should be array",
        "info": {"type":"array"}
      }
    ]
  }
}
```

**Comment by bajtos** [comment]
@mikeevstropov please open a new issue for the problem you are experiencing and make sure to provide a small app we can use to reproduce the problem locally, see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report. Ideally, write an automated test we can run via `npm test`, one that fails with the current LoopBack version.
