### ISSUE TITLE
Wrong Model name in Repository/Controller by CLI when a Model name has number

### ISSUE THREAD

**Issue by nabdelgadir** [strongloop/loopback-next#2644]
## Description / Steps to reproduce / Feature proposal

Say we have model `Model1` as follows, generated through `lb4 model`:
```ts
export class Model1 extends Entity {}
```
The file name is `model-1.model.ts`. Then when generating a repository with `lb4 repository`:

```
$ lb4 repository
? Please select the datasource DsDatasource
? Select the model(s) you want to generate a repository *Model_1*
? Please select the repository base class DefaultCrudRepository (Legacy juggler bridge)
   create src/repositories/model-1.repository.ts
   update src/repositories/index.ts
```

## Current Behaviour

The generated `model-1.repository.ts` file uses `Model_1` instead of `Model1`
```ts
import {DefaultCrudRepository} from '@loopback/repository';
import {Model_1} from '../models'; 
import {DsDataSource} from '../datasources';
import {inject} from '@loopback/core';

export class Model_1Repository extends DefaultCrudRepository<
  Model_1,
  typeof Model_1.prototype.id
> {
  constructor(
    @inject('datasources.ds') dataSource: DsDataSource,
  ) {
    super(Model_1, dataSource);
  }
}
```
This also happens in the generated `model-1.controller.ts` file.

## Expected Behaviour

It should match the model class name and use `Model1` instead of `Model_1` in both the repository and controller.

**Comment by jannyHou** [comment]
The model name should be consistent in 4 places:

*Note(naming conversion): The camel case model name like `FooBarBaz` will result in a model file named as `foo-bar-baz`*

Assume the correct name is exactly the input from `lb4 model`: `Model1`
- model file name should be `model-1.model.ts`
- model class name should be `Model1`
- `lb4 repository` prompt: `? Select the model(s) you want to generate a repository Model1`
- repository: `import {Model1} from '../models';`
- `lb4 controller` prompt: `? Select the model(s) you want to generate a repository Model1`
- controller: `import {Model1} from '../models';`
