### ISSUE TITLE
Emit schema excluding certain model properties

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2653]
Allow Controller methods implementing CREATE operation to describe their input data as "a model without `id` and `_rev` properties ". This story requires #2629 and #2631 to be implemented first.

To emit schema with certain properties excluded, we should add a new schema-generation option called `exclude` & accepting a list of property names to remove from the schema. To allow TypeScript compiler to verify that `exclude` items are valid property names, we should leverage TypeScript generics and `keyof` keyword.

```ts
export interface JsonSchemaOptions<T extends object = any>{
  /// List of properties to exclude from the schema
  exclude?: (keyof T)[];
}
```

An example showing a controller method excluding the property `id`:

```ts
class TodoListController {
  // ...

  @post('/todo-lists', {
    responses: {
      // left out for brevity
    },
  })
  async create(
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(TodoList, {exclude: ['id']}),
          /***** ^^^ THIS IS IMPORTANT - OPENAPI SCHEMA ^^^ ****/
        },
      },
    })
    obj: Omit<TodoList, 'id'>,
    /***** ^^^ THIS IS IMPORTANT - TYPESCRIPT TYPE ^^^ ****/
  ): Promise<TodoList> {
    return await this.todoListRepository.create(obj);
  }
}
```

See https://github.com/strongloop/loopback-next/pull/2646/commits/887ae847c04c29fab01735e3c54db141f3cf53ed for a spike showing proposed implementation details.

## Acceptance criteria

- ~~A type alias for `Pick<T, Exclude<keyof TodoList, K>>`, see the discussion in https://github.com/strongloop/loopback-next/pull/2646/commits/887ae847c04c29fab01735e3c54db141f3cf53ed#r269305305~~ - not needed, TypeScript has recently introduced `Omit` type.
- [x] Implementation including test coverage
- [x] API documentation
- [x] `CREATE` endpoints in all example applications are updated to leverage `exclude` option to remove `id` property and use the new type alias as the type of the controller method argument accepting model data.
- [x] CLI templates are updated accordingly
- [ ] Should have - create a new issue if it's too difficult to implement:

    Controller methods working with related models should exclude the foreign key from request body properties. Cross-posting from https://github.com/strongloop/loopback-next/issues/1872#issuecomment-503571828:

    >  `myRepo.users(tenantId).create(new User(...))` fails unless "tenantId" is explicitly passed in the request body even though the relation automatically attaches the "tenantId" property. 

    Things to change: example-todo-list, CLI template for relational controllers (has-many, belongs-to)

- Review the following issues , either close them as fixed or post a comment explaining what's remaining to be done:
    - [x] #1179
    - [x] #1470
    - [x] #1719
    - [x] #1894

**Comment by bajtos** [comment]
> `Pick<TodoList, Exclude<keyof TodoList, 'id'>>`

TypeScript 3.5 is going to introduce a new type `Omit` (see the [announcement post](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5-rc/)), let's leverage it here.

```diff
- Pick<TodoList, Exclude<keyof TodoList, 'id'>>`
+ Omit<TodoList, 'id'>
```

**Comment by bajtos** [comment]
@nabdelgadir What is the remaining work now that #3309 was landed? Could you please update checkboxes in the acceptance criteria to match the new status and perhaps add a new task for adding support for PK with a custom name (not `id`).

**Comment by nabdelgadir** [comment]
@bajtos I'm assuming you were referring to https://github.com/strongloop/loopback-next/pull/3297, but after https://github.com/strongloop/loopback-next/pull/3309 is landed we can close this issue. 

> perhaps add a new task for adding support for PK with a custom name (not id).

I'm working on custom names but I'll create the new issue so we can close this one after https://github.com/strongloop/loopback-next/pull/3309 is landed.
