### ISSUE TITLE
Migrate LB2 to LB4 

### ISSUE THREAD

**Issue by sukeerthi117** [strongloop/loopback-next#2655]
Hi,

I am new to loopback.I am working on an application which is implemented using loopback2 now i want to convert it loopback 3/4 .Is it possible?
if possible, can u explain?

Thank u.

**Comment by bajtos** [comment]
Hi @sukeerthi117, in the future, please post questions to StackOverflow - see https://loopback.io/doc/en/contrib/Reporting-issues.html#before-asking-a-question-on-github

We offer a migration guide from LB 2.x to LB 3.x, see [Migrating apps to LoopBack 3.x](https://loopback.io/doc/en/lb3/Migrating-to-3.0.html) and also [3.0 Release Notes](https://loopback.io/doc/en/lb3/3.0-Release-Notes.html).

As for upgrading to LB4, it's something we are still researching. See https://github.com/strongloop/loopback-next/issues/1849

We have recently posted a blog post with additional information for LB 2.x and 3.x users, see https://strongloop.com/strongblog/lb3-extended-lts/
