### ISSUE TITLE
Context find() not matching with 2nd level notation

### ISSUE THREAD

**Issue by rahulrkr08** [strongloop/loopback-next#2689]
## Description / Steps to reproduce / Feature proposal
@loopback/context - find function returns empty array if more than two notations applies. Example given below.

I have seen there is a description given in [context api doc](http://apidocs.loopback.io/@loopback%2fdocs/context.html#Context.prototype.find) that find pattern will not search more than one dot (.) or column (:). So, in case if more than one notations required what will be the best way implement.
## Current Behavior

```
const { Context } = require('@loopback/context');
const ctx = new Context();

ctx.bind(`a.b.c`).to('test');

console.log(ctx.find('a.*')); // returns []
```

## Expected Behavior

```
const { Context } = require('@loopback/context');
const ctx = new Context();

ctx.bind(`a.b.c`).to('test');

console.log(ctx.find('a.*')); // should return one item array
```

**Comment by raymondfeng** [comment]
The apidocs says `* matches zero or more characters except . and :`. 

To support `a.b.c` matching, you can either pass a `RegExp` or `BindingFilter` function to `find`. For example:

```ts
ctx.find(/^a\.(.+)/); // It matches all keys starting with `a.`.
```

**Comment by rahulrkr08** [comment]
Thanks @raymondfeng it worked... :)
