### ISSUE TITLE
Error in @loopback/rest related to BindingFilter

### ISSUE THREAD

**Issue by psaunders** [strongloop/loopback-next#2713]
## Description / Steps to reproduce / Feature proposal
Error appeared in very basic codebase following update.

## Current Behavior
This simple code:
```
import { HttpErrors } from '@loopback/rest';

console.log(HttpErrors);
```

Causes this error
```
node_modules/@loopback/context/dist/context-view.d.ts:26:14 - error TS2416: Property 'filter' in type 'ContextView<T>' is not assignable to the same property in base type 'ContextObserver'.
  Type 'BindingFilter<T>' is not assignable to type 'BindingFilter<unknown>'.
    Type 'unknown' is not assignable to type 'T'.

26     readonly filter: BindingFilter<T>;
                ~~~~~~
```

## Expected Behavior
Import to compile.

Workaround: avoid this by putting `"skipLibCheck": true` in your tsconfig.json file

**Comment by jannyHou** [comment]
@psaunders Could you post the dependency version of your LoopBack app here?

I just tried with the latest `@loopback/cli`, the created app starts properly:

```
jannyhous-mbp:testapp jannyhou$ npm list -g --depth 0
/Users/jannyhou/.nvm/versions/node/v10.15.3/lib
├── @loopback/cli@1.9.0
└── npm@6.4.1

jannyhous-mbp:testapp jannyhou$ npm list --depth 0
testapp@1.0.0 /Users/jannyhou/2019/testapp/testapp
├── @loopback/boot@1.1.3
├── @loopback/build@1.4.1
├── @loopback/context@1.9.0
├── @loopback/core@1.3.0
├── @loopback/openapi-v3@1.3.3
├── @loopback/repository@1.3.0
├── @loopback/rest@1.10.0
├── @loopback/rest-explorer@1.1.14
├── @loopback/service-proxy@1.1.2
├── @loopback/testlab@1.2.2
├── @loopback/tslint-config@2.0.4
├── @types/node@10.14.4
├── tslint@5.15.0
└── typescript@3.4.2
```

**Comment by psaunders** [comment]
Did you turn off the lib skip with `"skipLibCheck": false`?

There may be some other configuration differences in mine and the default tsconfig.

**Comment by raymondfeng** [comment]
The flag is already set at https://github.com/strongloop/loopback-next/blob/master/packages/build/config/tsconfig.common.json#L10. Please make sure you pick up the latest version of `@loopback/build`. Use `npm up` to update deps for your package.json.

If you have latest `@loopback/cli` installed, `lb4 version` will print out a list of compatible versions of `@loopback/*` modules for that release.

**Comment by psaunders** [comment]
Yeah, the addition of that flag is how I discovered the workaround (I have a custom tsconfig because we use more than just loopback). 

I find it strange that `context-view.ts` has an error in it meaning all loopback users now have this flag on for everything. Seems like it can't be the real solution, but I understand that sometimes typing can get incredibly time consuming and for the sake of productivity you have to go with a fix like this.
