### ISSUE TITLE
Create Namespaced Reflect wrapper for metadata

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#272]
Description :
  - [ ] Add a Provider class to to @loopback/core
      -  class: Meta
      -  provider class to access Component metadata

Meta Class:
  - controller will be injected through the constructor
  - Provider method : value() 
       - value() will return **all** metadata defined by decorators (eg. `@authenticate`, `@get`, etc)

Core Methods: 
 - getMetaByName(name)
       get a meta by it's name
 - getAllMeta()
 - defineMetaByName()
 - MetaProvider
 - update @authenticate to use defineMetaByName()

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/issues/282

**Comment by ritch** [comment]
@deepakrkris - I updated the description

**Comment by raymondfeng** [comment]
The Metadata Reflector should go into `@loopback/context`. Please also update existing references to `reflect-metadata` with the new class.

**Comment by raymondfeng** [comment]
I suggest that we model it after https://github.com/rbuckton/reflect-metadata#api.
