### ISSUE TITLE
Indexes are not created for MySQL during migration when included in ModelDefinition

### ISSUE THREAD

**Issue by Narrator** [strongloop/loopback-next#2723]
## Description / Steps to reproduce
Use the MySQL datasource, and define indexes in the model definition like so and run migration
```
@model({
    indexes: {
        uniqueIndex: {
            keys: {
                property: 1,
                anotherProperty: 1
            }
        }
    }
})
```

## Current Behavior
The indexes are not actually created in the database

## Expected Behavior
Indexes are created in the database

**Comment by bajtos** [comment]
IIRC, model-level settings must be nested in `settings` object, see https://github.com/strongloop/loopback-next/issues/2142

```ts
@model({
  settings: {
    indexes: {
        uniqueIndex: {
            keys: {
                property: 1,
                anotherProperty: 1
            }
        }
    }
  }
})
```

I am looking into ways how to make index and foreign key definition more ergonomic, see https://github.com/strongloop/loopback-next/issues/2606
