### ISSUE TITLE
instantiateClass nonInjectedArgs

### ISSUE THREAD

**Issue by psaunders** [strongloop/loopback-next#2727]
## Description / Steps to reproduce / Feature proposal
It seems that the instantiateClass is either not fully implemented or behaves differently to how you would expect.

## Current Behavior

I want to create an DIed instance of the following:
```
export class BoundConfiguration<TSettingCollection extends Settings> {
  public constructor(
    @inject(CONFIGURATION_SERVICE_BINDINGS.SETTING_RESOLVER)
    settingResolver: SettingResolver,
    private settings: TSettingCollection
  ) { }
  ...
```

Inside a custom Mixin I have the following code trying to DI the SettingResolver and take some settings.
```
let injected = instantiateClass(BoundConfiguration, (this as unknown) as Context, undefined, [configuration.settings]);
```

But you get the error
```
 Error: Cannot resolve injected arguments for BoundConfiguration.[1]: The arguments[1] is not decorated for dependency injection, but a value is not supplied
```

## Expected Behavior
I would expect that the instantiateClass class method in resolver.ts would do something with the nonInjectedArgs parameter, however it looks like it only logs to the debugger.

Related to this, it would be good if the documents showed usage of some of these methods. For a while I thought they were controller only options: https://loopback.io/doc/en/lb4/Dependency-injection.html#method-injection

**Comment by raymondfeng** [comment]
Please note that `nonInjectedArgs` only applies to argument that's not decorated for injection. So the behavior you see is by design. `nonInjectedArgs` is mostly for method parameter injections - with some of the args resolved from DI, while the rest from `@param`.

BTW, these functions are documented at http://apidocs.loopback.io/@loopback%2fdocs/context.html.

**Comment by psaunders** [comment]
Can you take a quick look at the nonInjectedArgs parameter on your [instantiateClass](https://github.com/strongloop/loopback-next/blob/dcc9cac76b53a5f2ea4f0c358f034838e71f6e67/packages/context/src/resolver.ts#L44
) function please?

I understand what this method is for and the difference between the decorated and non-decorated arguments. It sounds great, *I would really like to use it*, however I cannot because the argument going into that function is not attached to anything.

I can see looking through the code that loopback does not make use of that 4th parameter so I think it has slipped through the cracks. Because the debug line does log the parameter the noUnusedParamters check is not finding the problem.

**Comment by raymondfeng** [comment]
@psaunders Sorry for the confusion. I think we need to pass `nonInjectedArgs` to https://github.com/strongloop/loopback-next/blob/dcc9cac76b53a5f2ea4f0c358f034838e71f6e67/packages/context/src/resolver.ts#L58. Would you like to contribute a patch?

**Comment by psaunders** [comment]
Sure thing, will do, thanks for taking another look

**Comment by psaunders** [comment]
Done @raymondfeng 
https://github.com/strongloop/loopback-next/pull/2729
