### ISSUE TITLE
Is there any way to validate Loopback 4 Model

### ISSUE THREAD

**Issue by DilupaSampath** [strongloop/loopback-next#2735]
Is there any way to validate Loopback 4 Model,
Now i'm validate my model like this.

import {Entity, model, property, belongsTo} from '@loopback/repository';
import {SaleStore} from './sale-store.model';
import {VehicleQuarry} from '../patterns/vehicle-decorator';
import {UploadImages} from './upload-images.model';

@model()
export class Vehicle extends Entity {
  @property({
    type: 'number',
    id: true,
    index: true,
    generated: true,
  })
  id?: number;

  @property({
    type: 'number',
  })
  vehicle_price?: number;

  @property({
    type: 'number',
  })
  vehicle_booking_price?: number;

// 1st -- i want to add more validations like, minimum price, maximum price 
constructor(data?: Partial<Vehicle>) {
    super(data);
  }
}
1st -- I want to add more validations like, I want to check minimum price, maximum price.  
2nd-- Is there any way to compare two fields in model. like :
  vehicle_booking_price < vehicle_price;

**Comment by jannyHou** [comment]
@DilupaSampath Model validation has different levels:

> 1st -- I want to add more validations like, I want to check minimum price, maximum price.

This could be achieved by the spec level validation. 
We use `ajv` module to validate the incoming request data based on your model metadata, see [document](https://loopback.io/doc/en/lb4/Parsing-requests.html#request-body).
To specify a maximum/maxLength or minimum/minLength for your property, you can decorate the model property with a `jsonSchema` that contains valid [keywords](https://github.com/epoberezkin/ajv#validation-keywords):

```ts
@model()
export class Vehicle extends Entity {

...

@Property({
  type: 'number',
  jsonSchema: {
    maximum: 10,
    minimum: 3,
  }
})
vehicle_price?: number;

...
}
```

> 2nd-- Is there any way to compare two fields in model. like :

This would be a customized validation we haven't fully supported yet, you can follow the discussion and proposal from @bajtos in issue https://github.com/strongloop/loopback-next/issues/1872

**Comment by DilupaSampath** [comment]
thank you @jannyHou,  'ajv module'  is good solution for my issue.Also I can handle my second question(2nd-- Is there any way to compare two fields in model.) using 'ajv module'.

**Comment by frrodriguez** [comment]
I was checking this issue and dont works for me:

```
import {Entity, model, property} from '@loopback/repository';

export enum InvitationRoleType {
  'CREATOR' = 'CREATOR',
  'PROMOTOR' = 'PROMOTOR',
  'GUEST' = 'GUEST',
}

@model()
export class Invitation extends Entity {
  @property({
    type: 'string',
    required: true,
  })
  title: string;

  @property({
    type: 'string',
    id: true,
  })
  id?: string;

  @property({
    type: 'date',
    defaultFn: 'now',
  })
  createDate: string;


// this property
  @property({
    type: 'string',
    jsonSchema: {
      maxLength: 3,
      minLength: 1,
    },
    required: true,
  })
  role: string;
////////////


  constructor(data?: Partial<Invitation>) {
    super(data);
  }
}
```

I am using postman to use a simple post creation, and dont validates correctly the payload.

Postman body:
![Captura de pantalla 2019-04-23 a las 15 53 19](https://user-images.githubusercontent.com/15798947/56586412-fee45500-65df-11e9-9e92-8ea4cd836f94.png)
Postman response:
![Captura de pantalla 2019-04-23 a las 15 53 25](https://user-images.githubusercontent.com/15798947/56586431-0572cc80-65e0-11e9-9e6a-64b3edde84b1.png)

I was checking the keywords of ajv, and no one works. I tried 'const' and 'enum' too.
https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#keywords-for-all-types

**Comment by hadasiddhant** [comment]
Is there any way to enforce uniqueness like how mongodb does it in the model with unique:true

**Comment by webmaster-ar** [comment]
@hadasiddhant You can do that creating an index. For example:
```
@property({
    index: {
      "unique": true
    },
    type: 'string',
    required: true,
  })
  email: string;

```
