### ISSUE TITLE
CLI command to expose REST API of a Model with no custom classes

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2739]
_Part of From model definition to REST API with no custom repository/controller classes #2036_

A new CLI command that will ask the user for an existing model, an existing datasource, and then generate the corresponding `public-models` entry (model configuration json)

Nice to have: the pattern (crud vs key-value) can be automatically inferred from the datasource config (connector type).

(Much can be borrowed from `lb4 repository`)

## Acceptance Criteria 

- [ ] Introduce a new command `modelconfig` in the CLI to generate the model configuration json that will be stored in the `public-models` directory ( `modelconfig` is a suggestion) 
- [ ] Update `Generating LoopBack Artifacts` section in documentation : https://loopback.io/doc/en/lb4/Command-line-interface.html#generating-loopback-artifacts. Be sure to update the sidebar as well. 
- [ ] Provide new unit,integration,acceptance mocha tests

**Comment by dhmlau** [comment]
@bajtos, could you please add the acceptance criteria? Thanks.

**Comment by emonddr** [comment]
@bajtos I added the Acceptance Criteria. Please adjust it to your liking; if necessary. thx

**Comment by nabdelgadir** [comment]
Closing because https://github.com/strongloop/loopback-next/pull/4932 is landed.
