### ISSUE TITLE
Docs for exposing REST API of a Model with no custom classes

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2740]
Documentation for the feature From model definition to REST API with no custom repository/controller classes #2036

## Acceptance criteria

 - [ ] Docs for application developers consuming this feature. Describe the new CLI command, how to use controller/repositories contributed by extensions, what model config options are available.

 - [ ] Docs for  extension developers building custom controller/repository classes. Explain what API contract the custom controller/repository class must implement, show how the component must export the classes so that they can be picked by the Booter.

**Comment by dhmlau** [comment]
Cross posting from https://github.com/strongloop/loopback-next/issues/4296#issuecomment-603361853 from @raymondfeng : 

> Existing docs:
> 
> - https://github.com/strongloop/loopback-next/blob/master/docs/site/Creating-CRUD-REST-apis.md (README)
> - https://github.com/strongloop/loopback-next/blob/master/docs/site/Rest-Crud-generator.md
> - https://github.com/strongloop/loopback-next/blob/master/examples/rest-crud/README.md (README)
> I think we can convert https://github.com/strongloop/loopback-next/blob/master/docs/site/Creating-CRUD-REST-apis.md into a regular page that glues the runtime/cli/example today to tell a story.
