### ISSUE TITLE
Implement @injectInvoke

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#275]
- [ ] class Invoke Provider (aka Binding) (invoke sequence method) @miroslav
  - [ ] @injectInvoke()
- [ ] Tests

**Comment by raymondfeng** [comment]
I start to question if these sugar decorators are necessary. We can use `@inject`. Please note they are only used by `Sequence`, not by application developers. Using `@inject` is probably good enough.

**Comment by superkhau** [comment]
@raymondfeng IMO, they are not anymore since we chose to go with the extends path (allows user defined sequences to inherit the builtin sugar methods anyways via `this.invoke`, etc).

**Comment by superkhau** [comment]
A more concrete example is like the first example at https://github.com/strongloop/loopback-next/wiki/Sequence, where as long as you extend Sequence, you have access to `this.sendResponse` (hence no need for @inject anything)

**Comment by bajtos** [comment]
Fair enough, let's close this issue.

We can discuss this topic more in the older issue https://github.com/strongloop/loopback-next/issues/67
