### ISSUE TITLE
How to pass `--grep` filter to Mocha when running `npm test`

### ISSUE THREAD

**Issue by ThePinger** [strongloop/loopback-next#2755]
## I have a problem whenever using the grep filter
Every time I run ```npm test --grep "HomePage"``` it displays a  warning message ```Warning: Cannot find any files matching pattern "HomePage"``` and runs all the tests despite having a describe with that keyword. You can find it in that repo https://github.com/ThePinger/first-project in ```/__tests__ /acceptance/home-page.acceptance.ts```. So does anyone have a solution to this problem ??

## Acceptance criteria

- [ ] Capture the information from https://github.com/strongloop/loopback-next/issues/2755#issuecomment-484373421 in our docs. Ideally, wait until https://github.com/strongloop/loopback-next/pull/6371 is landed and then add the new content to `docs/site/Debugging-tests-with-mocha.md`.

---

## 🎆 Hacktoberfest  2020

Greetings :wave: to all Hacktoberfest 2020 participants!

Here are few tips 👀 to make your start easier, see also #6456.

- Before you start working on this issue, please leave a comment to let others know.
- We don't have a full list of code snippets that are missing `import` statements, we rely on you to find the places needing improvement. Don't worry if you miss some, others will pick them up later. It's perfectly fine to work in small steps, changing only few pages in a single pull request. Baby steps FTW, every little helps!
- If you are new to GitHub pull requests, then you can learn about the process in [Submitting a pull request to LoopBack 4](https://loopback.io/doc/en/lb4/submitting_a_pr.html).
- If this is your first contribution to LoopBack documentation, then read [Documentation guide for LoopBack 4 developers](https://loopback.io/doc/en/lb4/code-contrib-lb4.html#documentation) please. Consider [previewing loopback-next docs only](https://loopback.io/doc/en/lb4/code-contrib-lb4.html#previewing-loopback-next-docs-only) for a faster feedback loop. Finally, please refer to [Contributing to LoopBack documentation](https://loopback.io/doc/en/contrib/doc-contrib.html) for a more advanced information on our Jekyll-based documentation infrastructure.
- Feel free to ask for help in `#loopback-contributors` channel, you can join our Slack workspace [here](https://join.slack.com/t/loopbackio/shared_invite/zt-8lbow73r-SKAKz61Vdao~_rGf91pcsw).

**Comment by bajtos** [comment]
IIRC, `npm` is treating `--grep` as its own option and does not pass it to the underlying script.  As a result, the following command is invoked to run Mocha tests - notice that `--grep` is not present and therefore Mocha treats `HomePage` as a name of a file to load:

```
> first-project@1.0.0 test /private/tmp/first-project
> lb-mocha --allow-console-logs "dist/__tests__" "HomePage"
```

You need to add `--` before any arguments you want to `npm` to pass directly to the invoked script.

```shell
$ npm test -- --grep "HomePage"
```

With that change, `npm` gives both `--grep` and `HomePage` arguments to `lb-mocha`:

```
> first-project@1.0.0 test /private/tmp/first-project
> lb-mocha --allow-console-logs "dist/__tests__" "--grep" "HomePage"
```

It would be great to capture this information in `DEVELOPING.md` file we create in scaffolded projects, see the template in [packages/cli/generators/project/templates/DEVELOPING.md](https://github.com/strongloop/loopback-next/blob/2bad7011e540e927598dc5a24c1d6ccf41bc0e93/packages/cli/generators/project/templates/DEVELOPING.md).

Would you @ThePinger like to contribute this improvement yourself? See [Contributing code in LoopBack 4](https://loopback.io/doc/en/contrib/code-contrib-lb4.html) and [Submitting a pull request to LoopBack 4](https://loopback.io/doc/en/lb4/submitting_a_pr.html) to get started.

**Comment by ThePinger** [comment]
@bajtos Well thanks a lot for the good elaboration that worked as expected, and of course I would like to contribute this improvement.

**Comment by jannyHou** [comment]
I believe this is covered in the new troubleshooting doc: https://loopback.io/doc/en/lb4/Debugging-tests-with-mocha.html#running-specific-tests

cc @bajtos closing this issue. Feel free to reopen it if necessary.
