### ISSUE TITLE
Can't install @loopback/socketio from npm

### ISSUE THREAD

**Issue by octisfall** [strongloop/loopback-next#2761]
## Description / Steps to reproduce / Feature proposal
I need to install socketio package from 
https://github.com/strongloop/loopback-next/tree/socketio/packages/socketio
it has README.MD with installation command

`npm install --save @loopback/socketio`

## Current Behavior

>npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@loopback%2fsocketio - Not found
npm ERR! 404 
npm ERR! 404  '@loopback/socketio@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

## Expected Behavior
Success installation

**Comment by raymondfeng** [comment]
@octisfall The module is not released yet. It's work in progress.

**Comment by octisfall** [comment]
@raymondfeng Is there a workaround to use websocket beside REST application?

**Comment by raymondfeng** [comment]
@octisfall Here is how you can test it:

```sh
git clone git@github.com:strongloop/loopback-next.git
cd loopback-next
git checkout socketio
npm i
npm run build
cd packages/socketio
npm pack ==> it creates a tgz
```

In your app:
```sh
npm i <path-to-the-tgz>
```
