### ISSUE TITLE
Implementing ts-mocha is throwing type errors in Inject

### ISSUE THREAD

**Issue by Navos** [strongloop/loopback-next#2764]
## Description / Steps to reproduce / Feature proposal
I've been trying to implement ts-mocha instead of the built in lb-mocha for faster test running and while I have taken care of the main issues within my code, one problem remains related to when `inject` checks if a getter or setter is a function.

The issue stems from the following lines: https://github.com/strongloop/loopback-next/blob/master/packages/context/src/inject.ts#L551 and https://github.com/strongloop/loopback-next/blob/master/packages/context/src/inject.ts#L426

When modifying the code and trying to make working adjustments, `typeof targetType === 'function'` returns true, but the check against the interface `Function` does not.

## Current Behavior
`The type of AuthenticateActionProvider.constructor[1] (Object) is not Setter function`

## Expected Behavior
It understand the given object is a function.

**Comment by raymondfeng** [comment]
It seems that `ts-node` does not emit `Function` for the design type of `Setter`. `ts-mocha` probably sees `Object` instead. Please note `typeof Object === 'function'` returns `true` as `Object` itself is a class/constructor.

**Comment by raymondfeng** [comment]
Maybe there is a possibility to relax the check if the design type is `Object`, which pretty much hints that no design type is inferred.

**Comment by raymondfeng** [comment]
@Navos Please try https://github.com/strongloop/loopback-next/pull/2765

**Comment by raymondfeng** [comment]
@Navos Can you make sure `emitDecoratorMetadata` is enabled for your ts-mocha setup. See https://www.typescriptlang.org/docs/handbook/compiler-options.html.

https://github.com/strongloop/loopback-next/pull/2765 skips the assertions but `@loopback/rest` also relies on the design time metadata for type introspection.

**Comment by Navos** [comment]
@raymondfeng I tried the seperate branch and the added the `emitDecoratorMetadata` and still having the same issue. Debugging through the new code, `isDesignTypeSupported` is returning true.

**Comment by raymondfeng** [comment]
If you have a github repo to reproduce the issue, I can take a look.

**Comment by Navos** [comment]
Hey Raymond, I can show you the code I am currently working on due to it being work related, but I reproduced the error with the log-extension example here https://github.com/Navos/ts-mocha-implementation/blob/master/package.json

**Comment by raymondfeng** [comment]
Here is the transpiled result from `ts-node`:

```ts
__decorate([
    context_1.inject(keys_1.EXAMPLE_LOG_BINDINGS.LOGGER, { optional: true }),
    __metadata("design:type", typeof (_a = typeof types_1.LogWriterFn !== "undefined" && types_1.LogWriterFn) === "function" ? _a : Object)
], LogActionProvider.prototype, "writeLog", void 0);
__decorate([
    context_1.inject(keys_1.EXAMPLE_LOG_BINDINGS.APP_LOG_LEVEL, { optional: true }),
    __metadata("design:type", typeof (_b = typeof keys_1.LOG_LEVEL !== "undefined" && keys_1.LOG_LEVEL) === "function" ? _b : Object)
], LogActionProvider.prototype, "logLevel", void 0);
LogActionProvider = __decorate([
    __param(0, context_1.inject.getter(core_1.CoreBindings.CONTROLLER_CLASS)),
    __param(1, context_1.inject.getter(core_1.CoreBindings.CONTROLLER_METHOD_NAME)),
    __param(2, context_1.inject(keys_1.EXAMPLE_LOG_BINDINGS.TIMER)),
    __metadata("design:paramtypes", [typeof (_c = typeof context_1.Getter !== "undefined" && context_1.Getter) === "function" ? _c : Object, typeof (_d = typeof context_1.Getter !== "undefined" && context_1.Getter) === "function" ? _d : Object, typeof (_e = typeof types_1.TimerFn !== "undefined" && types_1.TimerFn) === "function" ? _e : Object])
], LogActionProvider);

```

**Comment by raymondfeng** [comment]
And here is what `tsc` produces:
```ts
__decorate([
    context_1.inject(keys_1.EXAMPLE_LOG_BINDINGS.LOGGER, { optional: true }),
    __metadata("design:type", Function)
], LogActionProvider.prototype, "writeLog", void 0);
__decorate([
    context_1.inject(keys_1.EXAMPLE_LOG_BINDINGS.APP_LOG_LEVEL, { optional: true }),
    __metadata("design:type", Number)
], LogActionProvider.prototype, "logLevel", void 0);
LogActionProvider = __decorate([
    __param(0, context_1.inject.getter(core_1.CoreBindings.CONTROLLER_CLASS)),
    __param(1, context_1.inject.getter(core_1.CoreBindings.CONTROLLER_METHOD_NAME)),
    __param(2, context_1.inject(keys_1.EXAMPLE_LOG_BINDINGS.TIMER)),
    __metadata("design:paramtypes", [Function, Function, Function])
], LogActionProvider);
```

**Comment by raymondfeng** [comment]
`typeof context_1.Getter` is `undefined` as `Getter` is just a TypeScript type definition and it's erased at runtime. As a result, `ts-node` only emits `Object` instead of `Function`.

**Comment by Navos** [comment]
@raymondfeng Hey Raymond, what will happen with this issue?

**Comment by bajtos** [comment]
Possibly related: https://github.com/strongloop/loopback-next/pull/3160

@Navos is this issue still relevant? Have you managed to find any solution or any workaround?

I am looking into ways how to switch loopback-next from Mocha to Jest (see https://github.com/strongloop/loopback-next/issues/3159). It seems to me that the solution for on-the-fly-compilation used by Jest is different from the solution used by `ts-mocha` (and `ts-node`) and the problem described in this issue is not triggered by Jest.

Would you like to try [Jest](https://jestjs.io) instead of `ts-mocha` and let us know if it works any better?
