### ISSUE TITLE
Injecting Repository Getter vs the Repository itself

### ISSUE THREAD

**Issue by Narrator** [strongloop/loopback-next#2772]
Hi,

I'm wondering why you'd want to inject `@repository.getter()` when you can inject the `@repository()` directly in a `Repository` class. For instance:

```ts
class ContactEmailRepository {
  constructor(
    .. other injectables..
    @repository.getter('ContactRepository')
    protected contactRepositoryGetter: Getter<ContactRepository>,
  ) {
    super(ContactEmail, dataSource);

    this.contact = this.createBelongsToAccessorFor(
      'contact',
      contactRepositoryGetter,
    );
  }
}
```

^^ I understand the `createBelongsToAccessorFor` method requires the getter, but is that the only use case? If I want to access the actual repository methods, I'd have to resolve the repository from the getter first and then make the repository calls like so:
```ts
  const contactRepository = await this.contactRepositoryGetter();
  const contact = await contactRepository.findById(contactId);
```

Instead of that, I can just directly inject the repository like so:
```ts
class ContactEmailRepository {
  constructor(
    .. other injectables..
    @repository(ContactRepository) public contactRepository: ContactRepository
  ) {}
}
```
Then, I can just do:
```ts
const contact = await this.contactRepository.findById(contactId);
```

Is there are reason for the getter that I'm completely missing?

**Comment by hoangleanhtu** [comment]
The different is the time to resolve instance of ContactRepository.

- `@repository(ContactRepository)` resolves instance of ContactRepository when you initial instance of ContactEmailRepository
- But, if somehow, you can not resolve instance of ContactRepository when you initial instance of ContactEmailRepository, then let using `@repository.getter('ContactRepository')` and resolve its instance when you need by calling `const contactRepository = await this.contactRepositoryGetter();`

So when can't you resolve instance of a class? One example is when you have circular dependency like this:

```typescript
class ContactEmailRepository {
  constructor(
    @repository(ContactRepository)
    public contactRepository: ContactRepository
  ) {}
}

class ContactRepository {
  constructor(
    @repository(ContactEmailRepository) 
    public contactEmailRepository: ContactEmailRepository
  ) {}
}
```
So it's better to use `@repository.getter` in a relationship.
Above is just an example, you may need to use `@inject.getter` in similar cases.

**Comment by bajtos** [comment]
As @hoangleanhtu explained above, we are using `@inject.getter` to break circular dependencies.
