### ISSUE TITLE
Compressing / Zip API response

### ISSUE THREAD

**Issue by haresh333** [strongloop/loopback-next#2780]
I am using Loopback 3.

I have few APIs that return large data JSON about 15MB. I want LB server to compress it before sending to client and then have it decompressed on client side.

Please advice how I can achieve this

**Comment by raymondfeng** [comment]
See https://loopback.io/doc/en/lb3/Defining-middleware.html

**Comment by dhmlau** [comment]
Closing this issue as answered.
