### ISSUE TITLE
How debugging  Loopback 4

### ISSUE THREAD

**Issue by pavelgronsky** [strongloop/loopback-next#2791]
Hello. I don't understand how I can debug Loopback 4 project?

First: I added **debbuger** to my controller.ts but after **npm start** I can't  to catch debugger in chrome console. 
Second: I try to debugging used VSCode. But it doesn't work for me. 

What I must added to launch.json and package.js for debuging code and why my debugger doesn't work in Chrome? 

Who can explain why Chrome doesn't have file from controller, model and repo ?

**Comment by Narrator** [comment]
I've been debugging successfully using VSCode. Try adding this to your launch config:

Using nodemon (So it auto-reloads on file save given you have the transpiler running)
```ts
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Retroactive Server",
      "runtimeExecutable": "nodemon",
      "program": "${workspaceFolder}/index.js",
      "outFiles": [
        "${workspaceFolder}/**/*.js"
      ],
      "restart": true,
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "envFile": "${workspaceFolder}/.env",
    }
}
```

Using only node:
```
```ts
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Retroactive Server",
      "runtimeExecutable": "node",
      "program": "${workspaceFolder}/index.js",
      "outFiles": [
        "${workspaceFolder}/**/*.js"
      ],
      "restart": true,
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "envFile": "${workspaceFolder}/.env",
    }
}
```

**Comment by dhmlau** [comment]
@Narrator, thanks for the information.  I think it would be beneficial to have that in our documentation: https://github.com/strongloop/loopback-next/blob/master/docs/site/DEVELOPING.md.  Would you like to submit a PR?  Thanks.

**Comment by pavelgronsky** [comment]
@Narrator Hello. 
Thanks for your your reply. But when I run project by launch.json in VSCode I cann debugger inside VSCode, but my nodemoon doesn't work. 

I try to explain my situation:
I have two configuration in my launch.json. First conf. work only by **node runtimeExecutable**. I't work fine for me. But, when I try to run configuration by **nodemon runtimeExecutable**, I take only debugger works. Nodemon doesn't work. 

Then I tried to run nodemon separately by npm command. 

I added: script to packaje.json **"dev": "nodemon server.js"**

And added nodemon config to package.json:

**"nodemonConfig": {
    "verbose": true,
    "watch": [
      "src/"
    ],
    "ignore": [
      "dist/*"
    ],
    "ext": "ts",
    "exec": "npm start"
  }**

Then nodemon work by **npm run dev** command

Questions: How I can run nodemon and debugger together by your config by launch.json?
And How run nodemon and debugger together by npm command?

**Comment by pookdeveloper** [comment]
@Narrator is possible to use: 
➜  DEBUG=loopback:connector:* npm start
or
➜  DEBUG=loopback:connector:* npm run build:watch

With the vscode debugger ? I want to use DEBUG MODE (to show more info in the console log) with the vscode debugger, Thanks!

**Comment by dhmlau** [comment]
@pookdeveloper, you might want to take a look at the `launch.json` in  https://github.com/strongloop/loopback4-example-shopping/blob/master/.vscode/launch.json as a reference for running on debug.

**Comment by pookdeveloper** [comment]
I see @dhmlau but I want to activate the **DEBUG MODE** for loopback to view a log about the queries of the database etc.. Thanks!

**Comment by dougal83** [comment]
@dhmlau Is the lb3 page still relevant? https://loopback.io/doc/en/lb3/Setting-debug-strings.html  I think that is what is being requested.

**Comment by pookdeveloper** [comment]
@dougal83 If now it is used the same as raymondfeng commented in the issue: https://github.com/strongloop/loopback-next/issues/3027

I want to know if a can use that with nodemon and restart automatically  the server: Like that @Narrator says before (https://github.com/strongloop/loopback-next/issues/2791#issuecomment-486292004), I mean Loopback in debug mode and vscode in debug mode, thanks

**Comment by dougal83** [comment]
@pookdeveloper So if I understand correctly, these are env variables?  So perhaps, inject them?  See https://stackoverflow.com/questions/29971572/how-do-i-add-environment-variables-to-launch-json-in-vscode.  Is that what you are looking for?

**Comment by pookdeveloper** [comment]
yes @dougal83 , this is i needed !! Thanks!!
`      "env": {
        "DEBUG": "loopback:connector:*"
      },`
Entry launch.json file:
````json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Server auto reload",
      "runtimeExecutable": "nodemon",
      "program": "${workspaceFolder}/index.js",
      "outFiles": [
        "${workspaceFolder}/**/*.js"
      ],
      "env": {
        "DEBUG": "loopback:connector:*"
      },
      "restart": true,
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "envFile": "${workspaceFolder}/.env",
    }
  ]
}
````
I run:
➜  npm run build:watch
Then enter debug mode F5 in VSCode
Thanks again!

**Comment by pavelgronsky** [comment]
Thanks!
