### ISSUE TITLE
Python-shell using loopback 4

### ISSUE THREAD

**Issue by sureshkodur** [strongloop/loopback-next#2796]
Can anyone know how to execute python-shell in lb4.
I'm trying to execute the python-shell in controller, but before the python-shell execution, the response is 204. It does not returning any content. Please help me.

**Comment by hacksparrow** [comment]
What is python-shell? A link will help.

**Comment by sureshkodur** [comment]
var {PythonShell} = require('python-shell');

**Comment by dougal83** [comment]
Tried "import * as PythonShell from 'python-shell';"?
