### ISSUE TITLE
API Explorer ignores `where` filter

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2804]
## Description 
In the API Explorer, the `where` filter is being ignored.

## Steps to reproduce 
Using `todo-list` example, 
1. create todolist with ids 1, 2, and 3. 
2. create 3 todo's, one for each todolist:
```
[
  {
    "id": 10,
    "title": "todo 1",
    "desc": "string",
    "isComplete": false,
    "todoListId": 1
  },
  {
    "id": 20,
    "title": "todo 2",
    "desc": "string",
    "isComplete": false,
    "todoListId": 2
  },
  {
    "id": 30,
    "title": "todo 3",
    "desc": "string",
    "isComplete": false,
    "todoListId": 3
  }
]
```
3. in the API explorer, call `GET /todos` with the following filter:
```
{
  "where": {"todoListId": 1}
}
```

It returns all the `todo` instances regardless of the todoListId. 

However, if I call `http://localhost:3000/todos?filter[where][todoListId]=1` from a browser, it's returning the right response.

## Investigation
From @nabdelgadir. 
Printing out what get passed into `filter` 
```
async findTodos(
    @param.query.object('filter', getFilterSchemaFor(Todo)) filter?: Filter,
  ): Promise<Todo[]> {
    console.log(filter);
    return await this.todoRepo.find(filter);
  }
```
it returns `undefined` from the explorer but `{ where: { todoListId: '1' } }` from the link

## Current Behavior
API Explorer ignores the `where` filter.

**Comment by bajtos** [comment]
See https://github.com/strongloop/loopback-next/issues/2208#issuecomment-453005884.

> I am afraid this is a known bug/limitation of swagger-ui and swagger-js, see the discussion in #1679 and the tracking issue swagger-api/swagger-js#1385.
>
> You can see this yourself in API Explorer UI. When you send the request, the UI shows the full URL, request headers and response headers. There you can see that the request URL created by API Explorer (swagger-js) does not contain the filter properties.
>
> Unfortunately swagger-ui does not warn the user about this problem, which makes the entire experience less than ideal.

**Comment by dhmlau** [comment]
Thanks @bajtos.  Closing as duplicate of https://github.com/strongloop/loopback-next/issues/2208.
