### ISSUE TITLE
How to execute raw MongoDB queries

### ISSUE THREAD

**Issue by sureshkodur** [strongloop/loopback-next#2807]
## Description / Steps to reproduce / Feature proposal
How to use raw queries like aggregation on mongodb. Is there any solution ?
## Expected Behavior
I want to use raw queries or other models. For example, Customer model, and Products model. I need to write aggregate query like 

```js
db.LoanRequestMappings.aggregate([
    {
        $lookup:{
            .....   
        }
    },
    {   $unwind:"$data" },
    {
        $match:{
            ...
        }
    },
    {
        $lookup:{
            ... 
        }
    },
    {   $unwind:"$LoanRepayment" },
    { $project : { _id: 0} },
    { $out : "tempData" }
])
```

on product model while getting customer model. 
 
Please help.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
You can execute raw queries using the recently introduced `Repository` method `execute`, see https://github.com/strongloop/loopback-next/pull/2681. This works great for SQL connectors.

Based on the code we have in [loopback-datasource-juggler](https://github.com/strongloop/loopback-datasource-juggler/blob/47addd943adfd7ace37cd52d2d4dcbd04ee7c0d8/lib/datasource.js#L2606-L2643) and [loopback-connector-mongodb](https://github.com/strongloop/loopback-connector-mongodb/blob/f67d1e5660e875a839b78177eafdbceb97b686ba/lib/mongodb.js#L449-L520), I suspect the `execute` method will not work for MongoDB, because the connector requires more than just a `command` string and `args` array :(

We need to find a way how to improve LB4 API, MongoDB connector API or both, to make it easy to execute raw MongoDB commands.

Until that happens, you can call MongoDB connector's `execute` method directly. 

```ts
const repo = // obtain the repository instance, e.g. via @inject()
const result = await new Promise((resolve, reject) => {
  repo.dataSource.connector.execute('LoanRequestMappings', 'aggregate', [
    {
        $lookup:{
            .....   
        }
    },
    {   $unwind:"$data" },
    {
        $match:{
            ...
        }
    },
    {
        $lookup:{
            ... 
        }
    },
    {   $unwind:"$LoanRepayment" },
    { $project : { _id: 0} },
    { $out : "tempData" }
  ],
  (err, data) => {
    if (err) reject(err);
    else resolve(data);
  });
});
```

**Comment by sureshkodur** [comment]
Hi @bajtos , I tried the above code as below, 
<img width="713" alt="Screen Shot 2019-04-30 at 11 21 52 AM" src="https://user-images.githubusercontent.com/31954801/56942836-60ee0e80-6b3a-11e9-82de-63d5dea0103e.png">

Its not working

**Comment by dougal83** [comment]
What error is the red underline indicating? Are the parameters correct?

**Comment by sureshkodur** [comment]
@bajtos said dataSource.connector.execute will work. But it giving undefined connector. See the second image.  I tried #2021 . But it is also not working. it says 500 TypeError: Cannot read property 'settings' of undefined at MongoDB.collectionName . Can you help me

**Comment by dougal83** [comment]
@sureshkodur Sorry I didn't see the images via email earlier.  Maybe screen dumps are less than optimal..

It looks like you're falling foul of typescripts type checking.  I think you'll need to provide a repo in order to get help with this.

**Comment by sureshkodur** [comment]
Hi @dougal83 , My code is for aggregation is below
```
async create(
    @requestBody() loanClosingStatus: LoanClosingStatus[],
  ): Promise<any> {
    // let repayments = await this.loanClosingStatusRepository.createAll(
    //   loanClosingStatus,
    // );

    console.log(
      'Connected:',
      this.loanClosingStatusRepository.dataSource.connected,
    );
    if (!this.loanClosingStatusRepository.dataSource.connected) {
      console.log('Waiting for connection...');
      await this.loanClosingStatusRepository.dataSource.connect();
    }
    console.log(
      'Connected:',
      this.loanClosingStatusRepository.dataSource.connected,
    );
    console.log('Getting loanMappingCollection...');
    const _loanMappingCollection = (this.loanClosingStatusRepository.dataSource
      .connector as any).collection('LoanRequestMappings');

    console.log(_loanMappingCollection);

     return await _loanMappingCollection
      .aggregate([
        {
          $lookup: {
            from: 'LoanRequests',
            localField: 'RequestID',
            foreignField: 'input_requestID',
            as: 'AvailableLoanRequests',
          },
        },
        {$unwind: '$AvailableLoanRequests'},
        {
          $match: {
            $or: [
              {RequestID: '152216107695585237'},
              {RequestID: '152216076180212068'},
            ],
          },
        },
        {
          $lookup: {
            from: 'LoanClosingStatus',
            localField: 'LoanID',
            foreignField: 'LoanID',
            as: 'LoanRepayment',
          },
        },
        {$unwind: '$LoanRepayment'},
        {$project: {_id: 0}},
        {$out: 'tempData'},
      ])
      .get();
  }
```
I'm getting the below error.

--- Database in local Mode ---
{ name: 'mongoDs',
connector: 'mongodb',
url: 'mongodb://localhost:27017/xxdb' }
Server is running at http://[::1]:3000
Connected: false
Waiting for connection...
Connected: true
Getting loanMappingCollection...
Unhandled error in POST /closingStatus: 500 TypeError: Cannot read property 'settings' of undefined
at MongoDB.collectionName (/Volumes/Projects/WORKSPACE/suresh-koduri/loopback/projectlb4/node_modules/loopback-connector-mongodb/lib/mongodb.js:341:18)
at MongoDB.collection (/Volumes/Projects/WORKSPACE/suresh-koduri/loopback/projectlb4/node_modules/loopback-connector-mongodb/lib/mongodb.js:356:29)
at LoanClosingStatusController.create (/Volumes/Projects/WORKSPACE/suresh-koduri/loopback/projectlb4/dist/controllers/loan-closing-status.controller.js:45:24)
at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by dougal83** [comment]
@sureshkodur Sorry I can't help you based on the code you've shown.  Please bear in mind that I'm just learning LB4 too.  Without the ability to run your code I'm at a loss.  Hopefully someone else can come along and help.

**Comment by bajtos** [comment]
@sureshkodur is this issue still relevant? Please create a small application we can use to reproduce the problem, see https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs

**Comment by bajtos** [comment]
I opened a new issue to describe the more generic feature we are looking for - the ability to execute raw MongoDB queries. See https://github.com/strongloop/loopback-next/issues/3342

It would be great if you can up-vote the issue by adding a :+1: reaction (not a comment please, see https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/), that way we will know how many people are asking for this particular feature.

**Comment by VigneshMeem** [comment]
To resolve as array you can use like this 
`       (err: any, data: any) => {
          console.log('err ', err);
          // console.log('data ', data);
          if (err) reject(err);
          else resolve(data.toArray());
        });`

**Comment by VigneshMeem** [comment]
> You can execute raw queries using the recently introduced `Repository` method `execute`, see #2681. This works great for SQL connectors.
> 
> Based on the code we have in [loopback-datasource-juggler](https://github.com/strongloop/loopback-datasource-juggler/blob/47addd943adfd7ace37cd52d2d4dcbd04ee7c0d8/lib/datasource.js#L2606-L2643) and [loopback-connector-mongodb](https://github.com/strongloop/loopback-connector-mongodb/blob/f67d1e5660e875a839b78177eafdbceb97b686ba/lib/mongodb.js#L449-L520), I suspect the `execute` method will not work for MongoDB, because the connector requires more than just a `command` string and `args` array :(
> 
> We need to find a way how to improve LB4 API, MongoDB connector API or both, to make it easy to execute raw MongoDB commands.
> 
> Until that happens, you can call MongoDB connector's `execute` method directly.
> 
> ```ts
> const repo = // obtain the repository instance, e.g. via @inject()
> const result = await new Promise((resolve, reject) => {
>   repo.dataSource.connector.execute('LoanRequestMappings', 'aggregate', [
>     {
>         $lookup:{
>             .....   
>         }
>     },
>     {   $unwind:"$data" },
>     {
>         $match:{
>             ...
>         }
>     },
>     {
>         $lookup:{
>             ... 
>         }
>     },
>     {   $unwind:"$LoanRepayment" },
>     { $project : { _id: 0} },
>     { $out : "tempData" }
>   ],
>   (err, data) => {
>     if (err) reject(err);
>     else resolve(data);
>   });
> });
> ```
To resolve as array : 
`>     else resolve(data.toArray());
`
