### ISSUE TITLE
Redirection to Swagger UI is cached too aggressively

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#2808]
## Description

1. Start an app with redirection to Swagger UI enabled (older apps have it enabled by default).
2. Load `localhost:3000/explorer` in the browser. The request will be redirected to `http://explorer.loopback.io/?url=http://localhost:3000/openapi.json`.
3. Stop the app.
4. Start another app with redirection **disabled** (default behavior in latest apps).
5. Load `localhost:3000/explorer`. This request is also redirected to `http://explorer.loopback.io/?url=http://localhost:3000/openapi.json`.

## Expected Behavior

If redirection is disabled (default), it should not be redirected.

##  Cause

Request to `localhost:3000/explorer` in the first app, sent a `308` (Permanent Redirect) response. The browser remembers this.

Now on, any request to `localhost:3000/explorer` will be redirected to `http://explorer.loopback.io/?url=http://localhost:3000/openapi.json`.

---

Why was `308` chosen as the response code? Wouldn't `302` make more sense? Enabling or disabling redirection may not be a permanent decision. One may change their decision about it any time.

**Comment by bajtos** [comment]
Good catch!

> Why was 308 chosen as the response code? Wouldn't 302 make more sense? Enabling or disabling redirection may not be a permanent decision. One may change their decision about it any time.

I don't remember the reasoning behind this decision. Have you tried to run `git blame` to find the commit & pull request that introduced the `308` status code?

Personally, I am fine to change our implementation to use `302 Found` instead of `308 Permanent Redirect`.

Quoting from https://httpstatuses.com/302
> The target resource resides temporarily under a different URI. Since the redirection might be altered on occasion, the client ought to continue to use the effective request URI for future requests.

Quoting from https://httpstatuses.com/308
> The target resource has been assigned a new permanent URI and any future references to this resource ought to use one of the enclosed URIs.
