### ISSUE TITLE
How do I listen to unix socket instead binding http server to an ip address and port?

### ISSUE THREAD

**Issue by reinaldorauch** [strongloop/loopback-next#2811]
## Description / Steps to reproduce / Feature proposal
Currently in @loopback/rest RestApplication we can only bind the http server to an ip address and port as in [the docs](https://loopback.io/doc/en/lb4/Server.html). Can we make an option in configs to make the RestApplication to listen to a socket like node HttpServer.listen [does](https://nodejs.org/dist/latest-v12.x/docs/api/net.html#net_server_listen_path_backlog_callback)?

[StackOverflow Question](https://stackoverflow.com/questions/55910312/how-i-listen-to-a-unix-socket-in-loopback-4)

## Current Behavior

The RestApplication/server config receives host and port configurations like:

```js
const config = {
  // ...
  rest: {
    host: '127.0.0.1',
    port: 3000,
  }
  // ...
};
```

## Expected Behavior

The RestApplication/Server config should accept a socket option to pass a path to listen to:

```js
const config = {
  // ...
  rest: {
    // ...
    socket: '/path/to/unix/socket.sock',
    // ...
  }
};
```

The priority may be socket -> host,port -> host, port default but IHMO the first two could be mutually exclusive.

Many thanks for your attention,

Reinaldo

**Comment by raymondfeng** [comment]
@reinaldorauch Can you elaborate your use case over local socket?

**Comment by reinaldorauch** [comment]
@raymondfeng 
1. Because my hosting provider only accepts binding in a unix socket that they specifies. (they use nginx as reverse proxy to manage the incoming http requests to forward them to node). 
2. Another reason is to conform to nodejs api that overloads listening to a unix socket/named pipe in http/https/net servers.
3. And yet there is that using unix socket/named pipe, that were made for IPC, there less overhead that using a TCP bind (as seen [here](https://stackoverflow.com/questions/14973942/tcp-loopback-connection-vs-unix-domain-socket-performance)

I found a way around it by using [socat](https://linux.die.net/man/1/socat), redirecting the requests comming from the named pipe to the tcp bind exposed by loopback.

**Comment by raymondfeng** [comment]
@reinaldorauch Please check out https://github.com/strongloop/loopback-next/pull/2812

**Comment by reinaldorauch** [comment]
Very nice @raymondfeng I think that will perfect! Thanks a lot, you're very helpful :D

**Comment by raymondfeng** [comment]
The fix is released.

**Comment by VictorLeach96** [comment]
Was `RestApplication` ever updated as part of this? I don't think it was.
