### ISSUE TITLE
docs: Loopback GDPR Readiness

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#2813]
## Description / Steps to reproduce / Feature proposal
Visit https://loopback.io/doc/en/lb4/Deploy-for-GDPR-readiness.html#product-configuration---considerations-for-gdpr-readiness

## Current Behavior
Under "Product Configuration for GDPR" > "LoopBack Overview", the first statement is:
"Please note that LoopBack 4 is in developer preview and not ready for production. For production, use LoopBack 3."

## Expected Behavior
LoopBack 4 has reached General Availability and this statement shouldn't appear (Or shouldn't state that LB4 is under a "developer preview").

![image](https://user-images.githubusercontent.com/25147899/56944031-9a337800-6b54-11e9-9dd7-1728f1367601.png)

**Comment by dhmlau** [comment]
@achrinza, thanks for reporting this. This docs was prepared at the time when LB4 is still in Developer Preview, and now should be updated.
