### ISSUE TITLE
When we delete the record, we need to return true(Deleted) or false(Not Deleted)

### ISSUE THREAD

**Issue by AnanthGopal** [strongloop/loopback-next#2819]
When we delete the record, we need to return true(Deleted) or false(Not Deleted or error occured)

**Comment by dougal83** [comment]
You can customise the controller to deliver that behaviour, if you mean the api response?

**Comment by AnanthGopal** [comment]
@dougal83  just I asked to implement that feature, because that is basic feature so only i am asking. Its okay fine.

**Comment by dougal83** [comment]
@AnanthGopal The loopback 4 framework delivers a CRUD implementation via the CLI.  You can alter the controller produced or write your own entirely.

You are free to alter the controller like so for the delete function to give the basic customisation that I think you are after:
````ts
  @del('/todos/{id}', {
    responses: {
      '200': {
        description: 'Transaction DELETE custom boolean response',
        content: {
          'application/json': {
            schema: {
              type: 'boolean',
            },
          },
        },
      },
    },
  })
  async deleteById(@param.path.number('id') id: number): Promise<boolean> {
    return await this.todoRepository
      .deleteById(id)
      .then(() => {
        // promise fullfilled ergo successful deletion
        return true;
      })
      .catch(() => {
        // promise rejected ergo failure to delete
        return false;
      });
  }
````

Is this more or less the functionality you are looking for?

**Comment by AnanthGopal** [comment]
Thank you
