### ISSUE TITLE
Metadata on bindings and container traversal

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#282]
- What's the official container API to fetch the binding info
- Define the meaning behind the key hierarchy
- Corresponding APIs to traverse through the hierarchy (container.get('component') vs container.get('component/xyz', etc)
- Define namespace separator

Relevant issues:
- https://github.com/strongloop/loopback-next/issues/258
- https://github.com/strongloop/loopback-next/issues/461

**Comment by raymondfeng** [comment]
For metadata associated with binding, we can possibly have:
```
container.bind('components/my-component').toClass(MyComponent).withMetadata({...});
```

**Comment by bajtos** [comment]
@raymondfeng is this issue still relevant? Can we close it?

**Comment by dhmlau** [comment]
Closing it as it's been resolved.
