### ISSUE TITLE
loopback framework is open source framework or not. If this framework is open source, provide the MIT licence details 

### ISSUE THREAD

**Issue by AnanthGopal** [strongloop/loopback-next#2826]
loopback framework is open source framework or not. If this framework is open source, provide the MIT licence details. Where you are mentioned licence details.

**Comment by dougal83** [comment]
https://github.com/strongloop/loopback-next/blob/master/LICENSE

**Comment by raymondfeng** [comment]
LoopBack is an open source framework with modules released under MIT license. See https://github.com/strongloop/loopback-next#license.

**Comment by AnanthGopal** [comment]
Thank you @raymondfeng
