### ISSUE TITLE
Question about compatibility of data source connectors with microsoft access (accdb)

### ISSUE THREAD

**Issue by charlypeluch** [strongloop/loopback-next#2833]
## Question
I have been working with Loopback 4 for a few weeks and I have had to work with a microsoft access database (against my will, xD). I have been reading about the connectors for datasource, but I have not seen any specific connection to MS Access through an accdb file.

Is there a connector available that I can use to connect to this database? If yes, could you give me an example that you can consult for its implementation?

Thanks in advance

**Comment by dhmlau** [comment]
@charlypeluch, we don't have a connector for MS Access.  I did some search and didn't find any community connector on MS Access either.

@raymondfeng, do you have some suggestions? Thanks.

**Comment by charlypeluch** [comment]
Any suggestions?

**Comment by raymondfeng** [comment]
If there is a Node.js driver available, you can use it in controllers directly or build a service around your need to access `MS Access`.

**Comment by bajtos** [comment]
If MS Access supports ODBC, then you may be able to access it via ODBC. There seems to be quite few ODBC packages on npmjs (e.g. https://www.npmjs.com/package/odbc and https://www.npmjs.com/package/@ratanakvlun/node-odbc).

**Comment by dhmlau** [comment]
Closing this issue as answered. Thanks.
