### ISSUE TITLE
Ability to create base controller

### ISSUE THREAD

**Issue by ruslankrivoshein** [strongloop/loopback-next#2835]
I'd like unify to request processing and reduce code for identical operations. Framework familiarization goes hard for me, but I try to implement this idea.

**base.controller.ts**:
```
let PATH = '';

@api({basePath: '/api/v1', paths: []})
export class BaseController<T, R> {
  constructor(public path: string, public repo R) {
    PATH = path;
}

@get(PATH)
async get(): Promise<Partial<T[]>> {
  // example operations of routine
  const res = await this.repo.find();
  return res.map((i) => {
    _.unset(i, 'password');
    return assignIt({}, i, {
      request: {type: 'GET', url: `http://localhost/users/${i.id}`},
  });
}
```

**user.controlles.ts**:
```
export class UserController extends BaseController<User, UserRepository> {
  constructor(
    @repository(UserRepository)
    public userRepository: UserRepository,
  ) {
    super('/users', userRepository);
  };

  // and here I should not write code for simple get
}
```

This way is beautiful in my opinion, but var PATH don't initializable, when I start server, so app has not 'users' endpoint. Perhaps, I do something weird, hence I'd like also if somebody suggest more elegant way for this...

**Comment by raymondfeng** [comment]
Use something similar as https://github.com/strongloop/loopback-next/blob/952d23e2a548569a6bd75026dbae7d9291dbf593/packages/repository-rest/test/acceptance/crud-controller.ts

**Comment by raymondfeng** [comment]
The other option is to use a class factory, such as:
```ts
export function controllerClassFactory(path: string, name: string) {
  @bind(tags: {name})
  @api({basePath: path})
  class BaseController {...}

  return BaseController;
}
```

**Comment by guitarhero1** [comment]
> Use something similar as https://github.com/strongloop/loopback-next/blob/952d23e2a548569a6bd75026dbae7d9291dbf593/packages/repository-rest/test/acceptance/crud-controller.ts

I was just trying so, but that way I must write methods in derivative class all the same. I was trying to avoid this :)
I can't pass field with endpoint to decorators, so I chose some way, but it doesn't work on framework level. I wanna just pass endpoint to base class and don't write base CRUD logic in derivative class...
