### ISSUE TITLE
How to use the reference authentication package?

### ISSUE THREAD

**Issue by webmaster-ar** [strongloop/loopback-next#2839]
**Questions**

I have been studying Loopback 4 for a few days. I want to create a production version, however I concern about that Loopback 4 authentication package is not production ready and it is just a reference. So I'm not sure how should we use that reference.
I have the following questions:
- Should we create a separate version based on that package?
- Is the package safe to base my security on it?
- Is that somethings are unfinished, but we can use the base?
- There is an approximate date to be ready for production or it will be always a reference?

**Comment by diegoazh** [comment]
I have the same questions. I need an authentication package, component or something else, but I not sure if this package will be finished. I would to contribute in the development of this component but I don't know if it  will be a package for productiono or it will be always a reference.
have there some shcedule to work on it?

**Comment by dougal83** [comment]
If you follow the [authentication label](https://github.com/strongloop/loopback-next/labels/Authentication) you can see the authentication issues and that includes labels that indicate the targeted delivery date namely 2019 Q3.

You can look at WIP repos under strongloop like https://github.com/strongloop/loopback-component-passport if you are interested but as auth. is in active development there is a high chance of breaking changes atm. I don't think it's considered production ready until the feature is documented at https://loopback.io/doc/en/lb4/ and is stated as such.

**Comment by jannyHou** [comment]
We are going to release a new major version `@loopback/authentication@2.0.0`, there are 3 related feature+blog stories team is actively working on:

https://github.com/strongloop/loopback-next/issues/2467
https://github.com/strongloop/loopback-next/issues/2311
https://github.com/strongloop/loopback-next/issues/2725(the blog will be published as a summary in the last step)

And @emonddr is refactoring the shopping cart example https://github.com/strongloop/loopback4-example-shopping/issues/79 to use the new auth system in `@loopback/authentication@2.0.0`

You can find more details in @dougal83 's update above (Thank you Daugal).

**Comment by jannyHou** [comment]
Self-assigned, I will update the tutorial here after finishing story #2467 and #2311

**Comment by gopalakrishnan-subramani** [comment]
+1, we need auth example as soon as possible to roll out basic integration with Authentication. We use lb4 for a project, we could not move further without authentication. Hope someone could give an example github example that can do hello world level authentication.

**Comment by samarpanB** [comment]
@gopalakrishnan-subramani you can take a look at [this](https://github.com/sourcefuse/loopback4-authentication) extension we created for the community members to help them with authentication in LB4 until it is complete and stable in loopback core. There is a boiler plate project also created using this package. You can refer to [that](https://github.com/sourcefuse/loopback4-starter) for example.

**Comment by jannyHou** [comment]
FYI - The new docs are already available. 

See:
https://loopback.io/doc/en/lb4/Loopback-component-authentication.html
https://loopback.io/doc/en/lb4/Authentication-Tutorial.html
Using passport based strategy: https://www.npmjs.com/package/@loopback/authentication-passport

I am closing this issue, feel free to reopen it if you still have questions :)
