### ISSUE TITLE
Better way to register binding names for components/sequences

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#284]
In @loopback/core/src/Application.ts, we use:

```
const componentClassName = component.toString().split(' ')[1];
```

to get the class name from the Array passed in the `AppConfig` options in the Application constructor.

The issue is `componentClassName.constructor.name` + `componentClassName.name` does not return the actual class name when it's part of the injected `appConfig` options.

The goal of this issue is to figure out a more elegant way to do this -- I might be missing something simple in the current implementation that prevents this.

**Comment by bajtos** [comment]
In https://github.com/strongloop/loopback-next/pull/359, we are using component class name directly:

```ts
  public component(component: Constructor<Component>) {
    const componentKey = `components.${component.name}`;
    this.bind(componentKey).toClass(component);
    const instance = this.getSync(componentKey);
    mountComponent(this, instance);
  }
```

I am closing this issue as done. Feel free to reopen if you disagree, @superkhau.
