### ISSUE TITLE
[Spike] Resolve the relational path's url

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#2855]
## Description / Steps to reproduce / Feature proposal

This is a spike of story https://github.com/strongloop/loopback-next/issues/2483:
Before we construct the relation controller from the static file, we need to decide where to define the relation endpoints(in a new controller class or in "modelFrom"'s controller), and how to resolve the relational path's url.

Copy from the original discuss:

> This story may need a spike to figure out how to map the relational paths to REST endpoints.
> 
> Reference story:
> Hierarchical resource locator: #802
> 
> /Users/{id}/orders
> 
>     * delegate to user controller
> 
>     * user controller interprets the `/orders`, resolve the url
> 
>     * delegate to order controller
> 
> 
> Proposal:
> Delegate the url resolve to controller, instead of defining the path pattern in relation controller

**Comment by dhmlau** [comment]
@b-admike, could you please add the acceptance criteria? thanks.

**Comment by bajtos** [comment]
We should be using the same approach we already have in place for relations, where a new controller class is created for every relation. E.g. `UserOrdersController` to handle all endpoints in `/Users/{id}/orders` path space.

**Comment by bajtos** [comment]
> @dhmlau added 2019Q2  p1  labels 3 days ago

I think it's too early to work on this spike and the story "From relation definition to REST API with no repository/controller classes #2483" in general. We need to implement "From model definition to REST API with no custom repository/controller classes #2036" first, because relations will leverage the foundational blocks provided #2036.

**Comment by dhmlau** [comment]
@bajtos, thanks for the info. Since #2036 (which needs to be implemented first) is planning for `2019Q3`, I'll move this spike to Q3 for now.

**Comment by jannyHou** [comment]
Close it in favor of https://github.com/strongloop/loopback-next/issues/3896
