### ISSUE TITLE
Develop a script to migrate LoopBack 3.x apps to LoopBack Next

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#287]
We should explore the possibility to develop a script to help migrate existing LB apps to next:

See some frameworks such as:
https://github.com/facebook/jscodeshift

**Comment by dhmlau** [comment]
spike is done here: https://github.com/strongloop/loopback-next/issues/485

**Comment by bajtos** [comment]
> Develop a script to migrate LoopBack 3.x apps to LoopBack Next

Labeling as post-GA. @raymondfeng @dhmlau please let me know if you object.
