### ISSUE TITLE
How to set 'trust proxy'?

### ISSUE THREAD

**Issue by DongWenHu** [strongloop/loopback-next#2873]
How to set 'trust proxy'?

**Comment by raymondfeng** [comment]
https://loopback.io/doc/en/lb4/Server.html#express-settings

**Comment by diegoblasco** [comment]
> https://loopback.io/doc/en/lb4/Server.html#express-settings

Add the expressSettings to your RestApplication config.

```
const app = new RestApplication({
  rest: {
    expressSettings: {
        'trust proxy': true,
      }
  },
});
```
