### ISSUE TITLE
Versioning support 

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#288]
There are a few concerns that we need to address to enable API versioning:

1. Define the strategy to allow client apps to express versioning requirement in the request:
    - As http headers for content negotiation
    - As part of client_id
    - As part of url, such as /api/v1/customers/ 

2. Have a step in the app sequence to introspect the versioning requirement and use it as a factor for controller/method resolution

3. Declare the versions for controller/method via decorators

4. Add version metadata as part of controller (or even service in general) bindings

**Comment by raymondfeng** [comment]
See https://github.com/lirantal/express-version-route

**Comment by dhmlau** [comment]
It could be a component, same way to create authentication component.

**Comment by bajtos** [comment]
I am closing this issue because we are not going to have time to work on this in the next 6-9 months. However, we are happy to accept a pull request contributing this feature.
