### ISSUE TITLE
authentication 2.0.0 error

### ISSUE THREAD

**Issue by sureshkodur** [strongloop/loopback-next#2887]
After installing @loopback/authentication2.0.0 , I'm getting below error,

Argument of type 'typeof StrategyResolverProvider' is not assignable to parameter of type 'Constructor<Provider<AuthenticationStrategy | undefined>>'.

Please help me.

**Comment by dhmlau** [comment]
@jannyHou @emonddr , could you PTAL? Thanks.

**Comment by emonddr** [comment]
@sureshkodur , can you please describe the steps you are taking that leads you to this error?
Are you creating a new application from scratch and using the authentication module, or updating an older application?

**Comment by emonddr** [comment]
@sureshkodur , also please see my comments in https://github.com/strongloop/loopback-next/issues/2886

**Comment by jannyHou** [comment]
+1 for Dom's comment in https://github.com/strongloop/loopback-next/issues/2887#issuecomment-492265703.

@sureshkodur the `@loopback/authentication@2.x` version contains breaking change, we are replacing the old passport adapter, which `@loobpack/authentication@1.x` is built on. 

If you are trying the shopping example and `StrategyResolverProvider` comes from this file:
https://github.com/strongloop/loopback4-example-shopping/blob/ee557f0dee0a9a5bd30e1f6b8f63b467d23162ca/packages/shopping/src/providers/strategy.resolver.provider.ts

It only works with 1.x, and we are working on the refactor https://github.com/strongloop/loopback4-example-shopping/pull/120 to adapter 2.x.

**Comment by jannyHou** [comment]
Since https://github.com/strongloop/loopback4-example-shopping/pull/120 is merged I am closing this story. 
Feel free to reopen it if you still get the error :)
