### ISSUE TITLE
Create a common layer for authentication & authorization component

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2900]
## Description / Steps to reproduce / Feature proposal
_Capturing the information from @raymondfeng in today's meeting and in Slack._

We might need a common layer e.g. `@loopback/security` to serve as a base where `@loopback/authentication` and `@loopback/authorization` are two extensions.  The common layer can possibly include:
- SecurityContext
- binding keys for current user/subject

_From the conversation in Slack:_
- Authentication binds the `subject` (who) to request context so that authorization can use it to make a decision against object + action (what)
- The subject contains a set of principals and other information from the access token (such as scopes)
- Today we build `UserProfile`, which is a subset of `subject`
- For example, facebook supports `user token`, `client app token`, `page token` etc
- The principal can a user, an application, or a device
- Maybe we should have a common module like `@loopback/security` to define the common interfaces/types

**Comment by dhmlau** [comment]
Draft PR #2902.
Recalling the conversation with @raymondfeng, he thinks after PR #1205 is done, we can see what makes sense to put in the common layer.

**Comment by jannyHou** [comment]
Closing as PR merged.
