### ISSUE TITLE
Updated model, but schema is not updating

### ISSUE THREAD

**Issue by ronaldlong46** [strongloop/loopback-next#2903]
## Description / Steps to reproduce / Feature proposal
When updating a model file, the schema in LoopBack API Explorer is not updating. 

## Current Behavior
Updated a property from:
`  @property({
    type: 'string',
    required: true,
  })
  maxAmount: string;`

To:
`  @property({
    type: 'string',
    required: true,
  })
  maxAmount: number;`

But the schema in LoopBack API Explorer remains the same. I have tried clearing out the '/dist' directory and rebuilding but the result remains the same.

## Expected Behavior
Updating model should update the schema.

## Versions:
Ubuntu 18.04
Node v8.16.0
  - @loopback/authentication: ^2.0.0
  - @loopback/boot: ^1.2.4
  - @loopback/build: ^1.5.1
  - @loopback/context: ^1.12.1
  - @loopback/core: ^1.6.1
  - @loopback/metadata: ^1.1.1
  - @loopback/openapi-spec-builder: ^1.1.7
  - @loopback/openapi-v3-types: ^1.0.15
  - @loopback/openapi-v3: ^1.3.8
  - @loopback/repository-json-schema: ^1.4.4
  - @loopback/repository: ^1.5.2
  - @loopback/rest: ^1.10.5
  - @loopback/testlab: ^1.2.6
  - @loopback/docs: ^1.16.1
  - @loopback/example-hello-world: ^1.1.14
  - @loopback/example-log-extension: ^1.1.14
  - @loopback/example-rpc-server: ^1.1.13
  - @loopback/example-todo: ^1.5.9
  - @loopback/example-soap-calculator: ^1.4.9
  - @loopback/service-proxy: ^1.1.7
  - @loopback/http-caching-proxy: ^1.0.16
  - @loopback/http-server: ^1.2.0
  - @loopback/example-todo-list: ^1.5.9
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^1.1.19
  - @loopback/tslint-config: ^2.0.4
  - @loopback/example-express-composition: ^1.2.9
  - @loopback/example-greeter-extension: ^1.2.1
  - @loopback/booter-lb3app: ^1.1.0

**Comment by dougal83** [comment]
Ah you spotted it. :)

**Comment by ronaldlong46** [comment]
@dougal83 I'm a little tired today. Not sure how I missed that. :)
