### ISSUE TITLE
Error 'Lb3AppBooter requires RestApplication with mountExpressRouter API'

### ISSUE THREAD

**Issue by f-w** [strongloop/loopback-next#2909]
## Description / Steps to reproduce / Feature proposal
Following docs [Boot and Mount a LoopBack 3 Application](https://loopback.io/doc/en/lb4/Boot-and-Mount-a-LoopBack-3-application.html), despite my app extends RestApplication, I still got the error in title. 

My application.ts looks like
```
...
import {Lb3AppBooterComponent} from '@loopback/booter-lb3app'
export class MyApplication extends BootMixin(
  ServiceMixin(RepositoryMixin(RestApplication)),
) {
...
    this.bootOptions = {
      controllers: {
        // Customize ControllerBooter Conventions here
        dirs: ['controllers'],
        extensions: ['.controller.js'],
        nested: true,
      },
      lb3app: {
        path: '../server/server',
      },
    }
    this.component(Lb3AppBooterComponent)
}
```

**Comment by raymondfeng** [comment]
Please run `npm ls @loopback/rest` to find out the version of `rest` module.

**Comment by f-w** [comment]
1.5.1

**Comment by raymondfeng** [comment]
Please run `npm up` to upgrade to latest versions.

**Comment by f-w** [comment]
upgraded to 1.11.2 and error is fixed.
