### ISSUE TITLE
How to reference HasMany when find all

### ISSUE THREAD

**Issue by kapookchang** [strongloop/loopback-next#2920]
## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@b-admike, could you PTAL? thanks.

**Comment by deepakrkris** [comment]
@kapookchang using filter conditions is well documented with https://loopback.io/doc/en/lb2/HasMany-relations.html and our examples https://github.com/strongloop/loopback-next/tree/master/examples , try testing the todo-list example for this question.
