### ISSUE TITLE
openapi import ref not setting up type in model file

### ISSUE THREAD

**Issue by deq9z** [strongloop/loopback-next#2930]
## Description / Steps to reproduce / Feature proposal
Given an OpenAPI 3.x formatted file, when using the loopback/@cli tool to import using the openapi syntax, then model files are generated for each individual definition component, however; their $ref is not used by the tool to setup an import and type (model class).  
## Current Behavior
As a result, the json schema is not properly generated and we need to force it by declaring it in the @property decorator (, jsonSchema: { ... }) 
## Expected Behavior
If the $ref is used to setup the import and type for the @property field, then the proper jsonSchema will be generated properly.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
@deq9z We need to emit more metadata into the generated files, including:

- `@api` at controller class
- `@operation` at controller method
- `@model` at model class
- `@property` at model property

Are you willing to contribute a patch?

**Comment by deq9z** [comment]
I can try to help, however; I'm not familiar with the loopback/@cli source code

**Comment by raymondfeng** [comment]
The related code is at https://github.com/strongloop/loopback-next/tree/master/packages/cli/generators/openapi

**Comment by gentunian** [comment]
@raymondfeng  this was closed due to inactivity... nobody uses openapi with loopback? I'm just using loopback to see if it's a fit for my project and trying to generate an API based on my openapi file is not possible.

Is this fully supported? 

Thanks
