### ISSUE TITLE
Reflect Metadata API wrapper

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#294]
- [ ] A wrapper class with all methods of Reflect metadata
- [ ] Should be able to access an instance of a context/container 
        `(this is dependent on a Context Factory implementation)`
- [ ] The class constructor should accept a container id 

```
  class Reflect {
      constructor(private containerId) { }
  }
```
- [ ] use the container id to configure and retrieve container specific metadata 
   `(this is dependent on a Metadata repository/storage within the context)` - This is still not useful from decorators, since decorators cannot pass in context ids

**Comment by raymondfeng** [comment]
The `reflect-metadata` module has a generic decorator as follows:
```js
  @Reflect.metadata(metadataKey, metadataValue)
```
For our wrapper, we can do:
```js
  @Reflect.metadata(ns, metadataKey, metadataValue)
```

**Comment by raymondfeng** [comment]
Based on my offline discussion with @deepakrkris, we think there are two cases:

1. Implementation of decorator functions that need to use `Reflect` APIs to add metadata to the target.

2. Services bound to the container that need to use `Reflect` APIs to retrieve metadata from the target.

Case 1 cannot access the scope for Reflect. As a consequence, I think we should start with a simple wrapper for reflect-metadata without considering the namespace for now.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/pull/297
