### ISSUE TITLE
loopback/context does not inject arguments to constructor of decorated class

### ISSUE THREAD

**Issue by checkmatez** [strongloop/loopback-next#2946]
## Description / Steps to reproduce / Feature proposal
loopback/context does not inject arguments to constructor of decorated class.
Repro: https://codesandbox.io/embed/loopbackcontext-bug-with-decorator-zdedp

## Current Behavior
Dependencies doesn't not get injected.

## Expected Behavior
Dependencies get injected.

This was introduced with https://github.com/strongloop/loopback-next/commit/8c0bdb6b5385fe683e8c6599336c4772cb76a592#diff-c1d762637c20a39c3e01ff4c7d440f03R307
Relevant issue: https://github.com/strongloop/loopback-next/issues/1565

This prevents using class properties in custom decorators, since Typescript moves them to implicit constructor, so class.toString() will contain constructor and will match against regular expression. Also this is really hacky way :)

Not sure what the fix would be...

**Comment by dhmlau** [comment]
@raymondfeng, could you please help? Thanks.

**Comment by raymondfeng** [comment]
@checkmatez Interesting. I'll investigate.

**Comment by dhmlau** [comment]
@checkmatez @raymondfeng , with the PR https://github.com/strongloop/loopback-next/pull/2954 landed, is this issue good to close?

**Comment by checkmatez** [comment]
Looks good, thanks.
