### ISSUE TITLE
[Model discovery] Need to force to exit when running `lb4 discover` command

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2952]
## Description / Steps to reproduce / Feature proposal
When running `lb4 discover` as below, the prompt never returns, and I need to press Ctrl+C to exit.  The models are being created properly, but I need to kill the process in order to get the prompt back. 

```sh
   $ lb4 discover --schema testdb
   ? Select the connector to discover ds
   ? Select the models which to discover address, customer
     create src/models/address.model.ts
     create src/models/customer.model.ts
     update src/models/index.ts
     update src/models/index.ts

   Discover address.model.ts,customer.model.ts was created in src/models/
   ```
# Acceptance Criteria
- [ ] Make sure to close all open datasource connections i.e. call `datasource.disconnect()`
- [ ] Create/Update test(s) accordingly (try to capture/reproduce bug in tests)
- [ ] Test against real live database (pick one SQL and NoSQL like MySQL/Mongo)

I'm using MySQL as the datasource, not sure if it matters.

**Comment by dhmlau** [comment]
cc @marvinirwin

**Comment by bajtos** [comment]
I suspect the connector is keeping a pool of connections opened and these connections are blocking Node.js from exiting. 

I think we should improve `packages/cli/generators/discover/index.js` to call `await this.artifactInfo.dataSource.disconnect()` after we have fetched all data from the database.
