### ISSUE TITLE
How to validate field in functional way ?

### ISSUE THREAD

**Issue by vjtc0n** [strongloop/loopback-next#2968]
## Description / Steps to reproduce / Feature proposal
Currently, I read the docs about validation: 
- https://loopback.io/doc/en/lb4/Parsing-requests.html

But in some cases, when we need to implement a function to validate a field (requestBody or property in Entity), so How can we do this?

I really need an example how to do this just like ajv docs.

**Comment by raymondfeng** [comment]
Have you checked out https://loopback.io/doc/en/lb4/Interceptors.html?

**Comment by vjtc0n** [comment]
@raymondfeng thanks for your support!
Basically, we can write a small function to validate the params in the controller.
But I'm afraid if we implement that way, it would break the app's structure.

I will try your solution.

**Comment by dhmlau** [comment]
Closing as resolved. @vjtc0n, please open a new issue if you run into other problems. Thanks.
