### ISSUE TITLE
@loopback/example-lb3-application with Fireloop

### ISSUE THREAD

**Issue by kimoudev** [strongloop/loopback-next#2970]
I want to convert my old LB3 project to LB4 by following this link.
https://github.com/strongloop/loopback-next/tree/master/examples/lb3-application
Since my frontEnd is angular, I always use the @mean-expert/model library.
After several hacking I still can't start my LB3 server.
here is one of the errors
Cannot start the application. Error: Model "myModel" uses unknown mixin: FireLoop at MixinProvider.applyMixin
Thank you

**Comment by dhmlau** [comment]
@nabdelgadir, could you please take a look? Thanks.

**Comment by nabdelgadir** [comment]
I'm not too familiar with Fireloop, maybe @raymondfeng could chime in?

Can you please provide a small application we can use to debug the problem? (See http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report)

**Comment by raymondfeng** [comment]
Did you install the FireLoop module?

**Comment by raymondfeng** [comment]
See https://github.com/mean-expert-official/loopback-component-realtime

**Comment by dhmlau** [comment]
@kimoudev , did @raymondfeng's comment answer your question?

**Comment by kimoudev** [comment]
@raymondfeng  Yes my application works perfectly in production but does not support the realtime fireloop plugin with LB4 for migration LB3 to LB4 shown on this [link](https://github.com/strongloop/loopback-next/tree/master/examples/lb3-application)
