### ISSUE TITLE
Add hasOne relation type to `lb4 relation`

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2980]
## Description / Steps to reproduce / Feature proposal
Trying out the `lb4 relation` command from the master branch and realized that there are only 2 model relation types available for selection: `belongsTo` and `hasMany`.  

We should add the `hasOne` relation type as one of the options as well. 

### Acceptance Criteria
- [ ] when running `lb4 relation` command, there should be 3 options for relation types: `belongsTo`, `hasMany` and `hasOne` (should be added in this work item) ( should implement the "inclusion resolver" prompt too)
- [ ] add related cli tests

**Comment by dhmlau** [comment]
@lakinmohapatra, this is the same issue you've reported. Would you like to submit a PR? Thanks.

**Comment by lokesh1197** [comment]
@dhmlau I would like to work on this. Can you assign this to me?

**Comment by dhmlau** [comment]
@lokesh1197, of course!

**Comment by dhmlau** [comment]
@lokesh1197, are you still interested in working on a PR for this? _I think_ I haven't seen a related PR. Thanks.

**Comment by lokesh1197** [comment]
@dhmlau I was working on it. But I got busy in another project so I had to stop. Currently the tests part is remaining. I will try to finish it within this week.

**Comment by dhmlau** [comment]
cool thanks!

**Comment by dhmlau** [comment]
PR https://github.com/strongloop/loopback-next/pull/4171
