### ISSUE TITLE
Documentation Request: ACL/Authorization with Loopback 4

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [strongloop/loopback-next#2991]
Looking for Authorization support offered by Loopback 4, I could see few examples on LoopBack 2 and 3, could not find example/documentation for LoopBack 4.

**Comment by dhmlau** [comment]
@gopalakrishnan-subramani , there's documentation on creating a component for authorization: https://loopback.io/doc/en/lb4/Loopback-component-authorization.html.  @raymondfeng is working on the authorization infrastructure using interceptor, see PR in progress: https://github.com/strongloop/loopback-next/pull/1205.

**Comment by gopalakrishnan-subramani** [comment]
All seems working fine, thank you @dhmlau , Application.ts file should have 

this.component(AuthorizationComponent) 

The documentation refers to this.component(AuthenticationComponent);
