### ISSUE TITLE
loopback4-example-express-composition - Filter<Note> | undefined

### ISSUE THREAD

**Issue by techskyey** [strongloop/loopback-next#2997]
## Follow the steps from https://loopback.io/doc/en/lb4/express-with-lb4-rest-tutorial.html
The try out part:
After run: `npm start`

## Terminal log
```13:05 $ npm start

> @loopback/example-express-composition@1.3.1 prestart /Users/*****/Desktop/loopback4-example-express-composition
> npm run build


> @loopback/example-express-composition@1.3.1 build /Users/*****/Desktop/loopback4-example-express-composition
> lb-tsc es2017 --outDir dist

src/controllers/note.controller.ts:74:43 - error TS2345: Argument of type 'Filter<AnyObject> | undefined' is not assignable to parameter of type 'Filter<Note> | undefined'.
  Type 'Filter<AnyObject>' is not assignable to type 'Filter<Note>'.
    Type 'AnyObject' is missing the following properties from type 'Note': title, getId, getIdObject, toJSON, toObject

74     return await this.noteRepository.find(filter);
                                             ~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @loopback/example-express-composition@1.3.1 build: `lb-tsc es2017 --outDir dist`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @loopback/example-express-composition@1.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/*****/.npm/_logs/2019-05-30T17_05_10_984Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @loopback/example-express-composition@1.3.1 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @loopback/example-express-composition@1.3.1 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/*****/.npm/_logs/2019-05-30T17_05_11_091Z-debug.log```

## Verbose log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.11.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.7.0
3 info using node@v11.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @loopback/example-express-composition@1.3.1~prestart: @loopback/example-express-composition@1.3.1
6 verbose lifecycle @loopback/example-express-composition@1.3.1~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle @loopback/example-express-composition@1.3.1~prestart: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/*****/Desktop/loopback4-example-express-composition/node_modules/.bin:/Users/*****/.fastlane/bin:/Users/*****/Library/Android/sdk/platform-tools:/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/bin:/usr/local/opt/gradle/libexec/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle @loopback/example-express-composition@1.3.1~prestart: CWD: /Users/*****/Desktop/loopback4-example-express-composition
9 silly lifecycle @loopback/example-express-composition@1.3.1~prestart: Args: [ '-c', 'npm run build' ]
10 silly lifecycle @loopback/example-express-composition@1.3.1~prestart: Returned: code: 2  signal: null
11 info lifecycle @loopback/example-express-composition@1.3.1~prestart: Failed to exec prestart script
12 verbose stack Error: @loopback/example-express-composition@1.3.1 prestart: `npm run build`
12 verbose stack Exit status 2
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
12 verbose stack     at EventEmitter.emit (events.js:197:13)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:197:13)
12 verbose stack     at maybeClose (internal/child_process.js:984:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
13 verbose pkgid @loopback/example-express-composition@1.3.1
14 verbose cwd /Users/*****/Desktop/loopback4-example-express-composition
15 verbose Darwin 18.5.0
16 verbose argv "/usr/local/Cellar/node/11.11.0/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v11.11.0
18 verbose npm  v6.7.0
19 error code ELIFECYCLE
20 error errno 2
21 error @loopback/example-express-composition@1.3.1 prestart: `npm run build`
21 error Exit status 2
22 error Failed at the @loopback/example-express-composition@1.3.1 prestart script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 2, true ]
```

**Comment by bgleolalahi** [comment]
#2986

**Comment by bgleolalahi** [comment]
please check "typescript": "^3.4.3" to be `"typescript": "~3.4.3" as mentioned on https://github.com/strongloop/loopback-next/issues/2986#issuecomment-497397362

**Comment by techskyey** [comment]
@bgleolalahi Thanks for your tip.

Here is how I fixed it:
1. Delete `package-lock.json`
2. In package.json file, change `"typescript": "^3.4.3"` to `"typescript": "~3.4.3"`
3. Run command `npm install`
4. Run command `npm build` then run `npm start`
