### ISSUE TITLE
Drop our openapi-spec packages, use openapi3-ts instead

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#301]
https://github.com/metadevpro/openapi3-ts looks more feature complete than our own openapi packages. Should we use openapi3-ts instead?

If we want to support both Swagger v2 and OpenAPI v3 then we probably cannot drop our packages, unless there is a replacement available.

UPDATE:

Looks like we have already dropped most of our custom type definitions. As of today ([0411811aa](https://github.com/strongloop/loopback-next/tree/0411811aa8348e31636fb0fe07b44dd18469280f/packages/openapi-v3-types/src)), openapi-v3-spec-types provides only few helpers:
 - `OpenApiSpec` as an alias for `OpenAPIObject`
 - `createEmptyApiSpec()`
 - `isSchemaObject()` and `isReferenceObject()` (type guards)

## Acceptance criteria

- [x] contribute type guards to `openapi3-ts` - see https://github.com/metadevpro/openapi3-ts/pull/46 and https://github.com/strongloop/loopback-next/pull/2974
- ~~try to upstream `createEmptyApiSpec`, e.g. to [src/dsl/OpenApiBuilder.ts](https://github.com/metadevpro/openapi3-ts/blob/ab997f12a63fa215e3b0c08cc293429b97ce0a44/src/dsl/OpenApiBuilder.ts)~~
- [x] move the rest to our `openapi-v3` package ~~(`createEmptyApiSpec` should go to `openapi--spec-builder` package)~~ - see https://github.com/strongloop/loopback-next/pull/3220
- [ ] and finally remove `openapi-v3-types` - see https://github.com/strongloop/loopback-next/pull/3385

**Comment by bajtos** [comment]
Related: #182.

**Comment by dhmlau** [comment]
@jannyHou , with your openapiv3 work, is this ticket still valid?

**Comment by bajtos** [comment]
From what I remember, our OpenAPI v3 packages are using a 3rd party dependency under the hood, but adding some extra features/types on top of that dependency. I would personally like more if we could contribute our improvements to that 3rd party package and start using it directly. IIRC, @jannyHou had good arguments against that, could you @jannyHou  please re-post them here please?

**Comment by virkt25** [comment]
@jannyHou any updates for this?

**Comment by jannyHou** [comment]
@bajtos @virkt25 Nice to know we already have an issue to continue the discussion. Copy paste from my V3 prototype PR:

---

From @bajtos 
It seems to me we are duplicating a lot of types from openapi3-ts package. I consider it as unnecessary work and extra maintenance cost for the future. Can we keep the number of custom types as small as possible, and contribute any missing features/types to openapi3-ts to have even less code to maintain ourselves?
Ideally, we should be able to leverage openapi3-ts as-is and remove our openapi-v3-types package entirely. I understand that contributing changes to upstream dependencies take time, so I am ok with the current proposal as a quick solution for MVP.

---

From @jannyhou

Interesting..by relying on the community module, I have two concerns:
- For anything not consistent with OpenAPI spec, keep patching a community module VS overriding them in our own package, which one is more convenient for us?
This is not a doubt for the maintainer of `openapi3-ts`, he replies very quickly actually, he merged my patch in a few minutes after created, but as a long term solution, we import the benefit but also the potential risk.

- People may take different approaches to describe a property, like `ParameterLocation`:

```js
  export type ParameterLocation = 'query' | 'header' | 'path' | 'cookie';
  export interface ParameterObject extends ISpecificationExtension {
    name: string;
    // `openapi3-ts` define it as string by `in: string`
    in: ParameterLocation;
    // ...other properties
  }
```

Essentially `ParameterLocation` is just a `string`, we use a union type to describe it like an enum, but I don't see any problem if people loose the restriction and just treat it as a `string` in their project. Patching the community module will break other projects using it without caring about the restriction.

So as a compromised solution, what I did is:

> Override important spec types by ourselves, export spec interfaces from the community module if missing in our package

---

And I got some feedback from @raymondfeng 

If the module is in a good shape and the maintainer is collaborative, +1 to use it. We can folk it any time if things won't work out any more.

**Comment by bajtos** [comment]
> People may take different approaches to describe a property, like ParameterLocation:

```ts
  export type ParameterLocation = 'query' | 'header' | 'path' | 'cookie';
  export interface ParameterObject extends ISpecificationExtension {
    name: string;
    // `openapi3-ts` define it as string by `in: string`
    in: ParameterLocation;
    // ...other properties
  }
```

> Essentially ParameterLocation is just a string, we use a union type to describe it like an enum, but I don't see any problem if people loose the restriction and just treat it as a string in their project. Patching the community module will break other projects using it without caring about the restriction.

My opinion: if the OpenAPI spec mandates a well-defined list of valid `in` values, then the type definition should reflect that and use `ParameterLocation` type instead of a generic `string`. I hope we can convince maintainers of `openapi3-ts` to follow this thinking and make the type definitions more accurate.

**Comment by bajtos** [comment]
BTW, looks like we have already dropped most of our custom type definitions. As of today ([0411811aa](https://github.com/strongloop/loopback-next/tree/0411811aa8348e31636fb0fe07b44dd18469280f/packages/openapi-v3-types/src)), openapi-v3-spec-types provides only few helpers:
 - `OpenApiSpec` as an alias for `OpenAPIObject`
 - `createEmptyApiSpec()`
 - `isSchemaObject()` and `isReferenceObject()` (type guards)

I am proposing to:
 - contribute type guards to `openapi3-ts`
 - try to upstream `createEmptyApiSpec`
 - then move the rest to our `openapi-v3` package
 - and finally remove `openapi-v3-types`

**Comment by dhmlau** [comment]
@jannyHou , looks like we're done with this task?  Is it good to close? Thanks.

**Comment by virkt25** [comment]
It's not ... this package still exists https://github.com/strongloop/loopback-next/tree/master/packages/openapi-v3-types and `createEmptyApiSpec` hasn't been upstreamed AFAIK.

**Comment by bajtos** [comment]
Let me copy the items from https://github.com/strongloop/loopback-next/issues/301#issuecomment-390247980 into acceptance criteria of this story.

**Comment by jannyHou** [comment]
@dhmlau +1 for Taranveer's comment it's not done yet. And +1 for Miroslav's acceptance criteria 👍

**Comment by bajtos** [comment]
We agreed with @dhmlau and @raymondfeng to create follow-up narrowly-focused stories for the features that are missing and close this story once they are created. I'll create the stories next week, I am thinking about:
 - Unified error handler for both REST APIs and static content.
 - Performance - REST router must be invoked before static content handler(s). This will allow  - static content to be mounted on `/`.
