### ISSUE TITLE
Error controller on npm start

### ISSUE THREAD

**Issue by pookdeveloper** [strongloop/loopback-next#3023]
## Description / Steps to reproduce / Feature proposal
Generate a new project,  then create a:
- usuarios model 
- datasource
- usuarios repository  
- usuarios controller.

And I get this error:
![image](https://user-images.githubusercontent.com/3384734/58729650-45e91580-83ea-11e9-9b0a-1e33bb24fe6e.png)

What's the problem?

Thanks

**Comment by raymondfeng** [comment]
This is caused by a breaking change in TypeScript@3.5.1. Please update your package.json to use `"typescript": "~3.4.5"`.
