### ISSUE TITLE
Debug mode like in Loopback3 (DEBUG=loopback:datasource node .)

### ISSUE THREAD

**Issue by pookdeveloper** [strongloop/loopback-next#3027]
## Description / Steps to reproduce / Feature proposal
The are any command to show what sql are executed?

Like in LB3:
DEBUG=loopback:datasource node .

**Comment by raymondfeng** [comment]
Juggler is the same as lb3.

**Comment by pookdeveloper** [comment]
If i use this command I do not see the sql: 
DEBUG=loopback:datasource node .

**Comment by raymondfeng** [comment]
try `loopback:connector:*`

**Comment by dhmlau** [comment]
@pookdeveloper, is this issue good to close? Thanks.

**Comment by pookdeveloper** [comment]
Hello @dhmlau @raymondfeng i try:
````
set DEBUG=loopback:connector:* 
npm start
````

or 

````
set DEBUG=loopback:connector:* 
node . 
````
and not work.

**Comment by pookdeveloper** [comment]
I try this
````
set DEBUG=loopback:connector: 'my-connector-name' `
````
but the same, it dosen't work

Any solution ?  Thanks

**Comment by dhmlau** [comment]
@pookdeveloper, sorry that I don't have access to a Windows machine for now.  On mac, that's what I did, and I think it should be the same for Windows. Could you please try it out?
```
DEBUG=loopback:connector:* npm start
```

**Comment by dhmlau** [comment]
Then I got something like:
```
Server is running at http://[::1]:3000
Try http://[::1]:3000/ping
  loopback:connector:postgresql Settings {"name":"ds","connector":"postgresql","url":"","host":"localhost","port":5432,"user":"xxx","password":"xxx","database":"testdb","debug":false} +0ms
  loopback:connector:postgresql SQL: SELECT "id","name" FROM "public"."dianatest" ORDER BY "id" +22ms
  loopback:connector:postgresql:data {"command":"SELECT","rowCount":0,"oid":null,"rows":[],"fields":[{"name":"id","tableID":24577,"columnID":1,"dataTypeID":25,"dataTypeSize":-1,"dataTypeModifier":-1,"format":"text"},{"name":"name","tableID":24577,"columnID":2,"dataTypeID":25,"dataTypeSize":-1,"dataTypeModifier":-1,"format":"text"}],"_parsers":[null,null],"_types":{"_types":{"arrayParser":{}},"text":{},"binary":{}},"RowCtor":null,"rowAsArray":false} +0ms
```

**Comment by pookdeveloper** [comment]
Thanks it works using: 
````
DEBUG=loopback:connector:* npm start
````
![image](https://user-images.githubusercontent.com/3384734/58971551-ff196800-87bb-11e9-99ed-f2e4e95129d2.png)

I using now a mac

**Comment by pookdeveloper** [comment]
I have another question.. If a

**Comment by pernsdorff** [comment]
When you are using Windows and VSCode, you are using PowerShell so you need follow PS commands for environment vars  https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7
