### ISSUE TITLE
How to call Loopback4 controller's method from another controller?

### ISSUE THREAD

**Issue by dinsvale** [strongloop/loopback-next#3028]
## Description / Steps to reproduce / Feature proposal
I have a loopback 4 controller with a function that I don't want to expose via HTTP.
I would like to be able to call the function from another controller. How can I do this? Is there any way of injecting a controller in another controller? (I 'm able to inject repositories in controllers, but not controllers in controllers)
## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
You should be able to inject another controller. Pls show your code.

**Comment by raymondfeng** [comment]
Check out similar examples at https://github.com/strongloop/loopback-next/tree/master/examples/context

**Comment by raymondfeng** [comment]
It should be as simple as `@inject(‘controllers.AnotherController’) c: AnotherController`

**Comment by dinsvale** [comment]
Alright, so to inject a repository in a controller, I do this, in the constructor of the controller:
`  constructor(
    @repository(RepositoryIWantToInject)
    public repositoryIWantToInject: RepositoryIWantToInject,
  ) {}`

I tried @controller but it didn't work. But what you posted just now seems to have worked! Thanks!

**Comment by raymondfeng** [comment]
Simply use `@inject`
