### ISSUE TITLE
loopback/authentication this.fail is not a function

### ISSUE THREAD

**Issue by vikramkh** [strongloop/loopback-next#3032]
After following the setup for loopback/authentication, and adding the decorator: @authentication('BasicStrategy') to my users controller, I get the error: 
Unhandled error in GET /users/count: 500 TypeError: this.fail is not a function
    at BasicStrategy.authenticate (/Users/myName/folder/node_modules/passport-http/lib/passport-http/strategies/basic.js:69:17)
    at AuthenticateActionProvider.action (/Users/myName/folder/node_modules/@loopback/authentication/dist/providers/auth-action.provider.js:55:44)

Error: 500
Internal Server Error
Unhandled error in GET /users/count: 500 TypeError: this.fail is not a function
    at BasicStrategy.authenticate

## Expected Behavior
Error: 400
Authentication Required

**Comment by dhmlau** [comment]
@jannyHou @emonddr, could you PTAL? thanks.

**Comment by emonddr** [comment]
@vikramkh 

Apologies for the broken example, we are in the midst of landing different PRs which
are updating @loopback/authentication  .

[feat: resolve authentication strategy registered via extension point](https://github.com/strongloop/loopback-next/pull/2763) landed in early May and it was a breaking change; bumping @loopback/authentication to `2.0.3`.

[Draft:Changes to passport strategy adapter ](https://github.com/strongloop/loopback-next/pull/2822) will be updating how passport strategies are handled given the new authentication strategy interface. We are exploring a few options right now. Once things have been decided, the documentation you mention will be updated. 

[refactor shopping cart example to utilize latest @loopback/authentication module](https://github.com/strongloop/loopback4-example-shopping/pull/120) also landed and uses
the latest @loopback/authentication 2.0.3.

We are also in the midst of making documentation changes :  `update @loopback\authentication documentation` (https://github.com/strongloop/loopback-next/issues/2940).

You probably were following either of these two documents which are out of date:

https://loopback.io/doc/en/lb4/Decorators_authenticate.html 

https://github.com/strongloop/loopback-next/tree/master/packages/authentication 



So please stay tuned...

:)

**Comment by jannyHou** [comment]
@vikramkh I think you are using a passport based strategy which is not supported yet in `@loopback/authentication@2.x`, we are working on the new adapter for the passport strategies in https://github.com/strongloop/loopback-next/pull/2969, I will let you know when it's ready for use.

**Comment by jannyHou** [comment]
Just talked to @emonddr and seems this is the same issue reported in https://github.com/strongloop/loopback-next/issues/2886, @vikramkh I am closing this story as a duplicate, and let's continue the discussion in the earlier issue https://github.com/strongloop/loopback-next/issues/2886.

Feel free to reopen this issue if you have other concerns :)
