### ISSUE TITLE
Loopback4 Bearer_Token authentication

### ISSUE THREAD

**Issue by sherif2011** [strongloop/loopback-next#3038]
Description / Steps to reproduce / Feature proposal

I tried following the example mentioned in https://www.npmjs.com/package/loopback4-authentication to get http-bearer configured.

Here is my simple project on Github:  https://github.com/sherif2011/lb4_token

Current Behavior
When I run and try accessing localhost:3000, I get "500 JsonWebTokenError: jwt must be a string"

Expected Behavior
Expected to be able to access explorer and when I try to ping, would get an error: Unauthorized

Thank you!
Sherif

**Comment by sherif2011** [comment]
Any update regarding this? I am just following the example, am I missing something? Thanks!

**Comment by dhmlau** [comment]
@emonddr, could you PTAL? thanks.

**Comment by samarpanB** [comment]
@sherif2011 this package is a community developed extension, not part of loopback-next core. Feel free to raise this issue on gihub there - https://github.com/sourcefuse/loopback4-authentication. We'll be happy to help with any issues there.

**Comment by dhmlau** [comment]
Thanks @samarpanB.  I'll close this issue since the issue raised is not part of loopback-next repo.

**Comment by sherif2011** [comment]
Ok, thank you!
