### ISSUE TITLE
typescript@3.5.1 not compatible to some of the packages

### ISSUE THREAD

**Issue by gordancso** [strongloop/loopback-next#3053]
## Description / Steps to reproduce / Feature proposal
Updated a current working project with `npm up`. `typescript@3.5.1` is breaking some of the packages (e.g. `Filter`/`Where` definition.).

## Current Behavior
Error is prompted at `npm run start`. (masked some of the sensitive information)
```
src/repositories/customer.repository.ts:85:49 - error TS2345: Argument of type 'Filter<AnyObject>' is not assignable to parameter of type 'Filter<Customer>'.
  Type 'AnyObject' is missing the following properties from type 'Customer': ...
``` 
```
src/repositories/customer.repository.ts:885:49 - error TS2345: Argument of type 'Where<AnyObject>' is not assignable to parameter of type 'Condition<Customer> | AndClause<Customer> | OrClause<Customer> | undefined'
...
``` 
Need to downgrade to `typescript@3.4.5` in order to continue development..

## Expected Behavior
Should not impose type error using `WhereBuilder()` and `FilterBuilder()` methods.

**Comment by bgleolalahi** [comment]
@gordancso Just modify your type param from `... filter?: Filter` to `... filter?: Filter<Customer>` and `...where?: Where` to `where?: Where<Customer>` and you can continue your development with `typescript@3.5.1`.
Don't forget to rebuild and update the @loopback/cli to latest version as well.

**Comment by bajtos** [comment]
Exactly as @bgleolalahi wrote. See https://github.com/strongloop/loopback-next/pull/3031 where we applied the same fix ourselves.

I am sorry for the inconvenience, unfortunately there is very little we can do about TypeScript introducing breaking changes in semver-minor releases :(

**Comment by gordancso** [comment]
What I am currently doing is using `WhereBuilder` and `FilterBuilder` method. 
```ts
const filterBuilder = new FilterBuilder();
const filter = filterBuilder
  .fields('id', a', 'b')
  .limit(10)
  .offset(0)
  .order(['a ASC', 'b DESC'])
  .where({id: 1})
  .build();
return this.exampleRepo.find(filter);
```
The `filter` inside `DefaultCrudRepository` method `find` was underlined with below prompt.
```
const filter: Filter<AnyObject>
Argument of type 'Filter<AnyObject>' is not assignable to parameter of type 'Filter<Entity>'.ts(2345)
```
May I know how exactly I can do to resolve the type error here?
