### ISSUE TITLE
Help required to debug the issue!

### ISSUE THREAD

**Issue by Nayak11** [strongloop/loopback-next#3060]
I am trying to reproduce soap-calculator application(https://loopback.io/doc/en/lb4/soap-calculator-tutorial.html)

When I run - http://localhost:3000/add/50/50 I am getting below error!

```
{"error":{"statusCode":400,"name":"BadRequestError","message":"Required parameter arg2 is missing!","code":"MISSING_REQUIRED_PARAMETER"}}MREM74E8E44C:soap-calculator 
```

Below is the expected output:

```
{"result":{"value":100},"envelope":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ns1=\"http://wsdl.example.org/\"><SOAP-ENV:Body><ns1:AddResponse><AddResult>100</AddResult></ns1:AddResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

**Comment by Nayak11** [comment]
@raymondfeng Can you please guide me.

**Comment by bajtos** [comment]
@Nayak11 Thank you for reporting the issue. Please provide us with steps how to reproduce the problem, see https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs

**Comment by Nayak11** [comment]
@bajtos Steps mentioned in https://loopback.io/doc/en/lb4/soap-calculator-tutorial.html are the exact steps to reproduce.

**Comment by Nayak11** [comment]
### calculator.datasource.json
`{
  "name": "calculator",
  "connector": "soap",
  "url": "https://calculator-webservice.mybluemix.net/calculator",
  "wsdl": "https://calculator-webservice.mybluemix.net/calculator?wsdl",
  "remotingEnabled": true,
  
  "operations": {

    "multiply": {
     "service": "CalculatorService",
     "port": "CalculatorPort",
     "operation": "Multiply"
   },

   "add": {
     "service": "CalculatorService",
     "port": "CalculatorPort",
     "operation": "Add"
   },

   "subtract": {
     "service": "CalculatorService",
     "port": "CalculatorPort",
     "operation": "Subtract"
   },

   "divide": {
     "service": "CalculatorService",
     "port": "CalculatorPort",
     "operation": "Divide"
   }
   
 }
}`






### calculator.service.ts
`import {getService} from '@loopback/service-proxy';
import {inject, Provider} from '@loopback/core';
import {CalculatorDataSource} from '../datasources';

export interface CalculatorService {
  Multiply(args: CalculatorParameters): Promise<MultiplyResponse>;
  Add(args: CalculatorParameters): Promise<AddResponse>;
  Divide(args: CalculatorParameters): Promise<DivideResponse>;
  Subtract(args: CalculatorParameters): Promise<SubtractResponse>;
}

export class CalculatorServiceProvider implements Provider<CalculatorService> {
  constructor(
    // calculator must match the name property in the datasource json file
    @inject('datasources.calculator')
    protected dataSource: CalculatorDataSource = new CalculatorDataSource(),
  ) {}

  value(): Promise<CalculatorService> {
    return getService(this.dataSource);
  }
}

export interface MultiplyResponse {
  result: {
    value: number;
  };
}
export interface AddResponse {
  result: {
    value: number;
  };
}
export interface SubtractResponse {
  result: {
    value: number;
  };
}
export interface DivideResponse {
  result: {
    value: number;
  };
}
export interface CalculatorParameters {
  intA: number;
  intB: number;
}
`






### calculator.controller.ts
`import {inject} from '@loopback/core';
import {get, param, HttpErrors} from '@loopback/rest';
import {
  CalculatorService,
  CalculatorParameters,
  AddResponse,
  MultiplyResponse,
  DivideResponse,
  SubtractResponse,
} from '../services/calculator.service';

export class CalculatorController {
  constructor(
    @inject('services.CalculatorService')
    protected calculatorService: CalculatorService,
  ) {}

  @get('/multiply/{intA}/{intB}')
  async multiply(
    @param.path.integer('intB') intA: number,
    @param.path.integer('arg2') intB: number,
  ): Promise<MultiplyResponse> {
    return await this.calculatorService.Multiply(<CalculatorParameters>{
      intA,
      intB,
    });
  }

  @get('/add/{intA}/{intB}')
  async add(
    @param.path.integer('intB') intA: number,
    @param.path.integer('arg2') intB: number,
  ): Promise<AddResponse> {
    console.log("Here in add");
    return await this.calculatorService.Add(<CalculatorParameters>{
      intA,
      intB,
    });
  }

  @get('/subtract/{intA}/{intB}')
  async subtract(
    @param.path.integer('intB') intA: number,
    @param.path.integer('arg2') intB: number,
  ): Promise<SubtractResponse> {
    return await this.calculatorService.Subtract(<CalculatorParameters>{
      intA,
      intB,
    });
  }


  @get('/divide/{intA}/{intB}')
  async divide(
    @param.path.integer('intB') intA: number,
    @param.path.integer('arg2') intB: number,
  ): Promise<DivideResponse> {
    //Preconditions
    if (intB === 0) {
      throw new HttpErrors.PreconditionFailed('Cannot divide by zero');
    }
    return await this.calculatorService.Divide(<CalculatorParameters>{
      intA,
      intB,
    });
  }
}
`




### Below is the error that i am getting
![Screen Shot 2019-06-07 at 12 31 22 AM](https://user-images.githubusercontent.com/36310654/59120679-e370a780-890a-11e9-9e41-2a75ac0cb4b7.png)

**Comment by dougal83** [comment]
The code example is not correct, "arg2" is erroneous. Try ``calculator.controller.ts`` as the following:

````ts
import {inject} from '@loopback/core';
import {get, param, HttpErrors} from '@loopback/rest';

import {
  CalculatorService,
  CalculatorParameters,
  AddResponse,
  MultiplyResponse,
  DivideResponse,
  SubtractResponse,
} from '../services/calculator.service';

export class CalculatorController {
  constructor(
    @inject('services.CalculatorService')
    protected calculatorService: CalculatorService,
  ) {}

  @get('/multiply/{intA}/{intB}')
  async multiply(
    @param.path.integer('intA') intA: number,
    @param.path.integer('intB') intB: number,
  ): Promise<MultiplyResponse> {
    return await this.calculatorService.multiply(<CalculatorParameters>{
      intA,
      intB,
    });
  }
  @get('/add/{intA}/{intB}')
  async add(
    @param.path.integer('intA') intA: number,
    @param.path.integer('intB') intB: number,
  ): Promise<AddResponse> {
    return await this.calculatorService.add(<CalculatorParameters>{
      intA,
      intB,
    });
  }

  @get('/subtract/{intA}/{intB}')
  async subtract(
    @param.path.integer('intA') intA: number,
    @param.path.integer('intB') intB: number,
  ): Promise<SubtractResponse> {
    return await this.calculatorService.subtract(<CalculatorParameters>{
      intA,
      intB,
    });
  }

  @get('/divide/{intA}/{intB}')
  async divide(
    @param.path.integer('intA') intA: number,
    @param.path.integer('intB') intB: number,
  ): Promise<DivideResponse> {
    //Preconditions
    if (intB === 0) {
      throw new HttpErrors.PreconditionFailed('Cannot divide by zero');
    }
    return await this.calculatorService.divide(<CalculatorParameters>{
      intA,
      intB,
    });
  }
}
````
