### ISSUE TITLE
Acceptance test for Authentication to use OAuth/JWT tokens

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#307]
- [ ] Write acceptance test to use Authentication package
- [ ] Create mock JWT/OAuth token generator http endpoint / service
- [ ] Use Passport-OAuth-Strategy or JWT Strategy to authenticate user with a token

**Comment by deepakrkris** [comment]
cc @ritch @bajtos @raymondfeng

**Comment by dhmlau** [comment]
Depending on the strategy refactor that relates to @bajtos' gRPC work.

**Comment by bajtos** [comment]
> Depending on the strategy refactor that relates to @bajtos' gRPC work. relate to: #521

@dhmlau I think you misunderstood the goal of this story. As far as I understand, this is related to the authentication package for REST API, not to gRPC.

**Comment by dhmlau** [comment]
OK.  I think @kjdelisle and @raymondfeng can chime in.  The comment was added probably when we three were going through the LBNext items for GA/non-GA category.

**Comment by dhmlau** [comment]
Closing as it is no longer relevavnt.
