### ISSUE TITLE
loopback postgresql connector neq with null check issue

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [strongloop/loopback-next#3073]
We have an critical issue, we could not filter not null values neq using postgresql with loopback find methods. 

This is show stopper for our entire application, we need soft delete features based on timestamp data. 
{ deleted_at: {neq: null} }

Any workaround possible without hitting DB performance? or if you could show a possible place to fix the bug, we will fix and contribute back with pull request.

**Comment by bajtos** [comment]
Hi @gopalakrishnan-subramani, thank you for reporting the issue. Please create a small application reproducing the issue, see https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs.

I suspect the problem may be in the connector, here is the relevant code:
- [SQLConnector.prototype.buildSelect](https://github.com/strongloop/loopback-connector/blob/417d6467b04c3fe4ad5d50374fb4acaab27f11b8/lib/sql.js#L1372-L1401)
- [PostgreSQL.prototype.escapeValue](https://github.com/strongloop/loopback-connector-postgresql/blob/42bf97f5a3008b54b85beda8342a53f01758257c/lib/postgresql.js#L371-L383)
- [PostgreSQL.prototype._buildWhere](https://github.com/strongloop/loopback-connector-postgresql/blob/42bf97f5a3008b54b85beda8342a53f01758257c/lib/postgresql.js#L552-L592)

**Comment by bajtos** [comment]
I see that we already have an issue reported in our postgresql connector, let's move the discussion there.

https://github.com/strongloop/loopback-connector-postgresql/issues/340
