### ISSUE TITLE
Decouple SwaggerRouter and end to end integration of sequence

### ISSUE THREAD

**Issue by rashmihunt** [strongloop/loopback-next#308]
This story will
-  Remove the swagger router as glue code for router, parser, invoker, writer.
- End to end test case working for Sequence

**Comment by rashmihunt** [comment]
1) Extension developer/user will implement MySequence class
```
class MySequence extends Sequence {
  async run() {
        await this.router.run();
        await this.parser.run();
        await this.invoker.run();
        await this.writer.run();
  }
}
```
2) Customer will bind the MySequence class as Class to their App
```
class MyApp extends Application {
  private _startTime: Date;

  constructor() {
    super();
    const app = this;
    app.bind('application.name').to('MyApp');
    app.controller(MyController);
    ....
    app.bind('applications.myApp').to(this); //TODO remove
    app.bind('sequence').toClass(MySequence);

  }
```
3) In current master code branch in server.ts, obtain the 'sequence' bound to app and start the sequence.
```
    const server = createServer(async (req: ServerRequest, res: ServerResponse) => {
    //   const sequence = new Sequence();
      var app = server.getSync('app)');
      var sequence =  app.getSync('sequence');
      await sequence.run(this, req, res);
    });
```
4) To resolve the problem where current router, parser, invoker, writer take specific args which are currently passed in from SwaggerRouter - One solution is to bind these values to the app and make the app available to router/parser/invoker/writer etc. 

5) Once we have done above work, we still have to decouple the sequence we have in swagger router: 
 SwaggerRouter --> parser --> Swagger Router -> invoker --> End User Operation(MyController) --> writer -->

6) MyController constructor should be invoked before invoker sequence  and after authenticator sequence so that we can inject authenticated user into constructor.

5) One question still remains is -> what if user doesn't supply a sequence -> we need to come up in the framework a default sequence..

**Comment by bajtos** [comment]
> Extension developer/user will implement MySequence class
```ts
class MySequence extends Sequence {
  async run() {
        await this.router.run();
        await this.parser.run();
        await this.invoker.run();
        await this.writer.run();
  }
}
```

FWIW, this is slightly different from the direction we agreed to take. The latest acceptance-level description can be found in [loopback-next-sandbox](https://github.com/strongloop/loopback-next-sandbox/blob/d4f351dd5190c1f54139cc7679983bce32a8453c/ts/src/application.ts).

**Comment by superkhau** [comment]
Closing as the current sequence already supports this.
