### ISSUE TITLE
docs should contain which versions of LB3 packages are required to mount into LB4

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-next#3104]
## Description / Steps to reproduce / Feature proposal

I've tried to mount a large LB3 app into LB4. The openapi.json does not contain LB3 models after booting. I looks like LB4 is continuing processing before LB3 is ready.

## Current Behavior

Our LB3 app uses loopback-boot 3.0.1, which does not set the lb3app.booting flag.
That's why [this check](https://github.com/strongloop/loopback-next/blob/72638d28f7ac7b93a4d896b83674eac9afb6fe3e/packages/booter-lb3app/src/lb3app.booter.ts#L78) does not wait for the lb3 app to be completly booted.
I took some time to figure out, that i just need to update loopback-boot to version 3.3.0.

## Expected Behavior

The documentation should contain which LB3 packages are required at minimum. It would be helpful to print some log message if there is a incompatible version.

**Comment by nabdelgadir** [comment]
The [fix](https://github.com/strongloop/loopback-boot/pull/286) that allows it to set the flag immediately was done in `loopback-boot@3.2.1`, so I'll create a PR to let users know to use that version or later. Thanks for letting us know 👍
