### ISSUE TITLE
Test/Enable Node.js 12 for SQL connectors

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#3110]
## Description / Steps to reproduce / Feature proposal
Originated from: https://github.com/strongloop/loopback-next/issues/3072

### Acceptance Criteria
For the following SQL connectors, test locally on Node.js 12 and see if all tests passed.

If yes, add Node.js 12 to CI
If not, try to fix it for simple fixes. If you don't think you can fix it in a day, open a new issue to keep track of it.

- [x] loopback-connector -> https://github.com/strongloop/loopback-connector/pull/148
- [x] loopback-connector-mysql -> [PR](https://github.com/strongloop/loopback-connector-mysql/pull/393)
- [x] loopback-connector-postgresql -> [PR](https://github.com/strongloop/loopback-connector-postgresql/pull/383)
- [x] loopback-connector-mssql -> https://github.com/strongloop/loopback-connector-mssql/pull/212
- [x] loopback-connector-oracle -> https://github.com/strongloop/loopback-connector-oracle/pull/186
- [ ] loopback-connector-db2 (doesn't support Node 12 as of now https://github.com/ibmdb/node-ibm_db/issues/528)

**Comment by nabdelgadir** [comment]
Closing as done.
