### ISSUE TITLE
Test/Enable Node.js 12 for noSQL connectors

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#3111]
## Description / Steps to reproduce / Feature proposal
Originated from: https://github.com/strongloop/loopback-next/issues/3072

reference -> [MySQL](https://github.com/strongloop/loopback-connector-mysql/pull/393)

### Acceptance Criteria
For the following noSQL connectors, test locally on Node.js 12 and see if all tests passed.

If yes, add Node.js 12 to CI
If not, try to fix it for simple fixes. If you don't think you can fix it in a day, open a new issue to keep track of it.

- [x] loopback-connector-mongodb -> https://github.com/strongloop/loopback-connector-mongodb/pull/518
- [x] loopback-connector-couchdb2 -> https://github.com/strongloop/loopback-connector-couchdb2/pull/67
- [x] loopback-connector-cloudant -> https://github.com/strongloop/loopback-connector-cloudant/pull/212
- [x] loopback-connector-cassandra -> https://github.com/strongloop/loopback-connector-cassandra/pull/78

**Comment by nabdelgadir** [comment]
Closing as done.
