### ISSUE TITLE
Test/Enable Node.js 12 for service connectors

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#3112]
## Description / Steps to reproduce / Feature proposal
Originated from: https://github.com/strongloop/loopback-next/issues/3072

### Acceptance Criteria
For the following service connectors, test locally on Node.js 12 and see if all tests passed.

If yes, add Node.js 12 to CI
If not, try to fix it for simple fixes. If you don't think you can fix it in a day, open a new issue to keep track of it.
- [x] loopback-connector-remote -> https://github.com/strongloop/loopback-connector-remote/pull/97
- [x] loopback-connector-rest -> https://github.com/strongloop/loopback-connector-rest/pull/140
- [x] loopback-connector-soap -> https://github.com/strongloop/loopback-connector-soap/pull/109
- ~[ ] loopback-connector-swagger~ [deprecated](https://github.com/strongloop/loopback-connector-swagger/commit/a27fa4eb2ad1f8b2929d329aff09f41e95e42bbf)
- [x] loopback-connector-jsonrpc -> https://github.com/strongloop/loopback-connector-jsonrpc/pull/25
- [x] loopback-connector-openapi -> https://github.com/strongloop/loopback-connector-openapi/pull/4

**Comment by nabdelgadir** [comment]
Closing this as done.
