### ISSUE TITLE
Load components and bind values to IOC container

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#313]
- [ ] loopback-core provides a component-loader which internally has a component-registry.
- [ ] components are loaded using a load() function or a config file
   `loader.load('Authentication', '@loopback/authentication')`
   ```
    component-registry.json
    {
      Authentication: '@loopback/authentication'
    }
   ```
- [ ] on call of load() a bind() function in the component's index.ts is called. context is passed as the parameter
  `module.exports.bind = function (context) {
      .....
    }`   

- [ ] components can bind values to the context
   `context.bind('authentication.required', AuthenticationRequired)`
   `context.bind('authentication.runner', AuthRunner)`

**Comment by raymondfeng** [comment]
1. The Container/Context is the registry. We can add the following methods to the Container interface:
```js
  bindComponent(componentClass: Class<Component>, name?: string): Promise<Component>;
  unbindComponent(name: string): Promise<Component>;
```

2. The component can be exported as follows:

```js
export class AuthenticationComponent implements Component {
  constructor(@inject('application') ..., @inject('other-dep') ...) {}
  activate(ctx: Context): Promise<Binding[]> {
     ctx.bind(...); // It can call bind
     return Promise.resolve(bindings); // Optionally return an array of bindings for the container to bind
  };
  deactivate(ctx: Context): Promise<void> {};
}
```

Additional configuration can be added to package.json or loopback-component.json for discovery.

3. The `app` can load the component as follows:
```js
const componentClass = import AuthenticationComponent from '@loopback/authentication';
app.component(AuthenticationComponent);
```

**Comment by deepakrkris** [comment]
@raymondfeng what if the app needs to refer to multiple authentication components like,
```
   @loopback/authentication
   @bank/authentication
   @telco/authentication
```
do we need to bind a component using a namespace ?

**Comment by deepakrkris** [comment]
@raymondfeng if the component is exported using the same always like `Bundle` or `Component`
then we can have the following in a reusable code:
```
const componentClass = import AuthenticationComponent from '@loopback/authentication';
app.component(AuthenticationComponent);
```

**Comment by raymondfeng** [comment]
We can install components to the app. 

To support declarative approach, the app can discover modules that has `component` signature (for example, `loopback-component` in package.json or loopback-component.json, TBD). The app can have `components.json` to list all components of interest if necessary.

The code above shows the MVP to register components by code. For example, we can do:
```js
import C1 from '@loopback/authentication';
import C2 from '@bank/authentication';
import C3 from  '@telco/authentication';

app.component(C1, C2, C3);
// Or
app.component('c1', C1);
app.component('c2', C2);
app.component('c3', C3);
```

**Comment by raymondfeng** [comment]
See https://code.visualstudio.com/docs/extensions/example-hello-world

**Comment by bajtos** [comment]
> Load components and bind values to IOC container

I think we ended up implementing a slightly different version in https://github.com/strongloop/loopback-next/pull/359.

@raymondfeng @deepakrkris could you please review the current implementation? If you discover any changes/improvements that we should implement on top of #359, then please create new follow-up issues.

I am closing this issue as done.
