### ISSUE TITLE
Loopback 4 issue with static function

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [strongloop/loopback-next#3167]
We found two issues with method name convention, during browerify. I beleive, we should not use static as function name, as we have JavaScript keyword with reserved keyword.

node_modules/@loopback/rest/dist/rest.server.js at line 411 

    static(path, rootDir, options) {
    }

node_modules/@loopback/rest/dist/rest.application.js at line 71, 

    static(path, rootDir, options) {

of versions  "@loopback/rest": {
      "version": "1.15.0",
}

**Comment by dhmlau** [comment]
@raymondfeng @bajtos, what's your thought on ths? 
The 2 files that @gopalakrishnan-subramani mentioned are:
https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/rest.server.ts
https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/rest.application.ts

**Comment by bajtos** [comment]
This looks like a bug in browerify to me (did you perhaps mean `browserify`?).

While Mozilla's JavaScript documentation mentions `static` as a future reserved keyword (see [Lexical grammar - keywords](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords)) and [SyntaxError: "x" is a reserved identifier](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Reserved_identifier), the rule does not seem to apply to method names.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords:
> Reserved words actually only apply to Identifiers (vs. IdentifierNames)

For example, the following code throws SyntaxError when I run it in Safari, Firefox or Node.js:

```js
(function test() { 
  'use strict';
  const static = 1; 
  console.log(static);
})()
```

The following code passes in Safari, Firefox and Node:

```js
(function test() {
  'use strict'; 
  class Foo { 
    static static() { console.log('static method'); }
  }
  Foo.static(); 
})()
```

My conclusion is that we are not doing anything wrong in LoopBack and the problem should be reported to browerify/browserify.

**Comment by gopalakrishnan-subramani** [comment]
We will report to browserify, thank you for clarification.

**Comment by dhmlau** [comment]
@gopalakrishnan-subramani, Is this issue good to close then? Thanks.

**Comment by bajtos** [comment]
Closing this issue as resolved. Feel free to reopen if there is anything else to do on our side.
