### ISSUE TITLE
How to set up Authentification using loopback v4

### ISSUE THREAD

**Issue by moda20** [strongloop/loopback-next#3168]
## Description / Steps to reproduce / Feature proposal

Can't find the documentation for authentification ways in the V4 of loopback, the documentation on the GitHub md files is not that clear ( it reads nonsense 

## Current Behavior
no clear documentation 
## Expected Behavior

Can we get easy steps like the controller, models , ... ways of creating stuff (they already exist )

**Comment by dougal83** [comment]
How about [this post](https://github.com/strongloop/loopback-next/issues/2896#issuecomment-501740873)?

**Comment by giltee** [comment]
While I agree you are right dougal83 but all the links on the actual website are broken. Doesn't make this the easiest thing to find. https://github.com/strongloop/loopback-next/tree/master/packages/authentication#loopbackauthentication

**Comment by dhmlau** [comment]
Sorry about inconvenience.  We'll be publishing a new release shortly, and the documentation will then have the updated information.
cc @emonddr

**Comment by dhmlau** [comment]
@moda20, FYI - We've published a new release.  Please update your dependencies and also `@loopback/cli` as well.  

The new docs are already available. See:
https://loopback.io/doc/en/lb4/Loopback-component-authentication.html
https://loopback.io/doc/en/lb4/Authentication-Tutorial.html

**Comment by jannyHou** [comment]
I am closing this issue since the documentations are published.
Feel free to reopen this issue if you still have questions :)
