### ISSUE TITLE
Set the ID property as auto increment on MySQL datasource

### ISSUE THREAD

**Issue by julianonunes** [strongloop/loopback-next#3174]
## Description / Steps to reproduce / Feature proposal
Add a way to set the ID property as auto increment 

## Current Behavior
Currently the ID property is created as a number but don't allow us to set as auto increment

## Expected Behavior
Create the migration to set the database column as auto increment and ignore the property when inserting a new row.

**Comment by dougal83** [comment]
Hey, have you set `generated: true` on the model ? 
````ts
  @property({
    type: 'number',
    generated: true,
    id: true,
  })
  id?: number;
````

Then you run the migrate tool... I think it's `npm run migrate` by default on a generated project.

**Comment by julianonunes** [comment]
Thanks, @dougal83. It worked.

I didn't see that in the docs and the command line didn't ask that when creating the model.
