### ISSUE TITLE
CLI / Authentication model incompatible versions

### ISSUE THREAD

**Issue by giltee** [strongloop/loopback-next#3175]
## Description / Steps to reproduce / Feature proposal

Create a new project, add the lb4 authentication package and then try and create a model

## Current Behavior
The project has dependencies with incompatible versions required by the CLI:
- @loopback/authentication: ^2.1.1 (cli ^1.2.1)
## Expected Behavior
The versions should be compatible.

This has just started to happen, I didn't have this problem last week. I am really struggling to get proper authentication working in LB4, and I am wondering if this might be the root issue.

**Comment by dhmlau** [comment]
@giltee, I just published new versions for the LoopBack modules less than 10 minutes.  Tried your scenario but didn't get the "incompatible version" error.  Could you please update `@loopback/cli` and try again?  Thanks.

**Comment by giltee** [comment]
Ahh, that would make sense, I tried to run an update about 10 mins ago and got nothing. I will try again, thanks!

**Comment by dhmlau** [comment]
The latest (and updated) documentation has been released as well.  It might take some time to have the docs site refreshed (possibly some time tomorrow). 

In the meanwhile, please take a look at the following:
- https://github.com/strongloop/loopback-next/tree/master/packages/authentication#loopbackauthentication (as you mentioned in another github issue)
- https://github.com/strongloop/loopback-next/blob/master/docs/site/Loopback-component-authentication.md

Hope it helps.
