### ISSUE TITLE
Add back references to passport adapter in authentication docs

### ISSUE THREAD

**Issue by emonddr** [strongloop/loopback-next#3183]
## Description / Steps to reproduce / Feature proposal

Not that PR `[LABS] feat: adapter that wraps strategy ` https://github.com/strongloop/loopback-next/pull/3056  has landed, let's add back `passport adapter` references in the authentication documentation where applicable.

## Acceptance Criteria

- [x] The [Authentication](https://loopback.io/doc/en/lb4/Loopback-component-authentication.html) documentation should have a link to passport-adapter documentation 
- [x] The [@loopback/authentication/README.MD](https://github.com/strongloop/loopback-next/blob/master/packages/authentication/README.md) should have a link to the `passport-adapter` documentation.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@emonddr , could you please add the acceptance criteria? Thanks.

**Comment by jannyHou** [comment]
PR created for it: https://github.com/strongloop/loopback-next/pull/3225
