### ISSUE TITLE
Explain how custom authentication strategy options should be managed

### ISSUE THREAD

**Issue by emonddr** [strongloop/loopback-next#3190]
## Description / Steps to reproduce / Feature proposal

Provide an example of how to manage `default` and `request-level` options in

https://loopback.io/doc/en/lb4/Loopback-component-authentication.html

## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
Closing as done.
