### ISSUE TITLE
 UnsupportedMediaTypeError: Content-type application/text is not supported.

### ISSUE THREAD

**Issue by SephReed** [strongloop/loopback-next#3196]
I want to post a string as a body.

I'm getting this error:

>  UnsupportedMediaTypeError: Content-type application/text is not supported.

Here is my code:

```
@post('/admin/parse-csv', {
    responses: {}
  })
  async createFromCsv(
    @requestBody({content: {'application/text': {}}}) csv: string,
){
  // code
}
```

Why am I getting this error?  And how can I post a string as a body?

I found these docs (https://loopback.io/doc/en/lb4/Extending-request-body-parsing.html), they don't show @requestBody in use.

I dug up these comments in the code (https://github.com/strongloop/loopback-next/blob/8ae8a0a81db205f052b81caaceece5303cd80ff2/packages/openapi-v3/src/decorators/request-body.decorator.ts#L68), and it's about as close to an answer as anything I've found yet.

**Comment by dougal83** [comment]
I think you can just use:
`@requestBody() csv: string,`

... and would `text/csv` be a better fit for your example?

**Comment by SephReed** [comment]
I tried that in the first place, but it kept treating it like json.  Got a could not parse issue.

`text/csv` did the trick though.  thank you.  `text/plain` would also work.

**Comment by rohit-sourcefuse** [comment]
@SephReed can you provide me an example of CSV upload? I am struggling with it?

**Comment by SephReed** [comment]
```
@post('/admin/parse-csv')
async importCsv(
    @requestBody({content: {'text/csv': {}}}) csv: string,
){
  // code
}
```

If you'd like to then parse the csv into a 2d array, here's some more code: https://stackoverflow.com/a/55697280/4808079
