### ISSUE TITLE
lb4 app command is freezing

### ISSUE THREAD

**Issue by tavindersingh** [strongloop/loopback-next#3198]
After I upgraded to @loopback/cli version 1.17.0, lb4 app command is freezing after project description step. I tried uninstalling and re installing the package also I updated to version 1.17.1 still it is freezing.

**Comment by raymondfeng** [comment]
Can you check what version of `inquirer` is installed?

```sh
npm ls -g inquirer
```

**Comment by tavindersingh** [comment]
inquirer@6.4.0

**Comment by raymondfeng** [comment]
That's wrong. Can you try the following?

```sh
npm uninstall -g @loopback/cli
npm install -g @loopback/cli
```

**Comment by tavindersingh** [comment]
it worked thanks
