### ISSUE TITLE
Simpler Syntax for Inclusion

### ISSUE THREAD

**Issue by nabdelgadir** [strongloop/loopback-next#3205]
## Description / Steps to reproduce / Feature proposal

See https://github.com/strongloop/loopback-next/pull/3171/files#r296128644.

Currently to specify inclusion, the following filter syntax is needed: `{include: [{relation: 'todos'}]}` e.g. http://127.0.0.1:3000/todo-lists?filter[include][][relation]=todos

If we try the following call:

```ts
await todoListRepo.findById(todoList.id, {include: ['todos']});
```

The complier complains: `Argument of type '{ include: string[]; }' is not assignable to parameter of type 'Filter<TodoList>'` because the type is currently: `include?: Inclusion<MT>[];` 

As LoopBack 3 supports `{include: ['todos']}`, LoopBack 4 should support this shortcut as well.

## Acceptance Criteria
- [ ] Update [include](https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/query.ts#L213) to accept an array of model relation strings so that something like `{include: ['todos']}` is accepted.
- [ ] Test coverage at both acceptance and integration level.
- [ ] Update examples, tutorials and documentation to leverage the new simpler syntax wherever possible

Important: we need to preserve backwards compatiblity, i.e. the current verbose syntax must stay supported too.

**Comment by bajtos** [comment]
Few examples of the syntax supported by LB3:

```ts
userRepo.find({include: ['posts', 'passports']});

userRepo.find({
  include: [
    {relation: 'posts', scope: {where: {title: 'Post A'}}},
    'passports',
  ],
});
```
