### ISSUE TITLE
expression expected for default 

### ISSUE THREAD

**Issue by kerolloz** [strongloop/loopback-next#3215]
## Description / Steps to reproduce / Feature proposal

```sh
lb4 model
```

![image](https://user-images.githubusercontent.com/36763164/59976314-f8b02c00-95c2-11e9-987b-6c8f219646d9.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/36763164/59976308-dc13f400-95c2-11e9-8ecb-328a3ad501cd.png)

## Expected Behavior

![image](https://user-images.githubusercontent.com/36763164/59976323-11204680-95c3-11e9-9872-9f996ecb1d83.png)

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dougal83** [comment]
This happens when the user enters a value for default as opposed to
blank(no value, not even a space).  Verified.

**Comment by mrmodise** [comment]
This looks to be fixed now

**Comment by dhmlau** [comment]
Closing as resolved.
