### ISSUE TITLE
error TS5042: Option 'project' cannot be mixed with source files on a command line.

### ISSUE THREAD

**Issue by aabou** [strongloop/loopback-next#3222]
hello @raymondfeng & @bajtos,

for information, I have an error following the module update @loopback/build. is there a solution/fix please?

Thk's 2Team.
## Steps to reproduce
>node --version
 v8.11.2
>npm --version
5.6.0

update @loopback/build  ^1.6.1  →  ^2.0.2

## Current Behavior

> npm run build
...
error TS5042: Option 'project' cannot be mixed with source files on a command line.

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
See the migration guide in release notes: https://github.com/strongloop/loopback-next/blob/master/packages/build/CHANGELOG.md#200-2019-06-17

 - Modify your `tsconfig.json` file and configure `dist` via `compilerOptions.outDir`
 - If you are using target different from `es2017`, then configure it via  `compilerOptions.target`.
 - Remove `es2017` and `--outDir dist` from lb-tsc arguments.
 - Ensure that the output directory is listed in `lb-clean` arguments,  e.g. call `lb-clean dist`.
 - When calling `lb-mocha`, replace `DIST` with the actual outDir value, typically `dist`

**Comment by shadyanwar** [comment]
@bajtos 
After updating @loopback/build and following the migration guide, tsconfig.json  is giving this error:
File '/{projectDirectory}/credentials/dev/myDs.dev.datasource.json' is not under 'rootDir' '/{projectDirectory}/src'. 'rootDir' is expected to contain all source files.ts

The reason why I have my datasource json files in a folder is that I am using key encryption (with my host) to upload the database credentials to git encrypted and make our deployment process seamless.
