### ISSUE TITLE
Add source map support

### ISSUE THREAD

**Issue by AmrSalama** [strongloop/loopback-next#3223]
## Suggestion

Add source map support between `ts` and `js` files

## Use Cases

The current behaviour doesn't reflect errors in `ts` files

![Error stack trace with js files](https://user-images.githubusercontent.com/15939360/60027463-cf180300-969d-11e9-9728-5a677c25c0ee.png)

## Examples

Using [`source-map-support`](https://www.npmjs.com/package/source-map-support) and updating `start` script to
```
"start": "node -r source-map-support/register .",
```

![Error stack trace with ts files](https://user-images.githubusercontent.com/15939360/60027830-81e86100-969e-11e9-8bd3-62233b674c39.png)

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dhmlau** [comment]
Closing as resolved because PR #3228 has landed.
