### ISSUE TITLE
Missing Documentation/Example for code coverage

### ISSUE THREAD

**Issue by jalouxx** [strongloop/loopback-next#3227]
Loopback build tools provide the command `lb-nyc` but unfortunately there is no further documentation added here: https://github.com/strongloop/loopback-next/tree/master/packages/build

I have tried the following command (and many more) but without any success:
`npx lb-nyc report` --> No console output
`npx lb-nyc npm run test` --> runs tests etc but no coverage report

running plain nyc with `npx nyc --all npm run test` only produces the following output:
```
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
 index.js |        0 |        0 |        0 |        0 |  1,3,5,7,17,18,19 |
----------|----------|----------|----------|----------|-------------------|
```
Which indicates that it is not going into the actual tested files.
Is there any working example with code coverage using istanbul or similar?

Additionally I was wondering:
Why is loopback executing the compiled tests on the `dist` resources and not directly on src-lvl? React-Scripts for the frontend is executing tests in the src directories. Wouldn't that make more sense from a coverage perspective?

**Comment by raymondfeng** [comment]
`lb-nyc` is simple wrapper over `nyc`. It takes the same arguments. By default, you should see `coverage/index.html`.

**Comment by raymondfeng** [comment]
> Why is loopback executing the compiled tests on the dist resources and not directly on src-lvl? React-Scripts for the frontend is executing tests in the src directories. Wouldn't that make more sense from a coverage perspective?

We transpile TS code into `dist` as JS code so that TS is only required at development time. Once the package is published to `npm`, it's just a JS module.

The test coverage is reported based on source map support that connects JS to TS.

**Comment by raymondfeng** [comment]
BTW, the nyc report can be customized using `.nycrc`. See an example at https://github.com/strongloop/loopback-next/blob/master/.nycrc

**Comment by raymondfeng** [comment]
@jalouxx Please let me know if your questions are answered so that we can close this issue.

**Comment by jalouxx** [comment]
@raymondfeng thank you very much for the answers.
I was able to get it running yesterday. I would like to add some documentation to the build tools readme. I will open a PR hopefully until end of this week.
