### ISSUE TITLE
Loopback4 challenges

### ISSUE THREAD

**Issue by psr1410** [strongloop/loopback-next#3247]
I am very new to this Loopback 4. When I am setting up my project I am having some setup issues. Below are few things.

Environment based datasource loading There is no direct way to load the datasource based on the environment.

Some configurations/constant variables need to be defined on a JSON file to access into the entire application, again this is also based on the environment.

Not able to connect MongoDB Atlas database. In an express application I am able connect, but not in Loopback. Below is the error it is returning. url.dbName || self.settings.database, ^ TypeError: Cannot read property 'dbName' of null

Not able to achieve model relations.

I don't want to return the entire Model in my API response. How can I customize my API response using the Model?
I want to write my business logic in a separate file, not in a controller/repository. is it a good idea OR where should I return the business logic? and best practices.
I don't find proper documentation on Loopback4 to solve these issues. any help would be appreciated.

**Comment by raymondfeng** [comment]
> Environment based datasource loading There is no direct way to load the datasource based on the environment.

You can override the generated datasource class to retrieve information from env vars. Probably around the code similar as 
https://github.com/strongloop/loopback-next/blob/master/examples/todo/src/datasources/db.datasource.ts#L14

**Comment by raymondfeng** [comment]
> Some configurations/constant variables need to be defined on a JSON file to access into the entire application, again this is also based on the environment.

Please check out https://loopback.io/doc/en/lb4/Context.html#configuration-by-convention. 

See examples at:
- https://github.com/strongloop/loopback-next/blob/master/examples/context/src/custom-configuration-resolver.ts
- https://github.com/strongloop/loopback-next/blob/master/examples/context/src/configuration-injection.ts

**Comment by raymondfeng** [comment]
> Not able to connect MongoDB Atlas database. In an express application I am able connect, but not in Loopback. Below is the error it is returning. url.dbName || self.settings.database, ^ TypeError: Cannot read property 'dbName' of null

> Not able to achieve model relations.

Please open separate issues.

**Comment by raymondfeng** [comment]
> I don't want to return the entire Model in my API response. How can I customize my API response using the Model?

You can use https://loopback.io/doc/en/lb4/Interceptors.html

**Comment by raymondfeng** [comment]
> I want to write my business logic in a separate file, not in a controller/repository. is it a good idea OR where should I return the business logic? and best practices.

You can create separate classes and compose them using Dependency Injection. See examples at https://github.com/strongloop/loopback-next/tree/master/examples/context.

**Comment by kerolloz** [comment]
@psr1410 
You can do something like 
![image](https://user-images.githubusercontent.com/36763164/60670145-4274fe00-9e70-11e9-9334-b5ef6b50ed5c.png)

**Comment by dhmlau** [comment]
@psr1410, we believe we've answered your question, so I'd like to close this issue. If you encounter other issues, please feel free to open a new one. Thanks!
