### ISSUE TITLE
Extending model CRUD operations

### ISSUE THREAD

**Issue by Subaku** [strongloop/loopback-next#3264]
Hello,

I'm a complete LoopBack beginner and I'm getting buried under all the magic...

How do I go about extending or overriding the find, findById, count, etc methods that get auto defined on my models when using the DefaultCrudRepository? Pouring through anything I can find (including the source code) it's unclear. I assume the place to do this is in my repository for the model?

Thanks

**Comment by raymondfeng** [comment]
Yes, you can override the generated repository classes.

**Comment by Subaku** [comment]
Thanks for getting back to me. 

Follow up question then. What I'm ultimately trying to to is pass extra arguments to my connector's getAllEntity method and others. I was thinking I'd need to override the find method inside the repository in some way to make that happen? 

 I'm also trying to change on the fly the model that gets passed to said getAllEntity as well. Sorry if this is documented somewhere already. Couldn't find any examples of this.

**Comment by raymondfeng** [comment]
1. TypeScript allows you to override base methods, such as:
```ts
async findAll(...) {
  // ... pre-process req
  const result = await super.findAll(...);
  // ... post-process res
  return result;
}
```
If you want to apply changes on the fly for multiple repositories, it's also possible to use interceptors.

See https://loopback.io/doc/en/lb4/Interceptors.html.
