### ISSUE TITLE
Support for PostgreSQL bytea and Node.js Buffer

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [strongloop/loopback-next#3270]
I could not find the document for this, 
how to define type for bytea PostgreSQL Blob type and Node.js object in loopback Next and TypeScript? We could not find any example for the same. 
export class Image extends Entity {
  
  @property({
    type: 'string',
    required: true,
  })
  content: string;

}

**Comment by raymondfeng** [comment]
Can you try to add postgresql mapping as illustrated by https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#data-mapping-properties?

**Comment by gopalakrishnan-subramani** [comment]
@raymondfeng Thanks for the tip, it works!!

Can you please give an example for downloading blob/image/documents like pdf using loopback 4? I could not find any source example. Thank you.
