### ISSUE TITLE
Primary changelog should include all changes

### ISSUE THREAD

**Issue by ErwSim** [strongloop/loopback-next#3278]
## Suggestion

I would like that the primary CHANGELOG file contains all others CHANGELOG.

## Use Cases

Without this, we can miss some breaking changes (I had hard time to fix a breaking change)

## Examples

For example with the last update I had to add "outDir": "dist" in my tsconfig.json
But I didn't knew before I checked file in a new project

## Acceptance criteria

TBD - will be filled by the team.

**Comment by bajtos** [comment]
@ErwSim thank you for the proposal, I see how an aggregated changelog file can be useful.

We are generating our CHANGELOG files using [`lerna version`](https://github.com/lerna/lerna/tree/master/commands/version) and [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog).

AFAICT, `lerna` does not support aggregation of changelog entries. Can you open a new issue in https://github.com/lerna/lerna to discuss this idea? I think we will be happy to use it once it becomes available.
