### ISSUE TITLE
Docs Loopback v4 are broken @ https://apidocs.strongloop.com/

### ISSUE THREAD

**Issue by mcorbe** [strongloop/loopback-next#3306]
## Steps to reproduce

Visit https://apidocs.strongloop.com/
Click on "@loopback/core" link

## Current Behavior

Error page

## Expected Behavior

Documentation for the loopback core API.
 
## Link to reproduction sanbox

https://apidocs.strongloop.com/@loopback%2fdocs/core.html

**Comment by jannyHou** [comment]
hey @mcorbe the apidocs are moved to https://loopback.io/doc/en/lb4/apidocs.index.html 🙂

**Comment by jannyHou** [comment]
cc @strongloop/loopback-maintainers should we remove the LB4 apidocs from https://apidocs.strongloop.com/ ?

**Comment by nabdelgadir** [comment]
Can we redirect from https://apidocs.strongloop.com/ to https://loopback.io/doc/en/lb4/apidocs.index.html?

**Comment by hacksparrow** [comment]
Yes, we should do a `301` redirection.

**Comment by bajtos** [comment]
@raymondfeng could you PTAL?

From what I remember, the old apidocs should be still working.

**Comment by mcorbe** [comment]
@jannyHou perfect, thanks !

@nabdelgadir @hacksparrow @bajtos, please take over closing the thread when reached a decision.

**Comment by raymondfeng** [comment]
Hmm, it should have been fixed by https://github.com/strongloop-internal/apidocs.strongloop.com/pull/93/. I'm not sure why the site has not been refreshed.

**Comment by rmg** [comment]
@raymondfeng last I checked the only deployment that is automatic is to staging. Promoting to production is a manual trigger.

**Comment by raymondfeng** [comment]
I just triggered the promotion now.

**Comment by raymondfeng** [comment]
The site is now updated.
