### ISSUE TITLE
repository cloning link for shoping example is not working

### ISSUE THREAD

**Issue by kerolloz** [strongloop/loopback-next#3314]
## Steps to reproduce

go to [JWT Authentication documentation](https://loopback.io/doc/en/lb4/Authentication-Tutorial.html#try-it-out) `try-it-out` section. Try to copy and paste the commands in your terminal.

## Current Behavior

![image](https://user-images.githubusercontent.com/36763164/60801797-e82db300-a177-11e9-8f82-eed51bda4a43.png)

This error comes up.

```
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

## Expected Behavior

The repository should be cloned successfully.

## Additional information

linux x64 12.5.0

**Comment by emonddr** [comment]
@kerolloz ,

Thank you for reaching out to us.

From the picture, it looks like you pasted all the lines into a command window.

1) Did you try the `git clone` by itself on the command line?

2) Do you have an SSH key set up with github.com ?
  
    Go to: https://github.com/settings/keys 
    Personal Settings > SSH and GPG keys 

3) Are you able to perform `git clone` with other repositories that are not LoopBack?

**Comment by bajtos** [comment]
Perhaps we should tell people to clone using HTTPS protocol?

```
git clone https://github.com/strongloop/loopback4-example-shopping.git
```

**Comment by kerolloz** [comment]
@bajtos 
That is what I did here: https://github.com/strongloop/loopback-next/pull/3315
