### ISSUE TITLE
Broken link on npmjs.com for authentication and example-greeter-extension

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#3319]
## Steps to reproduce
As @emonddr pointed out, when our readme shows up on npmjs.com, the images cannot be resolved for https://www.npmjs.com/package/@loopback/authentication and https://www.npmjs.com/package/@loopback/example-greeter-extension. 

One possible solution is to use full path of the image.

**Comment by raymondfeng** [comment]
The url for an image on github is something like:

https://raw.githubusercontent.com/strongloop/loopback-next/master/examples/greeter-extension/greeters.png

We'll have to embed the image as follows:
```md
![diagram](https://raw.githubusercontent.com/strongloop/loopback-next/master/examples/greeter-extension/greeters.png)
```
