### ISSUE TITLE
prevent sending some properties in request body

### ISSUE THREAD

**Issue by kerolloz** [strongloop/loopback-next#3325]
I have a `User` model. the model has a property named `isVerified`. I want to prevent this property from being sent in the request body.

I tried marking it as generated, but that doesn't work.

```typescript
@property({
   type: 'boolean',
   default: false,
   generated: true,
})
isVerified?: boolean;
```

I expect to throw 422 unprocessable entity when `isVerified` is sent in the request body.

**Comment by raymondfeng** [comment]
I think we'll have to introduce some metadata to describe the property is readonly.

**Comment by shadyanwar** [comment]
Check https://github.com/strongloop/loopback-next/issues/2454

**Comment by mrbatista** [comment]
@raymondfeng The [JSON Schema draft-07](http://json-schema.org/latest/json-schema-validation.html) define a new keywords `readOnly` and `writeOnly` keywords. AJV allow to define this keywords and to add custom validation. See the [Annotation keywords](https://github.com/epoberezkin/ajv#annotation-keywords) section.
Can this be a good starting point?

**Comment by lajosf** [comment]
Any news here?

**Comment by achrinza** [comment]
Will consolidate it under #2454 as a feature request. Please comment if you believe this was done in error.

**Comment by achrinza** [comment]
Duplicate of #2454
