### ISSUE TITLE
Missing whitespace in lb4 repository command last line output when selecting multiple models

### ISSUE THREAD

**Issue by Charly6596** [strongloop/loopback-next#3350]
# Description/Steps to reproduce
1- Create a new project and enable repositories
```cmd
lb4
? Project description: loopback
? Project root directory: loopback
? Application class name: LoopbackApplication
? Select features to enable in the project Enable repositories
```
2- Move to the proyect folder and add two models (with any name and default values would do)
```cmd
cd loopback
lb4 model
? Model class name: Animal
? Please select the model base class Entity (A persisted model with an ID)
? Allow additional (free-form) properties? No

lb4 model
? Model class name: Pet
? Please select the model base class Entity (A persisted model with an ID)
? Allow additional (free-form) properties? No
```

3- Add any datasource with default values
```cmd
lb4 datasource
? Datasource name: db
? Select the connector for db: In-memory db (supported by StrongLoop)
? window.localStorage key to use for persistence (browser only): 
? Full path to file for persistence (server only): 
```
4- Add a repository for both entities
```cmd
lb4 repository
? Please select the datasource DbDatasource
? Select the model(s) you want to generate a repository Animal, Pet
? Please select the repository base class DefaultCrudRepository (Legacy juggler bridge)
? Please enter the name of the ID property for Animal: id
? Please enter the name of the ID property for Pet: id
   create src/repositories/animal.repository.ts
   create src/repositories/pet.repository.ts
   update src/repositories/index.ts
   update src/repositories/index.ts

Repositories AnimalRepositoryPetRepository was created in src/repositories/
```

# Link to reproduction sandbox

The issue is before launching the app

# Expected result

Last line should be something like the following:
```cmd
Repositories AnimalRepository PetRepository created in src/repositories/
```
instead of
```cmd
Repositories AnimalRepositoryPetRepository was created in src/repositories/
```

# Additional information

```
node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 11.15.0```
```cmd
npm ls --prod --depth 0 | grep loopback
loopback@1.0.0 /home/charly/repos/loopback/loopback
├── @loopback/boot@1.4.4
├── @loopback/context@1.20.2
├── @loopback/core@1.8.5
├── @loopback/openapi-v3@1.7.0
├── @loopback/repository@1.8.2
├── @loopback/rest@1.16.3
└── @loopback/rest-explorer@1.2.5
```

**Comment by dhmlau** [comment]
Transferred to `loopback-next` repo since it's related to LB4. 
@Charly6596, thanks for reporting the problem. Would you be interested in submitting a patch?  The code for LB4 CLI is in here: https://github.com/strongloop/loopback-next/tree/master/packages/cli.

In case you're new to submitting PR in LB4, here is the step by step instruction: https://loopback.io/doc/en/lb4/submitting_a_pr.html. Thanks!

**Comment by raymondfeng** [comment]
@Charly6596 The fix should be very simple. On line https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/repository/index.js#L553, use:

`? this.artifactInfo.modelNameList.join(',')`

**Comment by Charly6596** [comment]
@dhmlau @raymondfeng thanks, yes, I'd like to do that after reading the instructions :+1:

**Comment by godartm** [comment]
hi @Charly6596 , i see you are not assigne to this issue , so do you plan to do it or can i take it ?

**Comment by Charly6596** [comment]
> hi @Charly6596 , i see you are not assigne to this issue , so do you plan to do it or can i take it ?

Hey, I actually _fixed_ it, it was a bit more than adding a `,` but it isn't passing the tests (formatting test i believe) so if you want to take a look at that [here](https://github.com/Charly6596/loopback-next/commit/92d8365f8a3a207e4ca33e226ff631cdb1dc8dbf) is my commit in my forked repo, I will create a work in progress pull request and I won't be able to complete it anytime soon, so feel free to contribute!
