### ISSUE TITLE
how to debug loopback 4 query in mysql.

### ISSUE THREAD

**Issue by ankit-devtool** [strongloop/loopback-next#3360]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by dhmlau** [comment]
@ankit-devtool, I've transferred your issue to the `loopback-next`. That's the repo for LB4.
Following up with our conversation on gitter, I've suggested to use `DEBUG=loopback:rest:*`. 

To use that, you can run this:
```
DEBUG=loopback:rest:* npm start
```

**Comment by ankit-devtool** [comment]
Thank you, this command is helpful.

**Comment by dhmlau** [comment]
Good to hear. Let me close this issue as resolved then. Thanks!
