### ISSUE TITLE
Sending email using loopback and angular 6

### ISSUE THREAD

**Issue by hns23** [strongloop/loopback-next#3368]
I have installed Loopback for angular 6. In registration page, I need to send password via email to the user.
Anyone implemented this let me know. I have followed this

https://loopback.io/doc/en/lb3/Email-connector.html

**Comment by dougal83** [comment]
See https://github.com/strongloop/loopback-next/issues/1979#issue-377500723.  An example has been posted by someone there on how to make a service.

**Comment by dhmlau** [comment]
Thanks @dougal83.
@hns23, I'd like to continue the discussion over #1979.  Closing this as duplicate. Thanks.
