### ISSUE TITLE
Upload image to mongodb using loopback4

### ISSUE THREAD

**Issue by yasminthaj** [strongloop/loopback-next#3377]
Hi Team,

I am building an e-commerce app with loopback 4, here i want to upload product details along with product image, do i need to go ahead with loopback storage components or any other options are available?, but i found the integration is not yet done https://stackoverflow.com/questions/54663283/how-to-use-storage-components-in-loopback-4-0 
Please help me on this.

**Comment by dhmlau** [comment]
@yasminthaj , could you please review the discussion in https://github.com/strongloop/loopback-next/issues/2559 to see if it helps? Thanks.

**Comment by yasminthaj** [comment]
I have tried already but it not help me on to achieve my requirement.

**Comment by raymondfeng** [comment]
@yasminthaj There are two parts involved:

1. How to expose an endpoint to allow file upload?

Please check out https://github.com/strongloop/loopback-next/tree/master/packages/rest/src/__tests__/acceptance/file-upload

2. How to write the file into mongodb?

You might have to use mongodb driver api directly at this point.

**Comment by dhmlau** [comment]
@yasminthaj, does the above comment from @raymondfeng help?

**Comment by dhmlau** [comment]
Closing as resolved. Thanks.

**Comment by charfeddine10** [comment]
Did you find a solution please ?
