### ISSUE TITLE
[Docs] Add page for "Inside a LoopBack 4 application"

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#3382]
## Description

Originated from the docs improvement proposal: https://github.com/strongloop/loopback-next/pull/3164

> Inside a LoopBack 4 application
> as a typical LoopBack 4 application (a concrete scenario), how a typical LB application looks like and what are the building blocks and how they fit into the LB application.

## Acceptance Criteria
- [x] Add a new sidebar item called "Inside a LoopBack 4 application" just above the "key concepts"
- [x] Add a page that contains content about: 
   > as a typical LoopBack 4 application (a concrete scenario), how a typical LB application looks like and what are the building blocks and how they fit into the LB application.

Note: IIRC, @raymondfeng has some version of such diagram.

**Comment by deepakrkris** [comment]
I am thinking about having a page with this outline

```
 ## Build models

  ...... give some overview and links to model and relations ....


## Design API spec

 .... overview/links on api spec configurations on controllers ....


## Persist and Query models

.... overview/links on connector architecture...
```

**Comment by deepakrkris** [comment]
we can even have a user interaction diagram like below
`Build Models -> Design APIs -> Connect`
