### ISSUE TITLE
Missing options in Authentication module to add passport based Goggle Auth

### ISSUE THREAD

**Issue by bhupesh-sf** [strongloop/loopback-next#3396]
## Suggestion

Need to update **AuthenticationStrategy** interface and **StrategyAdapter** class to allow for passport options

Currently the **AuthenticationStrategy** interface allows only request to be passed in authenticate function but it should also allow the optional response and options.

## Use Cases

Need to implement Google Auth passport strategy in my project i.e. http://www.passportjs.org/docs/google/
I need to pass certain options when creating this strategy like callback URL and when the authentication happens it returns back the redirect URL where application should be redirected. 

Current approach allows only request to be passed in **AuthenticationStrategy** interface which should allow response and options (to configure passport options for any strategy) and also **StrategyAdapter** class (taken from https://www.npmjs.com/package/@loopback/authentication-passport) doesn't have way to pass options (because interface doesn't have) and it also doesn't have any method to handle redirects as well. 

It will help to pass options with any passport strategy while calling authenticate function to override certain behaviours. 

I have already override certain changes and make it work and will be happy to contribute to the issue. I allowed in the interface for the response and options to be passed and override **StrategyAdapter** to implement the new interface changes and also included the redirect method.

Unfortunately I couldn't find the github repo for https://www.npmjs.com/package/@loopback/authentication-passport otherwise I could have generated the PR

@bajtos @raymondfeng @samarpanB

**Comment by dhmlau** [comment]
cc @jannyHou @emonddr

**Comment by bhupesh-sf** [comment]
Any update here?

**Comment by dhmlau** [comment]
@jannyHou, could you please take a look? Thanks. Assigning this to you.

**Comment by jannyHou** [comment]
Hi @bhupesh-sf just in case you haven't read our [Authentication documentation](https://loopback.io/doc/en/lb4/Loopback-component-authentication.html) I highly recommend you take a look of the section [managing custom authentication strategy options](https://loopback.io/doc/en/lb4/Loopback-component-authentication.html#managing-custom-authentication-strategy-options) first :)


Different options are provided in different places, from your description:

- You use `passport-google-auth`, and apply the `StrategyAdapter` to it
  - The `passport-strategy` module is in a lab branch(not master) called `labs/passport-adapter`: see the [package](https://github.com/strongloop/loopback-next/tree/labs/passport-adapter/labs/authentication-passport)
- You want to config the `GoogleStrategy` from `passport-google-auth` 
  - With the current design this should be possible. You can provide the options when you instantiate the `GoogleStrategy`. E.g. see how the `basicStrategy` get created in [the simple usage example](https://github.com/strongloop/loopback-next/tree/labs/passport-adapter/labs/authentication-passport#simple-usage). (The example doesn't have an option but it's very straightforward to add one)
  - Or if you need to **inject** the option, see the next example: [provide the strategy with a provider](https://github.com/strongloop/loopback-next/tree/labs/passport-adapter/labs/authentication-passport#with-provider), that example has an injected `verify` function, you can inject the options in the same way.

---

IMO, adding another parameter `options` in interface `AuthenticationStrategy`, or adding `options` in its `authenticate()` function is another story. If the example/doc above ^ doesn't solve your problem, let's continue the discussion for improving the interface itself :)

**Comment by joe-niland** [comment]
Hi @jannyHou 

I hope it's OK to add my discussion here, as I have a similar issue.

I am trying to use `passport-jwt` via a StrategyAdapter. I followed the Simple Usage case in your linked example and I am able to authenticate requests using the decorator.

However, I need to inject a UserRepository, JWT secret, etc into the Strategy. I tried creating a provider by following your other example, but the TypeScript compiler doesn't recognise the type of the custom provider as `Constructor<AuthenticationStrategy>`, e.g.

`Argument of type 'typeof PassportJwtAuthProvider' is not assignable to parameter of type 'Constructor<AuthenticationStrategy>'.`

Apologies if this is the wrong place to ask this. Thanks!

**Comment by jannyHou** [comment]
@joe-niland 
> I hope it's OK to add my discussion here

Sure feel free to continue the discussion here.
It's very hard for me to diagnose the problem without code, could you submit the example code you tried?

**Comment by jannyHou** [comment]
any update on this issue?

**Comment by joe-niland** [comment]
Hi @jannyHou

I've had to move away from LoopBack for this project due to deadlines.

Next time I use it I will open a new ticket.

Thanks for following up.

**Comment by jannyHou** [comment]
I am sorry to hear that, but thank you for trying LoopBack and good luck with your project.
We will be glad to help whenever you want to try it again :)

Closing this issue.
