### ISSUE TITLE
OpenAPI generator should give a more descriptive error when operationId is missing

### ISSUE THREAD

**Issue by evantrimboli** [strongloop/loopback-next#3417]
## Suggestion

The generator should detect if the operator is missing and throw an error.

## Use Cases

I had omitted the `x-operation-name` and `operationId` for a particular path. The generation failed with a not very helpful error.  `operationId` isn't required, so the yaml file validated as being correct.

## Examples

```
function getMethodName(opSpec) {
  const name = opSpec['x-operation-name'];
  const id = opSpec.operationId;
  if (!name && !id) {
    throw new Error('You forgot the operationId!');
  }
  return name || escapeIdentifier(id);
}
```

## Acceptance criteria

TBD - will be filled by the team.

**Comment by jannyHou** [comment]
I think a more reasonable error could be returned in the function here https://github.com/strongloop/loopback-next/blob/72cb8aafad31588deff96fb1af6d33fa03fe5fd5/packages/cli/generators/openapi/spec-helper.js#L137

**Comment by dhmlau** [comment]
@evantrimboli, would you be interested in submitting a patch?

**Comment by bajtos** [comment]
Perhaps instead of throwing an error, can we build the method name from other metadata that's available? For example, using the endpoint verb and path, like `GET /api/users/{id}` -> `getApiUsersWithId`.

**Comment by acorbellini** [comment]
Hi all, we had a hard time finding this issue. The bug description lacks the actual undescriptive error printed out, which is the only hint we had to google it:

> Loading test.yaml...
> Generation is aborted: TypeError: Cannot read property 'match' of undefined

As mentioned, the solution was adding `operationId` to the path definition. Thanks to the OP for pointing that out.

**Comment by bajtos** [comment]
@raymondfeng could you PTAL? I think we should start with fixing the generator first to ensure stack traces of unexpected errors are printed. IIRC, you are most familiar with the way how errors are handled by our CLI.

Secondly, it would be great to improve the generator to report a more helpful error when the operationId is missing, as proposed by Janny in https://github.com/strongloop/loopback-next/issues/3417#issuecomment-514333969

**Comment by jrr** [comment]
Tried out Loopback for the first time today, excited about its TypeScript support and OpenAPI integration.

Pasted in my existing OpenAPI schema, tried to generate from it:

```
lb4 openapi my-apis.yaml
```

And immediately hit this:

```
Generation is aborted: TypeError: Cannot read property 'match' of undefined
```

(Thanks @acorbellini for making this issue findable)

Adding `operationId`s to the schema for each endpoint fixed it.

**Comment by lauksas** [comment]
Many thanks @jrr , that resolved my problem.
