### ISSUE TITLE
npm run eslint fails in app generated by @loopback/cli

### ISSUE THREAD

**Issue by aharbis** [strongloop/loopback-next#3424]
## Steps to reproduce

Installed `@loopback/cli` and generated a new project.

## Current Behavior

```
$ npm run eslint

> app@1.0.0 eslint /home/user/app
> eslint -p .

Invalid option '-p' - perhaps you meant '-f'?
```

## Expected Behavior

Generated `package.json` should not include npm run script which fails.

## Additional information

For what it's worth, I think this came from here:

https://github.com/strongloop/loopback-next/blob/1882240c623c3e68b8b90630296e622b6193a1bd/packages/cli/generators/project/templates/package.plain.json.ejs#L32-L35

As far as I can tell, the `eslint` CLI does not offer a `-p` command, or at least I didn't see one from:

```
$ ./node_modules/.bin/eslint --help
```

Additionally their config for the CLI doesn't seem to list one:

https://github.com/eslint/eslint/blob/master/lib/options.js

LB4 CLI version info:

```
$ lb4 --version
@loopback/cli version: 1.19.0

@loopback/* dependencies:
  - @loopback/authentication: ^2.1.6
  - @loopback/boot: ^1.4.5
  - @loopback/build: ^2.0.4
  - @loopback/context: ^1.20.3
  - @loopback/core: ^1.8.6
  - @loopback/metadata: ^1.2.6
  - @loopback/openapi-spec-builder: ^1.2.6
  - @loopback/openapi-v3-types: ^1.2.1
  - @loopback/openapi-v3: ^1.8.0
  - @loopback/repository-json-schema: ^1.9.0
  - @loopback/repository: ^1.9.0
  - @loopback/rest: ^1.16.4
  - @loopback/testlab: ^1.7.0
  - @loopback/docs: ^1.26.1
  - @loopback/example-hello-world: ^1.2.6
  - @loopback/example-log-extension: ^1.2.6
  - @loopback/example-rpc-server: ^1.2.6
  - @loopback/example-todo: ^1.6.6
  - @loopback/example-soap-calculator: ^1.6.7
  - @loopback/service-proxy: ^1.2.6
  - @loopback/http-caching-proxy: ^1.1.6
  - @loopback/http-server: ^1.4.5
  - @loopback/example-todo-list: ^1.8.2
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^1.2.6
  - @loopback/eslint-config: ^2.0.1
  - @loopback/example-express-composition: ^1.4.6
  - @loopback/example-greeter-extension: ^1.3.6
  - @loopback/booter-lb3app: ^1.2.6
  - @loopback/example-lb3-application: ^1.1.6
  - @loopback/example-greeting-app: ^1.1.6
  - @loopback/example-context: ^1.2.6
  - @loopback/repository-tests: ^0.2.3
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by aharbis** [comment]
Here's the full `scripts` section of the `package.json` that yields the issue:

```json
  "scripts": {
    "build": "tsc",
    "build:watch": "tsc --watch",
    "clean": "rimraf dist *.tsbuildinfo",
    "lint": "npm run prettier:check && npm run eslint",
    "lint:fix": "npm run eslint:fix && npm run prettier:fix",
    "prettier:cli": "prettier \"**/*.ts\" \"**/*.js\"",
    "prettier:check": "npm run prettier:cli -- -l",
    "prettier:fix": "npm run prettier:cli -- --write",
    "eslint": "eslint -p .",
    "eslint:fix": "npm run eslint -- --fix",
    "pretest": "npm run clean && npm run build",
    "posttest": "npm run lint",
    "docker:build": "docker build -t home-tasks .",
    "docker:run": "docker run -p 3000:3000 -d home-tasks",
    "migrate": "node ./dist/migrate",
    "start": "npm run build && node -r source-map-support/register .",
    "prepare": "npm run build"
  },
```

**Comment by aharbis** [comment]
I'm not quite sure what the difference is between the use of these two files:

- `packages/cli/generators/project/templates/package.json.ejs`
- `packages/cli/generators/project/templates/package.plain.json.ejs`

But it seems the non-`plain` one likely has the more correct `eslint` usage:

https://github.com/strongloop/loopback-next/blob/1882240c623c3e68b8b90630296e622b6193a1bd/packages/cli/generators/project/templates/package.json.ejs#L32-L35

**Comment by aharbis** [comment]
I confirmed that installing `@loopback/build` (honestly thought I checked that in the generator, but maybe not), and switching my `scripts` section to what's doc'd [here](https://www.npmjs.com/package/@loopback/build#basic-use) my `npm run eslint` succeeds.

I guess that just means that for whatever reason if a user does not check the `@loopback/build` option in the app generator then their `eslint` npm run script will be broken.

**Comment by raymondfeng** [comment]
Good catch! Can you submit a patch to remove `-p`?

**Comment by aharbis** [comment]
Sure! Feel free to assign to me, I'll get a PR open soon.
