### ISSUE TITLE
Setting a timezone other than UTC as default

### ISSUE THREAD

**Issue by shadyanwar** [strongloop/loopback-next#3430]
It seems that loopback-datasource-juggler is converting any `type: Date` (if defined as so in the model) to UTC before saving to the database.

By doing some digging, [this](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L331) is where it happens.

What makes things more confusing is that whenever the same data is fetched, it does not undergo this conversion backwards. i.e. it is displayed exactly as it is saved in the database.

## Steps to reproduce

1. Create a model with a property of the type Date: `@property({type: Date,...}))`

2. In a machine with a timezone other than UTC (for example UTC+7), create a record with the date value: '2019-07-25T08:00'

## Current Behavior

The data will be saved to the database as '2019-07-25T01:00', not taking into consideration any timezone set anywhere.

## Expected Behavior

I propose that adding a timezone property in the datasource be honoured instead of defaulting to UTC. So the behaviour of converting to UTC should remain, but after that conversion a check should be made whether a different timezone is defined in the datasource and convert to it if exists: `{"timezone": "UTC+07:00"}`
Example:
`{ "host": "127.0.0.1", "port": 3306, "database": "mydb", "username": "root", "password": "root", "name": "mydb", "connector": "mysql", "timezone": "UTC+07:00" }`

My only current workaround is to change `type: Date` to `type: String` in the model property definition.

## Additional information
I am reporting this as a bug since the framework's behavior is as described even if the app server (on the os level) and the database server (for example mysql, my.cnf: default-time-zone='+07:00') have a timezone set to other than UTC.

And also because this behavior is enforced even if the value of the date is defined as string. The [dao](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js) overrides any possible value and performs this conversion.

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
@shadyanwar thank you for reporting the bug. What database are you using? (This behavior could be connector specific).

Please create a small application we can use to reproduce and debug the issue. We are quite busy and creating one ourselves would not be an effective use of our limited time. See https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs

**Comment by shadyanwar** [comment]
@bajtos Here you go:
https://github.com/shadyanwar/lb4-timezone-test

After running npm start, go to:
http://localhost:3000/addUser?name=test

I use [moment-timezone](https://www.npmjs.com/package/moment-timezone) to change the timezone and set a default one.

It will give something like the following:
```js
{
  "createdUser": {
    "id": 1,
    "name": "test",
    "dateAdded": "2019-08-13T00:40:00.780Z"
  },
  "dateTimeNowTz": "2019-08-13T09:40:00.78+09:00"
}
```

The property `createdUser` shows the values returned from the database. Notice how the time is in UTC (00:40:00) although it was sent to the database in another timezone.
Meanwhile, the property `dateTimeNowTz` shows the value of the current time inside the app in Asia/Tokyo timezone (09:40:00), which is the value sent to the [dao](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js) before the dao converted it to UTC.

My proposal is that dao conversion should by default still convert to UTC, but if a timezone is mentioned in the datasource file, then it should honour the mentioned timezone rather than the UTC default.

To see how the data is retrieved go to: http://localhost:3000/users
The data is retrieved as is.
```js
[{
  "id": 1,
  "name": "test",
  "dateAdded": "2019-08-13T00:40:78.000Z"
}]
```

Note:
I'm using MySQL. The app is connected to a free public MySQL database which you can use right away, though it is not always reliable. Here's the MySQL table needed:
```sql
CREATE TABLE `User` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(11) DEFAULT NULL,
  `dateAdded` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;
```

**Comment by dougal83** [comment]
@shadyanwar Hey! Out of curiosity, how do dates behave if you set `process.env.TZ = 'Asia/Tokyo'`?  I think you should then be able to use features like `toLocaleTimeString()`.

**Comment by shadyanwar** [comment]
@dougal83 Thanks for the great suggestion.

In package.json, I have added "TZ" to the "start" script as follows:
`TZ=\"Asia/Tokyo\" `
so now it is:
`"start": "TZ=\"Asia/Tokyo\" node -r source-map-support/register .",`

This has affected the conversion behavior so whenever a new Date() is stored in the database, it is stored in the database with the timezone I have set above (toLocaleTimeString() is not needed in case of storing).

For data retrieval, it is converted to UTC by default (even though it is saved in the database in my chosen timezone). However, if date.toLocaleTimeString() is used on **every value**, or alternatively setting a default with moment.tz.setDefault("Asia/Tokyo") at the beginning then just applying the moment to the date, like moment(date).format('YYYY-MM-DDTHH:mm:ss.SSZ'), then everything works as desired.

Anyway, I believe this is an ok situation. The only catch is that developers have to be wary of any date returned from the database before showing it in the response. They have to **manually convert** it to their local timezone (using either toLocaleDateString() & toLocaleTimeString(), or the moment-timezone package which works nicely). In many cases, this will mean looping through all values and reformatting them.

However, it would be **ideal** if the time is returned by default in the selected timezone, the timezone set at the start of the node app in the TZ environment variable.

So I still propose that if a timezone is mentioned in the datasource file, then values fetched from db that are defined in the app as the types Date would be converted to the the mentioned timezone rather than the UTC default.

**Comment by bajtos** [comment]
Sorry for not coming back to this conversation earlier. Dates, times and timezones are notoriously difficult to handle properly, double so in JavaScript.

In the past, we have had a long discussion around timezones in MySQL in the following GH issue, you may find some relevant information there too: https://github.com/strongloop/loopback-connector-mysql/issues/149 The pull request  https://github.com/strongloop/loopback-connector-mysql/pull/257 should have improved the handling of time/date values by our MySQL connector.

I am afraid I don't have bandwidth to look into this issue in more details :( If you can come up with an actionable proposal (a pull request would be even better), then I am happy to provide feedback.

**Comment by bajtos** [comment]
Can we perhaps start by documenting the current behavior and best practices (like setting `TZ` env var)?

**Comment by thuthuatna** [comment]
i have problem too
