### ISSUE TITLE
Run repository tests for PostgreSQL

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3436]
Add `acceptance/repository-postgresql` package, modeled after MySQL tests in `acceptance/repository-mysql`. The tests should be run as a new Travis CI job, see the existing setup for other connectors.

See also https://github.com/strongloop/loopback-next/pull/3387

## Acceptance criteria

- [ ] A new directory `acceptance/repository-postgresql` running all CRUD tests from `repository-tests` packages
- [ ] A new matrix entry in Travis CI config to run PostgreSQL tests as part of our CI builds
- [ ] All tests are passing

**Comment by agnes512** [comment]
see @emonddr for help :D
