### ISSUE TITLE
Reject create/update requests when data contains navigational properties

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3439]
## Suggestion

When the client attempts to create or update a model and related models in a single call, then we should reject such requests with a helpful error message explaining the problem.

## Acceptance criteria

Step 1:

- [ ] Introduce a new protected method `DefaultCrudRepository.fromEntity`.
- [ ] Update repository methods to call `fromEntity` whenever we need to convert LB4 Entity into data to be passed to juggler's PersistedModel.
- [ ] This new method is an extension point for app & extension developers, it complements already existing `toEntity` method and provides functionality similar to LB3 Operation Hook `persist`.

Step 2:

- [ ] Modify `fromEntity` to detect navigational properties in data and throw a helpful error.

See #3387 and https://github.com/strongloop/loopback-next/commit/5beb7b93a3d1ce1077538bed39abfa31c309eba0 in particular.

**IMPORTANT** In the spike, `fromEntity` is accepting options allowing the caller to decide how to treat navigational properties (`relations?: true | false | 'throw'`). Based on the discussion we had, this is not what we want to implement. Instead, we want `fromEntity` to ALWAYS REJECT navigational properties.

**Comment by jannyHou** [comment]
estimation meeting discussion:
- `toEntity` converts a JSON object(from the database) to an entity class instance 
- maybe we should think of a better name for the function `fromEntity`, it should do the reverse vs `toEntity`, then we should put the rejection logic outside the function.
- some proposal: name it as `ensurePersistable`, the function makes sure the data doesn't contain non-persistent data.

**Comment by agnes512** [comment]
closing as done
