### ISSUE TITLE
UML generator for loopback-next

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#345]
## Description

It would be better to have a UML generator for a project that written in typescript, since it's the straightforward doc to tell users how our interfaces/classes get integrated.

e.g. `loopback-next/repository/src/model.ts`:
![screen shot 2017-06-07 at 1 15 23 pm](https://user-images.githubusercontent.com/12554153/26891606-a00e533c-4b83-11e7-9e9d-4721f35cbc8f.png)

## Tool

I find an open source one https://github.com/joaompneves/tsviz, but seems it could not generate UML across different files properly, or maybe I haven't figured out the correct way to use it.

## Advantage

Every time we add an interface/class, we just run the tool to generate a new UML which helps people quickly understand what it does and how to use it.

## Challenge

Need to either find a good generator or create our own one.

**Comment by alemhnan** [comment]
We have created this component that does something similar: https://github.com/redbabel/loopback-component-model-diagram

Here an example: http://redmongo-staging.herokuapp.com/modeldiagram/

http://www.nomnoml.com is being used to render the UML like graph

**Comment by raymondfeng** [comment]
Some prior arts for LB models:

https://github.com/yantrashala/loopback-component-visualizer
https://github.com/raymondfeng/loopback-model-visualizer

**Comment by dhmlau** [comment]
Can be an extension contributed by the community. 
Related to #461

**Comment by bajtos** [comment]
I am closing this issue because we are not going to have time to work on this in the next 6-9 months. However, we are happy to accept a pull request contributing this feature.
