### ISSUE TITLE
Add inclusion resolvers to `lb4 relation` CLI

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3451]
At the moment, `lb4 relation` initializes the factory for relation repository. We need to enhance this command to register the inclusion resolver too.

See also https://github.com/strongloop/loopback-next/pull/3387

## Acceptance criteria

- [ ] Implementation & tests for all relations supported by `lb4 relation`
- [ ] Update `repository` template

**Comment by agnes512** [comment]
Closing as done.
