### ISSUE TITLE
Recursive inclusion of related models

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3454]
In LB3, it's possible to recursively include models related to included models. Let's implement that feature in LB4 too.

For example, consider the domain model where `Author` has many `Post` instances and each `Post` instance has many `Comment` instances.

Users can fetch authors with posts and comments using the following query:

```ts
userRepo.find({
  include: [
    {
      relation: 'posts',
      scope: {
        include: [{relation: 'comments'}],
      },
    },
  ],
});
```

LB3 also offer few simpler alternatives how to express the same query:

```ts
userRepo.find({include: {posts: 'comments'}});
userRepo.find({include: {posts: {relation: 'comments'}}});
```

LB3 test suite:
[loopback-datasource-juggler/test/include.test.js#L175-L195](https://github.com/strongloop/loopback-datasource-juggler/blob/f0a6bd146b7ef2f987fd974ffdb5906cf6a584db/test/include.test.js#L175-L195)

See also https://github.com/strongloop/loopback-next/pull/3387

## Acceptance criteria

TBD - will be filled by the team.

**Comment by st119848** [comment]
waiting for this feature

**Comment by eyasalmamoun** [comment]
Plus one

**Comment by upscreen** [comment]
let me know if we can contribute

**Comment by marioestradarosa** [comment]
@upscreen , it would be nice to have your contribution.

See our [Contributing guide](https://loopback.io/doc/en/lb4/code-contrib-lb4.html) and [Submitting a pull request to LoopBack 4](https://loopback.io/doc/en/lb4/submitting_a_pr.html) to get started.

**Comment by malek0512** [comment]
Waiting for this feature also.
Is there any progress ?

**Comment by raymondfeng** [comment]
@agnes512 Can you clarify?

**Comment by agnes512** [comment]
@malek0512 @st119848 @eyasalmamoun @upscreen I think this is being done in the issue https://github.com/strongloop/loopback-next/issues/3453 and the PR https://github.com/strongloop/loopback-next/pull/4263. The documentations can be found in the [Query multiple relations](https://loopback.io/doc/en/lb4/HasMany-relation.html#query-multiple-relations) section of each relation.

@raymondfeng from the description, I think the feature is already implemented, and I didn't realize until you ping me, thanks. Closing it.

**Comment by tcmal** [comment]
Is there any way to include nested relationships infinitely/to N degrees using this? For example,

```ts
@model()
export class Comment extends Entity {
	// ...

	@hasMany(() => Comment, {keyTo: 'replyTo'})
	replies: Comment[];
```

My current attempt is:

```ts
let scopeRecurse: any = {relation: "replies", scope: {}};
scopeRecurse.scope.include = [scopeRecurse];

const filter: Filter = {
	// ...
	include: [scopeRecurse]
}

const comments: CommentWithRelations[] = await this.postRepository.comments(id).find(filter);
```

but this only includes the first level.

Ideally there would be some sort of option for recursive relationships, ie `{relation: "replies", depth: 10}`.

**Comment by malek0512** [comment]
@tcmal you can actually include multiple nested relations with the same fashion thanks to the scope field. 
See example below :
`filter = {include:[{relation: "replies", scope:{ include: [{relation: "nestedRelation"}] } }, etc..]`
See also documentation [here](https://github.com/strongloop/loopback-next/blob/master/docs/site/HasMany-relation.md#query-multiple-relations)

**Comment by tcmal** [comment]
Yes, that's what I'm trying to do, except the same relation nested an infinite amount of times.

So comments have many replies, what I'm trying to do is fetch a comment, its replies, its replies' replies, its replies' replies' replies, etc. until there's no more replies.

The code I posted is the same as what you posted, is a trick to essentially get:

```js
let scopeRecurse = {relation: "replies", scope: {include: [scopeRecurse]}
```

If you try to access each level you get:

```js
scopeRecurse.relation // replies
scopeRecurse.scope.include[0].relation // replies
scopeRecurse.scope.include[0].relation // replies
scopeRecurse.scope.include[0].scope.include[0].relation // replies
```

However many levels deep you go. I'd expect this to fetch replies for every comment fetched by the query, no matter how many levels deep, but instead it only fetches the first level of replies.

**Comment by agnes512** [comment]
@tcmal we don't support recursive inclusion in such form `{relation: "replies", depth: 10}`. But it should be able to traverse nested relations even the relation name is the same as long as the foreign key is set up correctly. I will check on my end to see if it only fetches the first level of replies in your case.

**Comment by agnes512** [comment]
I just tried it on my end, and it seems work. 
My model:
```ts
  @property({
    type: 'number',
    id: true,
    generated: true,
  })
  id: number;

  @property({
    type: 'string',
  })
  cotent?: string;

  @hasMany(() => Comment)
  replies: Comment[];

  @property({
    type: 'number',
  })
  commentId?: number;
```
My repository:
```ts
export class CommentRepository extends DefaultCrudRepository<
  Comment,
  typeof Comment.prototype.id,
  CommentRelations
  > {

  public readonly replies: HasManyRepositoryFactory<Comment, typeof Comment.prototype.id>;

  constructor(
    @inject('datasources.db') dataSource: DbDataSource,
  ) {
    super(Comment, dataSource);
    this.replies = this.createHasManyRepositoryFactoryFor('replies', Getter.fromValue(this));
    this.registerInclusionResolver('replies', this.replies.inclusionResolver);
  }
}
```
With filter: 
```
    const fil = {
      where: {id: 1},
      include: [
        {
          relation: 'replies',
          scope: {
            include: [{relation: 'replies'}],
          },
        },
      ],
    };
```
I got the expected result.

I am not sure if something's wrong with `let scopeRecurse = {relation: "replies", scope: {include: [scopeRecurse]}`

**Comment by tcmal** [comment]
I might not be explaining myself right.

I have data:

```json
{
      "1": "{\"content\":\"a\",\"commentId\":1}",
      "2": "{\"replyTo\":1,\"content\":\"b\",\"commentId\":2}",
      "3": "{\"replyTo\":2,\"content\":\"c\",\"commentId\":3}",
      "4": "{\"replyTo\":3,\"content\":\"d\",\"commentId\":4}",
      "5": "{\"replyTo\":4,\"content\":\"e\",\"commentId\":5}",
      "6": "{\"replyTo\":5,\"content\":\"f\",\"commentId\":6}",
}
```

In this case I'm expecting it to return all 6 of those comments, but when I try your example it only returns up to c:

```
{
  "commentId": 1,
  "content": "a",
  "replies": [
    {
      "replyTo": 1,
      "commentId": 2,
      "content": "b",
      "replies": [
        {
          "userName": "tcmal",
          "replyTo": 2,
          "commentId": 3,
          "content": "c",
        }
      ]
    }
  ],
}
```

**Comment by agnes512** [comment]
Sorry I didn't make it clear. The example I have above is to check if it works well with nested relations. And it does.

As for recursively querying the related data, we currently don't support such a recursive way due to the current design. i.e you will need to write the filter yourself to query a certain levels of relations. The filter above is an example that queries two levels of `replies`. 

For your case, you need to set the `scope` field to include the next level `replies` several times. It might look like this eventually:
```
{
      // where: {id: 1},
      include: [
        {
          relation: 'replies',
          scope: {
            include: [{relation: 'replies',
            scope: {
              include: [{relation: 'replies',
              scope: {
                include: [{relation: 'replies',
                ... include more nested relations ...}],
              },}],
            }}],
          },
        },
      ],
    };
```

**Comment by tcmal** [comment]
Would it be possible to have this implemented? At the very least as a helper function that returns the nested struct:

```js
let atEachLevel = {relation: "replies"}
let root = {...atEachLevel};
let currentNode = root;
for (let n = 0; n < maxDepth; n++) {
	currentNode.scope = {include: [{...atEachLevel}]};
	currentNode = currentNode.scope.include[0];
}
```

**Comment by agnes512** [comment]
@tcmal I think your use case is valid. I've created a story for it, see https://github.com/strongloop/loopback-next/issues/5080. Feel free to join the discussion ( or submit a PR :D ). Thanks!
