### ISSUE TITLE
Controller method params description

### ISSUE THREAD

**Issue by ludohenin** [strongloop/loopback-next#3457]
## Suggestion

I'm looking for a way to describe the Controller methods params so that they are document in the generated spec.

```ts
class MyController {
  @get('/data')
  getData(
    @params.query.object('condition', schema, {
      description: 'Super usefull query param' // add here request param info
    }) cond: object
  ) {
    // return data;
  }
}
```

Btw, haven't found any ways to do even setting it in `api` controller decorator doesn't seems to work.

```ts
@api({
  paths: {
    '/data': {
      get: {
        parameters: [
          {
            name: 'search',
            in: 'query',
            description: 'search object',
          },
        ],
      },
    },
  },
})
```

![image](https://user-images.githubusercontent.com/1011516/61944766-bcdffc00-af9e-11e9-88f6-cdcb36b83cb8.png)

**Comment by raymondfeng** [comment]
You can use `@param`, such as:
```ts
@param({
      name: 'search',
      in: 'query',
      style: 'deepObject',
      description: 'search object',
      schema: getFilterSchemaFor(Customer),
    })
```

**Comment by raymondfeng** [comment]
FYI - I'm improving these shortcut decorators to accept an optional object for additional properties for the parameter. See https://github.com/strongloop/loopback-next/pull/3461.
