### ISSUE TITLE
Expose `isActive()` method in Transaction interface

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#3471]
## Steps to reproduce

Coming from https://github.com/strongloop/loopback-next/pull/3397#discussion_r308600347. We need to expose an API for transactions in LB4 to check if a transaction is active or not.

## Acceptance Criteria
- [x] Create a `isActive` method in `loopback-connector` that checks if the connection object on a transaction is present or not, thus indicating if transaction itself is active. Add unit tests to verify the behaviour and release a new minor version of the module.
- [x] Include the method definition in `Transaction` interface in loopback-next and use it in tests and `before/after` hooks to check if transactions are active

**Comment by jannyHou** [comment]
closing since all related PR merged. And see the postgresq follow-up story in https://github.com/strongloop/loopback-connector-postgresql/issues/411
