### ISSUE TITLE
lb4 discover does not work with ts files

### ISSUE THREAD

**Issue by SouthRibbleTech** [strongloop/loopback-next#3477]
When you use lb4 datasource it creates the files in /src/datasources/*.ts

However lb4 discover requires that the datasource be in /dist/datasources/*.js

You can not simply rename ts to js

How do you manually create .js datasource files, is there any documentation, I can't find any.

**Comment by godartm** [comment]
Im not sure if i have understand right the issue but did you try this command ?
```
npm run build
```

**Comment by dhmlau** [comment]
@agnes512 @nabdelgadir , could you please take a look? Thanks.

**Comment by dhmlau** [comment]
@SouthRibbleTech, `lb4 discover` command requires the LoopBack 4 project to be built first, so as @godartm suggested, you need to run `npm run build` before running the discovery command.

**Comment by dhmlau** [comment]
@SouthRibbleTech, we believe we've answered your question, so I'm closing this issue.  If you still have questions, please ping me here and I can reopen the issue. Thanks.
