### ISSUE TITLE
Unable to create a related model

### ISSUE THREAD

**Issue by bhupesh-sf** [strongloop/loopback-next#3480]
## Steps to reproduce

1. Create a new LB4 app.
2. Create 2 models employee and employee-salary-packages
3. use LB4 relation command from CLI to define hasMany relation between employee and employee-salary-packages models.
4. Now try to create employee-salary-packages and it throws an exception. 

Following are the models and the request:

## Employee Model
```js
import { model, property, hasMany } from '@loopback/repository';
import { UserModifiableEntity } from '.';
import { Location } from '../modules/employee/location.enum';
import { EmployeeStatus } from '../modules/employee/employee-status.enum';
import { EmployeeSalaryPackage } from './employee-salary-package.model';

@model({ settings: {} })
export class Employee extends UserModifiableEntity {
  @property({
    type: 'number',
    id: true,
  })
  id?: number;

  @property({
    type: 'string',
    required: true,
  })
  name: string;

  @property({
    type: 'string',
    required: true,
  })
  code: string;

  @property({
    type: 'number',
    required: true,
  })
  department_id: number;

  @property({
    type: 'number',
    required: true,
  })
  designation_id: number;

  @property({
    type: 'string',
    required: true,
    default: 'current',
  })
  status: EmployeeStatus;

  @property({
    type: 'string',
  })
  jira_id?: string;

  @property({
    type: 'boolean',
  })
  is_billable?: boolean;

  @property({
    type: 'date',
    required: true,
  })
  joining_date: string;

  @property({
    type: 'date',
  })
  relieving_date?: string;

  @property({
    type: 'string',
    required: true,
  })
  location_id: Location;

  @hasMany(() => EmployeeSalaryPackage, { keyTo: 'employee_id' })
  employeeSalaryPackages: EmployeeSalaryPackage[];

  constructor(data?: Partial<Employee>) {
    super(data);
  }
}

export interface EmployeeRelations {
  // describe navigational properties here
}

export type EmployeeWithRelations = Employee & EmployeeRelations;
```

## Employee Salary Package model
```js
import { model, property } from '@loopback/repository';
import { UserModifiableEntity } from '.';
import { Currency } from '../modules/employee/currency.enum';

@model({ settings: {} })
export class EmployeeSalaryPackage extends UserModifiableEntity {
  @property({
    type: 'number',
    id: true,
  })
  id?: number;

  @property({
    type: 'number',
    required: true,
  })
  employee_id: number;

  @property({
    type: 'number',
    required: true,
  })
  current_package: number;

  @property({
    type: 'string',
    required: true,
  })
  currency: Currency;

  @property({
    type: 'string',
    required: true,
  })
  effective_date: string;

  @property({
    type: 'string',
  })
  end_date?: string;

  @property({
    type: 'number'
  })
  monthly_cost: number;

  @property({
    type: 'number'
  })
  hourly_cost: number;

  constructor(data?: Partial<EmployeeSalaryPackage>) {
    super(data);
  }
}

export interface EmployeeSalaryPackageRelations {
  // describe navigational properties here
}

export type EmployeeSalaryPackageWithRelations = EmployeeSalaryPackage & EmployeeSalaryPackageRelations;
```

## Employee Repository
```js
import { Employee, EmployeeRelations, EmployeeSalaryPackage } from '../models';
import { PgdbDataSource } from '../datasources';
import { Getter, inject } from '@loopback/core';
import { DefaultUserModifyCrudRepository } from './default-user-modify-crud.repository.base';
import { AuthenticationBindings } from 'loopback4-authentication';
import { AuthUser } from '../modules/auth';
import { repository, HasManyRepositoryFactory } from '@loopback/repository';
import { EmployeeSalaryPackageRepository } from './employee-salary-package.repository';

export class EmployeeRepository extends DefaultUserModifyCrudRepository<
  Employee,
  typeof Employee.prototype.id,
  EmployeeRelations
  > {

  public readonly employeeSalaryPackages: HasManyRepositoryFactory<EmployeeSalaryPackage, typeof Employee.prototype.id>;

  constructor(
    @inject('datasources.pgdb') dataSource: PgdbDataSource,
    @inject.getter(AuthenticationBindings.CURRENT_USER)
    protected readonly getCurrentUser: Getter<AuthUser | undefined>, @repository.getter('EmployeeSalaryPackageRepository') protected employeeSalaryPackageRepositoryGetter: Getter<EmployeeSalaryPackageRepository>,
  ) {
    super(Employee, dataSource, getCurrentUser);
    this.employeeSalaryPackages = this.createHasManyRepositoryFactoryFor('employeeSalaryPackages', employeeSalaryPackageRepositoryGetter,);
  }
}
```

## Request I made
```js
http://localhost:3000/employees/1/employee-salary-packages`
`{
  "current_package": 3000,
  "currency": "USD",
  "effective_date": "2019-07-31",
  "end_date": "2019-07-31"
}
```
**Curl Request:**
`curl -X POST "http://localhost:3000/employees/1/employee-salary-packages" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"current_package\":3000,\"currency\":\"USD\",\"effective_date\":\"2019-07-31\",\"end_date\":\"2019-07-31\"}"`

## Current Behavior

It throws an exception rather to create a record.
```js
{
  "error": {
    "statusCode": 422,
    "name": "UnprocessableEntityError",
    "message": "The request body is invalid. See error object `details` property for more info.",
    "code": "VALIDATION_FAILED",
    "details": [
      {
        "path": "",
        "code": "required",
        "message": "should have required property 'employee_id'",
        "info": {
          "missingProperty": "employee_id"
        }
      }
    ]
  }
}
```

## Expected Behavior

It says **employee_id** is required which is true for the salary package model as its the foreign key but the same has been passed as part of URL itself. So my expectation is that it need not be passed in the body also. I should have been able to create the new entry for salary package.

## Additional information
Os: linux x64 
Node version: 10.13.0

├── @loopback/boot@1.4.6
├── @loopback/context@1.21.0
├── @loopback/core@1.8.7
├── @loopback/openapi-v3@1.9.0
├── @loopback/repository@1.10.0
├── @loopback/rest@1.16.5
├── @loopback/rest-explorer@1.3.0
├── @loopback/service-proxy@1.2.7
├── loopback-connector@4.8.0
├── loopback-connector-kv-redis@3.0.1
├── loopback-connector-postgresql@3.7.0
├── loopback4-authentication@2.1.3
├── loopback4-authorization@2.3.2
└── loopback4-soft-delete@1.2.0

**Comment by dhmlau** [comment]
@agnes512 @nabdelgadir , could you please take a look? Thanks.

**Comment by agnes512** [comment]
@bhupesh-sf Hi! I tried to fix it in my PR. Could you try them out to see if it resolves your problem? Thanks!

**Comment by nabdelgadir** [comment]
@bhupesh-sf hi so as @agnes512 said, you can try the fix she implemented in her PR.

In your case, in the `employee-employee-salary-package.controller.ts` file, find the `create` method:
```ts
async create(
  @param.path.number('id') id: typeof Employee.prototype.id,
  @requestBody({
    content: {
      'application/json': {
       // notice the following line
        schema: getModelSchemaRef(EmployeeSalaryPackage, {exclude: ['id']}),
      },
    },
  })
  employeeSalaryPackage: Omit<EmployeeSalaryPackage, 'id'>,
): Promise<EmployeeSalaryPackage> {
  return this.employeeRepository
    .employeeSalaryPackages(id)
    .create(employeeSalaryPackage);
}
```

In the `getModelSchemaRef` function, modify the second argument from
```ts
getModelSchemaRef(EmployeeSalaryPackage, {exclude: ['id']})
```
 to 
```ts
getModelSchemaRef(EmployeeSalaryPackage, {exclude: ['id'], optional: ['employee_id'})
```

Let us know if this helps, thanks!

**Comment by bhupesh-sf** [comment]
@agnes512 @nabdelgadir I tried the solution, it fix one thing that it doesn't gives the model validation error which I already achieved by putting **employee_id** in exclude list itself along with id. But the main problem is that in DB this foreign key is mandatory as employee_salary_package is child of employee and I still need to extract employee_id from the request and add it to data being sent to repository to create.

Following is the code I have done for create function:

`async create(
    @param.path.number('id') employee_id: typeof Employee.prototype.id,
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(EmployeeSalaryPackage, { exclude: ['id', 'employee_id'] }),
        },
      },
    }) employeeSalaryPackage: Omit<EmployeeSalaryPackage, 'id'>,
  ): Promise<EmployeeSalaryPackage> {
    employeeSalaryPackage.employee_id = employee_id!;
    return await this.employeeRepository.employeeSalaryPackages(employee_id).create(employeeSalaryPackage);
  }`

Expectation is this should be done automatically.

By the way I have approved the PR but now I am realising more work is required. I have also put a comment in PR.

**Comment by agnes512** [comment]
@bhupesh-sf Hi! and yes, the change I made in [the PR](https://github.com/strongloop/loopback-next/pull/3495) is to have the foreign key passed in the request body automatically. For your case, it would attach `customerId` to `optional`, so that you don't have to pass the value again in the request body. (we will need to discuss to have the fk inside of `optional` or `exclude` with the team)

As for:
> But the main problem is that in DB this foreign key is mandatory as employee_salary_package is
> child of employee and I still need to extract employee_id from the request and add it to data
> being sent to repository to create.

I am not sure if I understand it correctly. Do you mean that the `employee-employee-salary-package.controller` doesn't create a salary instance for you in the db? 
I tried it with `in-memory` db and `mySQL`, it creates a new `salary-package` instance with the foreign key `employeeId` in both databases. And I don't need to  "extract employee_id from the request and add it to data being sent to repository to create".
```ts
My salary-package table in MySQL
+----+------------+
| id | employeeId |
+----+------------+
|  1 |          1 |
|  2 |          1 |
+----+------------+
```
I don't know if my example addresses your questions. Please let me know if it doesn't. It would be helpful if you could provide more details/steps to reproduce it. Thanks!

**Comment by bhupesh-sf** [comment]
Hey @agnes512 Yes its working. I am not sure why it throw error earlier. It could be the reason that I was trying by putting **employee_id** in exclude list rather than optional list. Seems like exclude list make the elements excluded from the request body. Not sure.

Anyways thanks for all the help. Now closing this issue.
