### ISSUE TITLE
REST DataSource Header Authorization Basic Example

### ISSUE THREAD

**Issue by jonathan-silva** [strongloop/loopback-next#3492]
I can't create a REST datasource service of type post, which goes in the Authorization Basic header

@loopback/cli version: 1.20.0

@loopback/* dependencies:
  - @loopback/authentication: ^2.1.7
  - @loopback/boot: ^1.4.6
  - @loopback/build: ^2.0.5
  - @loopback/context: ^1.21.0
  - @loopback/core: ^1.8.7
  - @loopback/metadata: ^1.2.7
  - @loopback/openapi-spec-builder: ^1.2.7
  - @loopback/openapi-v3: ^1.9.0
  - @loopback/repository-json-schema: ^1.9.1
  - @loopback/repository: ^1.10.0
  - @loopback/rest: ^1.16.5
  - @loopback/testlab: ^1.7.1
  - @loopback/docs: ^1.27.0
  - @loopback/example-hello-world: ^1.2.7
  - @loopback/example-log-extension: ^1.2.7
  - @loopback/example-rpc-server: ^1.2.7
  - @loopback/example-todo: ^1.7.0
  - @loopback/example-soap-calculator: ^1.6.8
  - @loopback/service-proxy: ^1.2.7
  - @loopback/http-caching-proxy: ^1.1.7
  - @loopback/http-server: ^1.4.6
  - @loopback/example-todo-list: ^1.9.0
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^1.3.0
  - @loopback/eslint-config: ^2.0.2
  - @loopback/example-express-composition: ^1.5.0
  - @loopback/example-greeter-extension: ^1.3.7
  - @loopback/booter-lb3app: ^1.2.7
  - @loopback/example-lb3-application: ^1.1.7
  - @loopback/example-greeting-app: ^1.1.7
  - @loopback/example-context: ^1.2.7
  - @loopback/repository-tests: ^0.3.0

*** datasource

![image](https://user-images.githubusercontent.com/25329651/62301241-96aed600-b44e-11e9-8c79-d3a004b4cef3.png)

** service

![image](https://user-images.githubusercontent.com/25329651/62301301-ba721c00-b44e-11e9-8fed-21a039455fab.png)

** controller

![image](https://user-images.githubusercontent.com/25329651/62301366-dd9ccb80-b44e-11e9-8917-0f2d666310fe.png)

Could you send me an example of REST service, where the datasource of type post where the Authorization Basic {token} ??

**Comment by raymondfeng** [comment]
The header name should be `authorization` instead of `authentication`. You also turn it into a variable so that it can be passed in via the method call.

**Comment by jonathan-silva** [comment]
@raymondfeng 
I made change ...

![image](https://user-images.githubusercontent.com/25329651/62312947-dd5bfa80-b465-11e9-9197-c5cb9e59e697.png)
and gave following error in the log
![image](https://user-images.githubusercontent.com/25329651/62312824-940bab00-b465-11e9-8ba3-10f8e4d02c5f.png)

Thanks for listening

**Comment by raymondfeng** [comment]
See https://loopback.io/doc/en/lb3/REST-connector.html#configure-options-for-request. You can set `strictSSL` to `false` in the datasource config.

**Comment by jonathan-silva** [comment]
@raymondfeng  Thank you very much brother! It worked here
