### ISSUE TITLE
The documentation is not updated

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#3501]
The documentation in loopback.io is not being updated according to this repository

**Comment by frbuceta** [comment]
To have the updated version I have done:

* `npm ci` in the repository root
* `npm run build:site` WATCH OUT! [bundler](http://bundler.io) must be installed
* then I have run `npm start` in `/sandbox/loopback.io`

**Comment by dhmlau** [comment]
Closing as resolved because PR #3502 has landed. @frbuceta, thanks for your contribution!

**Comment by frbuceta** [comment]
The page is still not updated

**Comment by dhmlau** [comment]
@frbuceta , my apologies. I thought your PR is fixing the issue you're complaining.  Do you have the link of the documentation?  And are you interested in submitting a PR for that? Thanks.

**Comment by frbuceta** [comment]
No problem. For example `https://loopback.io/doc/en/lb4/Model.html` not equal to `loopback-next/docs/site/Model.md`

I really don't know what the problem is ... I guess you'll have this automated and it won't be working properly

**Comment by raymondfeng** [comment]
For some reason, the build does not pick up latest version of `@loopback/docs` and reverted my manual updates.

**Comment by dhmlau** [comment]
It should be in sync now.

**Comment by frbuceta** [comment]
Yes, now, yes
Good job guys;)
