### ISSUE TITLE
Show HTTP request info

### ISSUE THREAD

**Issue by jonathan-silva** [strongloop/loopback-next#3513]
How do I show HTTP request information ?

I need to get some information that is within a request, status, authorization, among other things, as it would be, and would have any examples?

Thank you very much in advance

**Comment by hacksparrow** [comment]
The HTTP request object is accessible from controllers. For example, you can modify `src/controllers/ping.controller.ts` to `console.log` the request object:

```ts
export class PingController {
  constructor(@inject(RestBindings.Http.REQUEST) private req: Request) {}

  // Map to `GET /ping`
  @get('/ping', {
    responses: {
      '200': PING_RESPONSE,
    },
  })
  ping(): object {
    console.log(this.req);
    // Reply with a greeting, the current time, the url, and request headers
    return {
      greeting: 'Hello from LoopBack',
      date: new Date(),
      url: this.req.url,
      headers: Object.assign({}, this.req.headers),
    };
  }
}
```
