### ISSUE TITLE
Can't filter on foreign key field for api calls 

### ISSUE THREAD

**Issue by giltee** [strongloop/loopback-next#3527]
## Steps to reproduce

I have a classic simple User, Transaction models that I have setup with relationships to link the models (using mongoDB). I followed the docs on the loopback website and was successful in getting posts sent over.

Now I have found that for some reason the foreign key field is not filterable by the client but every other field seems to work. When I filter for a specific userId it just returns an empty array:

`https://event-api.webmeau.ca/transactions?filter={"where":{"userId":"5d4c9f199d3cf16476a62d68"}}
`
But when I filter for any other field, such as:
`https://event-api.webmeau.ca/transactions?filter={"where":{"id":"tok_1F516qKCLPFi6h8hKYatdRok"}}`

the API the results are returning correctly. I am copy pasting over the inputs from the /transactions get API so I know that they are correct. Plus if the value was incorrect it would throw a 404 when I was trying to request that url. 

## Expected Behavior

All the transactions with the associated userId are filterable, I don't want to send unnessary data over https and filter on the client, that is just silly. 

## Link to reproduction sandbox

https://event-api.webmeau.ca/transactions 

## Additional information

I did set up the relationships using the second option recommended in the documents, not sure if that's an issue or not:

`  @belongsTo(() => User)
  userId: string;
`

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by temp3l** [comment]
same here

**Comment by nflaig** [comment]
@giltee @temp3l 
there are two options to resolve this:

**Option 1**: In the `find()` method set `strictObjectIDCoercion` to `true` e.g `find(filter, {strictObjectIDCoercion: true})`

**Option 2**: Update [loopback-connector-mongodb](https://www.npmjs.com/package/loopback-connector-mongodb) to the latest version (v5.0.0) which stores the foreign keys as `ObjectId` instead of `String` which should fix the issue and `strictObjectIDCoercion` is not needed.

**Comment by giltee** [comment]
So neither of those options worked for me... I also tried the updated documentation that is now on the loopback site and it's also not working. The tutorial shows how to get orders by order id and not by customer which really isn't what I would think it's trying to do. Going to keep playing around but this really shouldn't be so difficult. Is there an actual working example somewhere...?

**Comment by giltee** [comment]
so noSql belongs to doesn't work properly: 

https://github.com/strongloop/loopback-next/issues/2341 

And you can't filter data from the client using url parameters. How on earth is this supposed to be scalable?

**Comment by giltee** [comment]
I also tried to follow the shopping cart loopback example:

```
@get('/users/{userId}/transactions', {
    responses: {
      '200': {
        description: "Array of User's Orders",
        content: {
          'application/json': {
            schema: {type: 'array', items: {'x-ts-type': Transactions}},
          },
        },
      },
    },
  })
  async findTransactions(
    @param.path.string('userId') userId: string,
    @param.query.string('filter') filter?: Filter<Transactions>,
  ): Promise<Transactions[]> {
    console.log('UID & filter: ', userId, filter);
    const orders = await this.userRepository.transactions(userId).find(filter);
    return orders;
  }

```
And it also returns an empty array....

**Comment by bajtos** [comment]
The most likely source of the problem is that the value used by the query and the value stored in the database don't have the same type - one is a string and another is an ObjectID.

Can you try to define your relation as follows please?

```ts
@belongsTo(
  () => User,
  // additional relation metadata
  {},
  // property definition
  {
    type: 'string', 
    mongodb: {dataType: 'ObjectID'},
  }
)
userId: string;
```

**Comment by bajtos** [comment]
Also, can you provide us with a small app we can use to reproduce and debug the problem? See https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs
