### ISSUE TITLE
app.restServer.url is undefined

### ISSUE THREAD

**Issue by diego92sigma6** [strongloop/loopback-next#3534]
Hi, I'm currently having this issue. I'm not sure how to deal with it since the configuration is seemingly right

## Steps to reproduce

Run the app normally using *npm start*
With the following code on index.ts: (pretty sure those binds shouldn't affect the issue (right?))

```js
export async function main(options: ApplicationConfig = {}) {
    options.rest.host = 'http://localhost';
    options.rest.port = 3001;
    const app = new PollerV0Application(options);

    // Configuración de poller
    app.bind('datasources.Main').toClass(MainDataSource);
    app.bind('task-result.repository').toClass(TaskResultRepository);
    app.bind('poller-scheduler').toClass(PollerScheduler);
    await app.get('poller-scheduler');

    //Configura el socket de envió de datos del dashboard
    app.bind('repositories.TaskResultRepository').toClass(TaskResultRepository);
    app.bind('task-result.controller').toClass(TaskResultController);
    app.bind('dashboard-socket-server').toClass(DashboardSocketServer);
    await app.get('dashboard-socket-server');

    setTimeout(()=> {
        while (!app.restServer.listening);
        //never reached; is this right?
        console.log('Started listening')
    }, 0);

    const url = app.restServer.url;
    console.log(`Server is running at ${url}`);
    console.log(`Try ${url}/heartbeats`);
    return app;
}
```

code in application.ts (not touched):

```js
export class PollerV0Application extends BootMixin(
    ServiceMixin(RepositoryMixin(RestApplication)),
) {
    constructor(options: ApplicationConfig = {}) {
        super(options);


        // Set up the custom sequence
        this.sequence(MySequence);

        // Set up default home page
        this.static('/', path.join(__dirname, '../public'));

        // Customize @loopback/rest-explorer configuration here
        this.bind(RestExplorerBindings.CONFIG).to({
            path: '/explorer',
        });
        this.component(RestExplorerComponent);

        this.projectRoot = __dirname;
        // Customize @loopback/boot Booter Conventions here
        this.bootOptions = {
            controllers: {
                // Customize ControllerBooter Conventions here
                dirs: ['controllers'],
                extensions: ['.controller.js'],
                nested: true,
            },
        };

    }


}

```

## Current Behavior

- App runs well, but some requests aren't being received in the controllers of this lb4 app
- app.restServer.url is not defined on index.ts

## Expected Behavior

- App should receive requests in its controller
- app.restServer.url to be defined as 'localhost:3001

## Additional information

PS C:\Users\dmarq\loopback\microservices_poller> node -e 'console.log(process.platform, process.arch, process.versions.node)'
win32 x64 10.15.1
PS C:\Users\dmarq\loopback\microservices_poller> npm ls --prod --depth 0 | grep loopback
poller-v0@0.0.1 C:\Users\dmarq\loopback\microservices_poller
+-- @loopback/boot@1.4.4
+-- @loopback/cli@1.19.0
+-- @loopback/context@1.20.2
+-- @loopback/core@1.8.5
+-- @loopback/openapi-v3@1.7.0
+-- @loopback/repository@1.8.2
+-- @loopback/rest@1.16.3
+-- @loopback/rest-explorer@1.2.5
+-- @loopback/service-proxy@1.2.5
+-- loopback-connector-mongodb@4.2.0
+-- loopback-connector-rest@3.4.2
+-- loopback-socket@0.4.

## Related Issues

No similar bugs found

**Comment by raymondfeng** [comment]
The following code is flawed:
```ts
setTimeout(()=> {
        while (!app.restServer.listening);
        console.log('Started listening')
    }, 0);
```
