### ISSUE TITLE
Support for adding custom keywords to Ajv validator 

### ISSUE THREAD

**Issue by likexoo** [strongloop/loopback-next#3536]
## Suggestion

Support for adding custom keywords to Ajv validator 

## Use Cases

What do you want to use this for?

- Add custom keywords and using it in `@requestBody` `@param`
- Add expansion package such as [epoberezkin/ajv-keywords](https://github.com/epoberezkin/ajv-keywords) and using it in `@requestBody` `@param`

What shortcomings exist with current approaches?

- Cannot add custom keywords
- Need use keyword `regexp` (in [epoberezkin/ajv-keywords/regexp](https://github.com/epoberezkin/ajv-keywords#regexp)) instead of keyword `pattern`

## Examples

Show how this would be used and what the behavior would be

allow us to pass custom keywords to `@loopback/rest/src/body-parser/body-parser.ts` `.createValidator()`

![4058E30043AB77D637E1F8C01490ACAF](https://user-images.githubusercontent.com/15852426/62847322-33ebf300-bd08-11e9-8528-52708a3336e8.jpg)

and maybe we can define custom keywords in `Sequence` or somewhere

![841FF20DAB3A766B714B7FA489EB96C5](https://user-images.githubusercontent.com/15852426/62847342-4a924a00-bd08-11e9-9312-8c7a5943ea3b.jpg)

and finally we can use it like this

![C745E736-7956-4AB3-911B-A6DE8C9E7E6D](https://user-images.githubusercontent.com/15852426/62847349-639afb00-bd08-11e9-8fb6-9a7675bba222.png)

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dhmlau** [comment]
See PR #3539

**Comment by dhmlau** [comment]
PR has landed.  Closing as done.
