### ISSUE TITLE
BelongsToAccessor returns wrong entity

### ISSUE THREAD

**Issue by cyupa** [strongloop/loopback-next#3546]
## Steps to reproduce

I've picked up a starter repo that pretty much follows your guidelines from here: https://github.com/sourcefuse/loopback4-starter 

The problem I am facing is that a BelongsToAccessor returns a wrong entity.
In my situation, I fetch an entity "UserTenant" that has three belongsTo properties defined like this:
```
  @belongsTo(
    () => User,
    {keyFrom: 'user_id', name: 'user'},
    {
      name: 'user_id',
      required: true,
    },
  )
  userId: number;

  @belongsTo(
    () => Tenant,
    {keyFrom: 'tenant_id', name: 'tenant'},
    {
      name: 'tenant_id',
      required: true,
    },
  )
  tenantId: number;

  @belongsTo(
    () => Role,
    {keyFrom: 'role_id', name: 'role'},
    {
      name: 'role_id',
      required: true,
    },
  )
  roleId: number;

....

export interface UserTenantRelations {
  user: UserWithRelations;
  tenant: TenantWithRelations;
  role: RoleWithRelations;
}

export type UserTenantWithRelations = UserTenant & UserTenantRelations;
```
Model can also be found here: https://github.com/sourcefuse/loopback4-starter/blob/master/src/models/user-tenant.model.ts

The repo is defined like this:
```
export class UserTenantRepository extends ErrorHandlingCrudRepository<
  UserTenant,
  typeof UserTenant.prototype.id,
  UserTenantRelations
> {
  public readonly tenant: BelongsToAccessor<
    Tenant,
    typeof UserTenant.prototype.id
  >;

  public readonly user: BelongsToAccessor<User, typeof UserTenant.prototype.id>;
  public readonly role: BelongsToAccessor<Role, typeof UserTenant.prototype.id>;

  constructor(
    @inject('datasources.pgdb') dataSource: PgdbDataSource,
    @repository.getter(TenantRepository)
    tenantRepositoryGetter: Getter<TenantRepository>,
    @repository.getter(UserRepository)
    userRepositoryGetter: Getter<UserRepository>,
    @repository.getter(RoleRepository)
    roleRepositoryGetter: Getter<RoleRepository>,
  ) {
    super(UserTenant, dataSource);

    this.tenant = this.createBelongsToAccessorFor(
      'tenant',
      tenantRepositoryGetter,
    );

    this.user = this.createBelongsToAccessorFor('user', userRepositoryGetter);

    this.role = this.createBelongsToAccessorFor('role', roleRepositoryGetter);
  }
}
```
Can also be found here:
https://github.com/sourcefuse/loopback4-starter/blob/master/src/repositories/user-tenant.repository.ts

When I fetch the UserTenant object and then do the following:

```
console.log(
   `id: ${userTenant.id} tenantId: ${userTenant.tenantId}  roleId: ${
    userTenant.roleId
   }`,
 );
 // Create user DTO for payload to JWT
const authUser: AuthUser = new AuthUser(user);
authUser.tenant = await this.userTenantRepo.tenant(userTenant.id); // Tenant fetched here

console.log(`tenant: ${authUser.tenant.id}`);
```
As you can see here:
https://github.com/sourcefuse/loopback4-starter/blob/e76d8d70f2484fb082204efa8431d3789436e8fd/src/modules/auth/login.controller.ts#L371

I get the wrong entity fetched.

## Current Behavior

It gets the tenant with id 1 instead of 2.

> id: 2 tenantId: 2  roleId: 2
> tenant: 1

## Expected Behavior

It should obviously get the tenant with id 2.

> id: 2 tenantId: 2  roleId: 2
> tenant: 2

**Comment by raymondfeng** [comment]
@cyupa https://github.com/sourcefuse/loopback4-starter is community effort. Does it make more sense to open an issue there?

@samarpan-b WDYT?

**Comment by samarpanB** [comment]
Yes. Please raise it there. I’ll surely get you some help there.

**Comment by cyupa** [comment]
@raymondfeng thanks for the response. Sure, I can do that but by looking at the docs it seems that it everything is set up correctly.

To me it looks like an issue with the BelngsToAccessor, that’s why I posted it here.

**Comment by cyupa** [comment]
@raymondfeng  It seems that the issue was with the `keyFrom` option. Should have been using `keyTo` given that is a BelongsTo relationship? My understanding was that id looks to a property that has the  `id: true` option set. 

Thanks!
