### ISSUE TITLE
duplicate NPM packages?

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#3553]
Packages are being published twice in NPM

![Captura de pantalla 2019-08-16 a las 14 44 39](https://user-images.githubusercontent.com/13822438/63168491-9872bf00-c034-11e9-97e2-8e2c949ee261.png)

**Comment by raymondfeng** [comment]
@frbuceta Don't worry about the github releases. The last release process was a bit bumpy and it ended up with a few more github tags but `npm` should only have one set of published packages.
