### ISSUE TITLE
Project scaffolding via npx

### ISSUE THREAD

**Issue by rashtay** [strongloop/loopback-next#3554]
## Suggestion

I recently faced an issue where even after I globally installed the package, I couldn't use the commands. I fixed the issue. 

It just hit me that even `loopback` could bootstrap projects in the way `create-react-app` does it. I am not sure how feasible would it be for the team to do it or whether the team considers this suggestion helpful.

## Use Cases

1. No need to install the package globally.
2. Commands can be run within the project.
3. Each version can have its own set of commands and changes.

## Examples

1. `npx lb4 my-app`
2. `npx lb5 my-app`

**Comment by raymondfeng** [comment]
I believe that you can already install `@loopback/cli` as local dependency and use `npx lb4 ...`.

I don't think it's a good idea to allow multiple versions of `@loopback/cli` to be installed local to a project. Not sure that's even possible.

**Comment by raymondfeng** [comment]
BTW, you should be able to use `@loopback/cli` module programmatically too.

**Comment by rashtay** [comment]
@raymondfeng Oh, alright! Makes sense.

**Comment by mwrather** [comment]
If you're trying to run a binary that doesn't have the same name as its npm package, it's possible to specify the package like this:

```
$ npx -p @loopback/cli lb4
```
