### ISSUE TITLE
API_KEY example in Authentication Tutorial

### ISSUE THREAD

**Issue by sandijs-private** [strongloop/loopback-next#3561]
For secure web services deployments all newbies need also API_KEY.
(and some SHA1 fingerprints for mobile apps too?)

Current documentation describes how to create Authentication with JWT token.

That still allows hackers to flood freshly installed API with endless Login requests which floods also the database which in could scenarios pumps up project costs for startups with little cash which is big part of your audience.

Some simple example about how to add API_KEY too to the Authentication Tutorial will help a lot of folks!

Adding Http password is not a solution.

**Comment by dhmlau** [comment]
@jannyHou @emonddr, do you have some pointers for @sanadHaj to get started even we don't have the docs covering that yet? Thanks.

**Comment by jannyHou** [comment]
@sandijs-private Good point on the importance of having the api-key auth, the reason why we don't have a tutorial for it, is we encourage and give developers the flexibility to write their own auth strategy. We could write a simple example to demo the basic use of api-key auth, but it won't be shipped as an officially support extension.

I am looking at the express middleware [`api-key-auth`](https://github.com/arkerone/api-key-auth). If there is no such LoopBack auth strategy from the community yet, you can plugin the express one by applying the [`authentication-passport` adapter](https://www.npmjs.com/package/@loopback/authentication-passport)

**Comment by sandijs-private** [comment]
This is more like business requirement to have good reputation for a product which IBM acquired.

Product, which gives superb experience to its users.

I imagine it could be like web services creation CHECKLIST about what you should do to to create production quality web services.

Checklist could have links to various docs about Loopback features, and required external features.

Ability and guarantees that with Loopback you can create more serious API would spread popularity of this product like wild fire.

That same approach is needed for all new IBM owned product line.

Look at the Azure and Microsoft and their instructions for simple people!

**Comment by sandijs-private** [comment]
Example of systems administration checklist for production usage of mongodb: https://docs.mongodb.com/manual/administration/production-checklist-operations/

Even if there are no instructions on how to achieve API_KEY functionality, it could be mentioned in such checklist.
