### ISSUE TITLE
show imports in documentation

### ISSUE THREAD

**Issue by JohnPhoto** [strongloop/loopback-next#3581]
Sorry if this is incorrect template/repo for this suggestion.

## Steps to reproduce

When reading the docs on [https://loopback.io/doc/en/lb4/](https://loopback.io/doc/en/lb4/) for any of the Getting started tutorials.

## Current Behavior

It is most often problematic as a new into LB4 to know where the imports are made from with all the new syntax/concepts.
One specific example is [https://loopback.io/doc/en/lb4/Interceptors.html#apply-interceptors](https://loopback.io/doc/en/lb4/Interceptors.html#apply-interceptors)

## Expected Behavior

It would be very convenient if the code snippets "always" shows from where different imports that is needed from the `@loopback/{any}`-packages.

## Link to reproduction sandbox
example:
```ts
import {intercept} from '@loopback/core'; 
// ^-- Add these lines so that newcomers can start learning the concepts.

class MyController {
  @intercept(log) // Use the `log` function
  greet(name: string) {
    return `Hello, ${name}`;
  }
}
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

---

## 🎆 Hacktoberfest  2020

Greetings :wave: to all Hacktoberfest 2020 participants!

Here are few tips 👀 to make your start easier, see also #6456.

- Before you start working on this issue, please leave a comment to let others know.
- We don't have a full list of code snippets that are missing `import` statements, we rely on you to find the places needing improvement. Don't worry if you miss some, others will pick them up later. It's perfectly fine to work in small steps, changing only few pages in a single pull request. Baby steps FTW, every little helps!
- If you are new to GitHub pull requests, then you can learn about the process in [Submitting a pull request to LoopBack 4](https://loopback.io/doc/en/lb4/submitting_a_pr.html).
- If this is your first contribution to LoopBack documentation, then read [Documentation guide for LoopBack 4 developers](https://loopback.io/doc/en/lb4/code-contrib-lb4.html#documentation) please. Consider [previewing loopback-next docs only](https://loopback.io/doc/en/lb4/code-contrib-lb4.html#previewing-loopback-next-docs-only) for a faster feedback loop. Finally, please refer to [Contributing to LoopBack documentation](https://loopback.io/doc/en/contrib/doc-contrib.html) for a more advanced information on our Jekyll-based documentation infrastructure.
- Feel free to ask for help in `#loopback-contributors` channel, you can join our Slack workspace [here](https://join.slack.com/t/loopbackio/shared_invite/zt-8lbow73r-SKAKz61Vdao~_rGf91pcsw).

**Comment by dhmlau** [comment]
@JohnPhoto, thanks for pointing it out.  Would you like to submit a PR? 

For your reference, here is the step-by-step instructions in submitting a PR in `loopback-next` repo: https://loopback.io/doc/en/lb4/submitting_a_pr.html.  Thanks!

**Comment by JohnPhoto** [comment]
I will try to help out when I find the time.

One issue though:  [https://cla.strongloop.com/agreements/strongloop/loopback-next](https://cla.strongloop.com/agreements/strongloop/loopback-next) (taken from your link) does not seem to exist.

**Comment by raymondfeng** [comment]
> One issue though: https://cla.strongloop.com/agreements/strongloop/loopback-next (taken from your link) does not seem to exist.

We see the issue and in the process of fixing it.

**Comment by dhmlau** [comment]
@JohnPhoto, just wondering whether you're still interested in submitting a PR?  The CLA issue should be fixed. :)

**Comment by JohnPhoto** [comment]
I must admit that I really would like to see the change, but I have changed employer and are no longer actively working with loopback and my spare time is slim since I just got a child to take care of. So sadly do not get your hopes up that I will manage to get the time for it :(

**Comment by mrmodise** [comment]
Looks like most of them are added. Any more specific ones that maybe I can pick up?

**Comment by bajtos** [comment]
> Looks like most of them are added. Any more specific ones that maybe I can pick up?

I am afraid we don't have a list of places missing imports. Can you perhaps pick quickly scan through few doc pages to see if you can spot any code snippet(s) to fix?

**Comment by pktippa** [comment]
@dhmlau please assign the isse to me, please find PR #7084,
