### ISSUE TITLE
lb4 app does nothing (freezing)

### ISSUE THREAD

**Issue by milanissimo** [strongloop/loopback-next#3606]
I'm beginner starting to learn Loopback. Just freshly installed successfully Loopback (on Windows 8.1 64bit, node 12.7, Git Bash for Windows or ConEmu latest version) then running "lb4 app", but does nothing (freezing). Anything missing?

remains (no progress, no exiting), even after several minutes:
Kris@RISE1 MINGW64 /d/dev/loop-dev
$ lb4 app

References:

Kris@RISE1 MINGW64 /c/node12 
$ node -v                    
v12.7.0                      
                             
$ npm list -g --depth=0
c:\node12
+-- @angular/cli@8.2.0
+-- @loopback/cli@1.21.4
+-- express@4.17.1
+-- firebase-tools@7.2.4
+-- ionic@5.2.3
+-- native-run@0.2.8
+-- npm@6.10.0
`-- pg-promise@8.7.5

$ npm list -g inquirer
c:\node12
+-- @angular/cli@8.2.0
| `-- inquirer@6.5.0
+-- @loopback/cli@1.21.4
| +-- inquirer@6.5.2
| `-- yeoman-generator@4.0.1
|   `-- yeoman-environment@2.4.0
|     `-- inquirer@6.5.2  deduped
+-- firebase-tools@7.2.4
| `-- inquirer@6.3.1
`-- ionic@5.2.3
  `-- @ionic/cli-framework@2.1.2
    `-- inquirer@6.5.0

**Comment by derdeka** [comment]
I guess there is an issue getting an tty in MINGW64. Can you please try to do the same in a cmd or powershell window?

**Comment by milanissimo** [comment]
It works with cmd (admin). Thanks.

D:\DEV\loop-dev\firstapp>lb4 app
? Project name: firstapp
? Project description: firstapp
? Project root directory: firstapp
? Application class name: FirstappApplication
? Select features to enable in the project Enable eslint, Enable prettier, Enable mocha, Enable loopbackBuild
   create .eslintignore
   create .eslintrc.js
   create .mocharc.json
   create .npmrc
   create .prettierignore
   create .prettierrc
   create DEVELOPING.md
   create index.ts
   create package.json
   create README.md
   create tsconfig.json
   create .gitignore
   create index.js
   create public\index.html
   create src\application.ts
   create src\index.ts
   create src\migrate.ts
   create src\sequence.ts
   create src\controllers\index.ts
   create src\controllers\ping.controller.ts
   create src\controllers\README.md
   create src\datasources\README.md
   create src\models\README.md
   create src\repositories\README.md
   create src\__tests__\README.md
   create src\__tests__\acceptance\home-page.acceptance.ts
   create src\__tests__\acceptance\ping.controller.acceptance.ts
   create src\__tests__\acceptance\test-helper.ts

**Comment by hacksparrow** [comment]
Microsoft provides an official Linux subsystem on Windows - https://docs.microsoft.com/en-us/windows/wsl/install-win10. Using it might be better than MinGW.

Since you managed to get it working, I am closing this.
