### ISSUE TITLE
Model.toObject() should preserve prototypes (e.g. Date and ObjectID values)

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3607]
## Suggestion

ATM, `toObject()` method is implemented via `toJSON` and thus converts object values to JSON representation. This is problematic e.g. for `Date` and `ObjectID` values.

I am proposing to modify `toObject()` to preserve type of Date, ObjectID and other non-model values. Of course, if a model instance has a property set to a value of another Model, _that_ property must be recursively converted via `toObject` to a plain object.

## Use Cases

Consider the following test demonstrating the problem:

```ts
@model()
class Order extends Entity {
  @property({
      type: 'string',
      id: true,
      generated: true,
    })
    id: string;

    @property()
    createdAt: Date;
}

const orderRepo = // ...;
const DATE = new Date(...);
const created = orderRepo.create({
  createdAt: DATE;
});

expect(created.toObject()).to.deepEqual({
  id: created.id,
  createdAt: DATE,
});
```

The assertion above fails now.

## Examples

The test example above should pass.

## Acceptance criteria

- [ ] `.toObject()` is updated to handle `Date`,`ObjectID`, and other non-model values, and handle recursion into fields that are also `Model` objects. See : https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model.js#L422
- [ ] Update or add mocha test cases in https://github.com/strongloop/loopback-datasource-juggler/tree/master/test 
- [ ] Update documentation

**Comment by hacksparrow** [comment]
Agreed!

**Comment by emonddr** [comment]
@bajtos I added the Acceptance Criteria. Please adjust it to your liking; if necessary. thx

Also what is an example of non-model value?

**Comment by bajtos** [comment]
> I added the Acceptance Criteria.

Great, thank you @emonddr!

> Also what is an example of non-model value

A plain data object. For example:

```ts
@model()
class Foo extends Entity {
  @property({id: true})
    id: number;

    @property()
    data: object;
}

const foo = new Foo({id: 1, data: {key: 'value'}});
expect(foo.toObject().data).to.deepEqual({key: 'value'});
```

I think the conversion logic should work as follows:

- If the value is not an object, then keep it as-is
- If the value is an array, then (recursively) convert all items of that array
- If the value has `.toObject` method, then call it to perform the conversion
- Otherwise keep the value as-is

I have also checked the implementation of `toObject` in LB 3.x (see [loopback-datasource-juggler:lib/model.js](https://github.com/strongloop/loopback-datasource-juggler/blob/b6f9e92ef86369487bfc51261476c28ff1e276f3/lib/model.js#L441-L570)), I think we should also prepend the following rules:
- If the value is a function, then exclude it from the result
- If the property is configured as hidden, then exclude its value from the result

Here is the full algorithm:

1. If the property is configured as hidden, then exclude its value from the result.
2. If the value is a function, then exclude it from the result.
3. If the value is not an object, then keep it as-is.
4. If the value is an array, then (recursively) convert all items of that array.
5. If the value has `.toObject` method, then call it to perform the conversion.
6. Otherwise keep the value as-is.

**Comment by jannyHou** [comment]
I am debugging the code in [juggler's `toObject`](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model.js#L442) and [repository's `toObject`](https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/model.ts#L253), I think this story aims to improve repository's `toObject` to be allign with the one in juggler, instead of updating the juggler one, right?

**Comment by bajtos** [comment]
> I am debugging the code in [juggler's `toObject`](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model.js#L442) and [repository's `toObject`](https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/model.ts#L253), I think this story aims to improve repository's `toObject` to be allign with the one in juggler, instead of updating the juggler one, right?

Yes, the goal of this story is to improve `.toObject()` implementation in `@loopback/repository`. 

The code in juggler looks a bit convoluted to me. Rather than aligning the new implementation in LB4 to the complexity of the current implementation in juggler, I think it would be better to approach this problem with a fresh perspective and try to find an implementation `.toObject()` that will be simpler, more elegant and most importantly easy to understand & maintain going forward.

Setting aside implementation details, here is the behavior we are looking for (quoted from the issue description):

> I am proposing to modify `toObject()` to preserve type of Date, ObjectID and other non-model values. Of course, if a model instance has a property set to a value of another Model, _that_ property must be recursively converted via `toObject` to a plain object.

**Comment by jannyHou** [comment]
Closing after PR merged. Appreciate all the discussion from team 🎉 
The core conversion code in juggler is [these lines](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model.js#L528-L531), other code mostly checks options.
