### ISSUE TITLE
Create yeoman template/generator for loopback-next

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#361]
Even though parts of loopback-next are still in flux, I think it would be a good idea to begin building up a generator to rapidly spin up apps, rather than relying on the example as a template to bootstrap our own work.

This would be a good opportunity to properly dogfood the generator ourselves, as well as the design.

## Questions
- Do we have a "best practice" or default we'd like to follow for how the generated applications organize their resources? (Will we mimic loopback@3.x?)
- Would we want to change generator-loopback to accept command line arguments/environment variables? (Useful for automated testing)
- Would we create a new template rather than use the existing one?

## Considerations
- We currently have some tech debt to clean up for https://github.com/strongloop/generator-loopback

**Comment by kjdelisle** [comment]
cc @bajtos @raymondfeng @ritch @superkhau @rashmihunt

**Comment by superkhau** [comment]
@kjdelisle I've been discussing some of the CLI experience with @ritch for things that should happen soon, so +1 from me. However, I'm not sure if this should happen in the current generator/yeoman, etc.

**Comment by bajtos** [comment]
My opinion:

 - +1 for creating a project template for loopback.next projects. 
 - -1 for using yeoman, unless we are going to include loopback.next project template in the existing `loopback-cli`. In the long term, we need to rework loopback-cli to not depend on yeoman, see https://github.com/strongloop/generator-loopback/issues/139

Another thing to consider: integration with APIC Editor, possibly via loopback-workspace.

**Comment by dhmlau** [comment]
@kjdelisle, looks like we might need a spike to see what are the Yeoman equivalent we could possibly use for interactive command line user interfaces.  Are you ok to change this as a spike?

@bajtos  mentioned [Inquirer](https://www.npmjs.com/package/inquirer) in strongloop/generator-loopback#139.

cc @rashmihunt

**Comment by dhmlau** [comment]
duplicate of https://github.com/strongloop/loopback-next/issues/697 ?

**Comment by kjdelisle** [comment]
Closing as complete, see https://github.com/strongloop/loopback-next/tree/master/packages/cli
