### ISSUE TITLE
feat(authentication): allow AuthenticationStrategyProvider to get extended

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-next#3648]
## Suggestion

AuthenticationStrategyProvider is currently not exported, therefor is can not be easily extended.

## Use Cases

We would like to have a minimal diffenent behavior than the default one, but its not allowed to extend the class AuthenticationStrategyProvider. The extensionPoint functionality make it hard to replace it completely as it is AFAIK not possible to redefine an extensionPoint.

## Examples

```typescript
import { AuthenticationStrategy, AuthenticationStrategyProvider } from '@loopback/authentication';

export class MyAuthenticationStrategyProvider extends AuthenticationStrategyProvider {

  async value(): Promise<AuthenticationStrategy | undefined> {
    // ... do something before calling the super implementation

    return super.value();
  }
}
```

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dhmlau** [comment]
@derdeka, I'm assigning this ticket to you since you have a PR in progress. Thanks for your contribution!

**Comment by derdeka** [comment]
related to #3637
