### ISSUE TITLE
Dynamic Factories

### ISSUE THREAD

**Issue by bradharms** [strongloop/loopback-next#3652]
## Suggestion

Allow a context to have one or more "dynamic/abstract factories" for processing unbound keys.

This would allow a context that doesn't have a binding for a given key to dynamically "invent" a new service on-the-fly and inferring properties of the service by looking at the key being injected and/or other sources of config. This would happen at resolution time, and would ONLY occur if no explicit service had already been bound to a key (ie. explicitly-bound keys take precedence over dynamically-bound keys).

This is based roughly around the idea of "Abstract Factories" that was provided by Zend Framework.

## Use Cases

This feature was inspired by a situation in our project that requires us to create "stacks" of repositories per each entity type, with each repository in a stack handling a specific CRUD-related feature such as security checks or change logging. We realized it was a lot of work to create multiple repositories for each entity type and then chain them all together, so we thought of a way to automate the process by delegating entity-type-specific behavior to static entity methods on the entities themselves, and then having the repositories in the stack call the static methods of the entities (since repositories have a reference to the entity class). This allows us to forego nearly all explicit repository definitions in favor of just the entity classes with minimal code attached for determining security and logging-related properties

We currently approximate the feature being proposed using custom-flavored versions of the `@inject` decorator that accept an entity class and use a custom resolve function to either return a bound repository or else construct one on the fly if no repository is bound.

## Examples

```typescript
import {BindingAddress, BindingScope, Context} from '@loopback/core';
import {Context} from '@loopback/context';

export interface DynamicFactory {
    canResolve(address: BindingAddress): boolean;
    resolve(ctx: Context, address: BindingAddress): Promise<any>;
}

const DynamicFactoriesMixin = <C extends new (...args: any[]) => Context>(
    ContextClass: C
) => class DynamicFactoriesContext extends ContextClass {

    protected dynamicFactories: DynamicFactory[] = [];

    constructor(...args: any[]) {
        super(...args);
    }

    public dynamicFactory(df: DynamicFactory) {
        this.dynamicFactories.push(df);
        return this;
    }

    public findDynamicFactory(address: BindingAddress) {
        for (const df of this.dynamicFactories) {
            if (df && df.canResolve(address)) {
                return df;
            }
        }
        return null;
    }

    public isBound(address: BindingAddress) {
        return super.isBound(address) || !!this.findDynamicFactory(address);
    }

    public async get<ValueType>(
        keyWithPath: BindingAddress<ValueType>,
        ...args: any[]
    ): Promise<ValueType | undefined> {
        if (super.isBound(keyWithPath)) {
            return await super.get(keyWithPath, ...args);
        }
        const df = this.findDynamicFactory(keyWithPath);
        if (df) {
            return await df.resolve(this, keyWithPath);
        }
        return null;
    }
};

export default DynamicFactoriesMixin;
```

## Acceptance criteria

TBD - will be filled by the team.

**Comment by raymondfeng** [comment]
@bradharms Thank you for the proposal. In fact, I have been thinking about something similar for a while now.

**Comment by raymondfeng** [comment]
@bradharms Instead of a `DynamicFactory`, a `BindingFactory` probably makes our life easier as it's a factory to supply bindings for a context. If a binding key is not registered in the context registry, we can fall back to binding factories to see if there is a binding behind.

**Comment by bradharms** [comment]
@raymondfeng So you are suggesting that at we add a _binding_ at resolution rather than resolving the service directly?

I have some mixed feelings about this. In my mind a `DynamicFactory` would function more like bindings in the "transient" scope, meaning they would be redefined at each resolution and nothing about the application's binding registry would change outside the configuration phase. But a `BindingFactory` would have to modify the app config after we begin resolving for the initial request, and those bindings would persist into subsequent requests.

Maybe this is not a bad thing. It would allow more of Loopback's existing service resolution process to be applied. For example, a binding factory would have the ability to set the binding scope.
