### ISSUE TITLE
Generate lb4 application in local-directory or specific directory using --directory flag

### ISSUE THREAD

**Issue by DanielChuDC** [strongloop/loopback-next#3654]
Hi , may I ask does lb4 support --directory flag to generate the source code under a specific directory and not to create a new directory.

**Comment by raymondfeng** [comment]
@DanielChuDC What's your use case?

Please note that `lb4 app` allows `--outdir` option to supply the directory name to be created.

**Comment by DanielChuDC** [comment]
Hi, my use case like Angular project able to generate the source code into the local directory using `.` or `./` 
For example: `ng new --directory .`
It is convenient for create a project under a github folder.

By using --outdir, does not generate in the local directory where it will return a error saying that the `.` or `./` already exists.
```
lb4 app
? Project name: git-hub
? Project description: GitHub
? Project root directory: ./
>> Directory ./ already exists.
```

**Comment by raymondfeng** [comment]
Do you want to allow the `outdir` to exist even it's not empty?

**Comment by DanielChuDC** [comment]
Hi, technically the folder can be empty or not empty. Not empty as in the folder may including those file like .git; it is empty also because is hidden files.

If there are able to generate the new app lb4  by using `./` or `.` for those git initialized folder, that will be great.
