### ISSUE TITLE
UserProfile does not found using @loopback/authentication 2.2.0 

### ISSUE THREAD

**Issue by DanielChuDC** [strongloop/loopback-next#3655]
## Steps to reproduce

Follow guide from [loopback official documentation](https://loopback.io/doc/en/lb4/Loopback-component-authentication.html#authentication-component) and 
`npm install --save @loopback/authentication`. 

## Current Behavior

UserProfile not found in @loopback/authentication

## Expected Behavior

UserProfile found in @loopback/authentication

## Additional information

I found that there has a UserProfile in @loopback/security. But I am not sure the UserProfile is it the same with  @loopback/authentication

# Environment:
lb4 -version
@loopback/cli version: 1.21.5

@loopback/* dependencies:
  - @loopback/authentication: ^2.2.0
  - @loopback/boot: ^1.5.4
  - @loopback/build: ^2.0.9
  - @loopback/context: ^1.22.0
  - @loopback/core: ^1.10.0
  - @loopback/metadata: ^1.3.0
  - @loopback/openapi-spec-builder: ^1.2.11
  - @loopback/openapi-v3: ^1.9.5
  - @loopback/repository-json-schema: ^1.9.6
  - @loopback/repository: ^1.13.0
  - @loopback/rest: ^1.18.0
  - @loopback/testlab: ^1.7.5
  - @loopback/docs: ^1.30.0
  - @loopback/example-hello-world: ^1.2.12
  - @loopback/example-log-extension: ^1.2.12
  - @loopback/example-rpc-server: ^1.2.12
  - @loopback/example-todo: ^1.7.5
  - @loopback/example-soap-calculator: ^1.6.13
  - @loopback/service-proxy: ^1.3.4
  - @loopback/http-caching-proxy: ^1.1.11
  - @loopback/http-server: ^1.4.11
  - @loopback/example-todo-list: ^1.9.5
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^1.3.5
  - @loopback/eslint-config: ^4.0.2
  - @loopback/example-express-composition: ^1.5.5
  - @loopback/example-greeter-extension: ^1.3.12
  - @loopback/booter-lb3app: ^1.2.12
  - @loopback/example-lb3-application: ^1.1.12
  - @loopback/example-greeting-app: ^1.1.12
  - @loopback/example-context: ^1.2.12
  - @loopback/repository-tests: ^0.4.3
  - @loopback/extension-health: ^0.2.4
  - @loopback/authorization: ^0.2.1
  - @loopback/rest-crud: ^0.1.0
  - @loopback/security: ^0.1.0

Hi, I am following the tutorial and guide from https://loopback.io/doc/en/lb4/Loopback-component-authentication.html#authentication-component and realise the UserProfile stated in the guide are not found. Please let me know if the UserProfile are the same with @loopback/security

Thank you.
<img width="1238" alt="Screenshot 2019-09-04 at 3 36 35 PM" src="https://user-images.githubusercontent.com/52316624/64234918-e428d200-cf29-11e9-90cd-c367748b5d7a.png">

<img width="941" alt="Screenshot 2019-09-04 at 3 38 04 PM" src="https://user-images.githubusercontent.com/52316624/64235074-32d66c00-cf2a-11e9-9222-fc69a99bceb8.png">

**Comment by jannyHou** [comment]
@DanielChuDC Good catch, it is exported from `@loopback/security` now, I will submit a PR for the backward compatibility.

**Comment by DanielChuDC** [comment]
@jannyHou thank you for your response. May I ask what is the main reason moving that User profile to another package?

**Comment by JohnPhoto** [comment]
@DanielChuDC The reason is that they want to consolidate common types/keys between authentication and authorization.
