### ISSUE TITLE
Documentation and Example of Oauth2 sign in like google sign in.

### ISSUE THREAD

**Issue by DanielChuDC** [strongloop/loopback-next#3656]
## Suggestion

Add Documentation and Example of Oauth2 sign in like google sign in.

## Use Cases

Struggling to add the customs passport authentication even reading the guide.
Referring to the loopback 4 shopping cart example, it does not have Oauth 2.0 sign in example.

Thank you.

**Comment by dhmlau** [comment]
@jannyHou @emonddr, I believe we don't support OAuth2 right now out of the box. But is there any workaround? Thanks.

**Comment by emonddr** [comment]
@DanielChuDC @davilopez90 ,

In our documentation

https://loopback.io/doc/en/lb4/Loopback-component-authentication.html

there is a link mentioned 

https://www.npmjs.com/package/@loopback/authentication-passport

in this paragraph: 

![image](https://user-images.githubusercontent.com/6864736/65044719-78803500-d92b-11e9-9a90-1b7b0e3f9dc9.png)

that has instructions on how to set up an adapter to the 
popular `passport` npm modules for handling various types of authentication .
( http://www.passportjs.org/docs/ )

At last count, the passport website advertises ~500 different authentication strategies; including google, facebook etc.

At the moment, LoopBack has documentation for creating your own custom authentication strategy, or using the passport adapter, but we don't have specific instructions (documentation) for 500 authentication methods.

Hopefully the documentation in 

https://www.npmjs.com/package/@loopback/authentication-passport

along with the documentation provided by passport themselves is sufficient.

**Comment by emonddr** [comment]
@loopback/authentication and @loopback/authentication-passport are our recent developments with regard to authentication for LoopBack 4. We have examples on handling `basic` and `jwt` using our current design. @loopback/authentication-passport has an example using `passport-http` (Basic authentication). We have a spike `Spike] Explore/research the oauth2+session based authentication strategy ` https://github.com/strongloop/loopback-next/issues/2624  in plan to investigate OAuth2.0 strategies and how they can be integrated in our current design of the @loopback/authentication and @loopback/authentication-passport modules.

**Comment by emonddr** [comment]
Please stay tuned.

**Comment by emonddr** [comment]
let's continue the discussion in here

https://github.com/strongloop/loopback-next/issues/2624
