### ISSUE TITLE
loosing type check when using configure instead of bind

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-next#3662]
`configure` does not validate typescript types, `bind` is doing this.

## Steps to reproduce

Example 1:

With `bind` type check works fine, vscode claims aWrongKey as invalid:
```typescript
this.bind(RestExplorerBindings.CONFIG).to({
  path: '/explorer2',
  aWrongKey: 1,
});
```

With `configure` aWrongKey is not marked as invalid:
```typescript
this.configure(RestExplorerBindings.COMPONENT).to({
  path: '/explorer2',
  aWrongKey: 1,
});
```

Example 2:

Types are checked:
```typescript
this.bind(HealthBindings.CONFIG).to({
  healthPath: '/health',
  livePath: '/live',
  readyPath: '/ready',
  aWrongKey: 1,
});
```

Type check lost:
```typescript
this.configure(HealthBindings.COMPONENT).to({
  healthPath: '/health',
  livePath: '/live',
  readyPath: '/ready',
  aWrongKey: 1,
});
```

## Current Behavior

Type check missing when using `configure`, only works with `bind`.

## Expected Behavior

Type check should also work with `configure`.

## Additional information

```text
+-- @loopback/authentication@2.2.0
+-- @loopback/authorization@0.2.1
+-- @loopback/boot@1.5.4
+-- @loopback/booter-lb3app@1.2.12
+-- @loopback/context@1.22.0
+-- @loopback/core@1.10.0
+-- @loopback/extension-health@0.2.4
+-- @loopback/openapi-v3@1.9.5
+-- @loopback/repository@1.13.0
+-- @loopback/rest@1.18.0
+-- @loopback/rest-explorer@1.3.5
+-- @loopback/service-proxy@1.3.4
```

**Comment by raymondfeng** [comment]
@derdeka I relabeled the issue as `feature`.

One possible solution is to allow BindingKey to be typed as `<ValueType, ConfigType = unknown>`

**Comment by derdeka** [comment]
@raymondfeng
Thanks, i think i finally understand your hint now - after getting deeper into lb4 for some month.  ;-)

For the records, this solves the typing issue for me:
(not sure if this already worked when creating this issue)

```ts
this.configure<RestExplorerConfig>(RestExplorerBindings.COMPONENT).to({
  path: '/explorer2',
  aWrongKey: 1,
});

this.configure<HealthConfig>(HealthBindings.COMPONENT).to({
  healthPath: '/health',
  livePath: '/live',
  readyPath: '/ready',
  aWrongKey: 1,
});
```
