### ISSUE TITLE
TS2322 error with authentication example

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#3668]
## Steps to reproduce

https://github.com/strongloop/loopback-next/blob/5c3b875d97b8eafd236a0bdb6e09c771cefedf39/packages/authentication/src/__tests__/fixtures/services/jwt-service.ts#L33-L37

#### My Code
``` typescript
    // Decode user profile from token
    try {
      userProfile = await promisify(verify)(token, this.jwtSecret)
    } catch (error) {
      throw new HttpErrors.Unauthorized(
        `Error verifying token : ${error.message}`,
      );
    }
```

> error TS2322: Type 'unknown' is not assignable to type 'UserProfile'

## Additional information

> darwin x64 12.9.1

> ├── @loopback/authentication@2.2.0
> ├── @loopback/boot@1.5.4
> ├── @loopback/context@1.22.0
> ├── @loopback/core@1.10.0
> ├── @loopback/openapi-v3@1.9.5
> ├── @loopback/repository@1.13.0
> ├── @loopback/rest@1.18.0
> ├── @loopback/rest-explorer@1.3.5
> ├── @loopback/security@0.1.0
> ├── @loopback/service-proxy@1.3.4
> └── loopback-connector-mysql@5.4.2

## Related Issues

NaN

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by frbuceta** [comment]
Can somebody help me?

**Comment by julianomacielferreira** [comment]
Could you copy your tsconfig.json file content, please ?

**Comment by julianomacielferreira** [comment]
Hello @frbuceta,

My name is Juliano and I'm a new user of the project. Sorry if I can't help you much!

But, could you explain more what I have to do to reproduce this error ?

I know it is a type error of typescript and the config to trigger is something like:

 ```json
"strict": true,
```
on a tsconfig.json file.

Thank you!

**Comment by frbuceta** [comment]
thanks, all the help is necessary;)

Well, following the tests you can create an example, here([test](https://github.com/strongloop/loopback-next/tree/master/packages/authentication/src/__tests__/fixtures)) is the directory where you can play the issue

**Comment by raymondfeng** [comment]
Please use `@loopback/authentication@2.2.2` instead. v2.2.0 was published by mistake with breaking changes.

**Comment by frbuceta** [comment]
@raymondfeng I have come to update until version `3.0` and I get the same error

**Comment by dougal83** [comment]
> @raymondfeng I have come to update until version `3.0` and I get the same error

3.0 has the breaking change that you originally encountered, hence the jump to v3.  Use 2.2.2 with your current code or rewrite implementation to be compatible with breaking change.

**Comment by frbuceta** [comment]
> > @raymondfeng I have come to update until version `3.0` and I get the same error
> 
> @frbuceta 3.0 has the breaking change that you originally encountered, hence the jump to v3. Use 2.2.2 with your current code or rewrite implementation to be compatible with breaking change.

I have refactored my code for version 3. Later I will check again.

**Comment by frbuceta** [comment]
The error is resolved using `require` instead of` import`

Before
```
import * as jwt from 'jsonwebtoken'
const signAsync = promisify(jwt.sign);
const verifyAsync = promisify(jwt.verify);
```

After
```
const jwt = require('jsonwebtoken');
const signAsync = promisify(jwt.sign);
const verifyAsync = promisify(jwt.verify);
```
