### ISSUE TITLE
propagate configured AuthenticationStrategy to OpenApiSpec

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-next#3669]
## Suggestion

The configured `AuthenticationStrategy` should propagate the `securityschema` into the generated openapi spec. Currently each endpoint need several configuration options to make this possible. 

## Use Cases

With configured securityschemas the api explorer handles authentication information automatically and sends it to the lb4 server.

## Examples

Currently I'm doing something like this:

application.ts
```typescript
import { merge } from 'lodash';
// ...
constructor(options: ApplicationConfig = {}) {
	// ...
	const spec = this.getSync(RestBindings.API_SPEC);
	merge(spec, {
	  components: {
		securitySchemes: {
		  BasicAuth: {
			type: 'http',
			scheme: 'basic',
		  },
		  BearerAuth: {
			type: 'http',
			scheme: 'bearer',
		  },
		  ApiKeyAuth: {
			type: 'apiKey',
			in: 'header',
			name: 'X-API-Key',
		  },
		},
	  },
	});
	// ...
}
```

user.controller.ts
```typescript
...
@authorize('jwt')
@get('/users', {
  security: [{
    BearerAuth: [],
  }],
  responses: {
    [STATUS_CODE.OK]: {
      content: { [CONTENT_TYPE.JSON]: { schema: { type: 'array', items: getModelSchemaRef(User) } } },
    },
  },
})
async userFind(
...
```
Please note, that `@authorize('jwt')` and `security` is some kind of redundant and needs to be configured for each endpoint.

## Acceptance criteria

- [ ] Authentication strategy can contribute security schemas when it gets registered to an application. The security schema specs will be merged into `OpenAPISpec.components.schemas`. Modify the [`registerAuthenticationStrategy()`](https://github.com/strongloop/loopback-next/blob/2be7e67f6f685795920341f7762fbdd8da38f7b2/packages/authentication/src/types.ts#L56) method to handle the spec merge. 

- [ ] Update `loopback4-shopping-example` to leverage the new change.

**Comment by derdeka** [comment]
I found a simpler way without modifying all endpoints:

constants.ts
```typescript
export namespace SECURITY_REQUIREMENT {
  export const DEFAULT: SecurityRequirementObject[] = [
    {
      BearerAuth: [],
    },
  ]

  export const NONE: SecurityRequirementObject[] = [
  ]
}
```

application.ts
```typescript
import { merge } from 'lodash';
// ...
constructor(options: ApplicationConfig = {}) {
	// ...
	const spec = this.getSync(RestBindings.API_SPEC);
	merge(spec, {
          security: SECURITY_REQUIREMENT.DEFAULT,
	  components: {
		securitySchemes: {
		  BasicAuth: {
			type: 'http',
			scheme: 'basic',
		  },
		  BearerAuth: {
			type: 'http',
			scheme: 'bearer',
		  },
		  ApiKeyAuth: {
			type: 'apiKey',
			in: 'header',
			name: 'X-API-Key',
		  },
		},
	  },
	});
	// ...
}
```

user.controller.ts
```typescript
...
@authorize('none')
@post('/users/login', {
  security: SECURITY_REQUIREMENT.NONE,
  responses: {
    // ...
  },
})
async userLogin(
...
```

**Comment by derdeka** [comment]
related to #2027

**Comment by jannyHou** [comment]
see draft PR https://github.com/strongloop/loopback4-example-shopping/pull/267

**Comment by jannyHou** [comment]
Acceptance Criteria updated.

**Comment by dhmlau** [comment]
Related to https://github.com/strongloop/loopback-next/issues/2027

**Comment by jannyHou** [comment]
some update: 

The openapi spec enhancer service is created in https://github.com/strongloop/loopback-next/pull/4258.

To allow contributing custom security spec, we need https://github.com/strongloop/loopback-next/issues/4380 happen first.

And two more improvements:
https://github.com/strongloop/loopback-next/issues/4386
https://github.com/strongloop/loopback-next/issues/4385

**Comment by achrinza** [comment]
Closing as done (see #4693).

**Comment by achrinza** [comment]
Closing as done (see #4693).
