### ISSUE TITLE
app.stop() should close all database connections

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3675]
## Suggestion

When the user calls `app.stop()`, all database connections should be closed and any other handles should be released. This way the Node.js process should naturally exit because there is no more work to be done.

See the discussion in https://github.com/strongloop/loopback-next/issues/3672 for more details.

## Use Cases

- Run `mocha` tests without `--exit` flag.
- Graceful shutdown.

## Acceptance criteria

TBD - will be filled by the team.

**Comment by raymondfeng** [comment]
I see a few options to implement this feature:

1. Add `stop` alias to juggler datasource to call `disconnect` and register all datasources as life cycle observers. We probably don't want to call `connect` during `start` to honor `lazyConnect`.

2. Change the CLI template for datasource classes with lifecycle observer signature. This is probably more flexible as application developers can decide if they to override the start/stop.

**Comment by bajtos** [comment]
> Change the CLI template for datasource classes with lifecycle observer signature. This is probably more flexible as application developers can decide if they to override the start/stop.

+1

On the second thought, I see also a third option - modify our connector to unref the TCP connection handles they hold in the connection pool, so that Node.js don't consider them as "active" when deciding whether the process has finished.

**Comment by derdeka** [comment]
@bajtos @raymondfeng
Is this issue resolved as #3678 is merged? (lifecycle support to close the connection)

**Comment by raymondfeng** [comment]
@derdeka Thanks for the reminder.
