### ISSUE TITLE
Changes in relations

### ISSUE THREAD

**Issue by gonzarascon** [strongloop/loopback-next#3682]
Hi, it's me again!

A time ago, I posted issue [#3356](https://github.com/strongloop/loopback-next/issues/3356#issue-467928284) regarding problems in MySQL relations doing a `GET` request and I was able to solve the problem with a workaround.

Today I updated loopback and it's dependencies, when I double checked my endpoints (to ensure everything still worked), I noticed that now my endpoints wich have relations show this schema in the description field:

(Example of description in GET `/courses`. "Course" model belongs to "User" model)
```
  "where": {},
  "fields": {
    "id": true,
    "name": true,
    "description": true,
    "userId": true,
    "state": true,
    "course_photo": true
  },
  "offset": 0,
  "limit": 10,
  "skip": 0,
  "order": [
    "string"
  ],
  "include": [
    {
      "relation": "string",
      "scope": {
        "where": {},
        "fields": {},
        "offset": 0,
        "limit": 0,
        "skip": 0,
        "order": [
          "string"
        ]
      }
    }
  ]
}
```
I tested the app and all endpoints seem to work as espected, but I found strange the change in the description field.

I think this is an issue that has to do with updating, has anything changed regarding relations handling?

**Comment by dhmlau** [comment]
@gonzarascon, I believe you're looking at the filter field in API Explorer? 
![Screen Shot 2019-09-09 at 3 34 43 PM](https://user-images.githubusercontent.com/25489897/64560882-6b55bb80-d317-11e9-9351-d543db6ba3a9.png)


What's the behavior you're expecting?

**Comment by gonzarascon** [comment]
Hi @dhmlau! I was exactly looking at that field. Before upgrading loopback filter showed something more similar to the model instance like:

![image](https://user-images.githubusercontent.com/35515401/64572684-c51dac00-d33e-11e9-8c23-75cf6d562367.png)

I was worried this change would affect my application!

**Comment by achrinza** [comment]
Closing as solved.
