### ISSUE TITLE
[Spike] CASCON workshop prep work

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#3692]
As our workshop proposal got accepted in [CASCON](http://cascon.ca/), this spike is used to figure out what exactly the workshop would be, because it has been reduced to 1 hour 45 minutes. 

_Since this is a spike, I'm expecting to spend a day max for that._

## Acceptance Criteria
Given the workshop is only 1 hour 45 minutes
- [x] map out a workshop outline (intro, workshop exercise, slides about LB) 
- [x] workshop hands-on exercise that can fit in this time constraint, assuming the audience has no LB knowledge.  
   - [x] think of an application (is it greeter extension + greeter app? or others?)
   - [x] try to create it yourself and see how much time is needed
- [ ] after the spike is done, create tasks to work on it.

### Out of scope
- create hands-on exercise instructions
- create slides for presentation
We will create tasks for that. 

cc @jannyHou

**Comment by jannyHou** [comment]
See the demo app that augments a greeting endpoint by:

- binding greeting service from a component
- adding greeter extension in a different language
- applying cache service 

https://github.com/jannyHou/cascon-2019/tree/init/demo

Follow up stories:

- [ ] [story 1](link tbd) Create a formal demo app for workshop with:
    - [ ] Break down the implementation of app into 3-4 steps(summarized in [readme](https://github.com/jannyHou/cascon-2019/tree/init/demo/greeter#step-1))
    - [ ] Create a different branch for each step
    - [ ] Make sure the functionalities work well 
- [ ] [story 2](link tbd) Create slides to highlight the concepts and technologies we touched in the tutorial
- [ ] [story 3](link tbd) Presentation rehearsal

**Comment by dhmlau** [comment]
Thanks @jannyHou for the proposal. LGTM. I took the liberty to create the other 2 tasks. Closing this task as done.
