### ISSUE TITLE
[Spike] CASCON Expo prep work

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#3693]
Now that our poster proposal is accepted to [CASCON](http://www-01.ibm.com/ibm/cas/cascon/), this spike is to figure out what we need to prepare.

_Since this is a spike, expect to spend 0.5 max._

## Acceptance Criteria,
- [ ] What to show in poster (are we reusing the TechConnect poster? just bringing the TechConnect (internal) content to external?)
- [ ] What we need to talk about at the booth
   - _not the script. but what we want to tell the audience at a high level_
   - what demo to show? 

cc @emonddr

**Comment by dhmlau** [comment]
@emonddr, as discussed, if we're planning to create another poster, please leave it enough time for the design team to design it for us. Thanks!

**Comment by emonddr** [comment]
Placing poster ideas in 

https://ibm.ent.box.com/folder/88591184270

**Comment by emonddr** [comment]
Poster 1 is the classic poster (doesn't need redesign)
Poster 2 is a combination of [LoopBack 4 overview diagram and bullet points](https://loopback.io/doc/en/lb4/index.html) and a modified version of the [shopping cart application diagram](https://github.com/strongloop/loopback4-example-shopping)

Poster 3 - will be a diagram of deploying a LoopBack 4 application as separate microservices in Kubernetes on the cloud

**Comment by dhmlau** [comment]
We've sent the mockup to the designer.  Closing as done.

**Comment by emonddr** [comment]
Not doing Poster 3. Just poster 2. 


Work request sent to design team: https://github.ibm.com/velox/uxdesign/issues/1052

Poster 2
Something along these lines:

# LoopBack 4 : Built for API Developers, Extension Developers, Platform developers, and Teams

## High-level Overviev
![image](https://user-images.githubusercontent.com/6864736/67041986-d9e71f80-f0f4-11e9-9b96-eb69d1b6a902.png)

## Example Online Shopping application
![image](https://user-images.githubusercontent.com/6864736/67042000-e5d2e180-f0f4-11e9-952f-c3e5884a35fd.png)
