### ISSUE TITLE
Dynamically loading global interceptors

### ISSUE THREAD

**Issue by technicaljones** [strongloop/loopback-next#3697]
Hi,

First off the docs say the following:

> Global interceptors
Global interceptors are discovered from the InvocationContext. They are registered as bindings with interceptor tag. For example,

```
import {asInterceptor} from '@loopback/context';

app
  .bind('interceptors.MetricsInterceptor')
  .toProvider(MetricsInterceptorProvider)
  .apply(asInterceptor);
```
([https://loopback.io/doc/en/lb4/Interceptors.html](url))

Which seems incorrect as asInterceptor doesn't exist in @loopback/context.

What I want to do is include a global interceptor as part of a component and only enable it if certain config is set. But I can't seem to get it to load from any other dir than the interceptors directory. Do I need to write a custom booter for this or is there another way to dynamically load a Global Interceptor.

Thanks

**Comment by dhmlau** [comment]
@raymondfeng , I guess this has been changed? 

@technicaljones, I've created a blog regarding global interceptors based on a more updated version.  Perhaps you can take a look? https://strongloop.com/strongblog/loopback4-interceptors-part1/

**Comment by raymondfeng** [comment]
I believe that we reload global interceptors per request - see https://github.com/strongloop/loopback-next/blob/master/packages/context/src/interceptor.ts

**Comment by raymondfeng** [comment]
The template function should be `asGlobalInterceptor`. I'll fix the docs.

**Comment by technicaljones** [comment]
Thanks for the feedback. 

So I added the following to the application class 

Imported the template function
`import {asGlobalInterceptor} from '@loopback/context';`


Imported our Interceptor from the component
`import {AuthenticationInterceptor} from "./components/authentication/interceptors";`

Then tried to bind it as a global interceptor

```
// Bind the auth global interceptor
    this
        .bind('interceptors.AuthenticationInterceptor')
        .toProvider(AuthenticationInterceptor)
        .apply(asGlobalInterceptor);
```

This didn't build correctly and gave us a type error:

> error TS2345: Argument of type '(group?: string | undefined) => BindingTemplate<unknown>' is not assignable to parameter of type 'BindingTemplate<any>'.

For some reason the type BindingTemplate (binding.ts) is of type \<unknown\> whereas it comes through as type \<any\>.

So I changed the binding to look like this:
```
// Bind the auth global interceptor
    this
        .bind('interceptors.AuthenticationInterceptor')
        .toProvider(AuthenticationInterceptor)
        .apply(<any>asGlobalInterceptor);
```

And it built correctly however it didn't load or execute the interceptor.

Any ideas?

Thanks

**Comment by technicaljones** [comment]
Just on a side note I managed to load interceptors from component dirs using a custom glob in the application class boot options:

```
this.bootOptions = {
      controllers: {
        // Customize ControllerBooter Conventions here
        dirs: ['controllers'],
        extensions: ['.controller.js'],
        nested: true,
      },
      interceptors: {
        glob: '{' +
          // Find and load local project interceptors
          '/interceptors/*.interceptor.js,' +
          // Find and specified component interceptors
          `/components/@(${cmpInterceptors.join('|')})/interceptors/*.interceptor.js,` +
          '}'
      },
    };
```

**Comment by raymondfeng** [comment]
@technicaljones Sorry one fix for the docs - https://github.com/strongloop/loopback-next/pull/3710

Please note `asGlobalInterceptor` is a factory function of BindingTemplate and it takes an optional group name for the interceptor to help sort.

**Comment by technicaljones** [comment]
Great thanks @raymondfeng 

Passed in the group name and its working now.
