### ISSUE TITLE
Unable to POST on endpoint with recursive model

### ISSUE THREAD

**Issue by mmussche2** [strongloop/loopback-next#3706]
Related to #3674
I have updated my openapi-v3 dependency, now my API starts correctly, but I can't send a post on the associated endpoint, I get an internal server error :

```
{
    "error": {
        "statusCode": 500,
        "name": "RangeError",
        "message": "Maximum call stack size exceeded",
        "stack": "RangeError: Maximum call stack size exceeded\n    at Object.entries.forEach (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:95:43)\n    at Array.forEach (<anonymous>)\n    at ReportDefinitionRepository.definePersistedModel (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:91:47)\n    at ReportDefinitionRepository.resolvePropertyType (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:120:20)\n    at Object.entries.forEach (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:96:51)\n    at Array.forEach (<anonymous>)\n    at ReportDefinitionRepository.definePersistedModel (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:91:47)\n    at ReportDefinitionRepository.resolvePropertyType (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:120:20)\n    at Object.entries.forEach (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:96:51)\n    at Array.forEach (<anonymous>)\n    at ReportDefinitionRepository.definePersistedModel (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:91:47)\n    at ReportDefinitionRepository.resolvePropertyType (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:120:20)\n    at Object.entries.forEach (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:96:51)\n    at Array.forEach (<anonymous>)\n    at ReportDefinitionRepository.definePersistedModel (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:91:47)\n    at ReportDefinitionRepository.resolvePropertyType (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:120:20)"
    }
}
```
when replacing

```
@property.array(ReportState, {})
 states: ReportState[];
```
by

```
 @property.array(Object, {})
  states: ReportState[];
```
it works, but then the recursive model is not specified

**Comment by mmussche2** [comment]
@raymondfeng  I've update @loopback/repository to version 1.14.0 and loopback/repository-json-schema to version 1.10.0, and I still have the issue. 
loopback/openapi-v3 is in version 1.9.6, do I need to update another package ?

**Comment by bajtos** [comment]
@raymondfeng can you PTAL?

**Comment by mmussche2** [comment]
@raymondfeng @bajtos 
Still no progress on this issue ? Is there anything I can provide to help with this ?

**Comment by raymondfeng** [comment]
@mmussche2 Can you verify https://github.com/strongloop/loopback-next/pull/3897?

**Comment by mmussche2** [comment]
@mmussche2 
After importing packages openapi-v3 and repository-json-schema from your branch, I still have an error : 

`RangeError: Maximum call stack size exceeded\n    at Object.entries.forEach (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:95:43)\n    at Array.forEach (<anonymous>)\n    at ReportDefinitionRepository.definePersistedModel (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:91:47)\n    at ReportDefinitionRepository.resolvePropertyType (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:120:20)\n    at Object.entries.forEach (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:96:51)\n    at Array.forEach (<anonymous>)\n    at ReportDefinitionRepository.definePersistedModel (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:91:47)\n    at ReportDefinitionRepository.resolvePropertyType (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:120:20)\n    at Object.entries.forEach (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:96:51)\n    at Array.forEach (<anonymous>)\n    at ReportDefinitionRepository.definePersistedModel (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:91:47)\n    at ReportDefinitionRepository.resolvePropertyType (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:120:20)\n    at Object.entries.forEach (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:96:51)\n    at Array.forEach (<anonymous>)\n    at ReportDefinitionRepository.definePersistedModel (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:91:47)\n    at ReportDefinitionRepository.resolvePropertyType (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:120:20)"`

**Comment by raymondfeng** [comment]
You probably need to import `repository` module too.
