### ISSUE TITLE
[Blog post] Show how to deploy a LB application in a cloud native environment

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#3715]
Part of our production deployment story: https://github.com/strongloop/loopback-next/issues/1054

LoopBack is moving towards the cloud native direction - we have documentation covering how to deploy to kubernetes, start to add health check and distributed tracing as the non-functional requirements to deploy to kubernet clusters. LB has been added as one of the application stacks in [Appsody](https://appsody.dev/), as part of [Kabanero](https://kabanero.io/). 

## Acceptance Criteria 
Taking the shopping example as the starting point, this blog post will explore the steps for deployment.  We might be able to identify gaps in terms of developer experience, through the making of this blog post. 

@raymondfeng, please feel free to edit the description.

**Comment by agnes512** [comment]
This spike https://github.com/strongloop/loopback4-example-shopping/pull/268 might be helpful.

**Comment by dhmlau** [comment]
Closing as done.
