### ISSUE TITLE
Update controller class in package `rest-crud` when id is a required property

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#3728]
connect to https://github.com/strongloop/loopback-next/issues/2036
This is a follow-up story of PR https://github.com/strongloop/loopback-next/pull/3667.
As a quick fix, that PR fixes the controller generator by adding a new prompt `isIdOmitted`, and creating the corresponding controller class differently.

There are two more improvements which need more time to address, so I open a new issue here.

## Suggestion

Update the controller class in `@loopback/rest-crud` to reflect the id property's configuration.

## Acceptance criteria

- [ ] Update the controller class in `@loopback/rest-crud` package, so that it generates the correct schema for id property. See [discussion](https://github.com/strongloop/loopback-next/pull/3667#discussion_r322959181) and [discussion](https://github.com/strongloop/loopback-next/pull/3667#discussion_r323592252)

**Comment by bajtos** [comment]
> (Not sure is it a good idea to do them in one story, or should I create two?)

Let's create two stories please.
