### ISSUE TITLE
Implement TestSandbox.writeTextFile

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3731]
_This is a follow-up for the spike #3617._

Implement a helper for writing text files to the test sandbox. 

Example implementation:

https://github.com/strongloop/loopback-next/blob/2848a1b3e4c62da88cfd3edc966e8267768cf326/packages/testlab/src/test-sandbox.ts#L124-L129

## Acceptance criteria

- [x] Implementation
- [x] API documentation
- [x] Automated tests

**Comment by hacksparrow** [comment]
Closed via https://github.com/strongloop/loopback-next/pull/3824
