### ISSUE TITLE
Improve `defineCrudRestController` to create a named controller class

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3732]
_This is a follow-up for the spike #3617._

Improve `@loopback/rest-crud` - modify `defineCrudRestController` to create a named controller class, where the name is based on the model name we are creating the controller for.

Example implementation:

https://github.com/strongloop/loopback-next/blob/2848a1b3e4c62da88cfd3edc966e8267768cf326/packages/rest-crud/src/crud-rest.controller.ts#L260-L267

## Acceptance criteria

- [x] Implementation
- [x] Automated tests
- [x] Update API docs
- [x] Update the example code in `rest-crud` README

**Comment by hacksparrow** [comment]
Closed via https://github.com/strongloop/loopback-next/pull/3842
