### ISSUE TITLE
Add `defineCrudRepositoryClass` - a helper to create a named repository class

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3733]
_This is a follow-up for the spike #3617._

Add `defineCrudRepositoryClass` to `@loopback/rest-crud`, this function should create a named repository class for the given Model class.

Example implementation (notice wrong function name):

https://github.com/strongloop/loopback-next/blob/2848a1b3e4c62da88cfd3edc966e8267768cf326/packages/rest-crud/src/repository-builder.ts#L14-L36

## Acceptance criteria

- [ ] Implementation
- [ ] Automated tests
- [ ] API docs
- [ ] Add a code example to `rest-crud` README

**Comment by hacksparrow** [comment]
Closed via https://github.com/strongloop/loopback-next/pull/3867
