### ISSUE TITLE
authorization: workaround userToPrinciple replaces expected securityId

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-next#3766]
# Steps to reproduce

I tried to write a custom `Authorizer` and just logged the `AuthorizationContext` to console. The `securityId` does not contain the expected value.

## Current Behavior

https://github.com/strongloop/loopback-next/blob/7bf6f12f1da721a78071904fa02252577f4d1cba/packages/authorization/src/authorize-interceptor.ts#L155-L164

The provided `securityId` of an user gets replaced by user.id

## Expected Behavior

As UserProfile of `@loopback/security` is now also `Principal`, there is no need for this convertion anymore. The provided `securityId` should be used as provided. The workaround seems not necessary anymore.

## Additional information

```
$ npm ls --prod --depth 0 | grep loopback
+-- @loopback/authentication@3.0.1
+-- @loopback/authorization@0.3.0
+-- @loopback/boot@1.5.6
+-- @loopback/booter-lb3app@1.3.0
+-- @loopback/context@1.23.0
+-- @loopback/core@1.10.2
+-- @loopback/extension-health@0.2.6
+-- @loopback/openapi-v3@1.9.7
+-- @loopback/repository@1.14.0
+-- @loopback/rest@1.19.0
+-- @loopback/rest-explorer@1.3.7
+-- @loopback/service-proxy@1.3.6
+-- loopback@3.2.1
+-- loopback-boot@3.3.0
+-- loopback-component-passport@3.0.0
+-- loopback-connector-mongodb@5.0.0
+-- loopback-connector-mysql@5.4.2
+-- loopback-connector-postgresql@3.7.0
+-- loopback-connector-rest@2.1.0
+-- loopback-datasource-juggler@3.2.0
```

**Comment by jannyHou** [comment]
Good catch. Submitting a PR to fix it.
