### ISSUE TITLE
Node.js cluster integration

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [strongloop/loopback-next#3787]
https://nodejs.org/api/cluster.html

I am looking for adding Node.js cluster features within Loopback API servers, but I could not locate any documentation on the same. 

can you point me to right direction?

**Comment by dhmlau** [comment]
@raymondfeng @bajtos , what's your thoughts on that? Thanks.

**Comment by raymondfeng** [comment]
IMO, you should use a process manager such as https://github.com/strongloop/strong-supervisor or pm2 to enable Node.js cluster.

You should be able to update `index.js` to add cluster enablement too.

**Comment by bajtos** [comment]
As @raymondfeng said, please use a process manager like https://pm2.io if you want to run your Node.js app in a cluster.

**Comment by sudhirvolteo** [comment]
I want to use the cluster in electronjs app. Where pm2 is not available. Then how to use cluster

**Comment by rajdeepsignzy** [comment]
博斯迪瓦莱
