### ISSUE TITLE
[CASCON Workshop] Create the demo app greeter

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#3800]
### Description

We will use greeter application created in https://github.com/jannyHou/cascon-2019/tree/init/demo/greeter as the demo app for CASCON audience.

Create a formal demo app for workshop :

### Acceptance Criteria

- [ ] Break down the implementation of app into 3-4 steps(summarized in [readme](https://github.com/jannyHou/cascon-2019/tree/init/demo/greeter#step-1))
- [ ] Create a different branch for each step
- [ ] Make sure the functionalities work well
- [ ] Include the hands-on exercise instructions in each step's README.md file

**Comment by dhmlau** [comment]
I'm trying out the demo and adding the instructions in https://github.com/strongloop/cascon2019/pull/1.

**Comment by emonddr** [comment]
@agnes512 created her own pull request to continue with the instructions : https://github.com/strongloop/cascon2019/pull/2

**Comment by dhmlau** [comment]
Repo: https://github.com/strongloop/cascon2019

Closing this task as done.
