### ISSUE TITLE
cli model generator it's broken in v1.23.0

### ISSUE THREAD

**Issue by UrielCuriel** [strongloop/loopback-next#3831]
I update my @loopback/cli package to version 1.23.0 and when use the model generator this is the result:
```import {Entity, model, property} from '@loopback/repository';

@model()
export class Test extends Entity {
  @property({
    0: ',
    1: a,
    2: r,
    3: r,
    4: a,
    5: y,
    6: ',
  })
  type?: ;

  @property({
    0: ',
    1: s,
    2: t,
    3: r,
    4: i,
    5: n,
    6: g,
    7: ',
  })
  itemType?: ;

  @property({
    0: s,
    1: t,
    2: r,
    3: i,
    4: n,
    5: g,
    6: [,
    7: ],
  })
  tsType?: ;


  constructor(data?: Partial<Test>) {
    super(data);
  }
}

export interface TestRelations {
  // describe navigational properties here
}

export type TestWithRelations = Test & TestRelations;
```

```@loopback/cli version: 1.23.0

@loopback/* dependencies:
  - @loopback/authentication: ^3.1.0
  - @loopback/boot: ^1.5.7
  - @loopback/build: ^2.0.12
  - @loopback/context: ^1.23.1
  - @loopback/core: ^1.10.3
  - @loopback/metadata: ^1.3.3
  - @loopback/openapi-spec-builder: ^1.2.14
  - @loopback/openapi-v3: ^1.9.8
  - @loopback/repository-json-schema: ^1.10.1
  - @loopback/repository: ^1.15.0
  - @loopback/rest: ^1.20.0
  - @loopback/testlab: ^1.9.0
  - @loopback/docs: ^2.2.0
  - @loopback/example-hello-world: ^1.2.15
  - @loopback/example-log-extension: ^1.2.15
  - @loopback/example-rpc-server: ^1.2.15
  - @loopback/example-todo: ^1.8.1
  - @loopback/example-soap-calculator: ^1.6.16
  - @loopback/service-proxy: ^1.3.7
  - @loopback/http-caching-proxy: ^1.1.14
  - @loopback/http-server: ^1.4.14
  - @loopback/example-todo-list: ^1.11.0
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^1.4.0
  - @loopback/eslint-config: ^4.1.1
  - @loopback/example-express-composition: ^1.7.0
  - @loopback/example-greeter-extension: ^1.3.15
  - @loopback/booter-lb3app: ^1.3.1
  - @loopback/example-lb3-application: ^1.1.15
  - @loopback/example-greeting-app: ^1.2.1
  - @loopback/example-context: ^1.2.15
  - @loopback/repository-tests: ^0.5.0
  - @loopback/extension-health: ^0.2.7
  - @loopback/authorization: ^0.4.0
  - @loopback/rest-crud: ^0.3.1
  - @loopback/security: ^0.1.3
  - @loopback/authentication-passport: ^1.0.0

```
```
node version : v12.10.0
npm version:6.11.3
```

**Comment by sjtai** [comment]
It happens to me too. My environment:

    @loopback/cli version: 1.23.0

    @loopback/* dependencies:
      - @loopback/authentication: ^3.1.0
      - @loopback/boot: ^1.5.7
      - @loopback/build: ^2.0.12
      - @loopback/context: ^1.23.1
      - @loopback/core: ^1.10.3
      - @loopback/metadata: ^1.3.3
      - @loopback/openapi-spec-builder: ^1.2.14
      - @loopback/openapi-v3: ^1.9.8
      - @loopback/repository-json-schema: ^1.10.1
      - @loopback/repository: ^1.15.0
      - @loopback/rest: ^1.20.0
      - @loopback/testlab: ^1.9.0
      - @loopback/docs: ^2.2.0
      - @loopback/example-hello-world: ^1.2.15
      - @loopback/example-log-extension: ^1.2.15
      - @loopback/example-rpc-server: ^1.2.15
      - @loopback/example-todo: ^1.8.1
      - @loopback/example-soap-calculator: ^1.6.16
      - @loopback/service-proxy: ^1.3.7
      - @loopback/http-caching-proxy: ^1.1.14
      - @loopback/http-server: ^1.4.14
      - @loopback/example-todo-list: ^1.11.0
      - @loopback/dist-util: ^0.4.0
      - @loopback/rest-explorer: ^1.4.0
      - @loopback/eslint-config: ^4.1.1
      - @loopback/example-express-composition: ^1.7.0
      - @loopback/example-greeter-extension: ^1.3.15
      - @loopback/booter-lb3app: ^1.3.1
      - @loopback/example-lb3-application: ^1.1.15
      - @loopback/example-greeting-app: ^1.2.1
      - @loopback/example-context: ^1.2.15
      - @loopback/repository-tests: ^0.5.0
      - @loopback/extension-health: ^0.2.7
      - @loopback/authorization: ^0.4.0
      - @loopback/rest-crud: ^0.3.1
      - @loopback/security: ^0.1.3
      - @loopback/authentication-passport: ^1.0.0

    node version: v10.16.3
    npm version: 6.11.3

**Comment by raymondfeng** [comment]
This is a regression introduced by https://github.com/strongloop/loopback-next/commit/eeb1e7987142fcae24209abe9f32c35a89d1b443. I'm fixing it now.

**Comment by raymondfeng** [comment]
Please try @loopback/cli@1.23.1.

**Comment by sjtai** [comment]
v1.23.1 works for me. Thanks for the fixes @raymondfeng.

**Comment by UrielCuriel** [comment]
v1.23.1 works. Thanks @raymondfeng
