### ISSUE TITLE
Unable to remove Ping Controller

### ISSUE THREAD

**Issue by pktippa** [strongloop/loopback-next#3836]
## Steps to reproduce

Even if I remove the ping.controller.ts file, the REST API is still available.

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
Removing ts file does not delete the generated js file. Please run `nom run clean && npm run build`.

**Comment by pktippa** [comment]
thanks @raymondfeng that worked.
