### ISSUE TITLE
How to load an entity with his belongsTo relation in loopback 4

### ISSUE THREAD

**Issue by yanosh1982** [strongloop/loopback-next#3860]
I'm new to loopback 4 and Nodejs. I want to load an Entity named Pratica defining a BelongsTo Relation whose target is another Entity named Stato.

I followed [this tutorial](https://loopback.io/doc/en/lb4/todo-list-tutorial.html) on loopback 4 documentation but it explains how to do it with a HasMany relation.

This is the schema resulting in the api explorer generated by Loopback for the endpoint "/pratiche/{id}" 

```
{
  "protocolloaci": 0,
  "codicepratica": "string",
  "stato": {
    "stato": 0,
    "descrizione": "string"
  }
}
```

My model, repository and controller class in typescript

pratica.model.ts
```
import { Entity, model, property, belongsTo } from '@loopback/repository';
import { Stato, StatoWithRelations } from './stato.model';

@model({ settings: { strict: false } })
export class Pratica extends Entity {
  
  other properties
  ...

  @belongsTo(() => Stato)
  stato: Stato;
  // Define well-known properties here

  // Indexer property to allow additional data
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [prop: string]: any;

  constructor(data?: Partial<Pratica>) {
    super(data);
  }
}

export interface PraticaRelations {
  stato: StatoWithRelations;
}

export type PraticaWithRelations = Pratica & PraticaRelations;
```

stato.model.ts
```
@model({ settings: {} })
export class Stato extends Entity {
  @property({
    type: 'number',
    id: true,
    required: true,
    generated: false,
  })
  stato: number;

  @property({
    type: 'string',
    required: true,
  })
  descrizione: string;

  constructor(data?: Partial<Stato>) {
    super(data);
  }
}

export interface StatoRelations {
  // describe navigational properties here
}

export type StatoWithRelations = Stato & StatoRelations;
```

pratica.repository.ts
```
export class PraticaRepository extends DefaultCrudRepository<
  Pratica,
  typeof Pratica.prototype.protocolloaci,
  PraticaRelations
  > {

  public readonly stato: BelongsToAccessor<Stato, typeof Pratica.prototype.protocolloaci>;

  constructor(
    @inject('datasources.praticaDs') dataSource: PraticaDsDataSource, @repository.getter('StatoRepository') protected statoRepositoryGetter: Getter<StatoRepository>,
  ) {
    super(Pratica, dataSource);
    this.stato = this.createBelongsToAccessorFor('stato', statoRepositoryGetter);
  }

  async findById(
    id: typeof Pratica.prototype.id,
    filter?: Filter<Pratica>,
    options?: Options,
  ): Promise<PraticaWithRelations> {
    // Prevent juggler for applying "include" filter
    // Juggler is not aware of LB4 relations
    const include = filter && filter.include;
    filter = { ...filter, include: undefined };

    const result = await super.findById(id, filter, options);

    // poor-mans inclusion resolver, this should be handled by DefaultCrudRepo
    // and use `inq` operator to fetch related todos in fewer DB queries
    // this is a temporary implementation, please see
    // https://github.com/strongloop/loopback-next/issues/3195
    if (include && include.length && include[0].relation === 'stato') {
      result.stato = await this.stato(result.protocolloaci);
    }

    return result;
  }
}
```

method of the controller pratica.controller.ts
```
@get('/pratiche/{id}', {
    responses: {
      '200': {
        description: 'Pratica model instance',
        content: { 'application/json': { schema: getModelSchemaRef(Pratica, { includeRelations: true }) } },
      },
    },
  })
  async findById(@param.path.number('id') id: number): Promise<Pratica> {
    return this.praticaRepository.findById(id);
  }
```

This is what i get from the explorer. As you can see the property stato is a number, according to the data base definition of the property. What i expect is a complex object with id and description

```
{
  "protocolloaci": 243835076,
  "codicepratica": "C03301",
  "stato": 271
}
```

My database is Oracle 12

Thank you In advance

**Comment by dhmlau** [comment]
Transferred to `loopback-next` repo as this is related to LoopBack 4.
@agnes512, could you please take a look? Thanks!

**Comment by agnes512** [comment]
Hi @yanosh1982 , I read through the issue, IIUC, you are expecting to get something like from `findById()` method: 
```
{
  "protocolloaci": 243835076,
  "codicepratica": "C03301",
   "stato": {
      "stato": 999,
      "descrizione": "some statoName"
  }
}
```
The problem might lie in the setting of relations. And also, we've released a new version of loopback days ago, which is related to the issue. Could you install the latest loopback package?  

Also, we've simplified the docs because of the new released feature. 
Could you try out the [same tutorial docs](https://loopback.io/doc/en/lb4/todo-list-tutorial-repository.html) again to see if it works?

One last thing is that, in a `belongsTo` relation, the _default_ foreign key name is 'TargetModelName'+'Id'. In your case, the _default_ foreign key name would be `statoId`. 
If you'd like to customize your foreign key name to `stato` in your case, you will need to modify the `@belongsTo` decorator a bit to:

```ts
@model({ settings: { strict: false } })
export class Pratica extends Entity {
//  other properties

  @belongsTo(() => Stato, {name: 'stato'}) // specify `name` field here
  stato: Stato;

  [prop: string]: any;

  constructor(data?: Partial<Pratica>) {
    super(data);
  }
}
export interface PraticaRelations {
  stato: StatoWithRelations;
}
export type PraticaWithRelations = Pratica & PraticaRelations;
```

The `name` field we need to specify here:
```
  @belongsTo(() => Stato, {name: 'stato'}) // specify `name` field here
  stato: Stato;
```
 is the relation name of this relation. i.e the one you defined in `PraticaRelations`:
```
export interface PraticaRelations {
  stato: StatoWithRelations; // stato here is the name of the relation
}
```

Check the [querying related models belongsTo relation](https://loopback.io/doc/en/lb4/BelongsTo-relation.html#querying-related-models) section to learn more about how to load an entity with its belongsTo relation.

Please let me know if this works. Thank you.

**Comment by yanosh1982** [comment]
Thank you @agnes512 for answering. I’ll try as soon as possible. Can you just specify what you mean with “ The problem might lie in the setting of relations”? What do you see in my code that could be wrong exactly? Thanks in advance. Regards

**Comment by agnes512** [comment]
The code is mostly correct.  It's just that our documentation doesn't point out that such changes in the decorator are needed when we use customized names in lb4 relations. Sorry about confusion. The missing part will be updated it in the near future.

Basically, relations have 3 fields in relation metadata: `keyFrom`, `keyTo`, and `name`. Some of them need to be changed to customize the names that are decorated by `@belongsTo`, `@hasMany`, or `@hasOne`. Here's the [PR](https://github.com/strongloop/loopback-next/pull/3805) that I'm currently working on. It explains the metadata in respect of `hasMany` and `hasOne`.

I think the code will work if you download the latest code, update the files, and modify the `@belongsTo` part :smile:

Let me know if you need any help.

**Comment by yanosh1982** [comment]
Hi @agnes512. I've tried to follow again the tutorial with the new version you've released but I still have some problem. i get the result, but the generated schema doesn't seem to be correct. Check out the following.

this is the result i get with the call http://localhost:3000/pratiche/100084146:
```
{
  "protocolloaci": 100084146,
  "stato": {
    "stato": 139,
    "descrizione": "Non accettata"
  }
}
```

and the schema generated by the explorer: 
```
{
  "protocolloaci": 0,
  "stato": {} ->>> there should be some fake value here ?!!?!?
}
```

I paste again the code with some comment, I hope you can tell me what is wrong: 

pratica.model.ts (soruce model)
```
@model()
export class Pratica extends Entity {
  @property({
    type: 'number',
    id: true,
    required: true,
    generated: false,
  })
  protocolloaci: number;

/*
 * to make it work i had to define this as StatoWithRelations, if i define it as stato i get the following 
 *during the npm start execution:
 *Cannot start the application. RangeError: Maximum call stack size exceeded
 *at jsonToSchemaObject (C:\Users\vaccaro\projects\sta-r\assistenza\assistenza- 
 *bo\project\node_modules\@loopback\openapi-v3\src\json-to-schema.ts:36:35)
 */
  @belongsTo(() => Stato, { name: 'stato' })
  stato: StatoWithRelations;

  constructor(data?: Partial<Pratica>) {
    super(data);
  }
}

export interface PraticaRelations {
  stato: StatoWithRelations;
}

export type PraticaWithRelations = Pratica & PraticaRelations;
```

stato.model.ts (target model)
```
@model()
export class Stato extends Entity {
  @property({
    type: 'number',
    id: true,
    required: true,
    generated: false,
  })
  stato: number;

  @property({
    type: 'string',
    required: true,
  })
  descrizione?: string;


  constructor(data?: Partial<Stato>) {
    super(data);
  }
}

export interface StatoRelations {
  // describe navigational properties here
}

export type StatoWithRelations = Stato & StatoRelations;
```

pratica.repository.ts (source model repository)
```
export class PraticaRepository extends DefaultCrudRepository<
  Pratica,
  typeof Pratica.prototype.protocolloaci,
  PraticaRelations
  > {

  public readonly stato: BelongsToAccessor<Stato, typeof Pratica.prototype.protocolloaci>;

  constructor(
    @inject('datasources.operazionaleDS') dataSource: OperazionaleDsDataSource, @repository.getter('StatoRepository') protected statoRepositoryGetter: Getter<StatoRepository>,
  ) {
    super(Pratica, dataSource);
    this.stato = this.createBelongsToAccessorFor('stato', statoRepositoryGetter);

    this.registerInclusionResolver('stato', this.stato.inclusionResolver);
  }
}
```

pratica.controller.ts
```
  @get('/pratiche/{id}', {
    responses: {
      '200': {
        description: 'Pratica model instance',
        content: { 'application/json': { schema: getModelSchemaRef(Pratica, { includeRelations: true }) } },
      },
    },
  })
  async findById(@param.path.number('id') id: number): Promise<Pratica> {
    return this.praticaRepository.findById(id, { include: [{ relation: 'stato' }] });
  }
```

Please notice the comment on the definition of the belongsTo relation in pratica.controller.ts. I think I've done something wrong trying to fix the errors I've made. 

Anyway i can't clarify myself how, but i get some result :)

Thank you, regards

**Comment by agnes512** [comment]
Oops I think I made a mistake, the type of `stato` of `@belongsTo`  should be number (same as the type of the id property in `Stato`)
```

**Comment by yanosh1982** [comment]
With number it works, but the example schema of the explorer i still get 
```
{
  "protocolloaci": 0,
  "stato": 0
}
```

this is the schema definition in the openapi.json
```
"get": {
        "x-controller-name": "PraticaController",
        "x-operation-name": "findById",
        "tags": [
          "PraticaController"
        ],
        "responses": {
          "200": {
            "description": "Pratica model instance",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PraticaWithRelations"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "number"
            },
            "required": true
          }
        ],
        "operationId": "PraticaController.findById"
      }
```

Anyway: as a Java developer i use to query some Entity and the ORM automagically load the related model of the target type (Stato in this case). this prevent to have 2 access on database, one for the source model and one for the target.

Is this possible in LB4 at repository level? In other words, can I in some way do this ?

```
  async doSomething(@param.path.number('id') id: number): Promise<void> {
     Pratica p = this.praticaRepository.findById(id, { include: [{ relation: 'stato' }] });
     console.log(p.stato.descrizione) --- >>> access to the property stato loaded by pratica
  }
```

i've seen this is possible in TypeORM for example.

Thank you

**Comment by agnes512** [comment]
>   Is this possible in LB4 at repository level? In other words, can I in some way do this ?

>  ```async doSomething(@param.path.number('id') id: number): Promise<void> {
>     Pratica p = this.praticaRepository.findById(id, { include: [{ relation: 'stato' }] });
>     console.log(p.stato.descrizione) --- >>> access to the property stato loaded by pratica
>  }```


Yes for sure! Personally I don't touch controllers that much. I usually just test them over repositories. 

Here's the code snippet I used to test out the included models:
```
// define Customer, Order, customerRepo, OrderRepo classes above

   const thor = await customerRepo.create({name: 'Thor'});
      const odin = await customerRepo.create({name: 'Odin'});
      await orderRepo.create({
        description: "Thor's Mjolnir",
        customerId: thor.id,
      });
      const odinOrder = await orderRepo.create({
        description: "Odin's Coffee Maker",
        customerId: odin.id,
      });

      const result = await orderRepo.findById(odinOrder.id, {
        include: [{relation: 'customer'}],
      });
```
Once you set up the models and repositories, you can simply use `find*` methods at repository level.

You can find more tests over relations in [`repository-tests`](https://github.com/strongloop/loopback-next/tree/master/packages/repository-tests/src/crud/relations ) folder, `fixtires` contains all models and repositories.

**Comment by yanosh1982** [comment]
Thank you
