### ISSUE TITLE
OpenApi Decorators doesn't work

### ISSUE THREAD

**Issue by pavelgronsky** [strongloop/loopback-next#3868]
Hello. I'm try to add openapi decorators to my Loopback 4 example.
But this example from doc. doesn't work: https://loopback.io/doc/en/lb4/Decorators_openapi.html

1. What parameters I can used form [OpenAPI-Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md)
2 How I can debug  definition (Ii'm try to write definition used TS)
3. How I can crate API definition by yaml format and add by @api() function? 
4. How I can used all OPEN Api 3 attributes like this: https://editor.swagger.io/

**Comment by dtucker61** [comment]
I may be having the same issue; if not, its related.

I am using an OpenAPI (3.0.2) specification to generate controllers (‘lb4 openapi <my_spec_file>’).

I *think* that the ‘{requestBody : {}}’  and ‘{responses: {}’} json from my spec file should come across in the decorators of the controller’s endpoint method (@operation(.. , .., <response_spec>), @requestBody(<reqest_body_json>)).  

What I see is the the generated controller's decorator's parameters are empty (when I think they should have the json from my spec file.

I did the following to confirm:
1. Built my API from the spec, ‘npm start’ed the server, and then hit the ‘http://localhost:3000/explorer’ endpoint.  The resulting API spec did not include details of the ‘requestBody’ or the ‘response’ body.  -- basically the returned json said { ... "type": object } as opposed to providing actual details.
2.  I manually copied the {responses: {}} json from my API file, and pasted it into the third parameter of the @operation() decorator.  Saved, restarted the server, and hit the same endpoint.  This time I see the ‘{responses: {}}’ json in the ‘http://localhost:3000/explorer’ endpoint.

How do I get lb4 to auto-magically ‘copy’ the {requestBody …} and {resposes ….} into the Controller's appropriate decorator? I don’t see a command line option to turn this on or off (why wouldn’t you want to include this information?).  Is this functionality that is / is not planned?  Where in the code would this functionality live?

BTW -- this is version of lb4:
lb4 --version
@loopback/cli version: 1.24.0

@loopback/* dependencies:
  - @loopback/authentication: ^3.2.1
  - @loopback/authentication-passport: ^1.0.3
  - @loopback/authorization: ^0.4.3
  - @loopback/boot: ^1.5.10
  - @loopback/booter-lb3app: ^1.3.4
  - @loopback/build: ^2.0.15
  - @loopback/context: ^1.23.4
  - @loopback/core: ^1.10.6
  - @loopback/dist-util: ^0.4.0
  - @loopback/docs: ^2.4.0
  - @loopback/eslint-config: ^4.1.3
  - @loopback/example-context: ^1.2.18
  - @loopback/example-express-composition: ^1.8.1
  - @loopback/example-greeter-extension: ^1.3.18
  - @loopback/example-greeting-app: ^1.2.4
  - @loopback/example-hello-world: ^1.2.18
  - @loopback/example-lb3-application: ^1.1.18
  - @loopback/example-log-extension: ^1.2.18
  - @loopback/example-rpc-server: ^1.2.18
  - @loopback/example-soap-calculator: ^1.6.19
  - @loopback/example-todo: ^1.8.4
  - @loopback/example-todo-list: ^1.11.3
  - @loopback/extension-health: ^0.2.10
  - @loopback/http-caching-proxy: ^1.2.0
  - @loopback/http-server: ^1.4.17
  - @loopback/metadata: ^1.3.6
  - @loopback/openapi-spec-builder: ^1.2.17
  - @loopback/openapi-v3: ^1.10.0
  - @loopback/repository: ^1.15.3
  - @loopback/repository-json-schema: ^1.11.0
  - @loopback/repository-tests: ^0.6.0
  - @loopback/rest: ^1.22.0
  - @loopback/rest-crud: ^0.5.0
  - @loopback/rest-explorer: ^1.4.3
  - @loopback/security: ^0.1.6
  - @loopback/service-proxy: ^1.3.10
  - @loopback/testlab: ^1.9.3
