### ISSUE TITLE
lifeCycleObserver is not working with express composition 

### ISSUE THREAD

**Issue by JamilOmar** [strongloop/loopback-next#3878]
1. Have an lb4 app with a lifeCycleObserver.
2. Convert this app into an express app using express composition.
3. The lifeCycleObserver does not run.

## Current Behavior
Is not running after converted into an express app.

## Expected Behavior

lifeCycleObserver running.

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
You need to call lb4app.boot() and start()

**Comment by JamilOmar** [comment]
if you have multiple express apps , you will receive an exception because the port is already in use

**Comment by raymondfeng** [comment]
Yes. I’m working on a fix to disable Http listening for lb4 app.

**Comment by JamilOmar** [comment]
Do you have an approximate time for that release?

**Comment by raymondfeng** [comment]
The quick workaround is to have lb4 app listening a different port with host 127.0.0.1.

**Comment by dhmlau** [comment]
PR https://github.com/strongloop/loopback-next/pull/3879 is in progress.
