### ISSUE TITLE
Improve issue & pull-request templates (connectors, LB3)

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3886]
Copy the pull request and issue templates from loopback (see [`.github`](https://github.com/strongloop/loopback/tree/master/.github)) to the following repositories:

**IMPORTANT: Make sure to change the CLA link in PULL_REQUEST_TEMPLATE to the correct repository-specific URL.**

LB3 core:
- [x] loopback - see https://github.com/strongloop/loopback/pull/4266 and https://github.com/strongloop/loopback/pull/4283
- [x] strong-remoting - see https://github.com/strongloop/strong-remoting/pull/473 and https://github.com/strongloop/strong-remoting/pull/477
- [x] loopback-datasource-juggler - see https://github.com/strongloop/loopback-datasource-juggler/pull/1779 and https://github.com/strongloop/loopback-datasource-juggler/pull/1792

Connectors:
- [x] loopback-connector - see https://github.com/strongloop/loopback-connector/pull/158 and https://github.com/strongloop/loopback-connector/pull/160
- [x] loopback-connector-mysql - see https://github.com/strongloop/loopback-connector-mysql/pull/404
- [x] loopback-connector-postgresql - see https://github.com/strongloop/loopback-connector-postgresql/pull/400
- [x] loopback-connector-mssql - see https://github.com/strongloop/loopback-connector-mssql/pull/217
- [x] loopback-connector-oracle - see https://github.com/strongloop/loopback-connector-oracle/pull/196
- [x] loopback-connector-db2 - see https://github.com/strongloop/loopback-connector-db2/pull/141
- [x] loopback-connector-mongodb - see https://github.com/strongloop/loopback-connector-mongodb/pull/551
- [x] loopback-connector-couchdb2 - see https://github.com/strongloop/loopback-connector-couchdb2/pull/70
- [x] loopback-connector-cloudant - see https://github.com/strongloop/loopback-connector-cloudant/pull/228
- [x] loopback-connector-cassandra - see https://github.com/strongloop/loopback-connector-cassandra/pull/85
- [x] loopback-connector-remote - see https://github.com/strongloop/loopback-connector-remote/pull/101
- [x] loopback-connector-rest - see https://github.com/strongloop/loopback-connector-rest/pull/143
- [x] loopback-connector-soap - see https://github.com/strongloop/loopback-connector-soap/pull/110
- [x] loopback-connector-jsonrpc - see https://github.com/strongloop/loopback-connector-jsonrpc/pull/26
- [x] loopback-connector-openapi - see https://github.com/strongloop/loopback-connector-openapi/pull/6
- [x] loopback-connector-kv-redis - see https://github.com/strongloop/loopback-connector-kv-redis/pull/49
- [x] loopback-connector-grpc - see https://github.com/strongloop/loopback-connector-grpc/pull/11
- [x] loopback-connector-mqlight - see https://github.com/strongloop/loopback-connector-mqlight/pull/48
- [x] loopback-connector-dashdb - see https://github.com/strongloop/loopback-connector-dashdb/pull/90
- [x] loopback-connector-kv-extreme-scale - see https://github.com/strongloop/loopback-connector-kv-extreme-scale/pull/25

LB3 components:
- [x] loopback-component-passport - see https://github.com/strongloop/loopback-component-passport/pull/277
- [x] loopback-component-storage - see https://github.com/strongloop/loopback-component-storage/pull/281
- [x] loopback-component-push - see https://github.com/strongloop/loopback-component-push/pull/190
- [x] loopback-component-explorer - see https://github.com/strongloop/loopback-component-explorer/pull/267
- [x] loopback-component-oauth2 - see https://github.com/strongloop/loopback-component-oauth2/pull/87

**Comment by dhmlau** [comment]
@bajtos, I've added a few more repos per your request. I'm not sure if the following also are considered as LB3 core.

- loopback-boot
- generator-loopback
- loopback-workspace
- loopback-context
- loopback-phase
- loopback-filters
- strong-globalize

I'm referencing the list in here https://github.com/strongloop-internal/scrum-apex/blob/master/repo-list.md.
-

**Comment by dhmlau** [comment]
@nabdelgadir, as discussed, please take this task as a background task, doesn't need to do it all at once. Thank you!!

**Comment by bajtos** [comment]
I am experimenting with a slightly different configuration in loopback-next, see https://github.com/strongloop/loopback-next/pull/4030

**Comment by nabdelgadir** [comment]
All PRs have been merged 🎉
