### ISSUE TITLE
Repository injection bug?

### ISSUE THREAD

**Issue by RipkensLar** [strongloop/loopback-next#3907]
## Steps to reproduce

Checkout https://github.com/RipkensLar/loopback-next
Run "npm test" in the todo example.

## Current Behavior

> 1) todo Repository
>        meta():
>      TypeError: Cannot read property 'find' of undefined
>       at TodoRepository.meta (src\base-repository\base.repository.ts:21:44)
>       at Context.it (src\__tests__\integration\repositories\todo.repository.integration.ts:15:33)

## Expected Behavior

Pass the test. Not sure if I simply injected the repository in base.repository.ts not correctly or this is a bug. When I execute the method via the api-explorer, the method returns the expected object.

**Comment by raymondfeng** [comment]
@RipkensLar You use the following code to instantiate TodoRepository without dependency injection involved. As a result, the `enumRepository` is not set up. You'll have to call `todoRepo.enumRepository = ...` explicitly in your usage.

```ts
before(() => {
    todoRepo = new TodoRepository(new DbDataSource());
  });
```

To enable dependency injection, you have to use some code like the following:

```ts
todoRepo = await app.get<TodoRepository>('repositories.TodoRepository);
```

The `app` is an instance of your app that's booted.

**Comment by RipkensLar** [comment]
Ok, thank you @raymondfeng 
One last question: How can I use a different datasource in my tests? I cannot find something in the documentation about how structure the binding to do that.
Cause I would like to be able to use a testdb for my tests and a different database for my production.
