### ISSUE TITLE
The repository `updateById` method has been storing `undefined` fields as `null`

### ISSUE THREAD

**Issue by fabiohbarbosa** [strongloop/loopback-next#3930]
## Steps to reproduce
1. Should use `mongodb` connector.
2. Create a model object and set up a field as a not required one. Example:
```ts
@model()
export class Purpose extends Entity {
  @property()
  id: number;

  @property()
  value: string;

  @property()
  description?: string;
}
```

3. Set id and number fields of object, but don't set the description.
4. Save this object.
5. Perform an update of this object using `repository.updateById` method.

## Current Behavior

On step 3 the **description** field was not stored on mongo collection. 

As you can see below:
![image](https://user-images.githubusercontent.com/1550941/66833688-2e06ce00-ef54-11e9-8956-b51226229d63.png)

But after update the field was set to **null**.

![image](https://user-images.githubusercontent.com/1550941/66833798-5abae580-ef54-11e9-8b0e-7d742a45ca17.png)

## Expected Behavior

The method `updateById` does not set (and update) undefined fields to null.

## Additional Information
This object is a nested object.

**Comment by fabiohbarbosa** [comment]
The same issue is happening on first field levels as well.

**Comment by bajtos** [comment]
@fabiohbarbosa Can you please share the data object you are sending to `updateById` method? Are you making a REST API call or calling the repository method directly from the code?

**Comment by bajtos** [comment]
It would be best if you could create a small app reproducing the issue (see our [instructions]( https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs)) and include an automated test to cover your use case, so that running `npm test` fails with an error describing the problem.

**Comment by fabiohbarbosa** [comment]
@bajtos I'm calling the repository method directly. 

Sure, I can follow these instructions to generate a small app to be possible reproduce it.

**Comment by fabiohbarbosa** [comment]
After follow the instructions to create a small app, I figure out the `Partial` typescript utility type, it sorted out my problem. I'm going to close the issue. Thanks.

Partial guide: https://www.typescriptlang.org/docs/handbook/utility-types.html#partialt

**Comment by AbhisheKundalia** [comment]
@fabiohbarbosa @bajtos 
I am facing the same issue. Can you please help with what changes did you make to avoid saving undefined fields as null in mongodb?
