### ISSUE TITLE
Migration Guide: Discuss life cycle differences between LB3 and LB4

### ISSUE THREAD

**Issue by aharbis** [strongloop/loopback-next#3935]
## Suggestion

This is a spin-off from a [discussion](https://github.com/strongloop/loopback-next/pull/3922#issuecomment-542093435) on PR #3922.

The purpose of this issue is to discuss the life cycle differences between LB3 and LB4, with a primary goal of identifying pain-points during migration in regards to this topic.

## Use Cases

Some initial topics or points of interest:
- End-to-end request-response sequence
- Out-of-the-box data parsing and validation provided by LoopBack
- Various points to mount custom data validation for a given request / transaction
- Operation hooks(interceptors in lb4)/remote hooks and their equivalents in LB4
- differences of operations between LB3 and LB4 such as boot, injection.
- datasource interceptor in lb4
- How to migrate boot scripts https://github.com/strongloop/loopback-next/issues/3957 might be related

Since it's life cycle, this should be a high level view

## Acceptance criteria

TBD - will be filled by the team.
- [ ] add these topics to the migration guide doc(s)
- [ ] blog about this doc

**Comment by dhmlau** [comment]
@bajtos , could you please add the acceptance criteria so that the team can estimate? Thanks.

**Comment by dhmlau** [comment]
Discussion with @hacksparrow:
It seems like the scope of this task is not clear. A few things to figure out:
- does it make sense to work on this task now while we're still working on other parts of the migration guide?
- does it make sense to break the task down into a smaller pieces first?

**Comment by dhmlau** [comment]
@hacksparrow, let me assign it to you for now, because you indicated that you'll be looking into the scope of this task. Thanks.

**Comment by hacksparrow** [comment]
https://loopback.io/doc/en/lb4/Understanding-the-differences.html already contains the broad differences between LB3 and LB4. 

"Operation hooks(interceptors in lb4)/remote hooks and their equivalents in LB4" is covered by 
https://loopback.io/doc/en/lb4/migration-models-overview.html.

"How to migrate boot scripts #3957 might be related" is covered by https://loopback.io/doc/en/lb4/migration-boot-scripts.html.

"Datasource interceptor in lb4" is covered by https://loopback.io/doc/en/lb4/Interceptor-generator.html.

For the remainder, I am suggesting to create the following pages under the Migration Guide.

- Request-response cycle
	- Document the request response cycle in LB3
	- Document the request response cycle  in LB4
- In-built data parsing and validation
	- Document in-built data parsing and validation in LB3
	- Document in-built data parsing and validation in LB4
- Custom validation
	- Document the points where data (request / transaction) can be accessed and validated in LB3
	- Document the points where data (request / transaction) can be accessed and validated in LB4

Let's create three new tasks, with the sub points as the acceptance criteria.

**Comment by dhmlau** [comment]
+1 in breaking down into smaller tasks or at least PRs. 

I'm good with your updated acceptance criteria. @aharbis, feel free to chime in if there's particular topic you want to cover. 

Not sure how we want to organize the docs, we do have an old issue about documenting the request/response cycle: https://github.com/strongloop/loopback-next/issues/1833.

**Comment by hacksparrow** [comment]
https://github.com/strongloop/loopback-next/issues/1833 could be more detailed under "Behind the Scene", the one in the Migration Guide less detailed. I will close #1833 too.

**Comment by bajtos** [comment]
I am fine with breaking this down into smaller tasks, that way we can better track progress and perhaps even spread the work.

> - Request-response cycle
> - In-built data parsing and validation
> - Custom validation

That's a good plan 👍 

I think it's important to cover application life-cycle and especially the boot process too.

In LB3, the boot process works roughly as follows:
1. Create datasources
2. Define all models
3. Attach models to datasources
4. Run boot scripts

There are few more artifacts loaded by loopback-boot, e.g. middleware, I am not sure where exactly are they placed in the boot sequence.

In LB4, the boot process works differently. Models are define via TS files (there is no boot step for that), middleware is not supported at LB level yet (it's mounted on the top-level Express app), boot scripts are implemented as lifecycle observers that are invoked outside of the boot process, etc.

**Comment by hacksparrow** [comment]
Ok then, another task on booting.

- Booting
  - Document the LB3 bootup process
  - Document the LB4 bootup process

**Comment by dhmlau** [comment]
FYI - there's a GH issue for documenting application life cycle: https://github.com/strongloop/loopback-next/issues/3384.

**Comment by aharbis** [comment]
I am good with splitting this up into tasks, and I agree that these four will cover the large majority of the gaps I was hoping to see filled:

- Request-response cycle
- In-built data parsing and validation
- Custom validation
- Booting

I am happy to assist in contributing, but my expertise at this point is mostly on the LB3 side. I've yet to do many deep-dives into the inner workings of LB4.

**Comment by hacksparrow** [comment]
https://github.com/strongloop/loopback-next/issues/3384 would be a more detailed doc too. The content in the Migration Guide would not be as detailed.

**Comment by hacksparrow** [comment]
Created the following issues:

- https://github.com/strongloop/loopback-next/issues/4838
- https://github.com/strongloop/loopback-next/issues/1833
- https://github.com/strongloop/loopback-next/issues/4839
- https://github.com/strongloop/loopback-next/issues/4837

**Comment by dhmlau** [comment]
Closing as done. Thanks @hacksparrow!
