### ISSUE TITLE
Bad Request Error (400) in PUT request

### ISSUE THREAD

**Issue by AsjadMahmood** [strongloop/loopback-next#3938]
## Additional information
Error message : id property (id) cannot be updated from 6 to 6. 

![put_error](https://user-images.githubusercontent.com/38811693/66902677-7983af80-f01a-11e9-8932-5a2a89848731.PNG)

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@AsjadMahmood, do you have a small sample application that we can reproduce the problem from our side? And please include steps to reproduce as well. Thanks!

**Comment by AsjadMahmood** [comment]
So i am storing array of string in the table. Post request works fine. But when i use put req to update the data from my angular 8 app i got this Bad Request Error (400) id property cannot be updated from 6 to 6. This req works fine with patch but it stores array in {"1","2","3"} this format. I want to it to store like this  ["1","2","3"]. And the type of id is number and i am also sending number. 
Steps to reproduce:
1)Make a table and store some data in array form
2)Make a put req to update the array of data.  
3) Surely you will get this error.
sorry cannot attach the project it's quite big.

**Comment by bajtos** [comment]
@AsjadMahmood please create a small application we can download from github, run `npm install` and then `npm start` or `npm test` to reproduce the problem. We don't have bandwidth to create such application ourselves.
