### ISSUE TITLE
hasOne Relation doesn't work on a MongoDB datasource

### ISSUE THREAD

**Issue by david-saint** [strongloop/loopback-next#3944]
## Steps to reproduce

To reproduce this error all you have to do is start a new lb4 project and follow this tutorial [StrongBlog's first game tutorial part 3](https://strongloop.com/strongblog/building-an-online-game-with-loopback-4-pt3/)

Or
- by creating a new lb4 project
- create a mongodb datasource
- create two models and their repositories (assume character and weapon)
- create a belongsTo relation on one (this works fine)
- Manually create a hasOne relationship on the other model
- in a controller try to do `this.characterRepository.weapon(id).get();

## Current Behavior

Assuming weapons belongsTo Character in a hasOne relatioinship....
the route `/weapons/{id}/character` works, and returns an instance of the character. 
But 
the route `/character/{id}/weapon` returns 
```json
{
    "error": {
        "statusCode": 404,
        "name": "Error",
        "message": "Entity not found: Weapon with id \"constraint {\\\"characterId\\\":\\\"5da7a382ab03e0832eaf2d2c\\\"}\"",
        "code": "ENTITY_NOT_FOUND"
    }
}
```

## Expected Behavior

It should return the instance of the weapon

## Link to reproduction sandbox

https://github.com/david-saint/fg

## Additional information

darwin x64 12.8.1

├── @loopback/boot@1.5.9
├── @loopback/context@1.23.3
├── @loopback/core@1.10.5
├── @loopback/openapi-v3@1.9.10
├── @loopback/repository@1.15.2
├── @loopback/rest@1.21.0
├── @loopback/rest-explorer@1.4.2
├── @loopback/service-proxy@1.3.9
├── loopback-connector-mongodb@4.2.0

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@gobackhuoxing, since you're the author of this blog post series, could you please take a look at this question? Thanks!

**Comment by bajtos** [comment]
How is the foreign key defined? It must be configured as follows:

```ts
@property({
  type: 'string',
  mongodb: {dataType: 'ObjectID'},
}
```

Without that change, MongoDB is not able to match  an ObjectID value from the primary key against a a string value from the foreign key.

**Comment by dhmlau** [comment]
@david-saint, are you still encountering this issue after reviewing @bajtos' [above comment](https://github.com/strongloop/loopback-next/issues/3944#issuecomment-548719844)? Thanks.

**Comment by david-saint** [comment]
No, it worked thanks forgot to close this.
