### ISSUE TITLE
How to migrate (app-level) Express middleware from LB3 to LB4

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3947]
_This is a follow-up for #3718 and #3922._

Write content for `docs/site/migration/express-middleware.md`, explain how to modify a LB4 app with a mounted LB3 app to share the same Express middleware.

Initial setup:

```
lb4-app
 - lb3-app
   - Express middleware
```

The idea is to create a new top-level Express app, where we can mount the middleware to get it executed for requests handled by both LB3 and LB4 routes.

```
express app
 - Express middleware
 - lb4-app
   - lb3-app
```

## Acceptance criteria

- [ ] Migration guide describing manual steps
- Links to the following GH issues:
  - [ ] Allow app developers to configure custom Express middleware #1293
  - [ ] Register Express middleware per route, controller class or controller method #2035

**Comment by bajtos** [comment]
> The idea is to create a new top-level Express app, where we can mount the middleware to get it executed for requests handled by both LB3 and LB4 routes.

Such setup is documented here: https://loopback.io/doc/en/lb4/express-with-lb4-rest-tutorial.html

In the migration guide, we need to describe how to apply the steps outlines in "Creating an Express Application with LoopBack REST API" to an application created by following the steps in [Mounting a LoopBack 3 application](https://loopback.io/doc/en/lb4/migration-mounting-lb3app.html).

Note that in LB3, we are using declarative approach to middleware registration (see `server/middleware.json`). In Express+LB4+LB3 scenario, middleware is registered programmatically from JS/TS code.

/cc @hacksparrow

**Comment by dhmlau** [comment]
#4056 has landed. Closing as done.

**Comment by victor-enogwe** [comment]
In case anyone needs this, the concept of [interceptors](https://loopback.io/doc/en/lb4/Interceptors.html) solved this for me. to simulate a global `app.use` like in express I made a global interceptor. For middlewares scoped to class methods(controllers) create local interceptors and decorate your controller methods with the `@intercept` decorator function. See an example loopback-next helmet middleware [here](https://gist.github.com/victor-enogwe/16cb00c88fc4593fd20a76614d2c95f7)
