### ISSUE TITLE
How to migrate model mixins

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3951]
_This is a follow-up for #3718 and #3922._

Write content for `docs/site/migration/models/mixins.md`, explain how to migrate mixins from LB3 style (see [Mixins docs](https://loopback.io/doc/en/lb3/Defining-mixins.html)) to LB4 style (ES2015 mixin classes).

Important: In LB3, a model class provided both Schema definition, Persistence behavior and Public API. As a result, a single LB3 mixin can contribute to all three layers. In LB4, each of these layers map to a different concept (Model class, Repository class, Controller class). 

## Acceptance criteria

Migration guide describing how to:

- [ ] Convert a LB3 "mixin function" to LB4 mixin class factory
- [ ] Migrate mixins contributing to model schema (e.g. new property definitions)
- [ ] Migrate mixins modifying persistence behavior (e.g. adding new methods, installing operation hooks, etc.)
- [ ] Migrate mixins modifying API (e.g. adding new public methods, modifying remoting metadata of built-in LB3 methods).
- [ ] Migrate mixin configuration in LB3 model definition to LB4 Model and/or Repository.

UPDATED 2020-02-27 by @bajtos: Based on discussion with @emonddr, we decided to removed the following entry, because "mixin model" approach is not documented in LB3:
- Convert a LB3 "mixin model" to LB4 mixin class factory

**Comment by bajtos** [comment]
I think this story may need a spike to explore different LB3 mixin kinds and what's the best way migration path for them.

You can use the following npm search to find existing LB3 mixins as examples to help us better understand different usage patterns we need to cover in our migration guide:

https://www.npmjs.com/search?q=loopback%20mixin

**Comment by emonddr** [comment]
As suggested by @bajtos , we should have a LoopBack 4 topic in our documentation on how to use mixins. https://github.com/strongloop/loopback-next/issues/4759
