### ISSUE TITLE
 [Spike] How to migrate apps using loopback-component-oauth2

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3959]
_This is a follow-up for #3718 and #3922._

Write content for `docs/site/migration/auth/oauth2.md`, explain how to migrate LB3 applications using [loopback-component-oauth2](https://github.com/strongloop/loopback-component-oauth2) to LB4.

## Acceptance criteria

- [ ] Migration guide describing manual steps

**Comment by bajtos** [comment]
I think this story will require a spike first.

**Comment by emonddr** [comment]
This is for server side.

We don't intend on supporting our own oauth2 server module.
 
- Point them to existing infrastructure (social website passport modules)
- need to document how they can use these social website ones. We need to describe the LB4 authentication and authorization steps to enable the usage of access tokens from external oauth2 providers.

**Comment by dhmlau** [comment]
@deepakrkris, I'm assigning this issue to you because you've done part of the work already.

**Comment by jannyHou** [comment]
A proposal:

- Create an example app
- It contains migrated models with their REST apis
- It registers `authenticate` from `loopback-component-oauth2` as a middleware
  - based on PR https://github.com/strongloop/loopback-next/pull/5118
- It secures endpoints with the middleware configuration, adds tests for them
  - e.g. `app.oauth2.authenticate({session: false, scope: 'demo basic'});` 
  - see [reference](https://github.com/strongloop-archive/strong-gateway/blob/b0c80e7dc590708b579b17fe29d53235dd035f18/test/authorize.js#L24-L47)
- Add tests for the created model's endpoints to test the functionalities
  - AuthCodeGrant
  - AuthToken
  - OAuthPermission
  - grant
  - grant password
  - grant refresh token
  - jwt

**Comment by jannyHou** [comment]
Had a chat with @raymondfeng , thank you for providing feedback!

`loopback-component-oauth2` is used to setup a LoopBack application as an oauth2 server. This can be applied in an API gateway application but for the common cases, a LB4 app is usually created as a client app that talk to existing 3rd-party oauth2 servers like [google](https://developers.google.com/identity/protocols/oauth2) or [facebook](https://developers.facebook.com/docs/facebook-login/).
In LoopBack 4, @deepakrkris recently created an example application showing how to login with 3rd-party providers and secure the endpoints in https://github.com/strongloop/loopback-next/tree/master/examples/passport-login. At this stage, it would be good enough for developers to learn and follow.

In case you really want to turn a LoopBack 4 application as an oauth2 provider, here are some tips of how to migrate:
- mount the [`authenticate`](https://github.com/strongloop/loopback-component-oauth2/blob/master/lib/index.js#L24) as an express middleware. (based on PR #5118)
- migrate [models](https://github.com/strongloop/loopback-component-oauth2/tree/master/lib/models) using [lb4 import-lb3-models](https://loopback.io/doc/en/lb4/migration-models-overview.html)

cc @dhmlau are we good to close it?

**Comment by dhmlau** [comment]
@jannyHou, if this issue duplicates what @deepakrkris is doing for https://github.com/strongloop/loopback-next/issues/3958, then let's close this one. Thanks.

**Comment by jannyHou** [comment]
@dhmlau I rephrased the comment a bit. Deepak's repo (and all the examples/feats we’ve implemented so far) uses 3rd-party oauth2 provider like google/fb, but that component sets up a LoopBack app itself as an oauth2 provider, which is a rare use case.
API gateway used it long time ago.
It’s not a dup task, but is a rare case and the migration is very complicated.

**Comment by deepakrkris** [comment]
@jannyHou, agreed, the scope of this task is too broad.
What we can do is come up a lb4 version of the mock provider in https://github.com/strongloop/loopback-next/blob/master/extensions/authentication-passport/src/__tests__/acceptance/fixtures/mock-oauth2-social-app.ts
if this is doable we can close this issue. IMO, lets not go too deep into the details of what loopback-component-oauth2  does.

**Comment by jannyHou** [comment]
Thanks everyone for the discussion, follow up story created in https://github.com/strongloop/loopback-next/issues/5184 🙇‍♀️
