### ISSUE TITLE
BUILD: The test appears in "dist" folder. ( And maybe they shouldn't).

### ISSUE THREAD

**Issue by jotamora** [strongloop/loopback-next#3964]
Hello everyone,

We have seen that when you make the build, the "test" appears in the folder "dist". We understand that the tests are to make sure our code works, we don't need it in the build. 

It would be great an option to prevent the tests from appearing in the dist folder, once the build is done.  If there is something like that, we have not seen it...

Thanks in advance.

**Comment by raymondfeng** [comment]
The `__tests__` appears in `dist` folder as they are transpiled by TypeScript. But they are not part of published npm packages.
