### ISSUE TITLE
Issue when returning Map<string,string> in REST endpoint

### ISSUE THREAD

**Issue by hernanzoide** [strongloop/loopback-next#3972]
I've found that returning a Map<string,string> in a REST endpoint will always return empty results.
Example:

   `async getLabels(@param({ name: 'key', in: 'path' }) key: string): Promise<Map<string, string>>` 

If I convert the map like this it will return properly.

   `const res: any = {}
   map.forEach((v, k) => res[k] = v)
    return res`

Is this a known issue? any other fixes for it?

Thanks, Hernan

**Comment by ThomasGHenry** [comment]
You're certain this isn't a Promise/async/await issue? A more complete example might help. That's my two cents. I'm just passing through.

**Comment by raymondfeng** [comment]
Please note `Map` is not JSON serializable. Please transform it to a JSON-friendly object as the return value.
