### ISSUE TITLE
How Update loopback 4 project of old cli to new cli?

### ISSUE THREAD

**Issue by prth-123** [strongloop/loopback-next#3974]
Hello Team,
I have update by loopback cli to latest version but my loopback 4 was generated from old cli version due to which some dependencies were not install.
But if i am trying to update package.json file manually it is giving issues like of relations, on repository level and all.
So how can i update by  by loopback 4 project to latest version?
Kindly please help me as soon as possible.

**Comment by dhmlau** [comment]
Transferring to `loopback-next` repo.

**Comment by prth-123** [comment]
@dhmlau, First i have update my @loopback/cli and loopback/cli but it doesn't make any change so
I have updated package.json file using this commands 
1) npm i -g npm-check-updates
2) ncu -u
3) npm install

Then i have updated all my package.json file and also node modules due to this some node modules started giving issues.

My old @loopback/cli version = sorry won't getting old version (0.31.3 appx.)

My new @loopback/cli version = 1.23.1
When i am running any lb4 command it is giving me this 

**The project was originally generated by @loopback/cli@<unknown>.
The following dependencies are incompatible with @loopback/cli@1.23.1:
- @loopback/authentication: ^1.0.12 (cli ^3.1.1)
- @loopback/build: ^1.3.0 (cli ^2.0.13)**

and also if i am adding new model repository i had to manually remove the default relation code from the repository and model file.

Can you please help me on this ?

**Comment by raymondfeng** [comment]
See https://loopback.io/doc/en/lb4/Command-line-interface.html#upgrading-loopback-dependencies
and #4080
