### ISSUE TITLE
RFC: Timeline

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#4]
I am proposing to set an aggressive timeline for the next version and remove any features that are not done on time. Preliminary proposal:

 1. 2016-03-31: Any feature that's not *mostly* complete is removed from this release. (The definition of *mostly* is intentionally left vague.)
 2. 2016-04-30: Feature freeze. Any feature/change not finished by this time is removed from the release.
 3. Next 3-6 months: stabilize the code, integrate with APIC and to other tasks required for a new release.

This is based on my experience with managing 3.0 release - even though we drastically reduced the scope of the release in May 2016 (using the rule described in my step 1 above) , the first release candidate was not released until October 2016 and the GA was announced in December. I.e. it took us more than  6 months to finish a release. Projecting this experience to loopback-next and my proposed dates, loopback-next will be released in 2017Q4.

@ritch @raymondfeng @superkhau

**Comment by superkhau** [comment]
Closing in favour of https://github.com/strongloop/loopback-next/wiki/Upcoming-Releases
