### ISSUE TITLE
isTypeResolver issue with pre-compiled models.

### ISSUE THREAD

**Issue by evantrimboli** [strongloop/loopback-next#4001]
## Steps to reproduce

Probably related to this TODO in the code:

```
// TODO(bajtos): support model classes defined via ES5 constructor function
```

As part of our build process, we generate the OpenAPI models (using lb4 openapi), build them and include them as a node package. During startup of the rest server `generateOpenAPISchema()` is called to generate JSON to work with the model definitions.

Inside `isTypeResolver`, it attempts to figure out if the function is a class or a resolver, by using `/^class/.test(fn.toString()`. In my case, this doesn't pass, `fn.toString()` evaluates to:

```
function MainFilters(data) {
    if (data != null && typeof data === 'object') {
        Object.assign(this, data);
    }
}
```
Obviously this is intended as an object constructor, but it's not detected. My current workaround is to check: `if (fn.definition) return false;` which seems to work ok.

## Current Behavior

An exception is thrown by `metaToJsonProperty`. 

## Expected Behavior

An exception is not thrown.

## Link to reproduction sandbox

Not able to provide a simple test, however I hope from the description that it makes sense.

## Additional information

  win32 x64 12.5.0

```
"@loopback/boot": "^1.5.10"
"@loopback/context": "^1.23.4"
"@loopback/core": "^1.10.6"
"@loopback/openapi-v3": "^1.10.0"
"@loopback/rest": "^1.22.0"
"@loopback/rest-explorer": "^1.4.3"
"@loopback/cli": "^1.24.0"
```
## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
Here is the implementation of `isTypeResolver` with the TODO comment:

https://github.com/strongloop/loopback-next/blob/202b2c76b77122654ed81e60afcd2e2a2985de91/packages/repository/src/type-resolver.ts#L36-L52

Here is the thread where we discussed the problem of detecting ES5-style classes, it includes some ideas how to improve the detection too:

https://github.com/strongloop/loopback-next/pull/1618#discussion_r212284888

@evantrimboli How difficult is it for you to upgrade your models from ES5 style to ES6 `class`? I would expect your example code to look like this:

```js
class MainFilters{
  constructor(data) {
    if (data != null && typeof data === 'object') {
        Object.assign(this, data);
    }
  }
}
```

Is the ES5-style code generated by `lb4 openapi`? In that case I think we should change `lb4 openapi` to use ES6 or TypeScript.

Is this ES5 code created by your build step? If that's the case, then can you please change your compiler/transpiler to target ES6? I think `es2017` is even better target - IIRC Node.js 8.x (the oldest LTS version) has full support for ES2017.

Here is a snippet of code from TypeScript output for our [example Todo model](https://github.com/strongloop/loopback-next/blob/64587e198b6b287c01cd7d8e648528746fe2a522/examples/todo/src/models/todo.model.ts) - you can clearly see that it's using ES6 class syntax:

```js
let Todo = class Todo extends repository_1.Entity {
    constructor(data) {
        super(data);
    }
};
```
