### ISSUE TITLE
Controller generated from OpenAPI spec does not support 'multipart/xxx'

### ISSUE THREAD

**Issue by dtucker61** [strongloop/loopback-next#4011]
## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dtucker61** [comment]
I generate an app using 'lb4 app'.  I then add controllers from a previously create OpenAPI spec.  
A particular endpoint is used to upload a set of files ( per OpenAPI recommendations):
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "properties": {
                  "file": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "format": "binary"
                    }
                  }
                }
              }
            }

When I generate the controllers (lb4 openapi <my spec file>, I get a controller that looks like:
  @operation('post', '/endpoint')
  async testEndpoint(@requestBody() _requestBody: {
  file?: Buffer[];
}): Promise<any> {
    throw new Error('Not implemented');
  }

I then start my controller, and use a curl command to exercise the endpoint:
  curl -v -F 'file=@/tmp/junk.txt' http://localhost:3000/endpoint

I expect to see the loopback application throw an error.  That would tell me application control passed to the  testEndpoint() method.  I did not see that (i.e. the application did not attempt to call the testEndpoint() method.

What I did see is the following response from curl:{"error":{"statusCode":415,"name":"UnsupportedMediaTypeError","message":"Content-type multipart/form-data; boundary=------------------------04dc18517f45830e does not match [application/json].","code":"UNSUPPORTED_MEDIA_TYPE"}}

I looked around at existing issues.  I see issue# 1873 and issue# 2666 which talk about supporting 'multipart/form' context.  It is not clear if these are in the current product (see my version info below), and if so, how to get the 'lb4 opeapi' to generate the support. 

Thanks for your feedback.
---------------------------------------------
lb4 --version
@loopback/cli version: 1.24.0

@loopback/* dependencies:
  - @loopback/authentication: ^3.2.1
  - @loopback/authentication-passport: ^1.0.3
  - @loopback/authorization: ^0.4.3
  - @loopback/boot: ^1.5.10
  - @loopback/booter-lb3app: ^1.3.4
  - @loopback/build: ^2.0.15
  - @loopback/context: ^1.23.4
  - @loopback/core: ^1.10.6
  - @loopback/dist-util: ^0.4.0
  - @loopback/docs: ^2.4.0
  - @loopback/eslint-config: ^4.1.3
  - @loopback/example-context: ^1.2.18
  - @loopback/example-express-composition: ^1.8.1
  - @loopback/example-greeter-extension: ^1.3.18
  - @loopback/example-greeting-app: ^1.2.4
  - @loopback/example-hello-world: ^1.2.18
  - @loopback/example-lb3-application: ^1.1.18
  - @loopback/example-log-extension: ^1.2.18
  - @loopback/example-rpc-server: ^1.2.18
  - @loopback/example-soap-calculator: ^1.6.19
  - @loopback/example-todo: ^1.8.4
  - @loopback/example-todo-list: ^1.11.3
  - @loopback/extension-health: ^0.2.10
  - @loopback/http-caching-proxy: ^1.2.0
  - @loopback/http-server: ^1.4.17
  - @loopback/metadata: ^1.3.6
  - @loopback/openapi-spec-builder: ^1.2.17
  - @loopback/openapi-v3: ^1.10.0
  - @loopback/repository: ^1.15.3
  - @loopback/repository-json-schema: ^1.11.0
  - @loopback/repository-tests: ^0.6.0
  - @loopback/rest: ^1.22.0
  - @loopback/rest-crud: ^0.5.0
  - @loopback/rest-explorer: ^1.4.3
  - @loopback/security: ^0.1.6
  - @loopback/service-proxy: ^1.3.10
  - @loopback/testlab: ^1.9.3

**Comment by bajtos** [comment]
@raymondfeng could you PTAL?

**Comment by raymondfeng** [comment]
See a working example at https://github.com/strongloop/loopback-next/pull/4801
