### ISSUE TITLE
Import OpenAPI Spec

### ISSUE THREAD

**Issue by rahulrkr08** [strongloop/loopback-next#4032]
Is there any possible way to import/creation of models, repositories, controllers from OpenAPI Spec?

**Comment by raymondfeng** [comment]
Use `lb4 openapi` command. See https://loopback.io/doc/en/lb4/OpenAPI-generator.html

**Comment by rahulrkr08** [comment]
Thanks @raymondfeng. Is there any support for the array type parameter in controllers.
e.g. `@param.query.array('someparam') someparam: string[]`

**Comment by raymondfeng** [comment]
See https://loopback.io/doc/en/lb4/apidocs.openapi-v3.param.array.html
