### ISSUE TITLE
[docs] (@loopback/authentication-passport) Ambiguous experimental warning

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#4035]
## Steps to reproduce

1. Go to [@loopback/authentication-passport](https://www.npmjs.com/package/@loopback/authentication-passport) README
2. Look at experimental notice

![image](https://user-images.githubusercontent.com/25147899/68002866-eeefb100-fca5-11e9-97b5-f0bb614e517f.png)

## Current Behavior

The latest version of the package is no longer 0.x.y. Hence, there's ambiguity on whether or not breaking changes are going to appear in the minor or patch updates.
## Expected Behavior

The message should either be tweaked to reflect the latest versioning or removed entirely.

## Link to reproduction sandbox

https://www.npmjs.com/package/@loopback/authentication-passport

## Additional information

N/A

## Related Issues

N/A

**Comment by achrinza** [comment]
Sorry it should be tagged as `docs`, not bug.

**Comment by dhmlau** [comment]
@jannyHou , assigning this to you as you're working on PR #4036.

**Comment by jannyHou** [comment]
Fixed in https://github.com/strongloop/loopback-next/pull/4036 :)
