### ISSUE TITLE
docs(Testing your application): invalid import paths & broken test datasource example

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#4052]
There are 2 issues, but they are within the same docs page.

### Issue 1

1. Check [Testing your application](https://loopback.io/doc/en/lb4/Testing-your-application.html).
2. Look at any `model`, `repository` or `controller` import:
![image](https://user-images.githubusercontent.com/25147899/68293095-36bc7100-00c8-11ea-9353-082e8c717521.png)

### Issue 2

1. Check [Testing your application#use-test-data-builders](https://loopback.io/doc/en/lb4/Testing-your-application.html#use-test-data-builders)
2. Try to follow and create a test datasource:

![image](https://user-images.githubusercontent.com/25147899/68294013-11c8fd80-00ca-11ea-907e-2519b767173e.png)

### Issue 1

The docs are assuming `__tests__` are located outside `src`. This is not the case with `@loopback/cli@1.24.0`.

### Issue 2

The docs state to create a `new juggler.DataSource`. However, this is not the same signature as what's generated by `@loopback/cli@1.24.0`.

Later in the docs, a `src/tests/helpers/database.helpers.ts` file is created. A `new REPOSITORY_NAME()` object is instantiated with the test database.

This causes the error below in `/src/repositories/[REPOSITORY_NAME].repository.ts` when the datasource is injected into the repository class (which `extends DefaultCrudRepository`).

```
(alias) const testdb: juggler.DataSource
  import testdb
  Argument of type 'DataSource' is not assignable to parameter of type 'DbDataSource'.
  Type 'DataSource' is missing the following properties from type 'DbDataSource': start, stopts(2345)
```

### Issue 1

The import paths should be updated to `../../[controller/model/repository/]`. Modify path as necessary to fit the specific docs examples.

### Issue 2

The docs should be updated with the current best-practice method.

## Link to reproduction sandbox

https://github.com/achrinza/loopback-next-docs-issue-sandbox

## Additional information

```bash
$ node -e 'console.log(process.platform, process.arch, process.versions.node)'
win32 x64 10.16.0

$ npm ls --prod --depth 0 | grep loopback
+-- @loopback/boot@1.5.9
+-- @loopback/context@1.23.3
+-- @loopback/core@1.10.5
+-- @loopback/openapi-v3@1.9.10
+-- @loopback/repository@1.15.2
+-- @loopback/rest@1.21.0
+-- @loopback/rest-explorer@1.4.2
+-- @loopback/service-proxy@1.3.9
`-- loopback-connector-postgresql@3.8.0

$ npm ls -g --depth 0 | grep loopback
+-- @loopback/cli@1.24.0
```

## Related Issues

N/A

**Comment by raymondfeng** [comment]
@achrinza Thank you for reporting. The issue has been fixed recently at https://github.com/strongloop/loopback-next/blob/master/docs/site/Testing-your-application.md. Once we publish a new release, the web site will be refreshed.

**Comment by achrinza** [comment]
@raymondfeng I’ve checked the docs you’ve linked, Issue 1 has been resolved, but the docs for creating the test data source is the same. Unless if I’m mistaken, this still results in Issue 2 occurring.
