### ISSUE TITLE
Releasing breaking changes

### ISSUE THREAD

**Issue by MarkOfSine** [strongloop/loopback-next#4053]
Issues with:
**server.rest.ts** in @loopback/rest

Two questions:
1. 
This bug was caused by checking in **AND** releasing a simple **compilation!** breaking change.
At this stage in the maturity of loopback 4 ecosystem this should just fundimentally not be possible! 
How did it happen?
What has been done to mitigate this issue?

2. 
How can we as downstream developers and users of the package rely on releases if this is happening?
Should we not be keeping up to date with the latest releases? If not what is the alternative?
At this stage, with loopback 3 being end-of-life'd and loopback 4 being barely production ready (in reality it is not) how are we as developers supposed justify migrating!?

3. Finally. This occured 13! days ago?
Why is it taking so long to resolve? This type of error should have been picked up and resolved practially immediatialy.

## Steps to reproduce

Upgrade to latest release

## Current Behavior

**server.rest.ts** causes a compilation error

## Expected Behavior

**server.rest.ts** does not causes compilation error

Notes:
This has been fixed in commit: 05b4beede234c8d9f9b6a5a9c95f458d6d0fec8a
But still not released!?

**Comment by raymondfeng** [comment]
@MarkOfSine What's the breaking for you? https://github.com/strongloop/loopback-next/commit/05b4beede234c8d9f9b6a5a9c95f458d6d0fec8a is only for docs.

Did you upgrade to TypeScript 3.7.2? If so, you have to wait for a new release from LB4. Please note we intentionally set `typescript` dependencies with `~3.6.4` as TypeScript releases do not follow SEMVER semantics.

We're trying our best to follow SEMVER and only release breaking changes with new majors.

**Comment by MarkOfSine** [comment]
@raymondfeng Not sure why commit reference did not come through correctly. This is the one I meant:
[https://github.com/strongloop/loopback-next/commit/ab47ef63adc01b170ddc537ca973da631c5a8d8f](https://github.com/strongloop/loopback-next/commit/ab47ef63adc01b170ddc537ca973da631c5a8d8f)

I see we did upgrade to typescript 3.7.2. Will revert to ~3.6.4

So then the question becomes where should we read to see what library versions we should be sticking with and see release notes for a release.

thanks for coming back on this.

**Comment by raymondfeng** [comment]
For any release of `@loopback/cli`, you can run `lb4 -v` to display a list of module versions that are released together. Such collection of versions are guaranteed to be compatible.

**Comment by raymondfeng** [comment]
See https://loopback.io/doc/en/lb4/Command-line-interface.html#upgrading-loopback-dependencies

**Comment by raymondfeng** [comment]
I just created a PR that adds `lb4 version` to make version check and upgrade a bit eaisier.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/pull/4080
