### ISSUE TITLE
Implement lint-staged

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#4062]
## Suggestion

Today I come to propose adding an option to the CLI to use lint-staged and generate the corresponding code (also would have to adapt `@loopback/build` because I think it does not work correctly).

For those who do not know what [`lint-staged`](https://github.com/okonet/lint-staged) is (as its description says):
> Run linters against staged git files and don't let 💩 slip into your code base!

## Use Cases

This is responsible for helping to upload a good code to git without syntactic errors.

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dhmlau** [comment]
@frbuceta, I'd like to understand more about your feature proposal.  We already have linter in the scaffolded LB applications so what additional benefits would it bring if lint-staged is used? Thanks.

**Comment by frbuceta** [comment]
@dhmlau `lint-staged` only runs `eslint` for the files that are `staged` in git, it makes the tests much faster.

Currently I have tried to configure it but since the @ loopback / build package is used, I think it does not work with lb-eslint or lb-prettier because I have not found any improvement and in other repositories yes

**Comment by achrinza** [comment]
I'm not too familiar on what `@loopback/build` does other than being a wrapper, but I'd like to drop in my thoughts on this:

I think adding `lint-staged` will help speed up the pre-commit process as what @frbuceta said, it only targets staged files.

I think it should be an addition but not a replacement for the linting process as not everyone necessarily follows the same linting process (e.g monorepo with custom linting), perhaps a `lint:staged` npm script?

**Comment by raymondfeng** [comment]
You can update your application package.json with `lint-staged` dev dependency and a script such as `lint:staged`. Do you think it's worth to have a choice for `lb4 app` command?

**Comment by frbuceta** [comment]
> You can update your application package.json with `lint-staged` dev dependency and a script such as `lint:staged`. Do you think it's worth to have a choice for `lb4 app` command?

@raymondfeng I think it would be good to be able to select this option, in large projects with a lot of test it can be a great improvement in the time of processing the tests

But I think this doesn't work with lb-eslint because it doesn't select the files that says `lint-staged`

I take this in conclusion because it takes longer than in other projects with more test than I have

**Comment by frbuceta** [comment]
# With eslint & prettier
![Screenshot 2019-11-19 at 00 33 25](https://user-images.githubusercontent.com/13822438/69105165-ca982080-0a6a-11ea-926a-5e8d1987518b.png)

Video: https://drive.google.com/open?id=1mPLqqFbTwFhOI7nbYKODiRdmCQQq8Fg4

# With lb-eslint & lb-prettier
![Screenshot 2019-11-19 at 00 38 08](https://user-images.githubusercontent.com/13822438/69105189-da176980-0a6a-11ea-80da-8c84e5c5fa5c.png)

Video: https://drive.google.com/open?id=13DVP3xYZ0vmMkUSNT_CNalvVls8gbxWe

**Comment by achrinza** [comment]
Based on the the videos by @frbuceta, `lb-eslint` and `lb-prettier` aren't accepting the same arguments. `lint-staged` may not be included as part of `lb4 app`, but it's behaviour (or how to set it up with `lint-staged`) could be better documented.

**Comment by frbuceta** [comment]
> Based on the the videos by @frbuceta, `lb-eslint` and `lb-prettier` aren't accepting the same arguments. `lint-staged` may not be included as part of `lb4 app`, but it's behaviour (or how to set it up with `lint-staged`) could be better documented.

Correct, it seems that lb-eslint and lb-prettier do not accept the same parameters as eslint or prettier

**Comment by frbuceta** [comment]
I leave this piece of code here ... with this lint-staged works correctly
```
  "lint-staged": {
    "*.{ts,js}": [
      "lb-eslint --report-unused-disable-directives --fix",
      "lb-prettier --write",
      "git add"
    ]
  },
```

I will try to make a pr with an option in loopback cli

**Comment by dhmlau** [comment]
@frbuceta, thanks for picking up this issue. I just assigned it to you. Thanks.

**Comment by dhmlau** [comment]
Closing as PR #5616 has landed.
