### ISSUE TITLE
Read through all the LBn wiki

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#407]
- [ ] https://github.com/strongloop/loopback-next/wiki

**Comment by Setogit** [comment]
Before the wiki, TypesScript tutorial book below is concise and readable, yet covers many key concepts of TypeScript.
https://basarat.gitbooks.io/typescript/docs/getting-started.html

**Comment by Setogit** [comment]
// README guidelines
http://loopback.io/doc/en/contrib/README-guidelines.html

**Comment by Setogit** [comment]
OpenAPI spec: https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md

Resources (hierarchically defined schema) are assembled into Spec which conforms to/validates with the OpenAPI standard.

**Comment by Setogit** [comment]
comments:
- [ ] `app.sequence(MySequence)` -- app.setSequence ?
- [ ] `app.bind('hello').to('world'); // ContextKey='hello', ContextValue='world'`
  -- app.contextualize('hello').to('world')?  to disambiguate wit Function.prototype.bind

**Comment by Setogit** [comment]
Note: advanced topics are mostly empty:
Context (Advanced)
Sequence (Advanced)
Testing Your Application (Advanced)

**Comment by Setogit** [comment]
Finished reading all the available sections.
closing the task.
