### ISSUE TITLE
OpenAPI 'date' is always 'date-time'

### ISSUE THREAD

**Issue by evantrimboli** [strongloop/loopback-next#4085]
## Steps to reproduce

Generate models using openapi where the format is 'date'. Try and pass a date value '2019-01-01' to the server.

## Current Behavior

The server returns 422 unprocessable entity because the date doesn't match the 'date-time' format.

## Expected Behavior

It should parse the date only format.

## Additional information

This is caused by the line here:

https://github.com/strongloop/loopback-next/blob/cd5ca92c368ae35bc10d8847b3b0d379f7196544/packages/repository-json-schema/src/build-schema.ts#L234

The models themselves don't get a decorator attached to indicate the type of format, so at this point it's not possible to infer whether it's a date or a date-time.

```
"@loopback/boot": "^1.5.10"
"@loopback/context": "^1.23.4"
"@loopback/core": "^1.10.6"
"@loopback/openapi-v3": "^1.10.0"
"@loopback/rest": "^1.22.0"
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by marioestradarosa** [comment]
Hi @evantrimboli , this is not a bug. The Type Script `Date` in Loopback can hold `date`and `date-time` values. However, for your use case you can easily specify your final format  in the model class like so:

```ts
 @property({
    type: 'date',
    required: true,
    jsonSchema: {
      format: 'date',
    },
  })
  start_date: string;
```

With the above `jsonSchema` property we are hinting the schema validator.
I hope this helps.

**Comment by evantrimboli** [comment]
Is there a reason that isn't generated by default? Currently when I generate the models they only get decorated with:

`@property()`.

**Comment by marioestradarosa** [comment]
Sorry, what is the command you are using ?.  Are you generating from an openAPI spec file to the lb4 classes ? or you are using the `lb4 model` generator ?

**Comment by evantrimboli** [comment]
From the openAPI spec:

`lb4 openapi --force --yes --url file,yaml`

**Comment by marioestradarosa** [comment]
I believe it should ask for the final datatype (time, date, date-time) when we generate the model class from `lb4 model` also. A feature request possible that you can open ?

In case you can share your openApi file that would be great.

**Comment by marioestradarosa** [comment]
ok, I just tried with the `pets.yml` sample and indeed it is generating the properties, except that you will have to specify manually the final `date | datetime | time` . That's the current state of the generator, perhaps we need to add this feature.

```ts
@property({required: true})
  name: string;

  /**
   * 
   */
  @property()
  start_date: date;
```

**Comment by bajtos** [comment]
Thank you @marioestradarosa for helping to troubleshoot the issue ❤️ 

I agree that this looks like a limitation of the current implementation of `lb4 openapi` command. Personally, I consider it as a bug. IMO, `lb4 openapi` should generate models that allow all values that are valid according to the original spec.

@evantrimboli would you like to contribute a fix yourself?

I am not familiar with `lb4 openapi` implementation, it was written by @raymondfeng. Having said that, I think here is the place where to start looking:

https://github.com/strongloop/loopback-next/blob/9569a120278070d00977919f7da224c8d3dc3ac1/packages/cli/generators/openapi/schema-helper.js#L134-L219

**Comment by achrinza** [comment]
Glanced at the code, looks like this is responsible for setting the js type:

https://github.com/strongloop/loopback-next/blob/9569a120278070d00977919f7da224c8d3dc3ac1/packages/cli/generators/openapi/schema-helper.js#L235-L259

Also need to update this unit test:

https://github.com/strongloop/loopback-next/blob/9569a120278070d00977919f7da224c8d3dc3ac1/packages/cli/test/unit/openapi/schema-helper.unit.js#L43-L45

I don't mind creating a PR

**Comment by raymondfeng** [comment]
@achrinza PR is welcome!

**Comment by evantrimboli** [comment]
To clarify, this means that when the server receives the value it will be of type `string`, not of type `Date`?

**Comment by achrinza** [comment]
@evantrimboli If my understanding is correct, then yes; when generated via the CLI, the type in Javascript would be a `string`, though it can always be changed manually.

**Comment by marioestradarosa** [comment]
> To clarify, this means that when the server receives the value it will be of type `string`, not of type `Date`?

@evantrimboli , can you verify if the issue is resolved?. IMHO  it should validate the date field, meaning it should send an error when adding invalid dates automatically. The following excerpt do that in the `jsonChema` validator's hint.  

```ts
 @property({
    type: 'date',
    required: true,
    jsonSchema: {
      format: 'date',
    },
  })
  start_date: string;
```

**Comment by evantrimboli** [comment]
I'm not sure having it as a string is the best resolution for this. I would have expected that the type would still be a date, since it can still be represented as such.

**Comment by marioestradarosa** [comment]
Correct, I am using the regular `lb4 model` CLI and whenever I selected a date field, it automatically create this line in the model file:

```ts
  @property({
    type: 'date',
    required: true,
  })
  thedate: string;
```

If `thedate` field is not date-time but only date as in my case, then the `post`   method to create a new row sends back the `unprocessable entity` error. So we need to hint the schema validator we need a `date` and not `date-time` by just adding the following line.  It checks if the `date` is valid or not as expected.

```ts
@property({
    type: 'date',
    required: true,
    jsonSchema: {
      format: 'date',
    },
  })
  start_date: string;
``` 
In your case, your OpenAPI yml file has this information, so we need to reflect that in a similar fashion by the CLI. IMHO that should be the solution.

@raymondfeng  any thoughts?

**Comment by achrinza** [comment]
@evantrimboli I believe it's `string` still may be the best solution as using `Date` means converting from OpenAPI's definition to Javascript's definition of  a `Date`. [OpenAPI uses RFC3339](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types) while Javascript uses [ISO 8601](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). It should be left to the database to resolve it to a valid datetime format.

I agree with @marioestradarosa that the CLI should generate new models' `date` property with the JSON Schema format attribute. Correct me if I'm wrong, but that should created as a separate issue.

**Comment by marioestradarosa** [comment]
@achrinza you did a great job on the PR, which means now the property is of type `string`, but we might need to add the following for the validator: `date` or `datetime` or `time` which is information coming along in the `yml` file, otherwise it won't throw `unprocessable entity` but it will not validate a `date` anymore, or maybe I am not looking it from the right point of view ?.

```ts
jsonSchema: {
      format: 'date',
    },
```

**Comment by achrinza** [comment]
@marioestradarosa I think the issue is 2-fold:

1. CLI OpenAPI code generation should include the following to ensure proper client-side code generation:

    ```typescript
    @property({
       ...
      jsonSchema: {
        format: 'date',
      },
    })
   exampleAttribute: string;
   ```

2. There should be validation for `type: 'date'`.

    For this issue, I created a quick lb4 app with a model that has a `Date`-type property. This is what I've observed:

    * Sending a full date-time (e.g. `2019-11-21T01:27:27.497Z`) still works
    * Sending a `full-date` (e.g. `2019-11-21` results in a `422: UnprocessableEntityError`
    * The generated OpenAPI spec is:
        ```json
        ...
        TestProp {
          "type": "string",
          "format": "date-time"
        ```

On second glance, I agree that the PR hasn't fully resolved lb4's validation issue.

**Comment by achrinza** [comment]
@marioestradarosa Please disregard my previous comment. The issue is resolved by adding:

```typescript
jsonSchema: {
  format: 'date',
},
```

I've made a test lb4 app and found that the validation is working fine when the above code is added. A `422: UnprocessableEntityError` is thrown whenever the request does not provide a valid OpenAPI `date` type.

I agree that the `jsonSchema` property should be added as part of the CLI OpenAPI and Model code generation. However, there is an issue: `lb4 model` only provides a `Date` type for properties.

![image](https://user-images.githubusercontent.com/25147899/69295663-692ca900-0c46-11ea-9be1-c3e4dccd4f49.png)

**Comment by marioestradarosa** [comment]
`lb4 openapi`  is consuming a file in OpenAPI format that contains the date, date-time or time final data type already. so it would be easier for this cli to generate the appropriate `jsonSchema`. 

 As for the `lb4 model` I believe that we might need to ask for it. But this issue relates only to `lb4 openapi`.  You can go ahead and 1) reopen the issue or 2) create a new one with a request for this feature and finally add this piece of code 💯

**Comment by achrinza** [comment]
@marioestradarosa 

> 
> `lb4 openapi` is consuming a file in OpenAPI format that contains the date, date-time or time final data type already. so it would be easier for this cli to generate the appropriate `jsonSchema`.
> 

Yup, I think we can agree that's the best way forward

>
> As for the lb4 model I believe that we might need to ask for it. But this issue relates only to lb4 openapi. You can go ahead and 1) reopen the issue or 2) create a new one with a request for this feature and finally add this piece of code 💯
>

Apologies if it's my ignorance, but my main concern isn't about adding it as a feature, more of the function of `@property({type: 'Date'})` and it's relevance (e.g. what does it do?).
