### ISSUE TITLE
delete model controller repository 

### ISSUE THREAD

**Issue by swd72** [strongloop/loopback-next#4097]
i want delete model controller repository created

**Comment by dhmlau** [comment]
@swd72, I'm not sure if i understand your question.  Could you please elaborate some more and perhaps provide an example? Thanks.

**Comment by raymondfeng** [comment]
@swd72 Do you want to delete `*.ts` files for such artifacts? If so, you need to run `npm run clean && npm run build` to re-transcompile into `dist`.

**Comment by dhmlau** [comment]
@swd72, we believe we've answered your question through the [above comment](https://github.com/strongloop/loopback-next/issues/4097#issuecomment-557394173). Closing this issue.  Thanks.
