### ISSUE TITLE
Need to deleteall sample code 

### ISSUE THREAD

**Issue by AnanthGopal** [strongloop/loopback-next#4111]
Can you provide the deleteall  sample code?

**Comment by jannyHou** [comment]
@AnanthGopal If you mean sample code that calls `modelRepository.deleteAll`,  check [some example](https://github.com/strongloop/loopback-next/blob/cb4178ad5b5011a3a22107ae243e1372fe465676/examples/todo-list/src/__tests__/helpers.ts#L152-L154).

Actually you can search through in this repository with keyword `deleteAll` :p lots of its usage.
https://github.com/strongloop/loopback-next/search?q=deleteAll&unscoped_q=deleteAll

**Comment by dhmlau** [comment]
@AnanthGopal, did @jannyHou answer your question? Thanks.

**Comment by AnanthGopal** [comment]
yes. thank you @jannyHou
