### ISSUE TITLE
.env undefined outside Repository Class

### ISSUE THREAD

**Issue by vikramkh** [strongloop/loopback-next#4128]
## Steps to reproduce

Repository Class: 

```ts
console.log(process.env.STRIPE_SECRET_KEY)
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY)
export class MyRepository extends DefaultTransactionalRepository<
```

.env file:
```
STRIPE_SECRET_KEY= 'secretkey'
```

application.ts:
```ts
this.projectRoot = __dirname;
    // Customize @loopback/boot Booter Conventions here
    this.bootOptions = {
      controllers: {
        // Customize ControllerBooter Conventions here
        dirs: ['controllers', 'modules'],
        extensions: ['.controller.js'],
        nested: true,
      },
      repositories: {
        dirs: ['repositories'],
        extensions: ['.repository.js'],
        nested: true,
      },
    };

    dotenv.config();
    dotenvExt.load({
      schema: '.env',
      errorOnMissing: false,
    });
  }
```

## Current Behavior

If you call process.env variables that are defined in the .env file outside (above) any repository class, the variables are undefined. They work perfectly outside (above) any controller class, however.

## Expected Behavior

process.env.STRIPE_SECRET_KEY should be returning a value rather than undefined outside the repository class.

## Additional information

```
darwin x64 10.15.3
├── @loopback/boot@1.5.10
├── @loopback/build@2.0.15
├── @loopback/context@1.23.4
├── @loopback/core@1.10.6
├── @loopback/openapi-v3@1.10.0
├── @loopback/repository@1.15.3
├── @loopback/rest@1.22.0
├── @loopback/rest-explorer@1.4.3
├── @loopback/service-proxy@1.3.10
├── @loopback/testlab@1.9.3
├── @loopback/tslint-config@2.1.0
├── loopback-connector@4.9.0
├── loopback-connector-kv-redis@3.0.2
├── loopback-connector-postgresql@3.8.0
├── loopback4-authentication@2.1.3
├── loopback4-authorization@2.3.2
├── loopback4-soft-delete@1.2.0
```

**Comment by bajtos** [comment]
Thank you for reporting this issue. I strongly suspect there is some code in your application that loads the repository or service class (calls `import` or `require` from the repository/service `.ts` file) **before** the boot process is started. 

Please create a small app we can use to reproduce the issue as explained in [Reporting issues](https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs). We can't really help you without seeing the entire source code.

**Comment by vikramkh** [comment]
Hi @bajtos! Thanks. You were correct. I was actually using code from a cloned repo that i had hardly changed. I wasn't too familiar with env processes, and it turns out there was a .env.defaults file along with the .env file, which I'm guessing was delaying the loading in of the .env file. So I moved my keys over to the .env.defaults file
