### ISSUE TITLE
Missing `models/index.ts` after running `lb4 openapi` command

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#4135]
After running the `lb4 openapi` command, models are created.  However, there is no `index.ts` file in the `models` folder.  If I generate the repository for the model, it will get an error during build:

```

src/repositories/pet.repository.ts:2:33 - error TS2307: Cannot find module '../models'.

2 import {Pet, PetRelations} from '../models';
                                  ~~~~~~~~~~~
```

It's not a big issue because I can create the index.ts, but generating the index.ts when generating the models would be helpful. 

## Steps to reproduce

1. In a LB application, run 
```
lb4 openapi https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.yaml
```

2. It creates the Pet and NewPet and Error model. 
3. Create datasource and Repository
4. Run `npm run build`. 
It gives the error I've shown above because of the missing index.ts to export the models. 
UPDATED: it also complained about `PetRelations` not imported in the repository class but it actually doesn't exist. 

### Acceptance Criteria
- [ ] Generate the index.ts model file during `lb4 openapi`
- [ ] the generated code should not have any build error. (about the missing `{ModelName}Relations`)

**Comment by raymondfeng** [comment]
Interesting. Maybe it's a regression? The index files should be updated by calling https://github.com/strongloop/loopback-next/blob/master/packages/cli/lib/artifact-generator.js#L127

**Comment by dhmlau** [comment]
I'm using the latest version of @loopback/cli.  Just tried it again to make sure, it doesn't generate the index.ts.

**Comment by dhmlau** [comment]
After I added the index.ts in `models` folder, I realized that `PetRelations` does not exist but the repository class is referencing it. 

I've put my project in https://github.com/dhmlau/openapi-test.
