### ISSUE TITLE
BelongsTo relation with include and OASGraph return string error

### ISSUE THREAD

**Issue by stoffason** [strongloop/loopback-next#4137]
Hi, 
Firstly, you guys are doing great work, but I'm struggling to solve this issue...

If I create a simple relation (either HasOne or HasMany) with belongsTo, and also use registerInclusionResolver etc to include the related model in the result, everything works fine and I get a nested result as expected..
But if using OASGraph, I receive a string error

example..

storage.model
```typescript
@property({
        type: 'string',
        id: true,
        mongodb: {
            dataType: 'objectID'
        }
    })
    storageId: string;

@hasMany(() => CompanyPolicy, {keyTo: 'governingDivisionPolicy'})
    governingGroupPolicy?: CompanyPolicy[]


```

company-policy.model 
```typescript
@property({
        type: 'string',
        id: true,
        mongodb: {
            dataType: 'objectID'
        }
    })
    companyPolicyId: string;

@belongsTo(() => Storage, {keyFrom: 'governingGroupPolicy', keyTo: 'storageId'})
    governingGroupPolicy?: string

export interface CompanyPolicyRelations {
    governingGroupPolicy?: StorageWithRelations,
}
export type CompanyPoliciesWithRelations = CompanyPolicy & CompanyPolicyRelations;
```

I need to query companyPolicy and get the Storage details under "governingGroupPolicy"
If via REST, no problem and I get the correct expected result

```typescript
{ companyPolicyId: "whatever",
    governingGroupPolicy : {
            whatever: "whatever else"
}
```

if I query with GraphiQL 
```typescript
query {
  	companyPoliciesFind {
               companyPolicyId
               governingDivisionPolicy {
                    storageId
             }
      }
}
```

I get an error 
```json
{
  "errors": [
    {
      "message": "Field \"governingGroupPolicy\" must not have a selection since type \"String\" has no subfields.",
      "locations": [
        {
          "line": 4,
          "column": 28
        }
      ]
    }
  ]
}
```

It seems to be because the belongsTo - governingGroupPolicy is a string in the model.
Howerver if I change from "string" to "Storage", loopback complains and wont start

```typescript
@belongsTo(() => Storage, {keyFrom: 'governingGroupPolicy', keyTo: 'storageId'})
    governingGroupPolicy?: Storage

// Gives Error: Invalid type for property type
```
Any advise to solve would be appreciated.
Thanks

**Comment by bajtos** [comment]
From what I remember, our `@belongsTo` decorator is a bit broken. While it looks like it should be applied on the navigational property (e.g. `customer` in `Order` model), in fact you need to apply it on the foreign key. Also the foreign key must have a different name than the navigational property (the relation name).

Can you try to following code?

```ts
class CompanyPolicy /*...*/ {
  @property({
        type: 'string',
        id: true,
        mongodb: {
            dataType: 'objectID'
        }
    })
    companyPolicyId: string;

  @belongsTo(() => Storage, {keyTo: 'storageId'})
  governingGroupPolicyId?: string
}

export interface CompanyPolicyRelations {
    governingGroupPolicy?: StorageWithRelations,
}
export type CompanyPoliciesWithRelations = CompanyPolicy & CompanyPolicyRelations;
```

I you provide an app I can run to reproduce the problem and try different solutions, then I may be able to help you more. See https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs

**Comment by stoffason** [comment]
Thanks, I managed to find a workaround...
The way I understand it, the error is caused by my controller response...
company-policy.controller
```typescript
responses: {
            '200': {
                description: 'CompanyPolicy model instance',
                content: {'application/json': {schema: getModelSchemaRef(CompanyPolicy, {
                            includeRelations: true,
                            title: 'CompanyPolicyFind'
                        })
                    }
                },
            },
        },
```

Seems that OASGraph needs the response to give a reference to the BelongsTo model, but the function getModelSchemaRef will always build the schema with the BelongsTo as string. 

If I manually build the response schema like below, it works fine.

```typescript
responses: {
            '200': {
                description: 'Array of CompanyPolicy model instances',
                content: {
                    'application/json': {
                        schema: {
                            type: 'array',
                            items: {
                                properties:
                                        { companyPolicyId: { type: 'string'}},
                                        { governingGroupPolicy: { '$ref': '#/components/schemas/Storage'}},
                                    ]
                                })
                            }
                        },
                    },
                },
            },
        },
```
Found that I also need to manually build the response when any freeform object is needed to be returned via "additionalProperties: {}" rather than using the getModelSchemaRef function.

**Comment by dhmlau** [comment]
@stoffason, are you good with closing this issue? Thanks.

**Comment by stoffason** [comment]
Thanks,

Found a clean solution, and may be worth updating the documentation. (just needed Grapql to populate relation on BelongsTo)
Work around was to simply create another property on the model containing the  "BelongsTo"
So.. set the belongsTo with the ForeignKey as a string, and create a new property which needs to be populated separately 

_model_
```    
@property(Storage)
    governingGroupPolicy?: Storage


@belongsTo(() => Storage, {keyFrom: 'governingGroupPolicyFk', keyTo: 'storageId'})
governingGroupPolicyFk?: string
```
Then adjust the repository to populate the new property
_repository_
```
...
public readonly governingGroupPolicy: BelongsToAccessor<
        Storage,
        typeof CompanyPolicy.prototype.companyPolicyId
        >

...
 this.governingGroupPolicy = this.createBelongsToAccessorFor(
            'governingGroupPolicyFk', getStorageRepository
        );

this.registerInclusionResolver('governingGroupPolicy', this.governingGroupPolicy.inclusionResolver);
```
Then can use the "getModelSchemaRef" function as usual
_controller_
```
responses: {
            '200': {
                description: 'CompanyPolicy model instance',
                content: {'application/json': {
                        schema: getModelSchemaRef(CompanyPolicy, {
                            title: 'companyPolicyFind',
                            includeRelations: true
                        })
                    }
                },
            },
        },
```
and in GraphiQl can then just query the new property, and disregard the foreginKey property

```
query {
  	companyPoliciesFind {
               companyPolicyId
               governingDivisionPolicy {
                    storageId
                    ...
             }
      }
}
```
all good and working
