### ISSUE TITLE
Add a rate limiter to the app

### ISSUE THREAD

**Issue by shadyanwar** [strongloop/loopback-next#4139]
Hello,
What are your top recommendations to apply rate limiting to an LB4 app? Use an interceptor for example? Or is there a different approach you recommend? If interceptors are the way to go, I would be grateful if you give some pointers on how to best do it. Can we make use of an NPM package like [this one](https://www.npmjs.com/package/limiter)?

I believe such an important topic can be warranted its own section in the documentation. I have come across a quick mention of rate limiting in the [Architectural challenges](https://loopback.io/doc/en/lb4/core-tutorial-part2.html) page.

**Comment by raymondfeng** [comment]
It should be fairly easy to add an interceptor to call the rate limiting module.

**Comment by shadyanwar** [comment]
@raymondfeng The [documentation](https://loopback.io/doc/en/lb4/Interceptors.html#global-interceptors) isn't clear to me. To implement a global interceptor, I have to add this to `index.js`:

```ts
app
  .bind('interceptors.RateLimiter')
  .toProvider(RateLimiterProvider)
  .apply(asGlobalInterceptor('rateLimit'));

```

I have created this provider class:
```ts
export class RateLimiter {
  constructor() { }
  value() {
    var RateLimiter = require('limiter').RateLimiter;
    var limiter = new RateLimiter(500, 'hour');
    
    // Throttle requests
    limiter.removeTokens(1, function(err: any, remainingRequests: any) {
      console.log("remainingRequests", remainingRequests);
      if (err) console.log("err", err);
  
    });

    return true;
    };
  }
```

Highly appreciate your advice.

**Comment by dhmlau** [comment]
@shadyanwar, are you using the `lb4 interceptor` to create the interceptor? 
I think if you specify that it's a global interceptor, you don't need to bind it to the app yourself. 

Reference: https://medium.com/loopback/learning-loopback-4-interceptors-part-1-global-interceptors-163a7c5701b9.

**Comment by raymondfeng** [comment]
@shadyanwar Please mark the issue closed if @dhmlau answered your question.

**Comment by dhmlau** [comment]
@shadyanwar , we believe we've answered your question, so I'm closing this issue now. Thanks.
