### ISSUE TITLE
elasticsearch

### ISSUE THREAD

**Issue by ScottYueqiang** [strongloop/loopback-next#4159]
Do you have an example of how loopback4 operates elasticsearch

**Comment by dhmlau** [comment]
@ScottYueqiang, there's a community connector for ElasticSearch: https://loopback.io/doc/en/community/Elasticsearch-connector.html. It should be compatible with LoopBack 4 as well. Could you please give it a try? 

cc @raymondfeng

**Comment by ScottYueqiang** [comment]
@dhmlau thanks
