### ISSUE TITLE
Loopback does not process MSSQL tables with 100 million records

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#4160]
## Steps to reproduce

At work we have started using Loopback with Mssql and today we have to connect with a view with 100 million records but I have encountered a problem ... Tedious is not able to process the request with filters or limit

## Current Behavior

I am currently returning an error like this:
`?filter[limit]=100: 500 RequestError: Timeout: Request failed to complete in 15000ms`

## Expected Behavior

I expected him to give me 100 records back, I don't expect them to ever return me, it's impossible in less than 15 seconds!

## Additional information

`darwin x64 13.1.0`
```
├── @loopback/authentication@3.2.2
├── @loopback/boot@1.5.11
├── @loopback/context@1.23.5
├── @loopback/core@1.10.7
├── @loopback/openapi-v3@1.10.1
├── @loopback/repository@1.15.4
├── @loopback/rest@1.23.0
├── @loopback/rest-explorer@1.4.4
├── @loopback/security@0.1.7
├── @loopback/service-proxy@1.3.11
└── loopback-connector-mssql@3.6.0

```

**Comment by frbuceta** [comment]
I am not sure if this is a Loopback or Tedious or loopback-connector-mssql problem

**Comment by raymondfeng** [comment]
Can you set `DEBUG=loopback:connector:mssql` to see what SQL statement is sent?

**Comment by frbuceta** [comment]
> Can you set `DEBUG=loopback:connector:mssql` to see what SQL statement is sent?

### LOG
```
> DEBUG=loopback:connector:mssql node -r source-map-support/register .

  loopback:connector:mssql Settings: {"name":"MsSQL","connector":"mssql","url":"","host":"XXX.XX.XXX.XXX","port":1433,"user":"XXXX","password":"XXXX","database":"XXXX","debug":false} +0ms
Server is running at http://127.0.0.1:3000
  loopback:connector:mssql Connection established:  XXX.XX.XXX.XXX +454ms
  loopback:connector:mssql SQL: SELECT * FROM (SELECT [id],[codigo],[fecha],[latitud],[longitud],ROW_NUMBER() OVER ( ORDER BY [id]) AS RowNum FROM [dbo].[TABLE]
) AS S
 WHERE S.RowNum > 0 AND S.RowNum <= 100
 Parameters: [] +22s
  loopback:connector:mssql Result: {"code":"ETIMEOUT","number":"ETIMEOUT","originalError":{"message":"Timeout: Request failed to complete in 15000ms","code":"ETIMEOUT"},"name":"RequestError","precedingErrors":[]} undefined +16s
Unhandled error in GET /vehicle-positions?filter[limit]=100: 500 RequestError: Timeout: Request failed to complete in 15000ms
    at Request.userCallback (/Users/fran/Projects/.XXXX/XXXX-api/node_modules/mssql/lib/tedious.js:637:19)
    at Request.callback (/Users/fran/Projects/.XXXX/XXXX-api/node_modules/tedious/lib/request.js:40:14)
    at Connection.message (/Users/fran/Projects/.XXXX/XXXX-api/node_modules/tedious/lib/connection.js:2417:24)
    at Connection.dispatchEvent (/Users/fran/Projects/.XXXX/XXXX-api/node_modules/tedious/lib/connection.js:1247:15)
    at MessageIO.<anonymous> (/Users/fran/Projects/.XXXX/XXXX-api/node_modules/tedious/lib/connection.js:1107:14)
    at MessageIO.emit (events.js:210:5)
    at Message.<anonymous> (/Users/fran/Projects/.XXXX/XXXX-api/node_modules/tedious/lib/message-io.js:40:14)
    at Message.emit (events.js:215:7)
    at endReadableNT (/Users/fran/Projects/.XXXX/XXXX-api/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:1077:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by frbuceta** [comment]
This cannot be ... in the repository there is not the same code as in my node_modules

https://github.com/strongloop/loopback-connector-mysql/blob/ddb1c96a761443c9cc3b17a7630e87b22dd740ee/lib/mysql.js#L497-L501

And I have the latest version installed. How can this be! `v3.6.0`

**Comment by dhmlau** [comment]
@frbuceta, https://github.com/strongloop/loopback-connector-mysql/blob/ddb1c96a761443c9cc3b17a7630e87b22dd740ee/lib/mysql.js#L497-L501 is the same as the one in the `master` branch.  The latest version is `v5.4.2` https://github.com/strongloop/loopback-connector-mysql/releases. Perhaps you can try to update to 5.4.2?

**Comment by frbuceta** [comment]
> @frbuceta, https://github.com/strongloop/loopback-connector-mysql/blob/ddb1c96a761443c9cc3b17a7630e87b22dd740ee/lib/mysql.js#L497-L501 is the same as the one in the `master` branch. The latest version is `v5.4.2` https://github.com/strongloop/loopback-connector-mysql/releases. Perhaps you can try to update to 5.4.2?

Ouch sorry, I got confused as a repository so it wasn't in code, it's not MySQL, it's MsSQL

Sorry

**Comment by frbuceta** [comment]
> @frbuceta, https://github.com/strongloop/loopback-connector-mysql/blob/ddb1c96a761443c9cc3b17a7630e87b22dd740ee/lib/mysql.js#L497-L501 is the same as the one in the `master` branch. The latest version is `v5.4.2` https://github.com/strongloop/loopback-connector-mysql/releases. Perhaps you can try to update to 5.4.2?

https://github.com/strongloop/loopback-connector-mssql/blob/88eb7fe9e206b32dc6524d2455dac9e71f8b6ce9/lib/mssql.js#L486-L507

This is where I think the code is failing, I am using MsSQL 2019

**Comment by bajtos** [comment]
@frbuceta have you tried to enable `supportsOffsetFetch` setting? I think it's set in datasource configuration.

```json
{
  "connector": "mssql",
  "supportsOffsetFetch": true,
}
```

**Comment by frbuceta** [comment]
> @frbuceta have you tried to enable `supportsOffsetFetch` setting? I think it's set in datasource configuration.
> 
> ```json
> {
>   "connector": "mssql",
>   "supportsOffsetFetch": true,
> }
> ```

#### Well, this is giving me errors on all endpoints
`Unhandled error in POST /auth/sign-in: 500 RequestError: Invalid usage of the option NEXT in the FETCH statement.`

`Unhandled error in GET /vehicle-positions?filter[limit]=100: 500 RequestError: Invalid usage of the option NEXT in the FETCH statement.`

**Comment by raymondfeng** [comment]
Your SQL Server seems to be an old version that does not allow `FETCH/NEXT`.

**Comment by frbuceta** [comment]
> Your SQL Server seems to be an old version that does not allow `FETCH/NEXT`.

I am using:
```
Microsoft SQL Server 2017 (RTM-GDR) (KB4505224) - 14.0.2027.2 (X64) 
	Jun 15 2019 00:26:19 
	Copyright (C) 2017 Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)
```

I don't know if this version supports it but it's recent ... 2017

**Comment by dougal83** [comment]
@frbuceta What is the SQL query produced with `"supportsOffsetFetch": true,`?

**Comment by frbuceta** [comment]
> @frbuceta What is the SQL query produced with `"supportsOffsetFetch": true,`?

`SQL: SELECT [id],[codigo],[fecha],[latitud],[longitud],ROW_NUMBER() OVER ( ORDER BY [id]) AS RowNum FROM [dbo].[xxxxxxxxxxxxxxxxxxx] OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY Parameters: [] +22s`

**Comment by dougal83** [comment]
Is the SQL malformed? [MSSQL Fiddle](https://dbfiddle.uk/?rdbms=sqlserver_2017&fiddle=b68110d48ff0096f2c9f72583ac117f8)

**Comment by achrinza** [comment]
@frbuceta @raymondfeng Looks like it is a malformed SQL query. `FETCH NEXT` must be preceded by `ORDER BY` as part of the [SELECT - ORDER BY Clause](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-ver15).

So the query should be:
```sql
SELECT
    [id],
    [codigo],
    [fecha],
    [latitud],
    [longitud],
    ROW_NUMBER() OVER (ORDER BY [id]) AS RowNum
FROM [dbo].[xxxxxxxxxxxxxxxxxxx] 
ORDER BY RowNum
OFFSET 0 ROWS
FETCH NEXT 100 ROWS ONLY
```

[The offending line](https://github.com/strongloop/loopback-connector-mssql/blob/master/lib/mssql.js#L425-L434):
```typescript
function buildLimit(limit, offset) {
  if (isNaN(offset)) {
    offset = 0;
  }
  let sql = 'OFFSET ' + offset + ' ROWS';
  if (limit >= 0) {
    sql += ' FETCH NEXT ' + limit + ' ROWS ONLY';
  }
  return sql;
}
```

Potential fix:
```typescript
function buildLimit(limit, offset) {
  if (isNaN(offset)) {
    offset = 0;
  }
  let sql = 'ORDER BY RowNum OFFSET ' + offset + ' ROWS';
  if (limit >= 0) {
    sql += ' FETCH NEXT ' + limit + ' ROWS ONLY';
  }
  return sql;
}

**Comment by achrinza** [comment]
@frbuceta When runnng the SQL query directly on SSMS or Azure Data Studio, does it also cause a timeout / take longer than 15 seconds?

> SELECT * FROM (SELECT [id],[codigo],[fecha],[latitud],[longitud],ROW_NUMBER() OVER ( ORDER BY [id]) AS RowNum FROM [dbo].[TABLE]

@frbuceta When running this query on SSMS or Azure Data Studio, does it result in a similar error or response that's taking longer than 15 seconds?

**Comment by frbuceta** [comment]
> > SELECT * FROM (SELECT [id],[codigo],[fecha],[latitud],[longitud],ROW_NUMBER() OVER ( ORDER BY [id]) AS RowNum FROM [dbo].[TABLE]
> 
> @frbuceta When running this query on SSMS or Azure Data Studio, does it result in a similar error or response that's taking longer than 15 seconds?

`[S0001][102] Sintaxis incorrecta cerca de 'WEB_VGPS_Posiciones_Total'.` in DataGrid

**Comment by achrinza** [comment]
Apologies, I didn't quote the full SQL query:

```sql
SELECT *
FROM (
    SELECT [id],
    [codigo],
    [fecha],
    [latitud],
    [longitud],
    ROW_NUMBER() OVER ( ORDER BY [id]) AS RowNum FROM [dbo].[TABLE]
) AS S
WHERE S.RowNum > 0 AND S.RowNum <= 100;
```

Does the above result in a successful execution?

**Comment by frbuceta** [comment]
> Apologies, I didn't quote the full SQL query:
> 
> ```sql
> SELECT *
> FROM (
>     SELECT
>         [id],
>         [codigo],
>         [fecha],
>         [latitud],
>         [longitud],
>         ROW_NUMBER() OVER (ORDER BY [id]) AS RowNum FROM [dbo].[TABLE]
> ) AS S
> WHERE S.RowNum > 0 AND S.RowNum <= 100;
> ```
> 
> (Modify the table and column names where needed)
> 
> The above query is the one generated by lb4 as per your comment: [#4160 (comment)](https://github.com/strongloop/loopback-next/issues/4160#issuecomment-556017460)
> 
> Does the above result in a successful execution?

Well this seems to still not work
It has been charging for 2 minutes and it's not over yet

**Comment by achrinza** [comment]
@frbuceta Thanks for the reply; this seems more of an issue with the generated query. Try using this `filter` HTTP query:

`?filter[where][id][lte]=100`

If you want to have an offest (e.g. 101 200):

`?filter[where][id][gt]=100&[where][id][lte]=200`

(Replace `id` with the ID column of the table if necessary)

This should prevent MSSQL from going through all 100 million records.

**Comment by frbuceta** [comment]
> @frbuceta Thanks for the reply; this seems more of an issue with the general efficiency of generated query, less of lb4 not being able to process it. Try using this `filter` REST query:
> 
> `?filter[where][id][lt]=100`
> 
> If you want to have an offset (e.g. `id` = 100 - 199):
> 
> `?filter[where][id][gte]=100&filter[where][id][lt]=200`
> 
> (Replace `id` with the ID column of the table if necessary)
> 
> This should prevent MSSQL from going through all 100 million records/tuples and use the PK indexes.
> 
> Another way might be:
> 
> `?filter[where][id][between][0]=101&filter[where][id][between][1]=199`
> 
> If that doesn't work, [try creating a different filter](https://loopback.io/doc/en/lb3/Where-filter.html).

I am waiting for your PR in the MSSQL repository to be approved, this will not work for me because my ids are very large, they do not go 1, 2, 3, 4 ...

**Comment by bajtos** [comment]
Just for reference, here is the pull request that should fix the issue: strongloop/loopback-connector-mssql#219

**Comment by achrinza** [comment]
@frbuceta As per-https://github.com/strongloop/loopback-connector-mssql/pull/219#issuecomment-564408013, the PR may take a bit longer to be complete. Maybe you could test the PR first by setting the `package.json` dependency?

```
"loopback-connector-mssql": "git+https://github.com/achrinzafork/loopback-connector-mssql.git/daf6eb31e06772a91c3aa355e8fc313a6a1651d4"
```

If the issue still persists, then we know there's another issue that needs resolving.

**Comment by frbuceta** [comment]
> @frbuceta As per-[strongloop/loopback-connector-mssql#219 (comment)](https://github.com/strongloop/loopback-connector-mssql/pull/219#issuecomment-564408013), the PR may take a bit longer to be complete. Maybe you could test the PR first by setting the `package.json` dependency?
> 
> ```
> "loopback-connector-mssql": "git+https://github.com/achrinzafork/loopback-connector-mssql.git#daf6eb31e06772a91c3aa355e8fc313a6a1651d4"
> ```
> 
> If the issue still persists, then we know there's another issue that needs resolving.

No problem mate. Yes, I try it now and I tell you

**Comment by frbuceta** [comment]
I can confirm that now it does crash loopback but the query still doesn't work, even doing a "where" still doesn't work. Any ideas?

**Comment by achrinza** [comment]
@frbeutica Does it immediately crash upon startup or only when the query is executed? Using the same logging env. variable as stated in an earlier comment, what’s the error that occurs?

________________________________

**Comment by frbuceta** [comment]
> @frbeutica Does it immediately crash upon startup or only when the query is executed? Using the same logging env. variable as stated in an earlier comment, what’s the error that occurs?

No error occurs, the request is processed indefinitely

**Comment by achrinza** [comment]
@frbeutica The issue really seems to be an inefficient generated query. I’ll see if I can replicate a similar environment in my lab.

In the mean time, just to rule out any variables, could you run this query on the MSSQL client of your choice:

```SQL
SELECT id, codigo, fecha, latitud, longitud
FROM [TableName]
ORDER BY id
OFFSET 0 ROWS
FETCH NEXT 100 ROWS ONLY
```

I’m out and about right now, so the query may have some typos; modify that and [TableName] accordingly.

If the query above runs

________________________________

**Comment by frbuceta** [comment]
> @frbeutica The issue really seems to be an inefficient generated query. I’ll see if I can replicate a similar environment in my lab. In the mean time, just to rule out any variables, could you run this query on the MSSQL client of your choice: ```SQL SELECT id, codigo, fecha, latitud, longitud FROM [TableName] ORDER BY id OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY ``` I’m out and about right now, so the query may have some typos; modify that and [TableName] accordingly. If the query above runs then we can rule out the MSSQL server as a variable.

MsSQL has nothing to do with what it seems ... the query took 6 seconds (98ms)
Thank you very much for the help

**Comment by frbuceta** [comment]
WOW... When I do a "where" this is the call to MsSQL

```SQL
SELECT [id],[codigo],[fecha],[latitud],[longitud]
FROM [dbo].[web_vgps_posiciones]
ORDER BY [id]
```

**Comment by achrinza** [comment]
> MsSQL has nothing to do with what it seems ... the query took 6 seconds (98ms)
> Thank you very much for the help

@frbuceta Thanks for the report, I think it's almost safe to say that LoopBack 4's generated T-SQL query doesn't scale very well. I'll look more into it and drop any significant updates here.

Just to be sure, can you try to create a "GET endpoint" on an lb4 connector that executes (and potentially return) the below function?
```typescript
RepoNameHere.execute('SELECT id, codigo, fecha, latitud, longitud FROM [TableName] ORDER BY id OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY')
```

This above function should allow raw SQL queries passed through lb4. If this also fails to execute, then the efficiency issue may be beyond the generated T-SQL query.

> 
> 
> WOW... When I do a "where" this is the call to MsSQL
> 
> ```sql
> SELECT [id],[codigo],[fecha],[latitud],[longitud]
> FROM [TableName]
> ORDER BY [id]
> ```
> 
> After waiting a couple of minutes it seems that the explorer tried to process what I asked of the database but in the end I don't just like that
> ![Screenshot 2019-12-16 at 02 41 20](https://user-images.githubusercontent.com/13822438/70873323-98b4a400-1fad-11ea-90ff-a4364c8b310f.png)

That seems unusual. Was that query pulled from the lb4 logs or MSSQL itself? Also, does this happen with my fork of the MSSQL connector and/or the original MSSQL connector? I'll try to check on my end to confirm this issue.

**Comment by frbuceta** [comment]
> ```ts
> RepoNameHere.execute('SELECT id, codigo, fecha, latitud, longitud FROM [TableName] ORDER BY id OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY')
> ```
This is working

> ```sql
> SELECT
>     [id],
>     [codigo],
>     [fecha],
>     [latitud],
>     [longitud],
>     ROW_NUMBER() OVER (ORDER BY [id]) AS RowNum
> FROM [dbo].[TABLE]
> WHERE RowNum > 0 AND RowNum <= 100;
> ```
This query is not correct. It seems he doesn't like syntax

> ```sql
> SELECT
>     [id],
>     [codigo],
>     [fecha],
>     [latitud],
>     [longitud],
>     ROW_NUMBER() OVER (ORDER BY [id]) AS RowNum
> FROM [dbo].[TABLE] 
> ORDER BY RowNum
> OFFSET 0 ROWS
> FETCH NEXT 100 ROWS ONLY;
> ```
This works, it took 14 seconds

**Comment by achrinza** [comment]
@frbuceta Could you post the generated query when using the fork and `"supportsOffsetFetch": true`? AFAIK this should work fine if the above queries can be executed.

**Comment by frbuceta** [comment]
> @frbuceta Could you post the generated query when using the fork and `"supportsOffsetFetch": true`? AFAIK this should work fine if the above queries can be executed.

Unless you have it wrong, I have it defined as follows.
![Screenshot 2019-12-17 at 01 17 59](https://user-images.githubusercontent.com/13822438/70953882-49cd4400-206b-11ea-9ebe-660a15d9a5f2.png)

**Comment by achrinza** [comment]
@frbuceta Apologies, what I meant was using `DEBUG=loopback:connector:mssql` env. variable, using `supportsOffSetFetch`, making a request then posting the logged generated T-SQL query.

**Comment by frbuceta** [comment]
> @frbuceta Apologies, what I meant was using `DEBUG=loopback:connector:mssql` env. variable, using `supportsOffSetFetch`, making a request then posting the logged generated T-SQL query.

I've tried since postman and if it works, sorry for my mistake
` SELECT [id],[codigo],[fecha],[latitud],[longitud],ROW_NUMBER() OVER ( ORDER BY [fecha]) AS RowNum FROM [dbo].[TABLENAME] WHERE [codigo]=@param1 ORDER BY RowNum OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY`

I am also making an order by date but it seems not to work ... Can it be for the same?
`Date FORMAT: 2019-09-17T07:14:10.457Z`

Many thanks @achrinza

**Comment by frbuceta** [comment]
Upgrade:
Right after applying this patch to the mssql connector, it still does not return the results.

Will we have to apply a default limit? The request takes up to 2 minutes and even more

**Comment by achrinza** [comment]
@frbuceta From the top of my head -yes, you'll need to apply a default limit manually. This can be accomplished in 2 ays:

1. Client-side
  This can be done by adding it as part of the request filter query on the client-side
2. Server-side (recommended)
  Modifying the filter object with a fixed limit before passing it into the repository functions will ensure a server-enforced default limit
