### ISSUE TITLE
error TS5056: Cannot write file '/home/node/api/dist/src/datasources/admin.datasource.d.ts' because it would be overwritten by multiple input files

### ISSUE THREAD

**Issue by HamzaMansouri7** [strongloop/loopback-next#4173]
Hi #4170 Loopback DEVS i get this problem after i try to run my server API , im using #angular 7 and #loopback  error reference :TS5056
  i'm sure that  problem in typescript version  ..i'm using  (3.4.5) right now  , i have tried with many version like 3.8.1 ==> error in --target  flag 
3.5.1===>error in extends must be rooted or relative 
1.7.5===> include & exclude  Error   in Tsconfig 
i need help here guys 

------this is my Api Tscofig
`{
  "$schema": "http://json.schemastore.org/tsconfig",
  "extends": "@loopback/build/config/tsconfig.common.json",
  "include": [
    "src",
    "test",
    "index.ts"
  ],
  "exclude": [
    "node_modules/**",
    "packages/*/node_modules/**",
    "**/*.d.ts"
  ]
}
`
![tsconfig](https://user-images.githubusercontent.com/51540362/69223500-c3ad0300-0b7b-11ea-83d0-e61efa4e1e37.PNG)
![github](https://user-images.githubusercontent.com/51540362/69223517-cd366b00-0b7b-11ea-90f1-2bc107980342.PNG)

**Comment by achrinza** [comment]
Hi,

You've mentioned that you're using `typescript@3.8.1`. I've checked [Typescript's published versions](https://www.npmjs.com/package/typescript) and found no reference to the version mentioned. Could you clarify on that?

If you've just updated to `typescript@3.7.2`, then [a recent change has led to a file naming conflict](https://github.com/strongloop/loopback-next/pull/4051), which may be the issue.

If that's the case, it can be resolved by renaming all `*.datasource.json` files to `*.datasource.config.json` and then updating all references to those affected files.

The installation of [@loopback/cli](https://www.npmjs.com/package/@loopback/cli) should be updated to the latest version which has resolved this issue for future generated datasources.

**Comment by raymondfeng** [comment]
Close per @achrinza 's comment.

**Comment by ImJohnDoe** [comment]
> If that's the case, it can be resolved by renaming all *.datasource.json files to *.datasource.config.json and then updating all references to those affected files.

Thanks, I had the same issue @achrinza 's answer resolved this for me
