### ISSUE TITLE
docs(authorization): legacy "extract common layer" notice

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#4196]
## Steps to reproduce

1. Go to [`@loopback/authorization` README](https://github.com/strongloop/loopback-next/blob/master/packages/authorization/README.md#extract-common-layertbd)
2. Read "Extract Common Layer (TBD)" section
    
    ![image](https://user-images.githubusercontent.com/25147899/69479067-4a8c0500-0e34-11ea-90eb-f345e1358ac7.png)

## Current Behavior

This section exists, stating that the common interfaces are being refactored into the `@loopback/security` package and suggesting workarounds as it assumes that the refactoring has not been completed.

## Expected Behavior

This section should not exist or be updated to reflect the current status.

`@loopback/security` has been published and #2900 has been merged for a while. Furthermore, [`@loopback/authentication` README](https://github.com/strongloop/loopback-next/blob/master/packages/authentication/README.md#note) has references to use `@loopback/security` since `v3.0.0`. In addition, the [referenced draft branch](https://github.com/strongloop/loopback-next/tree/security/packages/security) hasn't had a commit in 6 months and the [referred PR](https://github.com/strongloop/loopback-next/pull/1205) has been merged. It seems safe to assume that the section is outdated.

### `@loopback/authentication` README

![image](https://user-images.githubusercontent.com/25147899/69479100-aeaec900-0e34-11ea-8902-892425db021e.png)

## Link to reproduction sandbox

N/A

## Additional information

N/A

## Related Issues

N/A

**Comment by dhmlau** [comment]
cc @deepakrkris @jannyHou.
Not sure if it'll be covered in https://github.com/strongloop/loopback-next/issues/3694, but something to keep in mind. Thanks.

**Comment by deepakrkris** [comment]
currently addressed in PR , https://github.com/strongloop/loopback-next/pull/4185

**Comment by deepakrkris** [comment]
PR merged, closing issue.
