### ISSUE TITLE
500 Error: scope is not supported

### ISSUE THREAD

**Issue by tibdev78** [strongloop/loopback-next#4202]
Hi,
I use loopback 4 and I'm trying to use the scope option to include multiple relations between my models, but when i try to do so...: 
`include: [
 {relation: 'relation1', scope: {
       include: [ { relation: 'relation2'} ]}
 }]`
It doesn't work, did you implent this option or is my implementation for the scope option wrong?

**Comment by achrinza** [comment]
Loopback 4 currently doesn't support nested `include` relations. See #3453.

**Comment by tibdev78** [comment]
Test @achrinza , i saw that, but do you any way to achieve this with loopback or is it necessary to realize that with simple SQL request?

**Comment by achrinza** [comment]
@tibdev78 I'm not too familiar on any workarounds, but it's possible to use `repository.execute(query, params)`.

**Comment by bajtos** [comment]
Closing as a duplicate of #3453

**Comment by bajtos** [comment]
Duplicate #3453
