### ISSUE TITLE
bug(cli): cli does not respect custom relation getter name

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-next#4209]
## Steps to reproduce

Generating `hasMany` relation between `News` and `NewsFile` object. Naming it `files` instead of the default `newsFiles`:

![image](https://user-images.githubusercontent.com/13640166/69612163-76bfa580-102f-11ea-9107-f3d26e57ee83.png)

@loopback/cli@1.26.0

## Current Behavior

The custom name `files` is used in the model, but not in the repository:

![image](https://user-images.githubusercontent.com/13640166/69612343-c900c680-102f-11ea-930a-fc1c129d6a11.png)

![image](https://user-images.githubusercontent.com/13640166/69612417-ea61b280-102f-11ea-8198-809d9099bfa1.png)

## Expected Behavior

Expecting consistent naming across model and repository.

**Comment by achrinza** [comment]
Correct me if I'm wrong but I believe this is expected behaviour. The CLI prompts for setting the `property` name (not the relation name), which in this case works fine.

**Comment by derdeka** [comment]
@achrinza if this is the expected behavior, maybe there should be another prompt for customizing the naming in the repository?

**Comment by achrinza** [comment]
Just curious, what’s the use case for custom relation names?

________________________________

**Comment by derdeka** [comment]
> Just curious, what’s the use case for custom relation names?

I have a model inheritance like `NewsFile extends BaseFile` and `ContractFile extends BaseFile` to have shared properties and some additional custom properties per subclass - each subclass is storing in it's own relational database table. On the api it's just named `files`.

**Comment by achrinza** [comment]
@derdeka Thanks for providing extra info. I think this feature is a possibility, though there are [limitations on using class inheritance](https://github.com/strongloop/loopback-next/issues/4042#issuecomment-549801710).

**Comment by achrinza** [comment]
I've dug into the code and docs and found some inconsistencies:

1. `--relationName` option is used for setting the property ([see here](https://loopback.io/doc/en/lb4/Relation-generator.html))
2. Internally, the function responsible referred to as a "promptRelationName" ([see here](https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/relation/index.js#L339-L382))
3. Internally, the constant storing the prompt message is called ([see here](https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/relation/index.js#L30-L31))
4. The end result is the foreign key property name being affected and not the relations name.

**Comment by achrinza** [comment]
@dhmlau Maybe the core maintainers might want to look into this; if this is expected behaviour

**Comment by bajtos** [comment]
> Expecting consistent naming across model and repository.

+1

I think this is a bug, an oversight on the side of the person implementing `lb4 relation` command.

@derdeka @achrinza would you like to contribute the fix yourself?
