### ISSUE TITLE
feat(cli): passing prompt values by cli parameters

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-next#4210]
## Suggestion

Currently the `@loopback/cli` is using prompts to ask for user input. This can be very time consuming if an large application has many models and you need to select source or taget model for `lb4 relation` command manually in a very large list of models.

It would be very helpful to have something like this:
`
lb4 relation --sourceModel ModelA --relationType belongsTo --targetModel ModelB
`

**AFAIK there is no command line support yet. Is there?**

## Use Cases

When migrating a `lb3` application to `lb4` there is currently no support for migration relations. **I don't want to wait another year for a completed model migration support.**

I know the project owners really like perfect software architecture, but a migration is only done once per project and I think the project should not spend too much time on migration path, but feature parity.

My shortcut is currently printing a list of the relations and adding the relation one-by-one with the `lb4` command line tool with prompts. This could be much easier when the parameters could be passed directly by command line - then a simple helper script can apply the relation migration with existing cli features.

## Examples

```
const fs = require('fs-extra');
const path = require('path');

const run = async () => {
  try {
    const folder = path.resolve(__dirname, 'models');
    const files = await fs.readdir(folder);
    for (const file of files) {
      if (/\.json$/.test(file)) {
        const fileContent = await fs.readFile(path.resolve(folder, file));
        const model = JSON.parse(fileContent);
        const relations = model.relations || {};
        const relationNames = Object.keys(relations);
        for (const relationName of relationNames) {
          console.log(`lb4 relation --sourceModel ${model.name} --relationType ${relations[relationName].type} --targetModel ${relations[relationName].model}`);
        }
      }
    }
  } catch (e) {
    console.error(e);
  }
}

run();
```

## Acceptance criteria

TBD - will be filled by the team.

**Comment by achrinza** [comment]
AFAIK LoopBack 4 CLI does support command line options (e.g. [lb4 relation](https://loopback.io/doc/en/lb4/Relation-generator.html))

**Comment by derdeka** [comment]
Thanks @achrinza. I did not find that part of the documentation.

**Comment by raymondfeng** [comment]
You can also use `-c, --config: JSON file name or value to configure options.` to pass in a json file or stringified json.
