### ISSUE TITLE
Fix issues with 'nodejs-loopback' stack for Appsody

### ISSUE THREAD

**Issue by emonddr** [strongloop/loopback-next#4216]
This is regarding the [nodejs-loopback](https://github.com/appsody/stacks/tree/master/incubator/nodejs-loopback) stack for Appsody.

## Current Behavior

There are a few minor issues at the moment:

- incompatible dependencies message appears when using LB4 CLI
   ```
    lb4 model
    The project was originally generated by @loopback/cli@1.25.1.
    The following dependencies are incompatible with @loopback/cli@1.25.1:
     - @types/node: ^12.12.5 (cli ^10.17.5)
    ? Continue to run the command? (y/N) 
    ```
    If user chooses Y, he/she can continue. But the prompt is confusing
- During all the appsody commands [run/debug/test], when a Docker image is being built, the following message appears:
    ```
     [Container] found 2 high severity vulnerabilities
     [Container]   run `npm audit fix` to fix them, or `npm audit` for details
    [Container] 
    ```
     and so does this message: 

     ```
      [Container]    │      New minor version of npm available! 6.9.0 -> 6.13.1       │
      [Container]    │   Changelog: https://github.com/npm/cli/releases/tag/v6.13.1   │
      [Container]    │               Run npm install -g npm to update!                │
     ```

It is still possible to work with the the stack and the appsody CLI despite these issues.

## Expected Behavior

None of these messages should be appearing.

**Comment by dhmlau** [comment]
@emonddr, is the cause of the issue being appsody is not using the latest version of the LB4 modules? What should be the fix here?

**Comment by raymondfeng** [comment]
To be fixed by https://github.com/appsody/stacks/pull/528

**Comment by bajtos** [comment]
appsody/stacks#528 has been merged, I am closing this issue as resolved.
