### ISSUE TITLE
[LB-Next] Review ModelDefinition and PropertyDefinition

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#422]
Referencing the model definition in LB3, make sure we are able to describe the model to the same level in LB-Next. 

Files to review:
- https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/loopback-datasource-juggler.ts
- https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/legacy-juggler-bridge.ts

### Reference
Model Definition: https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html

**Comment by bajtos** [comment]
Closing as not needed by now, per @kjdelisle
