### ISSUE TITLE
feat(docs): describe how to use local copy of this project in a loopback4 crafted project

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-next#4224]
## Suggestion

It would be helpful to describe the best practice, how a local copy of `loopback-next` repository can be **used in a loopback4 crafted project** or a development version of the `@loopback/cli` **can be used to operate on another project**.

I did not find anything like this in the documentation https://loopback.io/doc/en/lb4/code-contrib-lb4.html . Is there something describing this?

## Use Cases

Testing feature branches of the `loopback-next` repository on a real application without waiting for a release or a long living feature branch to get merged.

## Examples

What is the best practice, for normal dependencies and a global installed cli?
- `npm link` ?
- file system relative dependencies ?

How is the loopback core team doing this?

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dhmlau** [comment]
@derdeka, I use `npm link` on the particular package I want to link, e.g. Run `npm link` on `loopback-next/packages/cli` for testing out the CLI. 

Maybe that's something we can add in https://loopback.io/doc/en/lb4/submitting_a_pr.html or https://github.com/strongloop/loopback-next/blob/master/docs/site/DEVELOPING.md?

**Comment by dhmlau** [comment]
@derdeka, are you interested in submitting a PR to improve the docs in this area? Thanks.

**Comment by raymondfeng** [comment]
We already have `sandbox` directory under loopback-next for testing apps that depend on the code checked from github. See https://github.com/strongloop/loopback-next/blob/master/sandbox/README.md.

To run cli locally, simply use `loopback-next/packages/cli/bin/cli-main.js ...`.

**Comment by derdeka** [comment]
@dhmlau I tried your suggestion with `npm link`, but this seems to have some side-effekts, if the projects using diffferent versions of dependencies. For example `error TS2742: The inferred type of 'AuditMixin' cannot be named without a reference to '@loopback/repository'. This is likely not portable. A type annotation is necessary.`

@raymondfeng Thanks, i'll try this.

**Comment by achrinza** [comment]
+1 for better documentation. Currently [`sandbox/README.md](https://github.com/strongloop/loopback-next/blob/7fe694865b337c99beb25afc581c5429fb758746/sandbox/README.md) states to run the following commands:

```bash
cd loopback-next
npm install
cd sandbox/example
node .
```

However, this would lead to the following error (`npm start` was used, but the issue is the same):
```bash
[REDACTED]@[REDACTED] MINGW64 ~/Documents/loopabck-next/sandbox/lb4-test (master)
$ npm start

> lb4-test@1.0.0 prestart [REDACTED]\loopabck-next\sandbox\lb4-test
> npm run build


> lb4-test@1.0.0 build [REDACTED]\loopabck-next\sandbox\lb4-test
> lb-tsc


> lb4-test@1.0.0 start [REDACTED]\loopabck-next\sandbox\lb4-test
> node -r source-map-support/register .

Error: Cannot find module './dist'
Require stack:
- [REDACTED]\loopabck-next\packages\boot\index.js
- [REDACTED]\loopabck-next\sandbox\lb4-test\dist\application.js
- [REDACTED]\loopabck-next\sandbox\lb4-test\dist\index.js
- [REDACTED]\loopabck-next\sandbox\lb4-test\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> ([REDACTED]\loopabck-next\packages\boot\index.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lb4-test@1.0.0 start: `node -r source-map-support/register .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lb4-test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rifaa\AppData\Roaming\npm-cache\_logs\2020-02-18T11_25_51_731Z-debug.log
```

The command should instead be:

```bash
cd loopback-next
npm install
npm run build
cd sandbox/example
node .
```
