### ISSUE TITLE
Feature: Allow Auto-Update to synchronize from database to model and not just model to databse

### ISSUE THREAD

**Issue by delebash** [strongloop/loopback-next#423]
Currently auto-update updates the database tables based on model definition changes. From my point of view any changes to my schema such as adding a property or new table with a relationship will be made on the database first and then I would want the change to be propagated to the model.  Now it is the reverse and also it only updates properties but not relationships.

**Comment by bajtos** [comment]
@delebash thank you for the feature idea. Have you tried using autodiscovery ([dataSource.discoverAndBuildModels](http://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-discoverandbuildmodels) and friends)? It reads the database schema and produces model descriptions.

**Comment by delebash** [comment]
Yes I have autodiscovery working but it does not keep changes in sync automatically.  I can write my own code to compare added and removed properties/fields/tables but it would be nice to have the feature baked in like your auto-update. As it stands now with auto-discovery I can write code to read the db schema and create model files from this schema, If I then change a field/table/relationship in the database I can either rewrite the whole model file again which would destroy any manual changes I have made such as validations or I can write code to compare the current model file with the new auto-discovered schema and resolve the differences.  A bidirectional auto update with conflict resolution where you can say model takes precedence or db or merge changes.
