### ISSUE TITLE
LoopBack 4 nestRemoting 

### ISSUE THREAD

**Issue by jsylvester89** [strongloop/loopback-next#4243]
How do we achieve the nestRemoting in Loopback4?
ModelA -> relationX -> ModelB -> relationY -> ModelC in a single endpoint?

Here there is a solution to achieve it in loopback3....
https://github.com/strongloop/loopback/issues/2137

**Comment by dhmlau** [comment]
Moving to `loopback-next` repo since it's related to LB4.

**Comment by achrinza** [comment]
LoopBack 4 has since implemented querying nested relations. See [Query multiple relations](https://loopback.io/doc/en/lb4/HasMany-relation.html#query-multiple-relations)
