### ISSUE TITLE
Application should have app.repository() API

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#425]
#491 Per @bajtos,
>It would be nice to introduce `app.repository` API to take care of this.

There should be a way to bind multiple repositories (implementation tbd) -- This is just a shorthand of bind().toClass. 

Implementation Suggestion: Introspect the name of the repository and use that as the key. User can also supply a string the repository should bind to (similar to how .bind() works). 

# Acceptance

- [x] Implement `app.repository(AccountRepository)`
- [x] Allow components to export repositories
- [x] Testing (If test for bind exists then add similar tests but using  `app.repository()`) otherwise add new tests.
- Update Docs
  - [ ] https://github.com/strongloop/loopback-next/wiki/Using-Components
  - [ ] https://github.com/strongloop/loopback-next/wiki/Writing-Components
  - possibly other places too

---

```ts
app.repository(AccountRepository);
```

>The argument should be strongly typed to a base Repository interface, which is something that we cannot achieve via `bind().toClass()`, at least not now.

Instead of importing the repository class and binding it to a key on the `app` instance.
```ts
app.bind('repositories.account').toClass(AccountRepository);
```

@bajtos feel free to edit if I misunderstood.

**Comment by bajtos** [comment]
Once we have `app.repositorye`, it would be great to allow components to export repositories similarly how controllers are exported - ideally implement that as part of this story.

Relevant source code: [packages/core/src/component.ts](https://github.com/strongloop/loopback-next/blob/master/packages/core/src/component.ts).

**Comment by bajtos** [comment]
One point to consider: IMO, we shouldn't be coupling `Application` from `@loopback/core` with any specific version of`Repository` interface from `@loopback/repository`, `@loopback/repository` should not be a dependency of `@loopback/core`. This means that the type signature of `app.repository` cannot use `Repository` interface from `@loopback/repository`. The simplest solution that comes to my mind is to ship a simplified `Repository` definition in `@loopback/core`, this interface should contain the most important members that every `Repository` must have (are there any?).

Similar argument applies for registering repositories in Application constructor via `ApplicationOptions.repositories` (to be added) and `Component.repositories` (to be added too).

What I would like more is to allow components to contribute these three helpers for registering application artifacts (`app.registry()`, `ApplicationOptions.repositories`, `Component.repositories`), for example through a mixin. 

Here is a mock to illustrate my idea:

```ts
// in packages/persistence

export function AppWithPersistenceMixin(app: Class<Application>) {
  return class ApplicationWithPersistence extends Application {
    constructor(options: ApplicationOptions & {repositories?: Repository[]}) {
      super(options);
      if (options.repositories) {
        // register repos via this.repository()
      }
    }

    repository(repo: Repository) {
      // bind repo to a key derived from the repo name
    }

    component(component: Component & {repositories?: Repository[]}) {
      super.component(component);
      if (component.repositories) {
        // register repos via this.repository()
      }
    }
  };
}

// usage
class MyApp extends AppWithPersistenceMixin(Application) {
  // ...
}
```
