### ISSUE TITLE
How to connect to dynamo db using lb4?

### ISSUE THREAD

**Issue by sureshdmavericks** [strongloop/loopback-next#4254]
Can anyone know how to connect to dynamo db using lb4

**Comment by dhmlau** [comment]
@sureshdmavericks, there's a community connector for dynamo db: https://loopback.io/doc/en/community/dynamo-connector.html. You might want to give it a try. It's supposed to continue to work in LB4.

**Comment by dhmlau** [comment]
@sureshdmavericks, we believe we've answered your question, so I'd like to close this issue now.  If you have further questions, please feel free to open a new issue. Thanks.
