### ISSUE TITLE
How to define a model @property that allows any scalar value?

### ISSUE THREAD

**Issue by freakpol** [strongloop/loopback-next#4255]
I'm want to store any type on a property, for example:

```
@model()
class MyModel extends Entity{
    @property({id: true})
    id: number;

    @property({
        type: 'I DONT KNOW WHT TO PUT HERE TO ALLOW ANY VALUE'
    })
    value: any;
}
```

The idea, is that, when I POST to that entity I can send the following examples, and all work the same

```
POST /mymodels 
{
  "id": 1,
  "value": 1
}
---
POST /mymodels 
{
  "id": 2,
  "value": "1"
}
---
POST /mymodels 
{
  "id": 3,
  "value": true
}
---
POST /mymodels 
{
  "id": 4,
  "value": null
}
---
POST /mymodels 
{
  "id": 5,
  "value": {"a":"b" }
}
```

Note: Database is a mongo db, so it shouldn't be a problem.

## Acceptance Criteria
-  [ ] Specify type `any` in `lb4 model` cli should not result in "Unsupported type" error. 
-  [ ] Add test to make sure the type can be converted to OpenAPI spec correctly

References: 
- Code that gives out the "unsupported type" error: https://github.com/strongloop/loopback-next/blob/master/packages/repository-json-schema/src/build-schema.ts#L167
- Supported types: https://loopback.io/doc/en/lb3/LoopBack-types.html.  This is a LB3 docs, I assume it would be the same for LB4 (?).

**Comment by dougal83** [comment]
Try `type: any`

Ref: https://loopback.io/doc/en/lb3/LoopBack-types.html

**Comment by freakpol** [comment]
Nope, if I use any, loopback says that is not a valid type for the openapi spec:

```
Cannot start the application. Error: Unsupported type: any
```

**Comment by dougal83** [comment]
Perhaps it needs to be as following:

````
@property({
    type: 'any',
    required: true,
  })
  test: any;
````

This is what `lb4 model` produces.

**Comment by freakpol** [comment]
Yep, thats what I've tried.  And get that error.

**Comment by dougal83** [comment]
I see sorry, I had assumed it the `lb4 model` command would not give unusable results. I'd guess that an option would be to use `type string` and store as json.

**Comment by freakpol** [comment]
Yeah, kinda odd.

**Comment by dhmlau** [comment]
@freakpol @dougal83, thanks for reporting this issue and analyzing it.  
The "unsupported type" error is coming from https://github.com/strongloop/loopback-next/blob/master/packages/repository-json-schema/src/build-schema.ts#L167, and it doesn't include type `any`.

**Comment by jannyHou** [comment]
We have `AnyType` defined in [types](https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/types)
So probably handle that type in [build schema]( https://github.com/strongloop/loopback-next/blob/master/packages/repository-json-schema/src/build-schema.ts#L167), convert the [`AnyType`](https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/types/any.ts) to OpenAPI schema [`any type`](https://swagger.io/docs/specification/data-models/data-types/#any)

**Comment by luncht1me** [comment]
You could for now, define the property type as 'object'... ie:
```ts
@property({
  type: 'object'
})
data: anyObjectType

} // end of model

type anyObjectType = {
  value: any;
};
```

Ofc this results in your data being `modelInstance.data.value` but atleast you'd be able to just do anything with it now.

**Comment by jannyHou** [comment]
Created PR https://github.com/strongloop/loopback-next/pull/4930

Define the property in model as:
  
```ts
import {AnyType} from '@loopback/repository';
@property({
    // `@loopback/repository-json-schema` recognizes it
    type: 'any'
  })
  // specify `AnyType` for it
  arbitraryProp: AnyType
```

Generated json schema would be

```ts
arbitraryProp: {
    $ref: '#/definitions/AnyType'
}
```

Generated openapi spec would be

```ts
"components": {
    "schemas": {
      "Todo": {
        "title": "Todo",
        "properties": {
          "id": {
            "type": "number"
          },
          // ...other properties
          // The schema will be generated as a reference
          // TODO: to completely support this feature, we can provide schema for 
          // swagger AnyType out-of-the-box
          // see link https://swagger.io/docs/specification/data-models/data-types/#any
          "arbitraryProp": {
            "$ref": "#/components/schemas/AnyType"
          }
        },
        "required": [
          "title"
        ],
        "additionalProperties": false
      },
  },
}
```

---

A follow-up PR is coming for adding the openapi shema for any.
The openapi schema spec for any type will be:

```ts
components: {
   schemas: {
      AnyValue: {}
   }
}
```

**Comment by jannyHou** [comment]
Update: now you can define the property as

```ts
@property({
  // use type name 'any'
  type: 'any'
})
// specify type as `any`
anyProperty: any
```

Feel free to reopen the issue if you still have questions. Thanks.
