### ISSUE TITLE
Connector tutorials under Connectors reference are for LB3

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#4271]
While the connectors can be used for both LB3 and LB4, the tutorials under the [Connectors reference](https://loopback.io/doc/en/lb4/Connectors-reference.html) for LB4 are about LB3. It might cause confusion to the users.

Tutorials I'm referring to are:
- mongodb connector tutorial: https://loopback.io/doc/en/lb4/Connecting-to-MongoDB.html
- mysql connector tutorial: https://loopback.io/doc/en/lb4/Connecting-to-MySQL.html
- oracle connector tutorial: https://loopback.io/doc/en/lb4/Connecting-to-Oracle.html
- postgresql connector tutorial: https://loopback.io/doc/en/lb4/Connecting-to-PostgreSQL.html

There are probably more in the list.

**Comment by agnes512** [comment]
For those who work on the stories: see https://github.com/strongloop/loopback-next/issues/4877#issuecomment-599677236

**Comment by dhmlau** [comment]
Closing as done, since all the items in this epic are done. 
Many thanks @agnes512!! 🙇
