### ISSUE TITLE
Changing settings does not work in health extension

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#4289]
## Steps to reproduce

When trying to change the settings in health extension, it doesn't work

```
this.configure(HealthBindings.COMPONENT).to({
  healthPath: '/status',
  livePath: '/status/live',
  readyPath: '/status/ready',
});
```

## Additional information

> darwin x64 13.3.0

```
├── @loopback/authentication@3.2.4
├── @loopback/boot@1.6.0
├── @loopback/context@1.25.0
├── @loopback/core@1.12.0
├── @loopback/extension-health@0.2.13
├── @loopback/openapi-v3@1.10.3
├── @loopback/repository@1.16.0
├── @loopback/rest@1.25.0
├── @loopback/rest-explorer@1.4.6
├── @loopback/security@0.1.9
├── @loopback/service-proxy@1.3.13
└── loopback-connector-mssql@3.6.0
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
Does `/status` give 404?

You have to call `this.configure` before `this.component(HealthComponent)` due to a limitation that can be fixed.

We have an acceptance test to cover such config. See https://github.com/strongloop/loopback-next/blob/master/extensions/health/src/__tests__/acceptance/health.acceptance.ts#L117-L127.

**Comment by frbuceta** [comment]
> Does `/status` give 404?
Yes, it returns me a 404

> You have to call `this.configure` before `this.component(HealthComponent)` due to a limitation that can be fixed.
Works!!!

**Comment by dhmlau** [comment]
Closing as resolved.

**Comment by dhmlau** [comment]
Closing as resolved.
