### ISSUE TITLE
bug(repository): non-numeric IDs are not valid

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#4303]
## Steps to reproduce

1. Create a new model with a `string`-type ID
2. Create a datasource
3. Create a repository for the newly-created model
4. Crate a controller for the newly-created model

## Current Behavior

The generated `create()` function's `@requestBody()` parameter injection will return the following error:

```
Argument of type '{ title: string; exclude: "id"[]; }' is not assignable to parameter of type 'JsonSchemaOptions<Model>'.
  Types of property 'exclude' are incompatible.
    Type '"id"[]' is not assignable to type '("ID" | "getId" | "getIdObject" | "toJSON" | "toObject")[]'.
      Type '"id"' is not assignable to type '"ID" | "getId" | "getIdObject" | "toJSON" | "toObject"'.ts(2345)
```

## Expected Behavior

These functions should be able to accept non-numeric IDs as per-model definitions.

## Link to reproduction sandbox

https://github.com/achrinza/lb4-example-invalid-non-numeric-id

## Additional information

```bash
$ node -e 'console.log(process.platform, process.arch, process.versions.node)' && npm ls --prod --depth 0 | grep loopback
win32 x64 12.13.1
+-- @loopback/boot@1.6.0
+-- @loopback/context@1.25.0
+-- @loopback/core@1.12.0
+-- @loopback/openapi-v3@1.10.3
+-- @loopback/repository@1.16.0
+-- @loopback/rest@1.25.0
+-- @loopback/rest-explorer@1.4.6
`-- @loopback/service-proxy@1.3.13
```

## Related Issues

N/A

**Comment by bajtos** [comment]
@achrinza thank you for reporting the bug. Can you please create a small app reproducing the problem, per our instructions in https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs?

**Comment by achrinza** [comment]
@bajtos Unfortunately I haven't been able to get the exact issue to occur, but a similar issue seems to persist. I've updated the original comment to reflect that.

**Comment by dougal83** [comment]
It looks like case sensitivity.  Controller expects `exclude: ['ID'],`  Give that a try in place of `exclude: ['id'],`.

````
  @property({
    type: 'string',
    id: true,
    generated: true,
  })
  ID?: string;
````

**Comment by achrinza** [comment]
@dougal83 Yup, this seems like the case! A bit of an oversight at my part. Will close this issue.
