### ISSUE TITLE
how to resolve redirect issue in loopack4

### ISSUE THREAD

**Issue by ravikenqos** [strongloop/loopback-next#4320]
import { RestApplication} from '@loopback/rest';
export class ShopifyController extends RestApplication {
  constructor() {
    super();
  }

  async install(
    @param({name: 'shop', in: 'query'}) shop: string,
  ): Promise<void> {
    const redirectUrl = `https://${shop}/admin/oauth/authorize?
    client_id=${shopifyApiKey}&scope=${scopes}
    &redirect_uri=${redirectUri}`;
    this.redirect('/install', redirectUrl, 301);
}
}
Here Redirect is not working can anyone help me to resolve this issue

**Comment by jannyHou** [comment]
@ravikenqos The `redirect` function is supported at application or server level, not controller level, see example in the [http redirect documentation](https://loopback.io/doc/en/lb4/Routes.html#implementing-http-redirects)

**Comment by hacksparrow** [comment]
If you want to dynamically redirect a request you can do this:

```ts
import {RestBindings, get, Response} from '@loopback/rest';
import {inject} from '@loopback/context';

export class CoolController {
  constructor(@inject(RestBindings.Http.RESPONSE) private res: Response) {}

  @get('/hello')
  async hello() {
    this.res.redirect('http://example.com', 302)
  }
}
```
