### ISSUE TITLE
Loopback 4 install on Windows 10 core-js 2.6 is no longer maintained

### ISSUE THREAD

**Issue by micko75** [strongloop/loopback-next#4331]
Good day;
I have this error during the install of loopback-cli and on application initialisation.
==============================================================
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
==============================================================
Any help is welcome.
Mick

**Comment by dhmlau** [comment]
@micko75, what you've shown above is deprecation warning. Did you get any other error message? 

@agnes512, could you please take a look? I thought the `renovatebot` would update the dependencies for us. Thanks.

**Comment by micko75** [comment]
@dhmlau no other error message or warning.

**Comment by agnes512** [comment]
@micko75 Hi, for the older version project, you can
1. stick with existing deps and use an older version of CLI
2. upgrade deps to match the newer CLI and use the newer CLI

After deps upgrade, you might have to fix the project manually for any breaks.

For updating, you can do `npm update` ([Ref](https://loopback.io/doc/en/lb4/Command-line-interface.html#upgrading-loopback-dependencies)).
Or do `npm i -g @loopback/cli`.

**Comment by dougal83** [comment]
WARN will be resolved upstream.  See https://github.com/babel/babel/pull/10929
