### ISSUE TITLE
Limit the hostname/IP adress the app is listening on

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#434]
Right now, `app.start()` takes into account only `http.port` configuration. We should allow applications to configure the hostname/IP address of the server too.

**Comment by m3hari** [comment]
@bajtos  Can you provide some  Acceptance Criteria & Example test case for this issue please. I would like to work on this but I don't fully understand the requirement.

**Comment by raymondfeng** [comment]
It has already been implemented in https://github.com/strongloop/loopback-next/pull/717.
