### ISSUE TITLE
[SPIKE] Resolve `$ref` in api/controller/route specs

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#435]
At the moment, our code processing Swagger/OpenAPI Spec does not support `$ref` references, we assume all entities have been denormalized/dereferenced. IMO, this is a severe limitation because even the simples CRUD-based REST APIs usually reuse model (response object) definitions.

We should investigate how to support `$ref` in all places allowed by OpenAPI spec. Let's limit the scope to relative references only (e.g. `#/definitions/User`) and exclude external references (e.g. `http://json-schema.org/address`).

## Acceptance Criteria
- Establish agreement of the virtual OpenAPI Spec / $ref resolution
- What's the target OpenAPI Spec we're resolving against.
- Consistency between top-down and bottom-up approach
- Contributing Artifacts: Controller, Models, OpenAPI Spec, others?

**Comment by virkt25** [comment]
@bajtos @jannyHou is this still an issue with the migration to OAS3?

**Comment by raymondfeng** [comment]
`swagger-parser` now supports openapi 3.0 with dereference. We should use it.

**Comment by bajtos** [comment]
I am keeping this in CoreGA scope, I'd like to know the estimate before deciding whether to keep or push out this feature.
