### ISSUE TITLE
Db2 Data Sources - Fix names for clarity and proper branding

### ISSUE THREAD

**Issue by ThePrez** [strongloop/loopback-next#4371]
## Suggestion
There are several "Db2" data sources available now (hooray!):
- IBM DB2
- IBM DB2 for iSeries
- IBM DB2 for z/OS
- Db2 for i (brand new, from @strongloop/ibmi-maintainers , not yet on loopback.io)

## Use Cases
Users should be able to choose options from the loopback.io documentation and `lb datasource` with a proper sense of how the connectors are related

## Examples

A z/OS user has no guidance on whether he/she should choose "DB2" or "DB2 for z/OS". It's not clear why someone would choose "DB2" when there's a "DB2 for ______" variant (and vice versa). He/she may be inclined to simply choose the first "DB2" seen. 

I think better naming of the connectors would suffice as "guidance" 

## Acceptance criteria

The following should be true of the connectors' names:
- They should all start with "IBM" (or not, for consistency's sake)
- They should use the proper branding. It's "Db2," not "DB2"
- "IBM DB2" should be "IBM Db2 for LUW" (this should sufficiently differentiate it from the others, since LUW users will be quite familiar with the abbreviation). This also provides a consistent naming scheme. 

So, proposed names would be: 
- `IBM Db2 for LUW`
- `IBM Db2 for i`
- `IBM Db2 for z/OS`
- `IBM Db2 for iSeries` (if this connector continues to exist. There is a discussion at https://github.com/strongloop/loopback-connector-db2iseries/issues/35 and its existence or lack thereof is presumably outside the scope of this issue)

If we agree on the new changes, I'm guessing we'll have to have each project change accordingly (?), and also update loopback.io accordingly (we can PR over there and link to any discussion had here)

**Comment by dhmlau** [comment]
@ThePrez, your proposal LGTM in general.  One question... is `Db2 for LUW` the latest naming? In https://www.ibm.com/support/knowledgecenter/SSEPGG, the latest versions already change to just use `Db2`

I think if we just change the `description` field in https://github.com/strongloop/loopback-workspace/blob/master/available-connectors.json#L403, we don't need to change in other place. We might need to check if the tests expect certain text.

**Comment by dhmlau** [comment]
Just realized that the json file controlling the list of connectors in LB4 is https://github.com/strongloop/loopback-next/blob/master/packages/cli/lib/connectors.json.

**Comment by ThePrez** [comment]
> @ThePrez, your proposal LGTM in general. One question... is `Db2 for LUW` the latest naming? In https://www.ibm.com/support/knowledgecenter/SSEPGG, the latest versions already change to just use `Db2`

Thanks for catching. I'm embarrassed to say I did not know about that change. So `IBM Db2` is the proper branding, although still perhaps confusing to i/z users. I'm fine with either keeping it `IBM Db2` (fixing the case) or adding some kind of parenthetical clarification, for instance `IBM Db2 (for Linux, Unix, Windows)`, although that gets lengthy.

**Comment by dhmlau** [comment]
I'm good with the parenthesis.  So we have the following as the `description` field in the connector.json?
- IBM Db2 (for Linux, Unix, Windows)
- IBM Db2 for i
- IBM Db2 for z/OS

@ThePrez, I have a question for you in terms of deprecating iSeries: https://github.com/strongloop/loopback-connector-db2iseries/issues/35#issuecomment-572142860.

@bajtos @raymondfeng @strongloop/loopback-maintainers, WDYT?

**Comment by ThePrez** [comment]
I propose we make said changes as part of landing the `IBM Db2 for i` connector in LB4 (right now it's just LB3, but 4 is coming soon).

**Comment by dhmlau** [comment]
Thanks @ThePrez. I've assigned this issue to you. Thanks!
