### ISSUE TITLE
OpenAPI 'definitions' not being saved as definition component, but as schema

### ISSUE THREAD

**Issue by luncht1me** [strongloop/loopback-next#4384]
So, I was trying to define some more logic for OpenAPI validation within my loopback model, and ran into [This StackOverflow Post](https://stackoverflow.com/a/47667175/1973350) that pointed me in the right direction about more complex logical operators.

So, I went ahead and added the 'definitions' property to my OpenAPI Schema for the route that creates an instance of my target model. But, on inspecting loopback's generated `/openapi.json`, I noticed under `components`, that all the `definitions` that I just wrote, were bundled under `schemas` instead.

So, the OpenAPI Spec is supposed to let me define a definition like
```ts
 // Logic definitions for conditional validation based on 'type' property
    definitions: {
      'type-requires-value': {
        allOf: [
          // not prop w/o value, ie: property requires a value
          { not: { $ref: '#/components/definitions/props-without-value' } },
          { required: ['value'] },
        ],
      },
      'props-without-value': {
        properties: {
          type: {
            enum: ['invalidProp1', 'invalidProp2'],
          },
        },
      },
```
and then be able to reference it as a condition as so:
```ts
oneOf: [
      // types that require value
      { $ref: '#/components/definitions/type-requires-value' },
```

But, this throws an error that the definition can't be found: "can't resolve reference _#/components/definitions/type-requires-value_ from id #".
Inspecting the `/openapi.json` route, I see that it's been added as:
```json
"components": {
    "schemas": { // <-- under schemas, not definitions!
      "type-requires-value": {
        "allOf": [  { // what was written } [ ... ]
```

I do think that this 'definitions' keyword is pretty important to bundle definitions under when generating the OpenAPI Spec. Otherwise, you have your model schemas mixed in with your custom definitions and from the examples I've seen, this isn't how things are supposed to be?

Just throwing this out there for eyes. If someone runs into a similar problem trying to figure this stuff out, the 'definitions' that you write, become accessible under `#/components/schemas/{ your-definition }` which is an unexpected result. This `$ref` works, but It's expected (from what I can see) that these become available under `#/components/definitions/{ your-definition }`.

**Comment by dougal83** [comment]
Hey @luncht1me 

Although Json schemas have `#/components/definitions/` the Openapi spec v3 does not however.  (see [Open API spec v3.0.1](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#components-object)).  That being said you can use extensions if needs be but that is another matter.

IIRC in LB4 all references are currently shoehorned into `#/components/schemas/` as a starting point.  As time goes by we should see the Openapi spec produced by LB4 become more refined.  I'd recommend that you take a look at the new [LB4 enhancers](https://loopback.io/doc/en/lb4/Extending-OpenAPI-specification.html) that may be of interest to you.
