### ISSUE TITLE
Add API explorer

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#439]
It's critical to add `API Explorer` (aka Swagger UI) for REST APIs.

There are a few steps involved:

1. Create an endpoint to expose Swagger/OpenAPI Spec
2. Include web assets for Swagger UI (out of scope of this issue)

**Comment by rashmihunt** [comment]
@bajtos added label based on @raymondfeng input

**Comment by bajtos** [comment]
MVP scope for the first beta release: lb-next apps need to provide an HTTP endpoint returning Swagger/OpenAPI description of its API.
