### ISSUE TITLE
How can I assign foreign Key to a Loopback 4 model Entity

### ISSUE THREAD

**Issue by baltameme** [strongloop/loopback-next#4397]
I am trying to create a new LB4 project to test how to connect to a MySQL DB through following this reference: https://loopback.io/doc/en/lb4/todo-list-tutorial-sqldb.html

after preparing the project modules i tried to add to the code below to have a foreign relation between the "Todo", "TodoListImage" and the "TodoList" module:

```ts
@model({
  settings: {
    foreignKeys: {
      fk_todoListImage_todoListId: {
        name: 'fk_todoListImage_todoListId',
        entity: 'TodoList',
        entityKey: 'id',
        foreignKey: 'todolistId',
      },
    },
  },
})
```

* After adding it i have noticed an error related to the eslint:
ESLint: Identifier 'fk_todoListImage_todoListId' is not in camel case.(@typescript-eslint/camelcase)

* this is happening on the key "fk_todoListImage_todoListId" on specific.

* I attached the schema diagram for the sample DB. My main question is how to deal with camel case columns & foreign keys at the same time within Loopback 4 and MySQL.

![Screen Shot 2020-01-09 at 12 28 34 PM](https://user-images.githubusercontent.com/5762771/72050995-d91cee80-32db-11ea-83e2-e7a3b05dc598.png)

**Comment by achrinza** [comment]
There does seem to be a potential issue with the docs. I'll try to look into it further

In the mean time, these are some potential quick-fixes:
1. Surround `fk_todoListImage_todoListId` with quotation marks
2. Append `// eslint-disable-line camelcase` to the same line as the property:
    ```typescript
    @model({
        settings: {
            foreignKeys: {
                fk_todoListImage_todoListId: { // eslint-disable-line camelcase
                    name: 'fk_todoListImage_todoListId',
                    entity: 'TodoList',
                    entityKey: 'id',
                    foreignKey: 'todolistId',
                },
            },
        },
    })
    ```

**Comment by dhmlau** [comment]
Before we have ["strong relations" support](https://github.com/strongloop/loopback-next/issues/2331), that's probably the way to workaround it. 

I have tried a similar snippet as above posted by @achrinza and worked for Postgresql.  
https://github.com/dhmlau/loopback4-coffeeshop/blob/master/src/models/income.model.ts

**Comment by achrinza** [comment]
Hi @baltameme, we'll close this issue as solved; but if there's still any concerns, please feel free to open a new issue.

**Comment by baltameme** [comment]
OK @achrinza noted, thanks so much!

**Comment by SandroMoretti** [comment]
Hello @baltameme , you got this work?
I'm with the same trouble, I tried surround with quots and comment like ach said, but without success.
