### ISSUE TITLE
A reference implementation of gRPC support for controllers

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#440]
When developers use LB next to build microservices in Node, it is desirable to allow controllers to expose operations over gRPC in addition to REST.

**We should use this feature request to flush out how to enable multiple protocols/transports for LB next and implement necessary extension points.** 

We are not aiming at providing a full production-ready implementation of gRPC (yet).

Expected output: An example app, ideally with a tutorial/reference guide showing how to implement a custom transport.

**Comment by rashmihunt** [comment]
@bajtos Added labels as per @raymondfeng

**Comment by bajtos** [comment]
FWIW, there is already a community-developed gRPC extension available - see https://github.com/strongloop/loopback4-extension-grpc

@kjdelisle @raymondfeng I think this issue can be closed now, thoughts?

**Comment by dhmlau** [comment]
Closing as resolved.
