### ISSUE TITLE
Redis with loopback 4 Integration Example

### ISSUE THREAD

**Issue by baltameme** [strongloop/loopback-next#4421]
Where can I find an example on how to integrate Redis with loopback 4?
What I need to do with Redis is integrating it within the authentication process & architecture of Loopback 4.

**Comment by dougal83** [comment]
Hey @baltameme 

It seems that examples are thin on the ground so I suggest looking at the tests for the [redis connector](https://github.com/strongloop/loopback-connector-kv-redis) to gain an insight.

**Comment by jannyHou** [comment]
Another usage can be found in `loopback4-shopping-example`: https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/repositories/shopping-cart.repository.ts

The shopping-cart repository is connected to a redis datasource.

**Comment by dhmlau** [comment]
@baltameme, please let us know if we've answered your question, so that we can close this issue. Thanks.

**Comment by baltameme** [comment]
Hi @dhmlau, the example is clear enough. thanks so much.
I will be closing it from my side.
