### ISSUE TITLE
Link to apidocs is broken from README

### ISSUE THREAD

**Issue by mcorbe** [strongloop/loopback-next#4422]
Clikcing "API Documentation":
![image](https://user-images.githubusercontent.com/7733429/72324942-56fe4280-36ac-11ea-87ae-7878dd0d29af.png)

Lands here:
![image](https://user-images.githubusercontent.com/7733429/72324912-451c9f80-36ac-11ea-97ab-e53c7f253341.png)

**Comment by dougal83** [comment]
@mcorbe Thank you for reporting the broken link!
