### ISSUE TITLE
Authorization Header Keys - Native Mobile App 

### ISSUE THREAD

**Issue by baltameme** [strongloop/loopback-next#4436]
Recently, I built a new LB4 app for serving APIs to native mobile apps, where I've used the JWT for authenticating and authorizing the mobile user through passing the token.

I used the following scheme inside the LB4 project:

```ts
export const SECURITY_SCHEME_SPEC: SecuritySchemeObjects = {
  bearerAuth: {
    type: 'http',
    scheme: 'bearer',
    bearerFormat: 'JWT',
  },
};
```

I want to enquire what is the key required from the mobile client side that needs to be passed with requests headers in order to authenticate the user. In LB3 we used to pass the "Authorization" key along side with the user token.

**Comment by dougal83** [comment]
Hey @baltameme 

In a typical app involving a login procedure, you would have a token generated and passed back to the client see [loopback4-shopping-example](https://github.com/strongloop/loopback4-example-shopping/blob/5b6c15ea2bbfb3cd14cfc7759fdafe53308625b0/packages/shopping/src/controllers/user.controller.ts#L185-L217).  You might want to look into OAuth 2 aswell as a possible solution.

**Comment by baltameme** [comment]
Hey @dougal83 ,
thanks for your reply.

I am totally aware that about the flow of the shopping as i am following it exactly, and currently i am able to return the generated token back to the client. My question is about the name of the key that needs to be passed from the client side (mobile app) along side with the requests' header.

**Comment by emonddr** [comment]
@baltameme , you mean like this? 

https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/__tests__/acceptance/user-order.controller.acceptance.ts#L82 

```js
await client
      .post(`/users/${userId}/orders`)
      .set('Authorization', 'Bearer ' + token)
      .set('Content-Type', 'application/json')
      .send(order)
      .expect(400);
```

**Comment by baltameme** [comment]
Hi @emonddr, yes exactly that's what meant. just one concern I have, is there a way to avoid appending the 'Bearer' keyword and insert the token only so it will become something like this?

await client
      .post(`/users/${userId}/orders`)
      .set('Authorization', token)
      .set('Content-Type', 'application/json')
      .send(order)
      .expect(400);

**Comment by dougal83** [comment]
Hey @baltameme

Take a look at the [jwt auth strategy] (https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/authentication-strategies/jwt-strategy.ts)

You can amend this file to remove the requirement to add `Bearer ` to the authorisation header.

**Comment by baltameme** [comment]
I catch it @dougal83 thanks so much.
