### ISSUE TITLE
loopback-connector-redis: Broken CLA link

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#4449]
## Steps to reproduce

1. Go to https://github.com/strongloop-community/loopback-connector-redis `CONTRIBUTING.md`
2. Click the CLA link

## Current Behavior

The CLA link points to an non-existent web page:

![image](https://user-images.githubusercontent.com/25147899/70860941-882b0c00-1f62-11ea-996a-d78a8363dc40.png)

## Expected Behavior

The CLA link should points to a valid web page.

## Link to reproduction sandbox

N/A

## Additional information

N/A

## Related Issues

strongloop-community/loopback-connector-redis/issues/59

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@achrinza, I've removed the CLA checks but enabled the DCO check in https://github.com/strongloop-community/loopback-connector-redis.

![Screen Shot 2020-01-21 at 2 29 55 PM](https://user-images.githubusercontent.com/25489897/72836440-a28b9000-3c5a-11ea-8bd8-d4fed37fec53.png)

**Comment by dhmlau** [comment]
Closing as done.
