### ISSUE TITLE
docs: create a Querying Data page for LoopBack 4

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#4455]
Currently, if a user of LoopBack 4 (lb4) wants to find documentation of the usable `filters` for querying the repository, they will need to view [LoopBack 3's (lb3) documentation](https://loopback.io/doc/en/lb3/Querying-data.html). This may not be ideal as the page isn't easily accessible via the lb4 sidebar.

## Suggestion

Create a `Querying Data` or `Filters` page for lb4, replacing content and links to point to the lb4 docs where appropriate.

## Use Cases

1. Reduce jump between documentations
2. Assurance that this documentation also applies lb4
3. Easier for new users to start using lb4

## Examples

TBD; It could closely follow the existing lb3 docs.

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dhmlau** [comment]
@achrinza, thanks for suggesting this addition to the docs. I think this is much needed as well. We have an open issue: https://github.com/strongloop/loopback-next/issues/2527.  So I'd like to close this issue as duplicate and continue the discussion over there. Thanks!
