### ISSUE TITLE
External LoopBack API Validator default Swagger JSON URL to uses HTTP

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#4460]
## Steps to reproduce

1. Go to <https://loopback.io/api-explorer/>
2. Observe the mixed-content error

![image](https://user-images.githubusercontent.com/25147899/72681327-60007100-3afd-11ea-9741-c350c9bcb902.png)

## Current Behavior

A mixed-content error occurs.

## Expected Behavior

The default Swagger JSON URL should be using HTTPS as per-[Swagger API Validator](http://petstore.swagger.io/).

## Link to reproduction sandbox

N/A

## Additional information

~The external LoopBack API Validator is referenced under the [Configure the API Explorer](https://loopback.io/doc/en/lb4/Server.html#configure-the-api-explorer) docs.~

*EDIT:* This is fixed by #4464.

## Related Issues

https://github.com/strongloop/loopback.io/issues/925

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@achrinza, thanks for submitting (and merging) the PR https://github.com/strongloop/loopback-next/pull/4464. May I know where did you get the link for https://loopback.io/api-explorer/?

**Comment by achrinza** [comment]
@dhmlau, it can found under [Server > Configure the API Explorer](https://loopback.io/doc/en/lb4/Server.html#configure-the-api-explorer). #4464 updates the documentation to reference <https://explorer.loopback.io> instead; though that PR doesn't fix specifically this issue.
