### ISSUE TITLE
Rename security scheme 'bearerAuth' to 'jwt'

### ISSUE THREAD

**Issue by dougal83** [strongloop/loopback-next#4461]
## Suggestion

Rename following security scheme 'bearerAuth' to 'jwt' to be more specific.

``` json
"components": {
    "securitySchemes": {
      "jwt": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
},
```

## Use Cases

Current schema is out of step with [jwt auth strategy name](https://github.com/strongloop/loopback4-example-shopping/tree/master/packages/shopping/src/authentication-strategies).
``` json
"components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
},
```

See also #4386

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dhmlau** [comment]
@emonddr @jannyHou ^^

**Comment by jannyHou** [comment]
Good point, I created a PR to rename it in https://github.com/strongloop/loopback4-example-shopping/pull/504

**Comment by jannyHou** [comment]
updated in https://github.com/strongloop/loopback4-example-shopping/pull/504

**Comment by dougal83** [comment]
I've reverted #4386 to reflect this change.

**Comment by dhmlau** [comment]
@jannyHou @dougal83, since  strongloop/loopback4-example-shopping#504 has landed, is this issue good to close? Thanks.

**Comment by dougal83** [comment]
Closing as done.
