### ISSUE TITLE
docs: "API docs", "Connector reference" "edit this page" links to an invalid GitHub URL

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#4467]
## Steps to reproduce

1. Visit the LoopBack 4 (lb4) [API docs](https://loopback.io/doc/en/lb4/apidocs.index.html) or [Connector reference](https://loopback.io/doc/en/lb4/Connectors-reference.html) page
2. Optionally, navigate to any page part of the API docs or Connector reference.
3. Click the "Edit this page" button

## Current Behavior

The user is navigated to an invalid GitHub URL (such as the [API docs index page](https://github.com/strongloop/loopback-next/blob/master/docs/site/apidocs/index.md)).

## Expected Behavior

The "edit this page" button should be hidden, similar to doc pages generated by `README.md`.

## Link to reproduction sandbox

N/A

## Additional information

N/A

## Related Issues

N/A

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@achrinza, agree that we should hide the button because this page is generated.

**Comment by bajtos** [comment]
> The "edit this page" button should be hidden, similar to doc pages generated by README.md.

Alternatively, it would be awesome if the button "edit this page" could point to the source code file the API docs was generated from.

See Angular API docs for inspiration: open https://angular.io/api/animations/AnimationPlayer, click on the pencil icon at the top-right.

**Comment by achrinza** [comment]
This issue also seems to occur under [Connector reference](https://loopback.io/doc/en/lb4/Connectors-reference.html) and all of its sub-pages.
