### ISSUE TITLE
test fails if not running with en locale operating system

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-next#4487]
## Steps to reproduce

Having operating system **with locale other than `en_us`**, in my case locale is `de_de`.

```bash
git clone https://github.com/strongloop/loopback-next.git
cd loopback-next
npm install
cd packages/repository
npm test
```

## Current Behavior

Test fails when juggler returns localized message and test expects different language.

```
DefaultKeyValueRepository
    reports error from KeyValueRepository.ttl():
  AssertionError: expected [Promise] to be rejected with a message matching 'Cannot get TTL for unknown key "note2"', but got 'TTL für unbekannten Schlüssel "note2" kann nicht abgerufen werden'
    at next$onError (/tmp/loopback-next/packages/testlab/node_modules/should/as-function.js:1799:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is the source code of the failing test:
https://github.com/strongloop/loopback-next/blob/6105883967ca5853cc8990f423d9febd1eb07101/packages/repository/src/__tests__/unit/repositories/kv.repository.bridge.unit.ts#L75-L80

## Expected Behavior

Generated error messages should not have localisation to pass the test.

## Link to reproduction sandbox

n/a

## Additional information

```
$ lb4 -v
@loopback/cli version: 1.28.1

@loopback/* dependencies:
  - @loopback/authentication: ^3.3.0
  - @loopback/boot: ^1.7.1
  - @loopback/build: ^3.0.1
  - @loopback/context: ^1.25.1
  - @loopback/core: ^1.12.1
  - @loopback/metadata: ^1.3.10
  - @loopback/openapi-spec-builder: ^1.2.21
  - @loopback/openapi-v3: ^1.11.0
  - @loopback/repository-json-schema: ^1.11.4
  - @loopback/repository: ^1.17.0
  - @loopback/rest: ^1.25.1
  - @loopback/testlab: ^1.10.1
  - @loopback/docs: ^2.8.1
  - @loopback/example-hello-world: ^1.2.22
  - @loopback/example-log-extension: ^1.2.22
  - @loopback/example-rpc-server: ^1.2.22
  - @loopback/example-todo: ^1.9.4
  - @loopback/example-soap-calculator: ^1.7.4
  - @loopback/service-proxy: ^1.3.14
  - @loopback/http-caching-proxy: ^1.2.4
  - @loopback/http-server: ^1.5.1
  - @loopback/example-todo-list: ^1.12.4
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^1.4.7
  - @loopback/eslint-config: ^5.0.1
  - @loopback/example-express-composition: ^1.10.1
  - @loopback/example-greeter-extension: ^1.3.22
  - @loopback/booter-lb3app: ^1.3.9
  - @loopback/example-lb3-application: ^1.1.23
  - @loopback/example-greeting-app: ^1.2.9
  - @loopback/example-context: ^1.2.22
  - @loopback/repository-tests: ^0.9.0
  - @loopback/extension-health: ^0.2.14
  - @loopback/authorization: ^0.4.7
  - @loopback/rest-crud: ^0.6.3
  - @loopback/security: ^0.1.10
  - @loopback/authentication-passport: ^1.1.0
  - @loopback/example-metrics-prometheus: ^0.1.4
  - @loopback/extension-metrics: ^0.1.3
  - @loopback/model-api-builder: ^1.1.1
```

**Comment by jannyHou** [comment]
> de_de

Seems it falls back to the default lang.

**Comment by raymondfeng** [comment]
FYI: Behind the repository apis, we use LB3 juggler/connectors which are globalized using [strong-globalize](https://github.com/strongloop/strong-globalize).

**Comment by dhmlau** [comment]
I'm running into the same issue when extracting messages for translation.  For example
https://github.com/strongloop/loopback-next/blob/master/packages/cli/test/integration/generators/relation.integration.js#L67-L77
```
...
to.be.rejectedWith(/\"blabla\" model does not exist\./)
```
Since this message is coming from https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/relation/index.js#L21, I'm wondering if it's a good idea to use that variable instead of hard coding the error message. 

@raymondfeng @dougal83, what's your thoughts on this?

**Comment by dhmlau** [comment]
Capturing the conversation with @raymondfeng:
we can use one locale for tests and probably force it for `npm test` in package.json.

**Comment by dhmlau** [comment]
@derdeka, would it be a feasible solution for you?

**Comment by derdeka** [comment]
> @derdeka, would it be a feasible solution for you?

Forcing a locale in the tests would solve to make all tests passing on my localized operating system. This would really improve the developer experience.

When using a api server from a frontend like `angular` i would **not expect** to have error messages in the locale of the server's operating system. I think it would be better to request a specific locale with a custom parameter or http header (not the browser language header to switch the language). Having that said, maybe its possible to pass the requested locale by header in `@loopback/testlab` request too?
