### ISSUE TITLE
Make sure Persistence docs are up to date with code

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#449]
Go through loopback-next-example & loopback-next code and ensure that is reflected in the Persisting Data With Repositories (Juggler & No Juggler) Wiki Page. 

https://github.com/strongloop/loopback-next-example
https://github.com/strongloop/loopback-next/wiki/Persisting-Data-with-Repositories

**Comment by virkt25** [comment]
Example Repo & Wiki are consistent however actually implementing / running the implemented code doesn't work as expected. Below are the differences / changes that need to be made.

@bajtos Does the wiki take take precedence or the `@loopback/repository` code? 

## Persisting Data With Juggler
- importing juggler doesn’t work. Getting undefined. Need to import jugglerModule. 
- jugglerModule.ModelBase is not a thing but jugglerModule.ModelBaseClass is. Can’t use it however as it results in an error when settings it as a type as per Step 2 under DataSource Configuration. 

## Persisting Data Without Juggler
- Link to implementing CrudConnector is broken.
- Wiki uses newRepository but code in example is AccountRepository. Need to fix. 
- While the over process for defining a Repository is consistent between the code and the wiki, the API is failing to return data. Create works (but return doesn’t include object), Find gets the data but is not included in the response back from the API. Need to check with someone who worked on `account-without-juggler` to see what the issue might be.

**Comment by bajtos** [comment]
@virkt25 my knowledge of the persistence layer is pretty minimal. Could you please talk to @raymondfeng and @ritch to find out what's the best approach here?

**Comment by virkt25** [comment]
Updated Persisting With Juggler to remove `juggler.ModelBase` since it doesn't work.

**Comment by bajtos** [comment]
Is there anything else need? Can we close this issue as done?

**Comment by virkt25** [comment]
I needed to verify without-juggler. @raymondfeng helped me fix the `loopback-example-application/services/account-without-juggler` so I could verify the wiki.

Here's the latest change set for any feedback (after it this can be closed). 

Link: https://github.com/strongloop/loopback-next/wiki/Persisting-Data-with-Repositories/_compare/b1936c41baf627f00335cf33cad9b2d82de33865...421a52454ab7083e87e141c8034e3a996c6b8e09

cc: @b-admike @ritch

**Comment by bajtos** [comment]
> Here's the latest change set for any feedback (after it this can be closed).

I took a quick look and don't see any obvious problems. I'll leave it for somebody more experienced with persistence/repository component to do the final approval.

**Comment by raymondfeng** [comment]
LGTM
