### ISSUE TITLE
Mysql string id is null

### ISSUE THREAD

**Issue by KyDenZ** [strongloop/loopback-next#4512]
## Steps to reproduce

I have a MySQL database that contains data with a string format ID. A class is mapped to the data in my database. All data is returned except the id, is null. 

Initialize a loopback project, add a class with an id of type string, a mysql datasource.

```typescript
@property({
    type: 'string',
    id: true,
    required: true,
  })
  id?: string;
```

## Current Behavior

The problem is that the id is in string in my database. It is not the "varchar" type that is problematic, but that the value is a string. The data comes from keyclaok, I cannot change the id in number.

Besides, when I migrate with "npm run migrate" loopback creates the id in int type.

## Expected Behavior

We must be able to have ids in string from mysql.

## Additional information

darwin x64 12.14.1
@loopback/boot@1.7.1
@loopback/context@1.25.1
@loopback/core@1.12.1
@loopback/openapi-v3@1.11.0
@loopback/repository@1.17.0
@loopback/rest@1.25.1
@loopback/rest-explorer@1.4.7
@loopback/service-proxy@1.3.14

**Comment by dougal83** [comment]
Hey @KyDenZ 
I think #4270 is related, take a look.  Personally I'd try the following but I doubt that is the solution considering it is related to an identifier.

```ts
@property({
    type: 'string',
    id: true,
    required: true,
    mysql: {
      dataType: 'string',
    },
  })
  id?: string;
```

**Comment by KyDenZ** [comment]
Great, thank you ! I had not seen this pull request.
