### ISSUE TITLE
JsonSchemaOptions parameters conflict bug

### ISSUE THREAD

**Issue by 1057437122** [strongloop/loopback-next#4517]
## Steps to reproduce

1.  create a model, such as Store:id, name, taxNumber, createUserId(belongs to a user), countryId(belongs to a country)
2. create a repository with default option for model Store
3. create a controller with model and repository created before.
4. edit openapi document  like this in GET /stores controller
```
 @get('/stores', {
    responses: {
      '200': {
        description: 'Array of Store model instances',
        content: {
          'application/json': {
            schema: {
              type: 'array',
              items: getModelSchemaRef(Store, {
                title: 'StoreLists',
                includeRelations: true,
                exclude: ['id', 'createUserId', 'countryId'],
              }),
            },
          },
        },
      },
    },
  })
```

## Current Behavior

open in browser and scroll to this controller,  find response -> example value, the relation data such as country is wrong, in the example, the data are for the model store instead of country

## Expected Behavior

the relation data in the example should be a correct instance model.

if i don't use title and includeRelations in the same time, everything goes correct.

BTW, how to exclude some relation data? Such as a store model have a countryId(belong to a country), and a createUserId(belong to a user), how can i exclude 'createUser' in the response but keep country information ?

**Comment by dougal83** [comment]
Hi @1057437122 

It is a little hard to give advice based on what you've said.  Could you perhaps create a public repo on your account to demonstrate your issue?

Have you set up the relations correctly?  You can follow the [todo tutorial](https://loopback.io/doc/en/lb4/todo-list-tutorial-relations.html) if that helps.

**Comment by 1057437122** [comment]
> Hi @1057437122
> 
> It is a little hard to give advice based on what you've said. Could you perhaps create a public repo on your account to demonstrate your issue?
> 
> Have you set up the relations correctly? You can follow the [todo tutorial](https://loopback.io/doc/en/lb4/todo-list-tutorial-relations.html) if that helps.

Sure, sorry for my bad english, the repo is here:
https://github.com/1057437122/lb4jsonschemaoption.git

configuration is here: src/controller/store.controller.ts

**Comment by 1057437122** [comment]
First I only add @belongTo decorator in the model, the error is like the picture, then I added belongToAccessFor in repository , same error

**Comment by dougal83** [comment]
I'm not sure you can have a model that belongs to more than one other model although that is not specified in the [documentation](https://loopback.io/doc/en/lb4/BelongsTo-relation.html). Perhaps could you try an experiment using the `lb4 relation` command to set up your relations and see if it complains?

I would try myself but I'm traveling with only my smartphone.

**Comment by 1057437122** [comment]
yep, now i tried to add a store belong to a province with command `lb4 relation`, it's the same. 
btw, i tried in my other project, the real data respond from server is right, only there's something wrong with openapi document

**Comment by dougal83** [comment]
Having had a look, the relations were not configured completely and there were a few minor issues.  Rather than explain it... take a look at the following commit on your code that fixes the includes:

[Fix commit](https://github.com/dougal83/lb4jsonschemaoption/commit/3c49b6f18c8603820a79a802e07851f9a9875440)

Feel free to ask any particular questions on changes and I'll try to explain but I've had a busy day so I'll let the code do the talking. :)

**Comment by 1057437122** [comment]
> Having had a look, the relations were not configured completely and there were a few minor issues. Rather than explain it... take a look at the following commit on your code that fixes the includes:
> 
> [Fix commit](https://github.com/dougal83/lb4jsonschemaoption/commit/3c49b6f18c8603820a79a802e07851f9a9875440)
> 
> Feel free to ask any particular questions on changes and I'll try to explain but I've had a busy day so I'll let the code do the talking. :)

Thanks for your help. But I cloned your repo and started, in my browser, still it's error, this is my capture. 
![11580308631_ pic_hd](https://user-images.githubusercontent.com/6631168/73365847-42759900-42ad-11ea-961a-ab815d47e1cc.jpg)
![21580308760_ pic_hd](https://user-images.githubusercontent.com/6631168/73366026-89638e80-42ad-11ea-9ca9-8420cfa7d679.jpg)

may be error is because of my environments ?

**Comment by dougal83** [comment]
> may be error is because of my environments ?

No, it is most likely something simpler. I made the changes on a new branch called 'alteration'(not master).  Try `git checkout alteration` :)

**Comment by 1057437122** [comment]
Thank you for your patients ! I got it !
