### ISSUE TITLE
[migration/auth] Migrate https://github.com/strongloop/loopback-example-access-control to LB4

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#4520]
## Suggestion

Create an example in LoopBack 4 to illustrate similar access control features as https://github.com/strongloop/loopback-example-access-control. The other option is to add similar features to an existing example such as https://github.com/strongloop/loopback4-example-shopping.

## Acceptance criteria

- [x] The example should have ability to authenticate 4 users
  - Use user/user credential DB tables
- [x] Support 4 different roles - guest, owner, team member, administrator
- [x] Authorize different routes against different users/roles
- [x] Document the migration at https://github.com/strongloop/loopback-next/blob/auth-migration/docs/site/migration/auth/example.md

**Comment by jannyHou** [comment]
PR created in https://github.com/strongloop/loopback-next/pull/4571, in progress

**Comment by jannyHou** [comment]
close after merging https://github.com/strongloop/loopback-next/pull/4706
follow up stories: 
- https://github.com/strongloop/loopback-next/issues/4753
- 2nd phase improvement for casbin persistence(TBD)
