### ISSUE TITLE
[migration/auth] Create a guide to describe how to migrate LB3 User based authentication to LB4

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#4521]
Create a guide to describe how to migrate LB3 built-in User/AccessToken model based authentication

## Acceptance criteria

- [x] Describe usage of LB4 datasource and repository for the user/access token data access
- [x] Migrate model definitions from LB3 User/AccessToken to LB4
- [x] Create a login controller to perform authentication
- [x] Create a token service to generate access tokens
- [x] Create an authentication strategy to validate access tokens
- [x] Update https://github.com/strongloop/loopback-next/blob/auth-migration/docs/site/migration/auth/built-in.md

**Comment by dhmlau** [comment]
@bajtos @jannyHou, I'd like to continue the discussion from https://github.com/strongloop/loopback-next/pull/4571#discussion_r383710046 of having a reusable extension/component for the JWT authentication. If that's what we're going to create, should we get that component created first before working on this docs? 

cc @raymondfeng

**Comment by jannyHou** [comment]
@dhmlau Yes. Moving here after close https://github.com/strongloop/loopback-next/issues/4753

**Comment by jannyHou** [comment]
Will address the comment in https://github.com/strongloop/loopback-next/pull/4706#discussion_r383625928

**Comment by jannyHou** [comment]
closed as PRs merged. 🎉
