### ISSUE TITLE
Migration guide between LB3 to LB4 [MVP]

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#453]
Migrating between LB3 to LB4 and related documentation.

**Comment by dhmlau** [comment]
Removing `LoopBackNext-beta` label, because we're not planning to get it in for beta.

**Comment by bajtos** [comment]
@Spragalas I am afraid the migration story is not clear yet, see #1849 for more details.

**Comment by dhmlau** [comment]
FYI - Migration guide: https://loopback.io/doc/en/lb4/migration-overview.html. It is still working in progress. We'll be filling in more details and the docs will be found under this link.

**Comment by dhmlau** [comment]
Closing as done!
