### ISSUE TITLE
lb-tsc does not build dist folder with tsconfig.json key $schema value present

### ISSUE THREAD

**Issue by t2mercer** [strongloop/loopback-next#4545]
## Steps to reproduce
lb4 example (any example)
open tsconfig.json - it will look like the below.

{
  "$schema": "http://json.schemastore.org/tsconfig",
  "extends": "@loopback/build/config/tsconfig.common.json",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src"]
}
npm run build
time stamps on files in dist folder do not change even though command executes properly

## Current Behavior

time stamps on files in dist folder do not change even though command executes properly - ts files do not get compiled.

## Expected Behavior

time stamps on files in dist folder to change and files to be updated - ts files get correctly compiled

## Link to reproduction sandbox

Any local system that is configured to run any lb4 example

## Additional information

This can be resolved by doing one of the following two things:
1) delete the tsconfig.json file from the generated directory because when npm run build is run again it will generate a tsconfig.json file (which will look like this)

{
  "extends": "./node_modules/@loopback/build/config/tsconfig.common.json",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": [
    "src"
  ]
}

Note that $schema value is removed.

2) Please remove the $schema key:value pair in the examples' tsconfig.json files

## Related Issues

Searched for related issues without luck.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
Try to run `npm run clean && npm run build`

**Comment by t2mercer** [comment]
lb4 example soap-calculator
cd ./loopback4-example-soap-calculator
npm run clean && npm run build 

updated then run the following again

npm run build

not updated this time so try running the following again

npm run clean && npm run build 

now dist folder deleted ... oops

so ... delete both tsconfig.json and tsconfig.tsbuildinfo

run the following

npm run clean && npm run build 

this creates tsconfig.json WITHOUT THE $schema key value pair

and produces the dist directory.

The issue, to me, who admittedly is very new to all of this, is related to the key value pair in the tsconfig.json file.

**Comment by raymondfeng** [comment]
I can reproduce the problem now. Please delete `tsconfig.tsbuildinfo` and `npm run build` should be working. I'll investigate a fix to avoid the manual step.

**Comment by t2mercer** [comment]
confirmed.  
removing tsconfig.tsbuildinfo rebuilds dist folder after npm run clean had deleted it and then you execute npm run build.
Thank you for the guidance.

**Comment by t2mercer** [comment]
The issue is with the package.json file.

change

    "clean": "lb-clean *example-soap*.tgz dist package api-docs dist tsconfig.build.tsbuildinfo",

to 

    "clean": "lb-clean *example-soap*.tgz dist package api-docs dist tsconfig.tsbuildinfo",

**Comment by raymondfeng** [comment]
You can update package.json to replace `tsconfig.build.tsbuildinfo` with `tsconfig.tsbuildinfo` so that `npm run clean` works.

**Comment by t2mercer** [comment]
yup :-)
