### ISSUE TITLE
includeRelations bug

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#4547]
## Steps to reproduce

Checkout https://github.com/strongloop/loopback4-example-shopping/tree/bug/include-relations.

Run `npm t`, it will fail with: `Error: expected 200 "OK", got 422 "Unprocessable Entity"`.

Now, change `getModelSchemaRef(Order, {includeRelations: true})`  to `getModelSchemaRef(Order)` in `order.controllers.ts`. Run `npm t` again, test will pass now.

## Apparent Cause

The actual schema of `NewUserRequest` model is being overwritten by its parent model `User`, hence the request body becomes unprocessable as the `User` model does not have a password property.

## Acceptance Criteia

- [ ] Fix the bug
- [ ] Publish new package
- [ ] `npm t` on https://github.com/strongloop/loopback4-example-shopping/tree/bug/include-relations should pass with the updated package.

**Comment by dhmlau** [comment]
cc @jannyHou

**Comment by hacksparrow** [comment]
Checked with the latest dependencies, it is working fine now. Maybe something in the later version of `@loopback/repository` fixed it? Since the version used in the buggy app is one major version lower, it is hard to check what was causing it.

@jannyHou any idea? I remember you had mentioned of a probable cause.

**Comment by jannyHou** [comment]
@hacksparrow There are some PR related to the `title` inheritance months ago(searching it : p), it might fix this issue as well. If you confirmed the bug is fixed, then feel free to close it.
