### ISSUE TITLE
Inconsistent OpenAPI Validation with multiple OpenAPI Datasource

### ISSUE THREAD

**Issue by vhidvz** [strongloop/loopback-next#4553]
As you want to create multiple Datasource with OpenAPI connector, the Validator seems mixed them up.

Steps to regenerate this issue [Multiple OpenAPI Usage](#multiple_openapi_usage).

# Steps to Reproduce

1.  ```git clone https://github.com/vhidvz/loopback-next.git```

2.  ```cd loopback-next/examples/mutiple-openapis-usage```

3.  MongoDB database (if you need):

    ```docker run --name some-mongo -p 27017:27017 -d mongo:4.2```

4.  ```node deployOtherServices.js```

5.  ```npm install && npm run test```

# Current Behavior

It does looking for #/components/schemas/Session $ref in the User OpenApi.json file. But, it does never defined at this endpoint. [Issue](#issue)

# Additional Information

OS:

```
$ lsb_release -a

    LSB Version:	n/a
    Distributor ID:	ManjaroLinux
    Description:	Manjaro Linux
    Release:	18.1.5
    Codename:	Juhraya
```

NODE:

```
$ node --version

    v13.7.0
```

LB4:

```
$ lb4 --version

    @loopback/cli version: 1.29.0

    @loopback/* dependencies:
    - @loopback/authentication: ^3.3.1
    - @loopback/boot: ^1.7.2
    - @loopback/build: ^3.1.0
    - @loopback/context: ^2.0.0
    - @loopback/core: ^1.12.2
    - @loopback/metadata: ^1.4.0
    - @loopback/openapi-spec-builder: ^1.3.0
    - @loopback/openapi-v3: ^1.12.0
    - @loopback/repository-json-schema: ^1.12.0
    - @loopback/repository: ^1.18.0
    - @loopback/rest: ^1.26.0
    - @loopback/testlab: ^1.10.2
    - @loopback/docs: ^2.9.0
    - @loopback/example-hello-world: ^1.2.23
    - @loopback/example-log-extension: ^1.2.23
    - @loopback/example-rpc-server: ^1.2.23
    - @loopback/example-todo: ^1.9.5
    - @loopback/example-soap-calculator: ^1.7.5
    - @loopback/service-proxy: ^1.3.15
    - @loopback/http-caching-proxy: ^1.2.5
    - @loopback/http-server: ^1.5.2
    - @loopback/example-todo-list: ^1.12.5
    - @loopback/dist-util: ^0.4.0
    - @loopback/rest-explorer: ^1.4.8
    - @loopback/eslint-config: ^5.0.2
    - @loopback/example-express-composition: ^1.10.2
    - @loopback/example-greeter-extension: ^1.3.23
    - @loopback/booter-lb3app: ^1.3.10
    - @loopback/example-lb3-application: ^1.1.24
    - @loopback/example-greeting-app: ^1.2.10
    - @loopback/example-context: ^1.3.0
    - @loopback/repository-tests: ^0.9.1
    - @loopback/extension-health: ^0.2.15
    - @loopback/authorization: ^0.4.8
    - @loopback/rest-crud: ^0.6.4
    - @loopback/security: ^0.1.11
    - @loopback/authentication-passport: ^1.1.1
    - @loopback/example-metrics-prometheus: ^0.1.5
    - @loopback/extension-metrics: ^0.1.4
    - @loopback/model-api-builder: ^1.1.2
```

# <a name="issue">Issue</a>

Seems, It does looking for #/components/schemas/Session in the User OpenApi.json file. But, it does never defined at this endpoint.

<pre>
&gt; mutiple-openapis-usage@1.0.0 prestart /home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage
&gt; npm run build

&gt; mutiple-openapis-usage@1.0.0 build /home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage
&gt; lb-tsc

&gt; mutiple-openapis-usage@1.0.0 start /home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage
&gt; node -r source-map-support/register .

Server is running at http://[::1]:3000
Try http://[::1]:3000/ping
Connection fails: SyntaxError: Error resolving $ref pointer &quot;http://[::1]:3010/openapi.json#/components/schemas/Session&quot;.
Token &quot;Session&quot; does not exist.
It will be retried for the next request.

/home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/json-schema-ref-parser/lib/pointer.js:87
      throw ono.syntax(&apos;Error resolving $ref pointer &quot;%s&quot;. \nToken &quot;%s&quot; does not exist.&apos;, this.originalPath, token);
                ^
SyntaxError: Error resolving $ref pointer &quot;http://[::1]:3010/openapi.json#/components/schemas/Session&quot;.
Token &quot;Session&quot; does not exist.
    at Pointer.resolve (/home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/json-schema-ref-parser/lib/pointer.js:87:17)
    at $Ref.resolve (/home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/json-schema-ref-parser/lib/ref.js:83:18)
    at $Refs._resolve (/home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/json-schema-ref-parser/lib/refs.js:155:15)
    at dereference$Ref (/home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/json-schema-ref-parser/lib/dereference.js:99:23)
    at /home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/json-schema-ref-parser/lib/dereference.js:58:26
    at Array.forEach (&lt;anonymous&gt;)
    at crawl (/home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/json-schema-ref-parser/lib/dereference.js:51:24)
    at /home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/json-schema-ref-parser/lib/dereference.js:64:28
    at Array.forEach (&lt;anonymous&gt;)
    at crawl (/home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/json-schema-ref-parser/lib/dereference.js:51:24)
    at /home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/json-schema-ref-parser/lib/dereference.js:64:28
    at Array.forEach (&lt;anonymous&gt;)
    at crawl (/home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/json-schema-ref-parser/lib/dereference.js:51:24)
    at /home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/json-schema-ref-parser/lib/dereference.js:64:28
    at Array.forEach (&lt;anonymous&gt;)
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">code</font> ELIFECYCLE
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> <font color="#AA00AA">errno</font> 1
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> mutiple-openapis-usage@1.0.0 start: `node -r source-map-support/register .`
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> Exit status 1
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span>
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> Failed at the mutiple-openapis-usage@1.0.0 start script.
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> This is probably not a problem with npm. There is likely additional logging output above.

<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#000000"><font color="#AAAAAA">npm</font></span> <span style="background-color:#000000"><font color="#AA0000">ERR!</font></span>     /home/vahid/.npm/_logs/2020-01-28T08_13_01_223Z-debug.log</pre>

Debug File Context: ```vahid/.npm/_logs/2020-01-28T08_13_01_223Z-debug.log```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.13.6
3 info using node@v13.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mutiple-openapis-usage@1.0.0~prestart: mutiple-openapis-usage@1.0.0
6 verbose lifecycle mutiple-openapis-usage@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle mutiple-openapis-usage@1.0.0~prestart: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/.bin:/home/vahid/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
8 verbose lifecycle mutiple-openapis-usage@1.0.0~prestart: CWD: /home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage
9 silly lifecycle mutiple-openapis-usage@1.0.0~prestart: Args: [ '-c', 'npm run build' ]
10 silly lifecycle mutiple-openapis-usage@1.0.0~prestart: Returned: code: 0  signal: null
11 info lifecycle mutiple-openapis-usage@1.0.0~start: mutiple-openapis-usage@1.0.0
12 verbose lifecycle mutiple-openapis-usage@1.0.0~start: unsafe-perm in lifecycle true
13 verbose lifecycle mutiple-openapis-usage@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage/node_modules/.bin:/home/vahid/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
14 verbose lifecycle mutiple-openapis-usage@1.0.0~start: CWD: /home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage
15 silly lifecycle mutiple-openapis-usage@1.0.0~start: Args: [ '-c', 'node -r source-map-support/register .' ]
16 silly lifecycle mutiple-openapis-usage@1.0.0~start: Returned: code: 1  signal: null
17 info lifecycle mutiple-openapis-usage@1.0.0~start: Failed to exec start script
18 verbose stack Error: mutiple-openapis-usage@1.0.0 start: `node -r source-map-support/register .`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
18 verbose stack     at EventEmitter.emit (events.js:321:20)
18 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:321:20)
18 verbose stack     at maybeClose (internal/child_process.js:1026:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
19 verbose pkgid mutiple-openapis-usage@1.0.0
20 verbose cwd /home/vahid/WorkSpace/loopback-next/examples/mutiple-openapis-usage
21 verbose Linux 5.4.14-2-MANJARO
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
23 verbose node v13.7.0
24 verbose npm  v6.13.6
25 error code ELIFECYCLE
26 error errno 1
27 error mutiple-openapis-usage@1.0.0 start: `node -r source-map-support/register .`
27 error Exit status 1
28 error Failed at the mutiple-openapis-usage@1.0.0 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]
```

# <a name="multiple_openapi_usage">Multiple OpenAPI Usage</a>

All steps are going done with @loopback/cli version: 1.29.0.

Under examples/multiple-openapis-usage directory. (PORT: 3000)

Other API Services:

-   [User Api Configuration (PORT: 3010)](#user_api_configuration)
-   [Session Api Configuration (PORT: 3020)](#session_api_configuration)

#### Step 1\4. ```lb4 app```

<pre><font color="#00AA00">?</font> <b>Project name:</b> <font color="#00AAAA">mutiple-openapis-usage</font>
<font color="#00AA00">?</font> <b>Project description:</b> <font color="#00AAAA">mutiple openapis usage</font>
<font color="#00AA00">?</font> <b>Project root directory:</b> <font color="#00AAAA">mutiple-openapis-usage</font>
<font color="#00AA00">?</font> <b>Application class name:</b> <font color="#00AAAA">MutipleOpenapisUsageApplication</font>
<font color="#00AA00">?</font> <b>Select features to enable in the project</b> (Press <font color="#00AAAA"><b>&lt;space&gt;</b></font> to select, <font color="#00AAAA"><b>&lt;a&gt;</b></font> to togg
le all, <font color="#00AAAA"><b>&lt;i&gt;</b></font> to invert selection)<font color="#00AAAA">Enable eslint, Enable prettier, Enable mocha, En</font>
<font color="#00AAAA">able loopbackBuild, Enable vscode, Enable docker, Enable repositories, Enable se</font>
<font color="#00AAAA">rvices</font></pre>

#### Step 2\4. ```lb4 model login```

<pre><font color="#00AA00">?</font> <b>Please select the model base class</b> <font color="#00AAAA">Model </font><font color="#555555">(A business domain object)</font>
<font color="#00AA00">?</font> <b>Allow additional (free-form) properties?</b> <font color="#00AAAA">No</font>
Model <font color="#AA5500">Login</font> will be created in src/models/<font color="#AA5500">login.model.ts</font>

Let&apos;s add a property to <font color="#AA5500">Login</font>
Enter an empty property name when done

<font color="#00AA00">?</font> <b>Enter the property name:</b> <font color="#00AAAA">username</font>
<font color="#00AA00">?</font> <b>Property type:</b> <font color="#00AAAA">string</font>
<font color="#00AA00">?</font> <b>Is </b><font color="#AA5500"><b>username</b></font><b> the ID property?</b> <font color="#00AAAA">No</font>
<font color="#00AA00">?</font> <b>Is it required?:</b> <font color="#00AAAA">Yes</font>
<font color="#00AA00">?</font> <b>Default value </b><font color="#AA5500"><b>[leave blank for none]</b></font><b>:</b>

Let&apos;s add another property to <font color="#AA5500">Login</font>
Enter an empty property name when done

<font color="#00AA00">?</font> <b>Enter the property name:</b> <font color="#00AAAA">password</font>
<font color="#00AA00">?</font> <b>Property type:</b> <font color="#00AAAA">string</font>
<font color="#00AA00">?</font> <b>Is </b><font color="#AA5500"><b>password</b></font><b> the ID property?</b> <font color="#00AAAA">No</font>
<font color="#00AA00">?</font> <b>Is it required?:</b> <font color="#00AAAA">Yes</font>
<font color="#00AA00">?</font> <b>Default value </b><font color="#AA5500"><b>[leave blank for none]</b></font><b>:</b>

Let&apos;s add another property to <font color="#AA5500">Login</font>
Enter an empty property name when done

<font color="#00AA00">?</font> <b>Enter the property name:</b>
<font color="#00AA00">   create</font> src/models/login.model.ts
<font color="#00AA00">   update</font> src/models/index.ts

Model <font color="#AA5500">Login</font> was created in src/models/</pre>

#### Step 3\4. ```lb4 datasource users```

<pre><font color="#00AA00">?</font> <b>Select the connector for </b><font color="#AA5500"><b>users</b></font><b>:</b> <font color="#00AAAA">OpenAPI </font><font color="#555555">(supported by StrongLoop)</font>
<font color="#00AA00">?</font> <b>HTTP URL/path to Swagger spec file (file name extension .yaml/.yml or .json)</b>:
<font color="#00AAAA">http://[::1]:3010/openapi.json</font>
<font color="#00AA00">?</font> <b>Validate spec against Swagger spec 2.0?</b>: <font color="#00AAAA">No</font>
<font color="#00AA00">?</font> <b>Security config for making authenticated requests to API</b>:
<font color="#00AA00">?</font> <b>Use positional parameters instead of named parameters?</b>: <font color="#00AAAA">No</font>
<font color="#00AA00">   create</font> src/datasources/users.datasource.config.json
<font color="#00AA00">   create</font> src/datasources/users.datasource.ts</pre>

#### Step 4\4. ```lb4 datasource sessions```

<pre><font color="#00AA00">?</font> <b>Select the connector for </b><font color="#AA5500"><b>sessions</b></font><b>:</b> <font color="#00AAAA">OpenAPI </font><font color="#555555">(supported by StrongLoop)</font>
<font color="#00AA00">?</font> <b>HTTP URL/path to Swagger spec file (file name extension .yaml/.yml or .json)</b>:
<font color="#00AAAA">http://[::1]:3020/openapi.json</font>
<font color="#00AA00">?</font> <b>Validate spec against Swagger spec 2.0?</b>: <font color="#00AAAA">No</font>
<font color="#00AA00">?</font> <b>Security config for making authenticated requests to API</b>:
<font color="#00AA00">?</font> <b>Use positional parameters instead of named parameters?</b>: <font color="#00AAAA">No</font>
<font color="#00AA00">   create</font> src/datasources/sessions.datasource.config.json
<font color="#00AA00">   create</font> src/datasources/sessions.datasource.ts
<font color="#00AA00">   update</font> src/datasources/index.ts

Datasource <font color="#AA5500">Sessions</font> was created in src/datasources/</pre>

#### Final Step.

    export PORT=3000 && npm start

## <a name="user_api_configuration">User Api Configuration</a>

Under examples/multiple-openapis-usage/loopback-openapis directory. (PORT: 3010)

#### Step 1\5. ```lb4 app user-api```

<pre><font color="#00AA00">?</font> <b>Project description:</b> <font color="#00AAAA">user-api</font>
<font color="#00AA00">?</font> <b>Project root directory:</b> <font color="#00AAAA">user-api</font>
<font color="#00AA00">?</font> <b>Application class name:</b> <font color="#00AAAA">UserApiApplication</font>
<font color="#00AA00">?</font> <b>Select features to enable in the project</b> (Press <font color="#00AAAA"><b>&lt;space&gt;</b></font> to select, <font color="#00AAAA"><b>&lt;a&gt;</b></font> to togg
le all, <font color="#00AAAA"><b>&lt;i&gt;</b></font> to invert selection)<font color="#00AAAA">Enable eslint, Enable prettier, Enable mocha, En</font>
<font color="#00AAAA">able loopbackBuild, Enable vscode, Enable docker, Enable repositories, Enable se</font>
<font color="#00AAAA">rvices</font></pre>

#### Step 2\5. ```lb4 model User```

<pre><font color="#00AA00">?</font> <b>Please select the model base class</b> <font color="#00AAAA">Entity </font><font color="#555555">(A persisted model with an ID)</font>
<font color="#00AA00">?</font> <b>Allow additional (free-form) properties?</b> <font color="#00AAAA">No</font>
Model <font color="#AA5500">User</font> will be created in src/models/<font color="#AA5500">user.model.ts</font>

Let&apos;s add a property to <font color="#AA5500">User</font>
Enter an empty property name when done

<font color="#00AA00">?</font> <b>Enter the property name:</b> <font color="#00AAAA">id</font>
<font color="#00AA00">?</font> <b>Property type:</b> <font color="#00AAAA">string</font>
<font color="#00AA00">?</font> <b>Is </b><font color="#AA5500"><b>id</b></font><b> the ID property?</b> <font color="#00AAAA">Yes</font>
<font color="#00AA00">?</font> <b>Is </b><font color="#AA5500"><b>id</b></font><b> generated automatically?</b> <font color="#00AAAA">Yes</font>

Let&apos;s add another property to <font color="#AA5500">User</font>
Enter an empty property name when done

<font color="#00AA00">?</font> <b>Enter the property name:</b> <font color="#00AAAA">username</font>
<font color="#00AA00">?</font> <b>Property type:</b> <font color="#00AAAA">string</font>
<font color="#00AA00">?</font> <b>Is it required?:</b> <font color="#00AAAA">Yes</font>
<font color="#00AA00">?</font> <b>Default value </b><font color="#AA5500"><b>[leave blank for none]</b></font><b>:</b>

Let&apos;s add another property to <font color="#AA5500">User</font>
Enter an empty property name when done

<font color="#00AA00">?</font> <b>Enter the property name:</b> <font color="#00AAAA">password</font>
<font color="#00AA00">?</font> <b>Property type:</b> <font color="#00AAAA">string</font>
<font color="#00AA00">?</font> <b>Is it required?:</b> <font color="#00AAAA">Yes</font>
<font color="#00AA00">?</font> <b>Default value </b><font color="#AA5500"><b>[leave blank for none]</b></font><b>:</b>

Let&apos;s add another property to <font color="#AA5500">User</font>
Enter an empty property name when done

<font color="#00AA00">?</font> <b>Enter the property name:</b>
<font color="#00AA00">   create</font> src/models/user.model.ts
<font color="#00AA00">   update</font> src/models/index.ts

Model <font color="#AA5500">User</font> was created in src/models/</pre>

#### Step 3\5. ```lb4 datasource db```

<pre><font color="#00AA00">?</font> <b>Select the connector for </b><font color="#AA5500"><b>db</b></font><b>:</b> <font color="#00AAAA">MongoDB </font><font color="#555555">(supported by StrongLoop)</font>
<font color="#00AA00">?</font> <b>Connection String url to override other settings (eg: mongodb://username:passw</b>
<b>ord@hostname:port/database)</b>: <font color="#00AAAA">mongodb://localhost:27017/users</font>
<font color="#00AA00">?</font> <b>host</b>: <font color="#00AAAA">localhost</font>
<font color="#00AA00">?</font> <b>port</b>: <font color="#00AAAA">27017</font>
<font color="#00AA00">?</font> <b>user</b>:
<font color="#00AA00">?</font> <b>password</b>: <font color="#939B9D"><i>[hidden]</i></font>
<font color="#00AA00">?</font> <b>database</b>: <font color="#00AAAA">users</font>
<font color="#00AA00">?</font> <b>Feature supported by MongoDB v3.1.0 and above</b>: <font color="#00AAAA">Yes</font>
<font color="#00AA00">   create</font> src/datasources/db.datasource.config.json
<font color="#00AA00">   create</font> src/datasources/db.datasource.ts</pre>

#### Step 4\5. ```lb4 repository```

<pre><font color="#00AA00">?</font> <b>Please select the datasource</b> <font color="#00AAAA">DbDatasource</font>
<font color="#00AA00">?</font> <b>Select the model(s) you want to generate a repository</b> <font color="#00AAAA">User</font>
<font color="#00AA00">?</font> <b>Please select the repository base class</b> <font color="#00AAAA">DefaultCrudRepository </font><font color="#555555">(Legacy juggler </font>
<font color="#555555">bridge)</font>
<font color="#00AA00">   create</font> src/repositories/user.repository.ts
<font color="#00AA00">   update</font> src/repositories/index.ts

Repository <font color="#AA5500">UserRepository</font> was created in src/repositories/</pre>

#### Step 5\5. ```lb4 controller```

<pre><font color="#00AA00">?</font> <b>Controller class name:</b> <font color="#00AAAA">User</font>
Controller <font color="#AA5500">User</font> will be created in src/controllers/<font color="#AA5500">user.controller.ts</font>

<font color="#00AA00">?</font> <b>What kind of controller would you like to generate?</b> <font color="#00AAAA">REST Controller with CRUD </font>
<font color="#00AAAA">functions</font>
<font color="#00AA00">?</font> <b>What is the name of the model to use with this CRUD repository?</b> <font color="#00AAAA">User</font>
<font color="#00AA00">?</font> <b>What is the name of your CRUD repository?</b> <font color="#00AAAA">UserRepository</font>
<font color="#00AA00">?</font> <b>What is the name of ID property?</b> <font color="#00AAAA">id</font>
<font color="#00AA00">?</font> <b>What is the type of your ID?</b> <font color="#00AAAA">string</font>
<font color="#00AA00">?</font> <b>Is the id omitted when creating a new instance?</b> <font color="#00AAAA">No</font>
<font color="#00AA00">?</font> <b>What is the base HTTP path name of the CRUD operations?</b> <font color="#00AAAA">/users</font>
<font color="#00AA00">   create</font> src/controllers/user.controller.ts
<font color="#00AA00">   update</font> src/controllers/index.ts

Controller <font color="#AA5500">User</font> was created in src/controllers/</pre>

#### Final Step.

    export PORT=3010 && npm start

## <a name="session_api_configuration">Session Api Configuration</a>

Under examples/multiple-openapis-usage/loopback-openapis directory. (PORT: 3020)

#### Step 1\5. ```lb4 app session-api```

<pre><font color="#00AA00">?</font> <b>Project description:</b> <font color="#00AAAA">session-api</font>
<font color="#00AA00">?</font> <b>Project root directory:</b> <font color="#00AAAA">session-api</font>
<font color="#00AA00">?</font> <b>Application class name:</b> <font color="#00AAAA">SessionApiApplication</font>
<font color="#00AA00">?</font> <b>Select features to enable in the project</b> (Press <font color="#00AAAA"><b>&lt;space&gt;</b></font> to select, <font color="#00AAAA"><b>&lt;a&gt;</b></font> to togg
le all, <font color="#00AAAA"><b>&lt;i&gt;</b></font> to invert selection)<font color="#00AAAA">Enable eslint, Enable prettier, Enable mocha, En</font>
<font color="#00AAAA">able loopbackBuild, Enable vscode, Enable docker, Enable repositories, Enable se</font>
<font color="#00AAAA">rvices</font></pre>

#### Step 2\5. ```lb4 model Session```

<pre><font color="#00AA00">?</font> <b>Please select the model base class</b> <font color="#00AAAA">Entity </font><font color="#555555">(A persisted model with an ID)</font>
<font color="#00AA00">?</font> <b>Allow additional (free-form) properties?</b> <font color="#00AAAA">Yes</font>
Model <font color="#AA5500">Session</font> will be created in src/models/<font color="#AA5500">session.model.ts</font>

Let&apos;s add a property to <font color="#AA5500">Session</font>
Enter an empty property name when done

<font color="#00AA00">?</font> <b>Enter the property name:</b> <font color="#00AAAA">id</font>
<font color="#00AA00">?</font> <b>Property type:</b> <font color="#00AAAA">string</font>
<font color="#00AA00">?</font> <b>Is </b><font color="#AA5500"><b>id</b></font><b> the ID property?</b> <font color="#00AAAA">Yes</font>
<font color="#00AA00">?</font> <b>Is </b><font color="#AA5500"><b>id</b></font><b> generated automatically?</b> <font color="#00AAAA">Yes</font>

Let&apos;s add another property to <font color="#AA5500">Session</font>
Enter an empty property name when done

<font color="#00AA00">?</font> <b>Enter the property name:</b>
<font color="#00AA00">   create</font> src/models/session.model.ts
<font color="#00AA00">   update</font> src/models/index.ts

Model <font color="#AA5500">Session</font> was created in src/models/</pre>

#### Step 3\5. ```lb4 datasource db```

<pre><font color="#00AA00">?</font> <b>Select the connector for </b><font color="#AA5500"><b>db</b></font><b>:</b> <font color="#00AAAA">MongoDB </font><font color="#555555">(supported by StrongLoop)</font>
<font color="#00AA00">?</font> <b>Connection String url to override other settings (eg: mongodb://username:passw</b>
<b>ord@hostname:port/database)</b>: <font color="#00AAAA">mongodb://localhost:27017/sessions</font>
<font color="#00AA00">?</font> <b>host</b>: <font color="#00AAAA">localhost</font>
<font color="#00AA00">?</font> <b>port</b>: <font color="#00AAAA">27017</font>
<font color="#00AA00">?</font> <b>user</b>:
<font color="#00AA00">?</font> <b>password</b>: <font color="#939B9D"><i>[hidden]</i></font>
<font color="#00AA00">?</font> <b>database</b>: <font color="#00AAAA">sessions</font>
<font color="#00AA00">?</font> <b>Feature supported by MongoDB v3.1.0 and above</b>: <font color="#00AAAA">Yes</font>
<font color="#00AA00">   create</font> src/datasources/db.datasource.config.json
<font color="#00AA00">   create</font> src/datasources/db.datasource.ts</pre>

#### Step 4\5. ```lb4 repository```

<pre><font color="#00AA00">?</font> <b>Please select the datasource</b> <font color="#00AAAA">DbDatasource</font>
<font color="#00AA00">?</font> <b>Select the model(s) you want to generate a repository</b> <font color="#00AAAA">Session</font>
<font color="#00AA00">?</font> <b>Please select the repository base class</b> <font color="#00AAAA">DefaultCrudRepository </font><font color="#555555">(Legacy juggler </font>
<font color="#555555">bridge)</font>
<font color="#00AA00">   create</font> src/repositories/session.repository.ts
<font color="#00AA00">   update</font> src/repositories/index.ts

Repository <font color="#AA5500">SessionRepository</font> was created in src/repositories/
</pre>

#### Step 5\5. ```lb4 controller```

<pre><font color="#00AA00">?</font> <b>Controller class name:</b> <font color="#00AAAA">Session</font>
Controller <font color="#AA5500">Session</font> will be created in src/controllers/<font color="#AA5500">session.controller.ts</font>

<font color="#00AA00">?</font> <b>What kind of controller would you like to generate?</b> <font color="#00AAAA">REST Controller with CRUD </font>
<font color="#00AAAA">functions</font>
<font color="#00AA00">?</font> <b>What is the name of the model to use with this CRUD repository?</b> <font color="#00AAAA">Session</font>
<font color="#00AA00">?</font> <b>What is the name of your CRUD repository?</b> <font color="#00AAAA">SessionRepository</font>
<font color="#00AA00">?</font> <b>What is the name of ID property?</b> <font color="#00AAAA">id</font>
<font color="#00AA00">?</font> <b>What is the type of your ID?</b> <font color="#00AAAA">string</font>
<font color="#00AA00">?</font> <b>Is the id omitted when creating a new instance?</b> <font color="#00AAAA">No</font>
<font color="#00AA00">?</font> <b>What is the base HTTP path name of the CRUD operations?</b> <font color="#00AAAA">/sessions</font>
<font color="#00AA00">   create</font> src/controllers/session.controller.ts
<font color="#00AA00">   update</font> src/controllers/index.ts

Controller <font color="#AA5500">Session</font> was created in src/controllers/
</pre>

#### Final Step.

    export PORT=3020 && npm start

**Comment by raymondfeng** [comment]
Thank you for reporting the issue with details. I’ll take a look tomorrow.
