### ISSUE TITLE
MongoDB connector behaving unexpectedly

### ISSUE THREAD

**Issue by diego92sigma6** [strongloop/loopback-next#4581]
Hello, I have a problem using Jest and Loopback 4, version 6.4.1

I've been trying to figure out why my code behaves unexpectedly
```typescript
it('Debería detectar cambios en los ultimos chequeos', async () => {
            await givenEmptyDatabase();
            

            //Generación de mocks
            let taskResult1 = givenTaskResultData();
            let taskResult2 = givenTaskResultData();
            taskResult2.taskName += '2';
            taskResult2.agentResponse.Name += '2';
            await sleep(2000);

            //Inserción de datos
            await taskRepo.create(taskResult1);
            await taskRepo.create(taskResult2);
            await sleep(500);

            let storedTasks = await taskRepo.find({});
            await sleep(500);
            expect(storedTasks .length).toBe(2); //SOMETIMES FAILS???

```

```givenEmptyDatabase()``` deletes every document from all collections in mongo.
Here is how it looks:
```typescript
export async function givenEmptyDatabase() {
    await new HeartbeatRepository(testdb).deleteAll();
    await new TaskResultRepository(testdb).deleteAll();
    await new MailSuscriptionRepository(testdb).deleteAll();
    await new SuscriptionConfirmationRepository(testdb).deleteAll();
}
```

What is weird is that:

*sometimes storedTasks.length == 2, sometimes == 0, sometimes == 4*

**The same thing happens along all my tests:** Simple finds() immediately preceded by simple creates() give different results. I try to make sure I clean the database manualy at the beginning of each test.
Any ideas on why this should be happening?

When I run on debug mode and run over each line step by step, it runs all good .____. (that's the reason why I added those sleep() calls after each DB manipulation statement)

Cheers

**Comment by dougal83** [comment]
Hola @diego92sigma6 

Not enough info to provide any meaningful help but you could take a look at an example test to see if it helps you writing the test.  Here is a suitably structured one:  https://github.com/strongloop/loopback-next/blob/master/packages/repository-tests/src/crud/create-retrieve.suite.ts

Note the usage of features such as `before` features, I think it's `beforeEach` with Jest.

Failing that you may need to provide a sample repo to reproduce your issue.

**Comment by diego92sigma6** [comment]
Thanks for the response, much appreciated! That example looks promising. I'll see if I can make better use of the testing features and will get back to you later!

**Comment by dougal83** [comment]
Closing.  Feel free to reopen if necessary.
