### ISSUE TITLE
vscode source code formatting vs. linting rules?

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-next#4584]
**Questions**

When saving a typescript file in vscode it's getting automatically formated by some linting rules:

https://github.com/strongloop/loopback-next/blob/34ee060fee8757a1a3ff675355d6b899953c21cf/.vscode/settings.json#L10-L13

When saving it automatically gets formated, e.g. some spaces after brackets are inserted:

![image](https://user-images.githubusercontent.com/13640166/74026272-1e4d4280-49a6-11ea-83ac-0e7b1b98eaa8.png)
![image](https://user-images.githubusercontent.com/13640166/74026296-2c9b5e80-49a6-11ea-8845-37b7d73289af.png)

When running `npm run lint:fix` theese spaces are removed again to conform the .prettierrc or .eslintrc.js linting rules.

**Is there any way to let vscode and prettier apply the same linting rules?** Is this the expected behavior or is there something wrong with my local setup?

Windows 10 Version 1909 Enterprise
vscode 1.41.1
vscode ESLint Plugin 2.0.15

**Comment by dougal83** [comment]
Add to settings:
`"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,`

**Comment by derdeka** [comment]
> Add to settings:
> `"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,`

This setting works for me. Should we add this to .vscode/settings.json ?

> The above works as standard.

Do you mean this would be the standard if i disable all plugins?

**Comment by dougal83** [comment]
> This setting works for me. Should we add this to .vscode/settings.json?

Wouldn't be a bad idea if you ask me.  Would you like to do the honours with PR?

> Do you mean this would be the standard if i disable all plugins?
I believe it would apply with vanilla VSCode install if you have a suitably recent version of Typescript in use.  Can't remember of the top of my head.

**Comment by bajtos** [comment]
FYI: here is our recommended VSCode setup: https://github.com/strongloop/loopback-next/blob/master/docs/site/VSCODE.md

**Comment by derdeka** [comment]
> FYI: here is our recommended VSCode setup: https://github.com/strongloop/loopback-next/blob/master/docs/site/VSCODE.md

Thanks @bajtos @dougal83, i forgot to install prettier plugin on my new laptop. Anyway, i think the .vscode setting might be helpful.
