### ISSUE TITLE
Loopback does not work in the last update

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#4586]
## Steps to reproduce

I've been since yesterday (when I update) with problems with Mssql. Some 'endpoints' work and others do not.

Thinking that it was a 'deadlock' in the database and rollback in Loopback Version and it was proven to work so it can be a problem that has been introduced in the new version

Loopback returns an error 500 with the following message:
> 500 RequestError: Timeout: Request failed to complete in 15000ms

The model has 5 relationships and a total of 25 properties (20 normal and 5 relationships). At the time of the request, only 2 relationships are requested

I think it may be related to the incidence #4160 Only this table at most has 1000 records (without the relationships)

Let's see if someone is having something similar or can give me some help with this

Thanks in advance

## Additional information

```
darwin x64 13.7.0

OLD VERSION (it works here)
├── @loopback/authentication@3.3.1
├── @loopback/boot@1.7.2
├── @loopback/context@2.0.0
├── @loopback/core@1.12.2
├── @loopback/extension-health@0.2.15
├── @loopback/openapi-v3@1.12.0
├── @loopback/repository@1.18.0
├── @loopback/rest@1.26.0
├── @loopback/rest-explorer@1.4.8
├── @loopback/security@0.1.11
├── @loopback/service-proxy@1.3.15
└── loopback-connector-mssql@3.7.0
npm ERR! extraneous: readable-stream@2.3.7 /Users/fran/Projects/.xxxxxx/xxxx-api/node_modules/loopback-connector-mssql/node_modules/readable-stream

LAST VERSION
├── @loopback/authentication@3.3.3
├── @loopback/boot@1.7.4
├── @loopback/context@2.1.1
├── @loopback/core@1.12.4
├── @loopback/extension-health@0.2.17
├── @loopback/openapi-v3@2.0.0
├── @loopback/repository@1.19.1
├── @loopback/rest@2.0.0
├── @loopback/rest-explorer@1.4.10
├── @loopback/security@0.1.13
├── @loopback/service-proxy@1.3.17
└── loopback-connector-mssql@3.7.0
npm ERR! extraneous: readable-stream@2.3.7 /Users/fran/Projects/.xxxxxx/xxxx-api/node_modules/loopback-connector-mssql/node_modules/readable-stream
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by frbuceta** [comment]
**Updates**
I just activated the debug with `loopback:connector:mssql` and I see that loopback retrieves all the information before giving the error

I am editing a video so you can see it like me (the data is not mine and I cannot reveal it)

**Comment by dhmlau** [comment]
@frbuceta, comparing the working versions vs non-working versions, i noticed there is a breaking change in `@loopback/rest`. Could you please try if that's the module causing the problem? Thanks. https://github.com/strongloop/loopback-next/blob/master/packages/rest/CHANGELOG.md

**Comment by frbuceta** [comment]
> @frbuceta, comparing the working versions vs non-working versions, i noticed there is a breaking change in `@loopback/rest`. Could you please try if that's the module causing the problem? Thanks. https://github.com/strongloop/loopback-next/blob/master/packages/rest/CHANGELOG.md

I will review but [here](https://github.com/strongloop/loopback-next/blob/master/packages/rest/CHANGELOG.md) it says that the change is only internal
>Existing api clients will continue to work after an upgrade.
>
>The signature of the 'param.query.object' decorator has not changed.
>
>There is no code changes required in the LoopBack APIs after upgrading to this fix. No method signatures or data structures are impacted.

**Comment by frbuceta** [comment]
Today is Sunday and there are no records in the database ... Being a breaking change should give the same error and not return an HTTP 200

**Comment by frbuceta** [comment]
I just detected where the error is going. I have a "belongsTo" relationship that does not work but making a diff of my code I see that there is no change that affects, also if I create the relationship with the CLI, It make it as is.

```
  @belongsTo(() => Order, undefined, {
    name: 'idPedido',
    required: true,
  })
  deliveryOrderId: number;
```

```
    this.deliveryOrder = this.createBelongsToAccessorFor(
      'deliveryOrder',
      orderRepositoryGetter,
    );
    this.registerInclusionResolver(
      'deliveryOrder',
      this.deliveryOrder.inclusionResolver,
    );
```

Something I have not seen?

**Comment by achrinza** [comment]
@frbuceta I'm guessing that the query in the this part of the log is what's failing:

```bash
2020-02-07T17:49:54.654Z loopback:connector:mssql SQL: SELECT [idPedido],[idEmpresa],[codigoVehiculo],[codigoConductor],[codigoTurno],[tipoDestino],[nombreDestino],[nodo],[codigoPostal],[viaje],[descarga],[cumplido],[horaPrevistaLlegada],[horaLlegadaDT],[horaSalidaDT],[posicion],[H1],[H2],[H3],[H4],[fueraHoraCliente],[fueraHoraProgramada],[estadoPedido] FROM [dbo].[TABLE] WHERE [codigoVehiculo] IN (@param1,@param2,@param3,@param4,@param5,@param6,@param7,@param8,@param9,@param10,@param11,@param12,@param13,@param14,@param15,@param16,@param17,@param18,@param19,@param20,@param21,@param22,@param23,@param24,@param25,@param26,@param27,@param28,@param29,@param30,@param31,@param32,@param33,@param34,@param35,@param36,@param37,@param38,@param39,@param40,@param41,@param42,@param43,@param44,@param45,@param46,@param47,@param48,@param49,@param50,@param51,@param52,@param53,@param54,@param55,@param56,@param57,@param58,@param59,@param60,@param61,@param62,@param63,@param64,@param65,@param66,@param67,@param68,@param69,@param70,@param71,@param72,@param73,@param74,@param75,@param76) ORDER BY [idPedido] Parameters: [REMOVED_BY_FRAN]
```

When the query is executed through SSMS (or similar a program), does it still timeout?

**Comment by frbuceta** [comment]
> @frbuceta I'm guessing that the query in the this part of the log is what's failing:
> 
> ```shell
> 2020-02-07T17:49:54.654Z loopback:connector:mssql SQL: SELECT [idPedido],[idEmpresa],[codigoVehiculo],[codigoConductor],[codigoTurno],[tipoDestino],[nombreDestino],[nodo],[codigoPostal],[viaje],[descarga],[cumplido],[horaPrevistaLlegada],[horaLlegadaDT],[horaSalidaDT],[posicion],[H1],[H2],[H3],[H4],[fueraHoraCliente],[fueraHoraProgramada],[estadoPedido] FROM [dbo].[TABLE] WHERE [codigoVehiculo] IN (@param1,@param2,@param3,@param4,@param5,@param6,@param7,@param8,@param9,@param10,@param11,@param12,@param13,@param14,@param15,@param16,@param17,@param18,@param19,@param20,@param21,@param22,@param23,@param24,@param25,@param26,@param27,@param28,@param29,@param30,@param31,@param32,@param33,@param34,@param35,@param36,@param37,@param38,@param39,@param40,@param41,@param42,@param43,@param44,@param45,@param46,@param47,@param48,@param49,@param50,@param51,@param52,@param53,@param54,@param55,@param56,@param57,@param58,@param59,@param60,@param61,@param62,@param63,@param64,@param65,@param66,@param67,@param68,@param69,@param70,@param71,@param72,@param73,@param74,@param75,@param76) ORDER BY [idPedido] Parameters: [REMOVED_BY_FRAN]
> ```
> 
> When the query is executed through SSMS (or similar a program), does it still timeout?

I am using Jetbrains Datagrip and it returns me perfectly

**Comment by frbuceta** [comment]
I just set requestTimeout to 0 and everything works. It takes but it works. Sorry for the inconvenience
