### ISSUE TITLE
Is possible to select the data from database and export that data using loopback 4?

### ISSUE THREAD

**Issue by AnanthGopal** [strongloop/loopback-next#4624]
i need to select and export data by using loopback 4. If it is possible, can you provide the sample link?

**Comment by achrinza** [comment]
Hi @AnanthGopal, could you clarify one "export data"? LB4 is flexible in that you can query using a repository function (such as `.find()`, `.findById()`, etc.) and then use the response of those functions as you wish.

**Comment by AnanthGopal** [comment]
Do i select data from the database and need to export data into CSV

**Comment by agnes512** [comment]
@AnanthGopal Not sure if I understand your question correctly. But one of the basic usages of LB4 is that you can access the db if you set up the datasource properly.

Take MySQL as an example, if you already have your tables defined, LB4 allows you to discover schemas from DBs (ref: https://loopback.io/doc/en/lb3/Discovering-models-from-relational-databases.html). And this can also be done by the CLI `lb4 discover --options`, see [the site](https://loopback.io/doc/en/lb4/Discovering-models.html). Once you've created a lb4 app and defined your datasource, you can discover models(table) from your database. Once you have those models discovered, you can create repositories and controllers to set up REST APIs to create/query data. LB4 maps the models to the tables of the database.

LoopBack has different connectors for databases. These connectors implement the data exchange logic to communicate with backend systems such as relational or NoSQL databases. You can check the [database connectors](https://loopback.io/doc/en/lb4/Database-connectors.html) page.

**Comment by AnanthGopal** [comment]
The below URL has the download option loopback  "https://stackoverflow.com/questions/29372470/downloading-file-from-strongloop-loopback/31389086#31389086", I need this same option in loopback 4

**Comment by achrinza** [comment]
@AnanthGopal Something similar can be accomplished via the controller:

```typescript
import {
  Filter,
  repository,
} from '@loopback/repository';
import {
  post,
  param,
  get,
  getFilterSchemaFor,
  Response,
  RestBindings,
} from '@loopback/rest';
import {File} from '../models';
import {FileRepository} from '../repositories';
import {inject} from '@loopback/core';

export class FileController {
  constructor(
    @repository(FileRepository)
    public fileRepository : FileRepository,
    @inject(RestBindings.Http.RESPONSE)
    public response : Response,
  ) {}
  
  @get('/files/{id}/download', {
    responses: {
      '200': {
        description: 'File instance file download',
        content: {
          'text/csv': {
            schema: {
              type: 'string',
              format: 'binary'
            },
          },
        },
      },
    },
  })
  async downloadById(
    @param.path.number('id') id: number,
    @param.query.object('filter', getFilterSchemaFor(File)) filter?: Filter<File>
  ): Promise<string> {
    this.response.set('Content-Disposition', 'attachment; filename="export.csv');
    const files = await this.fileRepository.find(filter);
    let csv = 'Id,Name';
    files.map(x => {
      csv += `\n${x.Id},${x.Value}`
    });
    return csv;
  }
}

```

^ This above code assumes a `File` model with 2 columns: `Id` and `Value`.

`Content-Disposition: attachment` should be enough to encourage a web browser to download the file.

I haven't tested this code, but this is what I remember from the top of my head.

**Comment by achrinza** [comment]
@AnanthGopal Something similar can be accomplished via the controller:

```typescript
import {Filter, repository} from '@loopback/repository';
import {
  post,
  param,
  get,
  getFilterSchemaFor,
  Response,
  RestBindings,
} from '@loopback/rest';
import {File} from '../models';
import {FileRepository} from '../repositories';
import {inject} from '@loopback/core';

export class FileController {
  constructor(
    @repository(FileRepository)
    public fileRepository: FileRepository,
    @inject(RestBindings.Http.RESPONSE)
    public response: Response,
  ) {}

  @get('/files/download', {
    responses: {
      '200': {
        description: 'File instance file download',
        content: {
          'text/csv': {
            schema: {
              type: 'string',
              format: 'binary',
            },
          },
        },
      },
    },
  })
  async downloadById(
    @param.query.object('filter', getFilterSchemaFor(File))
    filter?: Filter<File>,
  ): Promise<string> {
    this.response;
    const files = await this.fileRepository.find(filter);
    let csv = 'Id,Name';
    files.map(x => {
      csv += `\n${x.Id},${x.Value}`;
    });
    this.response.set(
      'Content-Disposition',
      'attachment; filename="export.csv',
    );

    return csv;
  }
}
```

^ This above code assumes a `File` model with 2 columns: `Id` and `Value`.

`Content-Disposition: attachment` is usually enough to encourage a web browser to download the file.

**Comment by achrinza** [comment]
Related: #2230

**Comment by achrinza** [comment]
Hi @AnanthGopal, has the above solution helped resolve the issue?

**Comment by AnanthGopal** [comment]
> Hi @AnanthGopal, has the above solution helped resolve the issue?

Thank you that code is working as expected.

Below code used to download static files from the server
`@get('/files/download', {
    responses: {
      '200': {
        description: 'File instance file download',
        content: {
          'text/csv': {
            schema: {
              type: 'string',
              format: 'binary',
            },
          },
        },
      },
    },
  })
  async download(@param.query.string('path') path: string = ""): Promise<any> {
    if (fs.existsSync(path)) {
      let testData = fs.readFileSync(path);
      this.fileResponse;
      let resposne = this.fileResponse.status(200)
        .contentType('application/csv')
        .attachment('test.csv')
        .send(testData);
      ///await this.queryExecutorRepository.query("delete from jobdetails where filepath='" + path + "'");
      fs.unlinkSync(path);
      return JSON.stringify(resposne);
    } else {
      let errors = [];
      errors.push({
        message: 'File Not Exist',
        name: 'UnknownError',
        actualError: 'File Not Exist'
      });
      return JSON.stringify({
        errors: errors
      });
    }`
