### ISSUE TITLE
API docs tables not properly generated

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#4631]
## Steps to reproduce

1. Go to lb4 API docs
2. View either one of these links:
  https://loopback.io/doc/en/lb4/apidocs.rest-crud.html#functions
  https://loopback.io/doc/en/lb4/apidocs.repository.html#functions

## Current Behavior

It seems that any tsdoc with a code block causes the table to not be created:

### Rest Crud
![image](https://user-images.githubusercontent.com/25147899/74336801-fdd41c80-4dd9-11ea-8ce6-ed4b70fb76ad.png)

### Repository
![image](https://user-images.githubusercontent.com/25147899/74336832-0e849280-4dda-11ea-97b6-39d7af3c8f83.png)

## Expected Behavior

The funtions table should be generated and/or the description should cut off before the next heading to remove the code blocks.

## Link to reproduction sandbox

N/A

## Additional information

Site last generated: Feb 10, 2020 

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
@achrinza Good catch. The tsdoc comments at https://github.com/strongloop/loopback-next/blob/master/packages/rest-crud/src/repository-builder.ts#L14 should be fixed as follows:

```ts
/**
 * Create (define) a repository class for the given model.
 *
 * @example
 *
 * ```ts
 * const ProductRepository = defineCrudRepositoryClass(Product);
 * ```
 *
 * @param modelCtor A model class, e.g. `Product`.
 */
```

We need to use `@example` to represent sample code.
