### ISSUE TITLE
Rest-explorer queries the wrong url

### ISSUE THREAD

**Issue by SephReed** [strongloop/loopback-next#4640]
I have an nginx server which serves the loopback api explorer.

It is currently fowarding all queries to `localhost:3000/path/to/query` instead of the actual public server it is on.

I can not find a way to specify that it should not use `localhost:3000`

**Comment by raymondfeng** [comment]
See https://loopback.io/doc/en/lb4/Self-hosted-rest-api-explorer.html#advanced-configuration-and-reverse-proxies for instructions.

**Comment by dhmlau** [comment]
@SephReed, did @raymondfeng's comment resolve your question?

**Comment by SephReed** [comment]
I got it eventually.  The setup I was working with had an api host overwrite somewhere unexpected.
