### ISSUE TITLE
Loopback 4 filters not working with multiple relations

### ISSUE THREAD

**Issue by pratikjaiswal15** [strongloop/loopback-next#4644]
I am using multiple relations in loopback 4. I have 4 models.

User has many carts accessible on url `users/user_id/carts`
cart has many products. Relation named `product`
Product has many stocks and product-prices named `stocks` and `productPrices` respectively.
Here is a controller at url `users/user_id/carts/prices` which performs multiple relations as shown below.

```
get('/users/{id}/carts/prices', {
        responses: {
          '200': {
            description: 'Array of Cart\'s belonging to Users',
            content: {
              'application/json': {
                schema: { type: 'array', items: getModelSchemaRef(Cart) },
              },
            },
          },
        },
      })
      async Multiple_relation(
        @param.path.number('id') id: number,
        @param.query.object('filter') filter?: Filter<Cart>,
      ): Promise<Cart[]> {
        return this.usersRepository.carts(id).find({
          include: [{
            relation: 'product',
            scope: {
              include: [{ relation: 'productPrices' }, { relation: 'stocks' }],
            },

          },
          ],
        }, filter);
      }
```
But I am unable to perform a filter on this url like

`users/29/carts/prices?filter[where][cart_id]=29`

The above query doesn't filter records where cart_id is 29. What is going wrong?

Thank you in advance

**Comment by pratikjaiswal15** [comment]
Any update sir @agnes512

**Comment by agnes512** [comment]
@pratikjaiswal15 From your description, I guess you'd like to combine the `where` clause with the `include` clause. But notice that for the `find()` method, from the API docs, it takes 2 params: 
```
find(
    filter?: Filter<T>,
    options?: Options,
  ): Promise<>{..}
```

That's why your filter `filter[where][cart_id]=29` gets discarded, and
```
return this.usersRepository.carts(id).find({
          include: [{
            relation: 'product',
            scope: {
              include: [{ relation: 'productPrices' }, { relation: 'stocks' }],
            },

          },
          ],
        }, filter);
```
would only return **_all_** products with their related `Stock` and `ProductPrice`.

Basically, you need to combine these 2 filter. Here are two ways to do so:: 
1. use `filterBuilder` **( a formal, safer way)**:
add: `import filterBuilder from '@loopback/repository';`
modify your endpoint:
```
get('/users/{id}/carts/prices', {
...
      })
      async Multiple_relation(
        @param.path.number('id') id: number,
        @param.query.object('filter') filter?: Filter<Cart>,
      ): Promise<Cart[]> {
         // define the where clause here. You might want to check the existence of filter.where
         const where = filter!.where as Where<Cart>; 
        // if your filter might contain other clauses, you need to define and add them to the filterBuilder respectively 

         const filterBuilder = new FilterBuilder();
         const newFilter = filterBuilder
          .include(
             {relation: 'product',  scope: { include: [{ relation: 'productPrices' }, { relation: 'stocks' }]}}
          )
         .where(where);  // the where clause you defined above
         .build();

    return this.usersRepository.carts(id).find(newFilter);
}
```

2. Just combine these two filters **if you make sure** that you would only simply have the `where` clause in your query:
```
get('/users/{id}/carts/prices', {
...
      })
      async Multiple_relation(
        @param.path.number('id') id: number,
        @param.query.object('filter') filter?: Filter<Cart>,
      ): Promise<Cart[]> {
      // combine 2 filters
      const myFilter = {...filter, include: [{
        relation: 'product',
        scope: {
          include: [{ relation: 'productPrices' }, { relation: 'stocks' }],
        },
       }],
     };
  return this.usersRepository.carts(id).find(myFilter);
}

**Comment by pratikjaiswal15** [comment]
Okay, thank you

**Comment by achrinza** [comment]
@agnes512 AFAIK `filterBuilder` this isn't documented. Should this go under `Working with Data`?

See #2577

**Comment by agnes512** [comment]
@achrinza Do you mean the page that we are having for LB4?

**Comment by achrinza** [comment]
@agnes512 yup

________________________________

**Comment by agnes512** [comment]
That's a good suggestion! `filterBuilder` would be helpful to simplifies the query syntax for use cases like this.

**Comment by agnes512** [comment]
I am closing the issue. Feel free to reopen it if you have any questions, thanks!
