### ISSUE TITLE
Case insensitive routing

### ISSUE THREAD

**Issue by dkrantsberg** [strongloop/loopback-next#4648]
While porting a legacy API to LoopBack 4 I've noticed that LoopBack routing is case sensitive.
Is there a way to make it case insensitive so that it doesn't throw 404 errors if route casing is different (`/api/userprofile` or `/api/userProfile`)?

Case-insensitive routing is default in Express.js.  I was expecting LB4 to behave the same way.

**Comment by achrinza** [comment]
@dkrantsberg AFAIK, lb4 only uses Express.js for its middlewares, and uses its own routing engine. (see [Circling back to Express with a twist](https://loopback.io/doc/en/lb4/Crafting-LoopBack-4.html#circling-back-to-express-with-a-twist).

lb4 does have the concept of Sequences, to which you can "normalize" the incoming route path before passing it into `findRoute()` (see [Invoke Operations using Routes](https://loopback.io/doc/en/lb4/Routes.html#invoking-operations-using-routes)).

You can also completely replace the router for more flexibility (see [Customize the REST router](https://loopback.io/doc/en/lb4/Routing-requests.html#customize-the-rest-router))

**Comment by dkrantsberg** [comment]
Yes, this is what I ended up doing. Thanks, @achrinza.
