### ISSUE TITLE
wiki: Rename sequence-level context to request-level

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#465]
Start here: https://github.com/strongloop/loopback-next/wiki/Context

> LoopBack supports two types of context: Application-level and Sequence-level

Review other wiki pages for a possible usage of Sequence-level context too.

**Comment by dhmlau** [comment]
@bajtos, I'm doing a search on `sequence` and `sequence level` in this repo.  The only matching results in the wiki is in https://github.com/strongloop/loopback-next/wiki/Context (2 occurrences).

I did the renaming because it's a simple change.  
Perhaps we can close it?

**Comment by bajtos** [comment]
I searched for `level` just to be sure, and did not find any more occurrences. Thank you for making the change, I am closing this issue as done.
