### ISSUE TITLE
core: expose "this.ctx" in DefaultSequence

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#466]
See https://github.com/strongloop/loopback-next/wiki/Context#sequence-level-context-request for an example usage:

```ts
class MySequence extends Sequence() {
  run(request, response) { // we provide these value for convenience (taken from the Context)
    const req = this.ctx.getSync('http.request'); // but it is still available in the sequence/request context
    this.send(`hello ${req.params.name}`);
  }
}
```

**Comment by bajtos** [comment]
I think we should create a new binding allowing classes to get the current request context injected, e.g. `http.request.context`. Then we should change `DefaultSequence` constructor to inject this current context into `ctx` property.

**Comment by virkt25** [comment]
connect to #496
