### ISSUE TITLE
wiki: rename Sequence to DefaultSequence

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#467]
At the moment, wiki pages contains reference to `Sequence` class. This does not exist in the current implementation, we have two different entities instead:

 - `SequenceHandler` defines the interface required by our REST layer. This allows applications to build custom sequences not inheriting from our default implementation.
 - `DefaultSequence` provides a default implementation that uses `findRoute`, `invoke`, etc. to handle incoming requests.

We need to review all wiki pages and replace `Sequence` with `DefaultSequence` or `SequenceHandler` as appropriate.

**Comment by ssh24** [comment]
@bajtos Updated the wiki to fix examples that references `Sequence`:
- https://github.com/strongloop/loopback-next/wiki/Sequence
- https://github.com/strongloop/loopback-next/wiki/Routing
- https://github.com/strongloop/loopback-next/wiki/Context
- https://github.com/strongloop/loopback-next/wiki/Sequence-(Advanced)

Those are the only pages where I found `Sequence` relevant. Please let me know if anything else needs to be updated.

**Comment by bajtos** [comment]
@ssh24 thanks.

https://github.com/strongloop/loopback-next/wiki/Sequence
> `class MySequence extends SequenceHandler`

`SequenceHandler` is an interface (which is used with `implements` keyword, not `extends`). However, the code example needs properties from `DefaultSequence`. Same comment applies to most other code snippets on this page. I fixed them all.

**Comment by bajtos** [comment]
I reviewed and fixed other pages that you have referred to, @ssh24.  I am closing this issue as done.
