### ISSUE TITLE
wiki: create "Dependency Injection" page

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#468]
The wiki page [Context](https://github.com/strongloop/loopback-next/wiki/Context) refers to a page that does not exist "Dependency Injection":

> LoopBack can help "manage" your resources automatically (through Dependency Injection and decorators).

We need to write  https://github.com/strongloop/loopback-next/wiki/Dependency-Injection.

**Comment by dhmlau** [comment]
@bajtos , there's a Dependency Injection section in the Context wiki page: https://github.com/strongloop/loopback-next/wiki/Context#dependency-injection.
What else should we cover in the new wiki page?  Trying to define the acceptance criteria.
Some might not be applicable.  Please edit accordingly.

## Acceptance Criteria
- [ ] Wiki page should include the following topics:
    - [ ] what is dependency injection
    - [ ] why / when do we need to use?
    - [ ] what is the benefit of using it
    - [ ] how to use -- examples? 
- [ ] Clean up the reference in [Context page](https://github.com/strongloop/loopback-next/wiki/Context#dependency-injection) if applicable
- [ ] Clean up reference on DI in [Testing Your application page](https://github.com/strongloop/loopback-next/wiki/Testing-Your-Application-(Advanced))

**Comment by bajtos** [comment]
@dhmlau I think your list is a good one! Could you please check with @ritch? He may have ideas on what more should be included.

**Comment by bajtos** [comment]
@Setogit @virkt25 @b-admike could you please review the text in https://github.com/strongloop/loopback-next/wiki/Dependency-Injection and let me know your thoughts? As a reader of that wiki page, do you have any additional questions related to DI that you would the wiki page to answer for you?

**Comment by virkt25** [comment]
- Fixed a type `to` -> `two`.
- Seems simple enough and easy to follow with references to additional resources however, if I'm reading this page (out of the order suggested in the left nav) then I'm left wondering where the injected values come from or how they are set. (My suggestion would be to add a brief section / link to `Context` wiki page just like the `Context` wiki page talks about dependency injection briefly and links to this page for more information). 

Unrelated to wiki content but just a note from my first experience with DI.
- Maybe this might just be me being new to TS, but perhaps a line explaining that `@inject('binding.key') key` sets the value to the variable (key) specified after it ... when I was first looking at an example I had completely overlooked the variable after @inject. So for the previous inject I wondered where we would get the `key` variable from for `this.key = key` Took me a moment to realize it was specified right after the @inject(). (This might just be me though).

**Comment by bajtos** [comment]
@virkt25 thank you, this is very valuable feedback! I added more content to the page to address your first point, and changed formatting of the code examples to hopefully avoid issue pointed out by your second item. 

Could you PTAL again? 

The diff: https://github.com/strongloop/loopback-next/wiki/Dependency-Injection/_compare/cc31d292ef1cca22668c6a81e6691426c75f8237...19197230a15695e13b22b80299402604eee167e5

**Comment by virkt25** [comment]
Much clearer to follow along! Really like the explanations for binding a class vs provider vs value. 

Not sure as a developer if I prefer seeing the variable on the next line after `@inject('key')` even though it was done because of my idea. Not sure if there is an easy way out apart from just not having someone skip the variable after. Or maybe a comment saying it injects the value into the variable stated after the decorator? 

Otherwise LGTM 👍

**Comment by bajtos** [comment]
> Not sure as a developer if I prefer seeing the variable on the next line after @inject('key') even though it was done because of my idea. Not sure if there is an easy way out apart from just not having someone skip the variable after. Or maybe a comment saying it injects the value into the variable stated after the decorator?

I don't have a strong opinion on this. Feel free to make these changes yourself.

> Otherwise LGTM

**Comment by bajtos** [comment]
> Otherwise LGTM

Great, I am closing this issue as done.
