### ISSUE TITLE
core: x-controller-name

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#470]
In https://github.com/strongloop/loopback-next/wiki/Thinking-in-LoopBack, we are using `x-controller-name`, which is not supported yet. Strangely enough, we allow `x-controller `extension to provide a controller name

 - [x] rename `x-controller` to `x-controller-name` in the implementation
 - [x] fix all wiki pages using `x-controller` to use `x-controller-name` instead

**Comment by virkt25** [comment]
Updated the wiki. Updated the following: 
[Controllers](https://github.com/strongloop/loopback-next/wiki/Controllers)
