### ISSUE TITLE
wiki: Use deep-assign for merging OpenAPI spec objects

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#471]
Fix examples showing how to build a spec by merging multiple partial spec objects to correctly merge deep properties like `definition.properties` or `spec.paths`.

For example, in  https://github.com/strongloop/loopback-next/wiki/Thinking-in-LoopBack:

 - The schema building example is using `Object.assign` to merge definitions, assuming it will do a deep merge. That's not true and as a result, properties from `BaseSchema` will be discarded from `ProductBaseSchema`. 

 -  Similarly, `Object.assign(spec, DealResource);` discards any paths already defined in `spec`. I think we need to introduce and use some sort of a deep-assign solution (like [deep-assign](https://www.npmjs.com/package/deep-assign) module) instead.

**Comment by kjdelisle** [comment]
@bajtos I remember we spoke about potentially using `_.cloneDeep` instead, but I can't remember if this task called for recursive deep copies, or if a recursive shallow copy (like the one from deepAssign) is sufficient.

**Comment by bajtos** [comment]
Well, `_.cloneDeep` is not going to work, because we need to merge two (or more) objects. Having said that, I cannot tell whether we need a recursive deep or a recursive shallow algorithm.

**Comment by b-admike** [comment]
I think the `deep-assign` module achieves what we are looking for:
>The schema building example is using Object.assign to merge definitions, assuming it will do a deep merge. That's not true and as a result, properties from BaseSchema will be discarded from ProductBaseSchema.

```javascript
const ProductBaseSchema = deepAssign(BaseSchema, {
...   properties: {
.....     price: {
.......       type: "number",
.......       minimum: 0,
.......       exclusiveMinimum: true
.......     }
.....   }
... });
undefined
> ProductBaseSchema
{ properties:
   { id:
      { description: 'The unique identifier for a product',
        type: 'integer' },
     name: { type: 'string' },
     slug: { type: 'string' },
     price: { type: 'number', minimum: 0, exclusiveMinimum: true } } }
```
 >Similarly, Object.assign(spec, DealResource); discards any paths already defined in spec. I think we need to introduce and use some sort of a deep-assign solution (like deep-assign module) instead.
https://gist.github.com/b-admike/f490eeb5543d80154eafcc823dc3edd6

PTAL: https://github.com/strongloop/loopback-next/wiki/Thinking-in-LoopBack/_compare/1ce08c8a153c000754ac6c7d4c2eed98a2683364...b612119105eb273e9715149e47b4fb6c473d83c4

**Comment by bajtos** [comment]
> `npm i deep-assign`

Please use the full command name (`install`) and also add `--save` flag, as that's what most people need to do.

> We could use lodash's merge function like `_.merge(spec, DealResource)`, which would mutate the spec object, instead of doing `spec = deepAssign(spec, DealResource)`.

I think the usual approach is to provide `{}` as the first argument of `merge` in order to avoid mutation of the spec object. I think we need to do the same for `deepAssign`.

```js
spec = _.merge({}, spec, DealResource);
```

I personally don't mind whether we use `deep-assign` or `loadash/merge`. Please check with @kjdelisle, he has a good technical criteria for deciding which one to use.

**Comment by b-admike** [comment]
@bajtos I have talked to @kjdelisle about this and we've concluded on using `deep-assign` since it is lightweight and built for our purpose. I have made your proposed [changes](https://github.com/strongloop/loopback-next/wiki/Thinking-in-LoopBack/_compare/b612119105eb273e9715149e47b4fb6c473d83c4...c254e0e8085a8b78f975a115b405b109c5bd6c44) as well.

**Comment by bajtos** [comment]
LGTM :
