### ISSUE TITLE
Parsing OpenAPI callbackObject declared in controllers

### ISSUE THREAD

**Issue by getlarge** [strongloop/loopback-next#4712]
## Suggestion

In a Loopback 4 controller, i described an operation and also included CallbackObject. I was hoping that the `openapi.json` generated would contain the correct translation, but the schema declared in requestBody, responses ... are always empty (see below).

```javascript
    "callbacks": {
          "deviceCallbacks": {
            "{$request.body#/ownerId}/Devices/{$method}/+": {
              "post": {
                "operationId": "devicesEventListener",
                "description": "Listen all devices events owned by ownerId",
                "requestBody": {
                  "required": true,
                  "content": {
                    "application/json": {
                      "schema": {}
                    }
                  }
                },
                "responses": {
                  "200": {
                    "description": "Device instance",
                    "content": {
                      "application/json": {
                        "schema": {}
                      }
                    }
                  }
                }
              }
            }
          }
        }
```

So i'm wondering to which package it is related to ? ( openapi-spec-builder, openapi-v3, rest ?)
And where the changes could be made or if i'm doing something wrong.

## Use Cases

I made a pull request in openapi-to-graphql, to accomplish the reverse operation and thought that the logic could be reused in the related Loopback package.
This PR allowed to use the CallbackObject to automatically create Subscription fields in GraphQL Schema.
So the purpose would be to assign subscription point directly from Loopback controllers via the callbacks.

## Examples

Here is the operation in the controller:

```javascript
@post(`/${devicesApiEndPoint}`, {
    operationId: 'createDevice',
    security,
    requestBody: {
      description: 'Device instance to create',
      required: true,
      content: {
        'application/json': {
          schema: {
            'x-ts-type': Device,
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'Device instance',
        content: {'application/json': {schema: {'x-ts-type': Device}}},
      },
      default: defaultResponse,
    },
    callbacks: {
      deviceCallbacks,
    },
  })
```

Here the `deviceCallbacks` :

```javascript
export const deviceCallbacks = {
  '{$request.body#/ownerId}/Devices/{$method}/+': {
    post: {
      operationId: 'devicesEventListener',
      description: 'Listen all devices events owned by ownerId',
      requestBody: {
        required: true,
        content: {'application/json': {schema: {'x-ts-type': DeviceTopic}}},
      },
      responses: {
        '200': {
          description: 'Device instance',
          content: {'application/json': {schema: {'x-ts-type': Device}}},
        },
      },
    },
  },
};
```

**Comment by getlarge** [comment]
It seems that content declared in Callback Items can be resolved when using `getModelSchemaRef(Model)` method from openapi-v3 instead of 'x-ts-type'.

**Comment by dougal83** [comment]
Thank you for taking the time to follow up with solution!

I think the `x-ts-type` is for basic TypeScript types rather than models.  Glad you are sorted!
