### ISSUE TITLE
defining a nested array model property using @property.array decorator crashes the app

### ISSUE THREAD

**Issue by alyhegazy** [strongloop/loopback-next#4754]
## Steps to reproduce
define a nested array model property like the following

```
import {Model, property} from '@loopback/repository';

class testModel extends Model {
  @property.array(Array)
  nestedArr: Array<Array<string>>;
}
```

## Current Behavior
The app crashes with the error `Cannot start the application. Error: "items" property must be present if "type" is an array`

## Expected Behavior
The nested array property should be defined without problems. Would be nice to also allow defining the type of the nested array for example `@property.array(Array<string>)`.

## Additional information
darwin x64 10.19.0
├── @loopback/authentication@3.3.1
├── @loopback/authorization@0.4.9
├── @loopback/boot@1.7.2
├── @loopback/context@2.0.0
├── @loopback/core@1.12.2
├── @loopback/openapi-v3@1.12.0
├── @loopback/rest@1.26.0
└── @loopback/rest-explorer@1.4.8

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

## Acceptance Criteria
- [ ] Update documentation to clarify that @property.array() decorator does not support nested arrays in model properties ( add reasons why, Ts type issues)
- [ ] Fix validation code in https://github.com/strongloop/loopback-next/blob/master/packages/repository-json-schema/src/build-schema.ts#L221 to return appropriate error when seeing a nested array.
- [ ] Add example to achieve nested arrays with json schema directly using @param() decorator

**Comment by deepakrkris** [comment]
@alyhegazy ,  are you extending from another model, is `Model` a base class you have defined ?
 
can you try :

```
import {Entity, model, property} from '@loopback/repository';

@model()
class testModel extends Entity {
  @property.array(Array)
  nestedArr: Array<Array<string>>;
}
```
This seems to work for me.

**Comment by deepakrkris** [comment]
@alyhegazy please ignore my previous comment, I get the same error.

**Comment by alyhegazy** [comment]
@deepakrkris the problem is in the `property.array()` decorator. If you replace `@property.array(Array)` with `@property.array(Object)` for example it works fine.

**Comment by deepakrkris** [comment]
@alyhegazy we are not supporting nested arrays 

https://github.com/strongloop/loopback-next/blob/master/packages/repository-json-schema/src/build-schema.ts#L221 . 

But this is not well documented as well as the validation code above misses returning an appropriate error.

**Comment by alyhegazy** [comment]
@deepakrkris should I create a feature request for supporting it? As it's very likely to have nested arrays in a schema and it seems there's no way around it. What do you think?

**Comment by deepakrkris** [comment]
@alyhegazy , looks like we can achieve supporting nested arrays using json schema spec directly in @param() decorator . I am going to work on an example for this. If you are able to contribute with an example faster, that would be great as well.

**Comment by bajtos** [comment]
@deepakrkris I checked the acceptance criteria you proposed, they look great to me!

> - [ ] Update documentation to clarify that @property.array() decorator does not support nested arrays in model properties
> - [ ] Fix validation code in https://github.com/strongloop/loopback-next/blob/master/packages/repository-json-schema/src/build-schema.ts#L221 to return appropriate error when seeing a nested array.
> - [ ] Add example to achieve nested arrays with json schema directly using @param() decorator

I like that you are including a task to improve the error message reported by LoopBack to make the problem easier to understand & troubleshoot for our users :+1:
