### ISSUE TITLE
Support RequestObject injection on API methods

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#476]
See original comment here: https://github.com/strongloop/loopback-next/pull/462#issuecomment-318103253

## Proposal
Leverage support for per-parameter definitions, as seen on the `@param` decorator to support automatic injection of an entire `RequestObject` instead.

This would not be a replacement for the `@param` approach, but a complementary extension to simplify API handler method arguments.

```ts
const offsetSpec: ParameterObject = {
         name: 'offsetSpec',
         type: 'number',
         in: 'query',
};

const pageSizeSpec: ParameterObject = {
         name: 'pageSize',
         type: 'number',
         in: 'query',
};

const List: RequestObject = {
   parameters: [
     offsetSpec,
     pageSizeSpec,
   ]
};

class MyController {
  @operation('get', '/', {responses})
  @request(List)
  list(list: List) {
    // Auto-populate a List (RequestObject) instance based on provided values
  }
}
```
## Requirements
- A `@request` (or some other named) decorator that performs the association
   - This decorator should iterate through the listed parameters of the provided `RequestObject`,
  and inject the provided values in the request with the matching `ParameterObject` definition
  - Constructors of any objects extending `RequestObject` would need to be parameterless, or consist exclusively of optional parameters. Constructor-level validation would not be possible, since this would be building the empty object, and then injecting the matching parameters. **Documentation to this effect should be considered a requirement!**
  - Parameters used in this way would have to be of type `ParameterObject`; this ensures compatibility with the OpenAPI spec.

**Comment by bajtos** [comment]
@kjdelisle is this still relevant? Do you think this is something needed for Core-GA release? Otherwise I am proposing to close this issue with `help wanted` label, because I think we won't have bandwidth to work on this feature in the next 6-9 months.

**Comment by kjdelisle** [comment]
I'm okay with bumping it from MVP.

**Comment by jannyHou** [comment]
would this story be combined with https://github.com/strongloop/loopback-next/issues/436?
