### ISSUE TITLE
Blog post for beta announcement

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#477]
In discussion with @ritch , we probably need one or more blog posts on LB Next Core beta as marketing purpose.

**Comment by dhmlau** [comment]
@Setogit, since you're planning with the dev evangelist team on a series of blog posts, I'm thinking that it might be helpful to use this ticket to capture the list of topics to be covered (+purpose of the posts) after discussing with @raymondfeng @ritch and @emckean.  Then we can work out who can write the posts.

**Comment by bajtos** [comment]
Let's write a single high-level announcement blog post only, and refer to wikis/tutorials on GitHub instead of writing a series of blog posts (that will eventually get outdated).

**Comment by dhmlau** [comment]
@Setogit has proposed the following in the past: 
- `Journey of a new LB Next Developer` 
  - target at existing LB developer want to get on LB Next
  - https://github.com/strongloop/loopback-next/blob/wip-logging/packages/logger/README.md
- `LB Next Design Notes from Chief Architect`
  - https://github.com/strongloop/loopback-next/wiki/Crafting-LoopBack-Next
  - Owner: @raymondfeng 

As a high level (and as the first post), I think we need a blog post telling why LB Next is better than LB 3 and competitive advantage of using LB Next, so as to get people to get onto LB Next.  

@bajtos , what do you think?

**Comment by bajtos** [comment]
@dhmlau your proposal sounds good to me 👍

**Comment by dhmlau** [comment]
roadmap : https://github.com/strongloop/loopback-next/wiki/Upcoming-Releases

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/strongloop.com/pull/100
