### ISSUE TITLE
@loopback/rest: path-to-regexp too far ahead?

### ISSUE THREAD

**Issue by hlian** [strongloop/loopback-next#4809]
There's

```
    "express": "^4.17.1",
[snip]
    "path-to-regexp": "^6.1.0",
```

in package.json, but [express requires path-to-regexp to be on the 0.x major version](https://github.com/expressjs/express/issues/4171#issuecomment-586653090). I think this puts users of LB4 in an awkward position of having to choose between one or the other?

Also, as of the most recent release, TypeScript won't compile if `path-to-regexp@0.1.7` is the chosen version:

```
../../node_modules/@loopback/authentication/node_modules/@loopback/rest/dist/router/regexp-router.d.ts:4:21 - error TS7016: Could not find a declaration file for module 'path-to-regexp'. '/Users/h/w/chief/node_modules/path-to-regexp/index.js' implicitly has an 'any' type.
  Try `npm install @types/path-to-regexp` if it exists or add a new declaration (.d.ts) file containing `declare module 'path-to-regexp';`

4 import { Key } from 'path-to-regexp';
                      ~~~~~~~~~~~~~~~~

[2:10:19 PM] Found 1 error. Watching for file changes.
```

because path-to-regexp now has types in its repository. _But_ express doesn't work if `path-to-regexp@6.1.0` is the chosen version:

```
Cannot start the application. TypeError: pathRegexp is not a function
    at new Layer (/Users/h/w/node_modules/express/lib/router/layer.js:45:17)
    at Function.use (/Users/h/w/node_modules/express/lib/router/index.js:464:17)
    at ExternalExpressRoutes.registerAssets (/Users/h/w/node_modules/@loopback/rest/src/router/external-express-routes.ts:52:24)
    at RestServer.static (/Users/h/w/node_modules/@loopback/rest/src/rest.server.ts:759:26)
    at App.static (/Users/h/w/node_modules/@loopback/rest/src/rest.application.ts:113:21)
```

**Comment by emonddr** [comment]
@hlian , please provide a small application that reproduces the issue you are seeing. Thank you. :)

**Comment by emonddr** [comment]
@deepakrkris , PTAL. Thx :)

**Comment by raymondfeng** [comment]
@hlian Node.js allows different versions of the same module as dependencies. For example, `npm ls path-to-regexp` gives me the following information:

```
x1@1.0.0 /private/tmp/x3
├─┬ @loopback/rest@3.0.0
│ ├─┬ express@4.17.1
│ │ └── path-to-regexp@0.1.7 
│ └── path-to-regexp@6.1.0 
└─┬ @loopback/testlab@2.0.0
  └─┬ sinon@9.0.0
    └─┬ nise@4.0.3
      └── path-to-regexp@1.8.0 
```

Please note `6.1.0` is a transitive dependency for `@loopback/rest` and it should not have impact on your application.

**Comment by deepakrkris** [comment]
@hlian please provide a sample app or code sandbox to recreate your issue

**Comment by hlian** [comment]
ah, gotcha!
