### ISSUE TITLE
the example-file-upload is giving internal server error after submitting the file

### ISSUE THREAD

**Issue by dip-sinha** [strongloop/loopback-next#4834]
## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dip-sinha** [comment]
Unhandled error in POST /file-upload: 500 Error: unknown format "binary" is used in schema at path "#/properties/file"
this is the error I am getting in console

**Comment by achrinza** [comment]
@dip-sinha, please publish a GitHub repo sandbox so that we can examine the code. Otherwise it may be difficult for us to pinpoint the issue.

**Comment by raymondfeng** [comment]
@dip-sinha The example depends on https://github.com/strongloop/loopback-next/pull/4808, which is merged into master but not published to npm yet.

There are two options to try this example now:

1. Check out `strongloop/loopback-next` github repo and run `npm i` under `loopback-next` to set up dependencies for `examples/file-upload`.

2. In the example `application.ts`, add the following code to the constructor:

```ts
this.bind(RestBindings.REQUEST_BODY_PARSER_OPTIONS)
  .to({validation: {unknownFormats: ['binary']}});
```
