### ISSUE TITLE
Migration Guide: Request-response cycle

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#4836]
Document the request-response cycle differences in LB3 and LB4.  Created out of https://github.com/strongloop/loopback-next/issues/3935.

https://github.com/strongloop/loopback-next/issues/1833 should be done before doing the task.

## Acceptance Criteria

After 1833 is done, 
- [ ] Go through the request response cycle in LB4 and LB3 ( with diagrams)
- [ ] Explain the differences

**Comment by dhmlau** [comment]
In yesterday's estimation, @raymondfeng suggested the following:
- start with "Document the LoopBack 4 request-response cycle" #1833
- see if there's any LB3 documentation related to req/res cycle
- compare the two

**Comment by agnes512** [comment]
The built-in data parsing part of #4839 should be included in this story

**Comment by dhmlau** [comment]
Reopening this issue because PR #4914 only covers the LB4 portion.

**Comment by hacksparrow** [comment]
https://github.com/strongloop/loopback-next/issues/4837 (custom validation) story will also be included in this story.

**Comment by dhmlau** [comment]
Closing as done.
