### ISSUE TITLE
Migration Guide: Custom validation

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#4837]
Document the points of data access / validation and their differences in LB3 and LB4.  Created out of https://github.com/strongloop/loopback-next/issues/3935.

**Acceptance Criteria**

- [ ] Document the points where data (request / transaction) can be accessed and validated in LB3
- [ ] Document the points where data (request / transaction) can be accessed and validated in LB4

**Comment by agnes512** [comment]
Custom validation at different layers.

Better to have a lb4 documentation to talk about examples / use cases of custom validation at different layers first

**Comment by agnes512** [comment]
@dhmlau might have an article to talk about the use cases of validation.

**Comment by agnes512** [comment]
The validation part of #4839 should be included in this story

**Comment by dhmlau** [comment]
See PR https://github.com/strongloop/loopback-next/pull/4874

**Comment by hacksparrow** [comment]
Will be included in https://github.com/strongloop/loopback-next/issues/4836.
