### ISSUE TITLE
Migration Guide: Boot up

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#4838]
Document the differences in the boot up process in LB3 and LB4.  Created out of https://github.com/strongloop/loopback-next/issues/3935.

**Acceptance Criteria**

- [ ] Document the difference the boot up process between LB4 & LB3.

Related https://github.com/strongloop/loopback-next/issues/3384.

**Comment by agnes512** [comment]
https://loopback.io/doc/en/lb4/Life-cycle.html and https://loopback.io/doc/en/lb4/Booting-an-Application.html might help.

**Comment by hacksparrow** [comment]
Closed via https://github.com/strongloop/loopback-next/pull/5178
