### ISSUE TITLE
Migration Guide: In-built data parsing and validation

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#4839]
Document the in-built data parsing and validation differences in LB3 and LB4. Created out of https://github.com/strongloop/loopback-next/issues/3935.

**Acceptance Criteria**

- [ ] Document in-built data parsing and validation in LB3
- [ ] Document in-built data parsing and validation in LB4

**Comment by agnes512** [comment]
After discussion with the team: the in-built data parsing part should be included in #4836 and the validation part should be included in https://github.com/strongloop/loopback-next/issues/4837. Closing as redundant.
