### ISSUE TITLE
[EPIC] Add "Running and Debugging app" page

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#4844]
## Suggestion

In LB3 docs, there's [Running and debugging apps page](https://loopback.io/doc/en/lb3/Running-and-debugging-apps.html). A similar version for LB4 would be useful. 

### Acceptance Criteria
- [x] Running and debugging apps
   - [x] setting debug strings
       - The connector ones would be the same. For others, not every debug strings would be the same. e.g. strong-remoting
   - [x] error handling
      - instead of using strong-error-handler, we need to document how to configure http response for errors and how to report error from controller. 
      - Note: there are other error handling pages in LB4, we might need to see where is the best place to have this info.

**Comment by agnes512** [comment]
closing as done
