### ISSUE TITLE
[Docs] Add debug string information

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#4845]
Originated from: https://github.com/strongloop/loopback-next/issues/4844

In LB3 docs, there's Running and debugging apps page. A similar version for LB4 would be useful.

### Acceptance Criteria
- [x] Add Running and debugging apps
- [x] Add `setting debug strings` as a child page.
   - Note: The connector ones would be the same. For others, not every debug strings would be the same. e.g. strong-remoting

**Comment by agnes512** [comment]
Closing as done
