### ISSUE TITLE
[Docs] Add "error handling" page

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#4846]
Originated from: https://github.com/strongloop/loopback-next/issues/4844

In LB3 docs, there's Running and debugging apps page. A similar version for LB4 would be useful.

### Acceptance Criteria
- [ ] Review and clean up any error handling related content we have in LB4 docs
- [ ] Document how to configure http response for errors and how to report error from controller. 
    -  Use [strong-error-handler page](https://loopback.io/doc/en/lb3/Using-strong-error-handler.html) as a reference
    - the initial idea is to create a child page under `Running and debugging apps` page in LB4.

Related: https://github.com/strongloop/loopback-next/issues/4845

**Comment by agnes512** [comment]
Closing as done
