### ISSUE TITLE
Blog on what LB can offer on top of Express

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#4852]
### Acceptance Criteria
A blog post to persuade more Express users to use LoopBack 4. Possible content
- [ ] What LB can offer on top of Express
- [ ] what are the advantages of using LoopBack over Express? In most scenarios or particular ones?
- [ ] **can use LoopBack and Express together. It does not need to be exclusive**

**Comment by agnes512** [comment]
Some ideas for the blog:
-  Briefly talk about Express: solid but minimun fundation, users need to write route and glue middlewares themselves.
- How can Express users use LB4 for different personas: 
   - it can simply be used as a route as LB4 helps to glue the middleware, (What LB can offer on top of Expres, and they can be used together)
    - or even make it more open and scalable -> this is what LB4 are good at (what are the advantages of using LoopBack over Express)
- Some small examples to how how Express App can benefit from LB4 DI
- Show the lb4 working example: https://loopback.io/doc/en/lb4/express-with-lb4-rest-tutorial.html

**Comment by jannyHou** [comment]
Closing as the blog gets approved. Thank you @hacksparrow 🎉 !
