### ISSUE TITLE
how to execute native SQL queries in loopback4? I need  to do a inner join between to tables 

### ISSUE THREAD

**Issue by dip-sinha** [strongloop/loopback-next#4869]

**Comment by achrinza** [comment]
[`[RepositoryNameHere].execute()`](https://loopback.io/doc/en/lb4/apidocs.repository.defaultcrudrepository.execute.html)

**Comment by Rojasivalingam** [comment]
can anyone explain how to connect native sql in loopback 4

**Comment by hacksparrow** [comment]
@Rojasivalingam use `Repository.execute()` eg:

```ts
userRepository.execute(
    'SELECT * from User WHERE name=? && id=?',
    ['Apple', 3]
);
```

The returned object is the the result object of https://www.npmjs.com/package/mysql, you will have to process it on your own.

**Comment by Rojasivalingam** [comment]
Actually , I wants to know about the execution of the query in detail .
I'm  new to loopback  so any help is appreciated

**Comment by hacksparrow** [comment]
Create a LoopBack project using the `lb4` command, you can access the repository in the controller, where you can specify the SQL command as I have shown. [Start here](https://loopback.io/doc/en/lb4/Getting-started.html).

**Comment by Rojasivalingam** [comment]
yeah...!! Thanks anyways

**Comment by bajtos** [comment]
See also https://loopback.io/doc/en/lb4/Executing-database-commands.html
