### ISSUE TITLE
[Docs] Postgresql connector docs should cover LB4 content

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#4877]
Originated from #4271 

While the connectors can be used for both LB3 and LB4, the tutorials under the Connectors reference for LB4 are about LB3. It might cause confusion to the users.
- postgresql connector: https://loopback.io/doc/en/lb4/PostgreSQL-connector.html
- postgresql connector tutorial: https://loopback.io/doc/en/lb4/Connecting-to-PostgreSQL.html

### Acceptance Criteria 
For the two pages: https://loopback.io/doc/en/lb4/PostgreSQL-connector.html and https://loopback.io/doc/en/lb4/Connecting-to-PostgreSQL.html:
- [ ] Create separate sections that are specific to LB3 and LB4. 
   - The idea is to keep the LB3 content as well.

**Comment by agnes512** [comment]
Same for the READNE file (page https://loopback.io/doc/en/lb4/PostgreSQL-connector.html). Most of the setups, examples are in LB3 form. Should change or add contents for LB4.
