### ISSUE TITLE
[Docs] MongoDB connector docs should cover LB4 content

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#4879]
Originated from #4271 

While the connectors can be used for both LB3 and LB4, the tutorials under the Connectors reference for LB4 are about LB3. It might cause confusion to the users.

- mongodb connector tutorial: https://loopback.io/doc/en/lb4/Connecting-to-MongoDB.html

### Acceptance Criteria 
The docs page is coming from loopback-connector-mongodb README.
- [x] Create separate sections that are specific to LB3 and LB4. 
   - The idea is to keep the LB3 content as well.

**Comment by agnes512** [comment]
Please make sure these points are included in the tutorial: https://github.com/strongloop/loopback-next/issues/4059#issuecomment-622099952
