### ISSUE TITLE
Add a FAQ section

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#4883]
Let's have a FAQ section so our users can quickly find some of the common questions and queries instead of having to browse through multiple pages to get the answer.

Examples:

1. What's the difference between `ctx.bind()` and `ctx.configure()`?
2. Where do I find the default binding keys?
3. How do I use Express middleware with LoopBack 4?
4. How do I disable the API Explorer?
5. How do send a custom response?

**Comment by achrinza** [comment]
We already have an [FAQ page](https://loopback.io/doc/en/lb4/FAQ.html) that's hidden from the sidebar. We could start by adding it to the sidebar and expanding it from there.

**Comment by achrinza** [comment]
Closing as done.
