### ISSUE TITLE
(model-api-builder) Peer dependencies out of date?

### ISSUE THREAD

**Issue by dougal83** [strongloop/loopback-next#4889]
Should these dependencies be `^.2.0.0`?

https://github.com/strongloop/loopback-next/blob/4a25fa25ce33129f52b0e6eb196d2100c55ccb6e/packages/model-api-builder/package.json#L22-L25

**Comment by raymondfeng** [comment]
Lerna decided to not update peerDependencies as part of `lerna version`. See https://github.com/lerna/lerna/issues/1575.

I'm not a big fan of `peerDependencies`. I think we should either improve https://github.com/strongloop/loopback-next/blob/master/bin/update-template-deps.js to update `peerDependencies` or move them to regular `dependencies`.

@bajtos might have a different opinion.

**Comment by dougal83** [comment]
I was just looking at yarn and it came up when installing deps.  Any thoughts on optional-deps while we're on the subject?  fsevents & nan might be candidates for consideration.

**Comment by raymondfeng** [comment]
I don’t think we use optional deps for `@loopback/` modules, do we?

I would only declare non-critical binary addons as optional dep.

**Comment by dougal83** [comment]
> I don’t think we use optional deps for @loopback/ modules, do we?

Not that I can see.  Yarn discourages about implicit dependencies like fsevents (< rimraf < lbclean).  Declaring as optional deps seems like an option.

**Comment by dougal83** [comment]
Closed by #4972
