### ISSUE TITLE
hello-world: add Authentication component

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#490]
- add Authentication component
 - create a custom sequence calling `authenticate` action

cc @Setogit

**Comment by Setogit** [comment]
https://github.com/strongloop/loopback-next-hello-world/pull/8

**Comment by Setogit** [comment]
Added spec validation test and fixed the HelloWorld API spec
https://github.com/strongloop/loopback-next-hello-world/commit/2db4dcbe4c18091531468cedd6f593b33defecbd

**Comment by Setogit** [comment]
This PR contains both auth component and spec-validation:
https://github.com/strongloop/loopback-next-hello-world/pull/10
