### ISSUE TITLE
[Blog] Managing your APIs: From LoopBack to IBM API Connect

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#4901]
## Suggestion

With the plan of having LB4 integrated with the upcoming version of APIC, we should write an article / tutorial on how to go from LoopBack to IBM API Connect. This article will go to the IBM Developer site.

See https://github.ibm.com/IBMCode/IBMCodeContent/issues/2255 (restricted access)

## Acceptance Criteria
The article can possibly cover:
- why you might want to go from LB to APIC. 
- description/tutorial on how to import API from LB to APIC:
   - start with todo / todo-list app (so that we don't need to cover how to create a LB app)
   - check with OM whether we're going for the [APIC LB extension](https://github.com/strongloop/loopback-next/tree/master/extensions/apiconnect) or other ways. and document the recommended way.

**Comment by dhmlau** [comment]
cc @deepakrkris

**Comment by dhmlau** [comment]
Since the IBM Developer blog site uses a different repo, I'm thinking that we use strongloop.com repo for the blog PR and get the team to review as usual. Once it's ready, we can send that md file to the IBM Developer team.

**Comment by deepakrkris** [comment]
WIP PR opened https://github.com/strongloop/strongloop.com/pull/262

**Comment by dhmlau** [comment]
Sent to IBM Developer editor. Closing as done.
