### ISSUE TITLE
Support for oauth2 passport strategies, missing provisions for redirect and callback

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#4902]
## Suggestion

The StrategyAdapter is not adding the redirect() method in passport strategies, required for Oauth2 authorization flows.
This would also need some handling on the invocation side, i.e the Sequence class and others might need to participate according to the oauth flow.

## Use Cases

login thru third party apps like facebook, google
https://github.com/strongloop/loopback-next/issues/3958

## Acceptance criteria

- [ ] - strategy adapter must add all necessary calls for oauth2 in passport strategies
- [ ] - unit tests with mock redirect and mock third party app
- [ ] - must satisfy https://github.com/strongloop/loopback-next/issues/3958 for login with third party apps

**Comment by dhmlau** [comment]
related to https://github.com/strongloop/loopback-next/issues/2624

**Comment by deepakrkris** [comment]
PR submitted for review https://github.com/strongloop/loopback-next/pull/4919
