### ISSUE TITLE
Partial patch not working with required true of nested objects

### ISSUE THREAD

**Issue by bluewayll** [strongloop/loopback-next#4938]
Hello guys,

Dependencies version i'm using :

`"@loopback/boot": "^2.0.0",
    "@loopback/context": "^3.0.0",
    "@loopback/core": "^2.0.0",
    "@loopback/openapi-v3": "^3.0.0",
    "@loopback/repository": "^2.0.0",
    "@loopback/rest": "^3.0.0",
    "@loopback/rest-explorer": "^2.0.0",
    "@loopback/service-proxy": "^2.0.0",`

What i want to perform is a partial patch by id, my code : 

`@patch('/products/{id}', {
    responses: {
      '204': {
        description: 'Product PATCH success',
      },
    },
  })
  async updateById(
    @param.path.string('id') id: string,
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(Product, {partial: true}),
        },
      },
    })
    product: Partial<Product>,
  ): Promise<void> {
    await this.productRepository.updateById(id, product);
  }`

My models is : 
> Image => link (required: true), description (required; false)
> Product => id (id: true, generated: true), name (required: true), image (Model Image)(required: true)

What i get from the patch is : 

`{
  "error": {
    "statusCode": 422,
    "name": "UnprocessableEntityError",
    "message": "The request body is invalid. See error object `details` property for more info.",
    "code": "VALIDATION_FAILED",
    "details": [
      {
        "path": ".image",
        "code": "required",
        "message": "should have required property 'link'",
        "info": {
          "missingProperty": "link"
        }
      }
    ]
  }
}`

Thank you.

# Acceptance Criteria
- [] PATCH /Products/1 should work without error when only only the `image` property  object is specified, and only `description` property is specified for the image object. The `link` property shouldn't be required on an update, only on a create.

**Comment by emonddr** [comment]
@mastermunj  , can you take a look at this issue? It is related to your commit above. Thank you. :)

**Comment by emonddr** [comment]
`name` is required on Product model, and in a PATCH /products/1 , if we don't provide `name` property, the ajv doesn't mind. However, if in a PATCH /products/1 , we don't provide any product properties except `image`, and its contents does not include `link`, then ajv complains that this field is required. Seems inconsistent. How is the ajv validator informed that we are updating versus creating a Product model?

**Comment by bluewayll** [comment]
Hello @emonddr ,

Just for information if i put :

`schema: {type: 'object'},`

in place of : 

`schema: getModelSchemaRef(Account, {partial: true})`

No verification will be done and the patch will pass, but the problem is loopback will replace the object image with what i have provided and not change inside it.

**For example :** 

_old object :_ 
`
{
 name: "test name",
 image: {
      link: "test link",
      description: "test description"
 }
}
`

_patch with :_ 
`
{
 image: {
      description: "test description 2 2 2 2"
 }
}
`

_result :_ 
`
{
 name: "test name",
 image: {
      description: "test description 2 2 2 2"
 }
}
`

_expected result  :_ 
`
{
 name: "test name",
 image: {
      link: "test link",
      description: "test description 2 2 2 2"
 }
}
`

I don't know if it's related to the bug or it's another case.

Thank you.

**Comment by fidgi** [comment]
Hi @emonddr ,
Is there any progress related to the fix of this issue ?
As a workaround, I'm looking to revert to a version before the culprit commit but it's not obvious to find out the right combination of components versions to use.

**Comment by emonddr** [comment]
@fidgi , I was hoping @mastermunj would reply since provided the PR that added this code. I will speak with the broader team.

**Comment by emonddr** [comment]
Seems ajv had issues with PUT and PATCH in the past, based on this comment: https://github.com/epoberezkin/ajv/issues/211#issuecomment-400507746 . Investigating if they've fixed in or provided workarounds.

**Comment by raymondfeng** [comment]
@bluewayll This is an issue related to `partial` or `deep partial`.  When we see a schema as `schema: getModelSchemaRef(Product, {partial: true}),`, we only mark top-level properties of `Product` optional. In your case, the `link` is a required property of `Image` and `data.image.link` is not marked as optional.

To allow your use case, we'll have to introduce something like `partial: 'deep'`.

**Comment by emonddr** [comment]
@bluewayll , until then, as a workaround, you can update with PATCH /products/id and 
specify all the required fields of the image object.

```
{
  
    "image": {
      "link": "prod1 link",
      "description": "prod1 desc2"
    }
  }
```

**Comment by raymondfeng** [comment]
In #4968, I fixed `partial` to be deep.

**Comment by fidgi** [comment]
Thx @emonddr and @raymondfeng

**Comment by fidgi** [comment]
@raymondfeng hi, when do you plan to release the fix ? sorry to urge you, but this bug is blocking for us. Thanks

**Comment by emonddr** [comment]
> @raymondfeng hi, when do you plan to release the fix ? sorry to urge you, but this bug is blocking for us. Thanks

@fidgi , we will be making a release next week. :)

**Comment by fidgi** [comment]
@emonddr Great. thanks
