### ISSUE TITLE
Incomplete Loopback 4.x documentation

### ISSUE THREAD

**Issue by JacquesBonet** [strongloop/loopback-next#4982]
Comparing to Loopback 3.X, Loopback 4.x documentation is incomplete.

Especialy miss sections:

- Authentication, Authorization and Permissions
- Working with Data

**Comment by raymondfeng** [comment]
See docs for auth:

- https://loopback.io/doc/en/lb4/Integrate-with-infrastructures.html
- https://loopback.io/doc/en/lb4/Authentication-Tutorial.html
- https://loopback.io/doc/en/lb4/migration-authentication.html
- https://loopback.io/doc/en/lb4/migration-auth-access-control-example.html

Try search with `authentication` and/or `authorization`.

**Comment by achrinza** [comment]
PR for Working with Data: #4970

**Comment by achrinza** [comment]
Closing as the aforementioned docs are either already published or in the works.

If there's any other sections missing, feel free to comment or open a new issue so that we can continue the discussion.
