### ISSUE TITLE
hello-world tutorial README

### ISSUE THREAD

**Issue by Setogit** [strongloop/loopback-next#499]
This is a documentation part of the LoopBack Next tutorial umbrella task.  The other part is the coding part: https://github.com/strongloop/loopback-next/issues/463

The hello-world tutorial repo is in: https://github.com/strongloop/loopback-next-hello-world

==========
UPDATE (9/19) from @dhmlau 
- Verified the content and instructions in the https://github.com/strongloop/loopback-next-hello-world/README.md
- Outstanding work (code + writeup):
   - How to retrieve userid and password from Repository (in-memory, not backing with db).  Currently it is returning the same json of userid and password for any inputs.

**Comment by dhmlau** [comment]
Marking it as `p1` because it's part of the getting started tutorial.

**Comment by Setogit** [comment]
@emckean owns this task.

**Comment by dhmlau** [comment]
@emckean , would like to follow up on you regarding this issue.  Is it completed or you're waiting for @b-admike for the coding part to complete to finalize the writing?  Thanks.

**Comment by bajtos** [comment]
@b-admike please check with @kjdelisle whether this is still relevant, considering the other work on example repos.

**Comment by b-admike** [comment]
Talked with @kjdelisle and we've decided for me to work on https://github.com/strongloop/loopback-next/issues/645, and once that's done, close this.

**Comment by b-admike** [comment]
I am going to close this as done because we have a basic hello-world repo set up (see https://github.com/strongloop/loopback4-example-hello-world).
