### ISSUE TITLE
Migrating authentication and authorization

### ISSUE THREAD

**Issue by fgvicente** [strongloop/loopback-next#5026]
Hello i need guide for migrate user , accesstoken and acl.
Im migrate lb3 but when execute /explorer show api guide but not show where put token for try calls

**Comment by agnes512** [comment]
Hi, we recently added the guide and it is up on the site: [Migrate authentication](https://loopback.io/doc/en/lb4/migration-authentication.html). I am closing the issue. Feel free to reopen if it doesn't works for you, thanks.
