### ISSUE TITLE
Copy html file to DIST folder (BUILD)

### ISSUE THREAD

**Issue by MwSpaceLLC** [strongloop/loopback-next#5028]
## Suggestion

![image](https://user-images.githubusercontent.com/29952045/78381639-f3fab880-75d5-11ea-836e-feab211357c5.png)

We are not able to copy our HTML content into the DIST folder e.g. the content by email

For now our content is loaded in the typescript file but we don't want to include all the html template in a string.

Even if this works without problems we would like the possibility to include the file as a string via HTML file system But in the distribution folder this file is not copied

## Use Cases

HTML content can be used to send emails I have other strings.

Our function is very simple. It replaces the strings containing the keyword of the variable in question, thus providing dynamic support for html content.

## Examples

Use html with var:
![image](https://user-images.githubusercontent.com/29952045/78382113-974bcd80-75d6-11ea-8f87-f1c59e01ca4b.png)

Inside mail service:
![image](https://user-images.githubusercontent.com/29952045/78382167-ac286100-75d6-11ea-9784-a8cb5c1dc336.png)

Example sender dinamic content:
```javascript
mailClient.prepare(
    '✔ Confirm e-mail address', // SUBJECT
    'confirm', // HTML TEMPLATE src/services/nodemailer/emails/confirm.ts
   [{link: uniqid('mail-token')}]  // HTML PARAM {{link}}
)
    .send(user.email,'another@mail.com','another@mail.it')
```
## Acceptance criteria

TBD - will be filled by the team.

**Comment by MwSpaceLLC** [comment]
If u want see test project u can get it at:

https://github.com/MwSpaceLLC/lb4-starter

**Comment by MwSpaceLLC** [comment]
and we want include other html file also ejs as follow:

```javascript
  let people = ['geddy', 'neil', 'alex'],
      html = ejs.render('<%= people.join(", "); %>', {people: people});
```

This speed up our Dev Package. and clearly code for send email template

**Comment by MwSpaceLLC** [comment]
In this example we try to implement. But not are files in DIST FOLDER

![image](https://user-images.githubusercontent.com/29952045/78387913-653f6900-75e0-11ea-9fa3-192ed53bb794.png)

**Comment by MwSpaceLLC** [comment]
OK! We have found it:

    "build": "lb-tsc --copy-resources"

Work fine! U can tell me if this is correct option ?? bye

**Comment by dougal83** [comment]
@MwSpaceLLC `--copy-resources` is one way to do it.  You can also [host static files](https://loopback.io/doc/en/lb4/Serving-static-files.html) with loopback, which if I'm not mistaken is as you can with as `express` server.

Also please refer to the [example shopping app](https://github.com/strongloop/loopback4-example-shopping/tree/master/packages/shopping) for how you can use the public folder to host a website.

**Comment by dhmlau** [comment]
Closing as resolved.
