### ISSUE TITLE
How to create a custom primary key name with MongoDB

### ISSUE THREAD

**Issue by meet02** [strongloop/loopback-next#5042]
Hello, if I create the following primary key in MongoDB:

```ts
@property({
  type: "string",
  id: true,
  generated: false,
  default: ${IdGenerator.generateRandom("FAC")},
})
faq_category_id: string;
```

The primary key's name would be `_id` instead of `faq_category_id`.

So, can I use `faq_category_id` as the primary key name?

**Comment by agnes512** [comment]
@meet02 we don't allow custom names for **the id property** in the Mongo connector. Only the default name `_id` is allowed in the DB. 
```
  @property({
    id: true,
    type: string
    generated: true,
    // mongodb: {   // will cause error
    // field: 'myId',
    //}
  })
  id: string
```

Collections and other properties are able to be set with custom names:

```
@model({
    settings: {
        mongodb:{
            collection: 'CUSTOM_CLASS_NAME'
        }
    }
})
export class myClass extends Entity {
  ...
  @property({
    id: false,
    type: string
    mongodb: {
    field: 'MY_NAME', // property name is stored as MY_NAME in the db
    }
  })
  name: string
```

**Comment by agnes512** [comment]
We updated the README file on [customizing collections/field name](https://github.com/strongloop/loopback-connector-mongodb#customize-collectionfield-names). Hope it helps!
