### ISSUE TITLE
Loopback 4, Model, PostgresDB schema name

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [strongloop/loopback-next#5055]
I use Loopback 4, TypeScript with PostgreSQL DB, I have a requirement to mention the postgresql schema name for the tables,

```sql
CREATE TABLE registry.vendors (
  id VARCHAR(50) not null default registry.id_generator()  PRIMARY KEY,
  name VARCHAR (50) UNIQUE NOT NULL
);
```

Model is defined as below

```typescript
@model({
  name: 'vendors'
// name: 'registry.vendors' not working
})
export class Vendor extends Entity {
  @property({
    type: 'string',
    id: true,
    //required: true,
  })
  id: string;
....
}
```

Loopback 4 always look for table 'public.vendors' not 'registry', I don't find any documentation on lb4 website https://loopback.io/doc/en/lb4/Model.html  related to this, how to explicitly mention the schema name in the model/loopback so that the lookup can be done on schema name, not the default 'public'

**Comment by bajtos** [comment]
> is it possible to specify what Postgres schema to use for queries at runtime? I have a use case where after authorization, I get the schema name from the user object and that would determine what schema on my Postgres DB to query. I'm building a multi-tenant application.

I opened a new issue to discuss this use case and posted few ideas what to try.

See https://github.com/strongloop/loopback-next/issues/5056
