### ISSUE TITLE
Add CORS support to swagger/openapi endpoints

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#506]
CORS is required to use http://localhost:3000/openapi.json for http://editor.swagger.io/.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/pull/475

**Comment by kjdelisle** [comment]
Linking for my reference: https://github.com/strongloop/loopback-next/pull/531

**Comment by kjdelisle** [comment]
## Acceptance Criteria
- Allow `*.swagger.io` in CORS
- Pass generated swagger.json to `editor.swagger.io` so that users can leverage the existing editor tools on their local application.
- Verify that you can make REST requests from `editor.swagger.io` to listed local APIs.

**Comment by raymondfeng** [comment]
> Allow *.swagger.io in CORS

The openapi spec should be open to any domains. Let's not tie it to `*.swagger.io` only.

**Comment by b-admike** [comment]
I've created https://github.com/strongloop-internal/scrum-apex/issues/315 to track the doc work for this feature.
