### ISSUE TITLE
Add missing LoopBack 4 Types docs

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#5063]
Loosely related: #2527
LoopBack 3-equivilant docs: https://loopback.io/doc/en/lb3/LoopBack-types.html

## Steps to reproduce

1. Visit https://loopback.io/doc/en/lb4/Model.html#property-decorator
2. Click the "LoopBack types" link.
    
    ![image](https://user-images.githubusercontent.com/25147899/78761746-9390c000-79b5-11ea-9a39-60c69670086e.png)

## Current Behavior

The page doesn't exist:

![image](https://user-images.githubusercontent.com/25147899/78761896-cdfa5d00-79b5-11ea-944b-a2a977030c54.png)

## Expected Behavior

The page should exist, describing the different LoopBack types and how they map to the native types of OAS 3, JavaScript and the database engine.

## Additional information

N/A

## Related Issues

N/A

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
There is a LB3 version of LoopBack Types: https://loopback.io/doc/en/lb3/LoopBack-types.html. We can possibly use this as the starting point.

**Comment by agnes512** [comment]
Note: some connector docs for lb4 are using the outdated link. Don't forget to update them as well.

**Comment by agnes512** [comment]
Closing as done
