### ISSUE TITLE
[Discussion] Extensions contributed by the community

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#5076]
Originated from https://github.com/strongloop/loopback-next/issues/3047#issuecomment-611420052. 

Cross posting https://github.com/strongloop/loopback-next/issues/3047#issuecomment-611420052 from by @ckoliber

> I want to add more extensions:
> 
> loopback-history-extension: For adding history feature to models
> loopback-acl-extension: A generalized base application with User, Role, Permission models and controllers with an advanced controller generator supports model relations and access controlling
> And now i'm trying to implement loopback-connector-processmaker
> 
> Please give me the required access to create these projects in strongloop organization

### Things to discuss
1. For extensions contributed by the community, where would be a good location? the contributor's github org, `strongloop-community`, etc? The good thing to leave them in the contributor's org is that they can get the credits for creating/maintaining them.  Also, the community is free to create any extensions any time, so it is not necessary to put it in the `strongloop` org. 
 
2. With an increasing number of extensions created by the core maintains and community, it might make sense to have an "Extensions" page similar to [the Example page](https://loopback.io/doc/en/lb4/Examples.html). If someone wants to share an extension with the community, they can submit a PR to add it on the extension page.

Would like to hear inputs from @ckoliber @strongloop/loopback-maintainers. Thanks!

**Comment by ckoliber** [comment]
Thanks @dhmlau

Self GH organization is a good choice, but as we know, open source projects will grow up faster by community contributors help,
I thing keeping these types of extensions in a centralized origanization can help to finding them by community more easier

**Comment by achrinza** [comment]
We already have a [LoopBack community projects](https://loopback.io/doc/en/community/index.html) page. Though it’s quite hidden and it’s not LoopBack 4-specific.

So we probably want to create a separate page for LoopBack 4 community projects and then link to it.

**Comment by dhmlau** [comment]
Fixed via PR https://github.com/strongloop/loopback-next/pull/5707.
