### ISSUE TITLE
Filter not working with mongodb 

### ISSUE THREAD

**Issue by rahulrkr08** [strongloop/loopback-next#5092]
## Steps to reproduce

MongoDB Data:

```js
[{
   id: "5e8d9958dce3367fa11bc2fe",
   name: "Some name",
   slug: "some-name",
   user_id: "5c6b9d939a7b892772c894e8"
}]
```
**Request:**

`http://localhost:4001/posts?filter={"where":{"user_id":"5c6b9d939a7b892772c894e8"}}`

## Current Behavior

I am getting empty (`[]`) data when I am querying with where condition.

## Additional information

But, if I make changes in user_id value, something like 
```js
{
    ...,   
    user_id: "user|5c6b9d939a7b892772c894e8"
}
```
then, I am getting response (`http://localhost:4001/posts?filter={"where":{"user_id":"user|5c6b9d939a7b892772c894e8"}}` )

Please correct me if am doing something wrong here.

**Comment by mdbetancourt** [comment]
that it's an old but, mongo convert to ObjectId every string that has the same format. you can check it here https://github.com/strongloop/loopback-next/issues/1875#issuecomment-431184017

**Comment by rahulrkr08** [comment]
Thanks @mdbetancourt, it worked.
