### ISSUE TITLE
Exposing Stored Procedures from MSSQL using loopback 4

### ISSUE THREAD

**Issue by neha2683** [strongloop/loopback-next#5101]
Hello 

Able to access the DB tables from MS SQL using loopback 4 . 

Looking for options to expose only the Stored Procedures from the table , and expose them as Rest APIs . Kindly help.  Thanks.

**Comment by dhmlau** [comment]
Cross posting from https://github.com/strongloop/loopback-next/issues/3798#issuecomment-535119705.

You can call DataSource.execute(), something like below:
```
  @get('/test', {
    responses: {
      '200': {
        description: 'test for executing query',
      },
    },
  })
  async test(): Promise<any> {
    return this.customerRepository.dataSource.execute('SELECT * FROM CUSTOMER');
  }
```

**Comment by neha2683** [comment]
Thanks Diana .
But what I want is to call 2000+ stored procedures via REST API through loopback. 
Is there a way to do that ? Thanks in advance .

**Comment by dhmlau** [comment]
@neha2683, do you mean you want one REST API that calls 2000+ stored procedures, or 2000+ endpoints that each call one stored procedure?

**Comment by neha2683** [comment]
The latter one.... Procedure name and input parameters as inputs to one
Rest Api.

**Comment by neha2683** [comment]
hello
i need to create APIs like this ( as available  in dreamfactory ) . How to do with loopback. 

GET  /_proc/{procedure_name}
Call a stored procedure.

POST  /_proc/{procedure_name}
Call a stored procedure.

**Comment by dhmlau** [comment]
@neha2683, it would be something similar to what I posted in https://github.com/strongloop/loopback-next/issues/5101#issuecomment-613189957.  Controllers are used to expose REST APIs, so add those functions in the controller.

**Comment by deepakrkris** [comment]
@neha2683 please take a look at https://github.com/strongloop/loopback-next/issues/3459

```
constructor(
    @repository(MyRepository)
    public myRepo: MyRepository,
  ) {
    this.user_Profile = userProfile;
  }
 async testData(
  ): Promise<any> {
    return await this.myRepo.dataSource.execute(`EXEC Get_Customer(?)`, ['CUSTID01']);
  }
```

and

https://loopback.io/doc/en/lb4/apidocs.repository.connector.execute.html

**Comment by dhmlau** [comment]
Closing as resolved.
