### ISSUE TITLE
[GSSC-GVT]Some items are not translated when input command APIC apic lb4 app test01 repositories -h

### ISSUE THREAD

**Issue by wxuwh** [strongloop/loopback-next#5120]
27.030.010

Steps:
1. input command APIC apic lb4 app test01 repositories -h

Actual Result:
[GSSC-GVT]Some items are not translated
![image](https://user-images.githubusercontent.com/45190559/79432163-0a553b00-7ffe-11ea-9fa6-840fe2481af8.png)

**Comment by dhmlau** [comment]
I believe the highlighted text is coming from Yeoman. IIRC, we were able to override that in LB3. Will need to double check. 

@wxuwh, for GVT related issue, could you please use the `GVT` label? Thanks.

**Comment by dhmlau** [comment]
Here is the code for overriding the options from Yeoman: https://github.com/strongloop/generator-loopback/blob/d32f5112b84888751c7e4ba616915e92ae16ac4d/app/index.js#L36-L38.

@agnes512, could you please help on this? Thanks!

**Comment by candytangnb** [comment]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/26452457/81122915-850dd800-8f64-11ea-96d9-e4d9bce04150.png">
I check in cli master build 3275 and found that still in English
Built 2020-05-04T21:55:44Z
