### ISSUE TITLE
[GSSC-GVT]Some items are not translated when input command APIC apic lb4 app test03 repositories

### ISSUE THREAD

**Issue by wxuwh** [strongloop/loopback-next#5121]
27.030.020

Steps:

    input command APIC apic lb4 app test03 repositories

Actual Result:
Some items are not translated
![image](https://user-images.githubusercontent.com/45190559/79432550-8b143700-7ffe-11ea-8451-6b8d461a060b.png)

**Comment by candytangnb** [comment]
I check in cli master build 3275 and found that still in English
Built 2020-05-04T21:55:44Z
<img width="746" alt="image" src="https://user-images.githubusercontent.com/26452457/81122828-598aed80-8f64-11ea-9cfb-5fd0e3baef55.png">
