### ISSUE TITLE
[GSSC-GVT]English String when input command apic lb4 example

### ISSUE THREAD

**Issue by wxuwh** [strongloop/loopback-next#5128]
27.030.030 APIC apic lb4 example(Apr)
--

Steps:
input ./apic lb4 example
and click Enter
Click Enter
Verify the strings 

Actual Result:
![image](https://user-images.githubusercontent.com/45190559/79523601-2b1aa080-8091-11ea-983a-b053d16cc720.png)

**Comment by dhmlau** [comment]
`(Use arrow keys)` is coming from Yeoman, we cannot override that. 

For the example list name and description, @agnes512 and I had a discussion, not sure if the name can be translated but the description should be translated.

**Comment by candytangnb** [comment]
I check in cli master build 3275 and found that still in English 
Built 2020-05-04T21:55:44Z
<img width="944" alt="image" src="https://user-images.githubusercontent.com/26452457/81122488-88ed2a80-8f63-11ea-81c0-1056d11068dc.png">

**Comment by dhmlau** [comment]
The build `Built 2020-05-04T21:55:44Z` has `@loopback/cli@2.4.4` where the translation files are published in `2.5.0`.

**Comment by dhmlau** [comment]
I'm not sure how to update it from the apic command. For LoopBack, you can install the latest by running : `npm i -g @loopback/cli`.
