### ISSUE TITLE
Publish initial API docs 

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-next#513]
Developers need minimal API documentation to use LoopBack-Next.  Presumably, we would continue to use apidocs.strongloop.com to publish API docs.  I believe @mpatsute laid the necessary groundwork to generate API docs from the TypeScript code, but we need to hook it into the production version of apidocs.strongloop.com.  

cf. https://github.com/strongloop/loopback-next-apidocs (this repo can be deleted once apidocs.strongloop.com is updated).

**Comment by dhmlau** [comment]
I believe we are going to keep the apidocs for LB3 as well?  If so, how are we going to show these 2 sets of apidocs to our users?

**Comment by crandmck** [comment]
We definitely need to keep the v3 docs as well.  

I _think_ the two sets of API docs can co-exist, due to all the work that @mpatsute did on strong-docs, but he should confirm.

My assumption is that the user can simply choose "4.0beta1" or other release number from the drop-down list to display the v4 API doc.  IIUC all the LB-next packages will be in the `loopback` repo.

![2017-08-15_1632](https://user-images.githubusercontent.com/2925364/29341187-ae23975e-81d7-11e7-9811-ff0804e179a7.png)

**Comment by dhmlau** [comment]
cc @mpatsute

**Comment by crandmck** [comment]
I just spoke with Mahesh, and it seems like everything is lined up, so all we need to do is (1) promote the master branch of apidocs.strongloop.com to production and then (2) npm publish loopback-next.  Then the site _should_ pick up the latest version of the lb-next packages…. I think we can go ahead and do no. 1 now.  There is no reason to wait, AFAIK. I can do that perhaps with some help from Ryan if I need it.

So… we probably won’t need any of Mahesh’s time--unless something goes wrong!

**Comment by crandmck** [comment]
Currently, based on running the site locally, this won't work for beta release, because the design assumes that we only want to publish API docs for "stable" (non-alpha, non-beta) releases.  So the links on the site home page to LB-next packages go to (for example) http://localhost:3000/@loopback%2fcore which don't resolve and display the message `No latest stable version found!`.  

However, if you go directly to the URL for an alpha release, you can see the docs, for example:
http://localhost:3000/@loopback%2fcore/v/4.0.0-alpha.11/

We can fix this in two ways:
1. Change the site so it picks up alpha/beta releases (at least for lb-next).
2. Change the links on the home page (`home.ejs`) to go directly to the beta release, e.g. http://localhost:3000/@loopback%2fcore/v/4.0.0-beta.1/.  This is something of a hack, but it would work without any extra dev effort.

I'm going to discuss the options with @ritch.

**Comment by crandmck** [comment]
@dhmlau Current status is that we do need to do a little work to get apidocs.strongloop.com to pick up "non-stable" (i.e. beta) releases from npm.

Most likely @mpatsute would be the best person to do this work.  I suspect it would be less than a day of work, but he would be best to provide more accurate estimate.  It's possible someone else could do the work, but would need to consult with Mahesh anyway.

**Comment by crandmck** [comment]
This PR _should_ make it work for beta https://github.com/strongloop-internal/apidocs.strongloop.com/pull/77

**Comment by dhmlau** [comment]
@crandmck , do we need to wait till no more tsdoc changes in order to have it published?  Is it an automatic update if js/tsdoc changes in code?

**Comment by crandmck** [comment]
The API docs get updated with each publish to npm.  Any changes made to doc comments in the code are picked up at that time for that particular version.

BTW, here is the staging site: http://apidocs.strongoops.com/  (n.b. it's strong**oops**.com :-)
I can promote this to production with the "push of a button."

**Comment by dhmlau** [comment]
> The API docs get updated with each publish to npm.
I guess no work needs to be done here anymore?

**Comment by crandmck** [comment]
Yes, the apidocs app is functional for beta, so no more work needs to be done on it.  We might want to make some tweaks at some point (e.g. removing docs for "alpha" releases once we have "beta").

We do still need to review and flesh out the doc comments in the code to ensure that they accurately reflect the API, but that should be a separate issue.

**Comment by dhmlau** [comment]
@crandmck, the team is ready to have the API doc published.  Thanks!

**Comment by crandmck** [comment]
OK http://apidocs.loopback.io/ is now re-deployed and includes the loopback-next alpha modules.  When beta is published to npm, these will be reflected on the site as well.

**Comment by crandmck** [comment]
n.b. Added #577 because we still have lots of work to do on the API doc content, i.e. code comments.
