### ISSUE TITLE
[GSSC-GVT]English String in LB4 command "apic lb4 controller"

### ISSUE THREAD

**Issue by wxuwh** [strongloop/loopback-next#5130]
27.030.050
Steps:
input ../apic lb4 controller and click Enter
Input con1 as name and click Enter
Verify the strings in red circle.
Click Enter to exit

Actual Result:
![image](https://user-images.githubusercontent.com/45190559/79527635-afbdec80-809a-11ea-9076-d6b3be597c0a.png)

**Comment by candytangnb** [comment]
I check in cli master build 3275 and found that still in English
Built 2020-05-04T21:55:44Z
<img width="519" alt="image" src="https://user-images.githubusercontent.com/26452457/81122570-b9cd5f80-8f63-11ea-9a7c-840ecee6331a.png">
