### ISSUE TITLE
[GSSC-GVT]English String in LB4 command "apic lb4 interceptor"

### ISSUE THREAD

**Issue by wxuwh** [strongloop/loopback-next#5131]
27.030.050
Steps:
input ../apic lb4 interceptor and click Enter
Input con1 as name and click Enter
Verify the strings in red circle.
Click Enter to exit

Actual Result:
![image](https://user-images.githubusercontent.com/45190559/79531375-b9e4e880-80a4-11ea-9049-a99d223caf47.png)
![image](https://user-images.githubusercontent.com/45190559/79533046-82c50600-80a9-11ea-9a69-8bbbe20e9238.png)

**Comment by dhmlau** [comment]
@agnes512, the text above can be found in the following locations: 
https://github.com/strongloop/loopback-next/blob/master/packages/cli/lib/utils.js#L122-L131
https://github.com/strongloop/loopback-next/blob/master/packages/cli/lib/artifact-generator.js#L102-L128

**Comment by candytangnb** [comment]
I check in cli master build 3275 and found that still in English
Built 2020-05-04T21:55:44Z
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/26452457/81122678-fbf6a100-8f63-11ea-8a5c-36de308df1f1.png">
