### ISSUE TITLE
Broken link from the todo example to Sequence.md

### ISSUE THREAD

**Issue by danquah** [strongloop/loopback-next#5145]
## Steps to reproduce
Access the lb4 documentation for the todo example at 
https://loopback.io/doc/en/lb4/todo-tutorial-scaffolding.html scoll down a bit to the table that describes `src/sequence.ts` and click the "Sequence" link

## Current Behavior
Broken link that leads to https://loopback.io/doc/en/lb4/Sequence.md

## Expected Behavior
Link that leads to https://loopback.io/doc/en/lb4/Sequence.html

## Link to reproduction sandbox
(Not applicable)

## Additional information
(Not applicable)

## Related Issues
Found this over on the loopback.io repo: https://github.com/strongloop/loopback.io/issues/962 does not seem related, but it _is_ about a broken link in the lb4 docs, so how knows.

**Comment by raymondfeng** [comment]
Thank you for reporting the issue. We need to adjust the relative path to `Sequence.md` in the tutorial - https://github.com/strongloop/loopback-next/blob/master/docs/site/tutorials/todo/todo-tutorial-scaffolding.md:

`[Sequence](Sequence.md)` -> `[Sequence](../../Sequence.md)`

Are you interested in contributing a patch?

**Comment by danquah** [comment]
Sure am, I'll look into it in a couple of hours. I verify by building documentation as outlined in https://github.com/strongloop/loopback.io/blob/gh-pages/README.md right? Or is it enough to just eyeball the diff itself?
