### ISSUE TITLE
Add CODEOWNERS for automatically requests reviews from code owners

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#517]
New feature in github allows us to specify the owner of the repo. https://github.com/blog/2392-introducing-code-owners

Since each package might have different set of codeowners, I'm proposing the following breakdown: 

```
*  @bajtos @raymondfeng #for overall
packages/authentication/*  <<some ids>>
packages/context/*  <<some ids>>
...
```

Related to https://github.com/strongloop-internal/scrum-apex/issues/278

**Comment by bajtos** [comment]
+1 from me. If I understand the format of CODEOWNERS file correctly, then I think we need to duplicate "overall" owners in each package-specific line.

```
*  @bajtos @raymondfeng

packages/context/* @bajtos @raymondfeng @somebodyelse
```

**Comment by dhmlau** [comment]
PR has landed. Closing it.
