### ISSUE TITLE
TS docs for OpenAPI decorators not showing up

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#5170]
In the OpenAPI decorator page https://loopback.io/doc/en/lb4/Decorators_openapi.html, the api docs for `@oas.response` and `@oas.tags` no longer exist, causing the broken links for: 
https://loopback.io/doc/en/lb4/apidocs.openapi-v3.oas.response.html 
https://loopback.io/doc/en/lb4/apidocs.openapi-v3.tags.html

From @jannyHou: 
> there should be a namespace for it:
https://github.com/strongloop/loopback-next/blob/master/packages/openapi-v3/src/decorators/response.decorator.ts#L86
but page https://loopback.io/doc/en/lb4/apidocs.openapi-v3.oas.html doesn’t generate

Currently, the temp workaround is to use https://loopback.io/doc/en/lb4/apidocs.openapi-v3.oas.html#oas-variable instead. 

## Acceptance Criteria
- [ ] Fix the ts docs for `oas.response` and `oas.tags`.
- [ ] Change https://loopback.io/doc/en/lb4/Decorators_openapi.html to point to the actual `oas.response` and `oas.tags` link instead of the temp workaround mentioned above.

**Comment by jannyHou** [comment]
Thanks for the summary Diana.
I think it’s because https://github.com/strongloop/loopback-next/blob/master/packages/openapi-v3/src/decorators/index.ts#L10 exports those earlier created decorators.
But for the new ones they are under `const oas` , like `response` so that the root level index doesn’t have it exported as namespace or function, and you can only find it under `oas` in
https://loopback.io/doc/en/lb4/apidocs.openapi-v3.oas.html#oas-variable

**Comment by raymondfeng** [comment]
We might have to do something like:
```ts
// Copyright IBM Corp. 2018,2020. All Rights Reserved.
// Node module: @loopback/openapi-v3
// This file is licensed under the MIT License.
// License text available at https://opensource.org/licenses/MIT

export * from './api.decorator';
export * from './deprecated.decorator';
export * from './operation.decorator';
export * from './parameter.decorator';
export * from './request-body.decorator';

import {api as oasApi} from './api.decorator';
import {deprecated as oasDeprecated} from './deprecated.decorator';
import {
  del as oasDel,
  get as oasGet,
  operation as oasOperation,
  patch as oasPatch,
  post as oasPost,
  put as oasPut,
} from './operation.decorator';
import {param as oasParam} from './parameter.decorator';
import {requestBody as oasRequestBody} from './request-body.decorator';
import {response as oasResponse} from './response.decorator';
import {tags as oasTags} from './tags.decorator';

/**
 * Decorators for OpenAPI specs
 */
export namespace oas {
  export const api = oasApi;
  export const operation = oasOperation;

  // methods
  export const get = oasGet;
  export const post = oasPost;
  export const del = oasDel;
  export const patch = oasPatch;
  export const put = oasPut;

  //param
  export const param = oasParam;

  // request body
  export const requestBody = oasRequestBody;

  // oas convenience decorators
  export const deprecated = oasDeprecated;
  export const response = oasResponse;
  export const tags = oasTags;
}
```

**Comment by jannyHou** [comment]
Closing as PR #6626 merged.
