### ISSUE TITLE
Add refresh in the jwt extension

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#5187]
## Suggestion

Based on the comment from @mschnee in https://github.com/strongloop/loopback-next/pull/5046#issuecomment-611778032.

Add token refresh functionality in the jwt auth extension https://github.com/strongloop/loopback-next/tree/master/extensions/authentication-jwt

There is a demo PR for token refresh in strongloop/loopback4-example-shopping#537, and the token service interface has revokeToken function added in https://github.com/strongloop/loopback-next/pull/4746/files.

## Use Cases

TBD 

_I may need more time to create the use case and example, cc @mschnee would you like to add your expected use cases here? Thank you!_

## Examples

TBD

## Acceptance criteria

- [ ] Add refresh function in the jwt strategy and corresponding tests.

**Comment by dhmlau** [comment]
@madaky, per our discussion on Slack, seems like you'll try to work on that. Assigning this to you now. Thanks!

**Comment by madaky** [comment]
@dhmlau: I am on it

**Comment by madaky** [comment]
Proposed Use Case for Referesh Token:  Any sugestion @jannyHou @deepakrkris  @dhmlau 
![proposerefresh](https://user-images.githubusercontent.com/17172989/82712552-daa4ed00-9ca5-11ea-8e89-b1a054b339b6.png)

**Comment by jannyHou** [comment]
cc @madaky There is some discussion in https://github.com/strongloop/loopback-next/issues/4573, I need a bit more time to investigate, will get back to you asap

**Comment by madaky** [comment]
The discussion [ #4573](https://github.com/strongloop/loopback-next/issues/4573) : pointing towards adding a method signature in Authentication Component.

For giving User choice between Choosing need for refresh token. I implemented two interceptors
`
@intercept('refresh-token-generate') //to generate refresh token
@intercept('refresh-token-grant') // to  refresh token
`
Will finish and pull it later today

**Comment by dhmlau** [comment]
Closing as done as PR #5589 has landed. 
Thanks @madaky and @jannyHou!
