### ISSUE TITLE
CLI packages not upgraded

### ISSUE THREAD

**Issue by rahulrkr08** [strongloop/loopback-next#5209]
I am getting below warning message when creating the model.

```sh
lb4 model
The project was originally generated by @loopback/cli@<unknown>.
The following dependencies are incompatible with @loopback/cli@2.4.3:
- @types/node: ^13.13.2 (cli ^10.17.21)
? How do you want to proceed? (Use arrow keys)
❯ Abort now 
  Upgrade project dependencies 
  Skip upgrading project dependencies
```

**Comment by dougal83** [comment]
Hi @rahulrkr08 
Try editing `package.json` and set `@types/node: ^10.17.21`.  There may have been a release that changed the version to ^13 in error.

**Comment by raymondfeng** [comment]
We still use `@types/node: ^10.17.21` for maximum compatibility with Node 10.x. Feel free to upgrade the project dependency as prompted. It's a one-time thing since you use a newer version CLI.
