### ISSUE TITLE
Define services to represent interactions with REST APIs, SOAP Web Services, gRPC services, and more

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#522]
LoopBack uses `DataSource` to configure connections to various services, such as:

1. REST APIs
2. SOAP Web Services
3. gRPC Microservices

The common characteristics of above are:

1. Service operation/message definition
2. Operations are service-oriented, not data oriented

We need to have a way expose such services as Node.js/TypeScript APIs backed by the data sources. Do we want to generate strongly-typed TS interface for the operations or mix in such methods at runtime (like LB 3.x)?

**Comment by dhmlau** [comment]
`Services` could be the base class of `Repository`.  Might need some refactoring.

**Comment by dhmlau** [comment]
@raymondfeng , we have a ticket for SOAP and REST service integration #1036, but not for gRPC.  Do we still want to keep this? Thanks.

**Comment by bajtos** [comment]
Closing as a duplicate of #1036
