### ISSUE TITLE
A blog post about extension development

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#524]
A blog post explaining to readers how easy it is to build an extension for LB Next, making people excited and wanting to write one! 

Stakeholders to discuss the blog post with: @raymondfeng , @ritch, @kjdelisle, etc.

Promote @kjdelisle call for extensions: https://github.com/strongloop/loopback-next/issues/509

See also #218

---

**Acceptance criteria**

The blog post should be at relatively high level (think of extension-starter's README), for deeply technical content point readers to existing docs in other places.

 - describe the scenario we have in mind (logger extension)
 - why we have to build an extension using the structure we are going to follow (explain LoopBack-Next concepts)
 - a step-by-step tutorial showing how to build this simple extension
 - link to the repo with the completed example

Use @virkt25's example extension - a logger component providing a `@log` decorator, a sequence action and an app-level mixin to drive the post content.

**Comment by Setogit** [comment]
Combine with Raymond's blog series: https://github.com/strongloop/loopback-next/wiki/Crafting-LoopBack-Next

**Comment by bajtos** [comment]
Let's make this a short post bringing hello-extension into attention of people reading our blog. Keep most of the details in the actual hello-extension repository.

**Comment by kjdelisle** [comment]
Blocked on #525 ; we can't estimate this task until we know how difficult it is to do this.

**Comment by jonathan-casarrubias** [comment]
[to-be-released]  cool :D that will help speed up things to other devs
