### ISSUE TITLE
Add Couchdb connector docs 

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#5267]
## Suggestion

Under the Connector References, there is no info on the CouchDB connector (loopback-connector-couchdb2), even though the `lb4 datsource` has this option. 

## Acceptance criteria
- [x] add an entry for CouchDB under Connector Reference in LB3 docs
  - [x] update the [update-readmes.sh](https://github.com/strongloop/loopback.io/blob/gh-pages/update-readmes.sh) file to get the couchdb readme
- [x] add an entry for CouchDB under Connector Reference in LB4 docs
- [x] update CouchCB readme with LB4 specific configuration

**Comment by dhmlau** [comment]
FYI - issue reported by a community user

**Comment by agnes512** [comment]
Met all acceptance criteria. Closing as done
