### ISSUE TITLE
Wrong documentation on Storage

### ISSUE THREAD

**Issue by JacquesBonet** [strongloop/loopback-next#5268]
## Steps to reproduce
The end of this loopback 4 documentation is wrong: https://loopback.io/doc/en/lb4/Storage-connector.html

````
Connect the model to the storage data source
/server/model-config.json

...
  "container": {
    "dataSource": "myStorageDataSource",
    "public": true
  }
...
Tags: connectors
````

There is no model-config.json on loopback 4

**Comment by agnes512** [comment]
@JacquesBonet Unfortunately we don't support the storage component in LB4 anymore. And that page should be removed from LB4 site.

We provides some workarounds for you to implement similar functionality. Please check [LoopBack 3 features not planned in LoopBack 4](https://loopback.io/doc/en/lb4/migration-not-planned.html).

I will remove it from the connector list shortly.
