### ISSUE TITLE
Broken wiki links

### ISSUE THREAD

**Issue by richardpringle** [strongloop/loopback-next#527]
# Description/Steps to reproduce
@crandmck - Couple broken links on [this page](https://github.com/strongloop/loopback-next/wiki/Getting-started) at the bottom.

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by crandmck** [comment]
Fixed link to "Installation".  We don't have a "scaffolding" page, and no working CLI yet, so just removed that one for now.
