### ISSUE TITLE
Loopack 4 command not found

### ISSUE THREAD

**Issue by nvthuong1996** [strongloop/loopback-next#5289]
I think this issue has been discussed a lot, but so far it has not been thoroughly resolved.
i flow setup loopack https://loopback.io/doc/en/lb4/Getting-started.html
`npm i -g @loopback/cli` 
but when i run command `lp4 app` error `Loopack 4 command not found` appear
I tried to install another package to check if npm worked properly
`npm install -g corona-cli`
continue i run `corona -x`. it working

i use node@12 install via brew in macos 10.15.4

**Comment by raymondfeng** [comment]
The command is `lb4` instead of `lp4`.
