### ISSUE TITLE
[Spike] New sidebar for loopback.io

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#5295]
There are missing gaps in LB4 docs. Some are due to lack to content, and some due to inefficient organization. This spike is for reorganizing the sidebar to be more efficient and identify possible missing topics.

**Acceptance criteria**

- [ ] Create a new structure for the sidebar 
- [ ] Identify topics to cover

**Comment by dhmlau** [comment]
Related to: https://github.com/strongloop/loopback-next/issues/5113

**Comment by bajtos** [comment]
Some of the sidebar reorganization was done in https://github.com/strongloop/loopback-next/pull/5718. I think we need to revisit the new sidebar, decide what other changes we want to make and update the acceptance criteria.

**Comment by dhmlau** [comment]
After the high level refactoring of the sidebar items, there are separate issues tracking the "lower level" sidebar menu. See #5961 and #5776. Closing this issue as the previously mentioned GH issues seem to be a better approach.
