### ISSUE TITLE
HasAndBelongsToMany relation

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#5297]
## Implementation
I have been trying to understand the flow of data through the LoopBack relationships for a couple of days

Well, with that said I have started testing and open this thread to discuss it a bit.

![9830483](https://user-images.githubusercontent.com/13822438/80735453-fd157180-8b10-11ea-9a6b-05b27ea91b51.png)

Seeing this sketch of LB3, I conclude that the intermediate model (AssemblyPart) should not be defined and therefore it had to be built within the relationship code.

Looking at the link below, `model` will become type `string` that would contain the model name
https://github.com/frbuceta/loopback-next/blob/feat/has-and-belongs-to-many/packages/repository/src/relations/relation.types.ts#L119-L152

What would be your opinion? @strongloop/loopback-maintainers

## Acceptance criteria

TBD - will be filled by the team.

**Comment by agnes512** [comment]
Thanks for the information! But I have to close it as we already have the issue opened https://github.com/strongloop/loopback-next/issues/2308. Thanks again.
