### ISSUE TITLE
Documentation for Migrating LB3 Tests Mounted on an LB4 App

### ISSUE THREAD

**Issue by nabdelgadir** [strongloop/loopback-next#5298]
Followup for https://github.com/strongloop/loopback-next/pull/5251. Related issue: https://github.com/strongloop/loopback-next/issues/3978.

Add documentation instructing users how to migrate their LB3 tests after they mount their LB3 app on an LB4 project.

## Acceptance criteria

- [ ] Create a section in [lb3-application's README](https://github.com/strongloop/loopback-next/tree/master/examples/lb3-application) for migrating tests
  - [ ] Describe what needs to be done before running the tests (e.g. adding lb3 directory to `npm test` command)
  - [ ] Describe how to migrate acceptance tests
  - [ ] Describe how to migrate integration tests

**Comment by jannyHou** [comment]
Closing after #5403 merged.
