### ISSUE TITLE
Bind Mounted LB3 Models to LB4 Context

### ISSUE THREAD

**Issue by nabdelgadir** [strongloop/loopback-next#5299]
Follow-up for https://github.com/strongloop/loopback-next/pull/5251.

In order to allow users to run integration tests, bind the LB3 models to the LB4 app's context.

## Acceptance criteria

- [x] Add a property `models` to `Lb3Application` interface
- [x] When the LB3 application is loaded, add the models to LB4 context
- [x] Add test(s) to verify

**Comment by jannyHou** [comment]
Closing after PR merged 🎉
