### ISSUE TITLE
Different initial migration experience from current

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#53]
https://github.com/strongloop/loopback/issues/591#issuecomment-280133927

I see this come up a lot, like how you have to "extend built in user model" + "automigrate the ACL, Role, etc" tables. We need a better experience than this (not to mention good docs up front if we're going to leave a bad experience like this for people just getting started).

**Comment by bajtos** [comment]
Closing in favour of https://github.com/strongloop/loopback-next/issues/487.
