### ISSUE TITLE
repository: Entity should construct the object

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#530]
Entity should support functionality of assigning data to Instance through super. 

> it would be nice if `Entity` constructor supported this use case OOTB, so that we could call `super(body)`.

Originally found here: https://github.com/strongloop/loopback-next-example/pull/70#discussion_r133905875

**Comment by dhmlau** [comment]
@virkt25 , could you please add the acceptance criteria so that the team can estimate this week or next?  Thanks!

**Comment by virkt25** [comment]
Closing as resolved. 

From the original PR, we were doing the following: 
https://github.com/strongloop/loopback4-example-microservices/blob/master/services/account-without-juggler/repositories/account/models/Account.ts#L18-L23

Which looking at the latest implementation of `Entity` class which extends `Model`, there is no need to use `Object.assign()` as `Entity` supports `super(data)` as demonstrated in the following implementation: 

https://github.com/strongloop/loopback-next/blob/master/examples/todo/src/models/todo.model.ts#L43-L45
