### ISSUE TITLE
Add Example LB3 Tests to lb3-application

### ISSUE THREAD

**Issue by nabdelgadir** [strongloop/loopback-next#5300]
Follow-up for https://github.com/strongloop/loopback-next/pull/5251.

To demonstrate migration of LB3 tests when it is mounted on an LB4 application, add example LB3-style tests to `lb3-application`.

## Acceptance criteria

- [ ] Add example acceptance tests
- [ ] Add example integration tests (blocked by https://github.com/strongloop/loopback-next/issues/5299)
- [ ] Add example authentication tests

**Comment by jannyHou** [comment]
Closing after #5403 merged.
