### ISSUE TITLE
Many Auth on same method.

### ISSUE THREAD

**Issue by madaky** [strongloop/loopback-next#5310]
```
@authenticate(['basicAuth', 'localAuth']) // We allow either basic or local auth
```
As mentioned in :@authenticate(['basicAuth', 'localAuth']) // We allow either basic or local auth
by @raymondfeng 
Is this has been implemented. If not can we put in feature-list?

**Comment by jannyHou** [comment]
@madaky 

I think this is not supported yet, see the decorator's [first parameter](https://github.com/strongloop/loopback-next/blob/master/packages/authentication/src/decorators/authenticate.decorator.ts#L32), and the strategy provider [only searches for one name](https://github.com/strongloop/loopback-next/blob/master/packages/authentication/src/providers/auth-strategy.provider.ts#L41)

Agreed that it's labelled as a feature.

**Comment by achrinza** [comment]
@jannyHou Would this be considered a duplicate of / related to #4842?
