### ISSUE TITLE
Add "signup" / create user in authentication-jwt module

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#5312]
## Suggestion

In the `authentication-jwt` extension, the user experience would be much nicer if it includes the default implementation for creating user as well. 

I'm trying to use this extension in my app, and I'd also want to have the "signup" REST API. In order to do that, I need to (I'm still in the middle of it, so the list may not be complete):
- add the signup endpoint in the UserController

cc @jannyHou @raymondfeng 

## Acceptance criteria

- [ ] Add the signup demo in the [controller test fixture](https://github.com/strongloop/loopback-next/tree/master/extensions/authentication-jwt/src/__tests__/fixtures)

**Comment by jannyHou** [comment]
@dhmlau Agreed 👍

**Comment by dhmlau** [comment]
For your reference, i've added the signup endpoint in my repo: https://github.com/dhmlau/loopback4-example-todo-jwt/.

**Comment by dhmlau** [comment]
Resolved via https://github.com/strongloop/loopback-next/pull/5763. Closing as done.
