### ISSUE TITLE
when undefined is passed to repository.updateById as id value, it executes an update on all rows.

### ISSUE THREAD

**Issue by hazimdikenli** [strongloop/loopback-next#5319]
## Steps to reproduce

get a repository instance.
Call updateById with the undefined as id parameter.
it will execute an update on all rows.

`    //create table
    await this.repo.execute('CREATE TABLE mymodel (col1 TEXT)', []);

    //populate data
    await this.repo.execute(
      `insert into mymodel(col1) values ('a'),('b'),('c');`,
      [],
    );

    const all = await this.repo.find();
    const first = all[0];
    first.col1 =
      'meant to change one row, but passed in undefined to updateById as id, and now all rows are updated.';
    await this.repo.updateById(undefined, first);
    const newRows = await this.repo.find();
    console.log(newRows);
`
the output should be something like;
[ {  "rowid": 1,
    "col1": "meant to change one row, but passed in undefined to updateById as id, and now all rows are updated."  },
  {  "rowid": 2,
    "col1": "meant to change one row, but passed in undefined to updateById as id, and now all rows are updated."  },
  {   "rowid": 3,
    "col1": "meant to change one row, but passed in undefined to updateById as id, and now all rows are updated."  }
]

## Current Behavior

As a result, it executes an DefaultCrudRepository.updateAll on the entire table.
## Expected Behavior

Nothing to be updated, as a row with that ID does not exist, or it can throw an error saying that id cannot be undefined.

## Link to reproduction sandbox

https://github.com/hazimdikenli/repobug
## Additional information

darwin x64 12.16.3

repobug@1.0.0 /Users/hazimdikenli/learn/loopback/repobug
├── @loopback/boot@2.1.2
├── @loopback/context@3.6.0
├── @loopback/core@2.4.2
├── @loopback/openapi-v3@3.3.0
├── @loopback/repository@2.3.0
├── @loopback/rest@3.3.2
├── @loopback/rest-explorer@2.1.2
├── @loopback/service-proxy@2.1.2
├── loopback-connector-sqlite3@3.0.0
## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by hazimdikenli** [comment]
I had this issue with postgres, but I used sqlite for simplicity.

**Comment by emonddr** [comment]
@hazimdikenli , any reason why you are using repo.execute(raw sql) instead of using the your model with a repository (created from `lb4 repository`) which handles all the crud functions for your model and uses the appropriate sql behind the scenes via a connector?

**Comment by emonddr** [comment]
e.g. repo.add(mymodel) : https://github.com/strongloop/loopback-next/blob/fc544c3dba71f543ec912c1b0ab174db4bd11952/examples/todo/src/controllers/todo.controller.ts#L61 or repo.updateById(id, mymodel) https://github.com/strongloop/loopback-next/blob/fc544c3dba71f543ec912c1b0ab174db4bd11952/examples/todo/src/controllers/todo.controller.ts#L130 ?

**Comment by hazimdikenli** [comment]
> @hazimdikenli , any reason why you are using repo.execute(raw sql) instead of using the your model with a repository (created from `lb4 repository`) which handles all the crud functions for your model and uses the appropriate sql behind the scenes via a connector?

Thank you @emonddr for pointing that out. I am not using execute raw sql on my real application, I just used it to set up data quickly to showcase the bug (or unexpected behaviour). The project I had this issue uses repo.create or repo.creatAll, and as I said this is just to set up a project quickly where it is possible to see the issue on hand. Fix is is pretty easy but I dont have the time to go setup the project and the environment and then to generate a pull request. It is as easy as adding an argument check to the mentioned function on legacy-juggler-bridge.ts
