### ISSUE TITLE
Loopback CLI not working. Installation seem to go through with success. However, the CLI just hangs when trying to create a project with 'lb4 ...'

### ISSUE THREAD

**Issue by netlander** [strongloop/loopback-next#5325]
## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@netlander, could you please provide more information on:
- node.js version
- OS and version
- are you using nvm?

Thanks.

**Comment by netlander** [comment]
OS: Win 10 (dev)
Using NVM
And tried two node versions with the same behaviour, namely 12.16.3 & 14.0.0 
Thanks

**Comment by dhmlau** [comment]
I've tried the run `lb4 app` command on my windows machine, with both  12.16.3 & 14.0.0, and it seems to be running fine.  

There's a [discussion thread](https://github.com/strongloop/loopback-next/issues/2569#issuecomment-542280415) about the problem related to Node.js 10 and higher but it seems like the issue no longer exist.  @netlander, perhaps apply the latest Windows updates if you haven't done so? 

@bajtos @dougal83, any insights?

**Comment by dougal83** [comment]
No idea.  I've never touched NVM and lb4 works fine for me too.  I can try reinstall later if I find a moment to look into it.

I tend to just install latest stable nodejs and use https://www.npmjs.com/package/npm-windows-upgrade to manage npm.  No problemo.

**Comment by achrinza** [comment]
I've not been able to reproduce the issue form my end.

```
Windows 10 1909
node@12.16.3
npm@6.14.4
@loopback/cli@2.6.0
```

**Comment by dougal83** [comment]
@netlander Can you give any more information that may be relevant?  Can you please try running lb4 with elevated permissions (cmd/ps run as administrator)?

**Comment by netlander** [comment]
@dougal83 Thanks for the suggestion, that did it, at least I get a prompt asking for a project name.
Thanks everybody else for your input, (un)fortunately I am not ready to update Win 10 at this point.
