### ISSUE TITLE
problems running the login passport example

### ISSUE THREAD

**Issue by chavitodb88** [strongloop/loopback-next#5340]
Hello, I am trying to launch the login example with passport as the documentation says but it seems not to be available.

Try `lb4 example passport-login`  I get this

Generation ended abnormally: Invalid sample name: passport-login
The example has been cloned to undefined.

run "lb4 example --help" to print the list of available sample names.

run `lb4 example --help` but the example passport-login does not appear in the list

Is there any other way to download this example?
I have also tried to download the entire repository and then just launch the passport-login example.

after an `npm install` and `npm start` I get the following error

`../../packages/testlab/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/http-caching-proxy/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/openapi-spec-builder/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/metadata/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/context/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/core/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/repository/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/repository-json-schema/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/openapi-v3/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/http-server/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/rest/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/security/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/authentication/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/model-api-builder/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/rest-crud/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/service-proxy/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/boot/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../packages/rest-explorer/tsconfig.json:3:14 - error TS6053: File '@loopback/build/config/tsconfig.common.json' not found.

3   "extends": "@loopback/build/config/tsconfig.common.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`

**Comment by dhmlau** [comment]
@chavitodb88, thanks for reporting this problem. We just fixed this issue via https://github.com/strongloop/loopback-next/pull/5334, it will be available when we publish a new release. 
For now, the workaround is to git clone the loopback-next repo and the example can be found under examples/passport-login. Here is the URL: https://github.com/strongloop/loopback-next/tree/master/examples/passport-login.

**Comment by dhmlau** [comment]
Fixed in the latest release. Please install `@loopback/cli` and try again. Thanks.

**Comment by jgutix** [comment]
@chavitodb88 seems to be that `npm install` needs to be done in the root, then `cd` into the example and `npm start`
