### ISSUE TITLE
Extension: Add Authorization component

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#538]
Related to https://github.com/strongloop/loopback-next/issues/512

- decoration at controller/method level may not be flexible enough
- URL-based rules as an alternative
- fine-grained access control on per-model-instance basis - ideally solved at Repository level
- local User/AccessToken auth scheme and models
- ACL/Role-based rules vs. scope-based rules
- JWT
- OAuth

**Comment by dhmlau** [comment]
Marking as `Core-GA` per our discussion.

**Comment by elv1s** [comment]
Is there going to be a `User` and `Role` model included in the authorization framework, or will that be provided by the app?

Will the framework concern be annotation on the controllers to describe authorized roles per path/verb?

**Comment by jannyHou** [comment]
I would proposal we provide built-in `User` and `Role` models and allow app developers replace them.

**Comment by raymondfeng** [comment]
> Is there going to be a User and Role model included in the authorization framework, or will that be provided by the app?

At the moment, we don't have a plan to have built-in User/Role models. There are probably some interfaces to capture the basic requirements for such entities if necessary.

> Will the framework concern be annotation on the controllers to describe authorized roles per path/verb?

I expect to have decorators to allow developers express their authorization requirements at controller class/method level.

**Comment by bajtos** [comment]
+1 to for leaving out User/Role models from the core authorization framework. In my experience from LB3, built-in User/Role models were difficult to maintain and very often not flexible enough to support different real-world use cases.

However, I think it probably makes sense to provide a standalone package offering a minimal implementation of User & Role models for demonstration purposes. LB4 users can then use this minimal implementation to build their own User & Role classes.

**Comment by samarpanB** [comment]
@bajtos We did implement a separate authorisation component in our first lb4 application. It was implemented as decorators at method level in controllers. The permissions were picked from access token (JWT). The implementation was not as vast as mentioned here, but it was good workable solution for us. If there is any way I can help/contribute to this task, please do let me know. I can share our implementation if needed. But it was more or less following the same guidelines mentioned [here](https://github.com/strongloop/loopback-next/blob/master/packages/authentication/README.md) for authentication component. These guidelines were really helpful.

**Comment by dhmlau** [comment]
@samarpanB, I think that would be helpful if you could add documentation on how to create such component.  
I'm thinking to add `LoopBack Component` > `Authorization` on the sidebar where the content from @samarpanB will be on that page.  
Thoughts, @samarpanB @strongloop/loopback-maintainers?

**Comment by dhmlau** [comment]
Related:
@osmanmesutozcan has created an extension https://github.com/xanthous-tech/loopback-4-accesscontrol (mentioned in https://github.com/strongloop/loopback-next/issues/2254)

**Comment by samarpanB** [comment]
@dhmlau Sure. That's a good idea. I'll put that documentation up. Can you please help me with where to start ? I think https://github.com/strongloop/loopback-next/tree/master/docs/site is the place where all pages md files are kept. So I need to create a new one here, right ?

**Comment by dhmlau** [comment]
@samarpanB , you're right.  For sidebar, it's from https://github.com/strongloop/loopback-next/blob/master/docs/site/sidebars/lb4_sidebar.yml.  Thanks!

**Comment by samarpanB** [comment]
@dhmlau added documenation in above PR. Please have a look.

**Comment by lvlinh961** [comment]
Hi everone,

I want to check whether user loged in berfore check I check his/her permission, I dont want to add "@authenticate" decorator to method when i added "@access" decorator to it (option configure the access control). How can I do that.

**Comment by samarpanB** [comment]
@raymondfeng I was trying to look for the doc page on https://loopback.io/doc/en/lb4/Using-components.html. But it’s not there yet. Is it not yet moved there ? As per my understanding, there is a daily job which moves it there.

**Comment by raymondfeng** [comment]
We need to publish a release to npm 1st.

**Comment by raymondfeng** [comment]
@samarpanB I just made a release. The document site will be updated soon.

**Comment by dhmlau** [comment]
@samarpanB, it's up: https://loopback.io/doc/en/lb4/Loopback-component-authorization.html.  Thanks for your contribution!

**Comment by dougal83** [comment]
Thanks for your work @samarpanB.  I've just been looking at your implementation.

As a comment I note that you've currently implemented named roles such as 'CreateRoles'.  Could I ask if you considered using the format "subject.action" namely roles.create or roles.write much like [implementations of scopes](https://api.slack.com/scopes)?  Personally I'd find an implementation based on [oath scopes](https://api.slack.com/docs/oauth-scopes) more logical to follow and more familiar as I've handled JWT access in such a manner.

Just food for thought as usage of scope like authorization schemas makes sense to me personally.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/pull/1205

**Comment by dhmlau** [comment]
Closing as done.
