### ISSUE TITLE
[Authentication passport] tests in an index file?

### ISSUE THREAD

**Issue by mdbetancourt** [strongloop/loopback-next#5380]
https://github.com/strongloop/loopback-next/blob/06d3a1f4e63c119766e75c9ff9073fa5ef912a2f/extensions/authentication-passport/src/index.ts#L8
Hello. when i try run the loopback passport example throw an error because this line, also this package is in extension folder shouldn't be called "@loopback/extension-authentication-passport"?

**Comment by achrinza** [comment]
> when i try run the loopback passport example throw an error

Could you please clarify the following:

1. **Step-by-step** instructions on how to replicate the issue
2. What is the actual, exact error?

> shouldn't (it) be called "@loopback/extension-authentication-passport"?

See https://github.com/strongloop/loopback-next/pull/5240#discussion_r414998370 for the rationale behind the naming convention.

**Comment by mdbetancourt** [comment]
I didn't anything special just follow the readme file, when I tried run node . Or yarn start throw an error because but found that test files

**Comment by ivan-rangel** [comment]
Same error here, the app does not even start due to this issue, please see:
https://i.imgur.com/b1NAWAt.png & https://i.imgur.com/D48Cgts.png

This is the version what I am using:
`"@loopback/authentication-passport": "^2.1.3"`

Thanks

**Comment by raymondfeng** [comment]
The example is broken as the `./__tests__/acceptance/fixtures/mock-oauth2-social-app` is not published to npm by `@loopback/authentication-passport`.

**Comment by raymondfeng** [comment]
For now, you have to check out `loopback-next` git repo and run the example there.

**Comment by deepakrkris** [comment]
fix in PR : https://github.com/strongloop/loopback-next/pull/5386
