### ISSUE TITLE
No valid exports main found for node_modules\uuid

### ISSUE THREAD

**Issue by rhiwn** [strongloop/loopback-next#5381]
Hi, I just updated my project using npm -update @loopback/cli and lb4 update.
No errors on build but when I start I get this.

Error: No valid exports main found for 'C:\repos\new client and server\api\node_modules\uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\repos\new client and server\api\node_modules\@loopback\context\src\value-promise.ts:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)

Is there anything simple I'm missing?

Thanks

**Comment by raymondfeng** [comment]
Pls remove node_modules, run npm install, and try again.

**Comment by rhiwn** [comment]
thanks, tried that, same issue.

**Comment by raymondfeng** [comment]
What do you see with `npm ls uuid`?

**Comment by rhiwn** [comment]
contacttlesscommerce@1.0.1 C:\repos\new client and server\api
+-- @loopback/build@5.3.1
| `-- nyc@15.0.1
|   `-- istanbul-lib-processinfo@2.0.2
|     `-- uuid@3.4.0 
+-- @loopback/context@3.7.0
| `-- uuid@8.0.0  deduped
+-- @loopback/repository@2.4.0
| `-- loopback-datasource-juggler@4.21.1
|   +-- loopback-connector@4.11.0
|   | `-- uuid@7.0.3
|   `-- uuid@7.0.3
`-- uuid@8.0.0

thanks

**Comment by raymondfeng** [comment]
That seems to be good. What about `npm ls @loopback/context`?

**Comment by raymondfeng** [comment]
There was a similar issue - https://github.com/facebook/flipper/issues/1144.

I cannot reproduce it. Do you have a simple git repo?

**Comment by rhiwn** [comment]
+-- @loopback/authentication@4.2.3
| +-- @loopback/context@3.7.0  deduped
| `-- @loopback/security@0.2.8
|   `-- @loopback/context@3.7.0  deduped
+-- @loopback/authorization@0.5.8
| `-- @loopback/context@3.7.0  deduped
+-- @loopback/boot@2.2.0
| `-- @loopback/context@3.7.0  deduped
+-- @loopback/context@3.7.0
+-- @loopback/core@2.5.0
| `-- @loopback/context@3.7.0  deduped
+-- @loopback/openapi-v3@3.3.1
| `-- @loopback/repository-json-schema@2.4.0
|   `-- @loopback/context@3.7.0  deduped
+-- @loopback/repository@2.4.0
| `-- @loopback/context@3.7.0  deduped
+-- @loopback/rest@4.0.0
| +-- @loopback/context@3.7.0  deduped
| `-- @loopback/express@1.1.0
|   `-- @loopback/context@3.7.0  deduped
+-- @loopback/rest-explorer@2.2.0
| `-- @loopback/context@3.7.0  deduped
`-- @loopback/service-proxy@2.2.0
  `-- @loopback/context@3.7.0  deduped

thanks

**Comment by raymondfeng** [comment]
Hmm, maybe you can try the following:
```sh
node
Welcome to Node.js v12.16.3.
Type ".help" for more information.
> const uuid = require('@loopback/context').uuid
undefined
> uuid()
'c8be5b85-cd49-490a-8e83-728686582feb'
>

**Comment by rhiwn** [comment]
Welcome to Node.js v13.5.0.
Type ".help" for more information.
> const uuid=require('@loopback/context').uuid
Uncaught:
Error: No valid exports main found for 'C:\repos\new client and server\api\node_modules\uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  code: 'MODULE_NOT_FOUND'
}

thanks

**Comment by raymondfeng** [comment]
Node.js 13.5.0 seems to be broken. I tried 13.14.0 and 14.2.0. Both of them work.

Please note you should use Node.js even versions for production. We support Node 10, 12, and 14.

**Comment by rhiwn** [comment]
thankyou :)

**Comment by mllrdev-raphael-dearce** [comment]
Hello.
Followed everything here. But I'm still getting the uuid error. Can anyone help me?

![ConEmu64_7KdpAprJrK](https://user-images.githubusercontent.com/56951197/84649612-64f50f80-af39-11ea-85c8-1ded96b493cc.png)

**Comment by rhiwn** [comment]
See comment from Raymond re node support - 10, 12, 14 - have you tried with
ones of these versions?

**Comment by mllrdev-raphael-dearce** [comment]
From what I've understood with his comment, he's referring to the even versions, i.e., 13.14.0, 14.2.0. I'm using 13.6.0.

**Comment by achrinza** [comment]
Even versions as in Node.js 10, 12, 14. Node.js 13 is not supported.

**Comment by mllrdev-raphael-dearce** [comment]
Updated to node v14 now. Everything seems to be working. Thank you all for your responses.

**Comment by GeovaniSorio** [comment]
Resolvi o meu problema com a atualização do nod para a versão 14.

**Comment by nawaazwill11** [comment]
> Node.js 13.5.0 seems to be broken. I tried 13.14.0 and 14.2.0. Both of them work.
> 
> Please note you should use Node.js even versions for production. We support Node 10, 12, and 14.

The same issue with version 13.1.0. Upgraded to 14.5.0. That solved it. Thanks!

**Comment by Guanhua1018** [comment]
just update the node version to even one, then the issue will be solved.
