### ISSUE TITLE
ModelDefinition helpers for defining relations

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#5384]
_Moved from [my comment](https://github.com/strongloop/loopback-next/pull/5358/files/da9a530d408a4199fb9c51895df35397530ab846#r421315010) in #5358_

Building relations using `ModelDefinition` API is too involved at the moment, the user has to specify metadata that can be automatically inferred from the relation type.

For example:

```ts
static definition = new ModelDefinition('Order')
  .addRelation(<BelongsToDefinition>{
    name: 'customer',
    type: RelationType.belongsTo,
    targetsMany: false,
    source: Order,
    target: () => User,
    keyFrom: 'customerId',
  });
```

## Suggestion

Provide higher-level builders for each individual relation type.

For example:

```ts
new ModelDefinition('Order')
  .belongsTo('customer', {
    source: Order,
    target: () => User,
    keyFrom: 'customerId', // can we infer this value?
  });
```

## Acceptance criteria

Implementation, tests and TSDOC API docs for all built-in relation types.

 - [ ] belongsTo 
 - [ ] hasOne 
 - [ ] hasMany 
 - [ ] embedsOne 
 - [ ] embedsMany 
 - [ ] referencesOne 
 - [ ] referencesMany 

Based on the list of relation types as of 2020-05-11:

https://github.com/strongloop/loopback-next/blob/4cc8eba853232213f9f82408568587d81103142e/packages/repository/src/relations/relation.types.ts#L11-L19

**Comment by jimmy1wu** [comment]
hello, i am a first time contributor to loopback. can i take this issue?

**Comment by hacksparrow** [comment]
@jimmy1wu sure! Looking forward to the PR.

**Comment by jimmy1wu** [comment]
@hacksparrow hello, i created a draft PR https://github.com/strongloop/loopback-next/pull/5742 if you wanted to provide some early feedback. I still have to write the tests. Also, the acceptance criteria mentions some relations that i don't think are implemented yet (only belongsTo, hasOne, and hasMany have been implemented)
