### ISSUE TITLE
Feature: Offline first synchronization built in.

### ISSUE THREAD

**Issue by delebash** [strongloop/loopback-next#540]
In loopback 3 you have offline sync abilities.  I think being able to have two way sync from local to remote database is very important.  At least for me :)

[PouchDB ](https://pouchdb.com/)is a good example of offline first synchronization

Another example not reliant on CouchDB is [DexieJs](http://dexie.org/)  seems like they have a nice synchronization component built in and are nearing version 2.0 release

**Comment by bajtos** [comment]
Hello, I am afraid we are not going to have time to work on this in the next 6-9 months. However, we are happy to accept a pull request contributing this feature.
