### ISSUE TITLE
how we can add login method in usercontroller class in loopback4 API? needs more clarification on this

### ISSUE THREAD

**Issue by kanusoni** [strongloop/loopback-next#5407]
Hello,
I have created User controller in loopback4 Explorer but i need login method for JWT authentication.
Whatever is written in loopback.io tutorial is bit confusing so do you have any other tutorial for the clarification.

**Comment by kanusoni** [comment]
Hello,
I have created User controller in loopback4 Explorer but i need login method for JWT authentication.
Whatever is written in loopback.io tutorial is bit confusing so do you have any other tutorial for the clarification.

**Comment by dougal83** [comment]
Please find a working example below:

````ts
  @post('/users/login', {
    responses: {
      '200': {
        description: 'Token',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                token: {
                  type: 'string',
                },
              },
            },
          },
        },
      },
    },
  })
  async login(
    @requestBody(CredentialsRequestBody) credentials: Credentials,
  ): Promise<{token: string}> {
    // ensure the user exists, and the password is correct
    const user = await this.userService.verifyCredentials(credentials);


    // convert a User object into a UserProfile object (reduced set of properties)
    const userProfile = this.userService.convertToUserProfile(user);


    // create a JSON Web Token based on the user profile
    const token = await this.jwtService.generateToken(userProfile);


    return {token};
  }
}
````
From [example shopping](https://github.com/strongloop/loopback4-example-shopping/blob/04c53e37c6fb647ba5deaa6bad6437549239b47b/packages/shopping/src/controllers/user.controller.ts#L234-L267).  Hope that helps.

**Comment by kanusoni** [comment]
yes, i have tried this...but i am getting errors.
The variables that you are using like (Credentials, userservice, jwtservice) where we need to define this in our application

Error is like:-
Parameter 'credentials' of public method from exported class has or is using private name 'Credentials'.

Property 'userService' does not exist on type 'UserController'.

**Comment by dougal83** [comment]
@kanusoni Please take a closer look at the Shopping example and follow the breadcrumbs (look at [Constructor](https://github.com/strongloop/loopback-next/issues/5101#issuecomment-613189957) that instantiates services and follow the imports to find their implementation.  It takes time to familiarise yourself but it is worth it if the tutorial does not suit you.

**Comment by kanusoni** [comment]
@dougal83 okay Thanks

**Comment by dhmlau** [comment]
@kanusoni, we recently published an extension called `@loopback/authentication-jwt`, this might make adding jwt authentication eaiser: https://github.com/strongloop/loopback-next/tree/master/extensions/authentication-jwt. 

While learning how to use this extension, I created this blog: https://medium.com/@MobileDiana/add-jwt-authentication-in-your-loopback-4-application-325137642c2c. Hope this helps.

**Comment by kanusoni** [comment]
@dhmlau Thanks Diana for you reply. 
The blog which has been mentioned in above comment section is really helpful. now i am able to create both login and signup method in usercontroller class.
Thanks Again for publishing this blog.

**Comment by kanusoni** [comment]
@dhmlau can you help me out in the below issue:-
while i am signing in loopback4 explorer with credentials email: foo@bar.com and password: foobar
i am getting error which is shown in screenshot.

![Screenshot (2)](https://user-images.githubusercontent.com/65274176/81930728-9a3ed280-9606-11ea-8c4b-97049c8b3923.png)

because of this issue JWT token is also not generating. 
your help will be appreciated. Thanks.

**Comment by deepakrkris** [comment]
@kanusoni please provide a sample project or sandbox to check your code

**Comment by dhmlau** [comment]
> @kanusoni please provide a sample project or sandbox to check your code

+1. From the error in the screen shot, it seems like the `password` was not specified. If it was specified and still got this error, it's the best if you can share your app. Thanks.

**Comment by kanusoni** [comment]
newlbapp.zip
<https://drive.google.com/file/d/1ydc8jzw3VRHhaQ_PGn1drz5FJZ3_qsaB/view?usp=drive_web>

**Comment by kanusoni** [comment]
@deepakrkris @dhmlau sent App to you. please check the code and let me know the solution.
Thanks.

**Comment by dougal83** [comment]
@kanusoni FYI it is much easier to use github to share your project. See [guide](https://kbroman.org/github_tutorial/pages/init.html) on making a repo from existing project. That gives helpful souls a single command line option to pull your project. Best of luck.

**Comment by kanusoni** [comment]
@dougal83  shared the code in github repo.

**Comment by dougal83** [comment]
@kanusoni I'm a little unsure how you've arrived at your implementation, it seems a little confused.  Are you following a particular tutorial?  It may be worth starting afresh following the tutorial mentioned above by Diana or use [Shopping Example](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/controllers/user.controller.ts#L66-L122) as a reference to patch up your current project and methodically inspecting models/controllers at this point.

That being said there are several issues:
Firstly you may wish to proceed to implement the credentials model repository as the password will not be stored following the advice below...

- [Comment out/remove password from user model](https://github.com/kanusoni/myrepo/blob/516b1257fdbae6353a2daac2d073fee4eebeebf2/src/models/user.model.ts#L18-L22)
- [Rename 'NewUser' to say 'duplicateNewUser'](https://github.com/kanusoni/myrepo/blob/516b1257fdbae6353a2daac2d073fee4eebeebf2/src/controllers/user.controller.ts#L99)  This will confuse the getModelSchemaRef() function as there are two instances named 'NewUser'.
- Change [these lines](https://github.com/kanusoni/myrepo/blob/516b1257fdbae6353a2daac2d073fee4eebeebf2/src/controllers/user.controller.ts#L283-L285) to the following: 
````ts
          schema: getModelSchemaRef(NewUserRequest, {
            title: 'NewUser',
            exclude: ['id','role']
          }),
````

I would highly recommend using the [Shopping Example](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/controllers/user.controller.ts) as a reference to patch up your work further.

Good luck.  Hope that helps a bit.

**Comment by kanusoni** [comment]
@dougal83 I followed this [https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/controllers/user.controller.ts](url) tutorial only.
and after changing the above mentioned lines, this is not working fine yet.

**Comment by kanusoni** [comment]
@dougal83 i followed this [https://github.com/strongloop/loopback4-example-shopping](url) tutorial only.
and after changes in above mentioned lines, this is not working fine yet.

**Comment by kanusoni** [comment]
@dougal83 i am following this [Shopping example](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/controllers/user.controller.ts) tutorial only. 
And After changing the above mentioned lines, its not working fine yet.
Thanks

**Comment by kanusoni** [comment]
@dhmlau any update from your side on the code which i sent to you?

**Comment by jannyHou** [comment]
@kanusoni I had a quick look of your repo, seems you don't secure any of your endpoints with `@authenticate()`, that's probably the issue.


FYI - https://github.com/strongloop/loopback-next/pull/5463 is the latest working example that demos JWT AUTH only. The shopping example shows a more complicated scenario so it has noisy code for other stuff.

And that example's corresponding tutorial doc https://github.com/strongloop/loopback-next/pull/5421.

Let me know if the latest example and tutorial still confuse you.

**Comment by HrithikMittal** [comment]
Hey @jannyHou Here my example can close this issue please do it if possible https://github.com/strongloop/loopback-next/issues/5573
https://github.com/strongloop/loopback-next/issues/5595

**Comment by jannyHou** [comment]
@HrithikMittal thanks! I think this issue is more like a question, and I think my comment above https://github.com/strongloop/loopback-next/issues/5407#issuecomment-632857905 points out the problem and provides a much easier tutorial to begin with authentication. 

I am closing it. Feel free to reopen the issue if you still have problem :)

**Comment by Arathy-sivan** [comment]
src/controllers/ctr-users.controller.ts:75:18 - error TS2345: Argument of type '{ description: string; required: boolean; content: { 'application/json': { schema: { type: string; required: string[]; properties: { login: { type: string; }; password: { type: string; minLength: number; }; }; }; }; }; }' is not assignable to parameter of type 'Partial<RequestBodyObject>'.
  Types of property 'content' are incompatible.
    Type '{ 'application/json': { schema: { type: string; required: string[]; properties: { login: { type: string; }; password: { type: string; minLength: number; }; }; }; }; }' is not assignable to type 'ContentObject'.
      Property ''application/json'' is incompatible with index signature.
        Type '{ schema: { type: string; required: string[]; properties: { login: { type: string; }; password: { type: string; minLength: number; }; }; }; }' is not assignable to type 'MediaTypeObject'.
          Types of property 'schema' are incompatible.
            Type '{ type: string; required: string[]; properties: { login: { type: string; }; password: { type: string; minLength: number; }; }; }' is not assignable to type 'ReferenceObject | SchemaObject | undefined'.
              Type '{ type: string; required: string[]; properties: { login: { type: string; }; password: { type: string; minLength: number; }; }; }' is not assignable to type 'SchemaObject'.
                Types of property 'type' are incompatible.
                  Type 'string' is not assignable to type '"string" | "number" | "boolean" | "object" | "integer" | "null" | "array" | undefined'.

75     @requestBody(CredentialsRequestBody) credentials: Credentials,
                    ~~~~~~~~~~~~~~~~~~~~~~


How to solve this error ??

**Comment by achrinza** [comment]
@Arathy-sivan Please ask in the Slack channel, StackOverflow with #loopback4 tag, or open a new GitHub issue

**Comment by raymondfeng** [comment]
See https://loopback.io/doc/en/lb4/changelog.openapi-v3.html#breaking-changes
