### ISSUE TITLE
Invalid link in documentation

### ISSUE THREAD

**Issue by JacquesBonet** [strongloop/loopback-next#5409]
## Steps to reproduce

I'm on the following page: https://loopback.io/doc/en/lb4/Email-connector.html

This display this content parts:

Creating an email data source
Create a new email data source with the[ data source generator:](https://loopback.io/doc/en/lb4/Data-source-generator.html)

The "data source gnerator " link is bad

More generally, the email documentation is not in sync with Loopback 4.0

**Comment by hacksparrow** [comment]
Related - https://github.com/strongloop/loopback-next/issues/4879

**Comment by dhmlau** [comment]
@JacquesBonet, thanks for reporting this.

For email connector, it actually won't work in LB4, please see the discussion in https://github.com/strongloop/loopback-next/issues/1979 for work around and potential documentation we can add. 

I'll use this issue to remove the email connector from the connector reference list in LB4.
