### ISSUE TITLE
core: Refactor app.controller() & app.component into a extension package

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#542]
# Description/Steps to reproduce
Currently `app.controller` is implemented in the core along with `app.component`. These functions provide no information to the core to do it's job but are sugar methods for bindings. As per my discussion with @raymondfeng this ticket is to refactor the two methods into an extension package so the core only deals with the underlying HTTP protocols for LB. They should be implemented similar to the proposed `app.repository()` implementation.

---
Original Notes from Discussion: 
- Component should be refactored out of the Application Core. REST Endpoint support should be it's own module and Core should be Application+Component+Abstraction of Sequence/Actions, etc. This should be independent of the underlying protocols.
- App.controller & app.repository should have same behaviour

**Comment by bajtos** [comment]
I believe this is no longer relevant, we agreed `controller` method should stay in the Application object, so that a single controller can be exposed via multiple transports (gRPC, REST).
