### ISSUE TITLE
Extensions Architecture

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#543]
# Description/Steps to reproduce
The current approach to a mixin extension may require implemented methods to be overridden by an extension developer. This can prove to be an issue if an extension developer doesn't call `super.method()` (unless it's intentional). 

The ticket is to discuss and explore the idea of having extension points in our application to make it easy for extension developers to create extensions. From my understand an example would be to automatically look for a function to handle a given extension point. For Ex: What functions / extensions can handle `repositories`. Call the appropriate registered extensions. What can handle `controllers`? 

---
Original Meeting Notes
- Explore idea of extension point and have a component loader to lookup and delegate extensions instead of extension overriding the method (EX: component() by repository.)

Related
https://github.com/strongloop/loopback-next/pull/541#issuecomment-325405714
https://github.com/strongloop/loopback-next/pull/541#discussion_r135665731

**Comment by bajtos** [comment]
I personally prefer the explicit approach where mixins override `app.components` method and call `super.component()`. IMO, this is the idiomatic way that should be familiar to any JavaScript/TypeScript developer, it's less code in loopback core for us to maintain and it avoids the situation where our "automagic" implementation does not support a specific use case and therefore we need to keep adding more and more code to this part of loopback core.

**Comment by raymondfeng** [comment]
To add some context, here is the description of `extension points/extensions` idea I borrow from Eclipse as a proven successful platform and ecosystem with many extensions. Visual studio code also uses a similar mechanism. 

https://wiki.eclipse.org/FAQ_What_are_extensions_and_extension_points%3F
https://code.visualstudio.com/docs/extensionAPI/patterns-and-principles

LoopBack Next components are roughly equivalent to Eclipse plugins.

With mixins, extension implementations need to have a dependency on the extension point. Extension developers are required to write code to stitch extension behaviors into the extension point logic by adding new methods or overriding existing ones. And that's repetitive for each extensions too. Individual extensions might not have enough knowledge to fully control how they fit into the extension point as extension point is not in charge of the coordination any more.

**Comment by raymondfeng** [comment]
In summary, we need to come up a consistent way to support the following pattern using rest servers as an example:

1. Rest component (extension point) manages multiple rest servers (extension).
2. Each rest server has a name and corresponding configuration (or `options`).
3. Rest component should be able to get a list of rest servers or look up one by name
4. Rest server should be able to receive injection of the configuration

**Comment by bajtos** [comment]
Labelling as post-ga. For 4.0 GA, we are starting with a different set of spikes - see https://github.com/strongloop/loopback-next/issues/1034
