### ISSUE TITLE
error starting example. Looks like missing file

### ISSUE THREAD

**Issue by noorix1** [strongloop/loopback-next#5473]
I installed the lb4 example passport-login
then did the steps as expected by npm i in the install directory

when i do npm start, the app won't start and gives the error:

Error: Cannot find module './__tests__/acceptance/fixtures/mock-oauth2-social-app'

I am using Ubuntu 20.04 with current versions of  NPM (6.14.4), node (14.2.0) and loopback 4

**Comment by dougal83** [comment]
Looks like duplicate, see #5380
