### ISSUE TITLE
Broken table of contents in changelogs

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#5474]
Auto-generated table of contents in change log pages is broken.

Take https://loopback.io/doc/en/lb4/changelog.core.html as an example:

<img width="633" alt="Screen Shot 2020-05-18 at 09 15 01" src="https://user-images.githubusercontent.com/1140553/82184519-1297e300-98e8-11ea-9f77-2f3ac335b6d9.png">

- There are no entries for versions `2.0.0`, `2.1.0` and `2.2.0`
- Subsections like `Features` and `BREAKING CHANGES` from the versions `2.0.0` to `2.2.0` are all nested under the TOC entry for `2.2.1`

The actual content is rendered correctly.

<img width="852" alt="Screen Shot 2020-05-18 at 09 16 37" src="https://user-images.githubusercontent.com/1140553/82184707-5db1f600-98e8-11ea-9405-8159a982577e.png">

**Comment by raymondfeng** [comment]
@bajtos The html page is rendered directly from `CHANGELOG.md`, which is automatically generated by `lerna version|publish`. See https://raw.githubusercontent.com/strongloop/loopback-next/master/packages/core/CHANGELOG.md. It seems to have patch versions as child items under a minor version.
