### ISSUE TITLE
bug in todo list tutorial

### ISSUE THREAD

**Issue by khlilturki97** [strongloop/loopback-next#5503]
in todo list tutorial, in [this step](https://loopback.io/doc/en/lb4/todo-list-tutorial-sqldb.html#specify-the-foreign-key-constraints-in-todo-model), foreignKey attribute should match the model field
```
@model({
  settings: {
    foreignKeys: {
      fk_todo_todoListId: {
        name: 'fk_todo_todoListId',
        entity: 'TodoList',
        entityKey: 'id',
        foreignKey: 'todolistid',
      },
    },
  },
})
```
here it's in lowercase, meanwhile the `lb4 model` command generates it in camelCase

**Comment by dhmlau** [comment]
For postgresql, all the column names are in lower case, so the `foreignKey` is mapping to the column name instead of the model name.

**Comment by khlilturki97** [comment]
Oh my bad thank you
