### ISSUE TITLE
Generated Controllers using openapi command

### ISSUE THREAD

**Issue by bobby91560** [strongloop/loopback-next#5510]
Hello,

I have used the command lb4 openapi that generated successfully all I wanted regards to my yaml configuration.
I just wanted to know if there was a way to separate all the description in the controller, representing by the decorator @api et @operations, in a different file, to have a more readable controller ?
Or a way to have something more cleaner ?

Thanks for your response

**Comment by dhmlau** [comment]
@raymondfeng, what do you think?

**Comment by bobby91560** [comment]
Did you think about a solution ?

**Comment by raymondfeng** [comment]
@bobby91560 Inlining big chunk of json objects for openapi specs is indeed noisy. Maybe one option is to save the spec into a json file and import it into the generated controllers. This way, we can just have to reference corresponding path of the json file for decorations.

**Comment by bobby91560** [comment]
Hello,

Sorry for my late response... 
That's what I've done finally, thank you !

**Comment by dhmlau** [comment]
Thanks @bobby91560 for your reply. Closing this issue.
