### ISSUE TITLE
Geo-coding tutorial missing import HttpErrors in todo.controller.ts

### ISSUE THREAD

**Issue by mattkennedynz** [strongloop/loopback-next#5518]
When following the bonus geo-coding tutorial in the docs, I wasn't able to get the server running due to missing `HttpErrors` in the `todo.controller.ts`

## Steps to reproduce

Complete the original todo tutorial, then follow the changes in [https://loopback.io/doc/en/lb4/todo-tutorial-geocoding-service.html#navigation](https://loopback.io/doc/en/lb4/todo-tutorial-geocoding-service.html#navigation)

## Current Behavior

When running npm, I encountered:

```
src/controllers/todo.controller.ts:53:27 - error TS2304: Cannot find name 'HttpErrors'.

53                 throw new HttpErrors.BadRequest(`Address not found: ${
```

## Additional information

Adding `HttpErrors` to the initial `@loopback/rest` import in the todo.controller solves this issue:

`import {
    del,
    get,
    getModelSchemaRef,
    HttpErrors,
    param,
    patch,
    post,
    put,
    requestBody
} from '@loopback/rest';`

**Comment by dhmlau** [comment]
@mattkennedynz, thanks for reporting this. Would you be interested in submitting a PR? Here is the reference: https://loopback.io/doc/en/lb4/submitting_a_pr.html. Thanks.

**Comment by mattkennedynz** [comment]
Thanks @dhmlau, but it's probably better someone else looks into this. I'm learning to code—and I don't know if there there was a `lb4 controller` configuration missed in the earlier tutorial which might have imported this for us.

**Comment by dhmlau** [comment]
See PR #5652
