### ISSUE TITLE
docs: Decorators for application developers

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#552]
IMO we need two types of content for decorators:
 - one targeting people using existing decorators to build their apps
 - another targeting people writing components.

[Writing components](https://github.com/strongloop/loopback-next/wiki/Writing-Components) should be covering the second group, we need a new page to cover the first (and larger!) group.

**Comment by crandmck** [comment]
Added stub page as placeholder: https://github.com/strongloop/loopback-next/wiki/Using-decorators

**Comment by kjdelisle** [comment]
We should make sure there's a section that describes all of the available decorators we provide with core, as a reference.

**Comment by bajtos** [comment]
> We should make sure there's a section that describes all of the available decorators we provide with core, as a reference.

It makes me wonder - can we automate this and provide the list of decorators as part of API docs?

**Comment by crandmck** [comment]
> can we automate this and provide the list of decorators as part of API docs?

+1.  Rather than just putting a list into the docs comments, it would be ideal if there were a doc comment directive (i.e. `@decorator`) for this. But that would require enhancing strong-docs AFAIK.

**Comment by bajtos** [comment]
>  Rather than just putting a list into the doc comments, it would be ideal if there were a doc comment directive (i.e. `@decorator`) for this. 

Yes please 👍

**Comment by crandmck** [comment]
Created an issue.  Now we just need to find someone to do the work.  Mahesh is the only person (other than Ritchie) who knows strong-docs, and he's been reassigned to Velox project.  

@bajtos If we want to prioritize this, please add this repo to sprint planning board, and review existing issues.  There are a couple others we might want to consider addressing as well.

**Comment by bajtos** [comment]
> Created an issue.

@crandmck thank you, here is a link to the issue for our future reference: https://github.com/strongloop/strong-docs/issues/97

> Now we just need to find someone to do the work. Mahesh is the only person (other than Ritchie) who knows strong-docs, and he's been reassigned to Velox project. IMO it would be good for someone else to know the codebase for this repo.
> 
> If we want to prioritize this, please add this repo to sprint planning board, and review existing issues. There are a couple others we might want to consider addressing as well.

Yeah, we need to figure this out. I am little bit familiar with strong-doc's code base too, but I think we should find more people who should learn to understand this repo, to avoid bottlenecks in the future.

cc @dhmlau @kjdelisle

**Comment by jannyHou** [comment]
Close issue after https://github.com/strongloop/loopback.io/pull/463 merged, thanks for everyone's  review and suggestions.
