### ISSUE TITLE
'npm start' on lb4 app fails with error "events_1.once is not a function"

### ISSUE THREAD

**Issue by SumanBandopadhyay** [strongloop/loopback-next#5546]
Facing issue while starting with the loopback 4 "getting-started" application.
All steps were followed as mentioned in the [link](https://loopback.io/doc/en/lb4/Getting-started.html#create-a-new-project) to set up a new lb4 application.

After the application got created, the 'npm start' was unable to start the application.
[Note: I did not make any change to the project after it was created.]

Below is the error after trying to start the application.
`npm start

> hello-world@1.0.0 restart ....\hello-world
> npm run build

> hello-world@1.0.0 build ....\hello-world
> lb-tsc

> hello-world@1.0.0 start ....\hello-world
> node -r source-map-support/register .

Cannot start the application. TypeError: events_1.once is not a function
    at HttpServer.start (....\hello-world\node_modules\@loopback\http-server\src\http-server.ts:121:11)
    at RestServer.start (....\hello-world\node_modules\@loopback\rest\src\rest.server.ts:954:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-world@1.0.0 start: `node -r source-map-support/register .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello-world@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ....\AppData\Roaming\npm-cache\_logs\2020-05-24T13_31_05_575Z-debug.log`

**Comment by raymondfeng** [comment]
What’s your node version? We require 10 or above.

**Comment by rokoo** [comment]
same issue with node v10.12.0, but after use v12.16.0 problem solved.

**Comment by raymondfeng** [comment]
The `once` method was added in: v11.13.0, v10.16.0. See https://nodejs.org/api/events.html#events_events_once_emitter_name. Please use Node.js 10.16.0 or later.

CC @bajtos

**Comment by SumanBandopadhyay** [comment]
> The `once` method was added in: v11.13.0, v10.16.0. See https://nodejs.org/api/events.html#events_events_once_emitter_name. Please use Node.js 10.16.0 or later.
> 
> CC @bajtos

Thanks. It worked. I had10.15.x version. I updated it and its working now.

**Comment by chirappa-vishnupriya** [comment]
Cannot start the application. TypeError: binding.on is not a function

I am using node 12 still i am facing this issue
