### ISSUE TITLE
RFC: Adopt the four-quandrant documentation system

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#5549]
I am proposing to adopt the documentation system described at https://documentation.divio.com and successfully used by [Django](https://www.djangoproject.com) and others, and reorganize our documentation along the following four directions:
1. Tutorials
2. How-to guides
3. Reference
4. Background/Key concepts/Discussion/Explanation

![Overview of the documentation system](https://documentation.divio.com/_images/overview.png)

> Documentation needs to include and be structured around its four different functions: tutorials, how-to guides, technical reference and explanation. Each of them requires a distinct mode of writing. People working with software need these four different kinds of documentation at different times, in different circumstances - so software usually needs them all, and they should all be integrated into your documentation.

You can also watch the talk from PyCon Australia 2017 where this system was explained: https://youtu.be/t4vKPhjcMZg

In this issue, I'd like to keep the discussion at high-level and reach consensus whether such documentation system is something we all agree to asses and if we decide to implement it, then we will be all following it going forward.

An example of an existing doc page that's mixing different directions:
- [Key concepts >> Server](https://loopback.io/doc/en/lb4/Server.html) is a mixture of 
  - Some Background explanation of what is a Server.
  - How-to guides for customizing CORS, configuring REST API Explorer, etc.
  - Reference of [`rest` options](https://loopback.io/doc/en/lb4/Server.html#rest-options)

## Next steps

- [x] Discuss the proposal and reach consensus on whether we want to pursue this direction or not. If yes:
- [ ] A spike story to identify the first few steps of what will become a longer journey. For example, how to re-arrange the sidebar and existing pages, where to keep reference guides (inside `docs` or as tsdoc comments in code?), etc.
- [ ] Many small stories to review each existing doc page and rework it to follow the new system - extract How-to guides, extract Reference material, rework Explanations, and so on.

**Comment by dhmlau** [comment]
@bajtos, I agree with you that some of our docs page are mixed with how-tos and explanation. 
Are you thinking of each page (if applicable) to have 4 sections, or there will be 4 categories in the docs? 

> small stories to review each existing doc page and rework it to follow the new system

+1

**Comment by raymondfeng** [comment]
@bajtos In addition to what you proposed, I would like all of us to think about the following perspectives:

- Persona (Platform developer, API developer, Microservice developers, Integration Developer)
- Usage scenarios (Expose REST APIs, Expose GraphQL, Expose gRPC, access databases, access existing services, enable authentication/authorization, Cloud native observability, Use third-party ORMs, schedule jobs, use Pub/Sub, ...)
- Architectural layering (How are different packages positioned in the LB story)

**Comment by bajtos** [comment]
The adoption process was started by #5718 and will continue in the following pull requests and issues:

- docs: extract how-to guides from "Server" page #5768
- docs: move "Reserved binding keys" to "Reference guides" #5775
- docs: move "Error handling" to "Error codes" in "Reference guides" #5784
- docs: move "db transactions" to "how-to guides" in sidebar #5779
- docs: improve the structure of "Behind the scenes" sidebar + find a better name #5776 
- docs: improve the structure of "Usage scenarios" (how-to guides) sidebar #5777 
- docs: move API references to tsdoc #5778 
- docs: move recipes to how-to guides #5783
- docs: find a better place for "Extending LoopBack 4" in the sidebar [SPIKE] #5785
- docs: untangle connector reference into reference, how-to guides and tutorials #5786 
- docs: add a high-level framework overview that's easy to find #5788 

Closing this issue as done.
