### ISSUE TITLE
docs: Model

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#555]
## Overview

Update the documentation on loopback.io for models (currently listed as Schemas: http://loopback.io/doc/en/lb4/Schemas.html)

## Acceptance Criteria
- [x] Rename the page to "Model".
- [x] Give an example of a Model in loopback 4.
- [x] Describe how to add JSON schema metadata to your models (use the given decorators)
- [x] Update "Thinking in LoopBack" to clarify the role of models in LoopBack and update example usage to reflect current state-of-the-art.

**Comment by shimks** [comment]
Currently looking through Best Practices with LoopBack (Thinking in LoopBack) and noticed a couple of things that may need to be taken care of:
- the general advocacy of top-down approach
  - should there be an issue for a rewrite of the article based on the supported bottom-up approach?
- there is a page based on using Dredd to test deprecated https://github.com/strongloop/loopback-next-hello-world
  - should there be a separate issue to rewrite this section with more relevant repository?
  - would not be relevant if the rewrite to bottom-up approach is agreed upon since it'll be deleted anyway

**Comment by bajtos** [comment]
> the general advocacy of top-down approach
> should there be an issue for a rewrite of the article based on the supported bottom-up approach?

For MVP, we are going to add a notice only - see https://github.com/strongloop/loopback-next/issues/796

For GA, we need to support and document both approaches (bottom-up and top-down). Here are few relevant issues I found - feel free to open a new one if neither of those is matching the task you have in mind:

 - https://github.com/strongloop/loopback-next/issues/835 Docs: Consistent example in Best Practices for different approaches
 -  https://github.com/strongloop/loopback-next/issues/734 [Docs] Top-down (swagger gen) app tutorial

(You can search of "top-down" and "bottom-up" to find other issues that may be related.)

> there is a page based on using Dredd to test deprecated https://github.com/strongloop/loopback-next-hello-world
> - should there be a separate issue to rewrite this section with more relevant repository?
> - would not be relevant if the rewrite to bottom-up approach is agreed upon since it'll be deleted anyway

We have a story to find a better solution than Dredd, see https://github.com/strongloop/loopback-next/issues/644

I agree the current situation, where our "Best practice" page is pointing to a deprecated example repo, is not ideal. Since loopback-next-hello-world is the only example showing top-down approach, and top-down is not part of MVP, I don't think we have any easy replacement for loopback-next-hello-world.

I am proposing to add a warning to the page mentioning Dredd to explain the status:
 - top-down approach is not fully supported yet
 - the text on this page is outdated and may not work out of the box
 - we will revisit this area after MVP release

@kjdelisle @dhmlau thoughts?

**Comment by shimks** [comment]
I think with adding a notice for the Dredd page (as well as Thinking in LoopBack as whole) we should include it as a task to do in #796. Seems like that's already a part of the task though, so I guess it was a little redundant for me to bring it up here.

**Comment by bajtos** [comment]
@shimks 
> I think with adding a notice for the Dredd page (as well as Thinking in LoopBack as whole) we should include it as a task to do in #796. Seems like that's already a part of the task though, so I guess it was a little redundant for me to bring it up here.

No worries, nobody is carrying the whole contents of our issue tracker in their head! I am glad you have noticed the problem while reviewing the documentation and started this discussion that allowed us to review what is planned around Dredd and ensure we have a task in our backlog to fix the issues you found.
