### ISSUE TITLE
Where to provide Auth JWT SECRET Key

### ISSUE THREAD

**Issue by HrithikMittal** [strongloop/loopback-next#5555]
I was trying to implement the JWT authentication and I am successful in doing that but I want to ask that we haven't provided any JWT Secret key. So is this is not needed in loopback4 (everything is handled internally.) or I am doing something wrong?
I was comparing it with this: https://www.npmjs.com/package/express-jwt

**Comment by HrithikMittal** [comment]
I also refer one of your developer repo to implement JWT token 
Repo link: https://github.com/dhmlau/loopback4-example-todo-jwt

**Comment by dougal83** [comment]
HI @HrithikMittal 
I'm not sure that example is complete, how did you find it?  Have you followed an [authentication tutorial](https://loopback.io/doc/en/lb4/Authentication-Tutorial.html)?  The example referred to in the aforementioned tutorial contains the secret in a [key bindings file](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/keys.ts).  Take a look and see if it answers your query.

**Comment by HrithikMittal** [comment]
Ya I got it thanks
