### ISSUE TITLE
Loopback 4 authorization allowing access to all type of users

### ISSUE THREAD

**Issue by pratikjaiswal15** [strongloop/loopback-next#5567]
I am following [this](https://www.npmjs.com/package/@loopback/authorization) article for implementing authorization in my app. The user with the admin role can perform certain operations that other users can't.

But it is not working. The controllers are accessible to all type of users

Here is the code

Thank you in advance

user model has a property called role
```

@property({
    type: 'string',
  })
  role?: string;
```
authorizer.ts

```
import {AuthorizationContext, AuthorizationDecision, AuthorizationMetadata, Authorizer} from '@loopback/authorization';
import {Provider} from '@loopback/core';

export class MyAuthorizationProvider implements Provider<Authorizer> {
  constructor() {}

  /**
   * @returns authenticateFn
   */
  value(): Authorizer {
    return this.authorize.bind(this);
  }

  async authorize(
    authorizationCtx: AuthorizationContext,
    metadata: AuthorizationMetadata,
  ) {
    const clientRole = authorizationCtx.principals[0].role;
    const allowedRoles = metadata.allowedRoles;
    return allowedRoles?.includes(clientRole)
      ? AuthorizationDecision.ALLOW
      : AuthorizationDecision.DENY;
  }
}
```

application.ts

```
//Other imports        
        import {MyAuthorizationProvider} from './services/try';
        import {AuthorizationComponent, AuthorizationDecision, AuthorizationOptions, AuthorizationTags} from '@loopback/authorization';

       constructor(options: ApplicationConfig = {}) {
       super(options);
      // other code
        let app = new Application()
    const data: AuthorizationOptions = {
      precedence: AuthorizationDecision.DENY,
      defaultDecision: AuthorizationDecision.DENY,
    };

    const binding = app.component(AuthorizationComponent);
    app.configure(binding.key).to(data);

    app
      .bind('authorizationProviders.my-authorizer-provider')
      .toProvider(MyAuthorizationProvider)
      .tag(AuthorizationTags.AUTHORIZER);
}
```

user.controller.ts
```

 @get('/users/count', {
    responses: {
      '200': {
        description: 'User model count',
        content: {'application/json': {schema: CountSchema}},
      },
    },
  })

  @authenticate('jwt')
  @authorize({allowedRoles: ['admin']})

  async count(
    @param.where(User) where?: Where<User>,
  ): Promise<Count> {
    return this.userRepository.count(where);
  }
```

**Comment by pratikjaiswal15** [comment]
Anyone please?

**Comment by hacksparrow** [comment]
@pratikjaiswal15 can you share a simple app reproducing the behavior?

**Comment by pratikjaiswal15** [comment]
Here it is https://github.com/pratikjaiswal15/loopbackauthrization. 
Authorization is not working. Access is allowed to all user roles.

**Comment by hacksparrow** [comment]
@pratikjaiswal15 I am not sure, but the README of https://www.npmjs.com/package/@loopback/authorization seems to be missing some info. @jannyHou can you confirm?

Using a component is not the only way to enable authorization. Take a look at the [LoopBack 4 Example app](https://github.com/strongloop/loopback4-example-shopping), how it implements authentication and authorization. Maybe you will find its way easier to understand and use.

Controllers like the `ProductController` just have to import a function `basicAuthorization` from [src/services/basic.authorizor.ts](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/services/basic.authorizor.ts), and add it in the list of `voters` [like this](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/controllers/product.controller.ts#L48):

```ts
@authorize({allowedRoles: ['admin'], voters: [basicAuthorization]})
```

The implementation of `basicAuthorization` is just for the demo, you can modify it according to your requirements any way you like.

**Comment by pratikjaiswal15** [comment]
Thanks for your reply. Now, I have copied the code of basic-authorizer from the shopping example in my app. But the userProfile contains only two fields id and name. Other fields like role or email are undefined. So, I am getting 401 every time.  But while issuing token in my custom service I had returned many fields.

Can you please help?
Thank you in advance


authorizer.ts
```
export async function basicAuthorization(
  authorizationCtx: AuthorizationContext,
  metadata: AuthorizationMetadata,
): Promise<AuthorizationDecision> {
  // No access if authorization details are missing
  let currentUser: UserProfile;
  if (authorizationCtx.principals.length > 0) {
    const user = _.pick(authorizationCtx.principals[0]
      , [
        'id',
        'name',
        'role',
        'email',
        'address'
      ]);

    console.log(user) // contains only id and name
    currentUser = {[securityId]: user.id, name: user.name, roles: user.role, email: user.email, address: user.address};
    console.log(currentUser)
  }
```

custom-service.ts

 ```
convertToUserProfile(user: User): UserProfile {

    let address = ''
    if (user.address) {
      address = user.address
    }

    const profile = {
      [securityId]: user.id!.toString(),
      name: user.name,
      id: user.id,
      email: user.email,
      role: user.role,
      address: user.address
    }

    //    console.log(profile)
    return profile
```

**Comment by pratikjaiswal15** [comment]
I have added try.ts file for authorization in services in repository https://github.com/pratikjaiswal15/loopbackauthrization.

**Comment by pratikjaiswal15** [comment]
@hacksparrow how to add property role in `AuthorizationContext.principals `?

**Comment by HrithikMittal** [comment]
I think now this issue can be closed @pratikjaiswal15 as we already solve this issue
https://github.com/strongloop/loopback-next/issues/5603
