### ISSUE TITLE
@loopback/cli - "RangeError: Maximum call stack size exceeded" using lb4 openapi

### ISSUE THREAD

**Issue by ohenning** [strongloop/loopback-next#5569]
When trying to generate models for my lb4 project from a fairly large openapi spec, i'm getting a call stack error. The spec can be found here: https://technicalmasterdata.xtk-dev.de/swagger/v1/swagger.json. I double checked the spec on https://editor.swagger.io/ and it seems to be semantically correct.
## Steps to reproduce
Run `lb4 openapi https://technicalmasterdata.xtk-dev.de/swagger/v1/swagger.json` within any lb4 project.

## Current Behavior
The command fails with the following error: "RangeError: Maximum call stack size exceeded"

## Expected Behavior
The command to not fail and the artifacts to generate.

## Additional information

- @loopback/cli version: 2.7.1
- OS: macOS version 10.14.6
- node: version 10.16.0
- loopback dependencies:
  - @loopback/authentication: ^4.2.5
  - @loopback/boot: ^2.3.1
  - @loopback/build: ^5.4.1
  - @loopback/context: ^3.8.1
  - @loopback/core: ^2.7.0
  - @loopback/metadata: ^2.1.5
  - @loopback/openapi-spec-builder: ^2.1.5
  - @loopback/openapi-v3: ^3.4.1
  - @loopback/repository-json-schema: ^2.4.2
  - @loopback/repository: ^2.5.1
  - @loopback/rest: ^5.0.1
  - @loopback/testlab: ^3.1.5
  - @loopback/docs: ^3.8.1
  - @loopback/example-hello-world: ^2.1.1
  - @loopback/example-log-extension: ^2.1.1
  - @loopback/example-rpc-server: ^2.1.1
  - @loopback/example-todo: ^3.4.1
  - @loopback/example-soap-calculator: ^2.2.1
  - @loopback/service-proxy: ^2.3.0
  - @loopback/http-caching-proxy: ^2.1.5
  - @loopback/http-server: ^2.1.5
  - @loopback/example-todo-list: ^3.2.1
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^2.2.2
  - @loopback/eslint-config: ^7.0.1
  - @loopback/example-express-composition: ^2.2.1
  - @loopback/example-greeter-extension: ^2.1.1
  - @loopback/booter-lb3app: ^2.2.1
  - @loopback/example-lb3-application: ^2.1.1
  - @loopback/example-greeting-app: ^2.1.1
  - @loopback/example-context: ^2.1.1
  - @loopback/repository-tests: ^0.12.5
  - @loopback/extension-health: ^0.4.5
  - @loopback/authorization: ^0.5.10
  - @loopback/rest-crud: ^0.8.5
  - @loopback/security: ^0.2.10
  - @loopback/authentication-passport: ^2.1.5
  - @loopback/example-metrics-prometheus: ^0.3.1
  - @loopback/extension-metrics: ^0.3.5
  - @loopback/model-api-builder: ^2.1.5
  - @loopback/extension-logging: ^0.3.5
  - @loopback/example-access-control-migration: ^1.3.1
  - @loopback/example-file-transfer: ^1.3.1
  - @loopback/example-rest-crud: ^1.3.1
  - @loopback/apiconnect: ^0.3.3
  - @loopback/example-validation-app: ^1.4.1
  - @loopback/cron: ^0.2.5
  - @loopback/example-multi-tenancy: ^0.3.1
  - @loopback/example-passport-login: ^1.4.1
  - @loopback/authentication-jwt: ^0.3.1
  - @loopback/context-explorer: ^0.1.5
  - @loopback/express: ^1.2.1

I also tried converting the `.json` to `.yaml` and use that instead though without success.

**Comment by raymondfeng** [comment]
@ohenning Your swagger json probably has circular references in the schemas. We use `swagger2openapi` package to convert 2.0 to 3.0 and the package cannot handle circular refs gracefully. Is it possible to convert your spec to 3.0 first and try?

I'll dig more into the implementation as well.

**Comment by raymondfeng** [comment]
@ohenning I just realized that your spec is already 3.0.1. I'll try.

**Comment by raymondfeng** [comment]
This is the circular ref:
```
     "Newtonsoft.Json.Linq.JToken": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Newtonsoft.Json.Linq.JToken"
        }
      },
```

**Comment by raymondfeng** [comment]
I'm not sure if the `JToken` makes sense at all. An array of its own instances?

**Comment by ohenning** [comment]
Thanks @raymondfeng ! That circular reference actually was causing the stack exceedance. After removing it from the spec, another error occured: `TypeError: Cannot read property 'match' of undefined` - the spec though is still semantically correct due to https://editor.swagger.io/. As this is another error as the one i created this ticket for, we can close this ticket. After some investigation of mine to double check it's not the spec again causing the error i might open a new one for the new error.

**Comment by raymondfeng** [comment]
See https://github.com/APIDevTools/swagger-parser/issues/146

**Comment by dhmlau** [comment]
Closing this issue.
