### ISSUE TITLE
[Thinking in loopback] Doc - Organize resource pattern in a better way

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#557]
# Description

In [using-patterns-to-reduce-duplication](https://github.com/strongloop/loopback-next/wiki/Thinking-in-LoopBack#using-patterns-to-reduce-duplication)

People may define resource patterns in different files, we can add an extra example to show how to integrate them together then export.

The example file structure would like 
```
/apidef
  /resources
    searchable-resource.ts
    creatable-resource.ts
    updatable-resource.ts
    deletable-resource.ts
    ...
    index.ts
```

In each resource file, we export pattern functions:
```js
export let creatableResource = (resource: any) => ({})
```

Then export all resources as a whole in `index.ts`
```js
export * from "./creatable-resource";
export * from "./searchable-resource";
export * from "./deletable-resource";
export * from "./updatable-resource";
```

In a swagger file, people can import any function from `index.ts` instead of figuring out the corresponding file name everytime
```js
import { searchResource } from "./resources/index";
```

**Comment by dhmlau** [comment]
@jannyHou , you've mentioned that this might be affected / related to the openapi-v3 work.  Could you please add more details to this ticket? Thanks.

**Comment by shimks** [comment]
overshadowed by https://github.com/strongloop/loopback-next/issues/1094

**Comment by bajtos** [comment]
@shimks @jannyHou could you please check if this task is still relevant?

**Comment by bajtos** [comment]
IIUC, this story is related to top-down (design-first) approach which is out of scope of GA.

**Comment by shimks** [comment]
Confirming not relevant for GA
