### ISSUE TITLE
Add missing "fuzzy" filters to `WhereBuilder`

### ISSUE THREAD

**Issue by likexoo** [strongloop/loopback-next#5577]
## Suggestion

Need `.like()` method for `WhereBuilder` in lb4.
So far I have followed [this doc](https://loopback.io/doc/en/lb4/Where-filter.html#like-and-nlike) to do fuzzy queries.

## Acceptance criteria

TBD - will be filled by the team.

**Comment by achrinza** [comment]
Additional missing filters:
- like
- nlike
- ilike
- nilike
- regexp
