### ISSUE TITLE
SQS integration

### ISSUE THREAD

**Issue by GitMastStas** [strongloop/loopback-next#5582]
Was just trying to find implementation of SQS from AWS for loopback 4 but cant seem to find any resources whatsoever, would appreciate any sort of information on this topic and how to get it done.

**Comment by dhmlau** [comment]
Transferring to https://github.com/strongloop/loopback-next repo.

**Comment by achrinza** [comment]
Quoting from the [accepted StackOverflow answer](https://stackoverflow.com/a/62061547/5019371):

> 
> 
> There's several ways to go about it. Since LoopBack 4 is a TypeScript/Node.js application at its core, it is possible to simply import an Amazon SQS compatible library into a controller and then calling the library directly.
> 
> A recommended way is to refactor the SQS interfacing logic into a Service, and then bind it into the Application. This would allow the SQS module to be dependency-injected into the controllers, where its methods can be called.
> 
> Since LoopBack 4 Services do not define a strict interface, the implementation design can be tuned to your specific user requirements.
>
