### ISSUE TITLE
[API Explorer] Self-hosted API Explorer

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#559]
As an API developer, I would like to see the OpenAPI spec of my APIs created with LoopBack and have the web UI to visualize the API endpoints and allow me to play with the APIs.

It's important for the API Explorer to be available offline (as opposed to a version hosted on loopback.io):
 - Many enterprise users are behind a restrictive firewall/proxy that disallows access to loopback.io
 - A big part of world's population lives in places with poor/no internet access 
 - People often don't have internet access when traveling (on board of a plane, etc.)

## Acceptance criteria

- [x] Expose endpoints for OpenAPI specs in various combinations of versions and formats, such as:
  - versions: 2.0, 3.0.0
  - formats: json, yaml

- ~Allow such specs to be rendered with http://editor.swagger.io/ with appropriate CORS settings.~

- [ ] Have the option to install a component to enable built-in web UI for the API explorer

Build a (new) LoopBack4 extension based on the approach we have already implemented in loopback-component-explorer. Use the latest version of swagger-ui to make sure we support both Swagger (v2) and OpenAPI (v3), see https://github.com/strongloop/loopback-component-explorer/pull/209

Possibly related, but not strictly required: https://github.com/strongloop/loopback-next/issues/691

**Comment by bajtos** [comment]
I am proposing to enhance RestServer/RestApplication with an API allowing consumers to mount static files, for example `app.static(path, options)`. This API should leverage Express middleware [server-static](https://www.npmjs.com/package/serve-static) as an implementation detail.

With this new API in place, we can either write an API Explorer component bundling swagger-ui and calling `app.static(pathToSwaggerUI)`, or preferably write a short guide explaining LB4 users how to add swagger-ui to their project themselves.

**Comment by virkt25** [comment]
My preference would be to have an API explorer built in since it provides a better DX in my opinion just like it's included in LB3.

**Comment by dhmlau** [comment]
since it's an epic, moving to the backlog

**Comment by bajtos** [comment]
@raymondfeng should we use ReDoc for our API Explorer extension too, replacing swagger-ui we have in LB 3.x?

**Comment by dhmlau** [comment]
Closing as done. All the tasks in this epic are completed.
