### ISSUE TITLE
Add community authorization example to our doc

### ISSUE THREAD

**Issue by HrithikMittal** [strongloop/loopback-next#5595]
## Suggestion
I know you already create docs for adding the Authorization in loopback4 using the shopping example. But for developers to understand is tough (for me also previously as there are some bugs into also- in docs.)

In continuation of these issues
https://github.com/strongloop/loopback-next/issues/5573
https://github.com/strongloop/loopback-next/issues/5294
https://github.com/strongloop/loopback-next/issues/5441

## Use Cases
So, again as  I already create a one for [Authentication](https://github.com/HrithikMittal/Loopback4-auth) similar way I create a repo with the Readme file where a complete processor and steps are mentions of implementing the Authorization is given. [Repo link: [https://github.com/HrithikMittal/Loopback4-authorization](https://github.com/HrithikMittal/Loopback4-authorization) ]

I just give a bit of advice, If you can add the repo into yours or just add Readme would be beneficial for other developers.

## Examples
Authorization
https://github.com/HrithikMittal/Loopback4-authorization

## Acceptance criteria

- [ ] Sidebar change: Rename the community extension to community extension and examples, then that page will also include the community examples.
- [ ] Add https://github.com/HrithikMittal/Loopback4-authorization into our doc.

**Comment by dhmlau** [comment]
@jannyHou, you've proposed a plan on improving the docs for authentication, could you please take a look at this for authorization as well? Similarly, we can make this as an epic, if there's no duplicate issues already, and break it down into sub-tasks. Thanks!

**Comment by dhmlau** [comment]
@HrithikMittal, I just created a [community example page](https://github.com/strongloop/loopback-next/blob/master/docs/site/Community-examples.md). I believe we can just add your example repo to that page. Are you interested to submit a PR? Thanks.
