### ISSUE TITLE
Can't use an array of entities as request body

### ISSUE THREAD

**Issue by Tahakun** [strongloop/loopback-next#5601]
I am trying to use an array of entity as a request object but it does not work

Here's my post function
```
@operation('post', '/customers')
  async addCustomers(@requestBody() _requestBody: Customer[]): Promise<any> {
    throw new Error('Not implemented');
 }
```

when I use the entity without it being inside an array it works
`Customer instead of Customer[]`

here's the OpenApi error
```
Semantic error at paths./customers.post.requestBody.content.application/json.schema
Schemas with 'type: array', require a sibling 'items: ' field
```

that comes from this

```
requestBody:
        content:
          application/json:
            schema:
              type: array
      operationId: CustomerController.addCustomers
```

I tried to do the same thing in the todo example and the same problem occured

## Steps to reproduce

Create any model
Create any controller
Use an array of model as request object

## Current Behavior

![image](https://user-images.githubusercontent.com/17141939/83231265-23b3e000-a183-11ea-93f5-68048f16166a.png)

Should be an array of the model in the example value

## Additional information

`node -v
v12.13.1`

`linux x64 12.13.1`

```
+-- @loopback/authentication@3.3.1
+-- @loopback/authorization@0.4.8
+-- @loopback/boot@1.7.2
+-- @loopback/context@2.0.0
+-- @loopback/core@1.12.2
+-- @loopback/openapi-v3@1.12.0
+-- @loopback/repository@1.18.0
+-- @loopback/rest@1.26.0
+-- @loopback/rest-explorer@1.4.8
+-- @loopback/service-proxy@1.3.15
+-- loopback-connector-mongodb@4.2.0
```

**Comment by HrithikMittal** [comment]
Hey, @Tahakun can show some screenshot of sending the object in the POST request.

**Comment by HrithikMittal** [comment]
Hey, @Tahakun if you want to send many entities than you can send it in the multiple objects into an array then wrap it under the object.
```
{
 [
   { },
   { }
 ]
}
```

I think It will work and then after the req parameter you have to divide it.

**Comment by achrinza** [comment]
For arrays, you should use `@requestBody.array()`:

```ts
@post('/customers')
  async addCustomers(@requestBody.array() _requestBody: Customer[]): Promise<any> {
    throw new Error('Not implemented');
 }
```

Could you try if it works?

**Comment by Tahakun** [comment]
@achrinza Thank you, It's working, here's my updated code

```
@operation('post', '/customers')
  async addCustomers(@requestBody.array(getModelSchemaRef(Customer, {title: 'NewCustomer', exclude: ['id']}))
    _requestBody: Customer[]): Promise<any> {
    throw new Error('Not implemented');
  }
```

and as you said I searched first in the docs for a solution but it seems that 
`@requestBody.array()`
doesn't seems to be documented,

I think it'll be better to add it for anyone in the future looking for this kind of functionality
