### ISSUE TITLE
Broken hyperlink on strongloop website

### ISSUE THREAD

**Issue by jimmy1wu** [strongloop/loopback-next#5604]
## Steps to reproduce

1. Go to https://strongloop.com/projects/
2. Click on `Node.js` hyperlink
![image](https://user-images.githubusercontent.com/33457590/83264469-1ea85e00-a18e-11ea-98e5-556fc7b2aa6e.png)

## Current Behavior

Nothing happens.

## Expected Behavior

It should bring me to the `Node.js` section at the bottom of the page.

![image](https://user-images.githubusercontent.com/33457590/83264411-06d0da00-a18e-11ea-95b9-372b6127d486.png)

## Link to reproduction sandbox

N/A
## Additional information

The anchor name for the `Node.js` section is `openapi` which is probably why the hyperlink at the top of the page does not bring me down here. Changing the anchor name from `openapi` to `nodejs` should fix the issue.
![image](https://user-images.githubusercontent.com/33457590/83264237-ce310080-a18d-11ea-97f5-9759b4769fc7.png)

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by hacksparrow** [comment]
Thanks, will fix it.
