### ISSUE TITLE
How do I validate a nested JSON api request body payload using models in loopback4?

### ISSUE THREAD

**Issue by vishwas097** [strongloop/loopback-next#5611]
I am trying to validate a nested JSON payload using models in loopback4. Loopback4 is able to validate the name and description property. However, it isn't validating the contact.type or contact.number property.

This is an example of what my models looks like:

**Contact Model:**
```ts
import {Model, model, property} from '@loopback/repository';

@model({settings: {}})
export class Contact extends Model {
  @property({
    type: 'string',
    required: true,
    default: 'phone',
  })
  type: string;

  @property({
    type: 'number',
    default: 999999999,
  })
  number?: number;


  constructor(data?: Partial<Contact>) {
    super(data);
  }
}
```

**User Model:**

```ts
import {Entity, model, property} from '@loopback/repository';
import {Contact} from './contact.model';

@model({settings: {}})
export class User extends Entity {
  @property({
    type: 'string',
    id: true,
    required: true,
  })
  name: string;

  @property({
    type: 'string',
  })
  description?: string;

  @property({
    type: 'object',
    required: true,
  })
  contact: Contact;

  constructor(data?: Partial<User>) {
    super(data);
  }
}
```

**Request payload:**

```json
{
    "name": "user1",
    "description": "random user",
    "contact": {
        "type": "phone",
        "number" : 999999999
    }
}
```

## Current Behavior

When I delete name from my request body payload, it throws an error saying required parameter is missing. However, it doesn't throw the same error when I delete contact.type parameter from my payload.

## Expected Behavior

 Loopback4 should throw an error saying required parameter contact.type is missing.

**Comment by achrinza** [comment]
Could you try updating *User* model as follows?

```diff ts
import {Entity, model, property} from '@loopback/repository';
import {Contact} from './contact.model';

@model({settings: {}})
export class User extends Entity {
  @property({
    type: 'string',
    id: true,
    required: true,
  })
  name: string;

  @property({
    type: 'string',
  })
  description?: string;

  @property({
-    type: 'object'
+    type: Contact,
    required: true,
  })
  contact: Contact;

  constructor(data?: Partial<User>) {
    super(data);
  }
}
```

Reasoning being that REST-level validation looks at the `type` attribute and sees `object`, in which any object is considered valid. Changing it to `type: Contact` should inform the REST layer that it's the `Contact` interface.

`contact: Contact` isn't sufficient as the REST layer can't read that the TypeScript type of a controller. Instead, that's used purely for within the controller function itself.

**Comment by madaky** [comment]
@vishwas097: FYI: The loopback4 uses the route Decorator, which provides OpenAPI specification to describe the endpoint. There is en-detailed about  [ OpenAPI decorator in loopback4 here](https://loopback.io/doc/en/lb4/Decorators_openapi.html#api-decorator).

For better practices you can use the Request Body decorator at controller level.

**Comment by vishwas097** [comment]
@achrinza Yes. This is what i missed and it is working perfectly fine after changing type object. 
Thankyou very much.
So if i need to create a nested array again [for example inside type if i need something like this 
type:{
"address":"","value":""
}
 ]
is it required to create a model again ? Or in loopback4 do we have any other procedure also?

**Comment by vishwas097** [comment]
@madaky  I will try this procedure and let you know
