### ISSUE TITLE
Type String for ID is not emited at the creation

### ISSUE THREAD

**Issue by GitMastStas** [strongloop/loopback-next#5617]
## Steps to reproduce

Create a model, set uuid as ID of the table, type string,
Make repository
Make controller, uuid should be omitted by lb4 at the creation process.

## Current Behavior
Model defined as this
```
@property({
    type: 'string',
    id: true,
    generated: true,
  })
  uuid?: string;

  @property({
    type: 'number',
  })
  id?: number;

  @property({
    type: 'string',
  })
  text?: string;

  @property({
    type: 'string',
  })
  more?: string;
```
then POST METHOD
```
{
           "id": 2211
	"text":"aaaaaa",
	"more": "as"
}

```
Then GET METHOD to return what we jsut created
```
[
    {
        "uuid": null,
        "id": 2211
        "text": "aaaaaa",
        "more": "as"
    }
]
```
Even though its ommited, it creates NULL in the database.
## Expected Behavior

Was hoping it would create uuid or something of type string

## Link to reproduction sandbox

Once again, just make a table set uuid as ID of type string, can add a few extra fields like text and more (not required). Then make a repository, then make a controller

```
? What kind of controller would you like to generate? REST Controller with CRUD functions
? What is the name of the model to use with this CRUD repository? Test
? What is the name of your CRUD repository? TestRepository
? What is the name of ID property? uuid
? What is the type of your ID? string
? Is the id omitted when creating a new instance? Yes
? What is the base HTTP path name of the CRUD operations? /test
```

Please help, and disregard the id property, removing it doesnt eradicate the problem

**Comment by dougal83** [comment]
@GitMastStas Could you confirm which database connector you are using and have you run `npm run build` & `npm run migrate`.  This would be required to generate the id.

Docs: https://loopback.io/doc/en/lb4/Database-migrations.html

**Comment by achrinza** [comment]
Quoting my reply from Slack:


> Have you tried setting `useDefaultIdType: false`:
>
> https://loopback.io/doc/en/lb4/Model.html#id-properties

**Comment by dhmlau** [comment]
@GitMastStas, do the above comments resolve your issue? If so, is the issue good to close? Thanks.

**Comment by achrinza** [comment]
Closing as solved as per-Slack discussion.
