### ISSUE TITLE
Update README for beta

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#562]
## Acceptance Criteria
- [x] Verify that any instructions given to first-time users in **in all READMEs** are still correct
- [x] Change all links from wiki to the official documentation, if applicable
- [ ] Change the status notice from "ALPHA" to "Beta" **in all READMEs**
- [ ] Link to @raymondfeng's blog post (beta announcement)

**Comment by dhmlau** [comment]
when we're ready to release beta, change the status to be beta and point to @raymondfeng's beta announcement blog.

**Comment by b-admike** [comment]
```
 Change the status notice from "ALPHA" to "Beta" in all READMEs
 Link to @raymondfeng's blog post (beta announcement)
```
These bullet points are not applicable at the moment, so I have not made those changes.
