### ISSUE TITLE
Is there any way to use existing mongodb schema in loopback 4 ? 

### ISSUE THREAD

**Issue by vishwas097** [strongloop/loopback-next#5626]
As i am new to backend development, especially to loopback, I am just getting confused that how we suppose to use, create schema[ ie nested schema and validate it ]in loopback4. As I already have my tables in my database and I should expose API for those tables. So is there any way to define to use existing MongoDB schema in loopback 4?

**Comment by hacksparrow** [comment]
Create the corresponding models for those tables. That's all you have to do.

Models: https://loopback.io/doc/en/lb4/Model.html
Model generator: https://loopback.io/doc/en/lb4/Model-generator.html

Models can be autogenerated for SQL databases, using [model discovery](https://loopback.io/doc/en/lb4/Discovering-models.html), but it's not supported for NoSQL like MongoDB.
