### ISSUE TITLE
Not able to pass  querystring and requestbody together in an api call through service code.

### ISSUE THREAD

**Issue by ManzarBaig** [strongloop/loopback-next#5631]
<!-- 🚨 STOP 🚨 STOP 🚨 STOP 🚨

##This is the api method I am trying to call through open-api-connector
@post('/acc-api/sow/remote', {
    responses: {
      '200': {
        description: 'Sow model instance',
        content: { 'application/json': { schema: { 'x-ts-type': Sow } } },
      },
    },
  })
  async createRemote( @param.query.string('jwt') jwt: string , @requestBody() sow: Sow ): Promise<Sow> {
    return await this.sowRepository.create(sow);
  }

##This is the calling service code which calls the above api. 
const token: string = "sometoken";
      const sowService = await getServiceConstant(url, 'SowService');
const sow = await sowService.SowController_createRemote( token, {name:"xyz"});

**Comment by achrinza** [comment]
Thanks for reporting an issue. Please use [the full bug template](https://github.com/strongloop/loopback-next/issues/new?labels=bug&template=Bug_report.md) so that we can better diagnose and resolve the issue.

**Comment by ManzarBaig** [comment]
Created the issue in detail : #5632
