### ISSUE TITLE
Not able to pass querystring and requestbody together to call an api  through loopback-connector-openapi.

### ISSUE THREAD

**Issue by ManzarBaig** [strongloop/loopback-next#5632]
## Steps to reproduce

Step 1. In order to reproduce you have to create two lightweight sample loopback projects . 
Step 2. Write SowController in one project .
Step 3. Implement dapp controller in other. Dapp consumes SOW.
Step 4. write a method in sowController like this:  
` @post('/acc-api/sow/remote', {
    responses: {
      '200': {
        description: 'Sow model instance',
        content: { 'application/json': { schema: { 'x-ts-type': Sow } } },
      },
    },
  })
  async createRemote( @param.query.string('jwt') jwt: string , @requestBody() sow: Sow ): Promise<Sow> {
    return await this.sowRepository.create(sow);
  }
`
Step 5. Using loopback-connector-openapi 
Write these functions to create SOW datamodel in Dapp

`async function getServiceConstant(API_URL: any, serviceName: string) {
  const getDS = await createDataSource(API_URL, { positional: true });
  return await getDS.createModel(serviceName);
}

`
`async function createDataSource(spec: any, options: any) {
  const config = Object.assign(
    {
      connector: 'loopback-connector-openapi',
      spec: spec,
    },
    options,
  );
  const ds = loopback.createDataSource('openapi', config);
  await pEvent(ds, 'connected');
  return ds;
}`

Step 6. Write code in some method to call sow service to create SOW object:
`const url = process.env.SOW_OPENAPI+`?jwt=${token}`;
const sowService = await getServiceConstant(url, 'SowService');      
const sow = await sowService.SowController_createRemote( token, {abc:"def"});`

## Current Behavior
Calling this api like this
     `const sow = await sowService.SowController_createRemote( tokenn, JSON.stringify({abc:"def"}));`
 throws following error.
`TypeError: Cannot create property 'requestBody' on string '{"abc":"def"}'`
esult -->
I also tried removing JSON.stringify(), then it throws `TypeError: Converting circular structure to JSON`

## Expected Behavior

According http specification query string and request body can be sent to any post or put api.
I checked this behavior through post man I am able to call the SOW api . But in loopback controller I am getting errors.

## Link to reproduction sandbox

I don't have any link.

## Additional information

In brief, a method of a service 'SOW'
` @post('/acc-api/sow/remote', {
    responses: {
      '200': {
        description: 'Sow model instance',
        content: { 'application/json': { schema: { 'x-ts-type': Sow } } },
      },
    },
  })
  async createRemote( @param.query.string('jwt') jwt: string , @requestBody() sow: Sow ): Promise<Sow> {
    return await this.sowRepository.create(sow);
  }`

Needs to be called by passing query string and request body object.
`const sow = await sowService.SowController_createRemote( token, {abc:"def"});`

## Related Issues

Could not find any ticket similar to this

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by jannyHou** [comment]
Hi @ManzarBaig could you provide a sandbox/sample app to reproduce the error? It will help us diagnose the problem. Thanks!

**Comment by raymondfeng** [comment]
@ManzarBaig The following code works for me:
```ts
import {juggler} from '@loopback/repository';
import {getService} from '@loopback/service-proxy';
import {once} from 'events';

async function getServiceConstant(url: string) {
  const getDS = await createDataSource(url, {positional: true});
  return getService(getDS);
}

async function createDataSource(spec: string, options: object) {
  const config = Object.assign(
    {
      connector: 'loopback-connector-openapi',
      spec: spec,
    },
    options,
  );
  const ds = new juggler.DataSource('openapi', config);
  await once(ds, 'connected');
  return ds;
}

async function main() {
  const service = await getServiceConstant(
    'http://localhost:3000/openapi.json',
  );
  const result = await service.PingController_createRemote('jwt-token', {id: '2'});
  console.log(result);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
```

I would recommend you to try `lb4 openapi --client` to generate strongly-typed client code against the spec.

**Comment by raymondfeng** [comment]
See https://loopback.io/doc/en/lb4/OpenAPI-generator.html#client-side-datasource-and-service-proxies
