### ISSUE TITLE
loopback4 -  prerequisites for accessing existing mongodb table?

### ISSUE THREAD

**Issue by vishwas097** [strongloop/loopback-next#5638]
Hello, May i know how to access a existing mongodb table. I am able to connect to the mongodb, how to access to particular existing table?

**Comment by hacksparrow** [comment]
You have to create a connector for that. Specify the database details when prompted.

Instructions: https://loopback.io/doc/en/lb4/DataSource-generator.html

**Comment by jannyHou** [comment]
@vishwas097 We have a PR(landing soon) for mongodb instructions, see https://github.com/strongloop/loopback-next/pull/5637/files#diff-7569121d0ff2f39403ff381a26d4ace7.

It has a section called "Create a data source" which tells you how to specify a database in the configuration.

> how to access a existing mongodb table. I am able to connect to the mongodb, how to access to particular existing table?

Each LB4 repository provides the persistence operations for a particular **collection**, but other than making native queries, we don't provide database level operations.

**Comment by vishwas097** [comment]
@jannyHou Yes. I am able to create database source and all. But in my case, my table names included underscore[ ex : customer_details ]. So in this case, i was not able to access particular table as lb4 model name will ignore underscore while creating models.

So i found a solution, please include this in  PR also if you think its necessary.
In model setting we can replace the table name, for mongodb we have this procedure in lb4.

For example if my mongodb table name is 'customer_info',
@model({
  settings: {
    mongodb: {
      collection: 'customer_info',
    },

  },
})
we can access db table using this method.
Hope it helps someone who is facing this issue. 
Thanks

**Comment by dhmlau** [comment]
Thanks @vishwas097. 
@agnes512, IIRC, I think you've covered how to customize the model as mentioned in the [above comment](https://github.com/strongloop/loopback-next/issues/5638#issuecomment-638112468). If we've covered it, please close this issue. Thanks.

**Comment by agnes512** [comment]
Yes 
```
@model({
  settings: {
    mongodb: { //dbtype ex : mongodb, postgresql
      collection: 'customer_info', //'customer_info' table name
    },
  },
})
```
allows you to have different model names and collection names. We have it included in https://github.com/strongloop/loopback-next/pull/5637/files#diff-7569121d0ff2f39403ff381a26d4ace7R162. Thanks.
