### ISSUE TITLE
openapi not found after update to @loopback/rest@4.0.0

### ISSUE THREAD

**Issue by mrbatista** [strongloop/loopback-next#5650]
Upgrade to @loopback/rest@4.0.0 break the following urls:
- http://localhost:300/openapi.json 
- http://localhost:300/openapi.yaml 

## Steps to reproduce
1. git clone https://github.com/strongloop/loopback4-example-shopping.git
2. npm install
3. npm start
4. Open url http://localhost:300/openapi.json 

## Current Behavior

The response is 404 not found

## Expected Behavior

Return the openapi spec (json or yaml)

## Additional information
If downgrade to @loopback/rest@3.3.2 the api correctly returns the open api spec

**Comment by raymondfeng** [comment]
@mrbatista Good catch.
