### ISSUE TITLE
[GSSC-GVT]English String when input command apic client-creds:clear

### ISSUE THREAD

**Issue by wxuwh** [strongloop/loopback-next#5655]
Steps & Verification Points:
input ./apic client-creds:clear
and click Enter
Verify the strings in red circle.

Actual Result:

**Comment by wxuwh** [comment]
![image](https://user-images.githubusercontent.com/45190559/83712201-c2df4880-a657-11ea-89d1-28f6530cb578.png)

**Comment by wxuwh** [comment]
![01](https://user-images.githubusercontent.com/45190559/83712297-05088a00-a658-11ea-9b49-da68e3af66e7.png)

**Comment by candytangnb** [comment]
@dhmlau Xufen and I have no access to add label for issues. Could you please help to add GVT label? If possible, could you please grant us access to add label? Thanks.

**Comment by candytangnb** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/26452457/83729891-e071d980-a67a-11ea-8838-a2ac61497918.png">

**Comment by dhmlau** [comment]
this command is not coming from LoopBack. Please open this issue against APIC toolkit. Thanks.

**Comment by wxuwh** [comment]
Thanks for the information. We have opened a new issue  in Toolkit
https://github.ibm.com/velox/platform/issues/2501
