### ISSUE TITLE
[GSSC-GVT]English String when input command apic lb4 model

### ISSUE THREAD

**Issue by wxuwh** [strongloop/loopback-next#5657]
Steps & Verification Points:
if you have created lbproject, go to step 10
input ./apic lb4
input lbproject as Project aame and Click Enter
input lbproject as Project description and Click Enter
input lbproject as Project root directory and Click Enter
Leave application class name as default and click Enter
Click Enter
Wait until the project has been created
input cd lbproject and click Enter
input ../apic lb4 model and click Enter
Input module1 as name and click Enter
Click Enter
Click Enter
Input pro1 as property name and click Enter
click Enter
click Enter
click Enter
click Enter
Verify the strings in red circle.

![image](https://user-images.githubusercontent.com/45190559/83717809-3ab46f80-a666-11ea-9ffc-b8c44e5e9abd.png)

## Acceptance Criteria
- [ ] investigate if we can overwrite the text
- [ ] If possible, find a way to make the highlighted text translatable.

**Comment by dhmlau** [comment]
This is probably coming from Yeoman. @agnes512, could you please take a quick look to see if we can overwrite it? Thanks.
