### ISSUE TITLE
[GSSC-GVT]English String when input command APIC apic lb4 interceptor

### ISSUE THREAD

**Issue by wxuwh** [strongloop/loopback-next#5658]
Steps & Verification Points:
if you have created lbproject, go to step 10
input ./apic lb4
input lbproject as Project aame and Click Enter
input lbproject as Project description and Click Enter
input lbproject as Project root directory and Click Enter
Leave application class name as default and click Enter
Click Enter
Wait until the project has been created
input cd lbproject and click Enter
input ../apic lb4 interceptor and click Enter
Input inter1 as name and click Enter
Click Enter 
click Enter
Verify the strings in red circle.
Click Enter to exit

Actual Result:
![image](https://user-images.githubusercontent.com/45190559/83723216-e5ca2680-a670-11ea-91fb-c7bb522edb9b.png)

## Acceptance Criteria

- [ ] Make a list of reserved keywords and specify them in the way described by @candytangnb in [this comment](https://github.com/strongloop/loopback-next/issues/5658#issuecomment-641112722)

**Comment by dhmlau** [comment]
@wxuwh , `interceptor` is a concept in LoopBack, similar to Model and Controller. It may not be a good idea to have it translated, If you agree, I'd like to close this issue. Thanks.

**Comment by candytangnb** [comment]
@dhmlau Word 'Interceptor' and 'Model' could be kept as untranslated when they are concept if DEV would like to do so. But, please keep it consitent. When the word is treated as a concept, it could not be translated by Tester. When the word is back to original meaning, it could be translated by Tester. 
And, need dev to mark comment on those words to let Tester know where to translated and where not.

**Comment by dhmlau** [comment]
@candytangnb, where do we mark comment on the concept words?

cc @agnes512

**Comment by dhmlau** [comment]
Let me reopen this issue for now so that we won't miss the ongoing discussion.

**Comment by candytangnb** [comment]
I have checked that this file use IBMUJSON as markup table. Please refer to this when trying to add comment. https://w3-03.ibm.com/globalization/page/2089#IBMUJSON
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/26452457/84123036-de898b00-aa6b-11ea-937d-411a34db418d.png">

**Comment by candytangnb** [comment]
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/26452457/84123143-04169480-aa6c-11ea-9e1c-8b7bef6355fe.png">
