### ISSUE TITLE
[GSSC-GVT]Concatenation issue when input command  apic lb4 interceptor

### ISSUE THREAD

**Issue by wxuwh** [strongloop/loopback-next#5667]
Steps & Verification Points:
if you have created lbproject, go to step 10
input ./apic lb4
input lbproject as Project aame and Click Enter
input lbproject as Project description and Click Enter
input lbproject as Project root directory and Click Enter
Leave application class name as default and click Enter
Click Enter
Wait until the project has been created
input cd lbproject and click Enter
input ../apic lb4 interceptor and click Enter
Input inter1 as name and click Enter
Click Enter 
click Enter
Verify the strings in red circle.
Click Enter to exit

Actual Result:
![image](https://user-images.githubusercontent.com/45190559/83836095-22eff080-a725-11ea-8a19-fd7183e5d4d8.png)
![image](https://user-images.githubusercontent.com/45190559/83836114-33a06680-a725-11ea-9779-921de6f38816.png)
![image](https://user-images.githubusercontent.com/45190559/83836353-c04b2480-a725-11ea-9459-fc69ae3a829f.png)

Example
![image](https://user-images.githubusercontent.com/45190559/83836136-44e97300-a725-11ea-812c-1fff8495cddb.png)
http://tlbgsa.ibm.com/projects/g/gcoc/gvtguide/testareas/DOH-MCN-010.htm

## Acceptance Criteria
- [ ] for the translated string, include the whole sentence with parameters, instead of breaking them up.

**Comment by dhmlau** [comment]
@wxuwh, could you please specify what's the expected behavior? Thanks.

**Comment by candytangnb** [comment]
Now, in pii, string  "5337dcf1ffc5bb73817a6fe76bb5eb0a": "were created in" is seperate. Could it be resourced out with subject as a whole, such as "0f97dcea7dc212c905400da264b09cfd": "Application {0} was created in {1}."

**Comment by candytangnb** [comment]
for in some language, word order may be not the same as in English, if sentences not resourced out as a whole, it could not be translated correctly.

**Comment by candytangnb** [comment]
@agnes512 I see English string has been updated in loopback 2.12.0. However, still english in language. 

<img width="577" alt="image" src="https://user-images.githubusercontent.com/26452457/90107400-57aea280-dd7b-11ea-878e-0a749b77ee5e.png">

**Comment by agnes512** [comment]
👍 
They work on my machine. Let me reopen the issue and figure it out.

**Comment by candytangnb** [comment]
verified and fixed in loopback@cli 2.13.0 
<img width="751" alt="image" src="https://user-images.githubusercontent.com/26452457/91016072-c4992680-e61e-11ea-86d3-9028c7529a53.png">

**Comment by agnes512** [comment]
Thank you verifying it!
