### ISSUE TITLE
Create OpenAPI schema registry for @loopback/rest

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#568]
depends on #567 

## Overview
We should create a registry that allows the definition of schema

## Proposed Acceptance Criteria
Create a schema registry for the application that defines
- response schemas for operations
  - return types
  - response codes
  - etc
- `@response` decorators to associate this metadata with response functions
  - if the `@response` has been defined on a function
    - sequence should leverage this data on the app schema to define correct return codes/error classes
    - possible hooks for validating returned object definition and content-type format?
- request schemas for incoming data?

**Comment by bajtos** [comment]
@kjdelisle I am not sure, is this something we need for MVP?
