### ISSUE TITLE
Improvement suggestion for the microservices structure

### ISSUE THREAD

**Issue by turnerguo** [strongloop/loopback-next#569]
## Improvement Suggestion

First of all, I love Loopback, it's really a great service framework, and we are using Loopback v3 right now, just saw loopback-next is coming and tried it and have a little suggestion here.

As you can see the following example: 
![image](https://user-images.githubusercontent.com/633880/30363528-24d7bf52-9893-11e7-854c-afbedf132ae6.png)

It is a official example which contains several microservices, and each service has a `package.json` which means it will install `node_modules` in each service folder, and each `node_modules` contains much more same packages such as @loopback/core etc., I think that is not really a good structure in some situation.

Since node can dynamically read `node_modules` folder in runtime, so can we just use some mechanism to merge services' dependences? to keep microservices as a real `micro` service?

**Comment by kjdelisle** [comment]
@turnerguo Thanks for your feedback! The effort that's gone into loopback-next-example hasn't kept up with the work on the core framework, so there are lots of ways this could be improved.
If you have an idea for what we can tidy up, feel free to make a pull request and ping me. :)

**Comment by bajtos** [comment]
Hello, is this issue still relevant?

**Comment by bajtos** [comment]
Closing this issue as stale.

FWIW, I think it should be possible to achieve the requested outcome by using lerna and hoisted dependencies.
