### ISSUE TITLE
How to be more proactive/responsive with regards to community?

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#57]
Flame war topic.

We need to address the number of growing/open issues in a sustainable way. Ideas?

cc @bajtos @raymondfeng

**Comment by bajtos** [comment]
@strongloop/loopback-devs @dhmlau 

> We need to address the number of growing/open issues in a sustainable way. Ideas?

We have touched this topic yesterday, let's discuss concrete plans during our Tuesday's retrospective/sprint planning.

**Comment by bajtos** [comment]
I think we are constantly finding ways how to be more responsive, considering the amount of incoming issues and the small size of our team. I summarized my thoughts in a blog post, see https://medium.com/loopback/sustaining-loopback-project-b67fd59673e4
