### ISSUE TITLE
[Docs] Add Troubleshooting guide 

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#5701]
Add troubleshooting guide to the docs.
https://github.com/dhmlau/learning-loopback/blob/master/troubleshooting.md might be a good starting point.

cc @raymondfeng @bajtos, per our meeting today.

## Acceptance criteria
- [ ] create a new section "Troubleshooting" - mention different perspectives
- [ ] add pages for different topics
  - [x] Tips from https://github.com/dhmlau/learning-loopback/blob/master/troubleshooting.md
  - [x] move https://loopback.io/doc/en/lb4/Running-and-debugging-apps.html to "Troubleshooting"
  - [x] VSC debugging
  - [x] `DEBUG=*` usage
  - [x] LB4 Sandbox usage - esp for users submitting issues - https://github.com/strongloop/loopback-next/blob/master/docs/site/DEVELOPING.md#using-monorepo-packages-as-dependencies
  - [ ] Open follow up story covering the following
    - [ ] Mocha related tips - running specific test, env vars, debugging, setting db
    - [ ] Memory profiling, CPU usage
    - [ ] Debugging in Docker

**Comment by maaaaat** [comment]
Tips on profiling loopback’s startup would be huge right now. My company is running into cold start issues with our server less architecture that cause a bunch of 503s sent to clients as loopback gets ready to respond to requests. It would be monumental to know where to look and how to even start figuring out what needs fine tuning. 

Got a timeline on these guides or have any ideas we could try ahead of you guys publishing these guides?

**Comment by dhmlau** [comment]
@maaaaat, we're not working on the profiling at the moment. If you have any tips or guides, feel free to publish it and reference it here. Or you can also enhance our docs by submitting a PR to add that info too. Thanks.

**Comment by bajtos** [comment]
@maaaaat 

> Tips on profiling loopback’s startup would be huge right now. My company is running into cold start issues with our server less architecture that cause a bunch of 503s sent to clients as loopback gets ready to respond to requests. It would be monumental to know where to look and how to even start figuring out what needs fine tuning

I have had a good experience with https://www.npmjs.com/package/require-so-slow, you may want to give it a try.

**Comment by jannyHou** [comment]
Created follow stories:
#6466 
#6465 
#6464 
#6463

**Comment by jannyHou** [comment]
Closing as done. Let's use https://github.com/strongloop/loopback-next/issues/6465 for the further discussions about memory profiling and cpu usage.
