### ISSUE TITLE
[Docs] Add a Community extension page

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#5702]
Add a community extension page to list extensions built by the community. It will be similar to the community connector page: https://loopback.io/doc/en/lb4/Community-connectors.html. 

## Acceptance criteria
- [ ] add a community extension page with a few community extensions we know about. 
    - the idea is to have the community user to submit PRs to add their extensions on this page
- [ ] add this to sidebar of the docs
- [ ] Add link to npm keyword "loopback4-extension" page.
- [ ] Add links to pages about creating extensions.

cc @raymondfeng @bajtos, per our discussion today.

**Comment by dhmlau** [comment]
We might be able to use some of the extensions listed on npmjs: https://www.npmjs.com/search?q=loopback4-extension. 

@samarpanB @ckoliber, I believe you had a few LoopBack 4 extensions. Please feel free to add here to help us building the initial list!

**Comment by samarpanB** [comment]
Hi @dhmlau ,

Here are the ones we created

1. https://www.npmjs.com/package/loopback4-authentication 
2. https://www.npmjs.com/package/loopback4-soft-delete
3. https://www.npmjs.com/package/loopback4-authorization
4. https://www.npmjs.com/package/loopback4-helmet
5. https://www.npmjs.com/package/loopback4-ratelimiter
6. https://www.npmjs.com/package/loopback4-notifications
7. https://www.npmjs.com/package/loopback4-s3

**Comment by ckoliber** [comment]
Hi Diana,

Here are my extensions:

1. [loopback-component-history](https://github.com/loopback4/loopback-component-history)
    - Soft create, delete, delete models, saving history of changes

2. [loopback-component-filter](lhttps://github.com/loopback4/loopback-component-filter)
    - Filter models in repository layer, using an async function

3. [loopback-component-crud](https://github.com/loopback4/loopback-component-crud)
    - Generic CRUD controller mixin, supports authentication, nested authorization(cascade)

4. [loopback-component-cascade](https://github.com/loopback4/loopback-component-cascade)
    - Create, update, delete nested models in repository layer

5. [loopback-component-authorization](https://github.com/loopback4/loopback-component-authorization)
    - HRBAC authorization implementation
