### ISSUE TITLE
context.bind(...).toProvider(...).inScope(BindingScope.CONTEXT) does not work with async providers

### ISSUE THREAD

**Issue by thamion** [strongloop/loopback-next#5730]
## Steps to reproduce

In our LB rest application we have resources bound like this:
```
context.bind(someBindingKey).toProvider(MyProvider).inScope(BindingScope.CONTEXT);
```

The provider class provides the value in an async manner:

```TypeScript
export class MyProvider implements Provider<MyValue> {
  constructor(
    private readonly id = uuid(),
  ) {
    console.log(`MyProvider ${id}`);
  }

  public value(): Promise<MyValue> {
    console.log(`MyProvider.value ${this.id}`);
    return await somethingAsyncReturningMyValue();
  }
}
```

In a couple of other classes we inject `MyValue` via `someBindingKey`.

## Current Behavior
We observe that `MyProvider` is created several times in a single request and `MyProvider.value()` is called multiple times, once for each place where it is injected.

The output for one request looks like this, for example:

```
MyProvider fc879569-bb4d-467f-b544-5dac76a217b0
MyProvider.value fc879569-bb4d-467f-b544-5dac76a217b0
MyProvider b0c5c7f1-f1c5-4d33-b49d-3968b5a8842e
MyProvider.value b0c5c7f1-f1c5-4d33-b49d-3968b5a8842e
```

## Expected Behavior
Since the binding is in scope `(BindingScope.CONTEXT)`, `MyValue` should only be created once per request and reused afterwards, so there should only be one call to `MyProvider.value` per request.

After a bit of debugging, we believe that this is due to the way caching during resolving of dependencies is implemented. Dependencies coming from async providers are cached only after the promises have been resolved. This makes sense, of course, but there is no bookkeeping whether or not a provider has been already called but not yet returned. Therefore, trying to resolve the same asynchronously created dependency will result always in a cache miss and consequently another call to the provider.

## Link to reproduction sandbox

An example + test is in https://github.com/thamion/loopback-next/tree/async-provider
`examples/context/src/async-provider.ts`

## Additional information
```
node -e 'console.log(process.platform, process.arch, process.versions.node)'
darwin x64 12.13.1

npm ls --prod --depth 0 | grep loopback
@loopback/example-context@2.1.3 /workspaces/git/loopback-next/examples/context
├── @loopback/context@3.9.0
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
@thamion Thank you for reporting the issue. Please verify the PR.
