### ISSUE TITLE
doc: Move contribution doc from wiki to repo

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#574]
# Description/Steps to reproduce
Need to add a `CONTRIBUTING.md` file to the project as we currently point to the wiki. 

# Expected result
Information should be available within the project.

**Comment by bajtos** [comment]
Consider moving some of the content from wiki to docs in loopback.io so that we can share it with other loopack4 packages like examples, etc.

**Comment by bajtos** [comment]
See also https://github.com/strongloop/loopback-next/pull/977

**Comment by b-admike** [comment]
@bajtos The work you've done in #977 pretty much covers this task, correct? If you think so, please feel free to close it. If not, then I can take it up again.

**Comment by raymondfeng** [comment]
@b-admike There is another pending PR: https://github.com/strongloop/loopback-next/pull/1015

**Comment by bajtos** [comment]
@b-admike you are right, thank you for bringing this issue to my attention.

I am closing it as done.
