### ISSUE TITLE
[APIDocs] Table not showing properly when it includes code snippet

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#5756]
In  https://loopback.io/doc/en/lb4/apidocs.rest.openapispecoptions.html, the table for the properties is not shown properly, see screen shot below: 

<img width="870" alt="Screen Shot 2020-06-16 at 3 48 23 PM" src="https://user-images.githubusercontent.com/25489897/84821259-d63fcb80-afe8-11ea-86b7-d6bbfd1faf2c.png">

Discovered this during a meeting with @raymondfeng and @bajtos, the issue might be because there's a code snippet inside a table in tsdocs. 

Fix tip: Use the `@remarks` TSdoc notation

**Comment by jannyHou** [comment]
- `@example` and `@remarks` won't work, after parsing, code just disappears.

```
   * @example
   * ```
   * {
   *   '/openapi.json': {version: '3.0.0', format: 'json'},
   *   '/openapi.yaml': {version: '3.0.0', format: 'yaml'},
   * }
   * ```

   * @remarks
   * ```
   * {
   *   '/openapi.json': {version: '3.0.0', format: 'json'},
   *   '/openapi.yaml': {version: '3.0.0', format: 'yaml'},
   * }
   * ```
```

And adding empty line between the `@remarks` and code won't work either.

- other annotations in https://api-extractor.com/pages/tsdoc/doc_comment_syntax/ fail too

- suggestion in https://stackoverflow.com/questions/28508141/code-block-inside-table-row-in-markdown not working in this case.

- an issue probably related: https://github.com/microsoft/tsdoc/issues/166, explains why this is not support in api-extractor.

**Comment by jannyHou** [comment]
Close as PR merged.
