### ISSUE TITLE
Table with string ID property marked as required do not accept it in POST

### ISSUE THREAD

**Issue by gioppoluca** [strongloop/loopback-next#5757]
## Steps to reproduce
The following cose is the model.
It has a string ID (that should be possible)
`
import { Entity, model, property } from '@loopback/repository';

@model({
  settings: { idInjection: false, postgresql: { schema: 'micadoapp', table: 'languages' } }
})
export class Languages extends Entity {
  @property({
    type: 'string',
    required: true,
    length: 10,
    id: true,
    generated: false,
    //    postgresql: {columnName: 'lang', dataType: 'character varying', dataLength: 10, dataPrecision: null, dataScale: null, nullable: 'NO'},
  })
  lang: string;

  @property({
    type: 'string',
    length: 10,
    postgresql: { columnName: 'iso_code', dataType: 'character varying', dataLength: 10, dataPrecision: null, dataScale: null, nullable: 'YES' },
  })
  isoCode?: string;

  @property({
    type: 'string',
    length: 25,
    postgresql: { columnName: 'name', dataType: 'character varying', dataLength: 25, dataPrecision: null, dataScale: null, nullable: 'YES' },
  })
  name?: string;

  @property({
    type: 'boolean',
    required: true,
    postgresql: { columnName: 'active', dataType: 'boolean', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'NO' },
  })
  active: boolean;

  // Define well-known properties here

  // Indexer property to allow additional data
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [prop: string]: any;

  constructor(data?: Partial<Languages>) {
    super(data);
  }
}

export interface LanguagesRelations {
  // describe navigational properties here
}

export type LanguagesWithRelations = Languages & LanguagesRelations;

`
Generated a CRUD controller.
The call to the POST method do not accept the "lang" property

## Current Behavior

As explained

## Expected Behavior

Since I've defined that the property is required I have to be able to send the key in POST

**Comment by jannyHou** [comment]
cc @agnes512 could you help take a look? 🙇‍♀️

**Comment by agnes512** [comment]
@gioppoluca could you check if you have the id property omitted in the controller? i.e
```
  @post('/users', {...})
  async create(
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(User, {
            title: 'NewUser',
            exclude: ['id'],  // excluded
          }),
        },
      },
    })
    user: Omit<User, 'id'>, // omitted
  ): Promise<User> {
    return this.userRepository.create(user);
  }
```
For your case, as the id is not auto-generated and required, in the controller, you should have:
```
  @post('/users', {...})
  async create(
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(User, {
            title: 'NewUser'
          }),
        },
      },
    })
    user: User
  ): Promise<User> {
    ...
```

**Comment by gioppoluca** [comment]
Probably I'm missing some pieces, but I executed the command:
`lb4 rest-crud --datasource micadoDS --model Languages`
so I have in the "model-endpoints" folder this code (autogenerated by Loopback)

`
import {ModelCrudRestApiConfig} from '@loopback/rest-crud';
import {Languages} from '../models';

const config: ModelCrudRestApiConfig = {
  model: Languages,
  pattern: 'CrudRest',
  dataSource: 'micadoDS',
  basePath: '/languages',
};
module.exports = config;
`

How can I tall the controller I WANT to be able to send the ID?
Thanks

**Comment by gioppoluca** [comment]
I have tryed also to create the repository using command:
`lb4 repository Languages`
Than created the controller following this flow:
`lb4 controller Languages
Controller Languages will be created in src/controllers/languages.controller.ts

? What kind of controller would you like to generate? REST Controller with CRUD functions
? What is the name of the model to use with this CRUD repository? Languages
? What is the name of your CRUD repository? LanguagesRepository
? What is the name of ID property? lang
? What is the type of your ID? string
? Is the id omitted when creating a new instance? No
? What is the base HTTP path name of the CRUD operations? /languages
   create src/controllers/languages.controller.ts
   update src/controllers/index.ts

Controller Languages was created in src/controllers/
`

As you can see at the question if I want to OMIT the id I answered NO.
BUT in the end the POST does not allow me to send the id and tells me that:
`
{
  "error": {
    "statusCode": 422,
    "name": "UnprocessableEntityError",
    "message": "The request body is invalid. See error object `details` property for more info.",
    "code": "VALIDATION_FAILED",
    "details": [
      {
        "path": "",
        "code": "additionalProperties",
        "message": "should NOT have additional properties",
        "info": {
          "additionalProperty": "lang"
        }
      }
    ]
  }
}
`

**Comment by agnes512** [comment]
👍 The error message helps.  I think `rest-crud` automatically allows the `additionalProperty` property, which is only for NoSQL database. It seems a bug to me. Could you try remove these part from the model and see if it works?
```
// Define well-known properties here

// Indexer property to allow additional data
// eslint-disable-next-line @typescript-eslint/no-explicit-any
[prop: string]: any;
```

As for the bug, I will check the `rest-crud` package. Thanks!

**Comment by gioppoluca** [comment]
YES!!!!
Removing that statement solve the problem.
Thanks

**Comment by agnes512** [comment]
`rest-crud` creates repositories and controllers **based on** the models that users created. In this particular case, models should not have the `additionalProperty` property when defining models as that property is only for NoSQL databases. (`rest-crud` is good). Closing the issue as solved.

**Comment by MinSunLee** [comment]
Dear @agnes512,
I try remove statement as you guide, but not working for me.

I executed cmd to generate model-endpoints:
> lb4 rest-crud --datasource db_oracle --model my_table

And I removed statement `[prop: string]: any;` in model file, but not working.
When POST with value of ID field, I receive error message:

>     "message": "The request body is invalid. See error object `details` property for more info.",
>     "code": "VALIDATION_FAILED",
>     "details": [
>         {
>             "path": "",
>             "code": "additionalProperties",
>             "message": "should NOT have additional properties",
>             "info": {
>                 "additionalProperty": "my_field_xxx"
>             }
>         }
>     ],

**Comment by agnes512** [comment]
@MinSunLee could you share you model?

**Comment by rendy14s** [comment]
Hi @agnes512 

i am new on loopback and trying for learnig for my experince. But i have problem here.

i am following the documentation about Todo, and and make your own model, controller, repository.

When i try, i got the error message like this :

`{
  "error": {
    "statusCode": 422,
    "name": "UnprocessableEntityError",
    "message": "The request body is invalid. See error object `details` property for more info.",
    "code": "VALIDATION_FAILED",
    "details": [
      {
        "path": "",
        "code": "additionalProperties",
        "message": "must NOT have additional properties",
        "info": {
          "additionalProperty": "id"
        }
      }
    ]
  }
}`

This is my Model : 

`import {Entity, model, property} from '@loopback/repository';

@model()
export class User extends Entity {
  @property({
    type: 'string',
    id: true,
    generated: false
  })
  id?: string;

  @property({
    type: 'string',
    required: true,
  })
  isMerchant: string;

  @property({
    type: 'date',
  })
  createAt?: string;

  @property({
    type: 'date',
  })
  updateAt?: string;


  constructor(data?: Partial<User>) {
    super(data);
  }
}

export interface UserRelations {
  // describe navigational properties here
}

export type UserWithRelations = User & UserRelations;
`

And this is my Controller : 

`import {
  Count,
  CountSchema,
  Filter,
  FilterExcludingWhere,
  repository,
  Where
} from '@loopback/repository';
import {
  del, get,
  getModelSchemaRef, param, patch, post, put, requestBody,
  response
} from '@loopback/rest';
import {User} from '../models';
import {UserRepository} from '../repositories';

export class UserController {
  constructor(
    @repository(UserRepository)
    public userRepository: UserRepository,
  ) { }

  @post('/users')
  @response(200, {
    description: 'User model instance',
    content: {'application/json': {schema: getModelSchemaRef(User)}},
  })
  async create(
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(User, {
            title: 'NewUser',
            exclude: ['id'],
          }),
        },
      },
    })
    user: User,
  ): Promise<User> {
    return this.userRepository.create(user);
  }

  @get('/users/count')
  @response(200, {
    description: 'User model count',
    content: {'application/json': {schema: CountSchema}},
  })
  async count(
    @param.where(User) where?: Where<User>,
  ): Promise<Count> {
    return this.userRepository.count(where);
  }

  @get('/users')
  @response(200, {
    description: 'Array of User model instances',
    content: {
      'application/json': {
        schema: {
          type: 'array',
          items: getModelSchemaRef(User, {includeRelations: true}),
        },
      },
    },
  })
  async find(
    @param.filter(User) filter?: Filter<User>,
  ): Promise<User[]> {
    return this.userRepository.find(filter);
  }

  @patch('/users')
  @response(200, {
    description: 'User PATCH success count',
    content: {'application/json': {schema: CountSchema}},
  })
  async updateAll(
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(User, {partial: true}),
        },
      },
    })
    user: User,
    @param.where(User) where?: Where<User>,
  ): Promise<Count> {
    return this.userRepository.updateAll(user, where);
  }

  @get('/users/{id}')
  @response(200, {
    description: 'User model instance',
    content: {
      'application/json': {
        schema: getModelSchemaRef(User, {includeRelations: true}),
      },
    },
  })
  async findById(
    @param.path.string('id') id: string,
    @param.filter(User, {exclude: 'where'}) filter?: FilterExcludingWhere<User>
  ): Promise<User> {
    return this.userRepository.findById(id, filter);
  }

  @patch('/users/{id}')
  @response(204, {
    description: 'User PATCH success',
  })
  async updateById(
    @param.path.string('id') id: string,
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(User, {partial: true}),
        },
      },
    })
    user: User,
  ): Promise<void> {
    await this.userRepository.updateById(id, user);
  }

  @put('/users/{id}')
  @response(204, {
    description: 'User PUT success',
  })
  async replaceById(
    @param.path.string('id') id: string,
    @requestBody() user: User,
  ): Promise<void> {
    await this.userRepository.replaceById(id, user);
  }

  @del('/users/{id}')
  @response(204, {
    description: 'User DELETE success',
  })
  async deleteById(@param.path.string('id') id: string): Promise<void> {
    await this.userRepository.deleteById(id);
  }
}
`
