### ISSUE TITLE
[Docs] Revamp Docs UI Theme and layout

### ISSUE THREAD

**Issue by mitsos1os** [strongloop/loopback-next#5759]
## Suggestion

A documentation framework or custom styles should be applied to make the documentation easier to read as very well done on different frameworks

## Use Cases

As discussed in #5550,  the chaotically big amount of information found in the documentation page, in combination with its really plain appearance, contribute to making it harder to read through. 

Unfortunately I do not have the "stylistic" knowledge or backround to support this, I am just expressing my personal opinion on the matter. Let this issue be a place for anyone stating his opinion regarding the matter, suggesting frameworks, wireframes, etc...!

Related to Documentation Enhancements in #5113 

## Examples

NestJS 's documentation is a good example of UI Doc theme.

**Comment by dhmlau** [comment]
@mitsos1os, thanks for the suggestion. @achrinza had a similar proposal on the style/format changes in https://github.com/strongloop/loopback-next/issues/4632. I'd like to close this issue as duplicate and continue the discussion over there. Thanks.
