### ISSUE TITLE
Review and write content for all API docs

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-next#577]
Many methods, classes, interfaces, etc, in the API doc don't have descriptions.  This task is to go through and add useful descriptions.  

If desired, this work could be further decomposed for each module (@loopback/core, /context, /authentication, etc). 

--- 

In the apidocs, there are broken links (e.g. Array, ProviderMap) and missing descriptions in the arguments,

Example: https://apidocs.strongloop.com/@loopback%2fcore/#Application

## Acceptance Criteria
Go through each @loopback packages to fill in the missing descriptions and fix broken links

- [ ] core
- [ ] context
- [ ] authentication
- [ ] repository
- [ ] rest
- [ ] openapi-spec
- [ ] openapi-spec-builder

cc @crandmck @bschrammIBM

**Comment by dhmlau** [comment]
@bschrammIBM , do you think you can help on this task? Thanks.

**Comment by dhmlau** [comment]
Given that there are a large number of files, it might be more practical to fix issues as we go or when someone opens an issue.
