### ISSUE TITLE
ENOENT: no such file or directory, open 'C:\Pessoais\Estudos\Loopback\package.json'

### ISSUE THREAD

**Issue by andersonaskm** [strongloop/loopback-next#5772]
Hi, I´ve just installed lb4 cli and tried to build a new app from following the instructions from https://loopback.io/doc/en/lb4/Getting-started.html

When I try to npm start it shows the following errors

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Pessoais\Estudos\Loopback\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Pessoais\Estudos\Loopback\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

The only option that I disabled from scaffolding was RepositoryMixing because it was causing issues related to this thread https://github.com/strongloop/loopback-next/issues/5608

What else can I do?

**Comment by dhmlau** [comment]
@andersonaskm, which version of Node.js are you using?

**Comment by andersonaskm** [comment]
Hello

Windows 10
Node v 12.16.2
Npm 6.14.4

Thanks in advance...

**Comment by achrinza** [comment]
Make sure that you've `cd`-ed into the folder where the project was created in.

If the Getting Started tutorial was followed, then you'll need to do `cd getting-started` before `npm start`:

https://loopback.io/doc/en/lb4/Getting-started.html#starting-the-project

> The only option that I disabled from scaffolding was RepositoryMixin

AFAIK, disabling `RepositoryMixin` removes a lot of features from the LoopBack 4 to interact with databases. If there's an issue with `RepositoryMixin`, could you please open a new bug issue with a step-by-step guide and/or reproduction sandbox?

**Comment by andersonaskm** [comment]
Hi, I tried againt and got the following errors.

"teste" is the folder where I choose to run lb4 cli with all options enabled

C:\Pessoais\Estudos\Loopback\teste>npm start

> teste@1.0.0 start C:\Pessoais\Estudos\Loopback\teste
> npm run build && node -r source-map-support/register .


> teste@1.0.0 build C:\Pessoais\Estudos\Loopback\teste
> tsc

src/__tests__/acceptance/home-page.acceptance.ts:5:1 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

5 describe('HomePage', () => {
  ~~~~~~~~

src/__tests__/acceptance/home-page.acceptance.ts:9:3 - error TS2304: Cannot find name 'before'.

9   before('setupApplication', async () => {
    ~~~~~~

src/__tests__/acceptance/home-page.acceptance.ts:13:3 - error TS2304: Cannot find name 'after'.

13   after(async () => {
     ~~~~~

src/__tests__/acceptance/home-page.acceptance.ts:17:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

17   it('exposes a default home page', async () => {
     ~~

src/__tests__/acceptance/home-page.acceptance.ts:24:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

24   it('exposes self-hosted explorer', async () => {
     ~~

src/__tests__/acceptance/ping.controller.acceptance.ts:5:1 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

5 describe('PingController', () => {
  ~~~~~~~~

src/__tests__/acceptance/ping.controller.acceptance.ts:9:3 - error TS2304: Cannot find name 'before'.

9   before('setupApplication', async () => {
    ~~~~~~

src/__tests__/acceptance/ping.controller.acceptance.ts:13:3 - error TS2304: Cannot find name 'after'.

13   after(async () => {
     ~~~~~

src/__tests__/acceptance/ping.controller.acceptance.ts:17:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

17   it('invokes GET /ping', async () => {
     ~~

src/migrate.ts:9:13 - error TS2339: Property 'migrateSchema' does not exist on type 'TesteApplication'.

9   await app.migrateSchema({existingSchema});
              ~~~~~~~~~~~~~


Found 10 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! teste@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the teste@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\anderson.szalai\AppData\Roaming\npm-cache\_logs\2020-06-19T14_36_33_854Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! teste@1.0.0 start: `npm run build && node -r source-map-support/register .`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the teste@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\anderson.szalai\AppData\Roaming\npm-cache\_logs\2020-06-19T14_36_33_886Z-debug.log

C:\Pessoais\Estudos\Loopback\teste>

**Comment by achrinza** [comment]
@andersonaskm Thanks for the logs. Unfortunately, I haven't been able to replicate it from my end.

It seems like `node_modules` is corrupted. Could you please delete it and re-run `npm install`?

<details>
<summary>My "scaffolding & starting new lb4 app" logs</summary>

```sh
$ lb4 app
? Project name: getting-started
? Project description: Getting started tutorial
? Project root directory: getting-started
? Application class name: StarterApplication
? Select features to enable in the project Enable eslint, Enable prettier, Enable mocha, Enable loopbackBuild, Enable vscode, Enable docker, Enable repositories, Enable services
    force .yo-rc.json
   create .eslintignore
   create .eslintrc.js
   create .mocharc.json
   create .npmrc
   create .prettierignore
   create .prettierrc
   create DEVELOPING.md
   create package.json
   create README.md
   create tsconfig.json
   create .vscode\settings.json
   create .vscode\tasks.json
   create .gitignore
   create .dockerignore
   create Dockerfile
   create public\index.html
   create src\application.ts
   create src\index.ts
   create src\migrate.ts
   create src\openapi-spec.ts
   create src\sequence.ts
   create src\controllers\index.ts
   create src\controllers\ping.controller.ts
   create src\controllers\README.md
   create src\datasources\README.md
   create src\models\README.md
   create src\repositories\README.md
   create src\__tests__\README.md
   create src\__tests__\acceptance\home-page.acceptance.ts
   create src\__tests__\acceptance\ping.controller.acceptance.ts
   create src\__tests__\acceptance\test-helper.ts

> core-js@3.6.5 postinstall C:\Users\rifaa\getting-started\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall C:\Users\rifaa\getting-started\node_modules\ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> ejs@3.1.3 postinstall C:\Users\rifaa\getting-started\node_modules\@loopback\rest-explorer\node_modules\ejs
> node --harmony ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN getting-started@1.0.0 No license field.

added 644 packages from 811 contributors and audited 654 packages in 174.211s

66 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


Application getting-started was created in getting-started.

Next steps:

$ cd getting-started
$ npm start


rifaa@LAPTOP-DHVDTT1Q MSYS ~
$ cd getting-started/

rifaa@LAPTOP-DHVDTT1Q MSYS ~/getting-started
$ npm start

> getting-started@1.0.0 prestart C:\Users\rifaa\getting-started
> npm run build


> getting-started@1.0.0 build C:\Users\rifaa\getting-started
> lb-tsc


> getting-started@1.0.0 start C:\Users\rifaa\getting-started
> node -r source-map-support/register .

Server is running at http://[::1]:3000
Try http://[::1]:3000/ping
```

</details>

Could you also please run the following commands in Git Bash and provide the output?

```sh
  node -e 'console.log(process.platform, process.arch, process.versions.node)'
  npm ls --prod --depth 0 | grep loopback
```

**Comment by andersonaskm** [comment]
![image](https://user-images.githubusercontent.com/8411131/85161250-e00a3e80-b235-11ea-807b-bc57e7b08886.png)

**Comment by andersonaskm** [comment]
![image](https://user-images.githubusercontent.com/8411131/85161325-fb754980-b235-11ea-8bbf-5c1a97ccf744.png)

**Comment by andersonaskm** [comment]
And I tried to delete the folder and run npm install... the result is still the same... same errors :(

**Comment by dhmlau** [comment]
Just wanna make sure.. could you please also run `npm run clean`? i.e.
```
npm run clean && npm run build
```

Thanks.

**Comment by andersonaskm** [comment]
Same problem....

C:\Pessoais\Estudos\Loopback\teste>npm run clean && npm run build

> teste@1.0.0 clean C:\Pessoais\Estudos\Loopback\teste
> rimraf dist *.tsbuildinfo .eslintcache


> teste@1.0.0 build C:\Pessoais\Estudos\Loopback\teste
> tsc

src/__tests__/acceptance/home-page.acceptance.ts:5:1 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

5 describe('HomePage', () => {
  ~~~~~~~~

src/__tests__/acceptance/home-page.acceptance.ts:9:3 - error TS2304: Cannot find name 'before'.

9   before('setupApplication', async () => {
    ~~~~~~

src/__tests__/acceptance/home-page.acceptance.ts:13:3 - error TS2304: Cannot find name 'after'.

13   after(async () => {
     ~~~~~

src/__tests__/acceptance/home-page.acceptance.ts:17:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

17   it('exposes a default home page', async () => {
     ~~

src/__tests__/acceptance/home-page.acceptance.ts:24:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

24   it('exposes self-hosted explorer', async () => {
     ~~

src/__tests__/acceptance/ping.controller.acceptance.ts:5:1 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

5 describe('PingController', () => {
  ~~~~~~~~

src/__tests__/acceptance/ping.controller.acceptance.ts:9:3 - error TS2304: Cannot find name 'before'.

9   before('setupApplication', async () => {
    ~~~~~~

src/__tests__/acceptance/ping.controller.acceptance.ts:13:3 - error TS2304: Cannot find name 'after'.

13   after(async () => {
     ~~~~~

src/__tests__/acceptance/ping.controller.acceptance.ts:17:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

17   it('invokes GET /ping', async () => {
     ~~

src/migrate.ts:9:13 - error TS2339: Property 'migrateSchema' does not exist on type 'TesteApplication'.

9   await app.migrateSchema({existingSchema});
              ~~~~~~~~~~~~~


Found 10 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! teste@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the teste@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\anderson.szalai\AppData\Roaming\npm-cache\_logs\2020-06-19T20_15_16_205Z-debug.log

**Comment by dhmlau** [comment]
hm. Do you mind to try `npm run clean` and then `lb4 update`? `lb4 update` command will make sure the dependencies are updated. 
Sorry that I wasn't able to verify my suggestion because I cannot reproduce the problem. :(

**Comment by andersonaskm** [comment]
Still the same :(

C:\Pessoais\Estudos\Loopback\teste>npm run clean

> teste@1.0.0 clean C:\Pessoais\Estudos\Loopback\teste
> rimraf dist *.tsbuildinfo .eslintcache


C:\Pessoais\Estudos\Loopback\teste>lb4 update
The project dependencies are compatible with @loopback/cli@2.9.0

C:\Pessoais\Estudos\Loopback\teste>npm run clean && npm run build

> teste@1.0.0 clean C:\Pessoais\Estudos\Loopback\teste
> rimraf dist *.tsbuildinfo .eslintcache


> teste@1.0.0 build C:\Pessoais\Estudos\Loopback\teste
> tsc

src/__tests__/acceptance/home-page.acceptance.ts:5:1 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

5 describe('HomePage', () => {
  ~~~~~~~~

src/__tests__/acceptance/home-page.acceptance.ts:9:3 - error TS2304: Cannot find name 'before'.

9   before('setupApplication', async () => {
    ~~~~~~

src/__tests__/acceptance/home-page.acceptance.ts:13:3 - error TS2304: Cannot find name 'after'.

13   after(async () => {
     ~~~~~

src/__tests__/acceptance/home-page.acceptance.ts:17:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

17   it('exposes a default home page', async () => {
     ~~

src/__tests__/acceptance/home-page.acceptance.ts:24:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

24   it('exposes self-hosted explorer', async () => {
     ~~

src/__tests__/acceptance/ping.controller.acceptance.ts:5:1 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

5 describe('PingController', () => {
  ~~~~~~~~

src/__tests__/acceptance/ping.controller.acceptance.ts:9:3 - error TS2304: Cannot find name 'before'.

9   before('setupApplication', async () => {
    ~~~~~~

src/__tests__/acceptance/ping.controller.acceptance.ts:13:3 - error TS2304: Cannot find name 'after'.

13   after(async () => {
     ~~~~~

src/__tests__/acceptance/ping.controller.acceptance.ts:17:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

17   it('invokes GET /ping', async () => {
     ~~

src/migrate.ts:9:13 - error TS2339: Property 'migrateSchema' does not exist on type 'TesteApplication'.

9   await app.migrateSchema({existingSchema});
              ~~~~~~~~~~~~~


Found 10 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! teste@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the teste@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\anderson.szalai\AppData\Roaming\npm-cache\_logs\2020-06-19T20_25_10_223Z-debug.log

**Comment by dougal83** [comment]
Very odd, does `npm i @types/mocha` not resolve the issue?

**Comment by andersonaskm** [comment]
Nope. Afetr installing @types/mocha, several errors disappeared but still not initialize

Above is the log that I´ve captured from npm-cache/_logs

9 verbose lifecycle teste@1.0.0~start: CWD: C:\Pessoais\Estudos\Loopback\teste
10 silly lifecycle teste@1.0.0~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm run build && node -r source-map-support/register .'
10 silly lifecycle ]
11 silly lifecycle teste@1.0.0~start: Returned: code: 2  signal: null
12 info lifecycle teste@1.0.0~start: Failed to exec start script
13 verbose stack Error: teste@1.0.0 start: `npm run build && node -r source-map-support/register .`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid teste@1.0.0

Maybe could help...

**Comment by dougal83** [comment]
OK, that is fishy. Seems to me like `npm install` not running as expected. Could you try `npm ci` or deleting `node_modules` and running `npm install` again. If that fails could you ensure there are no `node_modules` in parent folder(s) and try again?

**Comment by achrinza** [comment]
It may also be caused by a bad `package.json` file. Could you try re-scaffolding the application with the all the defaults?

If that doesn't work, could you publish a copy of the application on a GitHub repo? That way, we can have a full picture of the scaffold-ed application.

**Comment by andersonaskm** [comment]
All right - I did the following - I guess that after first installation maybe something was corrupted... I tried to uninstall and install again and apparentely it worked!!! Thanks for all support!!! 

1) Uninstall LB4 cli: $ npm uninstall -g @loopback/cli

2) Installed it again: $ npm install -g @loopback/cli

It shows the following messages after that

![image](https://user-images.githubusercontent.com/8411131/85203378-caebe900-b2e3-11ea-80b4-543035ebcd3c.png)

3) Selected all options

![image](https://user-images.githubusercontent.com/8411131/85203418-1900ec80-b2e4-11ea-8c84-e8fe7edb7fdd.png)

4) After the, those messages appeared

![image](https://user-images.githubusercontent.com/8411131/85203479-8c0a6300-b2e4-11ea-9bd7-b7e16d61d449.png)

5) Then it worked

![image](https://user-images.githubusercontent.com/8411131/85203518-b4925d00-b2e4-11ea-9366-a32fca41aad5.png)

**Comment by achrinza** [comment]
Glad to hear it works! I’ll go ahead and close the issue as solved.
