### ISSUE TITLE
docs: improve the structure of "Behind the scenes" sidebar + find a better name

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#5776]
At the moment, "Behind the scenes" contains a list of topics in a seemingly random order.

<img width=150 src="https://user-images.githubusercontent.com/1140553/85109703-0918d800-b212-11ea-9564-441725f190ef.png">

Let's find a better organization of the items in this list.

Ideas to consider:

- Sort the entries from A to Z, possibly keeping "Crafting LoopBack 4" at the top
- Reorganize the entries into subsection aligned around different usage scenarios or architecture layer they belong to: Build REST APIs, Access databases, Access existing services,  Authentication/authorization, Cloud native, Dependency Injection & IoC, etc.
- Quoting https://github.com/strongloop/loopback-next/pull/5718#discussion_r439208811:

    > Maybe we should use a consistent order from top to bottom, from left to right? For example:
    >
    > Application/Component/Context/Binding
    > Server/Sequence/Action/Route/Controller/Repository/Service/Model/Relation/DataSource

We should  update the contents of "Behind-the-scene.md" accordingly too.

See also:
- Improve the structure of "Usage scenarios" (how-to guides) sidebar #5777

While we are discussing "Behind the scenes", let's try to find a better name for this section too (see the discussion in https://github.com/strongloop/loopback-next/pull/5718 for more details).

_This story is a part of #5113 Documentation improvements 2020Q3_

## Acceptance criteria 

- [ ] categorize concepts into subsections by responsiblities
- [ ] reorganize entires in Behind-the-scene.md as well

**Comment by jannyHou** [comment]
Given the discussions above, I tested with several refactor plans:

## Rename "Behind the scene"

The preview is pretty straightforward, just a name change.

### Choice 1: rename to "Concepts"
<img width="1179" alt="concepts+az+1" src="https://user-images.githubusercontent.com/12554153/89446979-433b2c00-d723-11ea-8065-771d13560b10.png">

### Choice 2: rename to "Fundamental"
<img width="1183" alt="fundamental+az+1" src="https://user-images.githubusercontent.com/12554153/89447276-b93f9300-d723-11ea-9cd6-7a2be1747c27.png">

## Reorganize items

(Personal opinion: New plans are much better than the current layout. I don't get lost for either of them.)

### Alphabetical

List items from a-->z. (Personal opinion: Good when have less items.)

<img width="1181" alt="concepts+az+2" src="https://user-images.githubusercontent.com/12554153/89446980-43d3c280-d723-11ea-87eb-fce2d4c2a03b.png">

### Subsections

Organize by categories. (Personal opinion: Good when have large number of items.)

fold subsections
<img width="1180" alt="Screen Shot 2020-08-05 at 1 08 04 PM" src="https://user-images.githubusercontent.com/12554153/89447874-bb562180-d724-11ea-9176-d4c3a50408b2.png">

unfold subsections - part1
<img width="1183" alt="Screen Shot 2020-08-05 at 1 08 35 PM" src="https://user-images.githubusercontent.com/12554153/89447876-bb562180-d724-11ea-9cac-c54bf114e7b0.png">

unfold subsections - part2
<img width="1179" alt="Screen Shot 2020-08-05 at 1 08 46 PM" src="https://user-images.githubusercontent.com/12554153/89448042-02441700-d725-11ea-9f8f-5a99ae8d6feb.png">


## DISCUSSION

Let's first discuss and agree on the choices:

- Rename "Behind the scene"
  - choice 1: "Concepts"
  - choice 2: "Fundamental"
  - others

- Reorganize items
  - choice 1: alphabet. 
    - next step: update the list on page "Behind the scene" with the same sequence
  - choice 2: subsections by category. 
    - next step: update page "Behind the scene" and create pages for each subsections.
  - others
    - (I found the 3rd choice confused, cc @bajtos @raymondfeng could you explain more about it? Thanks!)
       > Quoting #5718 (comment):
       > Maybe we should use a consistent order from top to bottom, from left to right? For example:
       > Application/Component/Context/Binding
       > Server/Sequence/Action/Route/Controller/Repository/Service/Model/Relation/DataSource

**Comment by agnes512** [comment]
Thanks for kicking it off! I like the name "Concepts". As for organization, I think subsections by category with alphabetical order is better in the matter of navigation.

**Comment by raymondfeng** [comment]
1. I vote for `Concepts` or `Architectural Concepts`

2. I would like to see categories as subtitles for concepts

- Core
   - Application
   - Component
   - Context
   - Binding
   - Dependency Injection
   - Interceptor
   - Life cycle event and observer
   - Service
   - Booter

- REST API
   - Server
   - Sequence
   - Middleware  
   - Route
   - Controller
  - Request/response cycle

- Data access
   - Model
   - Relation
   - Repository
   - DataSource
   - Connector

- TypeScript
   - Decorator
   - Mixin

3. We should uniformly use `singular` or `plural` terms, such as `Model` vs. `Models`.

**Comment by hacksparrow** [comment]
> I like the name "Concepts". As for organization, I think subsections by category with alphabetical order is better in the matter of navigation.

Exactly.

**Comment by bajtos** [comment]
Thank you @jannyHou for the screenshots of different versions, they make it easier to compare different proposals 👏🏻 

Regarding the new name: the purpose of this section is to explain concepts. Quoting from https://documentation.divio.com/explanation/:

> Explanation, or discussions, _clarify and illuminate a particular topic_. They broaden the documentation’s coverage of a topic.

I feel the name "fundamentals" is too narrow, we want to include information for non-fundamental topics too.

The name "Concepts" looks reasonable to me 👍🏻  Maybe "Concepts & explanations" would be even better?

As for organization of the pages, I vote for category-based subsections containing pages in alphabetical order. A picture from your proposal that I like:

![](https://user-images.githubusercontent.com/12554153/89447874-bb562180-d724-11ea-9176-d4c3a50408b2.png)

I don't have a strong opinion on how to organize individual pages, I am fine to adopt Raymond's proposal from https://github.com/strongloop/loopback-next/issues/5776#issuecomment-669524313.

**Comment by jannyHou** [comment]
Great so we all like the following plan:
- name "Concepts" (options: "Architecture Concepts" and "Concepts & Explanations")
- order: "subsections by category with alphabetical order"

Thanks everyone, PR coming

**Comment by jannyHou** [comment]
Related PR merged, closing
