### ISSUE TITLE
docs: improve the structure of "Usage scenarios" (how-to guides) sidebar

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#5777]
At the moment, "Usage scenarios" sidebar is a bit messy:

<img width=150 src="https://user-images.githubusercontent.com/1140553/85110114-af64dd80-b212-11ea-997a-d84564f1067d.png">

Some pages are nested under subcategories like "Access databases" and "Deployment", others are at top level ("Using Express Middleware", "Running cron jobs", etc.)

Let's reorganize the how to guides along different usage scenarios they belong to: Build REST APIs, Access databases, Access existing services, Authentication/authorization, Cloud native, Dependency Injection & IoC, etc.

- Keep "Usage scenarios" ("How-to guides") at the first level.
- All second level items should be groups - Build REST APIs, Access Databases, etc.
- Individual documentation pages are listed at third (or possibly fourth) level.

Use [Deployment](http://loopback.io/doc/en/lb4/Deployment.html) as the example to follow.

See also:
- Improve the structure of "Behind the scenes" sidebar #5776

_This story is a part of #5113 Documentation improvements 2020Q3_

## Acceptance criteria 

- Keep "Usage scenarios" ("How-to guides") at the first level.
- All second level items should be groups - Build REST APIs, Access Databases, etc.
- Individual documentation pages are listed at third (or possibly fourth) level.

Use [Deployment](http://loopback.io/doc/en/lb4/Deployment.html) as the example to follow.

**Comment by jannyHou** [comment]
### A proposal of the new layout:

Building REST APIs
  - Booting and mounting a LoopBack 3 application
  - Creating CRUD REST APIs from a model
  - Customizing how OpenAPI spec is served
  - Dynamically adding models, repositories, and controllers
  - Self-hosted REST API explorer
  - Serving static files
  - Uploading and downloading files
  - Using express middleware

Creating Other Forms of APIs
  - Exposing GraphQL APIs

Accessing Database
  - Database migrations
  - Using database transactions
  - Working with data

Using TypeORM
  - How to use TypeORM with LoopBack

Validation
  - Validation in REST Layer
  - Validation in the Controller, Repository and Service Layer
  - Validation in ORM Layer

Security
  - Authentication
  - Authorization

Deployment
  - Enabling HTTPS
  - Deploying to IBM cloud
  - Deploying to Kubernetes on IBM cloud
  - Deploying with pm2 and nginx
  - Developing and Deploying LoopBack Applications with Appsody

Accessing services
  - Calling other services

Running and debugging apps
  - Setting debug strings
  - Using strong-error-handler
  - Running cron jobs

Metrics
  - Health check
  - Metrics for Prometheus

--- 

Compare with the current layout, see picture in https://github.com/strongloop/loopback-next/issues/5777#issue-641783854

cc @strongloop/loopback-maintainers PTAL and share your feedback, appreciate it :)
After we agree on the layout and titles, I will create a PR for it.

**Comment by raymondfeng** [comment]
### A proposal of the new layout:

Building REST APIs
  - Creating CRUD REST APIs from a model
  - Customizing how OpenAPI spec is served
  - Dynamically adding models, repositories, and controllers
  - Self-hosted REST API explorer
  - Serving static files
  - Uploading and downloading files
  - Using express middleware
  - Booting and mounting a LoopBack 3 application

Creating Other Forms of APIs
  - Exposing GraphQL APIs

Accessing Database
  - Working with data
  - Using database transactions
  - Database migrations

  - Using TypeORM
    - How to use TypeORM with LoopBack

Accessing services
  - Calling other services

Validation
  - Validation in REST Layer
  - Validation in the Controller, Repository and Service Layer
  - Validation in ORM Layer

Security
  - Authentication
  - Authorization

Deployment
  - Enabling HTTPS
  - Deploying to IBM cloud
  - Deploying to Kubernetes on IBM cloud
  - Deploying with pm2 and nginx
  - Developing and Deploying LoopBack Applications with Appsody

Running and debugging apps
  - Setting debug strings
  - Using strong-error-handler

Other extensions
  - Health check
  - Metrics for Prometheus
  - Logging
  - Running cron jobs
  - Pooling

**Comment by agnes512** [comment]
This might be out of scope but I found [Creating Other Forms of APIs](https://loopback.io/doc/en/lb4/Create-other-forms-of-apis.html) page doesn't have ant content, which looks weird to me.

**Comment by jannyHou** [comment]
Thank you @raymondfeng @agnes512 for the feedback. @agnes512 I think that page is just created as a subsection page, my next PR is going to add all the subsection pages but with some brief contents describing them.

**Comment by dhmlau** [comment]
I believe @bajtos had a fix to allow "empty page" not showing up but to expand/collapse the section. "Building REST APIs" item behave this way. Another option to think about. :)

**Comment by jannyHou** [comment]
@dhmlau thanks for the suggestion! You are right omitting the url is easier, and I removed the empty page. PR created in https://github.com/strongloop/loopback-next/pull/6081

**Comment by jannyHou** [comment]
Related PRs merged, closing
