### ISSUE TITLE
docs: untangle connector reference into reference, how-to guides and tutorials

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#5786]
Quoting https://github.com/strongloop/loopback-next/pull/5718#issuecomment-642775520

> Another concern is the `connectors reference` entry. It's a bit weird to see it under references because they are actually mixed with `how to`s and `tutorials` 🙈

Let's review the documentation for connectors and rework it into reference guides, how-to guides and tutorials.

_This is a follow-up to #5718, see also #5549._

**Comment by dhmlau** [comment]
Closing in favor of #6091, #6092 and #6093
