### ISSUE TITLE
Does not support Node <=v10.15.0

### ISSUE THREAD

**Issue by andrey-abramow** [strongloop/loopback-next#5789]
Steps to reproduce:
- use node v10.13.0
- lb4 pr_name (@loopback/cli version: 2.9.0)
- cd  pr_name
- yarn start
```
Cannot start the application. TypeError: events_1.once is not a function
    at HttpServer.start (/Users/andreyabramow/Development/loopback-4-db-test/node_modules/@loopback/http-server/src/http-server.ts:122:20)
    at RestServer.start (/Users/andreyabramow/Development/loopback-4-db-test/node_modules/@loopback/rest/src/rest.server.ts:958:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
`events.once` added to a node in version 10.16,  so this code

```
 /**
   * Starts the HTTP / HTTPS server
   */
  public async start() {
    console.log('SSS')

    this.server.listen(this.serverOptions);
    try {
      await once(this.server, 'listening'); // error
      this._listening = true;

      const address = this.server.address();
      assert(address != null);
      this._address = address!;
    } catch(e) {
        console.log(e)
    }
  }
```
from https://github.com/strongloop/loopback-next/blob/master/packages/http-server/src/http-server.ts#L7

does not work in older versions of node (10 < v < 10.6).

Can you please just update documentation something like
**Node.js >= 10.16**
And adding some checking of the version to `cli` would be great as well.
Thanks!

**Comment by bajtos** [comment]
@andrey-abramow good catch, thank you for reporting the problem! I was not aware that `events.once` was added in a later version of Node.js 10.x when I removed `p-once` in https://github.com/strongloop/loopback-next/pull/5429.

Would you like to contribute this change yourself? I would start with updating `engines` field in all packages changed by #5429:

```diff
- "node": ">=10" 
+ "node": ">=10.16"
```

- `benchmark/package.json`
- `examples/express-composition/package.json`
- `examples/lb3-application/package-lock.json`
- `examples/lb3-application/package.json`
- `examples/passport-login/package.json`
- `examples/rpc-server/package.json`
- `extensions/cron/package.json`
- `extensions/health/package.json`
- `extensions/logging/package.json`
- `extensions/metrics/package.json`
- `packages/booter-lb3app/package.json`
- `packages/booter-lb3app/package.json`
- `packages/cli/package.json`
- `packages/core/package.json`
- `packages/http-caching-proxy/package.json`
- `packages/http-server/package.json`
- `packages/tsdocs/package.json`


Considering the long list of packages affected, it may be best to change all packages in the monorepo.

**Comment by dougal83** [comment]
Also, update readme.md? https://github.com/strongloop/loopback-next#installation

**Comment by achrinza** [comment]
This also needs to be updated: https://github.com/strongloop/loopback.io/blob/6bb8594c22b4d9b61991ae246a267e6820932d5f/pages/en/contrib/LTS.md#overview
