### ISSUE TITLE
docs: Testing your extension

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#579]
## Overview

[Thinking in LoopBack](http://loopback.io/doc/en/lb4/Thinking-in-LoopBack.html) explains how to write tests for as part of app development. We should create a similar content explaining _extension developers_ how to write a good test suite.

## Acceptance Criteria
- Verify if the [Thinking In LoopBack](http://loopback.io/doc/en/lb4/Thinking-in-LoopBack.html) docs provide a solid approach for testing your components/extensions.
- Extend "Writing Extensions" to describe how to test:
  - providers
  - controllers
  - repositories
  - SequenceActions (REST-specific)
  - mixins (adding application methods/configuration)
    - how to test controllers/repositories provided by the mixin
    - testing to ensure your mixin is available to _other_ components (`app.component(...)` API)
    - introducing new binding sugar functions (`app.foo(...)`) see #541 for an example

See also #525 and #553

**Comment by dhmlau** [comment]
Marking as `p1` because i believe this is a must-have for beta.

**Comment by dhmlau** [comment]
Discussed with @bajtos, will make this as a stretch goal for Sprint 48 (start the work on Sprint 48 and aim to finish on Sprint 49)
