### ISSUE TITLE
Updating Docs for Using / Writing Components

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#580]
## Overview
Mixins can do something useful for components being used in a LBNext application. An example is the `RepositoryMixin` which takes any repositories declared by a component and binds the repositoryClass to `repositories.*`. The mixin also binds any repositories declared by the Application in the constructor as well as using the sugar method `app.repository()`. 

Writing Components Docs & Using Component Docs need to be updated to show users how they can interact with Mixins (Repository mixin above is just used as an example!). 

## Acceptance Criteria

- [ ] Update Docs
  - [ ] https://github.com/strongloop/loopback-next/wiki/Using-Components
  - [ ] https://github.com/strongloop/loopback-next/wiki/Writing-Components
  - possibly other places. 

Note: __Update on loopback.io instead__

**Comment by jannyHou** [comment]
We probably should have a single page for concept `mixin` first, here is some topic we can add in it:

- create a mixin function
- apply mixins by `MixinBuilder` from lib `mixin.ts`

Some refactor work:

- Move `mixin.ts` from `repository` to `core`
- Apply `RepositoryMixin` by `MixinBuilder`

**Comment by jannyHou** [comment]
PR ready to merge and waiting for the fix of hursley registry .

**Comment by jannyHou** [comment]
Merged https://github.com/strongloop/loopback.io/pull/491 and close the issue.
