### ISSUE TITLE
Update Appsody stack

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#5802]
## Suggestion

Update the nodejs-loopback4 Appsody stack to use the scaffold generated by the latest LoopBack 4 CLI version.

## Use Cases

Currently, the Appsody stack uses an older scaffold. This means that dependencies need to be updated using `lb4 update` and manual updates (e.g. #5368) are necessary. This isn't an intuitive developer experience.

This DX improvement also have a domino effect on other devops toolings that use Appsody stacks, such as the Appsody k8s operator, and Eclipse Codewind.

## Examples

N/A

## Acceptance criteria

TBD - will be filled by the team.

---

Assigned @raymondfeng as the owner of the Appsody stack (Please correct me if this is wrong).

**Comment by jannyHou** [comment]
Thanks @achrinza sounds reasonable to me. cc @raymondfeng can we automate the appsody stack update after each release?

**Comment by jannyHou** [comment]
Related to https://github.com/strongloop/loopback-next/pull/4250

**Comment by achrinza** [comment]
Will be closed by https://github.com/appsody/stacks/pull/863

**Comment by achrinza** [comment]
Closing as done.
