### ISSUE TITLE
ci: Commit Linter needs to allow multiple packages listed in scope

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#581]
## Overview
A key benefit of lerna is the ability of being able to change multiple packages if needed in one PR to make fixes and feature implementation easier. 

Conventional Commit message guidelines require the header format to be `<type>(<scope>): <description>` where scope is the affected package name. Travis CI enforces this convention using `commitlint`.

Depending on the outcome of https://github.com/marionebl/commitlint/issues/75 we need to create the new `scope-types` rule (if / when) there is a plugin API available for `commitlint`
*OR*
We need to implement our own solution that can leverage `conventional-commits-parser` with a custom `headerPattern` (adding `,` to the default pattern). Then split it and check against available packages (check commitlint's lerna config for getting scope-enum automatically). 

## Acceptance Criteria

- [ ] One of the above two solutions (or another) implemented that allows me to make a commit with no scope, 1 package in scope, 2 or more packages in scope. All packages in scope must be valid.

**Comment by marionebl** [comment]
Relevant issue with `conventional-commits-parser`: https://github.com/conventional-changelog/conventional-changelog/issues/232

**Comment by bajtos** [comment]
IMO, this is a "nice to have" feature. Commits modifying multiple packages are omitting the scope now and I don't remember any issues caused by the missing scope.

I am proposing to close this issue and focus on more important tasks.

@virkt25 thoughts?

**Comment by virkt25** [comment]
I agree, plus this change is something we would pick up from conventional-commits if it's implemented there. Closing for now.
