### ISSUE TITLE
Limit when used in a relation filter doesn't work as intended

### ISSUE THREAD

**Issue by anjorinjnr** [strongloop/loopback-next#5817]
## Steps to reproduce

Create 2 models with 1:M relationship

e.g 
```
@model(..)
export class Forum {
 ...
  @hasMany(() => Thread, {keyTo: 'forumId'})
  threads?: Thread[];
}
 ...
```

```
@model(...)
export class Thread {
 ...
  forumId: string;
}
 ...

```

## Current Behavior
To get a forum with the most recently updated Thread, 

```
...
forumRepo.find({
   where: {
     somefield: "value",
    },
   include: [
         relation: 'threads',
          scope: {
            limit: 1,
            order: ['updatedAt DESC'],
      ]
  },
}
```
Only includes threads in one of the forums in the result. If you remove the limit:1, every forum has threads. It's as if the limit is applied to the forum, i.e only 1 forum can include the threads relation.

## Expected Behavior
Each forum with a thread, should include a threads field(array) with the most recently updated thread.

**Comment by madaky** [comment]
@anjorinjnr : Could you produce a sandbox for debug the condition.

**Comment by anjorinjnr** [comment]
When I try npm start from the todo-list example, after an npm install
I keep getting these errors

 Cannot read file '/Users/ebby/packages/boot/tsconfig.json'.


Why is it trying to reference files in the packages folder?

**Comment by anjorinjnr** [comment]
Reproduced here 
https://github.com/anjorinjnr/loopback-next/tree/relation-issue

`npm test -- -f TodoController` to run the specific test.

**Comment by anjorinjnr** [comment]
> Reproduced here
> https://github.com/anjorinjnr/loopback-next/tree/relation-issue
> 
> `npm test -- -f TodoController` to run the specific test.
