### ISSUE TITLE
StrongLoop website still references Gitter chat room

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#5832]
## Steps to reproduce

1. Navigate to https://strongloop.com/faq/

## Current Behavior

The Gitter chat room is still referenced as a place for active community support:

![image](https://user-images.githubusercontent.com/25147899/85852752-d196c680-b7e3-11ea-8c66-33000437ed34.png)

## Expected Behavior

The Slack org should be referenced instead.

## Link to reproduction sandbox

N/A
## Additional information

N/A

## Related Issues

N/A

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
Thanks @achrinza for catching that. I've submitted a PR to fix it.
