### ISSUE TITLE
docs: add HasManyThrough relation

### ISSUE THREAD

**Issue by agnes512** [strongloop/loopback-next#5835]
## Description

Add definition, set up, configuration, example, and diagrams for HasManyThrough relation.

## Acceptance Criteria

- [x] Add a new page under https://loopback.io/doc/en/lb4/Relations.html for HasManyThrough. It should be similar to HasMany https://loopback.io/doc/en/lb4/HasMany-relation.html but not as many as details since it's a subset of HasMany
- [x] add tests for self through and add a section https://loopback.io/doc/en/lb3/HasManyThrough-relations.html#self-through
- [x] List out limitations: 
  - only supports using the id properties as the foreign key for now
  - no inclusion yet

**Comment by dhmlau** [comment]
@agnes512, i guess it makes sense to get to this in July.. to continue with your work on hasManyThrough?

**Comment by agnes512** [comment]
> @agnes512, i guess it makes sense to get to this in July.. to continue with your work on hasManyThrough?

Sounds good.

**Comment by agnes512** [comment]
Should fix #5852 first.

**Comment by agnes512** [comment]
Closing as done
