### ISSUE TITLE
How to make authentication User model in loopback 4 to have unique values in its schema?

### ISSUE THREAD

**Issue by lemchen** [strongloop/loopback-next#5846]
I want to make email: string, property in authentication User model unique, is there a way to do that?

**Comment by jannyHou** [comment]
@lemchen You can specify the `email` as the id for `User`, like

```ts
@model()
export class Product extends Entity {
  @property({
    id: true,
    description: 'The unique identifier for a product',
  })
  email: string;
}
```

You can also specify `defaultFn` for other properties to generate uuid value for them. But it's not proper for `email`. See the [property decorator](https://loopback.io/doc/en/lb4/Model.html#property-decorator), `defaultFn`.

**Comment by lemchen** [comment]
> @lemchen You can specify the `email` as the id for `User`, like
> 
> ```ts
> @model()
> export class Product extends Entity {
>   @property({
>     id: true,
>     description: 'The unique identifier for a product',
>   })
>   email: string;
> }
> ```
> 
> You can also specify `defaultFn` for other properties to generate uuid value for them. But it's not proper for `email`. See the [property decorator](https://loopback.io/doc/en/lb4/Model.html#property-decorator), `defaultFn`.

OK, i got it.
