### ISSUE TITLE
@property.array does not convert string to MongoDB ObjectId

### ISSUE THREAD

**Issue by haotangio** [strongloop/loopback-next#5848]
## Backgrounds
I'm building many-many relation on MongoDB but LB4 doesn't support ReferencesMany yet so in the meantime I have to work-around by configure entity like below:
```
// film.ts
...
@property.array(String, {mongodb: {dataType: 'ObjectID'}})
directorIds: Array<string>;
...
```

## Steps to reproduce

When I save `directorIds` like below. The ID array is stored as string in MongoDB.
```
// film-controller.ts

...
film.directorIds = ['5eec55b897e7bf6b05210e48', '5eec55b897e7bf6b05210e49'];
await this.filmRepository.save(film);
...
```

## Current Behavior

The ID array is stored as list of string in MongoDB.

## Expected Behavior

The ID array is stored as list of ObjectId in MongoDB.

## Additional information
The root cause of this problem is that ReferencesMany is not supported yet while it's the critical feature to develop any systems using MongoDB. There is no timeline for it and the GH ticket for it is staled for almost a year.

**Comment by jannyHou** [comment]
Thank you @agnes512 for helping triage this issue!
