### ISSUE TITLE
ci: Implement a local commit linter using Husky

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#585]
Currently `commitlint` is configured to run on Travis. It is possible to configure it to run commitlint locally using `Husky` by tying into the commithook. This will allow developers to know if their commit message is valid when they write it instead of waiting to figure out once Travis is done running. 

We would still keep the Travis check as an enforcement but this will make developer / contributor experience for `@loopback` more pleasant.

**Comment by dhmlau** [comment]
@virkt25 , as discussed, this can be a core GA item.  thanks.

**Comment by kjdelisle** [comment]
@dhmlau @raymond I think we should do this sooner. Waiting on remote CI to validate my commit messages is a very large time sink and handling it before it gets pushed to a PR is a must, IMO.
