### ISSUE TITLE
How can we use order by field function on Mysql connector? (Loopback 4)

### ISSUE THREAD

**Issue by vodoanthanh** [strongloop/loopback-next#5867]
Currently, I want to use the field function to order by values. 

This is my order in code

```
 order: ["field('id', '1')"]
```

Expected:

```
SELECT * 
FROM `videos` 
ORDER BY field('id','1')
```

Actual:

```
SELECT * 
FROM `videos` 
ORDER BY `field('id'`,`'1')`
```
Are there any functions or ways for that?
Thanks!

**Comment by vodoanthanh** [comment]
@raymondfeng Please help me

**Comment by achrinza** [comment]
This isn't possible due to potential vulnerabilities arising from allowing unescaped SQL from clients. However, a custom controller function can take in custom parameters and use the `.execute()` function:

```
yourRepo.execute("SELECT *  FROM `videos`  ORDER BY field('id','1')")
```

**Comment by dhmlau** [comment]
Closing as the question has been resolved.
