### ISSUE TITLE
Unable to perform nested include in filter since @loopback-rest 5.2.0

### ISSUE THREAD

**Issue by hessman** [strongloop/loopback-next#5872]
Hi loopback team ! 

The last publish seems to have introduced a regression.

## Steps to reproduce

- Upgrade to @loopback-rest 5.2.0 
- Use PostgreSQL datasource with the loopback connector
- Create models, repositories with relations.
- Create simple controllers to perform a find or findById
- Do a query with nested include :
```
{
  "include": [
    {
      "relation": "relation0",
      "scope": {
        "include": [
          {
            "relation": "relation0relation0",
            "scope": {
              "include": [
                {
                  "relation": "relation0relation0relation0"
                }
              ]
            }
          }
        ]
      }
    },
    {
      "relation": "relation1"
    },
    {
      "relation": "relation2"
    }
  ]
}
```

## Current Behavior

A Bad Request 400 error :

```
{
  "error": {
    "statusCode": 400,
    "name": "BadRequestError",
    "message": "Invalid value.",
    "details": [
      {
        "path": "/include/0/scope",
        "code": "additionalProperties",
        "message": "should NOT have additional properties",
        "info": {
          "additionalProperty": "include"
        }
      }
    ]
  }
}
```

We can not use "include" inside "scope".

## Expected Behavior

The queried model with all his queried relations (and relation's relations).

## Link to reproduction sandbox

in progress

**Comment by dhmlau** [comment]
@agnes512, I believe you were looking into some issues on the filter. Could you please take a look as well? Thanks.

**Comment by agnes512** [comment]
@dhmlau this is causing by the change we made in #5808 . cc @jannyHou

**Comment by jannyHou** [comment]
I think the generated `TodoList.ScopeFilter` should also have `include` property. It passed before because we only validate request body but not object in query.
PR https://github.com/strongloop/loopback-next/pull/5808 introduced coercion with spec schema for query input, that's why it starts to fail. 
Submitting a fix for the scope filter.

**Comment by jannyHou** [comment]
Submitted a PR to fix it: https://github.com/strongloop/loopback-next/pull/5908
