### ISSUE TITLE
Unable to run passport-login example

### ISSUE THREAD

**Issue by ernestp** [strongloop/loopback-next#5876]
## Steps to reproduce

1. Run the `lb4 example` command to install `example-passport-login` repository:

   ```sh
   lb4 example passport-login
   ```

2. change into directory and then install the required dependencies:

   ```sh
   cd loopback4-example-passport-login && npm i
   ```

## Run the application

By default the user data is stored using a memory connector and saved locally to
`data/db.json`

Start the application with

```
$ npm start
```

## Test the login scenarios

Open browser to http://localhost:3000

### Scenario 1 : Sign up as a local user

1. Click on `Sign Up` from the header menu and register as a local user.
2. If the email provided during registration, matches with your account in
   Facebook or Google you can link those profiles with your local account.
3. Click on `Login` from the header menu and enter registered email id and
   password. The `View account` page loads with user information.

## Current Behavior

App crashed on login, see attached file

[crash.txt](https://github.com/strongloop/loopback-next/files/4876546/crash.txt)

I also tried to set Facebook app ids, but result is exactly the same

## Expected Behavior

User able to login with new account

## Link to reproduction sandbox

No modification of official sample required

## Additional information

darwin x64 10.16.3

@loopback/example-passport-login@1.5.1 /Users/ernest/Documents/ConVision/apitest/loopback4-example-passport-login
├── @loopback/authentication@4.2.9
├── @loopback/authentication-passport@2.1.9
├── @loopback/boot@2.3.5
├── @loopback/core@2.9.1
├── @loopback/mock-oauth2-provider@0.1.3
├── @loopback/openapi-v3@3.4.5
├── @loopback/repository@2.9.0
├── @loopback/rest@5.2.0
├── @loopback/rest-crud@0.8.9
├── @loopback/rest-explorer@2.2.6
├── @loopback/security@0.2.14
├── @loopback/service-proxy@2.3.4

## Related Issues

None

**Comment by raymondfeng** [comment]
@ernestp Did you follow https://github.com/strongloop/loopback-next/tree/master/examples/passport-login#create-oauth2-providersjson to create the json file 1st?

**Comment by ernestp** [comment]
@raymondfeng Yes, I created new App in Facebook, copied template and replaced id and secret in facebook section. But if I not copy template error is exactly the same, which brings me to idea that json is not used anyway.

**Comment by raymondfeng** [comment]
Can you try to set `OAUTH_PROVIDERS_LOCATION` env var to `../oauth2-providers.json`?

`OAUTH_PROVIDERS_LOCATION=../oauth2-providers.json npm start`

**Comment by ernestp** [comment]
Thanks, @raymondfeng, that solves issue.

**Comment by botura** [comment]
Where exactly should I change `OAUTH_PROVIDERS_LOCATION` ?

**Comment by dougal83** [comment]
> @raymondfeng
> Where exactly should I change `OAUTH_PROVIDERS_LOCATION` ?

On the command line where you start the application and type `npm start`, instead use `OAUTH_PROVIDERS_LOCATION=../oauth2-providers.json npm start` and this will pass the variable to the application.  Alternatively, you could make a new script in the `package.json` to set the variable:

```node
  "scripts": {
    ...
    "mystart": "OAUTH_PROVIDERS_LOCATION=../oauth2-providers.json npm run start"
  },
```

Then simply use `npm run mystart`.

See [guide](https://medium.com/the-node-js-collection/making-your-node-js-work-everywhere-with-environment-variables-2da8cdf6e786) if you're not familiar with env variables.

**Comment by hizbullaharif** [comment]
Where exactly should I change OAUTH_PROVIDERS_LOCATION ?

**Comment by hizbullaharif** [comment]
@raymondfeng where can i change?
