### ISSUE TITLE
Convert 'Intro to LB4 Dev' article into blogs

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-next#589]
Rand will edit / rewrite / re-organize [Intro to LB 4 development](http://loopback.io/doc/en/lb4/Intro-to-LB4-development.html) into one or more blog posts to help promote LB-Next beta release.

**Comment by loay** [comment]
@crandmck 
Hi Rand, I will be able to help out.

**Comment by crandmck** [comment]
Thanks @loay! I'm going to start working on it soon. 
I'll ping you when I need your help/input...

**Comment by crandmck** [comment]
@loay What I have so far is in the strongloop.com `lb4-dev-blog` branch: https://github.com/strongloop/strongloop.com/blob/lb4-dev-blog/_posts/2017-11-01-intro-to-lb4-for-developers.md

If you want to run Jekyll locally so you can see how it looks, follow the instructions in https://github.com/strongloop/strongloop.com#running-and-viewing-site-locally.
I can help if you have problems.

I added a TOC at top of the blog ot help us organize the material... we should remove it before we publish.

My assumption is that we are going to make this into several posts, so the first thing we need to resolve is how we're going to divide up the content.  What probably makes most sense is:

- Post 1: Intro + Foundation
- Post 2: Asynchronous patterns
- Post 3: LoopBack 4 + How to test and validate an API spec + How to debug an API spec

What do you think?  Is that the right division?  Is there enough "meat" for each of those 3 posts?  Do we need to add more?

Can you please do a technical review of this content; it looks OK to me, but you may have some input or want to make some changes.  Ping me if you want to chat.

**Comment by VMois** [comment]
Could I also help with articles? I can help with a review or something else.

**Comment by loay** [comment]
@crandmck 
The 3 posts content do make sense to me, however, I think we should seperate the topics of `Loopback4` from testing and debugging and have them combined in their own post. 

We can either do : 
```
Post 1: Intro + Foundation
Post 2: Asynchronous patterns
Post 3: LoopBack 4 
Post4: How to test and validate an API spec + How to debug an API spec
```

If you do not want to make 4 posts, then your 3 posts split is fine by me. I just thought it would make more sense to regroup testing and debugging in one separate post alone. 

I don't think that we need to add more, however, we will probably need to add `What's Next` in the last post to explain to the community what will be the next steps. 

I am half way through the technical review.. I will do another comment for the technical review. 

Looks Great. Good job.

**Comment by crandmck** [comment]
Thanks very much @VMois. You're welcome to provide feedback on this blog, or propose your own (in a new issue).

**Comment by crandmck** [comment]
I considered Loay's suggestion, but the "How to test and validate an API spec + How to debug an API spec" didn't seem like enough to be a post by itself, so I combined it with the LB4 material.
I broke up the content into 3 posts, and I think it works OK.  

However, they still need some work to make the whole thing more cohesive.  Here's what I suggest.  Need some input from @bajtos @raymondfeng @kjdelisle and anyone else:

- [Part 1](https://github.com/strongloop/strongloop.com/blob/lb4-dev-blog/_posts/2017-11-01-intro-to-lb4-for-developers-part1.md): I plan to add a bit more on TypeScript and OpenAPI, since these are really important and what's there now is minimal.
- [Part 2](https://github.com/strongloop/strongloop.com/blob/lb4-dev-blog/_posts/2017-11-01-intro-to-lb4-for-developers-part2.md): 
  - I added example output from the example code in [standard JS callbacks](https://github.com/strongloop/strongloop.com/blob/lb4-dev-blog/_posts/2017-11-01-intro-to-lb4-for-developers-part2.md#standard-javascript-callbacks) section; but we need to explain what happens in the example and what conclusion(s) you can draw.  _I could use help here._
  - Need to compare and contrast the four approaches in the [Comparison](https://github.com/strongloop/strongloop.com/blob/lb4-dev-blog/_posts/2017-11-01-intro-to-lb4-for-developers-part2.md#comparison) section.  _Could use some input here, too._
- [Part 3](https://github.com/strongloop/strongloop.com/blob/lb4-dev-blog/_posts/2017-11-01-intro-to-lb4-for-developers-part3.md): 
  - _Would like someone to do a technical review of this material._ Loay said it looked OK, but I would like confirmation.
  - I plan to try to add some linkage between what's covered here and parts 1 & 2.
  - _Need some help to add material at the end_ in [Putting it all together](https://github.com/strongloop/strongloop.com/blob/lb4-dev-blog/_posts/2017-11-01-intro-to-lb4-for-developers-part3.md#putting-it-all-together-with-loopback-4) that explains how Controllers and the API specs, Components & providers, and Sequences all play together; and then try to summarize the whole 3-part series.

**Comment by crandmck** [comment]
@dhmlau @bschrammIBM I finished my work on Part 1.  I think it's in fairly good shape.

Part 2 and Part 3 still need work as noted above.
