### ISSUE TITLE
Model: default value on new property (not already in database) looks broken

### ISSUE THREAD

**Issue by PierreDemailly** [strongloop/loopback-next#5899]
#  Steps to reproduce

Add a new property to an existing entity.
Entity example:
```
@model({ settings: { strict: false } })
export class Pokemon extends Entity {
  @property({
    type: "number",
    id: true,
    generated: true,
  })
  id: string;

  @property({
    type: "string",
    required: true,
  })
  name: string;

  [prop: string]: any;

  constructor(data?: Partial<Pokemon>) {
    super(data);
  }
}
```
My pokemon's table has 2 columns: id & name.

Now add a new property: level **with a default value**.

```
@model({ settings: { strict: false } })
export class Pokemon extends Entity {
  @property({
    type: "number",
    id: true,
    generated: true,
  })
  id: string;

  @property({
    type: "string",
    required: true,
  })
  name: string;

  @property({
    type: "number",
    required: false,
    default: 1,
  })
  level: number;

  // Define well-known properties here

  // Indexer property to allow additional data
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [prop: string]: any;

  constructor(data?: Partial<Pokemon>) {
    super(data);
  }
}
```

Now run `npm run build && npm run migrate`.

## Current Behavior

level's column is added to the pokemon's table, but the level's value is NULL.
As you can see on this screenshot:
![image](https://user-images.githubusercontent.com/39910767/86937902-16a1ed80-c140-11ea-8fba-cbbe0496d66b.png)

## Expected Behavior

level's column is added to the pokemon's table, and the level's value is **1**.

## Additional information

I've tryed with `required: true` at first, level's column was added to the pokemon's table, but the level's value was 0.

So I checked the doc, I'm not sure POST/PUT are working the same way lb4 alter tables but I tryed to not use `required: true` to make default value working.
>Default value for the property. The type must match that specified by type. NOTE: if you have both default value set and required set to true, you will still need to include the property in the request body of POST/PUT requests as LoopBack follows the OpenAPI standard that required means the user needs to provide the field in the request always.
The entity now:

edit: my database engine is MySQL.

**Comment by dougal83** [comment]
Hey, have you run migration to put database changes in to effect? `npm run migrate`

**Comment by PierreDemailly** [comment]
Yes, as you can see on the screenshot the level column is added.

**Comment by agnes512** [comment]
Hi, there are two ways to set the default value, and either way works:
- From LoopBack:
```
  @property({
    type: 'number',
    default: 1, // setting
  })
  level?: number;
```
By setting the `default` field, the default value will be send with requests **to the database**. That's why the corresponding table doesn't have the default value defined while instances have the correct default value `1`.

- From the database
If you check the docs [MySQL Connector](https://loopback.io/doc/en/lb4/MySQL-connector.html), you can define parts of the table through the model/property definitions by `mysql.<fieldName>`. 
For your case, if you'd like the table, the `level` column to have the default value defined, it can be done by the following settings:
```
  @property({
    type: 'number',
    mysql: {
      dataType: 'int',
      default: 1
    }
  })
  level?: number;
```
This way, you could see:
```
mysql> describe Pokemon;
+-------+--------------+------+-----+---------+----------------+
| Field | Type         | Null | Key | Default | Extra          |
+-------+--------------+------+-----+---------+----------------+
| id    | int(11)      | NO   | PRI | NULL    | auto_increment |
| name  | varchar(512) | NO   |     | NULL    |                |
| level | int(11)      | YES  |     | 1       |                |
+-------+--------------+------+-----+---------+----------------+
```

Notice that for `level` property, it should not be required, or you will need to include it in all requests. And also, since MySQL is SQL database, it doesn't support the free form properties. I'd suggest to remove ` [prop: string]: any` from the model.

I am closing this issue as it is not a bug. Feel free to reopen it if the solution doesn't work for you. Thanks!

**Comment by mhimasree11** [comment]
This doesn't seem to work when I give something like this
 @property({
    type: 'boolean',
    mysql: {
      dataType: 'boolean',
      default: true
    }
  })
  isActive?: boolean;
 the column value defaults to NULL in the DB, after migration

**Comment by MattRiddell** [comment]
I just added the following and it ends up creating a nullable field with no default value after yarn migrate:

```typescript
@property({
        type: 'number',
        precision: 1,
        scale: 0,
        required: false,
        default: 0, // LoopBack handles the default value
        mysql: {
            columnName: 'is_a_test',
            dataType: 'int',
            dataLength: null,
            dataPrecision: 1,
            dataScale: 0,
            nullable: 'N',
            default: 0, // MySQL handles the default
        },
    })
    isATest?: number;
```

**Comment by dougal83** [comment]
> I just added the following and it ends up creating a nullable field with no default value after yarn migrate:

How does it act if you remove `required: false,`?  I vaguely remember having a similar issue.  Been a long time.
