### ISSUE TITLE
yarn start failing

### ISSUE THREAD

**Issue by shweshi** [strongloop/loopback-next#5920]
## Steps to reproduce

rm -rf node_modules
yarn install
yarn start
## Current Behavior

node_modules/@loopback/repository/src/relations/has-many/has-many-through.helpers.ts:7:25 - error TS7016: Could not find a declaration file for module 'lodash'. '/home/nineleaps/projects/nova/nova/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

7 import {camelCase} from 'lodash';

## Expected Behavior
It should run the application.

## Additional information

 node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 12.14.0

npm ls --prod --depth 0 | grep loopback
+-- @loopback/boot@2.3.5
+-- @loopback/context@3.9.2
+-- @loopback/core@2.9.1
+-- @loopback/openapi-v3@3.4.5
+-- @loopback/repository@2.9.0
+-- @loopback/rest@5.2.0
+-- @loopback/rest-explorer@2.2.6
+-- @loopback/service-proxy@2.3.4
+-- loopback-connector-postgresql@5.0.2

**Comment by raymondfeng** [comment]
I cannot reproduce the problem as follows:

```sh
lb4 app y1 --skip-install --yes
cd y1
yarn install
yarn start
```

**Comment by shweshi** [comment]
Did a fresh start working fine. Thanks.
