### ISSUE TITLE
[GSSC-GVT]English string : apic lb4 app -h

### ISSUE THREAD

**Issue by candytangnb** [strongloop/loopback-next#5939]
Test case number:
27.030.010

Toolkit version:
APIConnect toolkit b5dd7c660396c9faae419a077f65e18220a341a4 (Built 2020-07-14T20:07:37Z) (Tag o.f817143-g.b5dd7c6)

Problem:
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/26452457/87619339-98040c00-c74e-11ea-8392-03c3ad7c243d.png">

**Comment by candytangnb** [comment]
I have no access to add GVT label

**Comment by dhmlau** [comment]
Thanks @candytangnb. Added the `GVT` label. 

The 2nd one is already fixed. We'll wait for the Jul translation to be dropped and come back before requesting to update the LB4 CLI version in APIC toolkit. 

@agnes512, could you please take a look at the first highlighted message? Thanks.

**Comment by agnes512** [comment]
Fixed in https://github.com/strongloop/loopback-next/pull/5964
