### ISSUE TITLE
[GSSC-GVT]English string : apic lb4 repository

### ISSUE THREAD

**Issue by candytangnb** [strongloop/loopback-next#5940]
Test case:
27.030.070

## Current Behavior

English string
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/26452457/87619756-8a9b5180-c74f-11ea-94cd-2ecca6c7d999.png">

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@agnes512, I think this is already fixed in this commit: https://github.com/strongloop/loopback-next/commit/2f572bd75883420e38bfaa780bc38445aec92e65. Could you please confirm? Thanks.

**Comment by agnes512** [comment]
Yes, that line is already being translated. This is what I have on my end: 
![image](https://user-images.githubusercontent.com/50331796/87814597-08d02480-c832-11ea-9ca5-4b1626562ac0.png)

**Comment by dhmlau** [comment]
Closing it as fixed.

**Comment by candytangnb** [comment]
verified and fixed in 2.12.0
<img width="539" alt="image" src="https://user-images.githubusercontent.com/26452457/90107915-2387b180-dd7c-11ea-8089-f30fc0716ef9.png">
