### ISSUE TITLE
Implement InclusionResolver for hasManyThrough relation

### ISSUE THREAD

**Issue by agnes512** [strongloop/loopback-next#5946]
## Acceptance criteria

- [ ] Implement a factory function for creating an inclusion resolver for the given hasManyThrough relation (similar to https://github.com/strongloop/loopback-next/pull/3595).
- [ ] Enhance `HasManyThroughRepositoryFactory` to provide `resolver` property.
- [ ] Write tests in `packages/repository-tests` to verify that resolver works for real databases.
- [ ] Feel free to write unit-level tests using mocked repositories too, as needed.
- [ ] Update documentation (e.g.hasManyThrough relation page and relation cli page) to explain how to enable or disable inclusion. Include examples showing how to build a query to include related model(s).

**Comment by cardea-fletcher** [comment]
(8-20-2020) Just to be clear, I have 2 tables (doctors, patients) and a many-many relationship between then using a hasManyThrough relationshp, generated with the **relation generator** , does this mean that there is no way to get the relations between those 2 things in the controller? For instance, return doctors, and all their patients?

Thanks in advance!

Also sorry if this doesn't go here, just trying to understand what has been built yet!

**Comment by ErwSim** [comment]
When will this be published to npm ?

**Comment by nabdelgadir** [comment]
@ErwSim hi, check for it early next week.

**Comment by dutchiexl** [comment]
Could you elaborate on how the workaround with 2 queries work ?

I need 3 queries and then have to traverse over every object to link them together. Is there a better way ?

**Comment by ErwSim** [comment]
@nabdelgadir Still not available ? :disappointed_relieved:

**Comment by nabdelgadir** [comment]
@ErwSim hi, sorry for the delay, but check again next week 🤞 I'll post a comment here when it's available.

**Comment by SebastianDaehnrich** [comment]
@nabdelgadir : do you have an idea when this will be available? :)

**Comment by nabdelgadir** [comment]
@ErwSim @SebastianDaehnrich there was just a new release, so it should be available now 😄

**Comment by ErwSim** [comment]
Yay, thanks @nabdelgadir
