### ISSUE TITLE
Filtering on an array type field

### ISSUE THREAD

**Issue by unclenorton** [strongloop/loopback-next#5958]
## Steps to reproduce

1. Create a new loopback 4 project.
1. Create a model that would have at least one field of type array, e.g.:
    ```
    @property({
        type: 'array',
        itemType: 'string'
    })
    arrayProperty: string[];
    ```
1. Create a MongoDB datasource, then a repository connected to it, and finally a CRUD controller with the default settings.
1. In the controller's `find()` method, replace
    ```
    return this.myRepository.find(filter);
    ```
    with
    ```
    return this.myRepository.find({where: {arrayProperty: 'someValue'}});
    ```
1. Run `yarn build` or `yarn start` to build and run the project.

## Current Behavior

The compiler will throw the following error:
```
error TS2322: Type 'string' is not assignable to type 'PredicateComparison<string[]> | (string[] & string) | (string[] & number) | (string[] & false) | (string[] & true) | (string[] & Date) | undefined'.
```

## Expected Behavior

The modified endpoint should return items of type that contain 'someValue' as one of `arrayProperty` members. 

## Link to reproduction sandbox

https://github.com/unclenorton/loopback-next/tree/filtering-by-array-prop

Modifications:
- `examples/todo/src/controllers/todo.model.ts`: changed `tag` property to `tags` as an array of strings
- `examples/todo/src/controllers/todo.controller.ts`: `findTodos()` function

## Additional information

The desired effect can be achieved both in MongoDB directly (`db.getCollection('myModel').find({arrayProperty: 'someValue')})`) and when using filtering in query string on an unmodified controller: `/model?filter[where][arrayProperty]=someValue`.

## Related Issues

Can't see anything like this on this repository, but it looks like this worked on earlier version of Loopback (e.g. as shown in [this StackOverflow question](https://stackoverflow.com/questions/45703955/loopback-where-filter-on-an-array-type-field))

**Comment by unclenorton** [comment]
Just realised this can be worked around by casting the value to `PredicateComparison<string[]>`: 
```
{where: {arrayProperty: 'someValue' as PredicateComparison<string[]>}}
```

Not sure if this is the right way to go about it, though.

**Comment by agnes512** [comment]
@unclenorton It doesn't look like a bug to me. It's more like a type issue. Maybe you can try to define the filter type as 
```ts
let filter: Filter<yourModelName>;
filter = {where...}
```
to see if you can get rid of the casting.

**Comment by unclenorton** [comment]
@agnes512 I've updated (and pushed to the repo) the `findTodos` function in the controller:

```ts
  async findTodos(
    @param.filter(Todo)
    filter?: Filter<Todo>,
  ): Promise<Todo[]> {
    const extraFilter: Filter<Todo> = {
      where: {tags: 'someValue'}
    }
    return this.todoRepository.find({
      ...extraFilter
    });
  }
```

The error is still the same, though

**Comment by agnes512** [comment]
For method `findTodos`, it should be fine to just use 
```ts
  async findTodos(
    @param.filter(Todo)
    filter?: Filter<Todo>,
  ): Promise<Todo[]> {
    return this.todoRepository.find(filter);
  }
```
as the type is already specified. 

I tried the modified todo example, and it works ( with in-memory db). I also checked it with MongoDB and it works as well. 

The error msg indicates that it is a type issue. For repository methods, sometimes you need to specify/cast the param to `Filter<yourModelName>` or `Where<yourModelName>`. E.g
```
await this.todoRepo.count({arrayProperty: 'someValue'} as Where<ModelName>);
await this.todoRepo.find({where: {arrayProperty: 'someValue'}} as Filter<ModelName>);
```

**Comment by agnes512** [comment]
Closing as inactive
