### ISSUE TITLE
[Spike] docs: untangle connector reference into reference, how-to guides and tutorials

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#5961]
Originated from: https://github.com/strongloop/loopback-next/issues/5786

Part of #5960 

## Acceptance Criteria
- [ ] Review the existing connector reference contents and create a plan on how to extract out content into reference, how-to guides and tutorials. 
   - As the outcome of this spike, once agreed upon, follow up stories will be created under epic #5960.

**Comment by agnes512** [comment]
Discussion from the estimation meeting:

Can follow the process or have a high-level docs to talk about the commonalities of connectors (learning tree of connectors:
- what is connectors
 - what role it plays in req/res cycle, and what relation it has between model and other artifacts
- connector types: 
  - SQL (transaction), NoSQL (freeform properties)
  - Services connectors (service proxy) and others
- How-to (in common)
  - how type maps
  - how to customize table/column names
  - how to discover/migration tables/models
- Explain challenges

Candidates for references should be specific contents, e.g handling objectId (MongoDB)
