### ISSUE TITLE
Using LoopBack 3 components like social login, storage connectors in LoopBack 4 application

### ISSUE THREAD

**Issue by KRN05** [strongloop/loopback-next#5967]

**Comment by hacksparrow** [comment]
Hi @KRN05 we don't have service-specific implementations as of now, but we do have the [infrastructure](https://loopback.io/doc/en/lb4/Services.html) to implement them, which you can use to connect to external services yourself.

Relevants docs:
- [Service generator](https://loopback.io/doc/en/lb4/Service-generator.html)
- [Calling other APIs and web services](https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html)
- [Example from a tutorial](https://loopback.io/doc/en/lb4/soap-calculator-tutorial-add-service.html)
