### ISSUE TITLE
Add `operationId` to controller endpoints on generation

### ISSUE THREAD

**Issue by RAW4RMCS** [strongloop/loopback-next#5970]
## Suggestion

Option to add `operationId` to generated controller endpoints for OpenApi spec.

## Use Cases

Currently when using nswag to generate the client side file for consuming the endpoints by `pathSegments` a lot of duplicate functions are created; ex;

`@get('/containers', {response: '{}})`  wil result in `containersGet` and
`@get('/containers/{id}', {})` wil also result in `containersGet` 

So it would be better to generate it by `operationId`,

by adding a `operationId` on generation like ex;
```
@get('/containers', {
    operationId: 'getContainers', 
    response: '{
    }
})
``` 

```
@get('/containers/{id}', {
    operationId: 'getContainerById', 
    response: '{
    }
})`
```
because it's repetative work to specify the operationId on every endpoint for every controller it would be nice if this could be build in the file generation as an option when specifing the field for example

## Acceptance criteria

- [x] Exam the decorator page https://loopback.io/doc/en/lb4/Decorators_openapi.html and update samples to remind and guide readers to define `operationId`.

- [ ]  Allowing customizing the auto generated operationId in @loopback/openapi-v3

**Comment by jannyHou** [comment]
Thank you @RAW4RMCS the suggestion is reasonable to me. When you say "using nswag to generate the client side file", which module and command did you use to generate the app?
(collecting details for criteria, thanks.)

**Comment by RAW4RMCS** [comment]
@jannyHou I use Nswag studio (windows desktop application) from https://github.com/RicoSuter/NSwag. Within this application you can specify the settings and add an openapi url and generate clients for typescript and / or C#.

![image](https://user-images.githubusercontent.com/47992568/88571573-25dcd280-d03e-11ea-92dd-a6a24932c89d.png)

example generated code from http://redocly.github.io/redoc/openapi.yaml demo openapi spec (this could also be .json)
```
export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : <any>window;
        this.baseUrl = baseUrl ? baseUrl : "//petstore.swagger.io/v2";
    }

    /**
     * Add a new pet to the store
     * @param body (optional) 
     * @param accept_Language (optional) The language you prefer for messages. Supported values are en-AU, en-CA, en-GB, en-US
     * @param cookieParam Some cookie
     */
    addPet(body: any | undefined, accept_Language: string | undefined, cookieParam: number): Promise<void> {
        let url_ = this.baseUrl + "/pet";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Accept-Language": accept_Language !== undefined && accept_Language !== null ? "" + accept_Language : "",
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAddPet(_response);
        });
    }

    protected processAddPet(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 405) {
            return response.text().then((_responseText) => {
            return throwException("Invalid input", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(<any>null);
    }
```
I copy-paste the generated output to my client app (React) and initialize it like 
`const client = new Client();` and use it like `client.addPet()`

I hope this answers your question :)

**Comment by RAW4RMCS** [comment]
@jannyHou i think there is a communication mismatch. I get the open api spec from loopback (backend) and generate the client for the frontend (as the previous example).

So the loopback app is build as you normally would do, and to let it communicate with the frontend (let's say a React app) i use nswag the generate the file that provides an easy way to do so.

If you decorate your code as specified here https://loopback.io/doc/en/lb4/Decorators_openapi.html and then put for example http://127.0.0.1:3000/openapi.json in the nswag application url location.

**Comment by jannyHou** [comment]
Ah my bad, thought it's spec --> app. @RAW4RMCS Good catch, but I think it's a documentation improvement. 

By default the generated CRUD controller does contain the `operationId`. E.g. if you run the [example todo app](https://github.com/strongloop/loopback-next/tree/master/examples/todo), `GET /todos` and `GET /todos/{id}` has different operationId:

`"operationId": "TodoController.findTodos"`
`"operationId": "TodoController.findTodoById"`

We should exam the decorator page https://loopback.io/doc/en/lb4/Decorators_openapi.html and update samples to remind and guide readers to define `operationId`.

**Comment by RAW4RMCS** [comment]
@jannyHou you are correct regarding the `operationId` if you generate the typescript client with the default `MultipleClientsFromOperationId`.

The only problem with this setting is that the `.` between `TodoController` and `findTodos` makes typescript think `findTodos` is a property from `TodoController`. (and can't be resolved).

This problem could simple be resolved by replacing the `.` with a `_`.

So the `operationId` would look like `TodoController_findTodos`

**Comment by bajtos** [comment]
I believe `.` is a valid character allowed in `operationId` values by OpenAPI, IIRC other code generators like [swagger-codegen](https://github.com/swagger-api/swagger-codegen) and [openapi-generator](https://github.com/OpenAPITools/openapi-generator) implement a bit of logic to sanitize operation ids and replace special characters like `.` with something that's valid in the target language they are generating code in (e.g. convert `TodoController.findTodos` to `TodoController_findTodos`).

Ideally, you should work with nswag to improve their support for non-letter characters in operation names. I think this issue may be relevant: https://github.com/RicoSuter/NSwag/issues/2447

Having said that, I can see how it can be easier to change `operationId` format emitted by LoopBack.

It makes me wonder what would be the impact of such change on existing clients though. Is it worth adding a new feature flag to control the separator used in operation ids (`.`, `_` or something else)?

**Comment by raymondfeng** [comment]
If the format of `operationId` is sensitive to a lot of tooling, it may be more flexible to allow a custom function.

**Comment by jannyHou** [comment]
> It makes me wonder what would be the impact of such change on existing clients though. Is it worth adding a new feature flag to control the separator used in operation ids (., _ or something else)?

> If the format of operationId is sensitive to a lot of tooling, it may be more flexible to allow a custom function.


Agree. I think we can allowing customizing the auto generated `operationId` in `@loopback/openapi-v3`

https://github.com/strongloop/loopback-next/blob/a81ce7e1193f7408d30d984d0c3ddcec74f7c316/packages/openapi-v3/src/controller-spec.ts#L296-L304

Function [`resolveControllerSpec`](https://github.com/strongloop/loopback-next/blob/a81ce7e1193f7408d30d984d0c3ddcec74f7c316/packages/openapi-v3/src/controller-spec.ts#L69) can take in `options`, and user can configure generator function through rest server configurations.

**Comment by jannyHou** [comment]
I created a PR to improve the doc in https://github.com/strongloop/loopback-next/pull/6102

**Comment by jannyHou** [comment]
Merged https://github.com/strongloop/loopback-next/pull/6102, and thanks for @raymondfeng 's suggestion, I added a section for leveraging spec enhancer to customize the `operationId`. @RAW4RMCS you could check the PR to see the code.

And I think using enhancer is a better solution than "customizing the auto generated operationId in @loopback/openapi-v3":

- we already support it
- much more flexible

So I am closing this issue. Feel free to reopen it if you still have questions :)
