### ISSUE TITLE
Handle app object in controllers or models in lb4

### ISSUE THREAD

**Issue by kvbogdanov** [strongloop/loopback-next#5995]
> **Note:** This question was also posted elsewhere:
>
> https://stackoverflow.com/q/63047155/5019371

According to docs In the lb3 we could do this:

```
With models, there is a special case. From anywhere except /common/models/model.js, you can actually get a reference to app through a model using model.app.

For instance:
...
Book.app
...

```
How can I get access to the app object in the same way in lb4? I'm trying to dynamically create controller from another controller and had stuck at this point.

**Comment by raymondfeng** [comment]
You can inject application instance as:

```ts
constructor(
    @inject(CoreBindings.APPLICATION_INSTANCE) app: Application,
) {}
```

**Comment by kvbogdanov** [comment]
Thanks a lot! It works
