### ISSUE TITLE
hasManyThrough: should not create through model for non-existent source and targets

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#5996]
This appointment is getting created despite the source and target model ids not existing.

```
{
  "date": "2020-07-23T13:29:09.924Z",
  "doctorId": 90000000,
  "patientId": 20000000000000
}
```

**Comment by agnes512** [comment]
@hacksparrow thanks for opening the issue 👍 I think this is because of the design.  I remember @Janny had the same question before, and we discussed it in https://github.com/strongloop/loopback-next/pull/5719#pullrequestreview-433160291 (quote from @bajtos ):
> So far, LoopBack implements what we call "weak relations", where it's up to the database to enforce any referential integrity. Typically, when using SQL, there is a foreign key constraint configured to ensure the "link" rows cannot point to a source/target model that does not exist, and also that it's not possible to delete a source or a target row before all their "link" rows are removed first. (It's also possible to configure cascading delete, but let's not get distracted.) We have been discussing "strong relations" in the past, but they weren't a priority so far. You can learn more in #2331.

> IMO, we should keep the current ("weak") design, if only for consistency with other existing relational APIs, and mention in the documentation that the referential integrity must be configured at database level.

WDYT?

**Comment by hacksparrow** [comment]
Got it. The notice on top of the doc should suffice.
