### ISSUE TITLE
How to use filter for sorting a parent relation in sql query?

### ISSUE THREAD

**Issue by duanvnc** [strongloop/loopback-next#6010]
## Suggestion

> We need a sorting query for relation database table in Filter Order 

## Use Cases

- Loopback is missing a filter[order] to parent objects' keys.

## Examples

For example: I have 2 relation sql tables: 

```
posts(id, title, description, category_id, created_at)
 
categories(id, name, created_at)

foreign key by: posts.category_id = categories.id
```

I want sort the Posts list by category name like this query: 
`SELECT * FROM posts p INNER JOIN categories c ON p.category_id=c.id ORDER BY c.name ASC; `

So, how the Loopback Filter can do like that way?
 

## Acceptance criteria

TBD - will be filled by the team.

**Comment by berlingoqc** [comment]
I really need this feature, is there any workaround in the meanwhile ?

**Comment by achrinza** [comment]
Related: #4299

**Comment by achrinza** [comment]
@berlingoqc A workaround is to use `.execute()` to write custom SQL queries.

**Comment by achrinza** [comment]
Closing in favour of #4299
