### ISSUE TITLE
Upgrading Helmet to the next major version

### ISSUE THREAD

**Issue by EvanHahn** [strongloop/loopback-next#6024]
I'm the maintainer of Helmet. I plan to release the next major version this Sunday, 2020-08-22.

Is there anything I can do to help get this project upgraded to `helmet@4`?

If you'd like to try out the release candidate now, you can install it with `npm install helmet@next`. If you'd rather discuss things outside of this issue, feel free to [reach out to me](https://evanhahn.com/contact) another way.

Hope I can be helpful!

**Comment by raymondfeng** [comment]
@EvanHahn Thank you for chiming in! We have WhiteSource Renovate Bot configured for this repo and it will sends us a PR with Helmet@4.x upgrade. We can land it if the CI is green. Otherwise, we try to fix breaking changes first.

Once the PR is in, we can ping you if necessary.

**Comment by EvanHahn** [comment]
Sounds good! I'll do nothing for now. Let me know if I can help further.

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/loopback-next/pull/6043
