### ISSUE TITLE
Problem with @get function 

### ISSUE THREAD

**Issue by dangchinh25** [strongloop/loopback-next#6026]
I'm currently using Loopback4 and trying to query data from my existing MySQL database. I only use the cli command to generate models, repo, and controller but when I try it everything works except for the GET all function that I always have this issue.
![image](https://user-images.githubusercontent.com/35798337/88725581-f12a5300-d0f1-11ea-9acb-241ac5c7cef9.png)

**Comment by achrinza** [comment]
Hi @dangchinh25, based on the error, the order filter was set to column "string". Could you please check the filter that's being passed, and ensure that it conforms to the following:


https://loopback.io/doc/en/lb4/Order-filter.html

**Comment by dangchinh25** [comment]
> Hi @dangchinh25, based on the error, the order filter was set to column "string". Could you please check the filter that's being passed, and ensure that it conforms to the following:
> 
> https://loopback.io/doc/en/lb4/Order-filter.html

![image](https://user-images.githubusercontent.com/35798337/88749178-5b55ee80-d118-11ea-80a5-7d8a884ad639.png)
This the code regarding the problem in the query, I didn't code anything I just used the cli command

**Comment by achrinza** [comment]
Apologies, to clarify my previous comment:

What was the GET request that was sent? The error message hints that the error occured when making a request to the lb4 application.

**Comment by dangchinh25** [comment]
> Apologies, to clarify my previous comment:
> 
> What was the GET request that was sent? The error message hints that the error occured when making a request to the lb4 application.

it is simply the GET to /roles endpoint, it is supposed to get all the roles in the table, I sent the request via the /explorer page

**Comment by duanvnc** [comment]
@dangchinh25 I can see that your **order** in the filter is invalid.
Yours: `{
  "offset": 0,
  "limit": 100,
  "skip": 0,
  "order": [
    "string"
  ],` 

please replace the "string" to **role** property name like:
`{
  "offset": 0,
  "limit": 100,
  "skip": 0,
  "order": [
    "name asc"
  ],`

It will work correctly. Good luck!

**Comment by achrinza** [comment]
To echo what @duanvnc has mentioned, please ensure that the API Explorer does not have a filter set.

Based on the error provided, _a filter query is being sent by the API Explorer_:

![image](https://user-images.githubusercontent.com/25147899/88885653-7a18ca00-d26b-11ea-9011-26e02c9fdd6a.png)

Notice the "filter" query being populated in the URL.

I'll close the issue as solved. Feel free to comment if clarification is needed.
