### ISSUE TITLE
docs: What does LB4 Beta mean for existing LB 3.x users

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#603]
http://loopback.io/doc/en/lb4/Migration-guide.html

need to change the title, NOT "Migration Guide"
(we're not ready for migration)
LB3 juggler can still be used with LB4 app
middleware -> will need to use Sequence
connect to: strongloop/loopback-next#485

**Acceptance criteria**

Outline:

 - Mapping key concepts from LB 3.x to LB 4.x: 

   - The Model in 3.x has three parts - data modeling, persistence, remoting/REST API. In LB 4.x, remoting is moved to controllers. Persistence is moving to repositories. Data modeling stays on its own.

   - Extensibility. LB 3.x - operation hooks, remoting hooks, middleware. In LB 4.x, we have Sequence & Sequence actions, Bindings/Dependency Injection. We are considering introducing hooks at Controller level. Operation hooks are still available via legacy juggler bridge.

   - Connectors - staying the same for now.

   - Component model. LB 3.x - very simple component model. LB 4.x - much more powerful.

   - Authentication. LB 3.x has built-in set of models and auth/auth implementation. LB 4.x is fully pluggable and extensible. There is no built-in auth functionality available as of Beta release.

 - What features are part of Beta and more importantly what's not.

 - What are our post-Beta plans 

   - highlight few items from the roadmap page that are relevant to people upgrading from LB 3.x
   - point readers to the full roadmap

Keep it high level, link to existing content (e.g. Thinking in LoopBack) for more details.

Rename http://loopback.io/doc/en/lb4/Migration-guide.html to a more appropriate name, put the content in that new page via a pull request, so that others can review the content.

**Comment by bajtos** [comment]
Rephrase the content from strongloop/loopback-next#485 and put it in docs. Set the expectations of LB3 users right, make it clear what is part of LB4 Beta release and what's missing.

**Comment by raymondfeng** [comment]
Kicking off - https://github.com/strongloop/loopback.io/blob/crafting-loopback/pages/en/lb4/LoopBack-3.x.md

**Comment by raymondfeng** [comment]
See http://loopback.io/doc/en/lb4/LoopBack-3.x.html

**Comment by dhmlau** [comment]
Talked to @raymondfeng, this is completed. Closing it.
