### ISSUE TITLE
npm ERR! 404  '@loopback/authorization@^0.6.4' is not in the npm registry.

### ISSUE THREAD

**Issue by sunilsmith** [strongloop/loopback-next#6065]
NodeJS - V13.9.0
 npm - v6.13.7
@loopback/cli version: 2.8.0
OS: Windows 10

## Steps to reproduce

In a LB4 project try using the below command to install @loopback/authorization package
**npm i @loopback/authorization**

Then the below error occurred:
npm ERR! 404 Not Found - GET http://registry.npmjs.org/@loopback%2fauthorization - Not found
npm ERR! 404
npm ERR! 404  '@loopback/authorization@^0.6.4' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'project-name'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2020-08-06T09_34_28_179Z-debug.log

## Expected Behavior

Using the command **npm i @loopback/authorization** it should install the package with the latest version successfully.

## Additional information
Added the complete stack below:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '@loopback/authorization'
1 verbose cli ]
2 info using npm@6.13.7
3 info using node@v13.9.0
4 verbose npm-session 2b98ee78ef76696a
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 http://registry.npmjs.org/@loopback%2fauthorization 148ms
8 http fetch GET 404 http://registry.npmjs.org/@loopback%2fauthorization 47ms
9 silly fetchPackageMetaData error for @loopback/authorization@0.6.4 404 Not Found - GET http://registry.npmjs.org/@loopback%2fauthorization - Not found
10 timing stage:rollbackFailedOptional Completed in 0ms
11 timing stage:runTopLevelLifecycles Completed in 8768ms
12 verbose stack Error: 404 Not Found - GET http://registry.npmjs.org/@loopback%2fauthorization - Not found
12 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
13 verbose statusCode 404
14 verbose pkgid @loopback/authorization@0.6.4
15 verbose cwd C:\<path-to-repo>\<project-name>
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@loopback/authorization"
18 verbose node v13.9.0
19 verbose npm  v6.13.7
20 error code E404
21 error 404 Not Found - GET http://registry.npmjs.org/@loopback%2fauthorization - Not found
22 error 404
23 error 404 '@loopback/authorization@0.6.4' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

**Comment by ElfenLiedGH** [comment]
I think that it's npm bug. npm i @loopback/boot doesn't work too. a lot of other npm libraries coudn't be found now :(

**Comment by sunilsmith** [comment]
@ElfenLiedGH  The issue is resolved now and i can install @loopback/boot and @loopback/authorization
