### ISSUE TITLE
Migration  loopback 

### ISSUE THREAD

**Issue by mousaa32** [strongloop/loopback-next#6074]
## Additional information

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by achrinza** [comment]
Please provide more info.

**Comment by dzhiwei** [comment]
@achrinza Is there any toturial document for migrating lb3 with TS to lb4?
I find there's toturial for migrating lb3 to lb4 at https://github.com/strongloop/loopback-next/tree/master/examples/lb3-application#tutorial
My current lb3 is written in TS now, when I follow the toturial steps, I will get below error:
```
> lb4-app@1.0.0 start /Users/workspace/data/nodejs_workspace/lb4-lb4-app
> node -r source-map-support/register .

Cannot start the application. { Error: Cannot find module '/Users/du/workspace/data/nodejs_workspace/lb4-app/lb3app/server/server'
```
It seems I need to enhance the `npm run build` step to compile the lb3 TS code firstly.
Any advice? Thank you.

**Comment by achrinza** [comment]
@dzhiwei I recommend keeping the build systems separate.

One possible way to do it:

In the root `tsconfig.json`, set it to exclude the LoopBack 3 folder if necessary.

In the root `package.json`,  configure the `build` script to execute the LoopBack 3's existing build script.

For example, if the LoopBack 3 is compiled standalone using `npm run build`, prepend to the root `build` script:

```
"build": "npm run build --prefix ./lb3app &&  lb-tsc
```

This would cause trigger the LoopBack 3 build system before LoopBack 4, thereby keeping them separate.

**Comment by dzhiwei** [comment]
@achrinza Thank you so much. Good suggestion. I will try this

**Comment by dzhiwei** [comment]
Finally, I migrate the compiled lb3 TS project successfully.
And one more step is that, need to replace the complied server/server.js with that original one from lb3 JS porject. the server.js compiled by `tsc` will not work for swagger generator due to no `remotes` in loopbackApplication:
```
> node -r source-map-support/register .

Cannot start the application. TypeError: loopbackApplication.remotes is not a function
    at createSwaggerObject (/Users/du/workspace/data/nodejs_workspace/lb4-domain-service/node_modules/loopback-swagger/lib/specgen/swagger-spec-generator.js:31:37)
    at Lb3AppBooter.buildOpenApiSpec (/Users/du/workspace/data/nodejs_workspace/lb4-domain-service/node_modules/@loopback/booter-lb3app/src/lb3app.booter.ts:114:25)
    at Lb3AppBooter.load (/Users/du/workspace/data/nodejs_workspace/lb4-domain-service/node_modules/@loopback/booter-lb3app/src/lb3app.booter.ts:58:29)
```

**Comment by achrinza** [comment]
Closing as solved; Feel free to open a new issue if the problem persists
