### ISSUE TITLE
feat: Easier configuration option for Application, Servers & Components

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#608]
After a discussion with @kjdelisle I would like to propose the following:

---

Introduce a first class method `.config()` in Application which can automatically bind keys to values based on a JSON Object, this would make it easier to config Servers and Components. I would also propose changing the separator from `#` to `.` to be consistent with JSON notation that most developers are used to. 

An example: 
```
app.config({
  RestServer: {
    type: RestServer, // Bind to 'RestServer.type'
    port: 3001,            // Bind to 'RestServer.port'
  },
  LogComponent: {
    log_level: LOG_LEVELS.INFO, // A constant value -> Bound to 'LogComponent.log_level'
  }
})
```

Server config can also be nested under `servers` key in config. (Implementation decision). 

This approach has a few benefits: 
- A cleaner experience for LoopBack Application Developers (easier to config like this imo vs. having to bind all those values manually). 
- For components, they can inject the top level config object and then use `.` notation to check for their appropriate config if their config is optional. No error would be thrown in this case and if override config is not set then component can default to it's own config. 
- This approach saves a component developer from having to write Mixins (which is another thing an app developer would have to remember to add in) to provide sugar for bindings.
- We switch bindings to be separated to `.` notation which is more in line with JavaScript / TypeScript. (I've personally had trouble wrapping my head with using `#` as the separator). 

Cons:
- Another breaking change

cc: @raymondfeng @bajtos

**Comment by kjdelisle** [comment]
I don't think we should tag it with a priority level until there's been discussion, but IMO this is a P1 change if we intend to do it.

**Comment by bajtos** [comment]
@virkt25 could you please add an example showing how to use this new configuration format within `ApplicationConfig` that's passed to `Application` constructor? Should the constructor call `this.config` as the first thing?

**Comment by virkt25** [comment]
Sure thing. 
```
const app = new Application({
  // components.RestComponent && components.StarterLogActionProvider
  components: [RestComponent, StarterLogActionProvider],
  // repositories.ProductRepository
  repositories: [ProductRepository],
  // servers.RestServer
  servers: [RestServer],
  // Now we have the config
  RestServer: {
    port: 3001 // RestServer.port
  },
  StarterLogActionProvider: {
    logLevel: LogLevel.INFO // StarterLogActionProvider.logLevel
  }
})
```
@kjdelisle also suggested being able to add `servers` as shown in original ticket so you can name your server as you please. **I'll suggest change `type` to `serverType` so others may use `type` in their components** and we won't be checking the `type` against a list of `Servers` to start them. 

The constructor would need to call `this.config` but only because `servers` expect the Application config so they can be started (IIRC). Everything else can technically be done after in via `app.config` but we might as well just promote them to configure everything there. 

@kjdelisle Feel free to add anything I missed / mis-interpreted.

**Comment by bajtos** [comment]
@virkt25 please check with @raymondfeng (and possibly @kjdelisle) whether this proposal makes still sense, considering the other ongoing work related to configuration/binding setup.

**Comment by raymondfeng** [comment]
1. For configuration providers, they might prefer to configure the whole hierarchy of properties in a JSON object. But for configuration consumers, they probably want to access the related values directly without navigation.

2. The proposed configuration property hierarchy hints that we want to organize artifacts in a hierarchy too, for example, as extension points/extensions. We probably should align the discussions.

3. Please note configuration can be built asynchronously from a DB or a registry.

4. We are already working on `@inject.options` to inject configuration values.

5. Please clarify why `#` and `.` are part of this proposal. Having an example for the configuration consumer will help.

**Comment by kjdelisle** [comment]
We'll look into this as a post-MVP step; our current MVP goals are for single-server setup only, and are currently accomplished by the `RestApplication` class.
