### ISSUE TITLE
build: move lint & prettier to a standalone Travis-CI build step

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#610]
See https://github.com/strongloop/loopback-next/pull/601#issuecomment-333659492

> Just a comment regarding checking this in our `npm test` workflow. I think it might be better to have different stage for linting on travis where we run `npm run lint && npm run prettier:check`. I just find it easier to look at Travis and know where something went wrong without having to open up logs.

**Comment by dhmlau** [comment]
@bajtos, is this something we still want to do?

**Comment by raymondfeng** [comment]
We already have a `code-lint` step in travis.
