### ISSUE TITLE
docs: move Server recipes to how-to guides

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#6107]
At the moment, the [Server](https://loopback.io/doc/en/lb4/Server.html) page in "Behind the scenes" is mixing [explanations](https://documentation.divio.com/explanation/) with [how-to guides](https://documentation.divio.com/how-to-guides/). This makes it difficult for our users to find the relevant content (a recipe to achieve the outcome they want).

As part of our adoption of the four-quadrant documentation system (see #5549 and #5718), we should extract all guides from explanation pages into guide pages (see #5768 for inspiration) and keep explanation pages focused on explaining the concepts & providing background information.

This story is a part of Epic #5783 move recipes to how-to guides. 

## Acceptance criteria

Move the following recipes into "How-to guides", decide yourself whether to create a new page for each recipe or group multiple recipes in one page. For each recipe moved elsewhere, add a new entry to "Common task" list in the "Server" page.

- [ ] [Configure REST API Explorer](https://loopback.io/doc/en/lb4/Server.html#configure-the-api-explorer), including [Disable redirect to API Explorer](https://loopback.io/doc/en/lb4/Server.html#disable-redirect-to-api-explorer) and [Use a self-hosted API Explorer](https://loopback.io/doc/en/lb4/Server.html#use-a-self-hosted-api-explorer)
- [ ] [Customize CORS](https://loopback.io/doc/en/lb4/Server.html#customize-cors)
- [ ] [Customize express settings](https://loopback.io/doc/en/lb4/Server.html#express-settings)
- [ ] [Configure the base path](https://loopback.io/doc/en/lb4/Server.html#configure-the-base-path)
- [ ] [Configure the router](https://loopback.io/doc/en/lb4/Server.html#configure-the-router)
- [ ] [Configure the request body parser options](https://loopback.io/doc/en/lb4/Server.html#configure-the-request-body-parser-options)
- [ ] [Add servers to application instance](https://loopback.io/doc/en/lb4/Server.html#add-servers-to-application-instance)
- [ ] [Enhance OpenAPI Specification](https://loopback.io/doc/en/lb4/Server.html#enhance-openapi-specification)

**Comment by mrmodise** [comment]
I will take this on. Thanks
