### ISSUE TITLE
loopback 4 jwt i dont know how it works

### ISSUE THREAD

**Issue by programaclases** [strongloop/loopback-next#6127]
Hello Everyboyd, everyones.
Sorry my english is very poor.

But i try to follow the instructions for iplement, jwt in loopback 4.
But i have this problem.

```

import {SequenceHandler, RequestContext, DefaultSequence} from '@loopback/rest';
// ---------- ADD IMPORTS -------------
import {
  AuthenticateFn,
  AuthenticationBindings,
  AUTHENTICATION_STRATEGY_NOT_FOUND,
  USER_PROFILE_NOT_FOUND,
} from '@loopback/authentication';
import {inject} from '@loopback/core';

export class MySequence implements SequenceHandler {
  constructor(
    // ---- ADD THIS LINE ------
    @inject(AuthenticationBindings.AUTH_ACTION)
    protected authenticateRequest: AuthenticateFn,
  ) {}

  async handle(context: RequestContext): Promise<void> {
    try {
      const {request, response} = context;
      const route = this.findRoute(request);
      // - enable jwt auth -
      // call authentication action
      // ---------- ADD THIS LINE -------------
      await this.authenticateRequest(request);
      const args = await this.parseParams(request, route);
      const result = await this.invoke(route, args);
      this.send(response, result);
    } catch (err) {
      // ---------- ADD THIS SNIPPET -------------
      // if error is coming from the JWT authentication extension
      // make the statusCode 401
      if (
        err.code === AUTHENTICATION_STRATEGY_NOT_FOUND ||
        err.code === USER_PROFILE_NOT_FOUND
      ) {
        Object.assign(err, {statusCode: 401 /* Unauthorized */});
      }
      // ---------- END OF SNIPPET -------------
      this.reject(context, err);
    }
  }
}

```

but not found several routes findRoute,parseParams, invoke,send reject.
If try extends DefaultSEquence.
`export class MySequence extends DefaultSequence implements SequenceHandler {}`
But in this case need a constructor, but i don't know how it implements,
I dont know if this its the correct way.
I try to find loopback4 implement this but not found anything example.
I hope somebody help me. Thanks.

**Comment by Sheldonfrith** [comment]
I am working on the same issue. I think the import statement for SequenceHandler must be missing.

**Comment by Sheldonfrith** [comment]
this is from the docs page https://loopback.io/doc/en/lb4/Authentication-tutorial.html

**Comment by Sheldonfrith** [comment]
I think I found a solution for you in this issue: https://github.com/strongloop/loopback-next/issues/2896

**Comment by dhmlau** [comment]
@programaclases @Sheldonfrith, did you have a chance to look at the [todo-jwt example](https://github.com/strongloop/loopback-next/tree/master/examples/todo-jwt)? There're some recent changes in switching to middleware based sequence.

**Comment by programaclases** [comment]
Hi everyone.
But i have the same problem. I dont lnow how to continue with this part i have methods but not contstructor
`export class MySequence extends DefaultSequence implements SequenceHandler {}`
or no constructor but no found methods.
Somebody have a simple example?

**Comment by programaclases** [comment]
Hello i tried to follow the instructions, I have only get protect my routes, but not implement roles i add link to my myrpoject todo
https://github.com/programaclases/loopback_auth_jwt.
If somebody that steep i need to follow, for solve this.
Thanks for your helpful, Sheldonfrith and dhmlau.

**Comment by dhmlau** [comment]
Closing as answered.
