### ISSUE TITLE
docs: Update all documentation for @loopback/rest refactor

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#613]
## Summary

After the refactor to move all of the HTTP/REST items into their own package, we need to update all of the documentation that involves use of those modules and functions.
 
## Acceptance Criteria

Review and update the documentation. Make sure the updated code snippets work! (You can use acceptance tests or example apps to help you with verification.)

loopback.io pages:

  - [x] Thinking in LoopBack
  - [x] Key concepts
  - [x] Getting started
  - [x] Using Components
  - [x] Creating Components
  - [x] Calling other APIs
  - [x] Testing Your Application
  - [x] Migration guide
  - [x] Crafting LoopBack 4 - No code snippet in this page
  - [x] Reference

loopback-next:

  - [x] review and fix per-package READMEs (authentication, etc.) (Diana)

**Comment by dhmlau** [comment]
@kjdelisle , I can work on reviewing the READMEs since I've started on one already.

**Comment by crandmck** [comment]
We also need to update the API docs: add the new package to https://github.com/strongloop-internal/apidocs.strongloop.com/blob/master/ts-repos.json

**Comment by crandmck** [comment]
We also need to update the API docs, specifically we need to add the new package to https://github.com/strongloop-internal/apidocs.strongloop.com/blob/master/ts-repos.json

**Comment by dhmlau** [comment]
@crandmck , I could submit a PR for the change in `ts-repos.json` if you want.  But I'm not sure how to verify it.

**Comment by kjdelisle** [comment]
Closing as complete!
