### ISSUE TITLE
lb4 relation does not work if primary key is not "very" explicit.

### ISSUE THREAD

**Issue by Salketer** [strongloop/loopback-next#6131]
## Steps to reproduce

From the ToDo example app.

One way to do it:

- Create a base model entity class that extends from Entity
- Extend from this base class in your ToDo model
- Move the ID definition from the todo class to the base class
- Try to create a belongsTo relation with the todo as source.

Another tried work-around:

- Create a new file that will export the ID property definition
- Import and use the ID property definition from the created file
- Try to create a belongsTo relation with the todo as source.

## Current Behavior

Error: The source model primary key does not exist.

## Expected Behavior

Be able to create the relation as usual.

## Additional information

This seems to be looking inside the source code of the model only and does not interpret or extrapolate the possibilities.

While building a controller, and even a repository works, why won't the relation simply ask for the id key name and type like those?

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by agnes512** [comment]
This is because of the design ([code](https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/relations/belongs-to/belongs-to.helpers.ts#L71)).

I can see your point though 👍 Let me check if we can do some improvements.

**Comment by Salketer** [comment]
Hello Agnes, thanks for taking the point! The code you are pointing to doesn't seem bad... It should indeed appear in there.

It looks like targetModel.definition does not hold properties that are inherited?

**Comment by agnes512** [comment]
@Salketer I thought it was because of the inheritance issue in the relation code of `repository`. Turns out that it is because the cli `lb4 relation` checks the mode primary key by files (see [code](https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/relation/utils.generator.js#L34)). i.e for your case, if you define relations without the cli, it should work.

Let me link the issue to https://github.com/strongloop/loopback-next/issues/6017.

**Comment by Salketer** [comment]
Ah that's what I thought! I confirm, we did a bunch of relations by hand
and they work just as they should.

I'd like to suggest to have the lb4 relation fallback to the same behaviour
as lb4 repository or lb4 controller that ask for the ID property and
type... That would save a lot of time for devs.

**Comment by Cethy** [comment]
As a temporary workaround, copy-pasting the id definition in the "used" models makes the cli works as expected.

**Comment by agnes512** [comment]
Fixed in https://github.com/strongloop/loopback-next/pull/6937, thanks!
