### ISSUE TITLE
Warn if BootMixin app is started without booting

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#6136]
```ts
export class MyApplication extends BootMixin(RestApplication) {
...
}

const app = new MyApplication();
...
await app.start();
```

This app will start successfully with no booted artifacts. Since the usage of `BootMixin()` indicates a desire for booting capabilities, starting the app without booting is very likely an accidental omission. The user should be warned about the missing booting step.

This may not be a problem for users limited to using the scaffolded files, but for someone using LoopBack in a customized manner, it can be a frustrating experience to have the app running successfully with none of the artifacts loaded.  

I made a quick attempt of resolving this by adding a `start()` method in the class returned by `BootMixin` but am hit by this error:

_Class '{ readonly options: ApplicationConfig; readonly state: string; controller: <T>(controllerCtor: Constructor<T>, nameOrOptions?: string | BindingFromClassOptions | undefined) => Binding<...>; ... 53 more ...; listenerCount: (type: string | symbol) => number; }' defines instance member property 'start', but extended class '(Anonymous class)' defines it as instance member function._

@raymondfeng @bajtos

**Comment by raymondfeng** [comment]
Use the following to work around the TypeScript issue:

```ts
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
```

**Comment by hacksparrow** [comment]
Thank you @raymondfeng, the PR - https://github.com/strongloop/loopback-next/pull/6141.

**Comment by hacksparrow** [comment]
Closed via https://github.com/strongloop/loopback-next/pull/6141.
