### ISSUE TITLE
Order filter's JSON Schema does not accept string

### ISSUE THREAD

**Issue by raman1212** [strongloop/loopback-next#6140]
> **Maintainers' Note:** This was posted elsewhere:
> - https://stackoverflow.com/q/63466867/5019371

There is a bug in loopback 4 latest CLI version as I just upgraded to the latest LOOPBACK CLI version and tried to HIT a URL from my dashboard and it is saying this is a BAD request.
THE same URL is working with an earlier LOOPBACK CLI version. 
URL I am trying to HIT :- 
`http://[::1]:3001/data?filter[limit]=10&filter[offset]=0&filter[order]=id+ASC`

I checked it again and again with both versions but for the latest one its getting BAD request and for the earlier version it's working.

Anyone knows what is going on here.

**Comment by raman1212** [comment]
One update on the issue: 
I modified the URL a little bit and now it gets worked. 
Updated URL is :
`http://[::1]:3001/cxdashboard/api/scorecustomer?filter{limit}=10&filter{offset}=0&filter{order}=id+ASC`

I only changed the bracket from square to curly brackets. This is strange.
Still, this remains an issue in loopback 4 as my application sends the above URL not this one and both the URL must be supported.

**Comment by achrinza** [comment]
I've tested it an can confirm the following:

The `order` filter must be an array. For example:

```
http://[::1]:3000/data?filter=offset": 0, "limit": 100, "order": ["id ASC"] }
```

or:

```
http://[::1]:3000/data?filter[limit]=10&filter[offset]=0&filter[order][0]=id+ASC
```

**Comment by achrinza** [comment]
Problematic code in question:

https://github.com/strongloop/loopback-next/blob/6b6c608c107f427217ad0bb07635770f2fb1b1da/packages/repository-json-schema/src/filter-json-schema.ts#L101-L106

**Comment by hacksparrow** [comment]
Note for whoever will fix this: please make sure to add a test case catching this problem, else it can come back again undetected.

**Comment by raman1212** [comment]
Any update on the bug ?

**Comment by raman1212** [comment]
Hitting this URL
http://[::1]:3001/data?filter[limit]=10&filter[offset]=0&filter[order]=id+ASC

GETTING THIS ERROR:- 
` 
Invalid data {"limit":10,"offset":0,"order":"id ASC"} for parameter "filter".
code: INVALID_PARAMETER_VALUE
details: [object Object]`

**Comment by raman1212** [comment]
Checking again
