### ISSUE TITLE
Sentry error tracking integration

### ISSUE THREAD

**Issue by duanvnc** [strongloop/loopback-next#6145]
## Suggestion

I can't find any Loopback 4 package integrates to Sentry which is famous application exception error tracking.

## Use Cases

Loopback4 Sentry package or official docs in detail: how to integrate Sentry into Loopback4 to tracking exception errors.

## Acceptance criteria

TBD - will be filled by the team.

**Comment by raymondfeng** [comment]
You can simply register Sentry handlers as Express middleware to LoopBack 4.

**Comment by dhmlau** [comment]
@duanvnc, we believe we've answered your question. Closing this issue. Thanks.
