### ISSUE TITLE
Partitioned application

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-next#615]
@landervs commented on [Tue Oct 03 2017](https://github.com/strongloop/loopback.io/issues/473)

I have an scalable application, which is being used by different groups of users. One group is NOT allowed to see the data from another group, so I have to partition up my application. 

(With realm of the build-in User model this is not possible, this is to partition models, but i want to partition my whole application, each group is able to use all the models, only the data (read: returned rows) is different).

In fact; each table in my database has a column "group" to declare which rows belongs to which group. (I have one shared database for all the groups).

**It would be nice if I could use the http requests of the API in this way:
/api/{group_name}/ModelName _instead of_ /api/ModelName/{group_name}**

**Question 1:**
Is it possible to define a prefix custom param in the API URL's?
I know you can define custom params as suffix after your model name, but what about prefixes?

**Question 2:**
Is there a way to define {group_name} as global param? Or is it needed to write my own custom REST endpoint for each model?

**Question 3:**
Is there a way to extend the default API endpoints with this one parameter {group_name} globally without writing custom endpoints?

If this is not possible, maybe is this an idea for a new built-in feature for another release?

Thanks,

Lander

**Comment by bajtos** [comment]
@raymondfeng @kjdelisle what's your take on this? I don't think we have bandwidth to implement support for partitioned applications in our GA release, therefore I am proposing to close this issue with `help wanted`.
