### ISSUE TITLE
Incorrect links

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#6176]
https://loopback.io/doc/en/lb4/Behind-the-scene.html is linking the `.md` file instead of `.html` for the following:

1. https://loopback.io/doc/en/lb4/Controllers.md
2. https://loopback.io/doc/en/lb4/Routes.md
3. https://loopback.io/doc/en/lb4/DataSources.md
4. https://loopback.io/doc/en/lb4/Repositories.md
5. https://loopback.io/doc/en/lb4/Components.md

Also, the title "Behind the scenes" should be renamed to "Concepts". Rename the filename too with a redirection.

We should probably introduce some kind automation to detect 404s.

**Comment by vanderdill** [comment]
https://loopback.io/doc/en/lb4/REST-connector-example.html

The link of the rest example on the above article points to a code for lb2. 
These kind of things are very disappointing.

**Comment by achrinza** [comment]
@vanderdill LoopBack is an open source project and thrives on community contributions. Unfortunately it may not be possible to allocate resources to fix every problem in every nook and cranny. If you've found any issues, feel free to open a new issue, comment on and existing issue or even open a PR to fix it. We welcome inclusive contributions from the community and will try to help on a best-effort basis. 😀

**Comment by vanderdill** [comment]
I understand that @achrinza , I would never blame the community. 
My point is: I'm leading a big project, on that we choose loopback for being carried on the shoulders of a giant (Strongloop/IBM). Where is the effort of these companies to maintain the quality of the project?  
There is a beautiful home page, with their logos, where you see half a dozen of motivational features that for you should use loopback. Them you decide to use it in your project, and came across things like this I pointed.
I don't see these kind things happening with Angular, for instance. Where is the problem?

**Comment by dhmlau** [comment]
Should be fixed in PRs #6177 and #6199.
