### ISSUE TITLE
Overriding dataSource using app.dataSource as per documentation has no effect

### ISSUE THREAD

**Issue by 0x0aNL** [strongloop/loopback-next#6178]
## Steps to reproduce

Follow instructions on https://loopback.io/doc/en/lb4/Testing-your-application.html to create a testdb datasource and use it as described in section "Test your individual REST API endpoints":

1. lb4 -> set up new app
2. lb4 datasource -> setup MySQL datasource (only tested with MySQL, but presumably is the case for all datasources)
3. lb4 model -> add Test model with field id
4. lb4 repository -> add DefaultCrudRepository for Test model
5. Edit `src/__tests__/acceptance/test-helper.ts`:

Add:
```
import {juggler} from '@loopback/repository';
export const testdb: juggler.DataSource = new juggler.DataSource({
  name: 'db',
  connector: 'memory',
});
```
  
Change:
```
  await app.boot();
  await app.start();
```
To:
```
  app.dataSource(testdb);  
  await app.boot();  
  await app.migrateSchema();  
  await app.start();
```
6. Run: npm test

## Current Behavior

In the configured MySQL database, a table Test is created. Subsequent interactions with repositories also result in changes in the MySQL database (e.g. adding entities).

## Expected Behavior

As `app.dataSource()` was called with testdb, a memory connector, the MySQL connector should not have been used and no table should have been created (nor should any entities have been subsequently persisted in MySQL).

## Link to reproduction sandbox

https://github.com/0x0aNL/loopback-next/tree/dataSource-bug

(By the way, it might be worth pointing out in https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs that `tsconfig.json` needs to be replaced. Took me a while to figure out why `lb-tsc` was trying to build all kind of directories higher up.)

## Additional information

`node -e 'console.log(process.platform, process.arch, process.versions.node)'`  
`linux x64 12.18.3`

`npm ls --prod --depth 0 | grep loopback`  
```
@loopback/example-todo@3.7.1 /home/developer/documents/slip/project/loopback-next/examples/todo
├── @loopback/boot@2.5.0
├── @loopback/core@2.9.4
├── @loopback/repository@2.11.1
├── @loopback/rest@6.1.0
├── @loopback/rest-explorer@2.2.9
├── @loopback/service-proxy@2.3.7
├── loopback-connector-mysql@5.4.4
├── loopback-connector-rest@3.7.0
```

## Related Issues

The documentation (i.e. https://loopback.io/doc/en/lb4/Testing-your-application.html) does not explain that testdb needs to have the same `name` as the connector you're trying to override. It may not be obvious to all developers that that is the case.

## Apparent Fix

If I switch the order of `app.boot()` and `app.dataSource(testdb)`, the memory connector seems to be used successfully.
Perhaps the only required fix would be to change the documentation.

**Comment by nabdelgadir** [comment]
Thanks for reporting this! We just landed a PR to fix the documentation.
