### ISSUE TITLE
Allow exclude datasource when migrateSchema

### ISSUE THREAD

**Issue by beary** [strongloop/loopback-next#6181]
## Suggestion

Provide a way to exclude a datasource when `migrateSchema`.

## Use Cases

There are two datasources in my application. Since one datasources belongs to other application, the current application has no permission to modify it, but `migrateSchema` will update the models of all datasources.
https://github.com/strongloop/loopback-next/blob/a8b3b00845e8922ca4fd2572ffeedfaa4a979b50/packages/repository/src/mixins/repository.mixin.ts#L281-L294

## Examples

```javascript
await app.migrateSchema({
  existingSchema,
  exclude: [
    'SomeDataSourceName'
  ]
})
```
or
```javascript
// This is better and can avoid typos
import { SomeDataSource } from './datasources'

await app.migrateSchema({
  existingSchema,
  exclude: [
    SomeDataSource
  ]
})
```

## Acceptance criteria

TBD - will be filled by the team.

**Comment by achrinza** [comment]
Would it be possible to use an allowlist of models instead? Th

```typescript
await app.migrateSchema({
  existingSchema,
  models: [
    'model1',
    'model2',
    // ...
  ]
})
```

**Comment by beary** [comment]
@achrinza Thanks!
My fault, I should read the document carefully.
