### ISSUE TITLE
More intuitive RestApplication options object

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#6201]
Currently, the `RestApplication` options object look like this:

```ts
new RestApplication({
  rest: {
    port: 3001,
    host: '127.0.0.1'
  }
});
```

It should look like this:

```ts
new RestApplication({
  port: 3001,
  host: '127.0.0.1'
});
```

When we already know it is a REST application, we shouldn't have to add a `rest` property again to the options object, it is not intuitive.

If, for any reason, we can't bring the server options to the top level, `rest` should be named too `server` to be more accurate about what we are dealing with.

```ts
new RestApplication({
  server: {
    port: 3001,
    host: '127.0.0.1'
  }
});
```

**Comment by dhmlau** [comment]
I think there was a discussion a while back that one Application can have multiple servers, probably that's why we have this configurations. 
cc @raymondfeng

**Comment by raymondfeng** [comment]
I would like to keep the application config consistent for all `Application` classes. There are other common properties that can be configured for different types of applications, such as `shutdown` hooks. Using `RestConfig` for `RestApplication` will lose such capabilities.

**Comment by hacksparrow** [comment]
> I think there was a discussion a while back that one Application can have multiple servers, probably that's why we have this configurations.

@dhmlau yes, in case of `Application` it is understood. However, here we are specifically dealing with `RestApplication`, which cannot have any more servers. At the same time, I can very well understand where @raymondfeng is coming from.
