### ISSUE TITLE
Rename @bind() to @injectable

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#6209]
@raymondfeng @bajtos how about renaming `@bind()` to `@binding()`?

`@bind()` makes it sound like it is performing the binding process, when it is not, it is a config for the binding. `@binding()` is less confusing and more self-explanatory IMO.

**Comment by achrinza** [comment]
Angular, Nestjs, and tsrynge use `@injectable`. Adopting this naming may make it more recognisable for those who come from other frameworks with DI.

**Comment by hacksparrow** [comment]
That's looks good too.

**Comment by raymondfeng** [comment]
Please be aware that decorators can be easily aliased such as:

```ts
import {bind as injectable} from '@loopback/core';

// or

export const injectable = bind;
```

**Comment by raymondfeng** [comment]
I don't mind exporting `@injectable` as an alias in `@loopback/context` itself while keeping `@bind`.

**Comment by hacksparrow** [comment]
> I don't mind exporting @injectable as an alias in @loopback/context itself while keeping @bind.

Great, then we should start using `@injectable` in the codebase and docs. It is a tiny confusion, which can be cleared up in a few minutes by looking up the docs, but many tiny confusions can add up to cause major friction in using and understanding the framework.

Once done, we will be no longer need to add notes like "To understand the difference between @bind() and ctx.bind(), see Configure binding attributes for a class." in https://loopback.io/doc/en/lb4/Binding.html.

**Comment by dhmlau** [comment]
PR #6321 in progress.

**Comment by hacksparrow** [comment]
Closed via https://github.com/strongloop/loopback-next/pull/6321
