### ISSUE TITLE
Nested Relations not working 

### ISSUE THREAD

**Issue by argupta23** [strongloop/loopback-next#6228]
## Steps to reproduce
There are 3 controllers
1. User
2. Devicetempl
3. Device

Models have the following relations

User.model.ts
@hasMany(() => Device)
  devices: Device[];
@hasMany(() => Devicetempl)
  devicetempls: Devicetempl[];

Devicetempl.model.ts
@hasMany(() => Device)
  devices: Device[];
@belongsTo(() => User)
  userId: string;

device.model.ts
  @belongsTo(() => Devicetempl)
  devicetemplId: string;

using "lb4 relation" I've confirmed that all inclusion resolvers for these relationships are in place and working. The relevant portion of my backend function is below:

`async find(@param.path.string('id') id: string>): Promise<(User & UserRelations)[]> {
    let foundUser = await this.userRepository.find({
      include: [
        {
          relation: 'devicetempls',
          scope: {
            include: [{relation: 'devices'}],
          },
        },
      ],
      where: {id: id},
    });
   return foundUser;
}`

When I test it within explorer I am able to get the associated devicetempl's associated with this user, but it does not contain the devices associated with the devicetempl.

Looking into the mongodb debug log, I can see the result of the query does contain the devices associated with the devicetempl, but for some reason they are not contained in the explorer output.

`
  loopback:connector:mongodb all Device { fields: [ 'deviceid' ], where: {} } null [
  { _id: 5f3c7d49d1b72df053895ee6, deviceid: '1234567' },
  { _id: 5f3d6551c3f1126e385867db, deviceid: 'abcdef' } ]
`

I've confirmed that my formatting looks correct using issues #3453 and #4644, as well as reading the bottom section of these master docs: 
[https://github.com/strongloop/loopback-next/blob/master/docs/site/HasMany-relation.md#query-multiple-relations](url)
.Additionally, a previous StackOverflow question (48391685) seems to address this formatting and everything looks to match. 

Is there a possible bug between Loopback 4 and MongoDB nested HasMany queries or does anyone else possibly spot anything else wrong with what I am doing? 

Thank you in advance for the help!

## Additional information

 npm ls --prod --depth 0 | grep loopback
├── @loopback/authentication@1.2.1
├── @loopback/authentication-passport@2.1.11
├── @loopback/authorization@0.6.4
├── @loopback/boot@2.4.1
├── @loopback/cli@2.12.0
├── @loopback/core@2.9.3
├── @loopback/openapi-v3@3.4.7
├── @loopback/repository@2.11.0
├── @loopback/rest@6.0.0
├── @loopback/rest-crud@0.8.11
├── @loopback/rest-explorer@2.2.8
├── @loopback/service-proxy@2.3.6
├── loopback-connector-mongodb@5.3.0

**Comment by dhmlau** [comment]
@agnes512, could you please take a look? Thanks.

**Comment by argupta23** [comment]
@dhmlau 

Earlier last week I brought this up on the Slack channel and with help from Agnes was able to resolve the issue.

Thanks again for your help.
