### ISSUE TITLE
enum in path is not respected in validation

### ISSUE THREAD

**Issue by Evaw** [strongloop/loopback-next#6247]
## Steps to reproduce
create an api with decorators

```

@operation('get', 'foo/{type}`)
public async getFoo(
  @param({
    name: 'type',
    in: 'path',
    description: 'Type of the Resource Group',
    required: true,
    schema: { type: 'string', enum:  ['type1', 'type2']},
    }
  ) type: string
```

## Current Behavior
loopback allows requests that do not match the enum in the type.
ex GET /foo/bar
allows function getFoo to be called

## Expected Behavior
loopback should return a 400 because the string does not match the enums provided in the schema

we execute the function when validation should have failed

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@Evaw, could you please try to replace `schema` with `jsonSchema`? 
Here is my working example in the model:
```
@property({
    type: 'string',
    jsonSchema: {
      type: 'string',
      enum: ['CA', 'US'],
    },
  })
  countryCode: string;
```

**Comment by Evaw** [comment]
the decorator in the example is not the same though. Im trying to use a path param for an api definition. The example is a model definition. We are using the following decorators, as you can see, Im using the `param` decorator, but the enum in its schema is not enforced  

```
const typeSchema: ParameterObject = {
    name: 'type',
    in: 'path',
    required: true,
    jsonSchema: { type: 'string', enum: ['foo', 'bar']},
};
    @operation('get', '/resource-groups/{type}', {
        ...
   })
    public async getResourceGroupList(
        @param(typeSchema) type: string
    ): Promise<string[]> {
        return await this.handler.getResourceGroupList(type);
    }
```

**Comment by dhmlau** [comment]
@raymondfeng, it looks like the ajv validation is not applicable to the OpenAPI parameters? Similar to #6274?

**Comment by raymondfeng** [comment]
We have a gap - parameters with simple types are not validated by AJV. I'll submit a fix.
