### ISSUE TITLE
passport-login controller content question

### ISSUE THREAD

**Issue by argupta23** [strongloop/loopback-next#6248]
@raymondfeng @dhmlau 

I am trying to understand why within this example did somebody use 

`content: {
        'application/x-www-form-urlencoded': {schema: CredentialsSchema},
      },`

as compared to

`content: {
        'application/json': {schema: CredentialsSchema},
      },`

If we look at other examples posted the default preference seems to be "application/json"

Also please see issue #6217 

I am working on building an Angular 10 example with authentication supporting different providers (beyond what this example supports) and want to get your input before I put in the effort.

I am happy to share that version with the community when done.

Appreciate your help and support.

Thanks

**Comment by dhmlau** [comment]
If I'm not mistaken, `application/x-www-form-urlencoded` is used as the content type because the signup page (https://github.com/strongloop/loopback-next/blob/master/examples/passport-login/web-application/views/pages/signup.jade) which calls the `/signup` endpoint is a form.

**Comment by jannyHou** [comment]
Thanks @dhmlau agreed. @argupta23 does comment https://github.com/strongloop/loopback-next/issues/6248#issuecomment-685249203 answer your question? If yes can we close this question and focus on the fix in https://github.com/strongloop/loopback-next/issues/6217?

**Comment by argupta23** [comment]
@jannyHou @dhmlau 

I do understand the difference between the two formats, what I wanted to understand if there was a particular scenario leading to the x-www format.

It seems to me that this was just a user preference.

Yes, we can close this and track the progress in #6270 

Thanks
