### ISSUE TITLE
'ER_CANNOT_ADD_FOREIGN'

### ISSUE THREAD

**Issue by georve** [strongloop/loopback-next#6259]
i'm trying to implement foreign keys to see if my search using related elements work finally... but in the migration process i have the following error by MYSQL

  code: 'ER_CANNOT_ADD_FOREIGN',
  errno: 1215,
  sqlMessage: 'Cannot add foreign key constraint',
  sqlState: 'HY000',
  index: 0,
  sql: 'ALTER TABLE `Agency` ADD  CONSTRAINT `fk_agency_groupId` FOREIGN KEY (`groupId`) REFERENCES `Group`(`id`),ADD  CONSTRAINT `fk_agency_agencyId` FOREIGN KEY (`parentId`) REFERENCES `Agency`(`id`)',
  statusCode: 500

my object is defined like this

@model({
  settings: {
    strict: true,
    foreignKeys:{
      fk_agency_groupId:{
        name:'fk_agency_groupId',
        entity:'Group',
        entityKey:'id',
        foreignKey:'groupId',
      },
      fk_agency_agencyId:{
        name:'fk_agency_agencyId',
        entity:'Agency',
        entityKey:'id',
        foreignKey:'parentId',
      },
    },

  }})
export class Agency extends Entity {
  @property({
    type: 'string',
    required: true,
    index: {
      unique: true,

in the migration schema i put first Group table and the second foreign keys is a field inside in Agency
.

I tested the sentence in the mysql workbench and i having the same error, it is like the sentence is not correct

'ALTER TABLE `Agency` ADD  CONSTRAINT `fk_agency_groupId` FOREIGN KEY (`groupId`) REFERENCES `Group`(`id`),ADD  CONSTRAINT `fk_agency_agencyId` FOREIGN KEY (`parentId`) REFERENCES `Agency`(`id`)',

**Comment by georve** [comment]
the migrate has the following table order

    models: ['Group','Enterprise','Agency','Agent','AgentCode', 'Ramos','Products','Plan','Deducible','User', 'Role', 'UserRole','Permissions', 'Insured','Policy',
    'Quotation','Documents','AgentDocuments','QuotationDocuments','InsuredDocuments','Commission','CommisionInfo','Claim','PoliciesDeducibles','PolicyPayment','PolicyRenovation',
    'ClientHistoryContact','StatusRnAgent','RequestNewAgent','Country','CrmDate','EmailTemplate','GoogleFolder','Translation','HistoryComments'],
  });

**Comment by achrinza** [comment]
Are the foreign key and their target keys' type the same (e.g. `parentID` of type `number` should reference `ID` of the same type)?

**Comment by georve** [comment]
sorry finally I could solve the error it was misspelled the var...
