### ISSUE TITLE
@loopback/authentication JwtStrategy crash

### ISSUE THREAD

**Issue by mikstur** [strongloop/loopback-next#626]
# Description/Steps to reproduce

I am making use of the @loopback/authentication package. I am using the JwtStrategy from the passport-jwt node module.

If I include a bearer token that is not a true JWT token (like dummy text). Then I get the following error and the server crashes:

TypeError: Cannot read property 'Unauthorized' of undefined
    at JwtStrategy.strategy.fail (/Users/../Documents/app/services/authentication/node_modules/@loopback/authentication/src/strategy-adapter.ts:63:30)
    at /Users/../Documents/app/services/authentication/node_modules/passport-jwt/lib/strategy.js:106:33
    at /Users/../Documents/app/services/authentication/node_modules/passport-jwt/node_modules/jsonwebtoken/verify.js:27:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

Anybody experienced this before?

If I use a normal JWT token it works fine.

**Comment by kjdelisle** [comment]
@mikstur Hey, sorry I missed this!

It sounds like it's implying that the `HttpErrors` class, which we re-export from `@loopback/rest` doesn't exist.
```ts
      // add failure state handler to strategy instance
      strategy.fail = function(challenge: string) {
        reject(new HttpErrors.Unauthorized(challenge));
      };
```

Would you be able to make a small sample application that shows this failing with the dummy token? That would definitely help with reproducing the issue.

**Comment by kjdelisle** [comment]
@mikstur It's been awhile, but have you had a chance to try it out with the newer iterations of the framework? We did fix a bug awhile back involving the proper export of the `HttpErrors` types, so that might've helped.

**Comment by bajtos** [comment]
Closing as abandoned.
