### ISSUE TITLE
Support `ajv-errors` in parameter schema

### ISSUE THREAD

**Issue by likexoo** [strongloop/loopback-next#6274]
## Suggestion

Support [ajv-errors](https://github.com/ajv-validator/ajv-errors) in parameter schema.

## Use Cases

So we can define custom error message.

## Examples

```ts
    @get('/v1/test/{_id}')
    public async test(
        @param({
            in: 'path',
            name: '_id',
            schema: {
                type: 'number'
            },
            errorMessage: '....' // <= 
        }) _id: unknown

    ) {
        // ...
    }
```

## Acceptance criteria

TBD - will be filled by the team.

**Comment by raymondfeng** [comment]
We support `ajv-errors` for model properties, see https://loopback.io/doc/en/lb4/Model.html#custom-validation-rules-and-error-messages. Do you propose to extend it for OpenAPI parameters?

**Comment by likexoo** [comment]
@raymondfeng Yes and using it in `@param`.

**Comment by raymondfeng** [comment]
PR #6285 will probably fix this issue.

**Comment by dhmlau** [comment]
Closing as done since PR #6285 has landed.
