### ISSUE TITLE
Properties with default value are generated but then retrieved as undefined

### ISSUE THREAD

**Issue by diego92sigma6** [strongloop/loopback-next#6281]
> **Maintainer's Note:**
> Slack thread: https://loopbackio.slack.com/archives/C01177XQN8N/p1599256501357600

## Steps to reproduce

* Create a model, use MongoDB connector
* Add property with default value. Example: 
`@property({
		type: 'date',
		name: 'date',
		default: () => new Date(),
	})
	date?: Date`
* Create and store an instance of this model
* Confirm that default value is correctly generated
* Perform a this.repo.find() to get it back

## Current Behavior

Properties are well retrieved, except for the one with a default value - it is `undefined`

## Expected Behavior

Default generated value is contained in the result of repo.find()

## Link to reproduction sandbox

Soon

## Additional information

  node -e 'console.log(process.platform, process.arch, process.versions.node)'
  **win32 x64 12.18.3**
  npm ls --prod --depth 0 | grep loopback
```+-- @loopback/authentication@6.0.0
+-- @loopback/authentication-jwt@0.5.1
+-- @loopback/authorization@0.6.5
+-- @loopback/boot@2.5.0
+-- @loopback/core@2.9.4
+-- @loopback/repository@2.11.1
+-- @loopback/rest@6.1.0
+-- @loopback/rest-explorer@2.2.9
+-- @loopback/service-proxy@2.3.7
+-- loopback-connector-mongodb@5.3.0
```

**Comment by achrinza** [comment]
Would using [`defaultFn: 'now'`](https://loopback.io/doc/en/lb4/Model.html#property-decorator) solve the issue?

**Comment by achrinza** [comment]
Quoting from Slack:

> Found out. Happended to be the "include" field in the filter query. I needed to include it :sweat_smile:

Glad you were able to solve the issue!

Closing as solved.

**Comment by diego92sigma6** [comment]
Sorry, I posted this 10 mins ago but had this problem for 5 hours. 
It's the include field in the filter query!  😅😅

**Comment by g-wozniak** [comment]
It does not work for 
```
  @property({
    type: 'string',
    id: true,
    required: true,
    generated: false,
    defaultFn: 'uuidv4',
  })
  id: string;
```
either. It just leaved `id` undefined upon constructing.

**Comment by dougal83** [comment]
@g-wozniak What do you get without `generated: false,`?

**Comment by g-wozniak** [comment]
I've tried removing/modyfing all those props.
Having a model:
```
export class XXX extends Model {
  @property({
    type: 'string',
    id: true,
    required: true,
    defaultFn: 'uuidv4',
  })
  id: string;

  constructor(data?: Partial<XXX>) {
    super(data);
    //    this.id = data?.id ? data.id : uuidv4();
  }
}
```
this test is failing:
```
const xxx = new LossSubType();
expect(xxx.id).to.not.be.undefined();
```
if I comment out the bit in the controller.

**Comment by dougal83** [comment]
@g-wozniak, I'm not sure that test will ever return anything but undefined for `id`.  As I understand it, the `@property` decorator is providing instructions for the db connector to configure the `id` property in the database.  Simply creating an instance of the class will not apply the decorator that is for the db connector to apply.  Perhaps you can take a look at existing tests for examples to follow?

**Comment by g-wozniak** [comment]
Yes, I'd agree because it seems like it's a DB-level function and that was my impression (similar to how ORMs work, i.e. Mongoose with similar option). Would be great if in the documentation [here](https://loopback.io/doc/en/lb4/Model.html#overview)  "A name of the function to call to set the default value for the property." to describe a bit more on what layer this function is executed.
