### ISSUE TITLE
Intelligence

### ISSUE THREAD

**Issue by Tabby-web** [strongloop/loopback-next#6282]
_intelligences_

_Originally posted by @BROGVOIDOVO in https://github.com/kamranahmedse/developer-roadmap/issues/767#issuecomment-686864201_

**Comment by Tabby-web** [comment]
[]()@fabien

**Comment by raymondfeng** [comment]
@Tabby-web Please don't spam our issues.

**Comment by Tabby-web** [comment]
@raymondfeng so what should I do to help

**Comment by BROGVOIDOVO** [comment]
_Authic_
