### ISSUE TITLE
Health checker OOB

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#63]
"Is there a preferred way to do a health check endpoint in LoopBack? I’m seeing this which looks decent: https://www.npmjs.com/package/healthcheck-fastit" as per @erin.mckean on Slack

Something we should consider IMO.

**Comment by bajtos** [comment]
I am closing this issue because we are not going to have time to work on this in the next 6-9 months. However, we are happy to accept a pull request contributing this feature.
