### ISSUE TITLE
Blog post comparing lb-next to other frameworks

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-next#630]
At some point (closer to GA #details of architecture and implementation have been fleshed out), it would be nice to have a blog on how LB4 compares with other frameworks such as NestJS.  As well, consider frameworks summarized in http://loopback.io/resources/#compare.

In Slack, Raymond stated:
My take is that NestJS handles incoming requests, as Express ++
LoopBack 4 is Express ++ & Integration/Composition for API/microservices
The key differentiator is that LB deals with API implementation/composition with backend systems
LB connects the dots between accepting api requests and interacting with existing resources
See [Crafting LB 4](http://loopback.io/doc/en/lb4/Crafting-LoopBack-4.html) for more info. The right half of the 1st diagram is what NestJS is missing.

**Comment by bajtos** [comment]
I think a blog post like this can be published soon after the GA is released, it's not necessary to include it in GA scope. @raymondfeng @dhmlau please let me know if you disagree.
