### ISSUE TITLE
Prepare to participate in Hacktoberfest 2020

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#6303]
Quoting from https://hacktoberfest.digitalocean.com:

> Open source is changing the world - one pull request at a time.
> Hacktoberfest encourages participation in the open source community, which grows bigger every year.

@dhmlau @raymondfeng and @bajtos agreed to join the festival this year.

Requirements (see https://hacktoberfest.digitalocean.com/details/#maintainers):

- [x] Apply the "Hacktoberfest" label to issues in your GitHub project that are ready for new contributors to work on.
  --> _@bajtos to review "good first issues" and pick candidates for "Hacktoberfest" label_

- [x] Add a CONTRIBUTING.md file with contribution guidelines to your repository 
  --> _all is good - see https://github.com/strongloop/loopback-next/blob/master/docs/CONTRIBUTING.md_

- [x] Choose issues that have a well-defined scope and are self-contained.
  --> _@bajtos to review "good first issues" and add details where needed_

- [x] Adopt a code of conduct to foster a greater sense of inclusion and community 
  --> _ see https://github.com/strongloop/loopback-next/pull/4802_

Further reading: [A maintainers guide to Hacktoberfest](https://medium.com/gitcoin/a-maintainers-guide-to-hacktoberfest-21405c8ff09f).

Other tasks:

- [x] Write a blog post to announce our participation - https://strongloop.com/strongblog/2020-hacktoberfest/

- [x] Open a GH issue describing how to participate, pin in a the top - https://github.com/strongloop/loopback-next/issues/6456

**Comment by dhmlau** [comment]
@bajtos, perhaps we can publish a blog towards the end of September to promote about this?

**Comment by bajtos** [comment]
> @bajtos, perhaps we can publish a blog towards the end of September to promote about this?

I am thinking about the same! My plan is to write it early and schedule publishing for Tuesday 2020-09-29.

**Comment by bajtos** [comment]
Closing as done. I haven't managed to review all good-first-issues yet. There should be enough Hacktoberfest-labeled issues for the start, I'll review the remaining candidates in the next few days.
