### ISSUE TITLE
API-Title and -Version are being overwritten by values in the package.json

### ISSUE THREAD

**Issue by markus-hsk** [strongloop/loopback-next#6310]
I've a LB4 application with this code:

```typescript
this.bind(RestExplorerBindings.CONFIG).to({path: '/explorer'});
this.api({
             openapi: '3.0.0',
             info: {
                 title: 'Swagger OpenAPI for MyApp',
                 version: '3.2 Build 12345',
                 contact: {
                     name: 'My Name'
                 }},
             servers: [{url: 'http://localhost:3000'}],
             paths: {}
         });
```

I expect the RestExplorer to deliver the title "Swagger OpenAPI for MyApp" and the version "3.2 Build 12345". This worked till i recently made an update to the packages. Now the RestExplorer ignores the given strings and replaces it with name and version from the package.json. As the contact data is correctly placed in the json i assume, the use of this method is correct. So why are title and version ignored?

## Steps to reproduce

1. Create an lb4 app and add the code to the application.ts constructor.
2. Call http://localhost:3000/explorer/openapi.json and look at info.title and info.version

## Current Behavior

info.title is taken from package.json->name
info.version is taken from package.json->version

## Expected Behavior

info.title should be `Swagger OpenAPI for MyApp`
info.version should be `3.2 Build 12345`

## Additional information
node -e 'console.log(process.platform, process.arch, process.versions.node)'
=> `win32 x64 12.16.1` & `linux x64 10.21.0`

npm ls --prod --depth 0 | grep loopback
=> 
```bash
backend-loopback@2.2.0 C:\Users\mark1911\htdocs\backend-loopback
+-- @loopback/authentication@6.0.0
+-- @loopback/boot@2.5.0
+-- @loopback/context@3.10.0
+-- @loopback/core@2.9.4
+-- @loopback/openapi-v3@3.4.8
+-- @loopback/repository@2.11.1
+-- @loopback/rest@6.1.0
+-- @loopback/rest-explorer@2.2.9
+-- @loopback/service-proxy@2.3.7
+-- loopback-connector@4.11.1
+-- loopback-connector-mysql@5.4.4
+-- loopback-connector-rest@3.7.0
```
_Previous versions, before the upgrade: https://github.com/strongloop/loopback-next/issues/6310#issuecomment-689996274 With these the result was as expected_

## Related Issues

Could not yet find any matching issues.

**Comment by jannyHou** [comment]
Looking. 
> This worked till i recently made an update to the packages

Seems a regression, @markus-hsk do you know the working version of the packages? especially `@loopback/rest` and `@loopback/openapi-v3`

**Comment by raymondfeng** [comment]
@jannyHou It may be related to https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/spec-enhancers/info.spec-enhancer.ts#L56. We can improve the enhancer to honor existing `title` and `version` properties so that they won't be overriden.

**Comment by markus-hsk** [comment]
@jannyHou 
Ah yes of course - sorry, i just forgot to add that to my initial post:

```bash
+-- @loopback/authentication@3.3.3
+-- @loopback/boot@1.7.4
+-- @loopback/context@1.25.1
+-- @loopback/core@1.12.4
+-- @loopback/openapi-v3@1.13.0
+-- @loopback/repository@1.19.1
+-- @loopback/rest@1.26.1
+-- @loopback/rest-explorer@1.4.10
+-- @loopback/service-proxy@1.3.17
+-- loopback-connector@4.11.0
+-- loopback-connector-mysql@5.4.3
+-- loopback-connector-rest@3.6.0
```

**Comment by markus-hsk** [comment]
@raymondfeng I commented the lines 49-52 out and checked the OpenAPI-Result. It is indeed the point, where the values are being overwritten.
