### ISSUE TITLE
includes with belongTo and hasMany relations

### ISSUE THREAD

**Issue by fgvicente** [strongloop/loopback-next#6318]
I have this filter

> {"where": 
>               {"and": [
>                   {"idCliente": "${cliente}"},
>                   ... // more filters
>                 ]
>               }
>             ,
>             "include": [
>               {
>                 "relation": "Articulos",  <---hasMany
>                 "relation": "vendedor"  <---belongto
>               }
>             ],"order":["fecha DESC"]
>   }

but the response only get belongTo relations but omit hasMany relation
if i include only one in filter, not both,  working fine

**Comment by hacksparrow** [comment]
@fgvicente please share a minimal app reproducing the behavior, we can take a look at the issue.

**Comment by nabdelgadir** [comment]
If you want to query more than one relation, you have to use the following syntax:

```json
"include": [{"relation": "Articulos"}, {"relation": "vendedor"}]
```

**Comment by georve** [comment]
{
   "include":[
      {
         "relation":"insured",
         "scope":{
            "where":{
               "insured_city":"Carora"
            }
         }
      }
   ]
}

**Comment by fgvicente** [comment]
@nabdelgadir thanks!! now works
