### ISSUE TITLE
Discussion: relation between App, Server and Controller

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#632]
Had a talk with @kjdelisle 

By reading our code/doc, I feel now the concept `Controller` is bound to an `App` not a `Server`, a typical example would be how we guide people to register a controller: `app.controller('foo')`.

But after the REST refactor, when getting apispec of a server we assume each controller only maps to one server:
see https://github.com/strongloop/loopback-next/blob/8c7f474a72df23a1fa2d33bee9d36ba41031fd63/packages/rest/src/rest-server.ts#L160

This may lead to confusion when an app has multiple servers: do we allow one controller contains routings for multiple servers? If so the controller should organize apispec fragments in a server-awared way(each fragment knows which server it belongs to).

IMO it makes sense to limit a controller to a specific server, but @kjdelisle brought me a good scenario that may require one controller to define routing for multiple servers:

```
app: 
  - a REST server `foo`
  - a GRPC server `bar`
```
now we need a controller display server properties like "version" for `foo` and `bar`.

--- 

There might be more discussion about multiple server support exist.

@raymondfeng @bajtos @strongloop/sq-lb-apex any thought?

**Comment by raymondfeng** [comment]
Controllers are assets of an `app`. When they are exposed to different servers, the metadata (such as paths, parameters) on the controller class should be agnostic to servers of the same type. 

We can potentially introduce additional metadata to allow a controller to be only made available to certain server instances. That can happen at server configuration level.

**Comment by bajtos** [comment]
Labelling as non-MVP. For MVP, we are focusing on a single transport/server instance per app.

**Comment by bajtos** [comment]
In GA, we are still focusing on a single transport/server instance per app. Removing this story from GA scope.
