### ISSUE TITLE
Documentation: Understanding and using Request-scope Context

### ISSUE THREAD

**Issue by mschnee** [strongloop/loopback-next#6325]
User Story
=======
Your API has a contextual route, such as `POST https://api.my-business.com/company/1/employee/2/avatarUrl`, which can allow an administrator, a business owner, a manager, or the employee to change their photo.  Behind the REST controller function, there can be several services: `photoService`, `companyService`, `userService`.  All of these services require loading some basic information from the `company` table of the database.  Ideally, you only want to load it once.

In Express, it's common to use `router.param()` as a router interceptor, and then to store results on `req.local`
```js
router.param('company_id', (req, res, next) => {
  database.collection('company').findById(req.params.company_id).then(result => {
    req.local.company = result;
    next();
  }).catch(e => next(e));
});

router.use('/:companyId/employee', companyEmployeeRouter);
// for all routes in companyEmployeeRouter, `req.local.company` will be set to the database result object.
```

This is an example of data that exists in the context of the request itself.  Between the request being received by express and the response being written to the network, this data is unique to that request alone.

This should be possible in Loopback 4, but how to do so is not immediately clear.  Ley's document and example the Loopback 4 equivalent:
- How can we access the local request context so that we can bind/get data?
  - Or, should we explicitly create a specific LOCAL_SCOPE binding key in the default sequence for this purpose?
- How can we write a provider service that can be injected into multiple other services and controllers, which can fetch- if necessary- and return a value that is specific to the context of a request.
- What are some other patterns?  Examples can include classes bound with a TRANSIENT BindingScope, which are created new every time they are injected, so that local member variables exist for the lifetime of the function they were injected in to.
- SUGGESTION: `BindingScope.Request` or `BindingScope.LocalScope`, so that injected services are only created once for the lifecycle of a request, and can explicitly be considered stateful.

**Comment by dhmlau** [comment]
Closing as done since PR #6332 and #6333 are landed.
