### ISSUE TITLE
Add banner to loopback.io about LBNext

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#633]
Per our discussion today, we probably want to have a banner in loopback.io to broadcast we're working on LB4.  

Marking this as `LoopBackNext-beta` and `p1`, but this should/can be done before beta.

cc @crandmck

**Comment by crandmck** [comment]
How does this differ from #634?
Is this issue for the home page http://loopback.io/ only?  Is it for any other pages or navigation elements?

**Comment by dhmlau** [comment]
@crandmck , from my understanding, this task is about adding some information in loopback.io that LBNext is on the way (or we're going to have beta release soon), to make people aware that there is LB4.  The timeframe for this could be anytime now, no need to wait for beta to be out. 

For #634, it's for changing the content that the top nav bar (e.g. getting started, examples, documentation link, etc) points to LB4 specific.  The timeframe for this would be GA, could be Core-GA or Tooling-GA, when we've reached function parity to LB3.

**Comment by crandmck** [comment]
I think https://github.com/strongloop/loopback.io/pull/487 addressed this.  
@dhmlau If I need to do anything further, please LMK and reopen.
