### ISSUE TITLE
Specify type of ids in a repository with multiple ids

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#6343]
Having two properties of type PK/id is not supported by the DefaultCrudRepository.

The specification of DefaultCrudRepository is:
```
export class DefaultCrudRepository<
  T extends Entity,
  ID,
  Relations extends object = {}
> implements EntityCrudRepository<T, ID, Relations> {
  ...
}
```

So the problem is that I can only specify the type of a single id and not of both as you can see in the example below.

**Example Code:**
```
@model()
class UserHasPermission extends Entity {
  @property({id: true})
  userId: number;
  @property({id: true})
  permissionId: number;

  constructor(data: Partial<UserHasPermission>) {
    super(data);
  }
}
```
```
class UserHasPermissionRepository extends DefaultCrudRepository<
  UserHasPermission,
  typeof UserHasPermission.prototype.id         <<<<<----------- Here
> {
  constructor(dataSource: juggler.DataSource) {
    super(UserHasPermission, dataSource);
  }
}
```

Any solution?

## Additional information

Node: darwin x64 14.10.1

**_I have this in the loopback repository, in a test for a HasAndBelongsToMany relation_**

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
In this case, we should have the following id type:

```ts
type IDType = Pick<UserPermission, 'userId' | 'permissionId>
```

**Comment by achrinza** [comment]
Would this be a duplicate of #1830?

**Comment by frbuceta** [comment]
> Would this be a duplicate of #1830?

Yes, I am going to close this issue and we move to that one
