### ISSUE TITLE
Create a LB4 version of CoffeeShop app

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#635]
Per our discussion this morning:
In LB3, we have CoffeeShop app as one of the example app.  
It would be nice to have a similar app using LB4. 
LB3 CoffeeShop make sure of CLI.  Having similar app in LB4 can guide us on what is needed for Tooling GA.

**Comment by bajtos** [comment]
This may be a duplicate of https://github.com/strongloop/loopback-next/issues/669

**Comment by dhmlau** [comment]
probably, and same idea for the MVP epic.  Closing it.
