### ISSUE TITLE
[GSSC-TVT]Loopback 3Q TVT updated translaton not in lb4 

### ISSUE THREAD

**Issue by candytangnb** [strongloop/loopback-next#6351]
## Current Behavior
Loopback 3Q TVT updated translaton not in lb4. 
Updates in this PR https://github.com/strongloop/loopback-next/pull/6300 could not be verified by tester in 3Q TVT final pass

For example:
PTBR
<img width="733" alt="image" src="https://user-images.githubusercontent.com/26452457/93048608-dc018780-f691-11ea-9464-f89c860c528b.png">
<img width="573" alt="image" src="https://user-images.githubusercontent.com/26452457/93048635-e885e000-f691-11ea-804a-1f18b32431cb.png">

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@candytangnb, we haven't published a release yet. Will notify here when there's a new release that includes the change. Thanks.

**Comment by candytangnb** [comment]
Thanks, @dhmlau. I know that LB has its own release plan. We have to open this issue for tracking and then let tester exit TVT.

**Comment by dhmlau** [comment]
@candytangnb, FYI - `@loopback/cli@2.14.0` was just published.

**Comment by candytangnb** [comment]
Checking in @loopback/cli@2.15.1. Translation have been in.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/26452457/93545891-25085300-f994-11ea-981b-7a3934fb2715.png">
