### ISSUE TITLE
docs: Rework in Key Concepts

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#636]
Per our discussion this morning, a few things to rework the `Key Concepts`:

## Acceptance Criteria
- key concept landing page includes
  - [x] short description of each concept, instead of simply links to each of the concept page
  - [ ] ~big picture how each concept come into play (might be coming from `Crafting LBNext` by @raymondfeng )~
- [ ] Order of the concepts might need to re-arrange
- [ ] add `Component` paragraph describing what they are, along with links to [Using Components](http://loopback.io/doc/en/lb4/Using-components.html) and [Creating Components](http://loopback.io/doc/en/lb4/Creating-components.html)

/cc @crandmck

**Comment by dhmlau** [comment]
There might be some changes due to: https://github.com/strongloop/loopback-next/issues/637

**Comment by shimks** [comment]
Waiting for https://github.com/strongloop/loopback-next/issues/650 to land, so that Application can also be a part of Key Concepts
