### ISSUE TITLE
In consistent documentation for Calling-other-APIs-and-web-services

### ISSUE THREAD

**Issue by tripled1313** [strongloop/loopback-next#6369]
In the documentation for https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html

The example code is not consistent, it switches between a calculator with 2 parameters in the service, and using 1 parameter in datasourse example.

It also does not show how to pass different types of parameters, like an object from the calling code through to the final API.

Showing how to pass an instantiated MODEL would be very useful, and it should be shown as an example.

## Acceptance Criteria
- [ ] split the instructions to call SOAP and REST services as separate page
- [ ] in each instruction, include examples that involves other types in parameters.
- [ ] For calling REST service, include:
  - [ ] docs to explain the template if the [REST connector readme](https://loopback.io/doc/en/lb4/REST-connector.html) doesn't contain sufficient information
   - [ ] example to call POST (there's only GET in the example)

**Comment by dhmlau** [comment]
@tripled1313, thanks for bringing this up. I agree that the docs for calling out other APIs is a bit messy, especially when we're trying to combine the instructions to call SOAP and REST services together. Do you have some publicly available REST service that we can use as an example? 

Based on your comments, I have the following proposal:
- split the instructions to call SOAP and REST services as separate page
- in each instruction, include examples that involves other types in parameters.
- For REST, include example to call POST (there's only GET in the example)

What do you think?

**Comment by tripled1313** [comment]
Thanks for looking into this, no, sorry no I do not.  
It looks good, what would also be nice is a link to somewhere that helps explain the what the template, body... are. 
For me, I'm not even sure what this datasource is doing, or the rules that are necessary for the formatting of things like the template, body.
Thanks again.
    On Friday, September 18, 2020, 01:49:58 PM CDT, Diana Lau <notifications@github.com> wrote:  
 
 


@tripled1313, thanks for bringing this up. I agree that the docs for calling out other APIs is a bit messy, especially when we're trying to combine the instructions to call SOAP and REST services together. Do you have some publicly available REST service that we can use as an example?

Based on your comments, I have the following proposal:
   
   - split the instructions to call SOAP and REST services as separate page
   - in each instruction, include examples that involves other types in parameters.
   - For REST, include example to call POST (there's only GET in the example)

What do you think?

**Comment by dhmlau** [comment]
Thanks. There are some more information from the REST connector page itself: https://loopback.io/doc/en/lb4/REST-connector.html. Will update the acceptance criteria on this issue.

**Comment by dhmlau** [comment]
In case you're looking for example, please take a look at https://github.com/dhmlau/loopback4-github-analytics2/blob/master/src/datasources/githubds.datasource.json. Hope it helps.

**Comment by mrmodise** [comment]
> * in each instruction, include examples that involves other types in parameters.
> * For REST, include example to call POST (there's only GET in the example)

@dhmlau on these points I was thinking of keeping it simple to avoid confusion on this. Maybe then add an additional section that routes out to where these are covered in other sections of `How-to guides`
