### ISSUE TITLE
docs: Extending LoopBack 4

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#637]
As the top level of the LB4 documentation, there should be a section for `Extending LoopBack4`.  
`Creating component` should be part of the extension developer guide.

/cc @raymondfeng @virkt25

**Comment by virkt25** [comment]
`Extending` implies it's meant for Application Developers (more so imo) & Extension Developers. Also `LoopBack 4` seems redundant since they would be that version of the docs. 

I would suggest the following format: 
```
Using Extensions // Alternative: Extending LoopBack / Leveraging Extensions
- Components
- Mixins
- Providers / Sequence Actions
// etc.

Creating Extensions // Alternative: Writing Extensions
- Components
- Providers / Sequence Actions
- Mixins
- Decorators
```

**Comment by kjdelisle** [comment]
It looks like you've already done this item, can you confirm?

**Comment by dhmlau** [comment]
Talked to @raymondfeng , it's done. http://loopback.io/doc/en/lb4/Extending-LoopBack-4.html
Closing it.
