### ISSUE TITLE
Generated README.MD for LB4 Application doesn't look right

### ISSUE THREAD

**Issue by emonddr** [strongloop/loopback-next#6379]
## Steps to reproduce
Create an LB4 application

## Current Behavior
Look at the REAMDE.MD file.

It doesn't look right.

![image](https://user-images.githubusercontent.com/6864736/93511731-42d0ac00-f8f1-11ea-89cc-707302fa1e0c.png)

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by emonddr** [comment]
@raymondfeng  mentioned

In https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/project/templates/README.md.ejs ,
we need to test if the projectType is application or extension.

We have similar conditional code gen - https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/project/templates/package.json.ejs#L87

**Comment by emonddr** [comment]
We would need to know what content we want to generated when
- lb4 app is a regular application
- lb4 app is an extension

**Comment by raymondfeng** [comment]
I suggest that we have separate copies of `README.md.ejs` for applications and extensions.
