### ISSUE TITLE
docs: Thinking in Loopback should fall under Best Practices section

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#638]
From our discussion yesterday, [Thinking in LoopBack](http://loopback.io/doc/en/lb4/Thinking-in-LoopBack.html) is target for existing LB3 users.
 
- should not be under `Getting Started` section
- might fall into Advanced / Best Practices section

## Acceptance Criteria
- Migrate "Thinking in Loopback" from the Getting Started section to ...?

**Comment by kjdelisle** [comment]
@crandmck What's your opinion on where this should live?

**Comment by crandmck** [comment]
I think it should be retitled "Best practices for developing APIs with LoopBack" (or something along those lines).

It could become a top-level article.  I don't think we have other "best practices" info, do we?  If so, we could put it under this one.

This article is very long.  I suggest breaking it down into smaller pieces to make it easier to digest.  Perhaps:
1. Defining and validating your API
1. Testing
1. Implementing features
1. [Preparing your API for consumption](http://loopback.io/doc/en/lb4/Thinking-in-LoopBack.html#preparing-your-api-for-consumption) - This section needs to be written!  I think it could reasonably have a "plug" for API Connect as a good way to provide an API for consumption.

**Comment by shimks** [comment]
@bajtos Can we get you opinion this?

**Comment by kjdelisle** [comment]
@shimks I think it would be good to implement Rand's suggestion as a Pull Request and then let @bajtos see if he likes the idea or not. In any event, we definitely _don't_ want it under "Getting Started", so any first step towards the end result is a good one. :)
