### ISSUE TITLE
Model: hidden property shortcut

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#6385]
Currently, to hide properties of a model we have to do this:

```ts
@model({
  settings: {
    hiddenProperties: ['password']
  }
})
class MyUserModel extends Entity {
  ...
   @property({type: 'string'})
  password: string;
  ...
}
```

Let's provide a shortcut so we can do this instead:

```ts
class MyUserModel extends Entity {
  ...
   @property({type: 'string', hidden: true})
  password: string;
  ...
}
```

## Acceptance Criteria

- [ ] Add new property `hidden` in model property definitions, which should do what `hiddenProperties` does for the listed properties.
- [ ] Update relevant documentation

Along with https://github.com/strongloop/loopback-next/issues/2766, users will now have a more intuitive model definition experience.

---

## 🎆 Hacktoberfest  2020

Greetings :wave: to all Hacktoberfest 2020 participants!

Here are few tips 👀 to make your start easier, see also #6456:

- Before you start working on this issue, please leave a comment to let others know.
- If you are new to GitHub pull requests, then you can learn about the process in [Submitting a pull request to LoopBack 4](https://loopback.io/doc/en/lb4/submitting_a_pr.html).
-  If this is your first contribution to LoopBack, then please take a look at our [Developer guide](https://loopback.io/doc/en/lb4/code-contrib-lb4.html).
- Feel free to ask for help in `#loopback-contributors` channel, you can join our Slack workspace [here](https://join.slack.com/t/loopbackio/shared_invite/zt-8lbow73r-SKAKz61Vdao~_rGf91pcsw).

**Comment by bajtos** [comment]
The benefit of the current model-level design is that child models can hide properties defined in the parent model. I think it is a useful feature we should preserve.

Adding support for property-level `hidden` metadata as an alternate syntax to model-level `hiddenProperties` looks reasonable to me 👍🏻

**Comment by mdbetancourt** [comment]
i would like to take this one

**Comment by hacksparrow** [comment]
@mdbetancourt great!
