### ISSUE TITLE
testlab: expect(spy).to.be.called()

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#641]
Code to reproduce the problem:

```ts
const spy = sinon.spy(console, 'log');
console.log('hello');
expect(spy).to.be.called();
```

Error message:
```
TypeError: testlab_1.expect(...).to.be.called() is not a function
```

I did a quick search, we are using `should/as-function` for `expect`, which has different `Assertion` class/constructor than regular `should`. Now `should-sinon` modifies only the `Assertion` prototype from `should`, not from `should/as-function`, therefore it does not add sinon-related assertions to our `expect.

See https://github.com/shouldjs/sinon/blob/3d1841d244316a02671b54a33660127def0dd8b6/should-sinon.js#L5

Workaround:

```ts
sinon.assert.called(spy);
```

**Comment by shimks** [comment]
Currently making changes to http://loopback.io/doc/en/lb4/Testing-your-application.html so that the workaround is used in the code example. Leaving the comment as a reminder to revert this when or if the fix is made.
