### ISSUE TITLE
Locked and Unlocked icons should be reversed

### ISSUE THREAD

**Issue by Mohammedalasaad** [strongloop/loopback-next#6430]
Hi
This is just UI issue. I think the Locked and Unlocked should be reversed.

When you are not **authorized its should show locked icon** and when you **authorized should show unlocked icon**.
 
<img width="250" alt="Screenshot 2020-09-23 at 21 32 14" src="https://user-images.githubusercontent.com/48674512/94060445-45953a80-fde4-11ea-91f5-4d2a96477c31.png">

**Comment by raymondfeng** [comment]
The icon is from `swagger-ui`. I think the idea is to click this button to `unlock`

**Comment by Mohammedalasaad** [comment]
As you are not authorized so it should be locked mean not accessible.. yes if u click to unlock.. then first state should be locked :) 
is this swagger related issue ?
