### ISSUE TITLE
Migrate LB3 datasources to LB4 format

### ISSUE THREAD

**Issue by condratbogdan** [strongloop/loopback-next#6434]
We have entries like this in our Core service datasources.json file, that represent endpoints in another service named Accounts:
```
"accounts": {
        "name": "accounts",
        "connector": "swagger",
        "spec": "http://192.168.100.103:3001/explorer/swagger.json"
    }
```
We could then use the endpoints from the service inside our loopback app like this, Accounts.Accounts_findById({...}).
How can i get the same effect using LB4 components? (both creation of datasource and method invokation)

**Comment by jannyHou** [comment]
Hi @condratbogdan when you say "How can i get the same effect using LB4 components", do you mean turn the app with accounts services into a LB4 component? Or you want to invoke the account service in a LB4 component?

**Comment by condratbogdan** [comment]
> Hi @condratbogdan when you say "How can i get the same effect using LB4 components", do you mean turn the app with accounts services into a LB4 component? Or you want to invoke the account service in a LB4 component?

I want to invoke the account service in a LB4 component.
