### ISSUE TITLE
A better tool for automated API smoke tests

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#644]
Right now, we are recommending [Dredd](https://dredd.readthedocs.io/en/latest/) for automated testing of API conformance with the spec. This tool has several shortcomings:

 - A binary dependency. Setting up build env is tricky (especially in enterprise environments with a constrained access to the interned), it requires us to spend more time on support. The time needed to `npm install` all dependencies is too long too.

 - The tool does not integrate with our Mocha test runner. We have to configure Dredd to log test failures to stdout/stderr, which makes test report inconsistent.

 - When a test fails, the error message is too verbose and makes it difficult to quickly spot what went wrong.

I am proposing to find a tool that will give our users a better UX.

**Comment by kjdelisle** [comment]
We should determine if:
- is there a better solution than Dredd
- if not, drop this section from "Thinking in LoopBack" and from our examples (if any)
- write a blog post about it

**Comment by thinusn** [comment]
For  API / swagger conformance tests that work in mocha one could look at https://github.com/CacheControl/hippie-swagger

**Comment by bajtos** [comment]
Removing from MVP, top-down approach is out of scope of MVP. However, see https://github.com/strongloop/loopback-next/issues/796

**Comment by bajtos** [comment]
Design-first (top-down) approach is out of scope of 4.0 GA, removing this story from the release.
