### ISSUE TITLE
Spike: example repositories

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#645]
Come up with a proposal of what example repositories we want to have, what is required for Beta and what can be deferred until Core-GA. 

This is a follow-up for https://github.com/strongloop/loopback-next/issues/614

 - [ ] Make sure there is no reference of the old repo names
 - [ ] Update the `Tutorial&Examples` doc: http://loopback.io/doc/en/lb4/Examples-and-tutorials.html

**Comment by jannyHou** [comment]
Moved the plan table from previous issue. Use it as a reference, the people who works on it decides the implementation and team can give feedback under each PR.


| repo name                               | topic/tutorial | description                                                                                  | plan                                                                                                                                                                                           |
|-----------------------------------------|----------------|----------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| loopback4-example-hello-world           | tutorial       | uses sequence/action to print out hello world!. No controllers or repositories are involved. | easy to build, we can **create a new repo**                                                                                                                                                    |
| loopback4-example-hello-world-controller | tutorial       | uses a controller to create a hello world response                                           | easy to build, we can **create a new repo**                                                                                                                                                    |
| loopback4-example-getting-started       | tutorial       | builds an simple app with LoopBack4 key concepts                                             | **rename existing `loopback-next-hello-world`**. I am not very familiar with it, we can discuss what concepts are missing in it and how to write the document to guide users with this example |
| loopback4-example-todo-legacy           | topic          | builds a todo app with legacy juggler                                                        | **create a new repo**, extract the app in folder `/services/todo-legacy` from `loopback-next-example`                                                                                          |
| loopback4-example-bank                  | tutorial       | builds a bank app demo multiple repositories, relations, authentication feature.             | **rename `loopback-next-example`**, extract other folders from `loopback-next-example`, refactor them according to the latest lbn                                                              |
| loopback4-example-log-extension         | topic          | builds an app demo a log extension                                                           | **rename `lb4-log-extension-example`** would be good enough                                                                                                                                    |

**Comment by kjdelisle** [comment]
Updating this table to reflect some changes, largely around simplification of the number of items:

| repo name                               | topic/tutorial | description                                                                                  | plan                                                                                                                                                                                           |
|-----------------------------------------|----------------|----------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| loopback4-example-hello-world           | tutorial       | uses sequence/action to print out hello world!. No controllers or repositories are involved. | **https://github.com/strongloop/loopback4-example-hello-world**, needs to use controller (sequence is not representative of a typical app)                                                                                                                                              |
| loopback4-example-getting-started       | tutorial       | builds an simple app with LoopBack4 key concepts                                             | **new repository** at https://github.com/strongloop/loopback4-example-getting-started, contains a todo app using legacy juggler |
| loopback4-example-todo-legacy           | topic          | builds a todo app with legacy juggler                                                        | no longer necessary, rolled into loopback4-getting-started |
| loopback4-example-bank                  | tutorial       | builds a bank app demo multiple repositories, relations, authentication feature.             | **rename `loopback-next-example`**, remove `todo-legacy`, update with lerna, add documentation |
| loopback4-example-log-extension         | topic          | builds an app demo a log extension                                                           | **https://github.com/strongloop/loopback4-example-log-extension** |                                                                                                                                 |
