### ISSUE TITLE
Write a better advice on testing custom sequences

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#648]
https://github.com/strongloop/loopback.io/pull/479 advices LoopBack users to write acceptance tests for their custom sequence implementation. As I wrote in https://github.com/strongloop/loopback.io/pull/479#discussion_r144544761, I think that may not be the best way, especially considering our own advice in [Testing your application](http://loopback.io/doc/en/lb4/Testing-your-application.html) ~~[Thinking in LoopBack](https://github.com/strongloop/loopback.io/blob/0be8c43d389c62a0122eeb29cd04f338b2387aa1/pages/en/lb4/Thinking-in-LoopBack.md#how-to-build-a-great-test-suite)~~:

> How to create a great test suite? By thinking smaller and favoring fast, focused unit-tests over slow application-wide end-to-end tests.

On one hand, writing several end-to-end tests to verify how auth is applied to each endpoint brings quite a lot of confidence for the security of our app. On the other hand, these tests are repetitive to write and take a long time to execute.

I am proposing to rewrite sequence-related sections in "Testing your application" with the following advices:

 - A small number of integration tests to make sure all sequence customizations are applied for HTTP requests, these tests can invoke a dummy test controller method instead of real API endpoints - we are interested in the sequence, not any specific controller method.

 - Unit test for each controller method to ensure the method is correctly decorated with the metadata used by additional sequence actions used in our custom sequence.

For example, let's say we are using `@loopback/authentication` and its `@authenticate` decorator and `authenticate()` sequence action. To test such app, we would write:

 - four integration tests: two tests for a controller method decorated with `@authenticate` (an anonymous request, an authenticated request), two tests for a controller method not decorated with `@authenticate` (again, an anonymous request, an authenticated request)

 - for each controller method, one unit test verifying that the method is (or is not) decorated with `@authenticate`
  

**Tasks**

 - [ ] Pick one of the (more complex?) example repositories, update the tests there to follow the new testing practice we are going to recommend in our docs. Check with the team to get approval from other developers for this new way.

 - [ ] Update the documentation to describe the new practice.

**Comment by dhmlau** [comment]
Remove from `LoopBack 4 MVP` release as this is marked as non-MVP.
