### ISSUE TITLE
Property injection is undefined in Class

### ISSUE THREAD

**Issue by pavelgronsky** [strongloop/loopback-next#6503]
Hello. 
I'm try to add my service or repository as Property injection to my Class in Loopback 4 project.

If I try to add Dependency injection in constructor (Constructor injection), everything is worked and I get all function from inject object, but when I try to add injection as property in Type Script Class i take undefined. 

This is example:
```TypeScript

export class ProductsModelSchemaUpdate {
//Example inject servcie
  @inject(MyServiceBinding.MY_SERVICE)
  public myService: MyService;

//example inject repo
  @inject('repositories.Orders')
   private ordersRepo: OrdersRepository;

  constructor(  ) {  }

  public async startModelSchemaUpdate() {
    this._log('update model schema');

    await this.removeField()
  }

  async removeField(){
     let test = this.myService.functionFromInterface() // in this moment I take undefined 
     //THe same situation with my inject repo. 
      let t = await new Context().get(MyServiceBinding .MY_SERVICE); // doesn't work too
  }
}
```
When I added inject in constructor, everything is work.

- Service is bind as provider in application.ts

```TypeScript
this.bind(MyServiceBinding.MY_SERVICE).toProvider(MyServiceProvider)
```
- MyService it's simple interface with provider.
- This is key for my service bind:

```TypeScript
export namespace MyServiceBinding {
  export const MY_SERVICE = BindingKey.create<MyService>(
    'services.myservice',
  );
}
```

Question:
1. How I can add inject repo as property, without constructor in my TS Class?
2. How I can add inject my own service as property, without constructor in my TS Class?

PS. Perhaps this is a problem in the correct spelling of the class, but I will be grateful for your help.

**Comment by mdbetancourt** [comment]
is not possible afaik, i'm not an expert but loopback pass those value through constructor (after read the metadata of injected value) and there you dont receive param in constructor a workaround could be store the value in a lifecycle time
```ts
export class ProductsModelSchemaUpdate implements LifeCycleObserver {
//Example inject servcie
  @inject(MyServiceBinding.MY_SERVICE)
  public myService: MyService;

  constructor(
    @inject(CoreBindings.APPLICATION_INSTANCE) // you need to inject at least the app
    public app: Application
  ) {}
  async start() {
    this.myService = await this.app.get<MyService>(MyServiceBinding.MY_SERVICE)
  }
  public async startModelSchemaUpdate() {
    this._log('update model schema');

    await this.removeField()
  }

  async removeField(){
     let test = this.myService.functionFromInterface()
     // here you are creating a new (empty) context so you bindings aren't here
     let t = await new Context().get(MyServiceBinding .MY_SERVICE);
     // in order to work you need do (using app as parent context)
     let t = await new Context(this.app).get(MyServiceBinding .MY_SERVICE); // without much sense is better just use this.app.get
  }
}
```
after all of this i dont understand why don't you want to use the constructor (is you want to use static methods) you could use static properties and a SINGLETON instance, you aren't to gain anything with that

**Comment by raymondfeng** [comment]
@pavelgronsky 

Property injection should work. It happens after Constructor injection. You should be able to reference `this.myService`. 

The following is NOT working for sure as an empty `Context` does not contain `MyServiceBinding.MY_SERVICE`.

```ts
let t = await new Context().get(MyServiceBinding.MY_SERVICE); // doesn't work too
```

How does your service provider looks like?

**Comment by pavelgronsky** [comment]
@raymondfeng 

My service provider look like:

```typescript
export interface Skowronek {
  getNewOrdersFullList(dateAdd: string): Promise<IOrder[]>;
  getOrderById(orderId: number): Promise<IOrder[]>;
  getAddressDeliveryById(addressId: string): Promise<IAddressDelivery[]>;
  getProductById(productId: string): Promise<IProduct[]>;
  getAllProducts(): Promise<IProduct[]>;
  getTaxRuleGroupById(taxRuleGroupId: number): Promise<ITaxInfo[]>;
  getTaxRuleGroup(): Promise<ITaxInfo[]>;
  getAllDeliverComments():  Promise<IDeliveryMessage[]>;
  getManufacturers(): Promise<IManufacture[]>;
  getSuppliers(): Promise<ISupplier[]>;
}

export class SkowronekProvider implements Provider<Skowronek> {
  constructor(
    @inject('datasources.skowronekRest')
    protected dataSource: SkowronekRestDataSource = new SkowronekRestDataSource(),
  ) {}

  value(): Promise<Skowronek> {
    return getService(this.dataSource);
  }
}
```

**Comment by raymondfeng** [comment]
1. Can you check if `SkowronekProvider.value()` is invoked?
2. What's the return value from `value()`?
3. Please also check for circular imports that can lead to some undefined variables, such as `MyServiceBinding.MY_SERVICE`. See https://techsparx.com/nodejs/howto/circular-dependencies.html

**Comment by pavelgronsky** [comment]
@raymondfeng Hi
Please, look on some change in my code:

This is my BindingKey:

``` typescript
export namespace SkowronekServiceBinding {
  export const SKOWRONEK_SERVICE = BindingKey.create<SkowronekService>(
    'services.SkowronekService',
  );
  //export const SKOWRONEK_SERVICE = 'services.SkowronekService';
}
```
The binding in my application.ts is same:

` this.bind(SkowronekServiceBinding.SKOWRONEK_SERVICE).toProvider(SkowronekProvider)   `

This is my service provider:

``` typescript
export interface SkowronekService {
  getNewOrdersFullList(dateAdd: string): Promise<IOrder[]>;
}

export class SkowronekProvider implements Provider<SkowronekService> {
  constructor( 
//beackpoint <-----
    @inject('datasources.skowronekRest')
    protected dataSource: SkowronekRestDataSource,
  ) {}

  value(): Promise<SkowronekService> {
//beackpoint <-----
    return getService(this.dataSource);
  }
}
```

My datasource:

``` typescript
@lifeCycleObserver('datasource')
export class SkowronekRestDataSource extends juggler.DataSource
  implements LifeCycleObserver {
  static dataSourceName = 'skowronekRest';
  static readonly defaultConfig = config;

  constructor(
    @inject('datasources.config.skowronekRest', {optional: true})
    dsConfig: object = config,
  ) {
    super(dsConfig);
  }
}
```

Look what's happening now:
When I used my service provider inject as parameter in constructor, everything works fine. Value return what I needed, breakpoint work in constructor and inside value function, but when I'm tried to use my service provider inject as property in my  class, breakpoints doesn't work. 

I do not fully understand why in different examples add binding in different ways.
In **loopback4-example-shopping** in user.controller.acceptance.ts how we can add service like this:
```
  const recommender = await app.get<RecommenderService>(
        'services.RecommenderGrpcService',
      );
```
And application.ts doesn't have bind, and doesn't have BindingKey for this service. 

**Only tests:**
With @mrmodise helps. I try to go that route for test, but it' work only I'm changed binding from:
this.bind(SkowronekServiceBinding.SKOWRONEK_SERVICE).toProvider(SkowronekProvider)   
to 
this.bind(SkowronekServiceBinding.SKOWRONEK_SERVICE).toClass(SkowronekRestDataSource) 

 I need to use all three possible injection in different places in my project.
Can you tell me step by step how I can bind my provider service for used all three possible injection?
Where did I go wrong?

**Comment by raymondfeng** [comment]
1. If your service is placed in `src/services` directory, it will be automatically discovered and bound to the application be `app.boot()`.

2. `.toClass` and `toProvider` are for different classes. `toClass` uses the class constructor to create a new instance of the class as the resolved value. `toProvider` uses the class constructor to create a new instance, then call `value()` to return the resolved value.

3. Are you saying `test` in your screenshot is `undefined`? Please note it's a `Promise` which can be resolved later than the breakpoint.

4. Please note that project injection happens after constructor injection. You cannot set a breakpoint on the property declaration.

**Comment by raymondfeng** [comment]
@pavelgronsky If you have a simple application to reproduce the problem, it will be easier for us to help troubleshoot.

**Comment by mrmodise** [comment]
@pavelgronsky I think it's worth closing this issue since we were able to resolve it. The issue was how the service binding/namespace was defined. We change the below from:

`export namespace SkowronekServiceBinding {
  export const SKOWRONEK_SERVICE = 'services.SkowronekService';
}`

then in `application.ts` bound the Repository to Repository class. Once this was done all that was left was to use `SkowronekServiceBinding.SKOWRONEK_SERVICE` to access the service:

`this.skowronekService = await this.app.get<SkowronekService>(SkowronekServiceBinding.SKOWRONEK_SERVICE)`

**Comment by pavelgronsky** [comment]
@raymondfeng Hi.
Look my repo example
https://github.com/pavelgronsky/loopback-service-provider

**Comment by mrmodise** [comment]
> @raymondfeng Hi.
> Look my repo example
> https://github.com/pavelgronsky/loopback-service-provider

Change this line:

```typescript
 setUpBindings(): void {
    this.bind(SkowronekServiceBinding.SKOWRONEK_SERVICE).toProvider(SkowronekProvider)   
  }
```

to

```typescript
 setUpBindings(): void {
    this.bind('datasources.config.skowronekRest').toClass(SkowronekRestDataSource)   
  }
```

Add a `keys.ts` and include the service namespace:

```typescript
export namespace SkowronekServiceBinding {
  export const SKOWRONEK_SERVICE = 'services.SkowronekService';
}
```


to retrieve service from context you can do:

```typescript
const skowronekService = await this.app.get<SkowronekService>(SkowronekServiceBinding.SKOWRONEK_SERVICE); 
```
or 

```typescript
@inject(SkowronekServiceBinding.SKOWRONEK_SERVICE) protected  skowronekService: SkowronekService
```

**Comment by raymondfeng** [comment]
There are quite a few things in the code that went wrong.

1. Using constructor directly (`const productsModelSchemaUpdate = new ProductsModelSchemaUpdate()` - https://github.com/pavelgronsky/loopback-service-provider/blob/master/src/application.ts#L63) does not trigger dependency injection. 

You need to fix it as follows:

**product.ts**
```ts
import {inject, CoreBindings} from '@loopback/core';
import { SkowronekService } from '../services';
import {SkowronekServiceBinding} from '../authentication/keys';
import {LoopbackServiceProviderApplication} from "../application"

export class ProductsModelSchemaUpdate {
   @inject(CoreBindings.APPLICATION_INSTANCE) 
   public app: LoopbackServiceProviderApplication

    @inject(SkowronekServiceBinding.SKOWRONEK_SERVICE)
    public skowronekServiceProp: SkowronekService

    constructor(
      ) {}
      
      public async startService() {

        await this.runService()
      }

      async runService(){
        let skowronekServiceProp = await this.skowronekServiceProp.getTaxRuleGroup()
      }
}
```

**application.ts**
```ts
async migrateSchema(options?: SchemaMigrationOptions): Promise<void> {
    await super.migrateSchema(options);
    
this.bind('migration.ProductsModelSchemaUpdate').toClass(ProductsModelSchemaUpdate);
    const productsModelSchemaUpdate = await this.get<ProductsModelSchemaUpdate>(migration.ProductsModelSchemaUpdate);
    await productsModelSchemaUpdate.startService();
  }
```

2. We bind datasources/services from src/datasources and src/services directories automatically using `app.boot()`. As a result, there is no need to call https://github.com/pavelgronsky/loopback-service-provider/blob/master/src/application.ts#L54

**Comment by mrmodise** [comment]
Thanks @raymondfeng created a pull request for @pavelgronsky at: https://github.com/pavelgronsky/loopback-service-provider/pull/1/

**Comment by mrmodise** [comment]
@pavelgronsky if happy please close the issue 😊

**Comment by pavelgronsky** [comment]
@raymondfeng  and @mrmodise  Thanks you very much, you are my heroes ;)
