### ISSUE TITLE
docs: Add missing gaps in Context concept page

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#651]
## Overview
On loopback.io under the Concepts section, `Context` needs to be modified to explain Bindings and add a server-level context section.

Link to Concepts Overview Page: http://loopback.io/doc/en/lb4/Concepts.html

## Acceptance Criteria
- [x] Include a detailed explanation of Bindings
  - [x] .to
  - [x] .toClass
  - [x] .toProvider
  - [x] .inScope
- [x] Add Server-level context section

**Comment by bajtos** [comment]
> Include a detailed explanation of Bindings

For Beta, just add a short sentence pointing people to our API docs: http://apidocs.strongloop.com/

**Comment by dhmlau** [comment]
@kjdelisle , since the PR has landed, is it good to close?

**Comment by dhmlau** [comment]
Confirmed with @kjdelisle, good to close.
