### ISSUE TITLE
Array query parameter does not work for a single value

### ISSUE THREAD

**Issue by nflaig** [strongloop/loopback-next#6514]
## Steps to reproduce

Add array query param to any endpoint

```ts
 @param.array("stringArray", "query", { type: "string" }) stringArray?: string[]
```

## Current Behavior

Passing only a single query parameter throws an error with code `INVALID_PARAMETER_VALUE` and and message `should be array` in details

```ts
?stringArray="value1"
```

## Expected Behavior

should not throw an error

## Additional information

Passing multiple query parameters works

```ts
?stringArray="value1"&stringArray="value2"
```

and using a different syntax also works

```ts
?stringArray[]="value1"
```

Currently, the api explorer passes the query parameter as described in current behavior `?stringArray="value1"`.

**Comment by mrmodise** [comment]
@nflaig this looks interesting. I would like to give it a try.

**Comment by raymondfeng** [comment]
Express query parser parses `?stringArray=value1` to `{stringArray: 'value1'}` if `stringArray` only shows once. We should be able to normalize `'value1'` to `['value1']` before passing to AJV.

**Comment by mrmodise** [comment]
> Express query parser parses `?stringArray=value1` to `{stringArray: 'value1'}` if `stringArray` only shows once. We should be able to normalize `'value1'` to `['value1']` before passing to AJV.

I found this to be helpful and pointed me in the right direction. Thanks @raymondfeng

**Comment by mrmodise** [comment]
@raymondfeng @nflaig I have created a draft PR with outstanding unit tests. Please check and let me know if am on track. Thanks
