### ISSUE TITLE
lb4 datasource and service with OpeAPI definition

### ISSUE THREAD

**Issue by emiliobristech** [strongloop/loopback-next#6520]
## Steps to reproduce

1. Generate datasource (select OpenAPI as DS) based on OpenApi/Swagger file
1.1 Datasource name: petStoreDS
1.2 Select the connector for ds: OpenAPI 
1.3 HTTP URL/path to Swagger spec file (file name extension .yaml/.yml or .json): https://petstore.swagger.io/v2/swagger.json
1.4 Validate spec against Swagger spec 2.0?: No
1.5 Security config for making authenticated requests to API: None
1.6 Use positional parameters instead of named parameters?: No
2. Generate service based on datasource previously created
2.1 lb4 service 
2.2 Remote service proxy backed by a data source: petStoreDS
2.3 Service name: petStore

## Current Behavior

There is no operation mapped in datasource or service and there is no model generated.

## Expected Behavior
Generate stubs based on OpenApi definition.

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
Have you checked out https://loopback.io/doc/en/lb4/OpenAPI-generator.html? If you want to generate strongly-typed client code to interact with another REST API, try `lb4 openapi`.

**Comment by emiliobristech** [comment]
> Have you checked out https://loopback.io/doc/en/lb4/OpenAPI-generator.html? If you want to generate strongly-typed client code to interact with another REST API, try `lb4 openapi`.

Yes, I tried it but it seems to freeze.

Just called `lb4 openapi https://petstore.swagger.io/v2/swagger.json` and it seems to be stuck.

**Comment by emiliobristech** [comment]
As @raymondfeng said, just call lb4 openid --client and it will generate everything.

Thank you all!
