### ISSUE TITLE
@injectable({tags: {[ContextTags.KEY]: HealthBindings.COMPONENT}})

### ISSUE THREAD

**Issue by AshNanjangud** [strongloop/loopback-next#6524]
Trying to add health check to a loopback 4 application. 

Added to application.ts  

import {HealthComponent} from '@loopback/health';
this.component(HealthComponent);

@injectable({tags: {[ContextTags.KEY]: HealthBindings.COMPONENT}})
 ^
TypeError: core_1.injectable is not a function
node_modules\@loopback\health\src\health.component.ts:25:2)

Package.json

"@loopback/boot": "^2.4.1",
    "@loopback/core": "^2.11.0",
    "@loopback/health": "^0.5.2",
    "@loopback/openapi-v3": "^3.4.7",
    "@loopback/repository": "^2.11.0",
    "@loopback/rest": "6.1.0",
    "@loopback/rest-explorer": "^2.2.8",
    "@loopback/service-proxy": "^2.3.6",
    "@types/async": "^3.2.3",
    "@types/formidable": "^1.0.31",
    "@types/multer": "^1.4.3",
    "async": "^3.2.0",

**Comment by nflaig** [comment]
This error should only happen if you are using `@loopback/core` below `2.10.0`. Are you sure you ran `npm install`  after updating your `package.json`?

**Comment by raymondfeng** [comment]
@AshNanjangud Please run `lb4 update` to update dependencies.

**Comment by AshNanjangud** [comment]
Thanks It works

**Comment by AshNanjangud** [comment]
Works
