### ISSUE TITLE
docs: Getting Started & Installation page clean up

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#653]
# Description/Steps to reproduce
Summary of what was discussed with @kjdelisle:
The current [Getting Started ](http://loopback.io/doc/en/lb4/Getting-started.html) and the subpages need some rework.  

## Current
- Installation
- Getting started
   - Examples & Tutorials
   - ~~Thinking in LoopBack~~
   - FAQ

## Proposal
The proposed Getting Started page should contain: 
- installation: we don't need the current Installation page as it contains lots of redundant information
- getting started example: same as what we have in the getting started page
- examples: links & description of the example repos 

Thinking in LoopBack and FAQ should be separated, not placed under Getting Started. 

Note: Some might be covered/related in another github issue.  But want to use this issue to capture our discussion.

**Comment by bajtos** [comment]
Looks like most of the work has been already done, the change in the location of FAQ is tracked by #834
