### ISSUE TITLE
apidocs split into lb4 and older version of lb

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#654]
# Description/Steps to reproduce
Capturing the discussion with @kjdelisle:

The [current apidocs](http://apidocs.loopback.io/) contains apidocs for lb2/3 and lb4.  It might be confusing to both lb-current and lb-next users because lb4 docs are not applicable to lb2/3, and vice versa (in most cases). 

Proposal: Can we have a similar structure as the docs such that apidocs for lb3 and lb4 are separated? i.e. something like:
http://apidocs.loopback.io/lb3
http://apidocs.loopback.io/lb4

@crandmck

**Comment by crandmck** [comment]
That makes sense to me, but I don't know to do it.  It would require some engineering work, and Mahesh is the only one who knows this code atm.  It probably wouldn't be all that hard, but I'm not certain.  It might involve hacking `strong-docs`.

Currently, apidocs routes are set up like 
```
/{package}/v/{version}
```` 
e.g. 
```
http://apidocs.loopback.io/loopback/v/3.12.0/
```
And your proposal would be to change this to something like
```
/lb{major-vers}/{package}/v/{version}
```
e.g.
```
lb3/loopback/v/3.12.0/
```
or 
```
lb4/@loopback%2fcore/v/4.0.0-alpha.15/
```

**Comment by dhmlau** [comment]
@crandmck , i totally agree that it's not for beta, given we're so close to beta.  
Before we figure out who would be doing it, I'd like to get some thought from @raymondfeng @bajtos @ritch...

**Comment by bajtos** [comment]
I am proposing a simpler solution: split the mostly-static [home page](https://github.com/strongloop-internal/apidocs.strongloop.com/blob/82078ce15144082f8efbc1bc7769d750b07e95cc/views/home.ejs) into multiple sections, add a sidebar listing all sections, create anchors allowing user to create URLs pointing to the right part of the page. We can modify the frontend to show only content from the selected section and hide other sections, to make the user experience closer to browsing between different web pages.

I don't think we need @mpatsute to do these changes, I think anybody with decent front-end skills should be able to implement the changes I have proposed above. AFAICT, our apidocs site is using jQuery, I think we can simply leverage jQuery's [vertical tabs](https://jqueryui.com/tabs/#vertical)?

> Currently, apidocs routes are set up like
> `/{package}/v/{version}`
> And your proposal would be to change this to something like
> `/lb{major-vers}/{package}/v/{version}`

TBH, that does not make sense to me. Certain packages like connectors are going to be shared by both LB2/3 and LB4, at least in Beta. I don't see much value in having the same content exposed on two different URLs, e.g. `lb3/loopback-connector-mysql/1.2.3` and `lb4/loopback-connector-mysql/1.2.3`.

**Comment by crandmck** [comment]
> Certain packages like connectors are going to be shared by both LB2/3 and LB4, at least in Beta. I don't see much value in having the same content exposed on two different URLs

Good point. I didn't consider that.

> I am proposing a simpler solution: split the mostly-static home page into multiple sections...

That seems simpler and better overall.  Ideally, I'd like to be able to link directly to a home page/tab that shows only the LB4 packages or only LB3 packages so users of either wouldn't be confused by the presence of links for irrelevant packages.

> AFAICT, our apidocs site is using jQuery, I think we can simply leverage jQuery's vertical tabs?

Yes...we are using a very old (4 years+) version of JQuery, which we would have to update--and which we should do anyway:

https://github.com/strongloop-internal/apidocs.strongloop.com/tree/master/public/js/vendor

**Comment by bajtos** [comment]
> Ideally, I'd like to be able to link directly to a home page/tab that shows only the LB4 packages or only LB3 packages so users of either wouldn't be confused by the presence of links for irrelevant packages.

Exactly! 👍 ✖️ 💯

**Comment by bajtos** [comment]
Let me make this Beta+p2 item, I think good API docs are pretty important.

**Comment by jannyHou** [comment]
Close since https://github.com/strongloop-internal/apidocs.strongloop.com/pull/80 merged.
