### ISSUE TITLE
docs: Route creation example doesn't work

### ISSUE THREAD

**Issue by VMois** [strongloop/loopback-next#659]
# Description/Steps to reproduce
Example from http://loopback.io/doc/en/lb4/Routes.html#creating-rest-routes doesn't compile for me. I don't know if it is my fault or example is outdated.

# Link to reproduction sandbox
I use package.json and tsconfig from Getting Started page 
My code:
```javascript
import {Application} from '@loopback/core';
import {RestServer, Route} from '@loopback/rest';

const app = new Application();
const spec = {
  parameters: [{name: 'name', in: 'query', type: 'string'}],
  responses: {
    '200': {
      description: 'greeting text',
      schema: {type: 'string'},
    }
  }
};

// greet is a basic operation
function greet(name) {
  return `hello ${name}`;
}

(async function start() {
  const server = await app.getServer(RestServer);
  const route = new Route('get', '/', spec, greet);
  server.route(route);
  await app.start();
})();
```
After running npm start (tsc && node index.js) I got this error
```
index.ts(22,39): error TS2345: Argument of type '{ parameters: { name: string; in: string; type: string; }[]; responses: { '200': { description: s...' is not assignable to parameter of type 'OperationObject'.
  Types of property 'parameters' are incompatible.
    Type '{ name: string; in: string; type: string; }[]' is not assignable to type '(ParameterObject | ReferenceObject)[]'.
      Type '{ name: string; in: string; type: string; }' is not assignable to type 'ParameterObject | ReferenceObject'.
        Type '{ name: string; in: string; type: string; }' is not assignable to type 'ReferenceObject'.
          Property '$ref' is missing in type '{ name: string; in: string; type: string; }'.

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "start"
npm ERR! node v8.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! getting-started@1.0.0 start: `tsc && node index.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the getting-started@1.0.0 start script 'tsc && node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the getting-started package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs getting-started
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls getting-started
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

# Expected result
Greeting text (e.g "hello loopback")when go to the root /?name=loopback

# Additional information

**Comment by kjdelisle** [comment]
@VMois Sorry it took so long to get to this, there's been a lot going on over here!

I'm currently running through this right now to make sure that it works, though I'd have to check with @bajtos to see if we still allow Route definition in this way.

**Comment by kjdelisle** [comment]
Are you running this as a TypeScript application, or as a JavaScript (ES2017) application?

**Comment by kjdelisle** [comment]
You're right, the current example is flawed and will throw more than a few errors, even as you work through it:
- The type information should be provided for things like the OpenAPI `spec` variable, which is an `OperationObject` (this makes it easier to determine if it's actually compliant should you edit it)
- There's no type information on the `greet` function (this actually shows up as an error in my environment)
- We didn't include any import statements
- The application instance requires the `RestComponent` to be loaded in so that you can make use of the RestServer implementation (it sets up a lot of the default providers for RestServer)

**Comment by kjdelisle** [comment]
I've updated the example, and added a third example for how to do Routing setup with the routing decorators as well! @VMois Try the new snippets and let me know how it goes.

**Comment by kjdelisle** [comment]
I'll take the thumbs-up as approval and close this. Lemme know if I was wrong!
