### ISSUE TITLE
Static files not work with class that extends of RestApplication

### ISSUE THREAD

**Issue by pookdeveloper** [strongloop/loopback-next#6592]
## Steps to reproduce

Create a custom class that extends of RestApplication

## Current Behavior

Can't access to localhost:3000/index.html

## Expected Behavior

Can access to localhost:3000/index.html

## Link to reproduction sandbox

https://github.com/pookdeveloper/loopback-next/tree/error-static-files-custom-restApplication

## Additional information
This not work:
`export class PruebaApplication extends BootMixin(ServiceMixin(RepositoryMixin(MyCustomRestApplication))) {
`
This work:
export class PruebaApplication extends BootMixin(ServiceMixin(RepositoryMixin(RestApplication))) `{`

**Comment by raymondfeng** [comment]
@pookdeveloper A few things:

1. I would recommend to have your test application to be placed under `/sandbox`.
2. Please make sure your `loopback-next` folk is up to date with https://github.com/strongloop/loopback-next.

I cloned your repo and rebase it against latest master:

```sh
git remote add upstream git@github.com:strongloop/loopback-next.git
git rebase upstream/master
```

After that, `node .` (examples/todo) starts and `http://localhost:3000` works for me.

**Comment by raymondfeng** [comment]
In your case:

```
This branch is 2 commits ahead, 2944 commits behind strongloop:master.
```

**Comment by raymondfeng** [comment]
http://localhost:3000/api/ is now serving `index.html` as you configure the `basePath` to `/api`. It also impacts the static files.

**Comment by pookdeveloper** [comment]
Ahh ok thanks @raymondfeng i think for static file there aren't any way to ignore base path ? Thanks!
