### ISSUE TITLE
Move shared types and other primitives to a standalone module

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#660]
## Description

Chatted with @raymondfeng 

context see https://github.com/strongloop/loopback-next/issues/580#issuecomment-337384246

Some files under `/repository` like `mixin.ts`,  `common-types.ts` could be organized to `/lang` to export language specific library functions.

From Raymond

> I think some of them should be refactored into a common module such as `@loopback/common`
or `@loopback/lang`
There are a few things related to language
such as Constructor, Mixin etc
We’ll have `@loopback/model` and/or `@loopback/types` etc

 
`loopback/lang` sounds more straightforward to me.

**Comment by bajtos** [comment]
IMO, `MixinBuilder` in particular should not be something to widely recommend to our users, we should be telling them to use mixins directly via ES2015/TS syntax. See https://github.com/strongloop/loopback.io/pull/491#discussion_r145687471 and https://github.com/strongloop/loopback.io/pull/491#discussion_r145688539 for more context.

**Comment by bajtos** [comment]
As for package name, I vote for `@loopback/core-types`.

**Comment by raymondfeng** [comment]
I vote for `@loopback/common-types` or `@loopback/common`
