### ISSUE TITLE
loopback turn http into https

### ISSUE THREAD

**Issue by fgvicente** [strongloop/loopback-next#6602]
>**Maintainers' note**
> This question has been posted elsewhere:
> - https://loopbackio.slack.com/archives/C01177XQN8N/p1603105519398700
> - https://loopbackio.slack.com/archives/C01177XQN8N/p1603107348399500

good morning teacher. I have a query for a rare problem. I have a loopback backend and a react application in /public.

when I access my localhost it works fine but through the ip the http calls transform them into https and it stops working ... it happens with all the scripts and assets. 

transform them all into https calls

localhost work OK
![image](https://user-images.githubusercontent.com/3626864/96447889-fa0a5c80-11e8-11eb-9f27-1e87f5a0af9b.png)

from ip turn http int https
![image](https://user-images.githubusercontent.com/3626864/96448399-b3693200-11e9-11eb-9fc2-57a60c2d710f.png)

**Comment by raymondfeng** [comment]
It seems that your `201.217.226.72` ip forced `https`. Please check if port 3000 is used by another process.

**Comment by fgvicente** [comment]
ok to discard that it is the react application I put a single file with this code in /public

`<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>
<p>My first paragraph.</p>

</body>
</html>`

![image](https://user-images.githubusercontent.com/3626864/96488659-b3caf280-1214-11eb-967b-17e5fa43de5c.png)
as you will see, favicon tries to search with https

I do not have another application or something in port 3000

**Comment by achrinza** [comment]
The favicon issue is most likely a browser behaviour. If no favicon is explicitly defined, the web browser will try to look for it in well-defined locations. In this case, it will not cause any issues and can be safely ignored.

**Comment by fgvicente** [comment]
solved it with lb4 update
