### ISSUE TITLE
Improve binding between app and server

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#661]
## Problem
The current usage requires asynchronous retrieval of the server binding made in the application constructor:

```ts
export class HelloWorldApp extends Application {
  constructor() {
    super({
      components: [RestComponent],
    });
  }

  async start() {
    const rest = await this.getServer(RestServer);
    rest.handler((sequence, request, response) => {
      sequence.send(response, 'Hello World!');
    });
    await super.start();
    console.log(`REST server running on port: ${await rest.get('rest.port')}`);
  }
}
```

## Acceptance Criteria
- [ ] Demonstrate some alternate approaches for binding the server to the application without the need for asynchronous retrieval, or in a way that is more elegant despite the need for async.
- [ ] Get the team and the community to vote on what they like more

## Resources
This PR had some discussion on how to address this:
https://github.com/strongloop/loopback-next/pull/658

**Comment by kjdelisle** [comment]
Make a blog post about this and get community feedback based on the current implementation

**Comment by kjdelisle** [comment]
cc @raymondfeng 

@bajtos If we go with your proposal to allow both RestServer and RestApplication, does that make this task less important, or is it unrelated?

You could argue that the UX is still worth changing since someone will probably want to use RestServer, so this task might have value, but I'd like to know your thoughts.

**Comment by bajtos** [comment]
IMO, my proposal to have `RestApplication` is a solution of this problem.

For people that are configuring servers in an advanced way (e.g. multiple servers, etc.), my recommendation would be to create a custom subclass of `RestServer` and move any server initialization/customization to the constructor of that new subclass.

```ts
export class HelloWorldApp extends Application {
  constructor() {
    this.server(MyRestServer);
  }
}

export class MyRestServer extends RestServer {
  constructor() {
    this.handler((sequence, request, response) => {
      sequence.send(response, 'Hello World!');
    });
  }
}
```

**Comment by kjdelisle** [comment]
TBH, I think that https://github.com/strongloop/loopback-next/pull/671 is a much better solution to this problem since it more generally fixes the issue of needing to asynchronously handle server bindings to configure them for any sort of purpose (which will affect any sort of server implementation). This will allow all binding to be pushed back into the app constructor, which I think is the elegant UX we need.
