### ISSUE TITLE
'Handling Errors' link goes to document without Handling Errors section

### ISSUE THREAD

**Issue by emonddr** [strongloop/loopback-next#6627]
## Steps to reproduce

There are two places where the 'Handling Errors' link is used, but takes you to a document without a 'Handling Errors' section

- https://loopback.io/doc/en/lb4/REST-middleware-sequence.html 
- https://loopback.io/doc/en/lb4/REST-action-sequence.html
- https://loopback.io/doc/en/lb4/Using-strong-error-handler.html 

## Current Behavior

Clicking on link brings you to

https://loopback.io/doc/en/lb4/Sequence.html

but it cannot scroll to 

`handling-errors` anchor.

e.g. https://loopback.io/doc/en/lb4/Sequence.html#handling-errors 

## Expected Behavior

Should take us to  a section talking about Handling Errors.

**Comment by dhmlau** [comment]
I believe it's because there are 2 subpages added: [middleware base sequence](https://loopback.io/doc/en/lb4/REST-middleware-sequence.html) and [action based sequence](https://loopback.io/doc/en/lb4/REST-action-sequence.html). Each page has its own "handling error" section.

**Comment by emonddr** [comment]
> I believe it's because there are 2 subpages added: [middleware base sequence](https://loopback.io/doc/en/lb4/REST-middleware-sequence.html) and [action based sequence](https://loopback.io/doc/en/lb4/REST-action-sequence.html). Each page has its own "handling error" section.

Yeah I looked at the history of Sequence.md, and noticed that the `Handling Errors` section was cut and paste into the two new sequence docs.

**Comment by dhmlau** [comment]
PR #6631 has landed. Closing as done.
