### ISSUE TITLE
docs: Target es6 or es2017?

### ISSUE THREAD

**Issue by VMois** [strongloop/loopback-next#666]
# Description/Steps to reproduce
On "Installation" doc page, in section "Typescript project"
 (http://loopback.io/doc/en/lb4/Installation.html#typescript-project) is written "Important: use target es6" and then in the example below target is set to "es2017". Does it make any difference? Because it can be not clear which option to use.

**Comment by VMois** [comment]
In "Getting started" (http://loopback.io/doc/en/lb4/Getting-started.html) example target is set with es2017. So probably changing from target:es6 to target:es2017 would be correct in http://loopback.io/doc/en/lb4/Installation.html#typescript-project.

**Comment by bajtos** [comment]
Hello, sorry for the confusion.

The best target depends on what version of Node.js you are running on. `target: "es6"` is required if your are on Node.js 6.x. `target: "es2017"` is recommended if you are running on Node.js 8.x

The "Installation" page is undergoing a rewrite, see https://github.com/strongloop/loopback.io/pull/493.

I am closing this issue as resolved.
