### ISSUE TITLE
todo tutorial results in return of empty array for get

### ISSUE THREAD

**Issue by norricorp** [strongloop/loopback-next#6662]
## Steps to reproduce

I run through the tutorial https://loopback.io/doc/en/lb4/Appsody-LoopBack.html for using loopback 4 within appsody. When I try to get the todo list, I get an empty array and 200 status. As I have been running various lb4 commands, perhaps I have been fat fingured.
So I went to the loopback only todo tutorial and used lb4 example to clone the todo code. Run that and same result. Empty array of todo's and 200 status.

## Current Behavior

status 200, empty array "[]"

## Expected Behavior

An array of todo's

## Additional information

For the appsody tutorial, the controller code was created by lb4 controller. The only copy / paste I did was creating the db.json file with the data.
For loopback 4 code, I only used lb4 example so did not even do the data code. It was all in the cloned repo.

That suggests the problem is either the lb4 controller command (very doubtful - this stuff is tested) or the data file (has the contoller code changed and the tutorial not been updated to change the data file?)

Copy+paste the output of these two commands:
  node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 12.19.0

  npm ls --prod --depth 0 | grep loopback
nodejs-loopback-scaffold@1.0.0 /home/jnorris/loopback4/todolist
├── @loopback/boot@3.0.2
├── @loopback/context@3.12.0
├── @loopback/core@2.11.0
├── @loopback/openapi-v3@5.0.0
├── @loopback/repository@3.1.0
├── @loopback/rest@8.0.0
├── @loopback/rest-explorer@3.0.2
├── @loopback/service-proxy@3.0.2

## Related Issues

https://github.com/strongloop/loopback-next/issues/6641 but this has a 500 status error

**Comment by norricorp** [comment]
Just to add, even if I change the controller code so that it is looking for a file called db1.json rather than db.json, I get the same result - an empty array with a 200 status. 
This is on the loopback example, nothing to do with appsody. So something is very strange. I would have expected a 500 internal error. I can only think I have done something very dumb except all I run was "lb4 example todo" so the opportunities for mistakes are limited.

**Comment by achrinza** [comment]
Hmm, I've not been able to replicate the issue.

Here's the steps I followed

Run these commands:
```bash
npm i -g @loopback/cli
lb4 example todo
cd loopback4-example-todo
npm start
```

Go to `/explorer` and execute the relevant GET request to `/todos` without any request body.

Results:
![image](https://user-images.githubusercontent.com/25147899/97445374-269c4200-1968-11eb-9b79-56a402545e95.png)

> even if I change the controller code so that it is looking for a file called db1.json rather than db.json

Did you mean Datasource code (under `src/datasources/*`)? The way the data is stored is abstracted away from Controllers.

> The only copy / paste I did was creating the db.json file with the data.

Was this the data that was copied-and-pasted?

```
{
  "ids": {
    "Todo": 5
  },
  "models": {
    "Todo": {
      "1": "{\"title\":\"Take over the galaxy\",\"desc\":\"MWAHAHAHAHAHAHAHAHAHAHAHAHAMWAHAHAHAHAHAHAHAHAHAHAHAHA\",\"id\":1}",
      "2": "{\"title\":\"destroy alderaan\",\"desc\":\"Make sure there are no survivors left!\",\"id\":2}",
      "3": "{\"title\":\"play space invaders\",\"desc\":\"Become the very best!\",\"id\":3}",
      "4": "{\"title\":\"crush rebel scum\",\"desc\":\"Every.Last.One.\",\"id\":4}"
    }
  }
}
```

This is identical to the `db.json` found in the [Todo example](https://github.com/strongloop/loopback-next/blob/1c40f6b197b271c6317f30f2203167d23d4f6f3a/examples/todo/data/db.json) and I haven't been able to replicate the issue. The results are the same as the screenshot above.

---

If following `lb4 example todo` doesn't work, then there may be something else amiss and unfortunately I'm not able to replicate the issue from my end.

**Comment by norricorp** [comment]
in one sense I am not surprised it works for you. It is the tutorial so it must work. Except for me it does not.
I run the same commands as you did. And the response from GET /todos via the explorer is "[]" with a status of 200.
And that means no code changes on my part.
I will carry on investigating.

**Comment by dhmlau** [comment]
We probably have a much older version on `@loopback/cli` on Apposody. If it works for @achrinza, it might be a good time to update the LB4 CLI version there. 
@raymondfeng, do you have any pointer on how we can get it updated? Thanks.

**Comment by norricorp** [comment]
Just to emphasise this is nothing to do with Appsody. I just happened to start from appsody but the same happens in a pure loopback env.
So appsody is a red herring.

**Comment by dhmlau** [comment]
@norricorp, thanks for the clarification. Sorry that I missed your previous comment about not Appsody related.
One more question, what's the `@loopback/cli` version you're using? Would like to try the exact version you're using. Thanks.

**Comment by norricorp** [comment]
So I have tried this on two mint linux VMs and on windows. And this is what I have discovered. Using the explorer, I get the following in brave, firefox (mint) and firefox and edge (windows)
![image](https://user-images.githubusercontent.com/19404257/97495144-37948580-195f-11eb-90e0-c082f144f575.png)

BUT, if in a browser or command line with curl, I go to 127.0.0.1:3000/todos, I get an expected result ie todo records

So the problem (for me) appears to be the explorer. The server is working, it is delivering REST but not within explorer.

$ lb4 -version
@loopback/cli version: 2.16.1

@loopback/* dependencies:
  - @loopback/authentication: ^7.0.2
  - @loopback/boot: ^3.0.2
  - @loopback/build: ^6.2.5
  - @loopback/context: ^3.12.0
  - @loopback/core: ^2.11.0
  - @loopback/metadata: ^3.0.2
  - @loopback/openapi-spec-builder: ^3.0.0
  - @loopback/openapi-v3: ^5.0.0
  - @loopback/repository-json-schema: ^3.0.2
  - @loopback/repository: ^3.1.0
  - @loopback/rest: ^8.0.0
  - @loopback/testlab: ^3.2.7
  - @loopback/docs: ^3.17.1
  - @loopback/example-hello-world: ^2.1.12
  - @loopback/example-log-extension: ^2.1.12
  - @loopback/example-rpc-server: ^2.1.12
  - @loopback/example-todo: ^3.8.0
  - @loopback/example-soap-calculator: ^2.4.5
  - @loopback/service-proxy: ^3.0.2
  - @loopback/http-caching-proxy: ^2.1.16
  - @loopback/http-server: ^2.3.0
  - @loopback/example-todo-list: ^3.6.0
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^3.0.2
  - @loopback/eslint-config: ^10.0.1
  - @loopback/example-express-composition: ^2.5.0
  - @loopback/example-greeter-extension: ^2.1.12
  - @loopback/booter-lb3app: ^2.2.12
  - @loopback/example-lb3-application: ^2.5.0
  - @loopback/example-greeting-app: ^2.2.10
  - @loopback/example-context: ^2.1.12
  - @loopback/repository-tests: ^0.14.0
  - @loopback/health: ^0.5.2
  - @loopback/authorization: ^0.7.2
  - @loopback/rest-crud: ^0.8.16
  - @loopback/security: ^0.3.2
  - @loopback/authentication-passport: ^3.0.2
  - @loopback/example-metrics-prometheus: ^0.4.2
  - @loopback/metrics: ^0.4.2
  - @loopback/model-api-builder: ^2.1.16
  - @loopback/logging: ^0.4.2
  - @loopback/example-access-control-migration: ^2.3.0
  - @loopback/example-file-transfer: ^1.5.5
  - @loopback/example-rest-crud: ^1.7.0
  - @loopback/apiconnect: ^0.5.2
  - @loopback/example-validation-app: ^1.8.0
  - @loopback/cron: ^0.3.2
  - @loopback/example-multi-tenancy: ^0.7.0
  - @loopback/example-passport-login: ^1.7.0
  - @loopback/authentication-jwt: ^0.7.2
  - @loopback/context-explorer: ^0.2.2
  - @loopback/express: ^2.1.0
  - @loopback/example-todo-jwt: ^1.4.0
  - @loopback/mock-oauth2-provider: ^0.1.10
  - @loopback/pooling: ^0.3.2
  - @loopback/typeorm: ^0.2.2
  - @loopback/example-graphql: ^0.1.2
  - @loopback/graphql: ^0.2.0
  - @loopback/filter: ^1.1.2
  - @loopback/rest-msgpack: ^0.2.1
  - @loopback/example-binding-resolution: ^0.1.0
  - @loopback/example-webpack: ^0.1.0

**Comment by raymondfeng** [comment]
@norricorp What value do you have for `filter` inside the API Explorer?

**Comment by achrinza** [comment]
Based on the screenshot, the `filter` parameter wasn't cleared.

Here's how I executed the query via the API Explorer:

![MakingCorrectQuery](https://user-images.githubusercontent.com/25147899/97508546-d8fcf500-19ba-11eb-90e9-ad458f50951f.gif)

If we don't remove the example `filter`, we are able to reproduce the same result:

![MakingWrongQuery](https://user-images.githubusercontent.com/25147899/97508579-eb772e80-19ba-11eb-80fe-7cd947b783cc.gif)

**Comment by norricorp** [comment]
@achrinza - thank you for taking the time on this. Yes, removing the filter in explorer gives a result. 
It does lead to two questions - why does explorer put that filter by default? And having read through the tutorials again, I still do not see anything about filters and removing them.
But again many thanks.

**Comment by norricorp** [comment]
Ah, so it is the additionalProp1 that messes it up.

**Comment by achrinza** [comment]
> why does explorer put that filter by default?

This is the behaviour of the Swagger Explorer, which is what the LoopBack API Explorer uses under the hood.

> And having read through the tutorials again, I still do not see anything about filters and removing them.

Unfortunately this is one of those areas that get missed when writing documentation for a large documentation. It's already covered under <https://loopback.io/doc/en/lb4/Working-with-data.html>, and typically users discover filters when toying with the API Explorer and going through the How To-Guides. Though I agree we could potentially improve discoverability of filters through the tutorials.
