### ISSUE TITLE
Cleanup - loopback4-example-microservices

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#669]
## Overview
We need to trim the fat on the loopback-next-example repository, and clean it up for GA.

## Acceptance Criteria
- [ ] Remove the `todo-legacy` service (as it's not a part of this example any longer)
- [ ] Setup lerna with the repository and replace the existing scripts used for app building/testing
- ~[ ] Give an example of how to publish and deploy microservices in your monorepo using lerna (or link to a better example of that on Lerna's website, if it exists)~ Shelved for the issue for creating a tutorial for this example

In addition, from strongloop/loopback4-example-microservices#94:
> - follow the instuctions on the README and update either the README or the code to make the repository's features apparent and complete
>   - currently, following the steps on README will result in errors
> - leverage lerna to resolve dependencies between services
> - use automatic openapi-v3 schema decorators instead of explicitly defining schemas
> - use 'models' and their decorators to define custom types
> - complete switching over repositories to extend from `DefaultCrudRepository`
> - follow file naming convention advocated over [here](https://github.com/strongloop/loopback-next/blob/master/docs/site/DEVELOPING.md#file-naming-convention)
> - look into potentially switching from `loopback-swagger-connector` since LoopBack 4 no longer supports swagger-v2.

**Comment by dhmlau** [comment]
Should involve service integration with SOAP services.
