### ISSUE TITLE
Todo-List tutorial - model contains "color", data contains "dateModified"

### ISSUE THREAD

**Issue by norricorp** [strongloop/loopback-next#6733]
## Steps to reproduce
Tutorial for todo-list. Model has 3 fields - id, title, color. But the db.json file has id, title and dateModified.

## Current Behaviour

Model and data fields do not match

## Expected Behaviour

The data should use "color" rather than "dateModified"

## Link to reproduction sandbox

Not applicable

## Additional information
$   node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 12.19.0
$   npm ls --prod --depth 0 | grep loopback
nodejs-loopback-scaffold@1.0.0 /home/xxxxxx/loopback4/todolist
├── @loopback/boot@3.0.2
├── @loopback/context@3.12.0
├── @loopback/core@2.11.0
├── @loopback/openapi-v3@5.0.0
├── @loopback/repository@3.1.0
├── @loopback/rest@8.0.0
├── @loopback/rest-explorer@3.0.2
├── @loopback/service-proxy@3.0.2

Am happy to fork repo, apply fix and open pull request.
Files that need changing are docs/site/tutorials/todo-list/todo-list-tutorial-relations.md and data/db.json

## Related Issues
none

**Comment by dhmlau** [comment]
@norricorp, if you could submit a PR to fix it, that would be great. Thanks! 
There's an ongoing PR (I believe it's close to land) https://github.com/strongloop/loopback-next/pull/6598 that changes quite a lot of files in the todo-list example. You might want to check what's changed before making further changes.

**Comment by norricorp** [comment]
Just to add this is my first bug fix on github so please be gentle.

**Comment by dhmlau** [comment]
PR #6733 has landed. Closing as resolved.
