### ISSUE TITLE
lb4 discover Oracle don't show models

### ISSUE THREAD

**Issue by alexsilvar** [strongloop/loopback-next#6734]
## Steps to reproduce

Create a datasource for a oracle database and run ```lb4 discover``` 

## Current Behavior

it will led you to the Select the models with an empty list
```
lb4 discover
? Select the connector to discover DataMart
? Select the models which to discover (Press <space> to select, <a> to toggle all, <i> to invert selection)
```

## Expected Behavior

List of models from database show bellow:
```
? Select the models which to discover (Press <space> to select, <a> to toggle all, <i> to invert selection)
Table1
Table2
```

## Additional information
Extensions version
```
loopback-connector-oracle: ^4.5.2
@loopback/cli: 2.16.1
```

I tested the connection using ```oracledb``` and I'm able to run select queries normally on my database using the same connection string that I'm providing.

## Related Issues
Maybe those two
#3296 #2915

**Comment by dhmlau** [comment]
@alexsilvar, if you try `lb4 discover --all`, would it work? The `--all` option will return all the tables. 

I haven't tried it on Oracle yet, but for DB2, without the `--all` option, it only returns the tables with schema name that's same as the user name.

**Comment by alexsilvar** [comment]
Hey, thanks. After I cleaned up my project and changed to an admin db account I was able to discover the tables.
The --all also helped me to get all of them at once.
