### ISSUE TITLE
invalid include relation throw 500

### ISSUE THREAD

**Issue by mdbetancourt** [strongloop/loopback-next#6741]
## Steps to reproduce
Add a relation and resolver
call the endpoint with the following filter
```ts
{
  "include": [{
    "relation": "prodctts" //instead of products
  }]
}
```
## Current Behavior
```ts
{
    "error": {
        "statusCode": 500,
        "message": "Internal Server Error"
    }
}
```
## Expected Behavior
throw a 400 BadRequestError

**Comment by dhmlau** [comment]
@agnes512, could you please take a look? Thanks.

**Comment by agnes512** [comment]
Thank @mdbetancourt for reporting this! I reckon it's a valid bug and have submitted a PR https://github.com/strongloop/loopback-next/pull/6755 to fix it. It would be great if you could take a look, thanks!
