### ISSUE TITLE
Docs: Update header about API World award

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#6742]
## Suggestion

I believe @bajtos mentioned it some time ago that since LoopBack received the API World award for a year now, it might be a good time to remove it from the header of the docs.

## Acceptance Criteria
My proposal:
- [x] Remove it from our docs' header, so that it doesn't appear on every page
- [x] Add some text around it in the [overview page](https://loopback.io/doc/en/lb4/index.html)
- [x] (Optional) Update loopback.io to include this information

WDYT? @strongloop/loopback-maintainers

**Comment by nabdelgadir** [comment]
+1 to removing it from the header. I think it would fit nicely in this section of the overview page:
<img width="904" alt="Screen Shot 2020-11-11 at 12 32 16 PM" src="https://user-images.githubusercontent.com/42985749/98844160-f057cb80-2419-11eb-9180-6934b0761f31.png">

**Comment by jannyHou** [comment]
+1 for removing it.

**Comment by bajtos** [comment]
+1 to remove (or move it to somewhere else)

**Comment by dhmlau** [comment]
Closing as done.
