### ISSUE TITLE
Extension: gRPC

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#675]
| Extension        | Descriptions           | Developers  |  LB4 Maintainer
| ------------- |:-------------:| -----:|-----:|
|gRPC      |      | @jonathan-casarrubias, @VMois   | @raymondfeng or @bajtos ?|

## Repo
https://github.com/strongloop/loopback4-extension-grpc

## Related issues
Spike done by @bajtos on gRPC: https://github.com/strongloop/loopback-next/issues/582

Prior arts:
- https://github.com/strongloop/loopback-example-polyglot
- https://github.com/strongloop/loopback-connector-grpc
- https://github.com/strongloop/loopback-next/issues/521

**Comment by raymondfeng** [comment]
I'll create a repo first - `strongloop/loopback4-extension-grpc`.

**Comment by raymondfeng** [comment]
Repo created - https://github.com/strongloop/loopback4-extension-grpc. I'll add the basic project setup 1st.

**Comment by jonathan-casarrubias** [comment]
@raymondfeng is there already a good example of a component? like one of the repos that you consider we can use that as foundation, in this docs: 

http://loopback.io/doc/en/lb4/Creating-components.html

There is no structure recommendation, so I want to know if there is a ready example for that

**Comment by raymondfeng** [comment]
@jonathan-casarrubias There are a few components we can use as references:
- https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/rest-component.ts
- https://github.com/strongloop/loopback-next/blob/master/packages/authentication/src/auth-component.ts
- https://github.com/strongloop/loopback4-example-log-extension/blob/dev/src/log.component.ts

**Comment by VMois** [comment]
@raymondfeng @jonathan-casarrubias I have one question. How we should work on repo gRPC? Do we need to use forks or we can directly push branches (without master of course)?

**Comment by jonathan-casarrubias** [comment]
@raymondfeng the loopback4-example-log-extension is just what I was looking for, thanks... Looking for an answer to @VMois's question about working on branches or forks, Im guessing PR's to a dev branch

**Comment by jonathan-casarrubias** [comment]
So, I've been reviewing the repo while working, it looks pretty good to me... I will continue until I fully understand the log extension, then I might start working on the initial structure this afternoon, basically I want to follow the log extension one.

Thinking about that, I would not like to simply pull from the log extension since it might be messy, so... I was thinking what if we also create like an **extension starter**, an empty structure with all the basics in there... It might be a separated repot (Potentially could be added into the CLI tool)

An initial draft (for new repo) can be easily done while starting this one but sending that before adding any gRPC specific feature.

Thoughts?

**Comment by VMois** [comment]
@jonathan-casarrubias I think it's a great idea to create a minimal draft for component development. Separate repo will be great, so other developers can use it in future for their own components.

**Comment by bajtos** [comment]
>  was thinking what if we also create like an extension starter, an empty structure with all the basics in there

We have that already ready for you - see https://github.com/strongloop/loopback4-extension-starter

> How we should work on repo gRPC? Do we need to use forks or we can directly push branches (without master of course)?

I am personally fine with giving you write access so that you can open feature branches directly in the repository.

**Comment by bajtos** [comment]
We have a new GitHub team @strongloop/loopback-grpc-maintainers with write access to  https://github.com/strongloop/loopback4-extension-grpc; you are both members, @jonathan-casarrubias and @VMois.

Additionally, I marked the `master` branch as protected to forbid `git push -f`.

Last but not least, I created a new Gitter room where we can discuss and coordinate our work: https://gitter.im/strongloop/loopback4-extension-grpc

**Comment by jonathan-casarrubias** [comment]
Ok cool @bajtos that is a time saver, I'm reviewing now the starter, also... I just joined the gitter room.

I'm reading the starter readme, it is very exciting... It reminds me when I was learning the good old  LoopBack, everything seems so new lol..

Anyway, we'll ramp up and do great things with LB4 as well.

Cheers
jon

**Comment by bajtos** [comment]
AFAICT, the first implementation is already live in https://github.com/strongloop/loopback4-extension-grpc. I am closing this issue as done. Please open new issues in that other repository for new feature requests or bug reports.
