### ISSUE TITLE
BindingScope path in socketio-controller-factory.ts needs to get corrected

### ISSUE THREAD

**Issue by IshuSF** [strongloop/loopback-next#6756]
BindingScope in socketio-controller-factory.ts is hard coded to '../../../packages/context/dist', so this needs to be changes to '@loopback/context'

## Steps to reproduce

In the root of socketio extension, there exist socketio-controller-factory.ts.
Import path of Binding Scope is  ../../../packages/context/dist but there is no such folder.

This will give compile error.

Path needs to be changed to '@loopback/context'

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by mayank-SFIN571** [comment]
thanks @IshuSF , i'll have made the necessary changes in 
https://github.com/strongloop/loopback-next/pull/6757

**Comment by samarpan-b** [comment]
@raymondfeng is this published ?
