### ISSUE TITLE
Why is required connectors?

### ISSUE THREAD

**Issue by mdbetancourt** [strongloop/loopback-next#6773]
Why we need a Connector or datasource? is not enough with just repositories? there's some way to build connector at the loopback 4 way? or connectors are just legacy code from lb3?

**Comment by achrinza** [comment]
A datasource...
- defines the connector and the connector-specific configuration to create a database or service connection.
- defines a set of common functions that is used by repositories (e.g. CRUD)
- is a lift-and-shift form LoopBack 3

A repository...
- defines a set of APIs to be used by the LoopBack 4 application (e.g. CRUD)
- does not posses connector-specific information (e.g. how to establish a connection, generate the query)
- works at a higher abstraction level thereby...
    - allowing for cross-database relations
    - allowing for custom functions

Though datasources are concepts from LoopBack 3, there are no plans to deprecate the concept.

There were some discussions on replacing Juggler (and in turn, `DefaultCrudRepository`) with `CrudRepositoryImpl` (see: https://github.com/strongloop/loopback-next/issues/889#issuecomment-500788596), though AFAIK it's low-priority as is requires rewriting all the connectors.

**Comment by mdbetancourt** [comment]
and how could i write a connector for loopback 4? i can't find anything about it in documentation, ok i understood repositories and connectors are different things but service can replace a connector?

**Comment by achrinza** [comment]
We haven't ported the documentation to LoopBack 4, but AFAIK, the LoopBack3 docs still apply as Juggler connector interface hasn't changed much:

https://loopback.io/doc/en/lb3/Building-a-connector.html

Services are just JavaScript classes with any arbitrary properties. Hence, anything can be classes.

Connectors have the benefit of built-in connection lifecycle management and a set of well-defined interfaces such as migration and discovery (which the lb4 CLI uses).

**Comment by achrinza** [comment]
Hi @mdbetancourt, I'll proceed to close this issue as solved due to inactivity. Feel free to comment if you believe that this is not the case.
