### ISSUE TITLE
rest: Support HTTPS and pre-instantiated HTTP/S instances

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#678]
## Overview

Developers obviously want to use https with their applications (and well they should!). Currently, the alpha implementation of `@loopback/rest` has no support whatsoever for this concept!

## Acceptance Criteria
- [ ] Add configuration support in `RestComponent`/`RestServer` for provision of:
  - [ ] Certificates/key materials
  - [ ] https configuration options (`rejectUnauthorized`, `requestCert`, etc...)
- [ ] Add configuration support to accept an existing http, https or https/2 server instance.

**Comment by bajtos** [comment]
Labelled as non-MVP - users can get HTTPS support by puting an Nginx instance in front of their LoopBack app, or use a sidecar like Envoy when running a microservice-based architecture like http://istio.io/

**Comment by dhmlau** [comment]
Talked to @raymondfeng , it might be solved through #1082

**Comment by dhmlau** [comment]
Closing as duplicate of https://github.com/strongloop/loopback-next/issues/430
