### ISSUE TITLE
index.ts is different when created via Appsody vs lb4 app

### ISSUE THREAD

**Issue by norricorp** [strongloop/loopback-next#6781]
## Steps to reproduce

Run appsody init nodejs-loopback and compare with index.ts with project created with lb4 app

## Current Behavior
appsody created index.ts
```
export async function main(config: ApplicationConfig = {}) {
  const app = new DemoApplication(config);
  await app.boot();
  await app.start();

  const url = app.restServer.url;
  console.log(`Server is running at ${url}`);
  console.log(`Try ${url}/ping`);

  return app;
}
```

lb4 created index.ts (comments removed)
```
export async function main(options: ApplicationConfig = {}) {
  const app = new TestApplication(options);
  await app.boot();
  await app.start();

  const url = app.restServer.url;
  console.log(`Server is running at ${url}`);
  console.log(`Try ${url}/ping`);

  return app;
}

if (require.main === module) {
  // Run the application
  const config = {
    rest: {
      port: +(process.env.PORT ?? 3000),
      host: process.env.HOST,
      gracePeriodForClose: 5000, // 5 seconds
      openApiSpec: {
        // useful when used with OpenAPI-to-GraphQL to locate your application
        setServersFromRequest: true,
      },
    },
  };
  main(config).catch(err => {
    console.error('Cannot start the application.', err);
    process.exit(1);
  });
}

```

## Expected Behavior

For them to be the same?

## Additional information

$   node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 12.19.0
$   npm ls --prod --depth 0 | grep loopback
nodejs-loopback-scaffold@1.0.0 /home/jnorris/loopback4/todolist
├── @loopback/boot@3.0.2
├── @loopback/context@3.12.0
├── @loopback/core@2.11.0
├── @loopback/openapi-v3@5.0.0
├── @loopback/repository@3.1.0
├── @loopback/rest@8.0.0
├── @loopback/rest-explorer@3.0.2
├── @loopback/service-proxy@3.0.2

This arose because I needed to configure CORS so as to work with a colocated gridsome server. Then I noticed that the appsody code did not have the required code to amend. 

Putting CORS aside, both appsody and lb4 generated apps work with curl. The only difference is that appsody will allow access from outside of the machine, lb4 will only allow access via localhost.

**Comment by achrinza** [comment]
Hi @norricorp, thanks for raising the issue! I believe this is a 2-pronged issue:

1. Part of it can be a duplicate of #5802 - the template hasn't been updated to the latest scaffolds
2. The template abstracts certain components away to enforce cloud-native best practices. That is, the Appsody template consists of a hidden LB4 "base" application that boots the user's LB4 application. https://github.com/strongloop/loopback-next/pull/4250#issuecomment-562336026 explains this a bit.

**Comment by norricorp** [comment]
It is in the extra code that configuration such as change port, configure CORS is done so how should these values be changed in an appsody created loopback app?

As an aside, why should an appsody run app be accessible from outside of the server but not accessible from a lb4 created app running with npm start? Both are listening on port 3000 so it is not a firewall issue because it works with appsody.

**Comment by raymondfeng** [comment]
https://github.com/appsody/stacks/tree/master/incubator/nodejs-loopback is out of date. We need to upgrade it to the latest version of LoopBack 4 releases.

**Comment by mrmodise** [comment]
@raymondfeng correct me if am wrong, as a work-around @norricorp can use the index.js to configure cors? before upgrading to the latest version of LB4 this is where I used to configure cors. @norricorp you will add cors config after this line: https://github.com/appsody/stacks/blob/8d8aebc9c256923cc155eaf2fff1be9e4a1a924c/incubator/nodejs-loopback/templates/scaffold/index.js#L10 

something like:

```ts
cors: {
        origin: ['http://localhost:4200'],
       methods: 'GET,HEAD,PUT,PATCH',
},
```

**Comment by norricorp** [comment]
Hi @mrmodise, 
appsody created an index.js file that does not have the if (require.main === module) condition, hence there is no place to put it. 
Except that is what I have done - I used the index.js from a test project created with lb4 app. And, as you know from slack, that is not working for me. 
But, to be fair, this is issue is not about whether CORS can be configured or not (that is another problem), it is that the appsody stack for loopback has not been updated to use the latest loopback code.
John

**Comment by achrinza** [comment]
In this case, would it be fine if we close this as duplicate of #5802?

**Comment by norricorp** [comment]
Yes that is fine. 
The remainder of index.ts has been put in a top level index.js file. So appsody loopback and loopback loopback have really diverged.
