### ISSUE TITLE
Deploying LB4 application on Apache server

### ISSUE THREAD

**Issue by codeduniya** [strongloop/loopback-next#6782]
> **Maintainers' Note**
> This question has been posted elsewhere:
> - https://stackoverflow.com/q/64831181

I have tried deploying my Loopback 4 application on Apache running on a CentOS 7 server. I followed the instructions given [here  ](https://loopback.io/doc/en/lb4/deploying-with-pm2-and-nginx.html) for Nginx but the proxy pass through is not working on Apache. Is there any documentation on how to deploy a LB4 application on Apache?

**Comment by achrinza** [comment]
Hi @codeduniya, have you tried looking at https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html? This should be a good starting point to mapping NGINX's configuration to Apache 2.

**Comment by achrinza** [comment]
Hi @codeduniya, I'll proceed to close this issue due to inactivity. Feel free to comment to request re-opening the issue.
