### ISSUE TITLE
Add Server section to Creating Components

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#681]
## Acceptance Criteria
- [ ] Add section on how to implement own Server/Transport
  - [x] Which interfaces to implement (Context, Server, etc...)
  - [x] Which functions (start, stop)
  ~- [ ] Handling sequences, and default sequence actions~
  ~- [ ] Creating per-request Context instances~
  ~- [ ] How to instantiate controllers and invoke controller methods~

**Comment by kjdelisle** [comment]
After going through a big complicated tutorial with the team, @jannyHou has made it clear that we'd be writing an excessively opinionated piece of documentation with respect to the last three bullet points of this task.

Unlike the unit test best practices, there isn't a stronger body of evidence to point towards that heavily implies that these listed approaches are best practices, or even what they should look like.

I would say that this is the sort of thing you would write as a blog post with a concrete working example/tutorial for people to follow along with, rather than adding it to the documentation.

**Comment by jonathan-casarrubias** [comment]
Looking forward for this docs to be published, I'm already working in the grpc module and I understood most of creating servers mainly by reverse engineering the rest component.

I still feel there are missing details that I'm pretty sure this docs will address
