### ISSUE TITLE
Testing your Application: explain reasoning behind our advice for stubbing

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#684]
In https://github.com/strongloop/loopback4-example-getting-started/pull/2, the unit tests are using Repository Stubs in a way that produces unhelpful error messages. 

```ts
    const controller = new TodoItemController(todoItemRepo, todoRepo);
    const replace = todoItemRepo.deleteById as sinon.SinonStub;
    // ...
    replace.withArgs(item.id as number, newItem).resolves(newItem);
    // ...
    expect(
       await controller.replaceTodoItem(
         item.id as number,
         newItem,
         todo.id as number
       )
    ).to.eql(newItem);
```

(see https://github.com/strongloop/loopback4-example-getting-started/pull/2#discussion_r147392237)

In my experience, this style where the stubs have strict argument matching produces test failures that are difficult to troubleshoot.

For example, if the controller invokes `replace` with id `42` instead of `item.id`, then `replace` returns undefined and sometime later you will see an error that `undefined` was supposed to equal to something else.

Another problem with this approach is that it breaks arrange-act-assert pattern - the assertion that `replace` should be invoked with `item.id` is implicitly hidden in the arrange part where we are setting up the stubbed behavior.

A better approach is to make stubs loose, let them always return the good value regardless of the input arguments. Then add assertions to verify that stubbed method were invoked as expected.

We should extend http://loopback.io/doc/en/lb4/Testing-your-application.html#create-a-stub-repository to show the approach used in that pull request and explain why we recommend against it.

```ts
// arrange
replace.resolves(newItem);

// act
// controller.replaceTodoItem

// assert
sinon.assert.calledWith(replace, item.id as number, newItem);
```

This produces a more helpful test failure:

```
AssertError: expected stub to be called with arguments
1 2
// 1 is printed in green, 2 is printed in red
```

**Comment by dhmlau** [comment]
@bajtos , I'd like to move this out of GA.   It's useful information to be included in this task, but i think there are higher priority items than this one.  If you disagree, feel free to change.
