### ISSUE TITLE
@loopback/authentication is not support Yarn on Windows?

### ISSUE THREAD

**Issue by jy-hirasawa** [strongloop/loopback-next#6871]
I upgrade @loopback all.
yarn start occured error.
> error TS2688: Cannot find type definition file for 'lodash'.

I tried to reproduce it, there seems to be a problem with @loopback/authentication.
@loopback/authentication is not support Yarn on Windows?
Maybe from version 7.0.3.

## Steps to reproduce
on Windows. ( on Centos is OK)

`lb4 app`
`npm install --save @loopback/authentication`
`npm insall`
`npm run start`
is OK

But,
`lb4 app`
`yarn add @loopback/authentication`
`yarn install`
`yarn start`
is

> error TS2688: Cannot find type definition file for 'lodash'.

## Additional information
OS:Windows 10 Pro
node: V14.5.0
npm: 6.14.5
yarn: 1.22.5

**Comment by dhmlau** [comment]
I tried the above steps on MacOS, and seem to be running fine. I'm not familiar with yarn. @strongloop/loopback-maintainers, any ideas?

**Comment by jy-hirasawa** [comment]
I got this error with yarn v1, but succeeded with yarn v2.
Thank you!
