### ISSUE TITLE
Custom Sequence as detailed in docs does not work

### ISSUE THREAD

**Issue by aslamj** [strongloop/loopback-next#6918]
## Steps to reproduce
1. Create a sample lb4 app using 'lb4 sample-api'
2. Modify the existing sequence.ts file to the following code based on documentation for the custom sequence: https://loopback.io/doc/en/lb4/REST-middleware-sequence.html#custom-sequences
````
import {MiddlewareSequence, RequestContext} from '@loopback/rest';

export class MySequence extends MiddlewareSequence {
  log(msg: string) {
    console.log(msg);
  }

  async handle(context: RequestContext): Promise<void> {
    this.log('>>>>> request');
    await super.handle(context);
    this.log('<<<<< request');
  }
}
````

## Current Behavior

When running the above app, the custom sequence's handle method is not being invoked.

## Expected Behavior

The custom sequence's handle method must be invoked and I should see the logs before and after handling the request/response.

## Link to reproduction sandbox

-NA-

## Additional information

darwin x64 14.5.0

├── @loopback/boot@3.1.2
├── @loopback/core@2.13.1
├── @loopback/repository@3.3.0
├── @loopback/rest@9.1.1
├── @loopback/rest-explorer@3.0.5
├── @loopback/service-proxy@3.0.5

When looked into the debugger, I see the default sequence using the middleware is being executed, so basically, my custom sequence is not getting invoked.

## Related Issues

-NA-

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by priyadharshini-gopal** [comment]
i ma trying to use the https://github.com/loopbackio/loopback-next/tree/master/examples/multi-tenancy . The sequence still doesnt work. I have export class MySequence implements SequenceHandler . how should I add the sequence to mulittenant
