### ISSUE TITLE
Migration of LB3 "app.models.modelName.modelMethod" 

### ISSUE THREAD

**Issue by grisson2** [strongloop/loopback-next#6925]
I need need a clarification for accessing repositories from express-side:

I have cloned the loopback4-example-express-composition demo in order to do some experiments before migrating a lb3 app.
Then, i started testing some stuff including trying to access repositories from the express-side of the app:

server.ts
```

export class ExpressServer {
  public readonly app: express.Application;
  public readonly lbApp: NoteApplication;
  private server?: http.Server;

  constructor(options: ApplicationConfig = {}) {
      this.app = express();
      this.lbApp = new NoteApplication(options);
  }

  public async boot() {
      await this.lbApp.boot();
  }

 // this is called after awaiting previous boot()
  public async mountExpress(){
      this.app.use('/', new ClientRouter().router);
  }
}

```

ClientRouter.ts
```
import { Router } from 'express';

export class ClientRouter {
    router: Router;
    constructor(){
        this.router = this.mount();
    }
    mount(){
        const router = Router();
        router.get('/renderSomeEjs', (req, res, next) => {
            // need to access repositories here
            res.render('test',{});
        });
        return router;
    };
}

```

In this example i need to access repositories, get some data and then render an html page.
Previously on LB3 i just had to write "app.models.someModel.someMethod.find", in the **router.get** section of ClientRouter, now i just can't figure what has to be done, nor what has to be included since dependency injection seems to be out of the games here.

Some suggestions?

**Comment by grisson2** [comment]
After a good refreshing meal and some research i got to this:

```
router.get('/renderSomeEjs', (req, res, next) => {
    this.lbApp.getRepository(NoteRepository)
      .then((r:NoteRepository) => {
           return r.find({});
      })
      .then((result: Note[])=> {
            res.render('test',{data: results});
      });
})
```

Looks like what i need but is this a correct way to do it?

**Comment by achrinza** [comment]
> Looks like what i need but is this a correct way to do it?

Yes, it's a valid way of doing it. Feel free to ask for any clarifications 😃
