### ISSUE TITLE
Jwt authentication

### ISSUE THREAD

**Issue by saravanababu1694** [strongloop/loopback-next#6932]
I am using jwt authentication service in loopback 4 how to revoke a token, i am not getting any boolean values the jwt is getting authenticated by passing any or previous user token to it how to prevent that.

**Comment by achrinza** [comment]
You can try injecting `RestBindings.Http.RESPONSE` and then using `res.clearCookie()`.

**Comment by indrakumarprajapat** [comment]
@achrinza let me correct the question plz, we are using jwt authentication, and our requirement is that, the token should be expired on every new login, that means, a user cannot login on multiple device at the same time. So what we were thinking is that, every time on login we are creating a new token and that token we are saving into user table. For every login the previously stored token, we are planning to revoke it. so we were trying to call, revokeToken method but it is undefined and networking.

@achrinza can you help plz.

**Comment by achrinza** [comment]
Sorry for missing your reply - In this case, one solution is to create a revoke table to keep track of the revoked tokens.

> revokeToken method but it is undefined and networking.

AFAIK, token revocation isnt' supported in `@loopback/authentication-jwt`. We could consider supporting such as feature, though it might be better-suited to be stored in a [Key-Value store](https://loopback.io/doc/en/lb4/Repository.html#access-keyvalue-stores) where there's native expiry support.

**Comment by dhmlau** [comment]
Closing as the question was answered.
