### ISSUE TITLE
apidocs needs more descriptions 

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#694]
In the apidocs, there are broken links (e.g. Array, ProviderMap) and missing descriptions in the arguments,

Example: https://apidocs.strongloop.com/@loopback%2fcore/#Application

## Acceptance Criteria
Go through each @loopback packages to fill in the missing descriptions and fix broken links

- [ ] core
- [ ] context
- [ ] authentication
- [ ] repository
- [ ] rest
- [ ] openapi-spec
- [ ] openapi-spec-builder

cc @crandmck @bschrammIBM

**Comment by bajtos** [comment]
Closing as a duplicate of https://github.com/strongloop/loopback-next/issues/577
