### ISSUE TITLE
Unusual handling of "this" in DefaultCrudRepository.modelClass.observe()

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#6962]
The current issue title is a placeholder as the exact issue is unknown.

The issue was created to help properly prioritize and discuss the issue discussed in #1919 and keep the topics separate.

**@mycolaos's comment:**

> Found this https://loopback.io/doc/en/lb4/migration-models-operation-hooks.html,
> 
> ```
> class ProductRepository extends DefaultCrudRepository<
>   Product,
>   typeof Product.prototype.id,
>   ProductRelations
> > {
>   constructor(dataSource: juggler.DataSource) {
>     super(Product, dataSource);
>   }
> 
>   definePersistedModel(entityClass: typeof Product) {
>     const modelClass = super.definePersistedModel(entityClass);
>     modelClass.observe('before save', async ctx => {
>       console.log(`going to save ${ctx.Model.modelName}`);
>     });
>     return modelClass;
>   }
> }
> ```
> 
> Seems to work. Is there any reason why the other approach was recommended?
> 
> UPDATE: not really working, it keeps the reference to the first `RequestContext`.

**@f-w comment:**

> 
> I also confirmed the workaround keeps the reference to the request context defined in the first repository instance.
> For example, with code
> 
> ```
> export class ProductRepository extends DefaultCrudRepository<
>   Product,
>   typeof Product.prototype.id
> > {
>   constructor(
>    ...
>     @inject.getter(MiddlewareBindings.CONTEXT)
>     protected getHttpContext: Getter<MiddlewareContext>,
>   ) {
>     ...
>   }
> 
>   definePersistedModel(
>     entityClass: typeof Product,
>   ): typeof juggler.PersistedModel {
>     const modelClass = super.definePersistedModel(entityClass);
>     modelClass.observe('access', async ctx => {
>       const httpCtx = await this.getHttpContext();
>       console.log(httpCtx);
>     });
>     return modelClass;
>   }
> }
> ```
> 
> 1. Subsequent http requests use the `httpCtx` of the first request
> 2.  In a test, when first inserting items using the repository (which has no http context), then querying using super test client, the httpCtx of the query request is null.

**@achrinza's comment**

> Thanks for providing your detailed findings, looking into this right now.
> 
> ---
> 
> These are my preliminary findings:
> 
> > 1. Subsequent http requests use the httpCtx of the first request
> > 2. In a test, when first inserting items using the repository (which has no http context), then querying using super test client, the httpCtx of the query request is null.
> 
> I have not been able to replicate this. In my testing, this has always resulted in a `key 'xxx' is not bound to any value` error.
> 
> I have tested and gotten the aforementioned behaviour with these bindings:
> 
> - RestBIndings.Http.REQUEST
> - MiddlewareBindings.CONTEXT
>

**Comment by f-w** [comment]
https://github.com/f-w/lb4-issue-6962 is the minimum-repro example built out of vanilla lb4 cli. Key point is [here](https://github.com/f-w/lb4-issue-6962/blob/master/src/repositories/product.repository.ts#L24-L33).

1.  init
    ```
    git clone https://github.com/f-w/lb4-issue-6962
    cd lb4-issue-6962
    npm i
    ```
2.  to repro *Subsequent http requests use the httpCtx of the first request*
     1. run `node .`
     2. in another console, run
         ```
         curl -X POST "http://[::1]:3000/products" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"name\":\"string\"}"
         curl -X GET "http://[::1]:3000/products"
         ```
    3. first console outputs 
        ```
        httpCtx.request.method=POST
        httpCtx.request.method=POST
        ```
3. to repro *In a test, when first inserting items using the repository (which has no http context), then querying using super test client, the httpCtx of the query request is null.*
    ```
    $npm run test
    ...
    httpCtx=undefined
    httpCtx=undefined
    ...
    ```
Had the context state been correct, the 2nd output in step 2 and 3 ought to be `httpCtx.request.method=GET`

**Comment by achrinza** [comment]
Thanks for providing the reproduction sandbox and steps - I've managed to consistently replicate the issue from my end, and was able to confirm that this only happens in _Juggler model observers_.
