### ISSUE TITLE
TypeError: this.userRepository.userCredentials is not a function

### ISSUE THREAD

**Issue by maher1719** [strongloop/loopback-next#6964]
I just copied authentication-jwt example from the documentation page and got this error

https://user-images.githubusercontent.com/25207866/103325641-e848ff00-4a4c-11eb-95f1-772e34a2091a.mp4

Request POST /signup failed with status code 500. TypeError: this.userRepository.userCredentials is not a function
    at ConnectController.signUp 
npm dependencies 
"dependencies": {
    "@loopback/authentication": "^7.0.5",
    "@loopback/authentication-jwt": "^0.7.5",
    "@loopback/boot": "^3.1.2",
    "@loopback/cli": "^2.17.2",
    "@loopback/core": "^2.13.1",
    "@loopback/repository": "^3.3.0",
    "@loopback/rest": "^9.1.1",
    "@loopback/rest-explorer": "^3.0.5",
    "@loopback/service-proxy": "^3.0.5",
    "concurrently": "^5.3.0",
    "loopback-connector-mongodb": "^5.5.0",
    "tslib": "^2.0.0"
  },
  "devDependencies": {
    "@loopback/build": "^6.2.8",
    "@loopback/eslint-config": "^10.0.4",
    "@loopback/testlab": "^3.2.10",
    "@types/node": "^10.17.48",
    "eslint": "^7.15.0",
    "source-map-support": "^0.5.19",
    "typescript": "~4.1.3"
  }

**Comment by achrinza** [comment]
Try updating the constructor injection to the following:

```ts
@inject(UserServiceBindings.USER_REPOSITORY)
protected userRepository: UserRepository
```

**Comment by maher1719** [comment]
I updated it but still the sale issue I tried login function it said verifyCredentials is not a function, but when I use UserRepository orm methods like save() and update() it works fine

**Comment by dhmlau** [comment]
@maher1719, I can take a look at the docs and see if there's any outdated content. 
In the meanwhile, the easiest way is to review the [todo-jwt example](https://github.com/strongloop/loopback-next/tree/master/examples/todo-jwt) and compare what you have. Hope it helps.

**Comment by maher1719** [comment]
@dhmlau @achrinza thank you for the support, I started a new project, and it worked just fine. I tried to upgrade the relatively old project  I got from my team, but it didn't work. Thank you for the help...

**Comment by dhmlau** [comment]
@maher1719, that's good to hear. Please note that you can view the change logs, especially looking for the ones with breaking changes when you're upgrading to a later version of the modules. 
With this, I'm closing this issue. Thanks.

**Comment by albjeremias** [comment]
this happened to me, cause i created a model and a repository.. so it was overriding the code from authentication module

**Comment by rukeshpaudel** [comment]
@albjeremias how did you fix the issue?

**Comment by xfudox** [comment]
Still face this error with following packages, has anyone found a solution to this?

```
"dependencies": {
    "@loopback/authentication": "^9.0.6",
    "@loopback/authentication-jwt": "^0.12.6",
    "@loopback/boot": "^5.0.6",
    "@loopback/core": "^4.0.6",
    "@loopback/repository": "^5.1.1",
    "@loopback/rest": "^12.0.6",
    "@loopback/rest-explorer": "^5.0.6",
    "@loopback/service-proxy": "^5.0.6",
    "loopback-connector-mysql": "^5.4.4",
    "tslib": "^2.0.0"
  },
  "devDependencies": {
    "@loopback/build": "^9.0.6",
    "@loopback/eslint-config": "^13.0.6",
    "@loopback/testlab": "^5.0.6",
    "@types/node": "^14.18.34",
    "eslint": "^8.28.0",
    "source-map-support": "^0.5.21",
    "typescript": "~4.9.4"
  }
```

**Comment by silvio-gratani** [comment]
Forgot to mention, project scaffolded with `@loopback/cli version: 4.1.6`

**Comment by albjeremias** [comment]
> @albjeremias how did you fix the issue?

i remade the whole code using nestjs

**Comment by demiro** [comment]
> > @albjeremias how did you fix the issue?
> 
> i remade the whole code using nestjs

lol, how is this a solution :'(

I am having the similar issue... where I have already had the user model and user controllers and repositories (scaffolded using cli)...

I replaced the content of the controller with the example code and the app builds fine... but when I try to signUp I get an  error

Request POST /signup failed with status code 500. TypeError: this.userRepository.userCredentials is not a function
    at UserController.signUp (C:\DEVELOPMENT\xxx-api2\src\controllers\user.controller.ts:139:31) 
    
    Probably the best example would be with a fully fledged standalone user model and repository.... also some relations between the user and todos

**Comment by ahmed-e-elhor** [comment]
i still have this error i tried to exted the built_in user model provided by the jwt packages and it did not work

**Comment by Muhammadtawil** [comment]
anyone solve this issue !?

**Comment by r0nc0d3r** [comment]
I tried replacing `this.userRepository.userCredentials` with  `this.userCredentialsRepository` and worked for me
```js
await this.userCredentialsRepository.create({
      userId: savedUser.id,
      password,
    });
```

and this how I injected in the constructor
```js
@inject(UserServiceBindings.USER_CREDENTIALS_REPOSITORY)
protected userCredentialsRepository: UserCredentialsRepository
```

**Comment by trandung2k1** [comment]
You are define a repository same name as UserRepository inside package @loopback/authentication-jwt
