### ISSUE TITLE
findByForeignKeys improperly imposing constraint to scope

### ISSUE THREAD

**Issue by vunyunt** [strongloop/loopback-next#6968]
I discovered this issue when trying to have deep include filter in HasManyThrough relationship. The following line in `findByForeignKeys` imposes constraint onto the original scope object. When querying with deep inclusion, inclusion in any entity has all constraints from previous found entities.

```ts
  if (scope && !_.isEmpty(scope)) {
    // combine where clause to scope filter
    scope = new FilterBuilder(scope).impose({where}).filter;
    // ^ This line imposes the where filter to scope
  } else {
    scope = {where} as Filter<Target>;
  }
```

A simple _.cloneDeep solves this issue for my use case, though I'm not sure if it affects anything else.
I have made a commit with this change: https://github.com/vunyunt/loopback-next/commit/c1ae658d4e8f66a64bdd9600eef190a7c76c5e8f

## Steps to reproduce

1 - Create the following models with only `id: string` as their ids: 
`Model1, Model2, Model3, Through12, Through23`

2 - Create HasManyThrough relations as follow:
Model1 -> Model2 (through Through12)
Model2 -> Model3 (through Through23)

3 - Create and link entities in Model1, Model2, and Model3
Model1 must have multiple entities
```ts
    // Create entities
    await this.mModel1Repository.createAll([{id: 'm1_1'}, {id: 'm1_2'}]);

    // Link Model1 entities to Model2 entities
    await this.mModel1Repository.model2s('m1_1').create({id: 'm2_1'});
    await this.mModel1Repository.model2s('m1_1').create({id: 'm2_2'});
    await this.mModel1Repository.model2s('m1_2').create({id: 'm2_3'});
    await this.mModel1Repository.model2s('m1_2').create({id: 'm2_4'});

    // Link Model2 entities to Model3 entities
    await this.mModel2Repository.model3s('m2_1').create({id: 'm3_1'});
    await this.mModel2Repository.model3s('m2_2').create({id: 'm3_2'});
    await this.mModel2Repository.model3s('m2_3').create({id: 'm3_3'});
    await this.mModel2Repository.model3s('m2_4').create({id: 'm3_4'});
```

5 - Query model1 with deep inclusion filter, and print the result
```ts
    // Fetch data with deep include
    let result = await this.mModel1Repository.find({
      include: [
        {
          relation: 'model2s',
          scope: {
            include: [{relation: 'model3s'}],
          },
        },
      ],
    });

    // log
    console.dir(result);
```

## Current Behavior

console.dir prints
```ts
[
  Model1 { id: 'm1_1', model2s: [ [Model2], [Model2] ] },
  Model1 { id: 'm1_2', model2s: [] }
]
```
Note that the second entity does not have model2 instances

## Expected Behavior

Query with deep inclusion filters returns all relevant related entities. In this case, console.dir should look like:
```ts
[
  Model1 { id: 'm1_1', model2s: [ [Model2], [Model2] ] },
  Model1 { id: 'm1_2', model2s: [ [Model2], [Model2] ] }
]
```

## Link to reproduction sandbox

https://github.com/vunyunt/test-deep-include.git
Note that this is not created exactly with [this guide](https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs), as I am not sure which example application is suitable to demonstrate this.
To run this, clone the repo, run `npm install`, and then run `npm run start`
All relevant code is in `test-deep-include.observer.ts`

## Additional information

```
linux x64 12.20.0
loopback-next@0.1.0 /run/media/vun/C/vun/workspace/loopback-next
```

## Related Issues

None that I know of

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by achrinza** [comment]
Thanks for raising the issue!

It seems like #6955 (specifically, [this line](https://github.com/strongloop/loopback-next/pull/6955/files#diff-bdf40a76216a85fd324c0b4276b7453ed59db93dc8fdf7418d458021da1ec2feR42)) should solve this issue.

If possible, could you please try out that PR's branch and check if it resolves the issue?

**Comment by vunyunt** [comment]
I'll try it, thanks!

**Comment by vunyunt** [comment]
Tried it on both the test sandbox and my use case, the query now returns correctly :+1:
