### ISSUE TITLE
Put up notice about EOL of LB3 on relevant pages and packages

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#6969]
In a follow up PR of https://github.com/strongloop/loopback-next/pull/6967, we should inform our users that LB3 is not supported anymore. Some of them end up on https://loopback.io/doc/en/lb4/migration-mounting-lb3app.html and assume that's the way to keep using their existing LB3 apps.

I identified the following pages where the notice must be put.

- https://github.com/strongloop/loopback-next/tree/master/packages/booter-lb3app
- https://github.com/strongloop/loopback-next/tree/master/examples/lb3-application
- https://loopback.io/doc/en/lb4/migration-overview.html
- https://loopback.io/doc/en/lb4/migration-mounting-lb3app.html
- https://loopback.io/doc/en/lb3/index.html

**Comment by bajtos** [comment]
@hacksparrow I think this issue is a duplicate of #6957. Can you please move the list of places you identified to the check-list in #6957 and close this issue?

**Comment by hacksparrow** [comment]
Closed on favor of https://github.com/strongloop/loopback-next/issues/6957.
