### ISSUE TITLE
Scaffold an empty REST application

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#697]
## Overview

As a developer, I would like to make use of a command line tool to rapidly create my new REST application.

## Notes
- [ ] should have a blog post written **first** describing how it will work (to get public feedback)
- [ ] decide on whether or not to use yeoman (or alternatives?)
- [ ] needs documentation
- [ ] should be extensible, but does **not** need to include things like `lb model` at this time
- we should very strongly consider **not** using yeoman and depend directly on [inquirer](https://www.npmjs.com/package/inquirer) and [ejs templating](https://www.npmjs.com/package/ejs) directly. See also https://github.com/strongloop/generator-loopback/issues/139.

Related: https://github.com/strongloop/loopback-next/pull/693

**Comment by kjdelisle** [comment]
cc @bajtos 

@raymondfeng You've already done this task to some extent, right?
We still need a blog post about it, but much of the documentation already exists (in the form of changes to the previous docs).

Can you quickly tick off which items have already been done?

**Comment by raymondfeng** [comment]
With the current code in `@loopback/cli`, `lb app` command basically scaffolds a REST-enabled LB4 application with a `PingController`. On top of that, we can run `lb controller` to add new controllers. What else do you expect?

**Comment by kjdelisle** [comment]
@raymondfeng Essentially, I'm asking if this task is already done (so we can close it) :P

**Comment by raymondfeng** [comment]
I think we can close it.
