### ISSUE TITLE
Automatically call "eslint --fix" after file changes made by lb4 cli tool

### ISSUE THREAD

**Issue by grisson2** [strongloop/loopback-next#6978]
## Suggestion

Command line tool lb4 should call eslint when it apply changes to user project files.
The user may have added custom eslint rules which may generate errors with the lb4-cli tool generated syntax.
Some of them may be solved automatically so instead of forcing the user to always manually fix these errors by calling itself an eslint instance, launch a 'eslint --fix' on the changed files automatically.

## Examples

Add this rule to your .eslintrc.js:
```
"indent": ["error", 4],
```
Then generate a model using 'lb4 model'.

Eslint will complain about the generated file because the identation is  made up with 2 spaces where it expect to be 4 spaces. This particular case can be solved by calling automatically an 'eslint --fix' on the changed files.

**Comment by achrinza** [comment]
LoopBack 4 Generation commands have the `--format` option which will run the `lint:fix` NPM script.

See example:

https://loopback.io/doc/en/lb4/Model-generator.html

**Comment by grisson2** [comment]
Thanks, missed it from docs.
