### ISSUE TITLE
Spike: can we use JSON Schema instead of LDL?

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#699]
We would like to move away from our own DSL for defining models and preferably use an industry standard like JSON Schema instead.

In order to do so, we need to find if JSON Schema provides enough parity with other schemas like:

 - Protocol Buffers for gRPC transport
 - SQL for persisting our models
 - anything else?

**Comment by dhmlau** [comment]
`non-DP3` because we will still be using the legacy juggler.

**Comment by bajtos** [comment]
Cross-posting @raymondfeng's https://github.com/strongloop/loopback-next/issues/118#issuecomment-401469475 as it may be relevant:

> However, @raymondfeng, our architect, has a different opinion. IIRC, he is proposing a slightly different implementation, where LoopBack internally uses some custom format, and then allows 3rd party plugins to provide converters from from different DSLs into this internal LoopBack format. In other words, JSON Schema would become only one of the supported ways how to define models. @raymondfeng could you please confirm whether I described your ideas correctly?

There are JSON-schema like languages to define models:

- Swagger 2.0 definitions
- OpenAPI 3.0 schemas
- JSON Schema
- GraphQL schema
- LoopBack 3.x DSL

The JSON-schema itself can only be used define the `typing` perspective of models. LoopBack often requires additional metadata, such as `mapping` to database schemas and JSON serialization on the wire.

**Comment by bajtos** [comment]
Closing as rejected based on my comment above.
