### ISSUE TITLE
Modular design: extensibility and pluggability

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#7]
- LoopBack runtime consists of multiple modules
- LoopBack should have a well-defined way to declare extension points and extensions to provide extensibility/pluggability
- Should we explore dependency injection?
- What is the packaging model for extensions (components/plugins)?
   - https://code.visualstudio.com/docs/extensions/overview

**Comment by ritch** [comment]
https://github.com/strongloop-internal/scrum-asteroid/issues/125
