### ISSUE TITLE
Helper converting Model definitions to Swagger/OpenAPI schemas

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#700]
In our [Todo model example](https://github.com/strongloop/loopback4-example-getting-started/blob/83c9423baadfad42242446e96a3d68ffa7403d01/src/models/todo.model.ts), we are duplicating information about model properties - first time in Model definition, second time in Swagger (OpenAPI) Schema.

We should have a helper function that can create Swagger/OpenAPI Schema from the Model data.

## Acceptance criteria

 - [ ] A blog post explaining how to use this new helper, maybe how is it built internally?
 - [ ] The implementation (including tests, etc.)
 - [ ] Documentation (including API docs)

**Comment by bajtos** [comment]
A thing to figure out: which version to support - Swagger (v2) or OpenAPI (v3) or both? This is related to https://github.com/strongloop/loopback-next/issues/182

**Comment by M-jerez** [comment]
Hi,

This probably has been discussed before, but I would go the other way around, I would define the models using the Swagger/OpenAPI schema, and generate TS interface/class to extend/implement.
This would allow for much better tooling for models creation/edition without coding requirements (thinking on CRM-CMS) and still 

Please ignore this message if this has been already discussed.

**Comment by jannyHou** [comment]
I kind of agree with @M-jerez, I would expect this helper tool give developers the flexibility to convert a Swagger style schema to any format of Model definition: either the official ModelDef style in LoopBack 4(which may change in the future) or any ModelDef flavour the users like.

But IMO one of our goals is relieving users from writing Swagger schema: they define LB style model and the Swagger schema will be auto-generated accordingly and be consumed by controller(@api, or apiDef annotations).

So I propose make the tool be able to convert from both directions:
SwaggerSchema <---> ModelDef

writing more about details, will update later...

**Comment by bajtos** [comment]
Hello @M-jerez, thank you for your comment, your request make a lot of sense to me! It's out of scope of this particular issue, but I believe we have it already covered by https://github.com/strongloop/loopback-next/issues/725. I'll cross-post your comment there for posterity.

**Comment by bajtos** [comment]
Closing in favor of https://github.com/strongloop/loopback-next/issues/786
