### ISSUE TITLE
API DOCS links discrepancy betwee LB4 top and side menus

### ISSUE THREAD

**Issue by NorthDecoder** [strongloop/loopback-next#7010]
![loopback4-api-docs](https://user-images.githubusercontent.com/9598008/104221153-61edcf00-53f5-11eb-9927-1a6467ab57a5.png)

## Steps to reproduce
Browse to [https://loopback.io/doc/en/lb4/index.html](https://loopback.io/doc/en/lb4/index.html)
* Note in the top menu bar that the link to API DOCS resolves to the loopback3 documentation [http://apidocs.loopback.io/](http://apidocs.loopback.io/)
* Then in the left sidebar note that the link  connects to [https://loopback.io/doc/en/lb4/apidocs.index.html](https://loopback.io/doc/en/lb4/apidocs.index.html)

## Current Behavior
same as above

## Expected Behavior
While viewing  the LB4 docs expected to be directed to LB4 API link.

## Link to reproduction sandbox
N/A

## Additional information
N/A

## Related Issues
N/A

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@NorthDecoder, thanks for reporting this. The top menu of the page you've shown is shared between LoopBack 3 and LoopBack 4, so it was showing the LoopBack 3 API docs as the default content. With LB3 EOL, let me submit a PR to update the link.
