### ISSUE TITLE
Angular5 SDK

### ISSUE THREAD

**Issue by HaiderMalik12** [strongloop/loopback-next#702]
# Description/Steps to reproduce
I want to add a new feature request for you. You have mentioned that you are going to create an SDK for React. 
Please, add the Angular5 SDK to the loopback v4.

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by aharbis** [comment]
We currently maintain our own SDK generator for our Angular front-end in LB3. It would be excellent to have a LB SDK generator for Angular. Though, I think the title of this issue could drop the `5` in hopes of staying current with Angular. Right now we are actually on Angular 6 and looking to move to 7 ASAP.

**Comment by collaorodrigo7** [comment]
I also think this would be a nice feature. Do you guys think this is something we can suggest in #1920  ??

**Comment by derdiggn** [comment]
Have a look at https://github.com/OpenAPITools/openapi-generator.

It can generate a loot of clients based on you openapi specs.

I use this for angular 7 projects

**Comment by jgwinner** [comment]
Looks interesting, although I got a ton of errors when I ran it; admitedly, it's an LB3 project (need those ACL's), but still?

```
>openapi-generator generate -i myapi.yaml -o out -g typescript-angular
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via valida
c (CLI).
 | Error count: 99, Warning count: 1
Errors:
        -attribute paths.'/MyFile1s/{id}'(put).[data].description is unexpected
        -attribute paths.'/MyFile2s'(post).[data].description is unexpected
        -attribute paths.'/MyFile2s/upsertWithWhere'(post).[data].description is unexpected
etc. Basically every API in the server.
```

Have you run into this? I haven't dug into it much, honestly.
