### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by ratheeshrajendran** [strongloop/loopback-next#7022]
Push notifications features are not available in loopback 4 now , when it will be added any plan for that?

**Comment by achrinza** [comment]
Narrowed the scope to push notifications only as #4854 already covers storage component.

**Comment by dhmlau** [comment]
There's a community extension for push notification: https://www.npmjs.com/package/loopback4-notifications. You might want to evaluate and see if it fits your needs. Thanks.

**Comment by dhmlau** [comment]
@ratheeshrajendran, we believe your question is answered. Closing this issue. Thanks.
