### ISSUE TITLE
Broken link in docs - "Migrating authentication and authorization"

### ISSUE THREAD

**Issue by style2joy** [strongloop/loopback-next#7023]
Broken link: https://loopback.io/doc/en/lb4/built-in.md in following para on https://loopback.io/doc/en/lb4/migration-auth-overview.html

> A set of built-in models like User, AccessToken and ACL makes it easy to store your user credentials locally and define custom access control checks. The migration path is described in _[Migrating built-in authentication and authorization](https://loopback.io/doc/en/lb4/built-in.md)_.

**Comment by dhmlau** [comment]
@style2joy, thanks for reporting this. We probably missed it when doing some refactoring on this portion of the docs. Would you like to submit a PR? 

The source of the docs page is https://github.com/strongloop/loopback-next/blob/master/docs/site/migration/auth/overview.md. And here is the instruction of submit a PR in LB4 in case you're not familiar with our process: https://loopback.io/doc/en/lb4/submitting_a_pr.html. Thanks!

**Comment by pktippa** [comment]
@dhmlau I have submitted the PR #7056
