### ISSUE TITLE
Using glob in boot options to specify controller path doesn't work

### ISSUE THREAD

**Issue by moshe-shaham-intel** [strongloop/loopback-next#7027]
## Steps to reproduce

1. in `application.ts` enter the glob pattern:
```
    this.bootOptions = {
      controllers: {
        // Customize ControllerBooter Conventions here
        dirs: ['controllers'],
        extensions: ['.controller.js'],
        nested: true,
        glob: "**/*.controller.js"
      },
    };
```

2. When running `npm start` there is a fatal error, complaining that ping.controller was not found:
`Cannot start the application. Error: Cannot find module 'dist/controllers/ping.controller.js'
`
## Current Behavior

When I specify glob, I get an error that a required controller was not found

## Expected Behavior

I expect the glob pattern to work

**Comment by dhmlau** [comment]
@moshe-shaham-intel, I've tried with the following (please note the extra `/` at the beginning) and it seemed to be working for me. Could you please try?
`glob: "/**/*.controller.js"`

**Comment by achrinza** [comment]
FYI, setting `glob` will override and [take precedence over the other options](https://loopback.io/doc/en/lb4/Booting-an-Application.html#controller-booter).

**Comment by dhmlau** [comment]
Closing as resolved.
