### ISSUE TITLE
Any example for how to use refresh token with JWT

### ISSUE THREAD

**Issue by Mohammedalasaad** [strongloop/loopback-next#7076]
> **Maintainers' note**
>  This question has been posted elsewhere:
> - https://loopbackio.slack.com/archives/C01177XQN8N/p1611841714121200

Hi,
Is there any example to use Refresh token with JWT. I have already model called refresh_token that has user_id, refresh_token and all was working.. but after update expiresIn not coming with the response object.

I know there is example here about jwt todo-jwt but it does not have refresh_token
https://github.com/strongloop/loopback-next/tree/master/examples/todo-jwt

any help, thanks

**Comment by Mohammedalasaad** [comment]
I have created an example here.. And he we can see an error. I have bound the jwt service but its still using the core one not ur custom code "btw, this happen after latest update"
and I have fixed the expiresIn in manual way as you see it there in user.controller.ts not sure if this good way!

`    tokens.expiresIn = TokenServiceConstants.TOKEN_EXPIRES_IN_VALUE // Return expiresIn with object
`
Code is here
https://github.com/Mohammedalasaad/Loopback-JWT

**Comment by jannyHou** [comment]
Hey @Mohammedalasaad, you can try binding your services after mounting the components:
move https://github.com/Mohammedalasaad/Loopback-JWT/blob/master/src/application.ts#L29-L32 to be after https://github.com/Mohammedalasaad/Loopback-JWT/blob/master/src/application.ts#L39

I think your binds are overridden by the component.

**Comment by Mohammedalasaad** [comment]
Thank you so much @jannyHou.. it works so good.. I will fix my code and push it. so maybe will help someone else if they need kind of this start with jwt :)

**Comment by dhmlau** [comment]
Closing this issue as resolved. Thanks!
