### ISSUE TITLE
Argument of type '(Target & TargetRelations)[]' is not assignable to parameter of type 'never'

### ISSUE THREAD

**Issue by sergki1** [strongloop/loopback-next#7077]
## Steps to reproduce

npm start with has many in model:

 @hasMany(() => AppRestriction, { keyTo: 'app_id', name: 'appRestrictions'})
  app_restrictions: AppRestriction[];

## Current Behavior

Got an error:

node_modules/@loopback/repository/src/relations/has-many/has-many-through.inclusion-resolver.ts:122:21 - error TS2345: Argument of type '(Target & TargetRelations)[]' is not assignable to parameter of type 'never'.

122         result.push(targetEntityList);
                        ~~~~~~~~~~~~~~~~

node_modules/@loopback/repository/src/relations/has-many/has-many-through.inclusion-resolver.ts:125:21 - error TS2345: Argument of type 'undefined' is not assignable to parameter of type 'never'.

125         result.push(entityList);
                        ~~~~~~~~~~


## Expected Behavior

Run without error

## Link to reproduction sandbox


## Additional information

Fix modify file:
line 105 of node_modules/@loopback/repository/src/relations/has-many/has-many-through.inclusion-resolver.ts
From:
const result = [];
To:
const result = [] as any; 
Or to:
const result = Array(); 

## Related Issues

<!-- Did you find other bugs that looked similar? -->

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by achrinza** [comment]
Could you please provide a GitHub repo with a reproduction sandbox? That would make it easier to replicate the issue and better understand the underlying problem.

**Comment by sergki1** [comment]
I found the problem, removing this line from another class:
`import {ensurePromise} from "@loopback/repository/src/repositories/legacy-juggler-bridge";`
solved the problem of the compilation.

But if your are checking the class in this file:
node_modules/@loopback/repository/src/relations/has-many/has-many-through.inclusion-resolver.ts

it's still making 2 errors TS2345 as described in the Current Behavior

**Comment by abdoulayesy** [comment]
Hello a got the same problem after run lb4 update.

node_modules/@loopback/repository/src/relations/has-many/has-many-through.inclusion-resolver.ts:122:21 - error TS2345: Argument of type '(Target & TargetRelations)[]' is not assignable to parameter of type 'never'.

122         result.push(targetEntityList);
                        ~~~~~~~~~~~~~~~~

node_modules/@loopback/repository/src/relations/has-many/has-many-through.inclusion-resolver.ts:125:21 - error TS2345: Argument of type 'undefined' is not assignable to parameter of type 'never'.

125         result.push(entityList);

**Comment by abdoulayesy** [comment]
any idea ?
