### ISSUE TITLE
lb4 app - Fails on npm start when repository service is not chosen when creating 

### ISSUE THREAD

**Issue by vairakkumar-vairaperumal** [strongloop/loopback-next#7080]
## Steps to reproduce

1. lb4 app
2. uncheck repositories
3. npm start

## Current Behavior
Receive error on migrate.ts
```
src/migrate.ts:9:13 - error TS2339: Property 'migrateSchema' does not exist on type 'MyAppApplication'.
9   await app.migrateSchema({existingSchema});
              ~~~~~~~~~~~~~
```

## Expected Behavior
1. app runs successfully with no additional change.

## Additional information

linux x64 10.23.2
+-- @loopback/boot@3.2.0
+-- @loopback/core@2.14.0
+-- @loopback/rest@9.1.2
+-- @loopback/rest-explorer@3.0.6
+-- @loopback/service-proxy@3.0.6

## Related Issues

Receiving same error as here: https://github.com/strongloop/loopback-next/issues/5608

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by pktippa** [comment]
@achrinza I would like to work on this issue, please guide me with few tips in right path to solve
