### ISSUE TITLE
Extension: MQTT

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#710]
# Description/Steps to reproduce

| Extension        | Descriptions           | Developers  |  LB4 Maintainer
| ------------- |:-------------:| -----:|-----:|
| MQTT | MQTT Transport |  @akashjarad, @Negrero | TBD |
|       |      |    ||

# Repo
https://github.com/strongloop/loopback4-extension-mqtt

# Additional information
This is originated from Call for Contribution on LB Extensions [issue](https://github.com/strongloop/loopback-next/issues/647).

**Comment by dhmlau** [comment]
From @bajtos 
> @akashjarad awesome! I added you to the table at the top, created https://github.com/strongloop/loopback4-extension-mqtt and gave you write permissions to that repository.

> I am afraid we don't have the documentation for server/transport authors ready yet, but see the following resources for help:

> https://github.com/strongloop/loopback4-extension-starter for basic project setup
strongloop/loopback4-extension-grpc#8 for an example of a custom transport
https://github.com/strongloop/loopback-next/tree/master/packages/rest for a pretty complete implementation of REST transport

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback4-extension-mqtt/pull/2

**Comment by Miced** [comment]
What is this extension's progress? It seems quite stale so far.

**Comment by juleskreutzer** [comment]
@Nosfistis I also needed to use this extension for my current project and probably other loopback projects in the future. We decided to create our own extension. If you need to, you can use it: https://www.npmjs.com/package/lb4-extension-mqtt (https://github.com/juleskreutzer/lb4-extension-mqtt#readme)

A manual will be added in the next few days, or just open an issue if you need some help ;)

**Comment by dhmlau** [comment]
@juleskreutzer , thanks for sharing!
