### ISSUE TITLE
Changes in Typescript 4.2 break usage of EntityCrudRepository and others

### ISSUE THREAD

**Issue by bradharms** [strongloop/loopback-next#7118]
## Steps to reproduce

- Upgrade project to typescript 4.2
- Create an instance of `DefaultCrudRepository`
- Try to create an new instance of `repository.entityClass`
- Type error will occur:

```typescript
const entity = new repository.entityClass();
// Cannot create an instance of an abstract class.ts(2511)
```

## Current Behavior

TypeScript 4.2 changed the way the compiler handles classes marked as `abstract`, which affects most notably certain places where `Entity` and `EntityCrudRepository` are used. This is because anywhere that an expression was typed as `typeof Entity` or `typeof Entity & { prototype: Entity }`, that expression is now implicitly marked as `abstract`, which means it is not valid to be used in any position where an `abstract` class constructor isn't explicitly allowed. 

## Expected Behavior

It's not clear whose responsibility it is to resolve this issue. I don't know whether something must change in the Loopback type definitions or in the user's code. Likely it's going to be some of each.

**Comment by raymondfeng** [comment]
See #7108
