### ISSUE TITLE
Activate discussion tab in Github

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#7136]
## Suggestion

I suggest activating the GitHub discussion tab so that users arrive there and that they do not create issues
![Screenshot 2021-03-01 at 07 12 44](https://user-images.githubusercontent.com/13822438/110033326-8ac97b00-7d39-11eb-87a3-16221ca3bff5.png)

**Comment by dhmlau** [comment]
@frbuceta, thanks for bringing this up. I didn't realize there's a discussion tab in GitHub. Just curious... how would it differ from Slack? I understand there's less friction to use GitHub discussion than Slack since it's the same platform.

**Comment by frbuceta** [comment]
The point that I see the most favorable is that in Slack it is impossible for a person to have access to a discussion that has already been resolved and can help them, in GitHub the topic would always be registered.

**Comment by frbuceta** [comment]
> I agree we should enable GitHub Discussions. As part of that change, I think we should create some basic structure in the new forum and also update our issue templates to point people to Discussions if they want to ask a question or discuss things that are not actionable yet.

I can take care of it if you want

**Comment by bajtos** [comment]
> I can take care of it if you want

Awesome, thank you for the offer @frbuceta!

I enabled the Discussions feature for this repo. They offer the following link to set things up:

https://github.com/strongloop/loopback-next/discussions/new?category=general&welcome_text=true

In case that link does not work for you, here is a screenshot:

<img width="873" alt="Screen Shot 2021-03-10 at 17 27 18" src="https://user-images.githubusercontent.com/1140553/110662531-e2e30000-81c5-11eb-8484-e90d914d519f.png">

And the full text:

```md
<!--
    ✏️ Optional: Customize the content below to let your community know what you intend to use Discussions for.
-->
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

<!--
  For the maintainers, here are some tips 💡 for getting started with Discussions. We'll leave these in Markdown comments for now, but feel free to take out the comments for all maintainers to see.

  📢 **Announce to your community** that Discussions is available! Go ahead and send that tweet, post, or link it from the website to drive traffic here.

  🔗 If you use issue templates, **link any relevant issue templates** such as questions and community conversations to Discussions. Declutter your issues by driving community content to where they belong in Discussions. If you need help, here's a [link to the documentation](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser).

  ➡️ You can **convert issues to discussions** either individually or bulk by labels. Looking at you, issues labeled “question” or “discussion”.
-->
```

**Comment by bajtos** [comment]
We may want to tweak the categories, I think it would be best to start a new Discussion thread to discuss with other maintainers and even the wider community.

**Comment by bajtos** [comment]
I created the "Welcome" discussion topic in https://github.com/strongloop/loopback-next/discussions/7155 and pinned it to the home page.

I also created a new category "LB3 Migration" for Q&A around migration.

Next steps:

- [x] Promote Discussion in our Slack (`#general`) - see https://loopbackio.slack.com/archives/CE8CRBBFU/p1615445989005600
- [x] Open a PR to update "New issue" template(s) - https://groups.google.com/g/loopbackjs/c/aqziD5i2IgY
- [x] Post a message to our mailing list - https://groups.google.com/g/loopbackjs/c/aqziD5i2IgY
- [ ] Promote the change on Social Media - @dhmlau can you please take care of this yourself?

**Comment by frbuceta** [comment]
Close as Done
