### ISSUE TITLE
CLI Epic - MVP

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#721]
## Epic

As a loopback4 user, I would like a command-line toolkit so that I can rapidly generate applications,
commonly used artifacts and more.

**Comment by bajtos** [comment]
I'd like us to implement the CLI in incremental baby steps. For MVP, start with CLI and templates that are mostly static and support only the MVP app that's our target (using legacy juggler, etc.) Later, we can expand templates (and CLI options) to support more flavours - e.g. different ORMs, etc.

To preserve backwards compatibility for people who have a project that was scaffolded with an older version of the toolkit, we should store necessary information in the project (either in package.json or in a standalone file, see e.g. [.yo-rc.json](http://yeoman.io/authoring/storage.html)). Few examples of information to store there: what version of CLI toolkit created the project, what kind of project this is (extension vs. API server), what ORM framework is used, etc. However, this config is out of scope of MVP - see #759. To keep things simple, we will assume that "no config" = "MVP version".

cc @kjdelisle I hope I captured all important points from our discussion, please let me know if there is anything missing or needing additional clarification.

**Comment by bajtos** [comment]
Closing as done. Hooray 🎉
