### ISSUE TITLE
[CLI] Generate Controller with CRUD methods

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#727]
## Story

As a loopback4 user, I would like to run a CLI command to generate a default set of CRUD API methods based on a model and its associated datasource(s) so that I can avoid hand-writing each of these functions manually.

## Acceptance Criteria
- [x] Prompt for controller name
- [x] Validate controller name
- [x] Prompt for whether or not they want to use the RestCrudController base template
- [x] If RestCrudController:
  - Generate new class that extends this type (should be a very small template!)
```ts
    async create(obj: T) : Promise<T>
    count(where: Where) : Promise<number>
    find(filter: Filter) : Promise<T[]>
    updateAll(where: Where, obj: T) : Promise<number>
    deleteAll(where: Where): Promise<number>

    findById(id: ID) :  Promise<T>
    updateById(id: ID, obj: T) :  Promise<boolean>
    deleteById(id: ID) :  Promise<boolean>
```
- else
  - Fall back to generating an empty controller
- [x] Document this feature on loopback.io
- [x] Release the CLI package
- [x] Write a blog post about how awesome this new feature is and how to use it.

**Comment by bajtos** [comment]
As far as this story is concerned, it's ok return `200` from the create (`POST`) method.

**Comment by bajtos** [comment]
As far as this story is concerned, it's ok return `200` from the create (`POST`) method (but see https://github.com/strongloop/loopback-next/issues/788).

**Comment by kjdelisle** [comment]
Blog post will go out on Thursday. Closing as complete.

**Comment by bajtos** [comment]
@kjdelisle I just realised that our documentation added by https://github.com/strongloop/loopback.io/pull/583 is missing an important piece of information: how is the generator discovering models and repositories in the project? What conventions does it require to work correctly?
