### ISSUE TITLE
npm start ---> Error: Cannot find module 'C:\Users\userName\@loopback\build\bin\run-clean.js'

### ISSUE THREAD

**Issue by emazzu** [strongloop/loopback-next#7272]
## Steps to reproduce

npm start

## Current Behavior

Error: Cannot find module 'C:\Users\xmazzuce\@loopback\build\bin\run-clean.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

## Additional information

Error: Cannot find module 'C:\Users\xmazzuce\@loopback\build\bin\run-clean.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prueba01@0.0.1 clean: `lb-clean dist *.tsbuildinfo .eslintcache`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prueba01@0.0.1 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xmazzuce\AppData\Roaming\npm-cache\_logs\2021-03-16T00_46_40_724Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prueba01@0.0.1 rebuild: `npm run clean && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prueba01@0.0.1 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xmazzuce\AppData\Roaming\npm-cache\_logs\2021-03-16T00_46_40_776Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prueba01@0.0.1 prestart: `npm run rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prueba01@0.0.1 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xmazzuce\AppData\Roaming\npm-cache\_logs\2021-03-16T00_46_40_827Z-debug.log

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by emazzu** [comment]
add information
C:\Users\xmazzuce\OneDrive - Sinopec Argentina Exploration & Production Inc\Documents\LB4\app>node --version && npm --version && lb4 -v | find "cli"
v14.16.0
6.14.11
@loopback/cli version: 2.19.0

**Comment by dougal83** [comment]
@emazzu Could you try `npm ls --prod --depth 0` and see what is installed?  If nothing is returned then try `npm install` then retry `npm start`.  The install process should be called by the cli when bootstrapping a new app by using the `lb4 app` command.

**Comment by emazzu** [comment]
@dougal83 
hi, how are you ? 

I have all installed. @loopback/cli, global
and app01 with lb4 app01

when i run npm ls --prod --depth 0, it return

+-- @loopback/boot@3.2.1
+-- @loopback/core@2.14.1
+-- @loopback/repository@3.4.1
+-- @loopback/rest@9.1.3
+-- @loopback/rest-explorer@3.1.0
+-- @loopback/service-proxy@3.0.7
`-- tslib@2.1.0

I don't understand what happens, i dont find the problem.

**Comment by emazzu** [comment]
here, i have the first problem, the run-clean.js, is here, and the message that cannot found is an another forder. 
C:\Users\xmazzuce\OneDrive - Sinopec Argentina Exploration & Production Inc\Documents\LB4\app01\node_modules\@loopback\build\bin

Error: Cannot find module 'C:\Users\xmazzuce\@loopback\build\bin\run-clean.js'

**Comment by dougal83** [comment]
Hey @emazzu, all good here just getting back into some programming myself.

Hmm, perhaps you could try deleting the local `node_modules` folder and retry `npm install` & `npm start` commands.  Other than that I've had some weird behaviour if there are any `node_modules` folders erroneously existing in parent folders.

Out of curiosity, could you try creating and running an lb4 app from `C:\testfolder\`.  Perhaps the path length is causing and issue... I've run into that on windows.  For the record... I eventually fired up a linux VM for node as windows can have little quirks that are hard to diagnose.

**Comment by emazzu** [comment]
I have resolved, 
The problem was, that I have installed loopback3 in the same machine. 
When I try install loopback 4 in the new VM on windows 10, it works good.

Thank you very much !!!!
