### ISSUE TITLE
[Docs] Garden path tutorial (bottom-up approach)

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#729]
## Story

As a LoopBack4 user, I would like an easy to follow and intuitive tutorial which shows me how to make a starter To-Do app like Angular's Tour of Heroes.

**This tutorial will be a bottom-up approach tutorial.**

See also #735 

## Acceptance Criteria
- [x] Migrate the step-by-step guide on strongloop/loopback4-example-getting-started to a section called Tutorial for v4 on loopback.io
  - [x] Add an introduction explaining what application the user will be building (Todo)
  - [x] Add explanations at each phase of the tutorial for what the user is currently creating (if it's not already there)
- [x] Hallway-usability-test this on people (devs) and gather feedback
- [x] Blog post

**Comment by bajtos** [comment]
We already have a Todo application implemented here: https://github.com/strongloop/loopback4-example-getting-started

I agree it makes sense to write a tutorial showing new LB4 developers how easy it is to write such app.

**Comment by kjdelisle** [comment]
Currently blocked on question of approach; will we change our tutorial names and site layout, or will we keep it the same?

**Comment by shimks** [comment]
Does anyone know whether this item is done or not?

**Comment by shimks** [comment]
@strongloop/lb-next-dev ping

**Comment by dhmlau** [comment]
From my understanding, the work is done, we just need to wait for the the doc monorepo work to be finished then we can land.  But @b-admike and @virkt25 probably know better.

**Comment by virkt25** [comment]
- Hallway usability testing (this can happen now)
- Blog -- Will be a part of the Month end blog post instead of a dedicated blog post.

Blocked on https://github.com/strongloop/loopback.io/pull/643 

- Once that lands, we need to make the tutorial visible on LoopBack.io

**Comment by virkt25** [comment]
Blog to be published Tuesday. Closing this as completed.
