### ISSUE TITLE
[Docs] Sidebar reorganization

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#731]
## Story

As a LoopBack4 user, I would like an intuitive sidebar which has clear flow in the order of contents.

**NOTE**: Make sure we use official `LoopBack` name throughout our sidebar and documentation (don't use Loopback, or loopback, or loopBack).

## Acceptance Criteria
- Organize it so that it goes from fundamentals concepts/tutorials to advanced usage/tutorials
  - [ ] Move `loopback4-example-log-extension` reference from Getting Started section to Extending LoopBack 4 section
  - [x] Move FAQ section into its own sidebar root item
- [ ] Split the docs into sections geared towards application developers' vs extension developers' sections
  - [ ] Reorganize the sidebar contents for application developers in a way that follows the typical developer experience
  - For the extension developers, include the following in the `Extending LoopBack 4` section:
    - [ ] Move the `Language-related Concepts` section here
    - For each concepts, 
      - [ ] section on what the concept is
      - [ ] section on how to implement it
      - [ ] section onhow it'd be consumed for extension users
 - [ ] Re-write Key concepts for application developers vs extension developers

**Comment by shimks** [comment]
I no longer think this task is MVP with the reason being that a lot of pages in the docs seem sub-par for the purpose that they're trying to serve: to provide a reference for the users to use loopback4 to build their application.

To me, it's pointless to restructure the docs with existing pages to fit a narrative when the pages themselves haven't been written to fit the narrative.

I personally feel that this issue should be closed and that a new issue be made to entirely restructure the docs akin to Angular or loopback3. My problem largely lies with `Key concepts` since the pages in them are rather poorly organized and read like boring textbooks.

Curious to hear what other thinks about this issue.

**Comment by shimks** [comment]
^^^ @strongloop/lb-next-dev

**Comment by dhmlau** [comment]
+1 for no need to restructure the current docs.
What stands out is the Mixin page under the Language-related concept.  We could either put it as low priority for MVP or remove from this release.

**Comment by shimks** [comment]
The last bullet in the criteria isn't done, and I personally think it shouldn't be done anymore. All other points look to be done, but my opinion is that we close this issue

**Comment by dhmlau** [comment]
Looking at the unchecked boxes in the Acceptance Criteria section: 
- Move loopback4-example-log-extension reference from Getting Started section to Extending LoopBack 4 section
   - there is a link to the log-extension under `Extending LB4`: http://loopback.io/doc/en/lb4/Extending-LoopBack-4.html#learn-from-existing-ones.  If there's outstanding work, it will just remove from the `Examples and tutorials` list: http://loopback.io/doc/en/lb4/Examples-and-tutorials.html
- Reorganize the sidebar contents for application developers in a way that follows the typical developer experience
   - i think it looks fine now? 
- Move the Language-related Concepts section here (under Extending L4)
For each concepts,
 section on what the concept is
 section on how to implement it
 section onhow it'd be consumed for extension users
   - we've removed this section all together. i assume there's no outstanding work needs to be done?  - Re-write Key concepts for application developers vs extension developers
   - not sure what we want to do here. 

@strongloop/lb-next-dev , thoughts?

**Comment by b-admike** [comment]
+1 to closing this issue as the narrative we are trying to portray here is not compatible with the content we have currently. But we should keep this in mind if we'd like to re-structure the docs in the way proposed in this ticket for the future.

**Comment by dhmlau** [comment]
Closing as it's no longer relevant.
