### ISSUE TITLE
[Docs] Simple hello world app tutorial

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#732]
## Story

As a LoopBack4 user, I would like an easy to follow and intuitive tutorial which shows me how to make a simple hello world application. Possibly change http://loopback.io/doc/en/lb4/Getting-started.html!

## Acceptance Criteria
TBD

**Comment by bajtos** [comment]
@b-admike IMO the page http://loopback.io/doc/en/lb4/Getting-started.html is exactly the tutorial you are looking for. What kind of changes would you like to make in that page?

**Comment by dhmlau** [comment]
@b-admike , i believe this ticket was created when we were defining what to put in for `MVP`.  I agree with @bajtos  that we've already covered that in getting started.

**Comment by b-admike** [comment]
Sorry I might have missed this notification, but yeah we are good in this front.
