### ISSUE TITLE
[Docs] Extension developer's guide (how to create an extension)

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#733]
## Story

As a LoopBack4 user, I would like an easy to follow and intuitive guide which shows me the steps I can take to create an extension for the framework.

## Acceptance Criteria
TBD

**Comment by bajtos** [comment]
@b-admike is this still relevant? We already have http://loopback.io/doc/en/lb4/Extending-LoopBack-4.html and http://loopback.io/doc/en/lb4/Creating-components.html. What specifically are you missing in those documents?

I am removing this issue from MVP.

**Comment by raymondfeng** [comment]
Close this issue as we already have a guide for extension developers.
