### ISSUE TITLE
Calling a service when the application starts

### ISSUE THREAD

**Issue by govea** [strongloop/loopback-next#7331]
What's the best way to call a service method when the application starts?

I have some business logic defined in a service that I need to execute at startup. 

In `application.ts`, in the start method, you can `app.getRepository` and 
[this comment](https://github.com/strongloop/loopback-next/issues/2699#issuecomment-480678870) from issue [#2699](https://github.com/strongloop/loopback-next/issues/2699) shows how to get a controller too, but how about a service?

Is it possible to call a service directly? Or do I need to do it via a controller?

```
export class SchedulerApplication extends BootMixin(ServiceMixin(RepositoryMixin(Application))) {
  // ...  
  async start(): Promise<void> {
     const repo : MyRepository = await app.getRepository<MyRepository>(MyRepository); 
     const myController = await app.get<MyController>('controllers.MyController');
  
     // how can you get ahold of a service when the app starts?
     const myService = await app.get<MyService>('services.MyService'); // "MyService refers to a value, but is being used as a type here"
  }
}
```

**Comment by raymondfeng** [comment]
You can simply use https://loopback.io/doc/en/lb4/Life-cycle.html.

**Comment by raymondfeng** [comment]
In your code, where and how is MyService defined? The typescript code expects a type.

**Comment by govea** [comment]
I'll look into [https://loopback.io/doc/en/lb4/Life-cycle.html](https://loopback.io/doc/en/lb4/Life-cycle.html), thanks. 

MyService is defined as a class and it is registered in the application.

```
@bind({scope: BindingScope.TRANSIENT})
export class SchedulerService {
```

```
export class MyApplication extends BootMixin(ServiceMixin(RepositoryMixin(Application))) {
  constructor(){
     // ...
     this.service(MyService);
```

**Comment by raymondfeng** [comment]
If you import `MyService` correctly, you should be able to use `this.get<MyService>(...)` in application's `start()`.

**Comment by govea** [comment]
The LifeCycleObserver is going to do the trick. I noticed you can inject both repositories and services on it. Thanks @raymondfeng!

```
@lifeCycleObserver('')
export class StartUpObserver implements LifeCycleObserver {

  constructor(
    @repository(MyRepository) protected repo: MyRepository,
    @service(MyService) protected service: MyService,
  ) {}
```
