### ISSUE TITLE
[Docs] Top-down (swagger gen) app tutorial

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#734]
## Story

As a LoopBack4 user, I would like an easy to follow and intuitive tutorial which shows me how to make a LB4 app using a top-down approach, where I start with a swagger definition.

## Acceptance Criteria
TBD

**Comment by bajtos** [comment]
Top-down approach is out of scope of MVP.

**Comment by dhmlau** [comment]
related to #725

**Comment by dhmlau** [comment]
@strongloop/sq-lb-apex @bajtos @raymondfeng @hacksparrow, now that we have `lb4 openapi` command and the docs page https://loopback.io/doc/en/lb4/OpenAPI-generator.html.  I'm thinking we can close this task as done.  What do you think? 

The blog post from @raymondfeng (https://strongloop.com/strongblog/loopback4-openapi-cli/) covers this topic more in depth and contains more examples.  If you think the current docs is not sufficient, we can move some of the content in that blog to our documentation as well.

**Comment by jannyHou** [comment]
I am good to close this issue, or add a section for "api definition first approach" under the "Best Practice" 
https://loopback.io/doc/en/lb4/Best-practices.html.
Mention that with a lb4 app, users can generate artifacts from an existing OpenAPI spec file, then point to the generator page and blog.

**Comment by bajtos** [comment]
Please note that top-down approach is not about taking an OpenAPI spec file and generating TS code with `@get` and `@param` decorators. In the top-down approach, the OpenAPI spec is the source of truth about the operations and their parameters. The TypeScript code is providing only implementation of the individual endpoints, using OAI extensions like `x-controller-name` and `x-method-name` to link endpoints with controller methods.

The problem of the `lb4 openapi` approach is that when the OpenAPI spec file changes, there is no easy way how to apply those changes to the generated code.
