### ISSUE TITLE
[Docs] Polish docs for bottom-up approach

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#735]
## Story

As a LoopBack4 user, I would like an easy to follow and intuitive tutorial which shows me how to make a LB4 app using TypeScript model definitions, decorators, and API spec fragments.

We already have a tutorial repository in https://github.com/strongloop/loopback4-example-getting-started, now we need to expose it in our docs on loopback.io.

See also #729

## Acceptance Criteria
 
 - [x] Rename http://loopback.io/doc/en/lb4/Defining-and-validating-the-API.html to something like "Define your API top-down way"
 - [x] Add a new page at the same level, something like "Define your API bottom-up way". Explain basic concepts (controller decorators like `@post`, `@param` etc.) and point people to example-getting-started as the tutorial.
 - [x] Add a note to both top-down and bottom-up pages pointing readers to each other, mentioning that both approaches are valid and fully supported by LoopBack.
 - [x] In http://loopback.io/doc/en/lb4/Examples-and-tutorials.html, update the description for example-getting-started to make it clear the example is showing bottom-up approach.

**Comment by dhmlau** [comment]
related to: #988

**Comment by dhmlau** [comment]
@shimks @virkt25 , seems like all the checkboxes are checked.  Is this task done?  If so, could you please close it and update the March milestone as well? #937   Thanks!
