### ISSUE TITLE
[Docs] Docs for each module (hoist module READMEs into docs)

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#736]
## Story

As a LoopBack4 user, I would like all the info on loopback-next packages' READMEs to be available on loopback.io.

## Acceptance Criteria
TBD but here are some pointers
Docs for each module (hoist module READMEs into docs)
@loopback/context
what is IoC?
binding functions

**Comment by bajtos** [comment]
I don't think this is needed for our upcoming MVP release.

**Comment by dhmlau** [comment]
With #843, I believe this is done. @b-admike , good to close?
