### ISSUE TITLE
GraphQL custom endpoint issue

### ISSUE THREAD

**Issue by hadnet** [strongloop/loopback-next#7412]
I'm trying to config a custom endpoint using the @loopback/graphql package

In my applications.ts I got this:

```ts
export class MyApplication extends BootMixin(
  ServiceMixin(RepositoryMixin(RestApplication)),
) {
    //...
    this.component(GraphQLComponent);
    this.configure(GraphQLBindings.GRAPHQL_SERVER).to({
      apollo: {
          path: '/gql',
      },
      asMiddlewareOnly: true,
    });
    const server = this.getSync(GraphQLBindings.GRAPHQL_SERVER);
    this.expressMiddleware('middleware.express.GraphQL', server.expressApp);

    // Set up the custom sequence
    this.sequence(MySequence);
    //....
```

But nothing happens, I can't change the GraphQL endpoint.

Looking into the Apollo docs I see that path is in the applyMiddleware() function param object but in the graphql.server.ts I can't see any config for that, only for app:

```ts
// Create ApolloServerExpress GraphQL server
    const serverConfig: ApolloServerExpressConfig = {
      // enable GraphQL Playground
      playground: true,
      context: graphqlContextResolver,
      subscriptions: false,
      ...this.options.apollo,
      schema,
    };
    const graphQLServer = new ApolloServer(serverConfig);
    graphQLServer.applyMiddleware({app: this.expressApp}); // there is no path or applyMiddleware props here
```
Editing it to something like:
```ts
  //...
  graphQLServer.applyMiddleware({app: this.expressApp. ...this.options.apollo.applyMiddlewareProps});
  //...
```
I can change the path for Apollo Server to listen on to 'gql' (default is '/graphql').
 
I don't know if this is a bug or issue but I read all the GraphQL doc (https://loopback.io/doc/en/lb4/GraphQL.html#configure-graphqlserver) but the server config section is very confusing (you guys, please, need to improve that section), lacks context in code examples and there is nothing about how to custom the GraphQL endpoint.

**Comment by raymondfeng** [comment]
@hadnet Can you try the following? Please note that components are instantiated When it's bound. 

```ts
this.configure(GraphQLBindings.GRAPHQL_SERVER).to({
      apollo: {
          path: '/gql',
      },
      asMiddlewareOnly: true,
    });
this.component(GraphQLComponent);
```

**Comment by raymondfeng** [comment]
I also added the options to configure graphql path.

**Comment by hadnet** [comment]
Thanks, man. When will this feat be available?
