### ISSUE TITLE
Repository mixin should add `app.dataSource` API

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#743]
I am not entirely sure if it's a good idea to register data-sources for DI/IoC consumption, but if we agree that's the way to go, then I think there should be `app.dataSource` API for that.

See https://github.com/strongloop/loopback4-example-getting-started/pull/7/files#diff-8f42631f8d7d8cbaf47074d3ea5536d1R36

```diff
- this.bind('datasources.db').to(datasource);
+ this.dataSource(datasource);
```

## Acceptance Criteria
- [x] Add code to allow bindings
- [x] Write tests
- [x] Update examples accordingly
- [x] Update TSDocs

**Comment by truongminh** [comment]
@bajtos May I work on this issue?

**Comment by bajtos** [comment]
> May I help on this issue?

@truongminh of course! Thank you for opening #966 😄

**Comment by bajtos** [comment]
Closing as done, thank you @truongminh for making this happen!

**Comment by truongminh** [comment]
You are welcomed.
