### ISSUE TITLE
[API-Explorer] Create a self-hosted component

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#749]
## Story
As a LoopBack4 user, I would like to test out my API endpoints on a self-hosted server.

## Acceptance Criteria
TBD

**Comment by bajtos** [comment]
Here is the tricky part: right now, the REST transport does not allow controllers to control the response content type, there is no way how to implement our own variant of Express' [server-static middleware](https://www.npmjs.com/package/serve-static). We need to figure this out as a pre-requisite.

**Comment by bajtos** [comment]
Closing as a duplicate of #559
