### ISSUE TITLE
Use OpenAPI v3 spec to coerce primitives in query, path and headers

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#750]
## Story
As a LoopBack4 user, I would like to be able to validate primitive types in my http request.

connected to #118

## Acceptance Criteria
- [x] Coerce incoming query string, path and header inputs into strings, numbers, booleans, Dates
  - [x] Do not coerce timestamps (Unix timestamps in milliseconds) 
- [x] Validate only that the output is correct for the chosen type

## Notes

We should consider using either [strong-remoting](https://github.com/strongloop/strong-remoting/tree/39aef9d4e4b6ad9cdb92de18a288887160d76b77/lib/types) or [AJV](https://github.com/epoberezkin/ajv/blob/master/COERCION.md) to perform the coercion

`packages/example-getting-started/src/controllers/todo.controller.ts` should be updated to remove the manual coercion once this issue is fixed! (Also update the related docs for the tutorial!)

Coercion is closely related to validation, see #118

A list of coming PRs for edge cases:
- [x] boolean
  - [comment1](https://github.com/strongloop/loopback-next/pull/1370#discussion_r192676145)
- [x] date
  - [comment1](https://github.com/strongloop/loopback-next/pull/1370#discussion_r192674150)
- [x] buffer
- [x] integer

Edge cases that should apply to all types:

- An empty string
- Value not provided (header missing, no query string argument with the given name, etc.)
- An invalid value

**Comment by bajtos** [comment]
@kjdelisle and me agreed to remove Validation from MVP scope. The current validation performed by Juggler should be good enough for CRUD applications which are our MVP target.

**Comment by virkt25** [comment]
`packages/example-getting-started/src/controllers/todo.controller.ts` should be updated to remove the manual coercion once this issue is fixed! (Also update the related docs for the tutorial!).

**Comment by jannyHou** [comment]
A list of coming PRs for edge cases:
- [ ] boolean
  - [comment1](https://github.com/strongloop/loopback-next/pull/1370#discussion_r192676145)
- [ ] date
  - [comment1](https://github.com/strongloop/loopback-next/pull/1370#discussion_r192674150)

keep adding more types

**Comment by bajtos** [comment]
@jannyHou in addition to the list you have above, there should be a test for each OAS type to verify how the following input values are handled:

- An empty string
- Value not provided (header missing, no query string argument with the given name, etc.)
- An invalid value

**Comment by jannyHou** [comment]
closing it after 2 PRs checked in
