### ISSUE TITLE
[OpenAPI] Support top-down consumption of full v3 spec

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#751]
## Story
As a LoopBack4 user, I would like to be able to use my OpenAPI spec to scaffold a LoopBack4 application

## Acceptance Criteria
TBD

**Comment by shenghu** [comment]
@shimks will loopback 4 support openapi 3 initially in later release?

**Comment by shimks** [comment]
@shenghu It is going to be supported in the later releases. We are currently hashing out the plans for the degree for its support

**Comment by jannyHou** [comment]
Hi @shenghu thank you for being interested in this feature, we have a spike story for it https://github.com/strongloop/loopback-next/issues/739, and will keep updating our plan in the comment.

**Comment by bajtos** [comment]
I think this is a duplicate of https://github.com/strongloop/loopback-next/issues/725, what do you think @jannyHou and @kjdelisle ?

**Comment by jannyHou** [comment]
hmm...yeah looks like #725 was created earlier and contains more details :-p

**Comment by dhmlau** [comment]
in that case, can we close it as dup of #725?

**Comment by shenghu** [comment]
#725 doesn't indicate to support openapi 3.  Although we still call swagger 2.0, etc. But the whole swagger spec is renamed as OpenAPI. I'm fine #725 can cover this requirement. Just hope this can be support as early as possible.

**Comment by bajtos** [comment]
Closing in favor of #1882.
