### ISSUE TITLE
[OpenAPI] Provide validator for v3 spec

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#754]
## Story
As a LoopBack4 user, I would like automatic validation for my OpenAPI spec.

## Acceptance Criteria
TBD

## Other Details
The types/interfaces exist here:
https://github.com/metadevpro/openapi3-ts

**Comment by dhmlau** [comment]
@shimks @jannyHou @bajtos , saw #301 and #1014 also mentioned `openapi3-ts`.  Any duplicates?

**Comment by bajtos** [comment]
This can be closed as done, testlab's `validateApiSpec` was updated to check OpenAPI Spec v3 as part of Janny's work on v2->v3 update (IIRC).

https://github.com/strongloop/loopback-next/blob/8d2d8bb5a8373e5ed149d86ba4ff337015b23f2c/packages/testlab/src/validate-api-spec.ts#L6-L20

**Comment by shimks** [comment]
Looking at the test that it's used in, it seems to only validate the default API spec generated from `createEmptyApiSpec`. Shouldn't we introduce some tests that runs against a spec that's been built from the decorators in `openapi-v3`?. This is something we can test for in `example-getting-started`

**Comment by shimks** [comment]
@bajtos I think we need to groom the task a bit before we _do_ add in validation. If I was to be working on the task, I wouldn't really know where to create the test and what schema I should be validating.

My proposal is that we repurpose #181 for this task
