### ISSUE TITLE
Validation and Type Conversion (DP3)

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#755]
## Epic
As a LoopBack4 user, I would like to have validation for my server requests and responses as defined in my spec.

## More information
- Validation and type-conversion of input arguments in the REST layer
   - query/path/headers/form parameters
   - request body - content-type, e.g. application/json, application/xml, 
   - validate against:
      - whether the property exists
      - simple type vs complex type (combined validation of various properties)

- Validation and type-conversion for Model and database tier 

## DP3 scope

- [x] deserialize HTTP parameters based on OpenAPI spec - see #750
- [ ] minimal validation of input parameters at REST layer - see #118

## Out of scope
- extensibility of coercion and validation - see #1343

**Comment by jannyHou** [comment]
We have two more stories left for this epic:

- Leveraging ajv to validate input parameters from requestBody: https://github.com/strongloop/loopback-next/issues/118
- Add jsonDef or OpenAPI schema for internal types in `@loopback/repository`: https://github.com/strongloop/loopback-next/issues/1112

**Comment by jannyHou** [comment]
We have two more stories left for this epic:

- Leveraging ajv to validate input parameters from requestBody: https://github.com/strongloop/loopback-next/issues/118
- Add jsonDef or OpenAPI schema for internal types in `@loopback/repository`: https://github.com/strongloop/loopback-next/issues/1112

cc @bajtos

**Comment by bajtos** [comment]
Thank you @jannyHou.

> Add jsonDef or OpenAPI schema for internal types in @loopback/repository: #1112

We have removed this task from DP3 two weeks ago, I'll move it to the GA Epic for Validation/Coercion.

**Comment by dhmlau** [comment]
Closing as done.
