### ISSUE TITLE
OpenAPI Epic - MVP

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#756]
## Epic

As a LoopBack 4 user, I would like to leverage the OpenAPI specification when using the framework. I'd like to see:
- bottom-up generation of OpenAPI spec files
- validator for OpenAPI spec file

Additionally, I think we should:
- Extract the OpenAPI decorators and routing from `@loopback/rest` into their own module.

**Comment by dhmlau** [comment]
Closing as all the items are done.
