### ISSUE TITLE
Describe how to use Shot Request/Response mocks

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#760]
See https://github.com/strongloop/loopback4-example-rpc-server/pull/1#discussion_r150798546 for background information.

We should improve testlab's README to show how to use Shot and `mockResponse` for mocking/stubbing HTTP request and response objects.

## Acceptance criteria

Expand the `shot` section of testlab's README ([packages/testlab/README.md#shot](https://github.com/strongloop/loopback-next/blob/master/packages/testlab/README.md#shot)) to explain users:

 - [ ] How to create a mocked/stubbed HTTP request and use it in places that require only the request object (without the response object; these places are typically dealing with request parsing).
 - [ ] How to create a mocked/stubbed HTTP request and response, how to `await` the response (wait until the request is handled) and how to inspect the response returned by the server.

Each topic should include a short code snippet to illustrate the intended usage.

**Comment by dhmlau** [comment]
@bajtos , assigned this to you for grooming.  Could you please add the acceptance criteria? thanks.

**Comment by bajtos** [comment]
> assigned this to you for grooming. Could you please add the acceptance criteria? thanks.

@dhmlau done

**Comment by b-admike** [comment]
We need to decide the http library we are going to use going forward from https://github.com/strongloop/loopback-next/issues/1071#issuecomment-380241710 and https://github.com/strongloop/loopback-next/issues/1255 and whether or not it's compatible with `Shot`.

**Comment by bajtos** [comment]
FWIW, `Shot` is a stub for the HTTP request/response objects as provided by Node.js core. I'd expect any framework-specific request/response objects to extend these builtin objects, therefore `Shot` stubs may be still useful. We'll see!

**Comment by b-admike** [comment]
Yeah I think we all agree that they'd be useful, it's just the compatibility we'd like to figure out (which, like you said, should not be an issue since they extend from the core).

**Comment by b-admike** [comment]
I was looking around and it looks like `Shot` has 8 dependents looking from npmjs. One of its dependents, `artificial`, ports it to work with Express:
```
Inject fake HTTP request/response into an Express server. This is a port of hapi's shot module, adapted to work with Express. artificial allows fake responses to be injected into a server without first binding to a port. This simplifies testing.
```
link: https://www.npmjs.com/package/artificial
So it might not work right off the bat with Koa as well.
