### ISSUE TITLE
'NodeJS\getting-started\node_modules\.bin\' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by jippy89** [strongloop/loopback-next#7600]
## Steps to reproduce
Follow the [Getting Started](https://loopback.io/doc/en/lb4/Getting-started.html) tutorial.

## Current Behavior
```
> getting-started@0.0.1 prestart C:\Users\MyUsername\Documents\Projects\Udemy\Loopback 4 Modern ways to build APIs in Typescript & NodeJS\getting-started
> npm run rebuild


> getting-started@0.0.1 rebuild C:\Users\MyUsername\Documents\Projects\Udemy\Loopback 4 Modern ways to build APIs in Typescript & NodeJS\getting-started
> npm run clean && npm run build


> getting-started@0.0.1 clean C:\Users\MyUsername\Documents\Projects\Udemy\Loopback 4 Modern ways to build APIs in Typescript & NodeJS\getting-started
> lb-clean dist *.tsbuildinfo .eslintcache

'NodeJS\getting-started\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Users\MyUsername\Documents\Projects\Udemy\@loopback\build\bin\run-clean.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! getting-started@0.0.1 clean: `lb-clean dist *.tsbuildinfo .eslintcache`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the getting-started@0.0.1 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MyUsername\AppData\Roaming\npm-cache\_logs\2021-06-29T12_55_32_296Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! getting-started@0.0.1 rebuild: `npm run clean && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the getting-started@0.0.1 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MyUsername\AppData\Roaming\npm-cache\_logs\2021-06-29T12_55_32_382Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! getting-started@0.0.1 prestart: `npm run rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the getting-started@0.0.1 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MyUsername\AppData\Roaming\npm-cache\_logs\2021-06-29T12_55_32_553Z-debug.log
```

## Expected Behavior

The app starts like what's in the documentation

## Link to reproduction sandbox

Just follow the guide

## Additional information
Windows 10
Platform: win32
Arch: x64
Node version: 12.18.0

Packages:
@loopback/boot@3.4.1
@loopback/core@2.16.1
@loopback/repository@3.7.0
@loopback/rest@9.3.1
@loopback/rest-explorer@3.3.1
@loopback/service-proxy@3.2.1

## Related Issues

https://github.com/JeffreyWay/laravel-mix/issues/151

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

Tbh, this seems like an issue only related to Windows, since in the related issue I just mentioned.

**Comment by jippy89** [comment]
I'm a bit concerned about this line
```javascript
Error: Cannot find module 'C:\Users\MyUsername\Documents\Projects\Udemy\@loopback\build\bin\run-clean.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
Since the correct folder should be `C:\Users\MyUsername\Documents\Projects\Udemy\ **Loopback 4: Modern ways to build APIs in Typescript & NodeJS\getting-started** \@loopback\build\bin\run-clean.js`, instead of just `C:\Users\MyUsername\Documents\Projects\Udemy\@loopback\build\bin\run-clean.js`

**Comment by jippy89** [comment]
Silly me. Problem solved, it's really is what I just mentioned. It seems that the spaces in "Loopback 4: Modern ways to build APIs in Typescript & NodeJS" what makes the problem. Just started a new project in a different directory, "C:\Users\Documents\Projects\getting-started\lb4-getting-started" and it works.

**Comment by Rajagopal37** [comment]
Microsoft Windows [Version 10.0.22621.3155]
(c) Microsoft Corporation. All rights reserved.

D:\2 Information Technology\1 Guvi Zen\00 Zen-Git Clone\Rajagopal-fsd\Tasks\05_React Tasks\React_Day_3_React_hooks_&_states\react_day_3_hooks_state>npm run dev

> react_day_3_hooks_state@0.0.0 dev
> vite

'_states\react_day_3_hooks_state\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'D:\2 Information Technology\1 Guvi Zen\00 Zen-Git Clone\Rajagopal-fsd\Tasks\05_React Tasks\vite\bin\vite.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.11.1

**Comment by MACOOF** [comment]
Same Error As @Rajagopal37 

C:\Users\sarthak\Desktop\web development\cohort-2.0\code\10-CustomHooks-&-TS\Hello\CustomHooks>npm run dev

> customhooks@0.0.0 dev
> vite

'-TS\Hello\CustomHooks\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module 'C:\Users\sarthak\Desktop\web development\cohort-2.0\code\vite\bin\vite.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.13.1

Is There Any Solution To This??

**Comment by MACOOF** [comment]
Found The Solution For This Type Of Error :

Do Not Use  Special Symbols in Folder Name In my case foldername:"10-CustomHooks-&-TS" => '&' my Case and in @Rajagopal37 foldername:React_Day_3_React_hooks_&_states =>'&' Because of this npm run dev was not working

**Comment by Dhinu-2001** [comment]
> Found The Solution For This Type Of Error :
> 
> Do Not Use Special Symbols in Folder Name In my case foldername:"10-CustomHooks-&-TS" => '&' my Case and in @Rajagopal37 foldername:React_Day_3_React_hooks_&_states =>'&' Because of this npm run dev was not working

It worked! You earned my respect. auro+++

**Comment by fayssalEL-ANSARI** [comment]
> Found The Solution For This Type Of Error :
> 
> Do Not Use Special Symbols in Folder Name In my case foldername:"10-CustomHooks-&-TS" => '&' my Case and in @Rajagopal37 foldername:React_Day_3_React_hooks_&_states =>'&' Because of this npm run dev was not working

for me I had a folder named "R&D" that was causing the problem, changed it to "RandD" 👍
