### ISSUE TITLE
Loopback file upload with postman

### ISSUE THREAD

**Issue by VishalSingh28** [strongloop/loopback-next#7607]
How we can upload file with the help of the postman because I getting failed with status code 500. MulterError: Unexpected field
But I am able to upload file with the help of loopback 

Please suggest how we can send file to loopback  with the help of postman

![postman](https://user-images.githubusercontent.com/41333057/124470985-f2f89e00-ddb9-11eb-9670-7e25604cbaa8.PNG)
![postman1](https://user-images.githubusercontent.com/41333057/124470989-f4c26180-ddb9-11eb-9f71-86c85434438f.PNG)

first i am using simple form data and after getting error i am using header request type

**Comment by achrinza** [comment]
Closing in favour of https://github.com/strongloop/loopback-next/discussions/7606
