### ISSUE TITLE
Static file serve in loopback 4

### ISSUE THREAD

**Issue by conqsys** [strongloop/loopback-next#764]
I'm using express for serving static folder using loopback 4 like

 let dir = path.join(directory)
    server.use(express.static(dir));
    server.listen(3001);
But my application is running on the 4200 port and server.listen(3001) creates A new port but i want to do the same on 4200 If i'm giving server.listen(4200) then that not start because its can't run on two server on same port

Is that possible to serve file on existing port OR ANY METHODE INBUILD IN LOOPBACK 4 LIKE THAT LOOPBACK 3

**Comment by shimks** [comment]
Hi @conqsys, the feature for LoopBack's REST component to support static file hosting is currently being planned, and you can keep a track of its progress in this issue: https://github.com/strongloop/loopback-next/issues/691.
