### ISSUE TITLE
Not able to do build production

### ISSUE THREAD

**Issue by shashi97** [strongloop/loopback-next#767]
I have a query that should be on discussion page but just asking here

I have completed my app in LB4 and the next phase production i run a command npm run build but its build in dist file with .map files i think that is not production build so what i need to do there is no proper documentation is available so i'm asking here

thanks in advance

**Comment by raymondfeng** [comment]
Please customize the `tsconfig.json` to set:
```
"compilerOptions" {
  "sourceMap": false
}
```
See https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by shashi97** [comment]
But its only not making map file and not reproduce production build.
Like i don't know how production build will use and how i host on windows server with pm2 module
thanks

**Comment by raymondfeng** [comment]
What do you expect the production build look like? The TypeScript files have been transpiled into plain JavaScript files. You can use `npm start` or `node .` to run the app.

**Comment by shashi97** [comment]
Yes but when goes to host dist folder on windows server and run npm start command its throwing error that :-

E:\Projects\property-portal\New folder\dist>npm start

> labinc@0.0.1 start E:\Projects
> ng serve --host 0.0.0.0 --disable-host-check

node_modules appears empty, you may need to run `npm install`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! labinc@0.0.1 start: `ng serve --host 0.0.0.0 --disable-host-check`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the labinc@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cqs-shashi\AppData\Roaming\npm-cache\_logs\2017-12-01T12_45_06_557Z-debug.log

E:\Projects\property-portal\New folder\dist>
