### ISSUE TITLE
Boot Epic - MVP

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#779]
## Epic

As a loopback4 user, I would like the framework to provide bootstrapping capabilities to help me with automatically associating artifacts and configuration with my application.

**Comment by kjdelisle** [comment]
Reopening; the other epic is solely about reading markup like JSON/YAML to create artifacts.

**Comment by dhmlau** [comment]
Closing this epic as #780 and #781 in this epic are done.
