### ISSUE TITLE
[Boot] Automatic configuration of controllers in Application

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#780]
## Story

As a LoopBack 4 user, I would like all of the controller files I place (or generate!) in `./src/controllers` to automatically be associated with my Application so that I don't have to type `app.controller(...)` over and over again.

## Acceptance Criteria
- [x] Must read all files of the format `*.controller.js` from the `controllers` directory
- [x] Must associate all of the controllers exported classes with the application using the `.controller` function.
  - [x] Take each exported class from the `*.controller.js` file (subject to change based on user feedback)
- [x] There should be a blog post informing users that this is now live (once this change has been released!), and explain how it works.
- [x] Docs on loopback.io
- [x] Refactor/update example code (loopback4-example-getting-started)
- [x] Update app template(s) in CLI to use `@loopback/boot`

## Notes
- Extensibility is out of scope; it does not need to accommodate anything beyond the current story for Controllers.

**Comment by jonathan-casarrubias** [comment]
+1

**Comment by virkt25** [comment]
Done :)
