### ISSUE TITLE
[Boot] Automatic configuration of repositories in Application 

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#781]
blocked by #780

## Story
As a LoopBack 4 user, I would like all of the repository files I place (or generate!) in ./src/repositories to automatically be associated with my Application so that I don't have to type app.repository(...) over and over again.

## Acceptance Criteria
- [x] If the Application is not using the RepositoryMixin, ignore the contents of `/src/repositories`.
- [x] Must read all files of the format *.repository.js from the `repositories` directory
- [x] Must associate all of the repository exported classes with the application using the .repository function.
- [x] Take each exported class from the *.repository.js file (subject to change based on user feedback)
- [ ] There should be a blog post informing users that this is now live (once this change has been released!), and explain how it works.
- [x] Docs on loopback.io
- [x] Refactor/update example code (loopback4-example-getting-started)
- [x] Check that app template(s) in CLI already use `@loopback/boot` (and if not, fix this)

**Comment by dhmlau** [comment]
FYI - please check with @raymondfeng when picking up this task.  Some of the ideas in boot for LB3 can be reused.

**Comment by virkt25** [comment]
As per a discussion with @kjdelisle, the blog for @loopback/boot will cover the Repository Booter since this alone doesn't provide enough content for a blog post.

PRs landed. Closing this.
