### ISSUE TITLE
[Schema] OpenAPI Schema to TypeScript

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#785]
## Story
As a LoopBack 4 user, I would like to convert OpenAPI schema objects into TypeScript classes.

## Acceptance Criteria
- Find a complete OpenAPI Schema to TypeScript converter

OR

- Use an existing library for converting JSON Schema to TypeScript classes
- Extend/enhance/fork this library to accommodate OpenAPI instead.

THEN

- Plug it into `@loopback/openapi-spec` ???

**Comment by raymondfeng** [comment]
FYI - https://github.com/bcherny/json-schema-to-typescript

**Comment by virkt25** [comment]
not stale, related to https://github.com/strongloop/loopback-next/pull/1399
