### ISSUE TITLE
App generator is adding copyright statements to code

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#793]
# Description/Steps to reproduce
Generate an application using `@loopback/cli`'s `lb4` command.
Note that all of the code generated has copyright statements
# Link to reproduction sandbox
N/A (run the lb4 command see for yourself)

# Expected result
Code generated for other developers should not have license statements relating to IBM (or anyone!)
Remove the copyright headers from the templates.

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/loopback-next/pull/774
