### ISSUE TITLE
Invoke controller methods with dependency injection for openapi decorated parameters

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#808]
# Description/Steps to reproduce

We describe controller methods to serve REST operations as follows:

```ts
export class MyController {
  @get('/greet')
  greet(
    @param.query.string('message') message: string, 
    @param.header.string('X-CLIENT-ID') user: string,
  ) {
    return `${user} ${message}`;
  }
}
```

The current implementation inspects the method/parameter metadata, parses the HTTP request to extract the argument values for the method, and invoke the method.

With our support of method dependency injection, we should turn it around to inject parameters.

1. Add an `injection` point for each decorated parameter. It can be achieved by calling `inject` inside the `@param` decorator function. A custom `resolve` function is set up to parse the HTTP request when injection happens. This allows us to defer the HTTP parsing to the final stage and provides flexibility such as streaming and calculation of parameter values.

2. At runtime, when an HTTP request is resolved to a given controller method, it can simply invoke the target method with `invokeMethod` from `@loopback/context`.

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by bajtos** [comment]
Implemented via #903.
