### ISSUE TITLE
Support virtual properties

### ISSUE THREAD

**Issue by arash01** [strongloop/loopback-next#827]
Hi,
I'm trying to add a virtual property by adding @property({store: {in: false, out: false}}) decorator, however I'm getting " Error: ER_BAD_FIELD_ERROR: Unknown column 'XXXX' in 'field list' "

**Comment by arash01** [comment]
This is still happening :( Is there any workaround for this issue?

**Comment by bajtos** [comment]
@arash01 thank you for reporting this issue.

To my knowledge, we don't support virtual properties yet. Where did you find the information that led you to the impression that `{in: false, out: false}` should work?

**Comment by arash01** [comment]
I've seen in the source code, also it was a similar discussion earlier.
https://github.com/strongloop/loopback-next/blob/06c787b01992c878b5aafb25a53c2cdbbeb5df42/packages/repository/src/model.ts#L19-L28
