### ISSUE TITLE
[Repository] Add "NOT IN" to where operators

### ISSUE THREAD

**Issue by arash01** [strongloop/loopback-next#847]
In my sample project I faced with a problem where I need to use NOT IN statement in sql filter. You may call it "ninq"

**Comment by kjdelisle** [comment]
@arash01 I've added some labels to this item. As far as I know, we haven't yet planned what form the filters will take in LoopBack 4. They may well follow the current format (and then we can add something like this easily), or it might change entirely.

**Comment by kjdelisle** [comment]
@raymondfeng Are we still keeping this sort of filter syntax?
