### ISSUE TITLE
[Docs]: How to create and register a custom sequence action (e.g. send)

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#863]
## Overview

We have removed "Configurable response types/formats #436" from MVP because custom responses can be produced via a custom send action. However, our documentation does not explain how to implement such custom send actions or how to register them in an application.

We need to do better! 😄 

See https://github.com/strongloop/loopback-next/issues/436#issuecomment-349073924, https://github.com/strongloop/loopback-next/issues/436#issuecomment-349329054 and https://github.com/strongloop/loopback-next/issues/436#issuecomment-349387123. I am cross-posting the content of the last comment below.

## Acceptance Criteria
- [x] Take the snippet below and convert it into documentation describing the creation of custom sequences
- [x] Update loopback.io with this documentation (http://loopback.io/doc/en/lb4/Sequence.html#using-sequence-actions)
---

Registering your custom send action involves injecting on the `RestBindings.SequenceActions.SEND` key with a custom Provider for Send.

**application.ts**
```ts
export class YourApp extends RepositoryMixin(Application) {
  constructor() {
    super();
    // Assume your controller setup and other items are in here as well.
    this.bind(RestBindings.SequenceActions.SEND).toProvider(CustomSendProvider);
  }
```

**custom-send-provider.ts**
```ts
import { Send } from "@loopback/rest";
import { Provider, BoundValue } from "@loopback/context";
import { writeResultToResponse } from "@loopback/rest";

export class CustomSendProvider implements Provider<BoundValue>{
  value(): Send | Promise<Send> {
    return writeResultToResponse; // Replace this with your own implementation.
  }
}
```

If you're implementing _multiple servers_ in your application, binding this key at the Application-level context will make that binding the default for all of the servers connected to it. This means that if you wanted different custom providers for different RestServer instances, you'd want to perform those bindings elsewhere (like in an async override of the `start` method).

In this example, PrivateSendProvider might allow stack traces to be returned via the response, whereas PublicSendProvider will not.

**in application.ts**
```ts
async start() {
   const publicServer = await this.getServer('public');
   const privateServer = await this.getServer('private');
   publicServer.bind(RestBindings.SequenceActions.SEND).toProvider(PublicSendProvider);
   privateServer.bind(RestBindings.SequenceActions.SEND).toProvider(PrivateSendProvider);
   await super.start(); // Don't forget to call start!
}
```

**Comment by kjdelisle** [comment]
I am removing the "good first issue" label, since I don't think that new contributors should be writing documentation for the framework (documentation that we should've written, anyhow).

Even though I've essentially written it in the form of that reply, I think it's a good general rule to only ask for docs from contributions made by those community members, rather than to supplement _our_ work.

**Comment by bajtos** [comment]
> I am removing the "good first issue" label, since I don't think that new contributors should be writing documentation for the framework (documentation that we should've written, anyhow).
>
> Even though I've essentially written it in the form of that reply, I think it's a good general rule to only ask for docs from contributions made by those community members, rather than to supplement our work.

I disagree with you. There are many ways how to contribute to an open-source project, writing documentation is one of them. Because this issue does not require (almost) any coding skills, it's a great task allowing people to start contributing to our project even if they are not comfortable making code-related changes yet.

Please note that "good first issue" does not mean that we are asking anybody to contribute documentation they don't want to write. Instead, it's an opportunity for newcomers to help us in a way that may be easier for them in the beginning. If nobody shows up, then this issue should be added to our Sprint backlog so that we can make the necessary documentation improvements ourselves.

Further reading:

https://opensource.guide/how-to-contribute/#you-dont-have-to-contribute-code
> A common misconception about contributing to open source is that you need to contribute code. In fact, it’s often the other parts of a project that are [most neglected or overlooked](https://github.com/blog/2195-the-shape-of-open-source). You’ll do the project a huge favor by offering to pitch in with these types of contributions!
> (etc., see the linked content)

https://opensource.guide/how-to-contribute/#do-you-like-to-write:
> Do you like to write?
> - Write and improve the project’s documentation
> - Curate a folder of examples showing how the project is used
> - Start a newsletter for the project, or curate highlights from the mailing list
> - Write tutorials for the project, like PyPA’s contributors did
> - Write a translation for the project’s documentation

**Comment by kjdelisle** [comment]
To clarify, I meant what I said for this phase of the framework. I would love docs contributions once the project is a bit further along, but I wouldn't expect community members to have an idea of what kind of documentation to write to fill gaps in the current docs, because _only we know_ what it should be doing right now. :)
