### ISSUE TITLE
npm run build:watch not working with lb4 in subfolder

### ISSUE THREAD

**Issue by Tera3yte** [strongloop/loopback-next#865]
# Description/Steps to reproduce

- Create a new lb4 app
- Move everything into a subfolder (exculde only node_modules & package.json & index.js &.npmrc)
- Change scripts in package.json like: `lb-tsc -p subfolder` and `lb-tsc -p subfolder --watch` also change in subfolder/tsconfig.json "extends" from "./node_modules/..." to "../node_modules/..."
- run `npm run build` -> will work and create dist-dir on root-dir of the project
- run `npm start` -> goto localhost:3000/ping -> will work
- run `npm run build:watch` -> will **not** work, even the console.log messages are not shown 

# Expected result
run `npm run build:watch` should work if lb4 is in an subdir 

# Additional information
```
npm run build:watch

> test@1.0.0 build:watch /home/user/project/lb4-test
> lb-tsc -p subfolder --watch

12:09:29 - Compilation complete. Watching for file changes.
```

**Comment by shimks** [comment]
@Tera3yte Thanks for taking an interest in LoopBack! Please post the content of your `package.json` so that we can better assist you.

**Comment by Tera3yte** [comment]
@shimks 

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "test",
  "keywords": [
    "loopback-application",
    "loopback"
  ],
  "main": "index.js",
  "engines": {
    "node": ">=8"
  },
  "scripts": {
    "build": "lb-tsc -p subdir",
    "build:watch": "lb-tsc -p subdir --watch",
  },
  "repository": {
    "type": "git"
  },
  "author": "",
  "license": "MIT",
  "files": [
    "README.md",
    "index.js",
    "index.d.ts",
    "dist",
    "dist6"
  ],
  "dependencies": {
    "@loopback/context": ">=4.0.0-alpha.18",
    "@loopback/core": ">=4.0.0-alpha.20",
    "@loopback/rest": ">=4.0.0-alpha.7",
    "@loopback/openapi-v2": ">=4.0.0-alpha.2"
  },
  "devDependencies": {
    "@loopback/build": ">=4.0.0-alpha.4",
    "@loopback/testlab": ">=4.0.0-alpha.13",
    "@types/mocha": "^2.2.43",
    "mocha": "^4.0.1"
  }
}```

**Comment by shimks** [comment]
@Tera3yte `npm run build:watch` seems to be working fine for me. Here is the console output that I'm getting when I make changes to a file.

```shell
lb-tsc -p sub/ --watch

10:15:13 - Compilation complete. Watching for file changes.


10:15:17 - File change detected. Starting incremental compilation...


10:15:18 - Compilation complete. Watching for file changes.
```

**Comment by shimks** [comment]
@Tera3yte `npm run build:watch` seems to be working fine for me. Here is the console output that I'm getting when I make changes to a file.

```shell
lb-tsc -p sub/ --watch

10:15:13 - Compilation complete. Watching for file changes.


10:15:17 - File change detected. Starting incremental compilation...


10:15:18 - Compilation complete. Watching for file changes.
```

**Comment by bajtos** [comment]
Closing as stale. Feel free to reopen if the problem still persists and you can provide additional information to help us reproduce the problem.
