### ISSUE TITLE
Remove cis-jenkins and PR Linter from loopback-next

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#878]
## Overview

PR Linter isn't necessary since GitHub will already tell you if your PRs need rebasing, and cis-jenkins isn't necessary since we're using Travis and AppVeyor for our CI runs.

## Acceptance Criteria
- [x] Unwire the cis-jenkins and PR Linter hooks from this repository

**Comment by virkt25** [comment]
`cis-jenkins` is at times slower than all other systems (like right now, I'm waiting for it) ... Appveyor, Coveralls, Travis are all done. Any reason to keep Jenkins around? 

cc: @strongloop/sq-lb-apex @raymondfeng @bajtos

**Comment by raymondfeng** [comment]
@rmg Are there extra benefits that we are getting from Jenkins?

**Comment by rmg** [comment]
The original reasons for running private CI for loopback were:
 - test on platforms not supported by available services
 - pre-release integration testing between dependencies

It seems like the value of those may have diminished enough over time that they are no longer worth the maintenance burden.

I think it is, ultimately, up to the Loopback project leaders to decide.

**Comment by bajtos** [comment]
> pre-release integration testing between dependencies

I think this may be still useful. For example, when we make changes in loopback-next, it would be great to run CI in loopback4-example-microservices, loopback-extension-grpc, etc. to make sure we are not breaking downstream consumers. Having said that, cis-jenkins does not support monorepos with multiple packages and therefore more work is required before we can have pre-release integration tests of loopback-next packages. Until that changes happen, I am fine with disabling cis-jenkins for loopback-next.

**Comment by virkt25** [comment]
`cis-jenkins` and `PR Linter` have been disabled for this repo
