### ISSUE TITLE
travis: add osx as an OS to test against

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#879]
# Description/Steps to reproduce
It is possible to use Travis to test against linux and osx. Need to update `.travis.yml` as shown here:

https://docs.travis-ci.com/user/multi-os/

**Comment by kjdelisle** [comment]
I've added a new label to describe the sort of work that should be done by us and not the greater community (it's not their problem to figure this out, IMO)

**Comment by virkt25** [comment]
Completed as part of #611
