### ISSUE TITLE
Example repos should use tsc watch

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#895]
Our old extension starter repository has a neat dev setup that enables quick red-green-refactor cycles by leveraging incremental transpilation via `tsc --watch`, see [DEVELOPING.md](https://github.com/strongloop/loopback4-extension-starter/blob/e9062ca01f9bff28d6d2ebe077cba84c242ae96e/DEVELOPING.md):

> **Visual Studio Code**
>
> - Start the build task (Cmd+Shift+B), it will run TypeScript compiler in backround, watching and recompiling files as you change them. Compilation errors will be shown in the VSCode's "PROBLEMS" window.
>
> - Execute "Test and lint" task (Cmd+Shift+T) to re-run the test suite and lint the code for both programming and style errors. Linting errors will be shown in VSCode's "PROBLEMS" window. Failed tests are printed to terminal output only.
>
> - Run `npm test` explicitly before committing your changes. This will execute the same sequence as our CI server does.

We should update our example repositories and also the empty project template used by our CLI tooling to include similar configuration for people using VisualStudio Code.

**Acceptance criteria**

 - [ ] Add `build:watch` and `test:dev` scripts to package.json, see the [starter repo](https://github.com/strongloop/loopback4-extension-starter/blob/e9062ca01f9bff28d6d2ebe077cba84c242ae96e/package.json
 - [ ] Add VS Code task configuration, see the [starter repo](https://github.com/strongloop/loopback4-extension-starter/blob/e9062ca01f9bff28d6d2ebe077cba84c242ae96e/.vscode/tasks.json). Consider adding VSCode settings file too.
 - [ ] Add `Developing.md` document explaining users our envisioned dev workflow, I think it's enough to mostly copy the contents from the [starter repo](https://github.com/strongloop/loopback4-extension-starter/blob/e9062ca01f9bff28d6d2ebe077cba84c242ae96e/DEVELOPING.md).

The steps above should be applied to all example packages and all relevant CLI project templates.

**Comment by dhmlau** [comment]
@bajtos , i think some of the description of the acceptance criteria is out of date.  Could you please update it so that the team can estimate?
also, do you think this is `good first issue`?

**Comment by bajtos** [comment]
Since almost all example repositories were either moved to our monorepo or deprecated, this story is no longer relevant. There is only one example repository outside of loopback-next, [loopback4-example-microservices](https://github.com/strongloop/loopback4-example-microservices), which is a monorepo containing multiple services, therefore `tsc --watch` is not so straightforward to set up.

Instead of modifying example repositories, it would be nice to modify our project templates used by `lb4` CLI tool to provide `tsc --watch` for developers. I'll open a new issue for that.
