### ISSUE TITLE
Setup `tsc --watch` workflow in examples and CLI project templates

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#922]
When I was working on the extension starter project, I added configuration allowing developers to avoid possibly long compilation time by leveraging `tsc --watch` mode. See [DEVELOPING.md](https://github.com/strongloop/loopback4-extension-starter/blob/e9062ca01f9bff28d6d2ebe077cba84c242ae96e/DEVELOPING.md) for the documentation.

We should apply this configuration to everything that can be used independently from our monorepo:

 - All example packages
 - CLI templates for app and extension projects

This is a follow-up task for #836.

## Acceptance criteria

Update the following places in our monorepo
 - [ ] Example packages (replace this checkbox with an up-to-date list of example packages)
 - [ ] Extension project template
 - [ ] Application project template

For each place, make the following changes:
 - Setup `build:watch` and `test:dev` scripts in `package.json` ([source](https://github.com/strongloop/loopback4-extension-starter/tree/e9062ca01f9bff28d6d2ebe077cba84c242ae96e/package.json))
 - Add `.vscode` configuration with "Watch and compile TypeScript" and "Test and lint" tasks - ([source](https://github.com/strongloop/loopback4-extension-starter/blob/e9062ca01f9bff28d6d2ebe077cba84c242ae96e/.vscode/tasks.json))
 - Add `DEVELOPING.md` file describing dev setup and workflow for developers using VS Code but also for developers using their own IDE/editor ([source](https://github.com/strongloop/loopback4-extension-starter/blob/e9062ca01f9bff28d6d2ebe077cba84c242ae96e/DEVELOPING.md))

**Comment by shimks** [comment]
@bajtos This feels like a duplicate of #1259. Could you please confirm?

**Comment by bajtos** [comment]
Yes, this looks pretty much as a duplicate of #1259, which was implemented via #1336.
