### ISSUE TITLE
Update Contrib docs to match the new reality

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#950]
[Contributing to Loopback](http://loopback.io/doc/en/contrib/index.html) is targeting our old codebases using ES5, eslint, etc. We need to upgrade these guidelines for our new stack (monorepo, TypeScript, prettier, tslint, etc.)

We need to preserve current docs for people contributing to 3.x version of LoopBack - use some sort of versioning like we have for regular docs.

**Comment by bajtos** [comment]
IMO, the documentation should explain:
 - How to configure VisualStudio code for the best experience and what plugins to install.
   - esbenp.prettier-vscode
   - eg2.tslint
   - Additional plugins I found in my VSCode which we may want to describe too:
     - christian-kohler.path-intellisense (?)
     - eg2.vscode-npm-script (?)
     - christian-kohler.npm-intellisense (?)
  - Describe TDD cycle, how to quickly re-run tests (and rebuild the solution)
  - Explain commands to run before submitting a pull request (`npm test`)
  - Explain how to reset monorepo after changing branches (maybe `npm run clean && npm run bootstrap`?)

**Comment by bajtos** [comment]
> How to configure VisualStudio code for the best experience and what plugins to install.
> - esbenp.prettier-vscode
> - eg2.tslint

See https://github.com/strongloop/loopback-next/pull/977

**Comment by dhmlau** [comment]
@bajtos , any outstanding tasks for this ticket?

**Comment by jannyHou** [comment]
@dhmlau I think comment https://github.com/strongloop/loopback-next/issues/950#issuecomment-363439043 covers the tasks in this issue.

**Comment by jannyHou** [comment]
I believe the original tasks are already finished in PR https://github.com/strongloop/loopback-next/pull/977.
Closing this issue.
Let's create a new issue to discuss updating the contribution page in loopback.io.

**Comment by bajtos** [comment]
> Let's create a new issue to discuss updating the contribution page in loopback.io.

@jannyHou Please cross-link the new issue with this old one to preserve context.

**Comment by jannyHou** [comment]
@bajtos The issue for improving the contribution page in loopback.io is: https://github.com/strongloop/loopback-next/issues/1673
