### ISSUE TITLE
TypeScript 2.7 breaks `@types/lodash`

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#959]
# Description/Steps to reproduce

Currently, a LoopBack4 app created by the CLI tool will not compile correctly due to compatibility issue with `@types/lodash` and TypeScript.

## Fix
- lock `@loopback/build` typescript version to 2.6

## Side note
- the package needs to be published; `lb-mocha` command in `build` current doesn't exist
- there should be a way to essentially do an acceptance test of physically creating an app through CLI and then trying out `npm t` and `npm start` and making sure that they don't fail.

## Comments

- this is tracked by https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23375

**Comment by shimks** [comment]
Closing since the issue seems to be fixed

**Comment by bajtos** [comment]
> lock @loopback/build typescript version to 2.6

We should find a way how to keep using the lastest TypeScript version. For example, it may be enough to upgrade some of our `@types/{module}` dependencies. If not, then we may need to copy and fix the broken `.d.ts` file as a temporary fix - see e.g. [packages/testlab/should-as-function.d.ts](https://github.com/strongloop/loopback-next/blob/a2368cee598c131a826ee42e347266c6e25ae582/packages/testlab/should-as-function.d.ts)

**Comment by shimks** [comment]
Reopening since it doesn't seem to be affecting just the apps generated by the CLI

**Comment by b-admike** [comment]
Yeah I was trying out https://github.com/raymondfeng/loopback4-example-di and this is what happened/ how I resolved it:
```
___________________    | ~/loopback/loopback4-example-di @ Biniams-MacBook-Pro (badmike)
| => npm i

> loopback4-example-di@1.0.0 prepare /Users/badmike/loopback/loopback4-example-di
> npm run build


> loopback4-example-di@1.0.0 build /Users/badmike/loopback/loopback4-example-di
> lb-tsc es2017

node_modules/@types/lodash/index.d.ts(12651,53): error TS2344: Type 'T' does not satisfy the constraint 'object'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! loopback4-example-di@1.0.0 build: `lb-tsc es2017`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the loopback4-example-di@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/badmike/.strong-registry/pre-release.cache/_logs/2018-02-06T14_41_51_016Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! loopback4-example-di@1.0.0 prepare: `npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the loopback4-example-di@1.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/badmike/.strong-registry/pre-release.cache/_logs/2018-02-06T14_41_51_051Z-debug.log
___________________    | ~/loopback/loopback4-example-di @ Biniams-MacBook-Pro (badmike)
| => npm un -g typescript
removed 1 package in 0.111s
___________________    | ~/loopback/loopback4-example-di @ Biniams-MacBook-Pro (badmike)
| => rm -rf node_modules/
___________________    | ~/loopback/loopback4-example-di @ Biniams-MacBook-Pro (badmike)
| => npm i

> loopback4-example-di@1.0.0 prepare /Users/badmike/loopback/loopback4-example-di
> npm run build


> loopback4-example-di@1.0.0 build /Users/badmike/loopback/loopback4-example-di
> lb-tsc

added 388 packages in 29.702s
```

**Comment by bajtos** [comment]
> there should be a way to essentially do an acceptance test of physically creating an app through CLI and then trying out `npm t` and `npm start` and making sure that they don't fail.

See https://github.com/strongloop/loopback-next/issues/932

**Comment by bajtos** [comment]
@b-admike @shimks I am not able to reproduce this problem. I don't have any globally-installed version of `typescript`.

Using `lb4` from the current `master` branch (e5a9ce8ca):

```
$ lb4
? Project name: foobar
? Project description: foobar
? Project root directory: foobar
? Application class name: FoobarApplication
? Select project build settings:  Enable tslint, Enable prettier, Enable mocha, Enable loopbackBuild
 [...]
$ cd foobar/
$ npm start

> foobar@1.0.0 start /private/tmp/foobar
> npm run build && node .


> foobar@1.0.0 build /private/tmp/foobar
> lb-tsc es2017

Server is running at http://127.0.0.1:3000
Try http://127.0.0.1:3000/ping
```

Strangely enough, I am seeing an older version of `tsc` installed in my project:

```
$ ./node_modules/.bin/tsc -v
Version 2.5.3
```

This looks like an issue in `typescript-json-schema`:

```
foobar@1.0.0 /private/tmp/foobar
├─┬ @loopback/build@4.0.0-alpha.13
│ ├─┬ strong-docs@1.8.0
│ │ └─┬ typedoc@0.10.0
│ │   └── typescript@2.7.1
│ └── typescript@2.7.1
└─┬ @loopback/openapi-v2@4.0.0-alpha.10
  └─┬ @loopback/repository-json-schema@4.0.0-alpha.7
    └─┬ typescript-json-schema@0.20.0
      └── typescript@2.5.3
```

However, it should not affect our use case, because we are invoking `tsc` via `lb-tsc`, which uses the correct version.

```
$ lb-tsc --version
Version 2.7.1
```

**Comment by virkt25** [comment]
Haven't run into this issue myself either. @b-admike have you tried updating `@loopback/cli` as per @shimks 's comment?

**Comment by aj-r** [comment]
Looks like this has been fixed in the latest version of lodash (4.14.103). Try running `npm install -S @types/lodash@latest` (or similar in yarn) with TS 2.7, and see if that fixes it.

**Comment by shimks** [comment]
I've been able to verify that builds from CLI generated apps no longer error out. @b-admike Could you also verify that your use case also builds correctly before the fix you applied?

**Comment by b-admike** [comment]
Yeah it's good on my end as well!

**Comment by shimks** [comment]
Closing since the issue seems to have been fixed with the latest version of lodash. Thanks @aj-r for letting us know!
