### ISSUE TITLE
Missing dependency in `example-getting-started` is not caught at compile-time

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#960]
# Description/Steps to reproduce

- `openapi-spec` used to be missing as a dependency in `example-getting-started`, but the repo ran fine even without it; there may be a build issue
- `openapi-spec` is used to provide the type definition `SchemaObject` to a openapi-v2 schema definition in `todo.model.ts`
- We may need to do an investigation as to why
- more context here: https://github.com/strongloop/loopback-next/pull/955

**Comment by dhmlau** [comment]
During the discussion with @bajtos , he thinks some part of it (if not all) might be fixed already.  @shimks, could you please verify? 
If it's not fixed, it would be a good candidate for `DP3`.  Thanks.

**Comment by shimks** [comment]
I'm ok with closing this. The schema doesn't exist anymore so it's hard to verify considering `openapi-v2` doesn't exist anymore.
