### ISSUE TITLE
LB3 logo is used when creating LB4 app

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#972]
Now that we have a new logo for LB4 (https://strongloop.com/strongblog/thanks-loopback-4-logo/), we should be using it when generating the app.  

# Current behavior
Currently, the README.md generated by the CLI tool is pointing to the LB3 logo (the green logo).  It is coming from this file: https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/project/templates/README.md. 

```
[![LoopBack](http://loopback.io/images/overview/powered-by-LB-xs.png)](http://loopback.io/)
```

# Expected result
If the README will have a LB logo, it should be the new logo.  

cc @virkt25

**Comment by virkt25** [comment]
![lb4-favicon-transparent-bg](https://user-images.githubusercontent.com/3311536/35884779-b6673b62-0b59-11e8-9ef8-92ca1c730647.png)
![loopback-4-logo-sample](https://user-images.githubusercontent.com/3311536/35884780-b678b2d4-0b59-11e8-8969-531f29952c3e.png)

Files attached if someone else takes on the task. I would recommend using the transparent-bg file. Can / should this be marked MVP + good first issue?

**Comment by virkt25** [comment]
I just realized we need a "Powered by LoopBack" version of the Logo. I've requested it from Cody and we should have that early next week.
