### ISSUE TITLE
Get rid of warning messages from `loopback-datasource-juggler` during tests

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#974]
## Description

- running `npm t` will result in a message being logged multiple times in the console
  - the full message: `A datasource has a name of "memory" while a name of "db" is specified in its settings. Please adjust your configuration so these names match. "memory" will be assigned as the actual datasource name.`
- coming from a warning message added by this PR in `loopback-datasource-juggler`: strongloop/loopback-datasource-juggler#1542

## Acceptance Criteria:
- [ ] conform the name in the settings so that the warning message does now show up (feel free to add in detailed explanation of what this fix could be)

**Comment by virkt25** [comment]
That's intentional! The warning was added recently to `loopback-datasource-juggler` via this PR: https://github.com/strongloop/loopback-datasource-juggler/pull/1542

`@loopback/repository` uses `loopback-datasource-juggler` under the hood.

The tests should be fixed so the name and config match to get rid of the warning.

**Comment by shimks** [comment]
I agree, I'll add that in as a requirement to fix this issue and change the title accordingly

**Comment by raymondfeng** [comment]
Fixed by loopback-datasource-juggler@3.15.2

**Comment by raymondfeng** [comment]
The warnings were a regression by loopback-datasource-juggler@3.15.1.

**Comment by shimks** [comment]
@raymondfeng should we consider updating in `repository/package.json` the version for `loopback-datasource-juggler`?

**Comment by raymondfeng** [comment]
`loopback-datasource-juggler@3.15.2` is a patch release. It should be picked up automatically. I don't mind enforcing it though.
