### ISSUE TITLE
Add CLI docs for generating example and extension

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#980]
From the official documentation (http://loopback.io/doc/en/lb4/Command-line-interface.html), it only has 2 commands, i.e. to generate application and controller.  Since we have 2 more commands for generating example and extensions, we need to add it to the docs.

Also, the README  (https://github.com/strongloop/loopback-next/tree/master/packages/cli) is out of date.

## Acceptance Criteria ##
Update the documentation to include all the commands we support:
- [ ] `lb4 controller`

Places to update:
- [ ] official doc - http://loopback.io/doc/en/lb4/Command-line-interface.html
- [ ] @loopback/cli README

**Comment by shimks** [comment]
`lb4 example` is covered by this PR

**Comment by dhmlau** [comment]
thanks @shimks .  updated the description.

**Comment by dhmlau** [comment]
looks like `lb4 controller` is here as well.. closing this issue now.
