### ISSUE TITLE
FAQ: Migration from LB3 to LB4, what version to use *now*?

### ISSUE THREAD

**Issue by GBeushausen** [strongloop/loopback-next#982]
How is the upgrade path for LB3 users? Will i have to completly rewrite my application? Does it make sense to start a new LB3 project at the monent? thanks.

**Comment by bajtos** [comment]
Hi @GBeushausen, thank you for raising this question. The new framework version is too incomplete yet to work on migration/upgrade path. 

You can find a high-level proposal for a migration path in my older comment https://github.com/strongloop/loopback-next/issues/485#issuecomment-323345250.

> Will i have to completly rewrite my application? 
While we would like to make migrations as easy as possible, I don't think it will be possible to automate everything. Certain amount of manual work (rewrite) will be always needed.

Does it make sense to start a new LB3 project at the monent? thanks.

**Comment by virkt25** [comment]
Added a disclaimer about the version that should be used in production to the main LoopBack 4 README. See #1147

**Comment by virkt25** [comment]
Closing as based on above comment.
