### ISSUE TITLE
Switch from strong-docs to TypeDoc for generating API documentation

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#989]
connected to https://github.com/strongloop/loopback-next/issues/874
related to #584 

## Overview

Determine the work required to migrate from strong-docs to TypeDoc as our default API documentation generator for LoopBack 4.

**NOTE**: These questions **must** be answered for the spike to be considered complete, since they determine:
- Whether or not we *can* use TypeDoc
- What sort of effort is required to switch to using it
- Whether or not the cost/benefit of doing so is not as attractive as fixing strong-docs to correctly use TypeDoc

-------------------------------------------------------------------------------------------------------------------------------
## Questions To Answer

- How will the generated TypeDoc be incorporated into our website? (Do we need to do something differently to have these docs appear on apidocs.strongloop.com?)
  - How does the current API document deployment work with strong-docs?
  - Can we simply drop in the new generated docs site as a replacement?
- Can we change the layout of the generated documentation made by TypeDoc?
  - If so, which parts are easily changed and which are not?
  - List the steps required to make these layout changes
- Can we change the theme of the generated documentation and site links (to fit our current/future site aesthetics)?
  - What are the steps that need to be taken to do this?
- Are there any gaps in the generated documentation with TypeDoc?
  - If so, list them as well as the **impact** this may have on areas of the documentation
- **What license does TypeDoc use?**
  - The default template adds a created-by message and link at the bottom of all generated pages; does the license require that we keep this?
  - Are there any other requirements to use TypeDoc?
- Can we modify the output of TypeDoc programmatically?
  - If so, what options are available to us?

**Comment by dhmlau** [comment]
As part of the spike, can we also find out if the problem in #584 will be gone too?

**Comment by raymondfeng** [comment]
FYI: strong-docs internally uses `typedoc` programatically. It parses docs.json and passes the file names to `typedoc` to create metadata constructs for TypeScript.

**Comment by raymondfeng** [comment]
I think #874 has been fixed. With that, I don't see the need to switch.

**Comment by dhmlau** [comment]
@kjdelisle , could you please take a look if we still need to do this spike, based on @raymondfeng 's comments?

**Comment by dhmlau** [comment]
@kjdelisle  ^^^

**Comment by virkt25** [comment]
Closing as no longer needed. Majority of outstanding issues have been fixed by @raymondfeng via #874
